karmada-io/karmada

hack/util.sh, pkg/descheduler/descheduler.go, pkg/estimator/client/cache.go, pkg/estimator/client/service.go, pkg/scheduler/scheduler.go
/kind feature
See <https://github.com/karmada-io/karmada/issues/2487>
Fixes #2487
NONE
```release-note
NONE
```
=> Support Deploy karmada-scheduler-estimator in Physical Machine

test/e2e/karmadactl_test.go
/kind cleanup
fix flaking-test: cordon cluster taint check
As talked in https://github.com/karmada-io/karmada/pull/2590#issuecomment-1260499581
Fixes #
```release-note
NONE
```
=> [E2E] fix flaking-test: cordon cluster taint check

pkg/util/lifted/corev1helpers.go, pkg/util/lifted/doc.go
/kind feature
There is redundant type conversion, which does not conform to the code specification
```release-note
NONE
```
=> Remove redundant type conversions

pkg/karmadactl/cmdinit/kubernetes/deploy.go
=> using helper function of client-go

pkg/scheduler/event_handler.go, pkg/scheduler/metrics/metrics.go, pkg/scheduler/scheduler_metrics_test.go
/kind cleanup
Add metrics test for scheduler.
Fixes #
None
=> Fix the issue that incomingBindingMetrics ignores the ClusterChanged event

cmd/karmada-search/OWNERS, hack/OWNERS, pkg/search/OWNERS
/kind cleanup
This PR nominates @ikaven1024 as an approver. 
He made a gorgeous contribution in previous releases.
@ikaven1024 took the reviewer role in July (#2109), the tools he built are used frequently for daily development and release.
At the last release(release-1.3) he led the effort of [Resource Proxy](https://github.com/karmada-io/karmada/blob/master/docs/proposals/resource-aggregation-proxy/README.md) and this feature now starts to be used in production environments. That's a great success. 
Fixes #
```release-note
NONE
```
/assign @ikaven1024 @liys87x @XiShanYongYe-Chang @mrlihanbo @lfbear
=> nominate ikaven1024 as approver 

README.md
=> add kubernetes1.25 compatibility for doc

docs/keps/cleanup-propagated-resources.md, docs/proposals/caching/README.md
/kind cleanup
When I read the proposal for Karmada-search and found the same noun error, it show `Karamada` or `Karamda`, this PR modified it. 
Fixes #
```release-note
NONE
```
=> fix typos in docs

test/e2e/propagationpolicy_test.go
/kind cleanup
add implicit priority E2E for pp
Fixes #
```release-note
NONE
```
=> add implicit priority E2E for pp

pkg/util/helper/override_test.go
/kind cleanup
Add ut for override.go
Part of #2579 
None
=> [UT]Add ut for override.go

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/controllers/status/workstatus_controller.go
/kind cleanup
Unify the dynamic client name for work_status_controller
Fixes #
```release-note
NONE
```
=> Unify the dynamic client name for work_status_controller

pkg/util/gclient/gclient.go
Signed-off-by: helen <helenfrank@protonmail.com>
/kind bug
Must panics on non-nil errors
Fixes #
```release-note
NONE
```
=> gclient handling programmer level errors

pkg/version/release_test.go
/kind cleanup
Add unit tests, especially for abnormal cases.
Fixes #
```release-note
NONE
```
=> Add test coverage for pkg/version/release.go

cmd/agent/app/agent.go, cmd/aggregated-apiserver/app/aggregated-apiserver.go, cmd/controller-manager/app/controllermanager.go, cmd/karmada-search/app/karmada-search.go, cmd/scheduler-estimator/app/scheduler-estimator.go, cmd/scheduler/app/scheduler.go, cmd/webhook/app/webhook.go
/kind cleanup
Now the descriptions of our components are too simplistic, and some are not even complete sentences. 
This pr complements the descriptions of all components to be able to generate documentation.
Fixes #
None
=> Add component descriptions

pkg/util/names/names_test.go
add ut function for util/name.go
**Which issue(s) this PR about**:
https://github.com/karmada-io/karmada/issues/2579
```release-note
```
=> add ut function for util/name.go

pkg/util/lifted/retain.go, pkg/util/lifted/retain_test.go
/kind bug
For serviceAccount, we don't retain that in control plane but merge that in control plane and member clusters. You can based on https://github.com/karmada-io/karmada/issues/2573#issuecomment-1256844989.
Fixes #2573 
None
=> Fix serviceaccount continual regeneration by service account controller

examples/README.md
/kind bug
While required to run the RI webhook example, MetalLB is not installed by `hack/local-up-karmada.sh`.
So this PR adds a Prequisites section that describe how to install and configure MetalLB.
It also change a script to  automatically replace the webhook @IP in webhook configuration.
Fixes #2614
I did the minimum to make it work.
To do it I mainly copied corresponding parts of `hack/pre-run-e2e.sh`.
But I think you should consider installing and configuring MetalLB with `hack/local-up-karmada.sh` as it will reduce duplicated shell code / config stuff.
Also all the TLS & certificate generation is pretty complicated and hardcoded (see for …
=> Take into account MetalLB in Resource Interpreter webhook example

pkg/scheduler/framework/runtime/registry_test.go
/kind cleanup
Add Unit Test for registry.go
```release-note
NONE
```
=> Unit Test registry.go

pkg/karmadactl/apply.go, pkg/karmadactl/karmadactl.go, pkg/karmadactl/util/factory.go
/kind feature
Fixes #
Part of [#2349](https://github.com/karmada-io/karmada/issues/2349)
Test
```shell
go run ./cmd/karmadactl/karmadactl.go --kubeconfig /etc/karmada/karmada-apiserver.config apply -f ./_tmp/nginx.yaml
namespace/test1 created
deployment.apps/nginx1 created
```
```release-note
NONE
```
=> karmadactl apply uses factory to access member cluster

examples/README.md
The customresourceinterpreter doesn't describe how to verify the functionality of InterpretStatus、InterpretHealth and AggregateStatus
Fixes #
```release-note
NONE
```
=> enhance the doc to give more description about InterpretStatus、InterpretHealth、AggregateStatus

test/e2e/overridepolicy_test.go
/kind cleanup
Part of #2641
```release-note
NONE
```
=> Add e2e for LabelsOverrider/AnnotationsOverrider

pkg/search/proxy/cache_proxy.go, pkg/search/proxy/cache_proxy_test.go, pkg/search/proxy/cluster_proxy.go, pkg/search/proxy/cluster_proxy_test.go, pkg/search/proxy/controller.go, pkg/search/proxy/controller_test.go, pkg/search/proxy/karmada_proxy.go, pkg/search/proxy/karmada_proxy_test.go, pkg/search/proxy/store/multi_cluster_cache_test.go, pkg/search/proxy/store/util_test.go
/kind cleanup
add ut for pkg/search/proxy
```release-note
NONE
```
=> [ut] add ut for proxy

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml, charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml, pkg/apis/policy/v1alpha1/override_types.go, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
The OverriderOperator description does not match the actual function
```release-note
NONE
```
=> The OverriderOperator description does not match the actual function

docs/proposals/clusterid/README.md
/kind cleanup
Refer to https://github.com/kubernetes/enhancements/pull/3508
Fixes #
```release-note
NONE
```
=> Rename id.k8s.io --> cluster.clusterset.k8s.io

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/resourceinterpreter/customizedinterpreter/customized.go, pkg/resourceinterpreter/interpreter.go
/kind cleanup
This PR cleans up the `kubeconfig` parameter from the customized interpreter.
Fixes #
```release-note
NONE
```
=> cleanup kubeconfig parameter from customized interpreter

pkg/util/helper/job_test.go, pkg/util/helper/policy_test.go
/kind cleanup
[UT]Add ut for job.go and policy.go
Part of #2579 
None
=> [UT]Add ut for job.go and policy.go

pkg/karmadactl/cmdinit/karmada/rbac.go, pkg/karmadactl/cmdinit/karmada/rbac_test.go, pkg/karmadactl/cmdinit/karmada/webhook_configuration.go, pkg/karmadactl/cmdinit/karmada/webhook_configuration_test.go, pkg/karmadactl/cmdinit/utils/rbac.go
/kind cleanup
UT: add ut for rbac.go and webhook_configuration.go
none
```release-note
none
```
=> UT: add ut for rbac.go and webhook_configuration.go 

pkg/apis/cluster/v1alpha1/events.go, pkg/controllers/cluster/cluster_controller.go
/kind cleanup
Fix a typo about TaintClusterByConditionFailed.
Fixes #
None
=> Fix a typo about TaintClusterByConditionFailed

pkg/util/selector_test.go
/kind cleanup
add ut for pkg/util/selector.go
Part #2579
```release-note
NONE
```
=> [ut] add ut for pkg/util/selector.go

hack/tools/tools.go, hack/update-mocks.sh, vendor/github.com/golang/mock/mockgen/mockgen.go, vendor/github.com/golang/mock/mockgen/model/model.go, vendor/github.com/golang/mock/mockgen/parse.go, vendor/github.com/golang/mock/mockgen/reflect.go, vendor/github.com/golang/mock/mockgen/version.1.11.go, vendor/github.com/golang/mock/mockgen/version.1.12.go, vendor/golang.org/x/mod/modfile/print.go, vendor/golang.org/x/mod/modfile/read.go, vendor/golang.org/x/mod/modfile/rule.go, vendor/golang.org/x/mod/modfile/work.go, vendor/modules.txt
/kind cleanup
Vendor `mockgen` thus people/CI can install it even in an offline environment.
See comment at : https://github.com/karmada-io/karmada/pull/2654#issuecomment-1290315810
Fixes #
```release-note
NONE
```
=> install mockgen from vendor

cmd/karmada-search/app/options/options.go, pkg/search/apiserver.go, pkg/search/controller.go
/kind cleanup
In `karmada-search` component, both `search` and `proxy` will cache the sub cluster's resource in memory, it will take much physical resource. While not both features are used for users. So I add the options to enable/disable these.
Fixes #
This shall be merged into release branches.
```release-note
`karmada-search`: users now can use `--disable-search` and `--disable-proxy` options to disable search and proxy feature (default both are enabled).
```
=> add option to disable search and proxy

go.mod, pkg/util/worker_test.go
/kind cleanup
Add Unit Test for worker.go
```release-note
NONE
```
=> Unit Test worker.go

pkg/karmadactl/describe.go, pkg/karmadactl/get.go, pkg/karmadactl/logs.go
/kind cleanup
https://karmada.io/docs/next/reference/karmadactl/karmadactl-commands/karmadactl_index/
We can see that some of the subcommands are missing descriptions, and this pr modification is missing parts
Part of https://github.com/karmada-io/karmada/issues/2665
```release-note
NONE
```
=> Add a description for the karmadactl subcommand

pkg/util/clusterrole_test.go, pkg/util/rbac.go, pkg/util/rbac_test.go, pkg/util/secret.go, pkg/util/secret_test.go, pkg/util/serviceaccount_test.go
/kind cleanup
add ut for  pkg/util/clusterrole, rbac, sercret,  secret, serviceaccount
Part #2579
```release-note
NONE
```
=> [ut] add ut for pkg/util/clusterrole, rbac, sercret,  secret, serviceaccount

pkg/karmadactl/cmdinit/utils/util.go, pkg/karmadactl/cmdinit/utils/util_test.go
/kind cleanup
`TestDownloadFile` no longer depend on internet.
Also fixes #2671.
Fixes #2671
```release-note
NONE
```
=> [ut] improve download from httptest

charts/karmada/_crds/kustomization.yaml
/kind feature
Install ResourceInterpreterCustomization CRD.
Part of https://github.com/karmada-io/karmada/issues/2371
```release-note
NONE
```
=> Install ResourceInterpreterCustomization CRD

pkg/util/cluster.go, pkg/util/cluster_test.go, pkg/util/clusterlease_test.go, pkg/util/membercluster_client_test.go
/kind cleanup
add ut for  pkg/util/cluster
Part of #2579
```release-note
NONE
```
=> [ut] add ut for cluster.go, clusterlease.go, membercluster_client.go

pkg/karmadactl/token.go
/kind cleanup
```release-note
None
```
=> fix wrong description for token commond

pkg/util/helper/binding_test.go
/kind cleanup
add ut for  pkg/util/helper/binding.go
Part of #2579
```release-note
NONE
```
=> [ut] add ut for binding.go

pkg/util/resource.go, pkg/util/resource_test.go
/kind cleanup
add ut for resource.go
Part of #2579
```release-note
NONE
```
=> add ut for resource.go

hack/tools/genkarmadactldocs/gen_karmadactl_docs.go, hack/tools/preferredimports/preferredimports.go, pkg/karmadactl/cmdinit/karmada/deploy.go, pkg/karmadactl/cmdinit/utils/format.go, pkg/karmadactl/register.go, pkg/search/proxy/framework/plugins/cluster/cluster.go, pkg/search/proxy/framework/plugins/cluster/cluster_test.go, pkg/webhook/interpreter/http.go
/kind cleanup
Please see https://golang.org/doc/go1.16#ioutil
Fixes #
```release-note
NONE
```
=> replace the ioutil by the os and io

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml, charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml, pkg/apis/policy/v1alpha1/override_types.go, pkg/generated/openapi/zz_generated.openapi.go, pkg/util/overridemanager/imageoverride_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Add UT for imageoverride

pkg/util/helper/cache_test.go, pkg/util/helper/mcs.go, pkg/util/helper/mcs_test.go
/kind cleanup
Add ut for  pkg/util/helper/cache.go, mcs.go;
And improve DeleteEndpointSlice
Part of #2579
```release-note
NONE
```
=> [ut] add ut for cache.go, mcs.go, and improve DeleteEndpointSlice

pkg/estimator/server/estimate.go
/kind bug
Fixes #
```release-note
NONE
```
=> fix bugs of nodeMaxAvailableReplica

pkg/detector/compare.go, pkg/detector/compare_test.go, pkg/detector/detector.go
/kind cleanup
Add ut for policy priority.
Fixes #
```release-note
NONE
```
=> add ut for policy priority

README.md
/kind cleanup
Add code coverage badge to provide quick insight.
Preview: https://github.com/RainbowMango/karmada/blob/e97e9f9762b670ec30f06191b13a10b87768e54d/README.md
Fixes #
```release-note
NONE
```
=> Add code coverage badge to provide quick insight

cmd/descheduler/OWNERS, pkg/descheduler/OWNERS
/kind cleanup
Add Garrybest as descheduler owner.
Fixes https://github.com/karmada-io/karmada/pull/2745#issuecomment-1303173586
```release-note
NONE
```
=> add Garrybest as descheduler owner

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/controllers/certificate/cert_rotation_controller.go, pkg/controllers/cluster/cluster_controller.go, pkg/controllers/cluster/taint_manager.go, pkg/controllers/execution/execution_controller.go, pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go, pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go, pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go, pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go, pkg/controllers/hpa/hpa_controller.go, pkg/controllers/mcs/endpointslice_controller.go, pkg/controllers/mcs/service_export_controller.go, pkg/controllers/mcs/service_import_controller.go, pkg/controllers/status/cluster_status_controller.go, pkg/controllers/status/workstatus_controller.go, pkg/controllers/unifiedauth/unified_auth_controller.go
/kind cleanup
/kind feature
Reuse the context for Reconcile logic..
Fixes #2701
=> reuse context for controller-manager base-context

pkg/karmadactl/deinit.go
/kind feature
deinit does not need args at present
Fixes #
```release-note
NONE
```
=> Add arges check for karmadactl deinit

pkg/karmadactl/get.go, pkg/karmadactl/karmadactl.go, pkg/karmadactl/promote.go, test/e2e/karmadactl_test.go
/kind feature
/kind cleanup
Not only introduce factory, but cleanup the code of promote.
Part of #2349 
We need to improve the code of karmadactl ASAP, then add unit test for it.
/cc @carlory @XiShanYongYe-Chang 
```release-note
NONE
```
=> karmadactl promote uses factory to access cluster

pkg/karmadactl/cmdinit/karmada/deploy.go, pkg/karmadactl/register.go, pkg/karmadactl/token.go, pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
Cherry pick of #2707 on release-1.3.
```release-note
fix karmadactl token：print correct register command according to the karmada-context flag
```
=> Automated cherry pick of #2707 on release-1.3.

pkg/karmadactl/register.go
=> fix wrong description for "dry-run" option.

hack/tools/lifted-gen/lifted-gen.go
Signed-off-by: tanberBro <pengfei.song@daocloud.io>
/kind cleanup
```release-note
NONE
```
=> lifted-gen.go add flag parse

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml, charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml, pkg/apis/policy/v1alpha1/propagation_helper.go, pkg/apis/policy/v1alpha1/propagation_helper_test.go, pkg/apis/policy/v1alpha1/propagation_types.go, pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go, pkg/generated/openapi/zz_generated.openapi.go
/kind feature
TBD.
Fixes #
```release-note
NONE
```
=> Introduce priority to PropagationPolicy

pkg/karmadactl/cmdinit/utils/ip.go
/kind feature
optimize ParseIP
Fixes #
```release-note
NONE
```
=> optimize ParseIP

pkg/karmadactl/addons/search/search.go
These two places do not refer to the same variable, which will confuse developers. Therefore I change them refer to the same variable.
Fixes #
```release-note
```
=> fix etcd sts name hardcode

pkg/detector/compare.go, pkg/detector/compare_test.go, pkg/detector/detector.go, test/e2e/clusterpropagationpolicy_test.go, test/e2e/propagationpolicy_test.go, test/helper/policy.go
/kind feature
**User story**: The platform administrator specifies the default PP. Users can specify the priority of their own PP to control the PP that are preferentially used.
Fixes #none
```release-note
Introduce priority to PropagationPolicy.
```
=> Implement priority of PropagationPolicy

test/e2e/suite_test.go
/kind flake
See #2804 analysis.
Fixes #2804 
```release-note
NONE
```
=> [e2e] decrease the number of replicas when updating the number of statefulset replicas

Makefile
Recently, we have frequently encountered CI failures:
https://github.com/karmada-io/karmada/actions/runs/3417843605/jobs/5689574998
This is obviously an occasional problem.
For the root cause of the problem, see @ikaven1024 's comments.
Fixes #
```release-note
NONE
```
=> Fix random errors occur during binary compilation

test/e2e/clusterpropagationpolicy_test.go, test/e2e/propagationpolicy_test.go
/kind flake
Fix  PP/CPP e2e probabilistic failure
none
```release-note
none
```
=> Fix  PP/CPP e2e probabilistic failure

charts/OWNERS
/kind cleanup
This PR nominates @Poor12 as one of the approvers.
@Poor12 has been a reviewer since Jun 2022 and helped with a bunch of PRs. 
If no objections, this will be merged by the middle of next week(11.16). 
Fixes #
```release-note
NONE
```
=> Put Poor12 onto chart owner list

pkg/karmadactl/util/idempotency.go
/kind bug
I found it when tested #2505 
Fixes #
It's introduced at #2724 , and doesn't need cherry-pick.
```release-note
NONE
```
=> Fix some call errors of `idempotency.go`

pkg/search/proxy/store/util.go
Cherry pick of #2746 on release-1.3.
#2746: make multi cluster ResourceVersion string stable
```release-note
karmada-search: Fixed ResourceVersion returned by proxy is not stable.
```
=> Automated cherry pick of #2746: make multi cluster ResourceVersion string stable

pkg/karmadactl/cmdinit/karmada/deploy.go, pkg/karmadactl/util/idempotency.go
Fixes #
Optimize initAPIService function.Make it more concise.
```release-note
```
=> optimize initAPIService

pkg/util/metrics/metrics.go, pkg/util/metrics/metrics_test.go
add ut for util/metrics
https://github.com/karmada-io/karmada/issues/2579
```release-note
```
=> add ut for util/metrics

pkg/controllers/certificate/cert_rotation_controller.go, pkg/karmadactl/util/idempotency.go, pkg/util/namespace.go, pkg/util/rbac.go, test/e2e/search_test.go
/kind cleanup
Unify ObjectMeta.Name to Name and unify  ObjectMeta.Namespace to Namespace
Fixes #
```release-note
```
=> unify namespace and name style

pkg/karmadactl/addons/addons.go, pkg/karmadactl/cmdinit/cmdinit.go, pkg/karmadactl/cordon/cordon.go, pkg/karmadactl/deinit/deinit.go, pkg/karmadactl/exec/exec.go, pkg/karmadactl/get/get.go, pkg/karmadactl/join/join.go, pkg/karmadactl/promote/promote.go, pkg/karmadactl/register/register.go, pkg/karmadactl/taint/taint.go, pkg/karmadactl/unjoin/unjoin.go
/kind cleanup
Improve karmadactl command description
Fixes #2665 
/cc @RainbowMango @Poor12 
```release-note
NONE
```
=> Improve karmadactl command description

pkg/scheduler/core/assignment.go, pkg/scheduler/core/generic_scheduler.go
/kind cleanup
Now assign function and algorithm is a little complex. This PR tries to refactor assign replicas strategy. 
Fixes #
Note that this PR is a start. Division strategy will be refactored in future PRs. 
```release-note
NONE
```
=> refactor assign replicas strategy

.github/workflows/ci.yml, .github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/release.yml, .github/workflows/swr-latest-image.yml, .github/workflows/swr-released-image.yml
/kind cleanup
This PR updates the default Go version for CI and releases bots to v1.18.3.
Fixes #
```release-note
Karmada(v1.3) is now built with Go1.18.8.
```
=> Build release-1.3 with go1.18.8

pkg/karmadactl/interpret/rule.go
/kind bug
fix karmadactl interpret panic
Fixes #
```release-note
NONE
```
=> fix karmadactl interpret panic

test/e2e/framework/workload.go, test/e2e/resourceinterpreter_test.go
/kind cleanup
As talk in https://github.com/karmada-io/karmada/pull/2839#discussion_r1029150199.
Fixes #
```release-note
NONE
```
=> [e2e] Refactor InterpreterOperation retain test with resourceinterpreter

test/e2e/resourceinterpreter_test.go
Signed-off-by: zhangyukun <38148677+jameszhangyukun@users.noreply.github.com>
/kind feature
add test case for resource interpreter customization:
- DependencyInterpretation
part of #2371 
```release-note
NONE
```
=> [E2E] add test case for resource interpreter customization

charts/karmada/templates/karmada-aggregated-apiserver.yaml, charts/karmada/templates/karmada-apiserver.yaml, charts/karmada/templates/karmada-controller-manager.yaml, charts/karmada/templates/karmada-descheduler.yaml, charts/karmada/templates/karmada-scheduler-estimator.yaml, charts/karmada/templates/karmada-scheduler.yaml, charts/karmada/templates/karmada-webhook.yaml, charts/karmada/templates/kube-controller-manager.yaml
/kind cleanup
The strategy format is wrong, so I fixed it to the correct format.
Fixes #
```release-note
```
=> fix strategy chart format

docs/CHANGELOG/CHANGELOG-1.3.md
* Add v1.3.0 changelog
Fixes #
@XiShanYongYe-Chang @RainbowMango 
```release-note
none
```
=> Add v1.3.0 changelog

pkg/scheduler/core/assignment.go, pkg/scheduler/core/assignment_test.go, pkg/scheduler/core/division_algorithm.go, pkg/scheduler/core/division_algorithm_test.go, pkg/util/helper/binding.go
/kind cleanup
Fixes part of #2834
```release-note
NONE
```
=> refactor static weight strategy

charts/karmada/values.yaml
/kind cleanup
Set image tag to v1.4.0
Fixes #
None
=> Set image tag to v1.4.0

pkg/karmadactl/cmdinit/utils/util.go, pkg/karmadactl/util/genericresource/visitor.go
/kind cleanup
Comparing with `== ` will fail on wrapped errors. Use errors.Is to check for a specific error
Fixes #
```release-note
NONE
```
=> Use errors.Is to check for a specific error

pkg/resourceinterpreter/configurableinterpreter/configmanager/manager_test.go
Fixes 
```
=== RUN   Test_interpreterConfigManager_LuaScriptAccessors/multi_ResourceInterpreterCustomization_with_redundant_operation_
manager_test.go:118: informer has not been synced
```
https://github.com/ikaven1024/karmada/actions/runs/3589549623/jobs/6042171370#step:4:785
`Informer.Synced` indicates local indexer (part 2 in above picture) is ready. While `Workqueue` (in part3) may not handled, i.e. `configManager` has NOT synced.
```release-note
NONE
```
=> fix ut: HasSynced error

pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go, pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
/kind cleanup
go1.19: change some atomic.Value to atomic.Bool
Fixes #
```release-note
NONE
```
=> go1.19: change some atomic.Value to atomic.Bool

pkg/resourceinterpreter/configurableinterpreter/configmanager/manager_test.go
Cherry pick of #2895 on release-1.4.
#2895: fix ut: HasSynced error
```release-note
NONE
```
=> Automated cherry pick of #2895: fix ut: HasSynced error

charts/index.yaml
/kind cleanup
Add helm index for 1.4.
Fixes #
None
=> Add helm index for 1.4

pkg/controllers/execution/execution_controller.go, pkg/karmadactl/addons/descheduler/manifests.go, pkg/karmadactl/addons/estimator/manifests.go, pkg/karmadactl/addons/search/manifests.go, pkg/util/fedinformer/keys/keys_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Modify the error log output

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/metrics/pool.go, pkg/metrics/pool_test.go, pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go, pkg/util/fixedpool/fixedpool.go
/kind cleanup
Add metrics for `FixedPool`, helps us to choose an optimal pool size.
Fixes #
```release-note
NONE
```
=> add metrics for pool

.github/workflows/ci.yml, .github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/release.yml, .github/workflows/swr-latest-image.yml, .github/workflows/swr-released-image.yml
Signed-off-by: qingwave <854222409@qq.com>
/kind cleanup
Fixes #
```release-note
Karmada is now built with Golang 1.19.4.
```
=> Cherry pick from #2908: Build with Go patch release 1.19.4

pkg/controllers/namespace/namespace_sync_controller.go
Signed-off-by: helen <haitao.zhang@daocloud.io>
/kind feature
accelerate namespace sync
Fixes #
```release-note
NONE
```
=> namespace_sync_controller: buildWorks parallel sync namespace

pkg/util/helper/unstructured_test.go
Signed-off-by: qingwave <isguory@gmail.com>
/kind cleanup
Add uinttest for util/helper/unstructed.go
Subtask of #2579
```release-note
None
```
=> [UT] Add unstructed helper uinttest

pkg/controllers/namespace/namespace_sync_controller.go
/kind bug
need return after ch <-
Fixes #
```release-note
NONE
```
=> need return after ch <-

pkg/detector/detector.go
We found such a failing test on the master branch:
https://github.com/karmada-io/karmada/actions/runs/3671907442/jobs/6207636506
After analysis, it is found that the primary `karmada-controller-manager` instance is faulty when the `resourceSelector` of `PropagationPolicy` is changed but not successfully processed during the test. After the standby instance takes over the work from the primary instance, the informer of the `detector` is rebuilt.
However, for the `detector` informer, the order fo `PropagationPolicy` is earlier than the order of `Deployment`. As a result, the related `Deployment` cannot be found during `PropagationPolicy` processing. So the …
=> fix failing test of editing policy resourceSelectors

pkg/util/helper/policy.go, pkg/util/helper/policy_test.go, pkg/util/validation/validation.go, pkg/util/validation/validation_test.go, pkg/webhook/clusterpropagationpolicy/validating.go, pkg/webhook/propagationpolicy/validating.go
/kind cleanup
move all validation funcs into util/validation
Fixes #
```release-note
NONE
```
=> move validation funcs into util/validation

pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
/kind cleanup
Fixes #
not detailed enough.
```release-note
NONE
```
=> Add detailed information about the taint

pkg/detector/detector.go
/kind bug
Fixes #2090
```release-note
NONE
```
=> fix RB may not be created when delete and create the same object immediately

hack/local-down-karmada.sh
/kind feature
Fixes #2926 
```release-note
```
=> Add a script to remove the karmada started by local-up-karmada.sh

docs/proposals/hpa/federated-hpa.md
Just fixing a few typos
Fixes #
```release-note
NONE
```
=> docs: fix typos in federated-hpa proposal

.github/workflows/ci.yml
/kind cleanup
This PR setup a GitHub token for `action setup-protoc` according to [Usage](https://github.com/arduino/setup-protoc#usage) to address the [rate-limiting issue](https://github.com/karmada-io/karmada/actions/runs/3745628055/jobs/6360254317#step:4:8).
Fixes #
```release-note
NONE
```
=> Setup github token for action protoc

test/e2e/framework/rbac.go
/kind bug
Fixes #2978
```release-note
NONE
```
=> Update the wrong message info in the e2e

.golangci.yml, operator/cmd/operator/app/operator.go, operator/cmd/operator/app/options/options.go, operator/cmd/operator/operator.go, operator/pkg/controller/context/context.go, operator/pkg/controller/karmada/karmada_controller.go, operator/pkg/scheme/scheme.go, vendor/k8s.io/component-base/config/options/leaderelectionconfig.go, vendor/modules.txt
/kind feature
```release-note
NONE
```
/cc @lonelyCZ @RainbowMango
=> add operator skeleton

charts/karmada/templates/karmada-agent.yaml
Signed-off-by: Amir Alavi <amir.alavi@zendesk.com>
/king bug
Fix indentation with karmada-agent
Fixes #
```
strategy:
-        rollingUpdate:
-          maxSurge: 50%
-          maxUnavailable: 0
-        type: RollingUpdate
+    rollingUpdate:
+      maxSurge: 50%
+      maxUnavailable: 0
+    type: RollingUpdate
```
```release-note
fix karmada-agent helm template strategy indentation
```
=> fix: karmada-agent helm template strategy indentation

pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go, pkg/resourceinterpreter/defaultinterpreter/healthy_test.go, pkg/resourceinterpreter/defaultinterpreter/reflectstatus_test.go, pkg/resourceinterpreter/defaultinterpreter/revisereplica_test.go
Signed-off-by: Amir Alavi <amiralavi7@gmail.com>
/king cleanup
Continuation of #2995
Make the rest of the defaultinterpreter tests to run in parallel
Fixes #
```release-note
NONE
```
=> default interpreter sub-tests to run in parallel

pkg/controllers/mcs/service_export_controller.go
/kind bug
Modify log output errors
Fixes #
```release-note
```
=> Fix log output errors

test/e2e/mcs_test.go, test/e2e/resourceinterpreter_test.go, test/e2e/scheduling_test.go
/kind cleanup
Remove unnecessary fmt.Sprintf for logging
Fixes #
```release-note
NONE
```
=> Remove unnecessary fmt.Sprintf for logging

Makefile, hack/util.sh
/kind feature
we need build karmada-operator image in local env.
Fixes # https://github.com/karmada-io/karmada/issues/2979
```release-note
NONE
```
=> build karmada operator image

cmd/scheduler-estimator/app/options/options.go
/kind bug
modify description for flag usage
Fixes #3038 
if new description is  not suitable, i will modify it again.
```release-note
NONE
```
=> modify description for flag usage 

pkg/util/overridemanager/overridemanager_test.go
Signed-off-by: wongearl <vamliang@163.com>
/kind cleanup
add UT for ApplyOverridePolicies
Subtask of #2579
```release-note
```
=> add UT for ApplyOverridePolicies

pkg/apis/cluster/mutation/mutation_test.go
Signed-off-by: wongearl <vamliang@163.com>
/kind cleanup
add UT for SetDefaultClusterResourceModels
Subtask of #2579
```release-note
```
=> add UT for SetDefaultClusterResourceModels

pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
Signed-off-by: helen <haitao.zhang@daocloud.io>
/kind feature
when UpdateOrCreateToken get secrets, if the error is not a NotFound, the error is thrown in time
Fixes #
```release-note
NONE
```
=> UpdateOrCreateToken get secrets err handling optimization

pkg/karmadactl/util/apiclient/apiclient.go, vendor/k8s.io/utils/env/doc.go, vendor/k8s.io/utils/env/env.go, vendor/modules.txt
Signed-off-by: helen <haitao.zhang@daocloud.io>
/kind feature
use k8s.io/utils/env GetString get env
Fixes #
```release-note
NONE
```
=> use k8s.io/utils/env GetString get env

docs/CHANGELOG/CHANGELOG-0.10.md, docs/CHANGELOG/CHANGELOG-1.3.md, docs/proposals/cleanup-propagated-resources/README.md, docs/proposals/hpa/federated-hpa.md, docs/proposals/proposal-template/proposal-template.md, docs/proposals/resource-aggregation-proxy/README.md, docs/proposals/resource-quota/README.md, docs/proposals/scheduling/521-scheduler-estimator/README.md
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
Fixes #
```release-note
NONE
```
=> Fix syntax errors in the document

pkg/karmadactl/cmdinit/kubernetes/deployments_test.go
/kind cleanup
Add ut for deployments.go
none
```release-note
```
=> Add ut for deployments.go

pkg/controllers/context/context_test.go
/kind cleanup
This PR just tries to simplify a unit test for better readability.
Fixes #
```release-note
NONE
```
=> simplify context tests

docs/CHANGELOG/CHANGELOG-1.4.md
Fixes #
```release-note
NONE
```
=> Add v1.4.0 changelog

hack/util.sh
/kind cleanup
/kind feature
We can update [ alpine 3.17 version](https://mirrors.ustc.edu.cn/alpine/v3.17/).
Follow the docker build base image ```cluster/images/Dockerfile and cluster/images/buildx.Dockerfile```.
=> update alpine version to /etc/apk/repositories

cmd/aggregated-apiserver/app/options/options.go, pkg/aggregatedapiserver/apiserver.go, pkg/apis/cluster/scheme/regiser.go, pkg/registry/cluster/strategy_test.go
/kind cleanup
Add ut for cluster registry
Part of #2579 
Adjuster the file position of the cluster scheme.
```release-note
NONE
```
=> Add ut for cluster registry

pkg/karmadactl/cmdinit/kubernetes/check.go, pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cmdinit/kubernetes/node.go, pkg/karmadactl/cmdinit/kubernetes/node_test.go
/kind cleanup
Part of #2579
none
```release-note
```
=> Add ut for node.go

pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cmdinit/kubernetes/services.go, pkg/karmadactl/cmdinit/kubernetes/services_test.go
/kind cleanup
Add ut for service.go
none
```release-note
```
=> Add ut for service.go

.github/workflows/ci.yml, .github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/release.yml, .github/workflows/swr-latest-image.yml, .github/workflows/swr-released-image.yml
/kind cleanup
Fixes #
```release-note
Karmada is now built with Golang 1.19.5.
```
=> Build with Go patch release 1.19.5

cmd/controller-manager/app/controllermanager.go, pkg/detector/detector.go
/kind cleanup
Clean up a unused variable in detector
Fixes #
None
=> Clean up unused variable

pkg/karmadactl/cmdinit/kubernetes/secret_test.go
/kind cleanup
Add UT for pkg/karmadactl/cmdinit/kubernetes/secret_test.go
Ref: https://github.com/karmada-io/karmada/issues/2579
```release-note
NONE
```
=> [UT] add ut for kubernetes/secret.go

hack/install-cli.sh
/kind bug
Create /usr/local/bin if it doesn't exists when install cli
Fixes https://github.com/karmada-io/karmada/issues/3106
```release-note
```
=> Create /usr/local/bin if it doesn't exists when install cli

pkg/karmadactl/cmdinit/kubernetes/node_test.go
/kind cleanup
Ref : https://github.com/karmada-io/karmada/issues/2579
```release-note
NONE
```
=> [ut] improve ut coverage for node.go

.codecov.yml
/kind cleanup
This PR introduces [Codecov configuration](https://docs.codecov.com/docs/codecov-yaml) to [ignore generated files](https://docs.codecov.com/docs/ignoring-paths#ignoring-specific-files-at-all-depths).
Fixes #
```release-note
NONE
```
=> Add Codecov configuration

pkg/karmadactl/cmdinit/utils/util.go, pkg/registry/cluster/storage/proxy_test.go, pkg/search/proxy/controller_test.go, pkg/search/proxy/framework/plugins/cache/cache_test.go, pkg/search/proxy/framework/plugins/cluster/cluster_test.go, pkg/search/proxy/framework/plugins/karmada/karmada_test.go, pkg/util/proxy/proxy_test.go, test/helper/request.go
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
/kind cleanup
Use http constants instead of string
Fixes #
```release-note
NONE
```
=> Use http constants instead of string

pkg/karmadactl/cmdinit/utils/rbac_test.go
Signed-off-by: xin.li <xin.li@daocloud.io>
/kind cleanup
Add ut for utils/rbac.go
Ref: https://github.com/karmada-io/karmada/issues/2579
```release-note
NONE
```
=> [ut] add ut for utils/rbac.go

pkg/scheduler/event_handler.go
/kind feature
Add schedulerName for event.
Part of #3024 
```
Instrumentation: it is now possible to identify scheduled events initiated by custom schedulers.
```
=> Add schedulerName for event

pkg/karmadactl/cmdinit/cmdinit_test.go
/kind cleanup
```release-note
NONE
```
=> [UT] add ut for cmdinit/cmdinit.go

pkg/descheduler/descheduler.go, pkg/karmadactl/addons/init/enable_option.go, pkg/karmadactl/cmdinit/kubernetes/services.go, pkg/karmadactl/get/get.go, pkg/scheduler/event_handler.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Replace ""  with NamespaceAll.

pkg/karmadactl/cmdinit/utils/kubeconfig_test.go
/kind cleanup
Add ut for cmdinit/kubeconfig.og
```release-note
NONE
```
=> [UT] add ut for cmdinit/kubeconfig.go

pkg/karmadactl/addons/utils/template_test.go
/kind cleanup
Add ut for utils/template.go
```release-note
NONE
```
=> [UT] add ut for utils/template.go

pkg/karmadactl/cmdinit/utils/kubeconfig_test.go
/kind cleanup
[UT] improve test for kubeconfig.go
Ref: https://github.com/karmada-io/karmada/pull/3148#discussion_r1105203347
```release-note
NONE
```
=> [UT] improve test for kubeconfig.go

pkg/detector/detector.go, pkg/scheduler/core/generic_scheduler.go, pkg/scheduler/framework/interface.go, pkg/scheduler/framework/plugins/apienablement/api_enablement.go, pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go, pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go, pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go, pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go, pkg/scheduler/framework/runtime/framework.go, pkg/scheduler/framework/runtime/framework_test.go, pkg/scheduler/framework/testing/mock_interface.go
/kind cleanup
Since we add placement for binding(#2702), the interface in scheduler(Filter, Score) do not need placement any more.
Fixes #
None
=> Refactor scheduler interfaces

pkg/util/validation/validation.go, pkg/util/validation/validation_test.go, pkg/webhook/clusterpropagationpolicy/validating.go, pkg/webhook/propagationpolicy/validating.go
/kind feature
Part of #3153 
Fixes #
```release-note
`karmada-webhook`: add validation for policy.spec.placement.orderedClusterAffinities
```
=> add validation for ClusterAffinities

pkg/scheduler/core/assignment_test.go
/kind cleanup
Increase test coverage for core/assignment.go
```release-note
NONE
```
=> [UT] increase test coverage for core/assignment.go

pkg/karmadactl/cmdinit/cmdinit.go, pkg/karmadactl/cmdinit/kubernetes/deploy.go
/kind feature
Fixes #2985 
This is continuing develoption of #2987 that has been hold too long. And it is useful for users.
What do you think? Solfly ping @hexiaofeng 
```release-note
karmadactl: import `--cert-validity-period` for `init` to make the validity period of cert configurable
```
=> Make the validity period of cert configurable

docs/proposals/scheduling/multi-scheduling-group/README.md
/kind feature
This PR provides a proposal for addressing the issue https://github.com/karmada-io/karmada/issues/780.
Fixes #
```release-note
NONE
```
=> Add multiple scheduling group proposal

pkg/karmadactl/cmdinit/utils/format_test.go
/kind cleanup
```release-note
NONE
```
=> [UT] Add ut for utils/format.go

pkg/util/validation/validation.go, pkg/util/validation/validation_test.go, pkg/webhook/clusteroverridepolicy/validating.go, pkg/webhook/overridepolicy/validating.go
/kind feature
validates the fieldSelector of overridepolicy
Parts of  #3188 
```release-note
`karmada-webhook`: validates the fieldSelector of overridepolicy.
```
=> feat: validates the fieldSelector of overridepolicy

pkg/controllers/execution/execution_controller.go, pkg/util/objectwatcher/objectwatcher.go
/kind cleanup
Refactor execution_controller.go and objectwatcher.go, make it looks better
Fixes #none
none
```release-note
```
=> Refactor execution_controller.go and objectwatcher.go

pkg/scheduler/core/generic_scheduler.go, pkg/scheduler/framework/interface.go, pkg/scheduler/framework/plugins/apienablement/api_enablement.go, pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go, pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go, pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go, pkg/scheduler/framework/runtime/framework.go, pkg/scheduler/framework/runtime/framework_test.go, pkg/scheduler/framework/testing/mock_interface.go, pkg/scheduler/scheduler.go
/kind feature
Part of #3153 
Fixes #
```release-note
NONE
```
=> Add bindingStatus in the schedule algorithm interface

pkg/scheduler/helper.go, pkg/scheduler/helper_test.go, pkg/scheduler/scheduler.go
/kind feature
Part of #3153 
```release-note
NONE
```
=> Modify judgement of placement changed and consider clusteraffinities

pkg/scheduler/scheduler.go, pkg/util/helper/workstatus.go
/kind bug
/kind cleanup
After determining that the binding does not need to be scheduled, the binding status does not need to be updated, so I move the binding status action to the logic after scheduling.
When I change the logic, I ran into the problem mentioned in #3180, I find that we need to update the binding condition in the retry of updating binding status.
Fixes #3180 
In terms of overall behavior, this pr focuses on cleaning up, fixed errors do not require cherry-pick.
```release-note
NONE
```
=> Update the RB condition is updated only after scheduling

pkg/scheduler/event_handler.go, pkg/scheduler/helper.go, pkg/scheduler/helper_test.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
/kind feature
Part of #3153 
Fixes #
```release-note
NONE
```
=> Invoke multi times with clusterAffinities when reschedule ResourceBinding

test/e2e/clusteraffinities_test.go, test/e2e/framework/clusterpropagationpolicy.go, test/e2e/framework/propagationpolicy.go, test/e2e/propagationpolicy_test.go
/kind feature
Part of #3153
```release-note
NONE
```
=> Add e2e for schedule with clusterAffinities when replica scheduling type is Duplicated

charts/karmada/values.yaml
/kind cleanup
Set image tag for release 1.5
Fixes #
None
=> Set image tag for release 1.5

docs/CHANGELOG/CHANGELOG-1.5.md
Add release notes to release 1.5.0.
Fixes #
```release-note
NONE
```
=> Add release notes for 1.5

charts/index.yaml, charts/karmada/Chart.yaml
/kind cleanup
Add helm index for 1.5. It works well locally.
Fixes #
None
=> Add helm index for 1.5

charts/karmada/templates/_karmada_apiservice.tpl, charts/karmada/templates/_karmada_system_namespace.tpl, charts/karmada/values.yaml
/kind bug
Fixes #3230
Fixed the system namespace to "karmada-system".
```release-note
NONE
```
=> Fixed the system namespace to "karmada-system".

pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
add unit tests for dependency interpretation
Fixes #
```release-note
NONE
```
=> add unit tests for dependency interpretation

.github/workflows/ci.yml
/kind cleanup
Fixes #
Running a full test every time push is unnecessary, and this patch will cancel CI when new changes are made.
```release-note
NONE
```
=> ci: Cancel when there is a new change

.github/workflows/ci-schedule.yml
/kind cleanup
Part of #3235 
`schedule` evemt configuration reference to https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
```release-note
NONE
```
=> add a new schedule workflow to run e2e test

README.md
Fixes #
```release-note
NONE
```
=> docs: update Kubernetes compatibility

.github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, Makefile
/kind cleanup
Since karmada-operator has implemented basic init and deint, it's time to push it to dockerHub for trial.
v1.6 may be the first version we release karmada-operator.
Fixes #
/cc @calvin0327 
None
=> Push karmada-operator to image registry

pkg/karmadactl/get/get.go
/kind cleanup
Delete redundance code for pkg/karmadactl/get/get.go.
Make the code more readable.
Fixes #
```release-note
NONE
```
=> Delete redundance code for pkg/karmadactl/get/get.go

pkg/resourceinterpreter/defaultinterpreter/prune/prune_test.go
add prune test
Fixes #
```release-note
NONE
```
=> add prune test

pkg/resourceinterpreter/defaultinterpreter/prune/prune_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> remove redundant conversion functions

pkg/scheduler/event_handler.go
/kind cleanup
Fix wrong logs for pkg/scheduler/event_handler.go
Fixes #
```release-note
NONE
```
=> Fix wrong logs for pkg/scheduler/event_handler.go

pkg/karmadactl/addons/search/search.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> chore: improve some format

pkg/util/membercluster_client.go
/kind feature
- use rest.Config
- when cluster.Spec.InsecureSkipTLSVerification is equal to false, check whether ca exists to avoid potential errors
Fixes #
```release-note
NONE
```
=> BuildClusterConfig：use rest.Config and check ca exist

pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go, pkg/scheduler/core/spreadconstraint/select_clusters_by_region_test.go, pkg/scheduler/core/spreadconstraint/select_groups.go, pkg/scheduler/core/spreadconstraint/select_groups_test.go, pkg/scheduler/core/spreadconstraint/util.go, pkg/scheduler/core/spreadconstraint/util_test.go
/kind feature
Fixes #3253
See the above issue for details.
```release-note
`karmada-scheduler`: optimize the region selection algorithm
```
=> region selection algorithm optimization

pkg/apis/policy/v1alpha1/propagation_helper.go, pkg/apis/policy/v1alpha1/propagation_helper_test.go, pkg/descheduler/core/filter.go, pkg/util/helper/policy.go, pkg/util/helper/policy_test.go, pkg/webhook/clusterpropagationpolicy/mutating.go, pkg/webhook/propagationpolicy/mutating.go
/kind cleanup
Fixes #3347
```release-note
NONE
```
=> add placement helper

pkg/util/helper/mcs.go
Cherry pick of #3348 on release-1.4.
#3348: Fixed the control plane endpointslice cannot be deleted.
```release-note
`karmada-controller-manager`: Fixed the control plane endpointslices cannot be deleted.
```
=> Automated cherry pick of #3348: Fixed the control plane endpointslice cannot be deleted.

pkg/util/apigroup_test.go
/kind feature
The logic in the switch statement is changed to the number of parts (split into multiple strings) to make the code clearer and clearer.
When dealing with the situation "<group>/<version>", the situation with the version number of "v1" is handled separately from other situations to avoid too many nested statements and duplicate codes.
Fixes #
```release-note
NONE
```
=> parseSingle: add test

docs/proposals/failover/application-failover.md
/kind design
Add “Rescheduling mechanism for unhealthy application state“ proposal
Fixes #
None
=> Add “Application failover mechanism“ proposal

operator/OWNERS
/kind cleanup
PRs: https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Acalvin0327+is%3Aclosed
Issues: https://github.com/karmada-io/karmada/issues?q=is%3Aissue+author%3Acalvin0327+is%3Aclosed
Fixes #
```release-note
NONE
```
=> Request to be a Operator Approvers of Karmada community

pkg/resourceinterpreter/default/native/dependencies_test.go, pkg/util/helper/pod.go
/kind cleanup
The remaining task of #3339
add unit test for `pkg/resourceinterpreter/default/native/dependencies.go`
Fixes #
NONE
```release-note
```
=> add unit test for pkg/resourceinterpreter/default/native/dependencies.go

pkg/controllers/cluster/cluster_controller.go
/kind cleanup
Fixes #
```
NONE
```
=> cleanup:cluster controller log missing clustername

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml, charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml, pkg/apis/work/v1alpha2/binding_types.go, pkg/apis/work/v1alpha2/zz_generated.deepcopy.go, pkg/generated/openapi/zz_generated.openapi.go
Binding API modification adaptation to implement application failover
Part of #3169 
None
=> Binding API modification adaptation to implement application failover

pkg/resourceinterpreter/default/native/retain.go
/kind bug
Fixes #3424 
```release-note
NONE
```
=> Fix func retainPodFields not include initContainer'volumesMounts bug

ROADMAP.md
/kind cleanup
This updates the roadmap for the year 2023, welcome to talk about it with the community. 
Fixes #
```release-note
NONE
```
=> Add draft of 2023 roadmap

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml, charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml, charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml, charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml, pkg/apis/policy/v1alpha1/propagation_types.go, pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go, pkg/apis/work/v1alpha2/binding_types.go, pkg/apis/work/v1alpha2/zz_generated.deepcopy.go, pkg/controllers/gracefuleviction/evictiontask.go, pkg/controllers/gracefuleviction/evictiontask_test.go, pkg/detector/detector.go, pkg/generated/openapi/zz_generated.openapi.go, pkg/util/helper/policy.go, pkg/util/helper/policy_test.go, pkg/util/validation/validation.go, pkg/util/validation/validation_test.go, pkg/webhook/clusterpropagationpolicy/mutating.go, pkg/webhook/propagationpolicy/mutating.go
/kind design
Add GracePeriodSeconds for GracefulEvictionTask.
Fixes #3430 
```
Add GracePeriodSeconds for GracefulEvictionTask.
```
=> Add GracePeriodSeconds for GracefulEvictionTask

pkg/apis/config/v1alpha1/interpretercontext_types.go, pkg/generated/openapi/zz_generated.openapi.go
Signed-off-by: mkloveyy [halfpig0627@163.com](mailto:halfpig0627@163.com)
It add more comments for AggregatedStatus definition.
Fixes #
```release-note
NONE
```
=> Add more detail comments for AggregatedStatus field

test/e2e/dependenciesdistributor_test.go
/kind cleanup
**What this PR does / why we need it**: 
Add some e2e test case for dependency distribution of resources which are propagated based on clusterPropagationPolicies 
Fixes #3265
```release-note
```
=> add e2e to test dependency distribution base on ClusterPropagationPolicy

pkg/controllers/gracefuleviction/evictiontask.go, pkg/controllers/gracefuleviction/evictiontask_test.go
/kind cleanup
This PR reverts #3283, the reason is explained at https://github.com/karmada-io/karmada/pull/3283#issuecomment-1522889612.
Fixes #
```release-note
NONE
```
/assign @Poor12
=> Revert PR3283

pkg/scheduler/scheduler.go
Cherry pick of #3455 on release-1.5.
#3455: fix generation inconsistent
```release-note
`karmada-scheduler`: Fixed the issue of inconsistent Generation and SchedulerObservedGeneration.
```
=> Automated cherry pick of #3455: fix generation inconsistent

operator/pkg/apis/operator/v1alpha1/defaults.go, operator/pkg/certs/certs.go, operator/pkg/constants/constants.go, operator/pkg/controlplane/apiserver/apiserver.go, operator/pkg/controlplane/apiserver/mainfests.go, operator/pkg/init.go, operator/pkg/tasks/init/apiserver.go, operator/pkg/tasks/init/cert.go, operator/pkg/tasks/init/data.go, operator/pkg/tasks/init/upload.go, operator/pkg/util/apiclient/idempotency.go, operator/pkg/util/endpoint.go
/kind feature
support nodeport service type for karmada apiserver
Fixes #
```release-note
NONE
```
=> karmada operator: add nodeport service type for apiserver

pkg/search/controller.go
/kind cleanup
Fixes #
```
NONE
```
=> Fix: cleanup ResourceRegistry controller logs

pkg/search/controller.go
/kind bug
Fix panic in SearchController caused by receiving DeletedFinalStateUnknown object from the cache.
Fixes #
```
Fix panic in ResourceRegistry controller caused by receiving DeletedFinalStateUnknown object from the cache.
```
=> karmada-search: ResourceRegistry controller can't handle DeletedFinalStateUnknown it gets from controller framework

README.md
/kind cleanup
This PR proposed the regular English community meeting based on #1560, the first call on `Tuesday, May 16th`([Convert to your time](https://dateful.com/convert/pt-pacific-time?t=08&d=2023-05-16)). 
Please feel free to add your agenda on the [meeting notes](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.xom4jxumka6a).  (By [joining the google groups](https://groups.google.com/forum/#!forum/karmada) you will be able to edit the meeting notes.)
Fixes #
```release-note
NONE
```
=> setup English community meeting

pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go, pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Cherry pick of #3475 on release-1.5.
#3475: fix: graceful-eviction still works after an unexpected
```release-note
`karmada-controller-manager`: Fixed a corner case that when there are tasks in the GracefulEvictionTasks queue, graceful-eviction-controller will not work after restarting karmada-controller-manager.
```
=> Automated cherry pick of #3475: fix: graceful-eviction still works after an unexpected

pkg/search/backendstore/opensearch.go
/kind cleanup
improve opensearch backend logs and modify `openserch` ==> `opensearch`.
Fixes #
```
NONE
```
=> karmada-search: improve opensearch backend logs

docs/proposals/failover/application-failover.md
According to https://github.com/karmada-io/karmada/pull/3508#pullrequestreview-1418190045, we need to update the proposal about fields which we postpone in release-1.6.
Fixes #
None
=> Update application failover proposal

test/e2e/failover_test.go
/kind flake
Add application failover e2e
Fixes #
None
=> Add application failover e2e

artifacts/deploy/bootstrap-token-configuration.yaml, artifacts/deploy/karmada-apiserver.yaml, hack/deploy-karmada.sh
/kind feature
Part of #3280 
```release-note
Support Karmada installed by script to use karmadactl register
```
=> Support Karmada installed by script to use karmadactl register

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/AdvancedCronJob/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/BroadcastJob/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/desired-ocirepository.yaml, pkg/resourceinterpreter/default/thirdparty/thirdparty_test.go
/kind flake
check thirdparty resources
Fixes #
check thirdparty resources
```release-note
NONE
```
=> check thirdparty resources

charts/karmada/templates/post-delete-job.yaml
fix helm uninstall remain deployment {{ name }}-controller-manager
helm uninstall remain deployment.
Fixes #
fix(chart): fix helm uninstall remain deployment {{name}}-controller-manager
```release-note
```
=> fix(chart): helm uninstall clear deployment {{name}}-controller-manager

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/customizations.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/customizations_tests.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/testdata/desired-clusterpolicy.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/testdata/observed-clusterpolicy.yaml, pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/ClusterPolicy/testdata/status-file.yaml
/kind cleanup
Add third-party resources `kyverno.io/v1/ClusterPolicy` into Resource Interpreter framework.
Part of #3331 
@Poor12 @chaunceyjiang 
NONE
```release-note
`Resource Interpreter`: Support `kyverno.io/v1/ClusterPolicy`
```
=> add customizations for kyverno.io/v1/ClusterPolicy

operator/README.md
/kind feature
**What this PR does / why we need it**
Add karmada operator README to introduce how to use karmada operator.
Fixes #
```release-note
NONE
```
=> karmada operator: add karmada operator readme

charts/karmada/templates/karmada-aggregated-apiserver.yaml, charts/karmada/templates/karmada-apiserver.yaml, charts/karmada/templates/karmada-cert.yaml
kind feature
Fixes # https://github.com/karmada-io/karmada/issues/3528
```release-note
```
=> Add the helmrealesa name prefix to the external etcd secret

pkg/karmadactl/interpret/check.go
Fixed typo: checkScrip -> checkScript
Fixes #3539 
```release-note
```
=> fix: Fixed typo

pkg/karmadactl/addons/enable.go
Fixes #
```release-note
NONE
```
=> fix error example for addons enable

.gitignore, charts/karmada-operator/.helmignore, charts/karmada-operator/Chart.lock, charts/karmada-operator/Chart.yaml, charts/karmada-operator/README.md, charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml, charts/karmada-operator/templates/NOTES.txt, charts/karmada-operator/templates/_helpers.tpl, charts/karmada-operator/templates/karmada-operator-clusterrole.yaml, charts/karmada-operator/templates/karmada-operator-clusterrolebinding.yaml, charts/karmada-operator/templates/karmada-operator-deployment.yaml, charts/karmada-operator/templates/karmada-operator-serviceaccount.yaml, charts/karmada-operator/values.yaml, hack/update-crdgen.sh
/kind feature
We need multiple way to install karmada operator, like helm chart:
here is test result:
```shell
helm install karmada-operator -n karmada-system  --create-namespace  ./charts/karmada-operator --debug
NAME: karmada-operator
LAST DEPLOYED: Thu May 11 19:23:56 2023
NAMESPACE: karmada-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
USER-SUPPLIED VALUES:
{}
COMPUTED VALUES:
common:
exampleValue: common-chart
global:
imagePullSecrets: []
imageRegistry: ""
global:
imagePullSecrets: []
imageRegistry: ""
operator:
affinity: {}
image:
pullPolicy: IfNotPresent
pullSecrets: []
registry: docker.io
repository: karmada/karmada-operator
tag: latest
labels: {}
nodeSelector: {}
podAnnotations: {}
podLabels: {} …
```
=> karmada operator: add karmada operator chart

operator/README.md
Today, It will be failed when follow the doc to create karmada instance.
Fixes #
```release-note
NONE
```
=> Fix doc of operator README for install crds

artifacts/deploy/kube-controller-manager.yaml
/kind feature
Part of #3280 
Sorry, omited this change at #3440 
```release-note
NONE
```
=> Add tokencleaner controller for karmada installed by script

.github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml
/kind cleanup
This PR ensures the image of `karmada-metrics-adaptor` could be released to DockerHub.
Fixes #
```release-note
NONE
```
cc @jwcesign
=> Setup automation process of release karmada-metrics-adaptor to DockerHub

pkg/metricsadapter/controller.go
/kind bug
karmada-metrics-adapter only handles clusters in Push mode
Fixes #
```release-note
NONE
```
=> karmada-metrics-adapter only handles clusters in Push mode

charts/karmada/values.yaml
/kind cleanup
Set image tag to v1.6.0 for branch v1.6.0
Fixes #
None
=> Set image tag to v1.6.0

docs/CHANGELOG/CHANGELOG-1.6.md
/kind cleanup
This PR adds the release notes of release-1.6.
Fixes #
```release-note
NONE
```
=> Add v1.6 release notes

charts/index.yaml
/kind cleanup
Add index for 1.6.
Fixes #
None
=> Add index for 1.6

pkg/search/proxy/store/store.go
/kind cleanup
rename suppported to supported
Fixes #
```release-note
NONE
```
=> cleanup: rename suppported to supported.

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml, operator/pkg/apis/operator/v1alpha1/type.go
**What this PR does**
Fixes some typos in the Karmada operator
Fixes #3649 
```release-note
NONE
```
=> Fixed small typos in the Karmada operator

hack/deploy-metrics-adapter.sh
/kind feature
**What this PR does**:
Provides deployment scripts for karmada-metrics-adapter.
Fixes #3625 
```release-note
NONE
```
=> Karmada metrics adapter deployment script

operator/pkg/controller/karmada/controller.go
/kind feature
In this scenario: user want to retain karmada instance when delete karmada cr.
we support a label `operator.karmada.io/disable-cascading-deletion` in karmada cr.
`operator.karmada.io/disable-cascading-deletion: false` represents delete karmada instance when delete karmada cr.
`operator.karmada.io/disable-cascading-deletion: true` represents  not to delete karmada instance when delete karmada cr.
Fixes #
```release-note
Karmada Operator: support disable karmada cascading deletion
```
=> Karmada Operator: support disable  karmada cascading deletion

.github/workflows/ci-schedule-compatibility.yaml, .github/workflows/ci-schedule.yml, .github/workflows/ci.yml, .github/workflows/cli.yaml, .github/workflows/dockerhub-latest-chart.yml, .github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-chart.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/fossa.yml, .github/workflows/lint-chart.yaml, .github/workflows/release.yml, .github/workflows/swr-latest-image.yml, .github/workflows/swr-released-image.yml
/kind flake
CI test large area failure
Fixes #3667 
@RainbowMango @XiShanYongYe-Chang 
```release-note
```
=> upgrade CI ubuntu image

cmd/controller-manager/app/controllermanager.go, pkg/dependenciesdistributor/dependencies_distributor.go, pkg/dependenciesdistributor/dependencies_distributor_test.go, test/e2e/resourceinterpreter_test.go
/kind feature
Support modification synchronization of custom resources as dependency
Fixes #3605 
```release-note
`karmada-controller-manager`: support modification synchronization of custom resources as dependency.
```
=> feat: Support modification synchronization of custom resources as dependency

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml, operator/config/crds/operator.karmada.io_karmadas.yaml, operator/pkg/apis/operator/v1alpha1/type.go
/kind bug
KarmadaComponents has a problem with the json definition of the karmadaDescheduler field
Fixes #
```release-note
NONE
```
=> fix: update karmada operator crd karmadaDescheduler field

operator/pkg/util/util.go
/kind bug
Fixes #
Optimize download percentage log
before
now
```release-note
NONE
```
=> Optimize download percentage log

.github/ISSUE_TEMPLATE/cherry-pick.md
/kind cleanup
This PR added an issue template for tracking cherry-pick tasks.
Fixes #
```release-note
NONE
```
=> Add cherry-pick issue template

operator/README.md
Refer to https://github.com/karmada-io/karmada/pull/3577#issuecomment-1605893356.
```release-note
NONE
```
=> update operator readme.md

operator/pkg/controlplane/apiserver/apiserver.go, operator/pkg/controlplane/controlplane.go, operator/pkg/controlplane/webhook/webhook.go, operator/pkg/tasks/deinit/kubeconfig.go, operator/pkg/tasks/init/upload.go, operator/pkg/util/naming.go
/kind bug
Fixes #
```release-note
NONE
```
=> fix: AdminKubeconfigSecretName function name

cmd/metrics-adapter/OWNERS, pkg/controllers/federatedhpa/OWNERS, pkg/metricsadapter/OWNERS
/kind cleanup
This PR nominated @jwcesign @Poor12 and @chaunceyjiang as the owner of the FederatedHPA feature. They've made significant contributions to the feature and will continue to lead the effort for it.
Fixes #
Please remind me if I missed some path/directory of the FederatedHPA feature.
```release-note
NONE
```
=> Nominate FederatedHPA feature owner

OWNERS, pkg/controllers/OWNERS, pkg/resourceinterpreter/OWNERS, pkg/resourceinterpreter/default/thirdparty/OWNERS, pkg/scheduler/OWNERS
/kind cleanup
This PR promotes code owners as per [Community membership](https://github.com/karmada-io/community/blob/main/community-membership.md#community-membership).
Fixes #
cc @chaunceyjiang @jwcesign @Poor12 @Garrybest @ikaven1024 @yike21 @whitewindmills 
As the code owner, you might be always involved in the progress of code review, if you are ok with this nomination, please leave your comments with `/lgtm`.
Note:
Please remind me if I missed someone who deserves to be on the owner list. 
```release-note
NONE
```
=> Promote code owners as per community membership

README.md
Fixes #
```release-note
NONE
```
=> Delete unnecessary symbols in the execution script

Makefile, hack/package-helm-chart.sh
/kind feature
I find that karmada operator chart package not be pushed to dockerhub repository.
Fixes #
```release-note
NONE
```
=> karmada operator: add karmada operator chart to dockerhub

MAINTAINERS.md
/kind cleanup
This PR updated the affiliation of @mrlihanbo and @carmark. 
Fixes #
```release-note
NONE
```
=> Update maintainers affiliation

charts/karmada/templates/_helpers.tpl, charts/karmada/templates/karmada-search.yaml
/kind bug
Fixes https://github.com/karmada-io/karmada/issues/3774
```release-note
Chart: Fixed the issue that `karmada-search` no ETCD secret volume mount when using external ETCD.
```
=> chart: fix karmada search external etcd no volume mount

operator/pkg/controller/karmada/controller.go
/kind feature
I find that the karmada cr has been reconciled over and over again. 
Due to the two situation:
1. At the end of  every reconcile will update karmada cr status that will retrigger the next reconcile.
2. The status will update failed as the version conflicts.
Fixes https://github.com/karmada-io/karmada/issues/3770
```release-note
NONE
```
=> karmada operator: avoid invalid reconclie for karmada cr

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml, pkg/apis/policy/v1alpha1/propagation_types.go, pkg/generated/openapi/zz_generated.openapi.go
/kind feature
This PR proposes the API of feature [PropagationPolicy Priority and Preemption](https://github.com/karmada-io/karmada/pull/3684). 
Fixes #
```release-note
NONE(Part of feature)
```
=> Proposing PropagationPolicy Preemption API

api/openapi-spec/swagger.json, hack/tools/swagger/generateswagger.go, pkg/apis/networking/v1alpha1/service_types.go
add MultiClusterService API to API swagger doc
Fixes #
```release-note
NONE
```
=> add MultiClusterService API to api swagger doc

test/e2e/coverage_docs/E2E_coverage.md, test/e2e/coverage_docs/namespace_test.md, test/e2e/coverage_docs/resource_test.md
Add features e2e test coverage details
issue:https://github.com/karmada-io/karmada/issues/3685
Fixes #
```release-note
```
=> Add e2e coverage of the features doc

hack/deploy-karmada.sh, hack/local-up-karmada.sh, test/e2e/cronfederatedhpa_test.go, test/e2e/framework/cronfederatedhpa.go, test/e2e/framework/deployment.go, test/e2e/framework/federatedhpa.go, test/e2e/suite_test.go, test/helper/resource.go
/kind cleanup
Add e2e for CronFederatedHPA.
case 1:Scale FederatedHPA.
case 2:Scale deployment.
case 3:Test suspend rule with CronFederatedHPA
Part of https://github.com/karmada-io/karmada/issues/3746
none
```release-note
```
=> e2e: Add e2e for CronFederatedHPA

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml, charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml, charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml, pkg/apis/policy/v1alpha1/propagation_types.go, pkg/apis/work/v1alpha2/binding_types.go, pkg/generated/openapi/zz_generated.openapi.go
This PR proposes the API changes for [Seamless Cluster Migration Proposal](https://github.com/karmada-io/karmada/pull/3780).
Fixes #
```release-note
NONE（Part of feature）
```
=> Add conflict resolution API to PP and CPP

test/e2e/search_test.go, test/e2e/suite_test.go
add e2e test when cluster join, update, karmada need to reconcile search cache
Fixes #3731 
```release-note
```
=> add e2e test when cluster join, update, karmada need to reconcile search cache

pkg/features/features.go
/kind feature
Add feature gate for policy preemption.
Part of #3787 
None
=> Add feature gate for policy preemption

pkg/webhook/cronfederatedhpa/validation.go
/kind feature
CronFedertedHPA validation enhancement:
1. `TargetReplicas` should be larger than or equal to 0.
2. `TargetMinReplicas` and `TargetMaxReplicas` should be larger than or equal to 1.
3. `TargetMinReplicas` should be larger than or equal to `TargetMaxReplicas`.
4. metadata.name should be a valid name.
5. spec.scaleTargetRef should be valid.
Fixes #none
```release-note
`karmada-webhook`: Validation enhancement, including:
1. `TargetReplicas` should be larger than or equal to 0.
2. `TargetMinReplicas` and `TargetMaxReplicas` should be larger than or equal to 1.
3. `TargetMinReplicas` should be …
```
=> feat: add more validation for CronFederatedHPA

pkg/apis/work/v1alpha2/well_known_constants.go, pkg/controllers/binding/common.go, pkg/controllers/binding/common_test.go, pkg/detector/detector.go, pkg/util/annotation.go, pkg/util/annotation_test.go, pkg/util/helper/work.go
/kind feature
#3780 
**Which issue(s) this PR fixes:**
Fixes #3824 
**Special notes for your reviewer:**
@RainbowMango @jwcesign @whitewindmills
Test Report: https://github.com/karmada-io/karmada/pull/3821#issuecomment-1649238940
**Does this PR introduce a user-facing change?:**
```
`karmada-controller-manager`: Now able to resolve conflict as per (Cluster)PropagationPolicy.
```
=> feat: realization of ConflictResolution in PP

pkg/scheduler/core/util.go
/kind feature
avoid calculating available replicas for non-workload.
Fixes #3743
```release-note
NONE
```
=> feat: avoid calculating available replicas for non-workload

.github/workflows/ci.yml, Makefile
/kind feature  
Like https://github.com/golang/go/issues/46921  
It is a little hard to find out which failed in a failed unit-test job.  
```release-note
```
=> color unit-test output

charts/karmada/templates/pre-install-job.yaml
/kind bug
Fix charts installation when certs mode is custom. Introduced in #3721.
Fixes #3814 
None
=> Fix charts installation when certs mode is custom

pkg/webhook/cronfederatedhpa/validating_test.go
/kind cleanup
add cron-fhpa validation unit-test
```release-note
NONE
```
=> ut: add cron-fhpa validation unit-test

docs/CHANGELOG/CHANGELOG-1.4.md, docs/CHANGELOG/CHANGELOG-1.5.md, docs/CHANGELOG/CHANGELOG-1.6.md
This PR updates release notes of release-1.4, release-1.5 and release-1.6.
Fixes #
We are heading to cut a new patch release after this PR:
- ~~release-1.4~~ Skipped as no bug fixes.
- release-1.5  cut new release `v1.5.3`
- release-1.6  cut new release `v1.6.2`
```release-note
NONE
```
=> Update release notes of release-1.4,release-1.5,release-1.6 

pkg/detector/preemption.go, pkg/events/events.go, pkg/metrics/resource.go
/kind feature
add metrics and events for policy preemption
part of [feature](https://github.com/karmada-io/karmada/issues/3787)
```release-note
NONE
```
=> feat: add metrics and events for policy preemption

pkg/resourceinterpreter/default/native/dependencies.go
/kind feature
Add a Ingress to the default dependencinterpreter
We are currently using Ingress in our product.
Fixes #
```release-note
`karmada-controller-manger`: Add a Ingress to the default dependencinterpreter
```
=> Add a Ingress to the default dependencinterpreter

docs/CHANGELOG/CHANGELOG-1.4.md
This PR adds release notes to `release-1.4` branch. 
Fixes #
```release-note
NONE
```
=> Update release notes on release-1.4 branch

docs/CHANGELOG/CHANGELOG-1.4.md, docs/CHANGELOG/CHANGELOG-1.5.md
This PR updates release notes on `release-1.5` branch. 
Fixes #
```release-note
NONE
```
=> Update release notes on release-1.5 branch

docs/CHANGELOG/CHANGELOG-1.4.md, docs/CHANGELOG/CHANGELOG-1.5.md, docs/CHANGELOG/CHANGELOG-1.6.md
This PR updates release notes on `release-1.6` branch. 
Fixes #
```release-note
NONE
```
=> Update release notes on release-1.6 branch

docs/CHANGELOG/CHANGELOG-1.5.md
This PR updates the release notes for the coming v1.5.3 release.
Fixes #
Notable changes come from [compare v1.5.2 and releaset-1.5](https://github.com/karmada-io/karmada/compare/v1.5.2...release-1.5).
After this, we should cherry-pick this PR to release-1.5 and then cut v1.5.3, so that the release note would be included in release assets. 
```release-note
NONE
```
=> Update v1.5.3 release notes

docs/proposals/scheduling/policy-preemption/README.md
update metrics indicators.
part of https://github.com/karmada-io/karmada/issues/3787
```release-note
NONE
```
=> feat: update policy preemption proposals

docs/CHANGELOG/CHANGELOG-1.5.md
Cherry pick of #3888 on release-1.5.
#3888: Update v1.5.3 release notes
```release-note
NONE
```
=> Automated cherry pick of #3888: Update v1.5.3 release notes

README.md
Fixes Adding talks from KubeDay and KubeCon
=> docs: Add talks from KubeDay and KubeCon

README.md
Fixes grammar and markdown syntax
```release-note
```
=> doc: Fix grammar and markdown syntax

pkg/webhook/multiclusterservice/validating_test.go
/kind cleanup
add mcs validation ut
Fixes #
```release-note
NONE
```
=> ut: add mcs validation ut

pkg/util/fedinformer/transform.go
/kind bug
When client disconnected from apiserver, it will trigger `replace` in delta_fifo.go.
https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L690
If  obj was deleted at this time, `replace` will generate a DeletedFinalStateUnknown delta, and `transformer` will return a error. Finally, the `list` will always fail and report `unable to sync list result: xxx`.
https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L456
https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/client-go/tools/cache/ …
=> fix unable to sync list

test/e2e/framework/configmap.go, test/e2e/propagationpolicy_test.go
/kind cleanup
Add e2e case to cover policy cleanup.
Fixes #3884 
```release-note
NONE
```
=> test: add e2e test to cover PropagationPolicy

ADOPTERS.md
Fixes #3918 
```release-note
```
=> docs: Add adopter refrence

pkg/resourceinterpreter/default/native/replica.go
/kind feature
add pod replica interpreter by default.
Fixes #3858
```release-note
`karmada-controller-manager`: Add pod replica interpreter by default.
```
=> feat: add pod replica interpreter

charts/index.yaml
/kind cleanup
Add helm index for v1.6.1 and v1.6.2. It works well locally.
Fixes #3892
@RainbowMango 
None
**Test Report**:
https://github.com/karmada-io/karmada/pull/3911#issuecomment-1668839956
=> Add helm index for v1.6.1 and v1.6.2

operator/pkg/controller/karmada/controller.go
/kind feature
If user set a lable to karmada cr, it will be overwritten by operator.
Fixes #
```release-note
NONE
```
=> karmada operator: fixed karmada label beinging overwritten

charts/karmada/values.yaml, hack/package-helm-chart.sh
/kind flake
automatic modify image version in helm chart when releasing
Fixes #3912
@RainbowMango @XiShanYongYe-Chang 
```release-note
```
=> automatic modify image version in helm chart when releasing

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/controllers/context/context.go, pkg/controllers/execution/execution_controller.go, pkg/controllers/execution/execution_controller_test.go, pkg/controllers/status/work_status_controller.go, pkg/controllers/status/work_status_controller_test.go, pkg/resourceinterpreter/fake/fake.go, pkg/util/fedinformer/handlers.go, pkg/util/lifted/objectwatcher.go, pkg/util/memberclusterinformer/memberclusterinformer.go, pkg/util/memberclusterinformer/memberclusterinformer_test.go, pkg/util/objectwatcher/objectwatcher.go, pkg/util/objectwatcher/objectwatcher_test.go, test/helper/resource.go
/kind feature  
As #3807   
Fixes #3807   
Fixes #1362  
Fixes #3572   
Fixes #3587 
**Does this PR introduce a user-facing change?**: 
```release-note
NONE  
```
=> only update object in member cluster by execution controller

operator/README.md
Fixes #3956
```release-note
NONE
```
=> doc: add dependency-update for helm chart of operator

pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go, pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go, pkg/metrics/resource.go
/kind feature
add cron federated hpa metrics
part of https://github.com/karmada-io/karmada/issues/3946
CronFederatedHPA:
* the time cost of handling rules.
* the time cost of handling CronFederatedHPA.
```release-note
NONE
```
=> feat: add cron federated hpa metrics

pkg/metrics/resource.go, pkg/scheduler/metrics/metrics.go, pkg/scheduler/scheduler_metrics_test.go
/kind cleanup
Fixes #3981 
```release-note
```
=> Standardize metrics help message

pkg/apis/cluster/validation/validation.go, pkg/apis/cluster/validation/validation_test.go
/kind cleanup
Add validation for zones
part of #3952
@XiShanYongYe-Chang @whitewindmills 
none
=> Add validation for zones

pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
/kind feature
adapt zones check in spread constraint plugin
part of https://github.com/karmada-io/karmada/issues/3952
```release-note
NONE
```
=> feat: adapt zones check in spread constraint plugin

charts/karmada/templates/_karmada-clusterrole.tpl, charts/karmada/templates/pre-install-job.yaml, charts/karmada/values.yaml
/kind bug
fix issue:https://github.com/karmada-io/karmada/issues/4006
last pr:https://github.com/karmada-io/karmada/pull/3957
Fixes #
```release-note
```
=> fix helm install clusterrole to wrong cluster

CODE_OF_CONDUCT.md
This PR syncs the code of conduct to the [primary one in the community repo](https://github.com/karmada-io/community/blob/main/CODE_OF_CONDUCT.md).
Fixes #
The community should have a single source of truth to declare the CoC.
```release-note
NONE
```
=> harmonize code of conduct to the primary one

docs/CHANGELOG/CHANGELOG-1.7.md
This PR updates v1.7.0 release notes.
Fixes #
```release-note
NONE
```
=> Update 1.7.0 release notes

docs/CHANGELOG/CHANGELOG-1.4.md
This PR updates the release notes for the coming v1.4.5.
Fixes #
This is probably the last release for 1.4 as we just maintain the latest 3 releases(for now it's 1.5, 1.6, 1.7).
```release-note
NONE
```
=> Update release notes for v1.4.5

docs/CHANGELOG/CHANGELOG-1.4.md, docs/CHANGELOG/CHANGELOG-1.5.md
This PR updates the release notes for the coming v1.5.4.
Fixes #
```release-note
NONE
```
=> Update release notes for v1.5.4

docs/CHANGELOG/CHANGELOG-1.4.md, docs/CHANGELOG/CHANGELOG-1.5.md, docs/CHANGELOG/CHANGELOG-1.6.md
This PR updates the release notes for the coming v1.6.3.
Fixes #
```release-note
NONE
```
=> Update release notes for v1.6.3

docs/CHANGELOG/CHANGELOG-1.4.md, docs/CHANGELOG/CHANGELOG-1.5.md, docs/CHANGELOG/CHANGELOG-1.6.md
This PR updates the release notes for the coming patch releases:
- release-1.4  v1.4.5
- release-1.5 v1.5.4
- release-1.6 v1.6.3
Fixes #
```release-note
NONE
```
=> Update release notes for v1.4.5, v1.5.4, 1.6.3

artifacts/deploy/karmada-controller-manager.yaml
Enable preemption feature in development environment
Fixes #4068
```release-note
NONE
```
=> Enable preemption feature in development environment karmada-controller-manager.yaml

charts/index.yaml
/kind bug
I am unable to pull helm chart v1.7.0
```
Error: accumulating resources: accumulation err='accumulating resources from '../base/': '/Users/amir.alavi/workspace/k8s-clusterset/kustomize/base' must resolve to a file': recursed accumulation of path '/Users/amir.alavi/workspace/k8s-clusterset/kustomize/base': Error: chart "karmada" version "v1.7.0" not found in https://raw.githubusercontent.com/karmada-io/karmada/master/charts repository
: unable to run: 'helm pull --untar --untardir <REDACTED> --repo https://raw.githubusercontent.com/karmada-io/karmada/master/charts karmada --version v1.7.0' with env=[HELM_CONFIG_HOME=/var/folders/br/29sycb5x187cxxnqd9w1m5dm0000gp/T/kustomize-helm-1598116109/helm …
```
=> helm: index 1.7

pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller.go, pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller_test.go, pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
/kind cleanup  
As https://github.com/karmada-io/karmada/issues/4057#issuecomment-1728646530  
Fixes #
```release-note
```
=> use status.DesiredReplicas instead of status.CurrentReplicas of HPA to update resource scale

api/openapi-spec/swagger.json, hack/tools/swagger/generateswagger.go, hack/update-codegen.sh, pkg/apis/autoscaling/v1alpha1/well_known_constants.go, pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go, pkg/generated/openapi/zz_generated.openapi.go
update swagger json
part of #4090
@XiShanYongYe-Chang @jwcesign  ~Do you have any idea about this error：~
**updated:** I have fixed the above error, by adding `--input-dirs "k8s.io/api/autoscaling/v2"` into `hack/update-codegen.sh`, and then re-generate the `pkg/generated/openapi/zz_generated.openapi.go`. （now ready to review）
```release-note
none
```
=> update swagger json

go.mod, pkg/util/worker.go, pkg/util/worker_test.go
/kind cleanup  
As https://github.com/karmada-io/karmada/issues/3959
Fixes #3959 
```release-note
```
=> remove unnecessary maxRetry for AsyncWorker

.github/workflows/ci-schedule-compatibility.yaml, .github/workflows/ci-schedule.yml
*What type of PR is this?**
/kind flake
Handling or maximizing github runner out-of-disk space error.
same as #4106
Fixes #4107
```release-note
none
```
=> clean ci runner disk space

pkg/karmadactl/unjoin/unjoin.go
/kind cleanup
Fixes #4122
```release-note
NONE
```
=> Fix incorrect comments in unjoin command

.github/workflows/ci-schedule-compatibility.yaml
=> APIServer compatibility for release-1.7

docs/proposals/resource-deletion-protection/README.md
Refine resource deletion protection proposal
Fixes #
```release-note
NONE
```
=> Refine resource deletion protection proposal

docs/CHANGELOG/CHANGELOG-1.6.md, docs/CHANGELOG/CHANGELOG-1.7.md
We are going to tag the new patch releases, this PR updates the release notes:
- v1.6.4 based on release-1.6 including [all these changes](https://github.com/karmada-io/karmada/compare/v1.6.3...release-1.6).
- v1.7.1 based on release-1.7 including [all these changes](https://github.com/karmada-io/karmada/compare/v1.7.0...release-1.7). 
Note: Patch release for release-1.5 is ignored, because no notable user-facing change since v1.5.4.
Fixes #
```release-note
NONE
```
=> Update release notes for v1.6.4, v1.7.1

operator/config/samples/karmada.yaml, operator/pkg/constants/constants.go, operator/pkg/tasks/init/karmadaresource.go, operator/pkg/util/util.go, operator/pkg/util/util_test.go
/kind bug
Fixes #4129
```release-note
`karmada-operator`: Fixed can not load Karmada v1.7.0 crds issue.
```
=> Operator support work with crds v1.7.0

docs/CHANGELOG/CHANGELOG-1.6.md
This PR updates the release notes for coming v1.6.4 against `release-1.6`.
Fixes #
```release-note
NONE
```
=> Update Release notes for v1.6.4

docs/CHANGELOG/CHANGELOG-1.7.md
This PR updates the release notes for coming v1.7.1 against `release-1.7`.
Fixes #
```release-note
NONE
```
=> Update release notes for v1.7.1

test/e2e/framework/deployment.go, test/e2e/framework/namespace.go, test/e2e/resource_deletion_protection_test.go
add e2e test for resource deletion protection https://github.com/karmada-io/karmada/pull/4074
Part of https://github.com/karmada-io/karmada/issues/3728
```release-note
```
=> [e2e] add resource deletion protection e2e test

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml, docs/proposals/resource-interpreter-webhook/README.md, pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go, pkg/apis/search/v1alpha1/searchregistry_types.go, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
During the translation of the API documentation, some spelling errors were discovered.
Fixes #
```release-note
NONE
```
=> update type in api definition

pkg/karmadactl/cmdinit/kubernetes/deploy.go
/kind cleanup
Fixes #
https://github.com/karmada-io/karmada/issues/4186
```release-note
NONE
```
=> gen certs remove ip 10.254.0.1

pkg/controllers/cluster/cluster_controller.go
Avoid removing clusters that are not ready or in an unknown state in pull mode, resulting in blockages and stuck failures. When the syncmode mode is pull and the cluster is not ready or in an unknown state, delete the finalizers of the work object directly
Fixes #1847 
@lonelyCZ 
```release-note
None
```
=> fix: The PULL mode cluster cannot be deleted immediately

docs/proposals/dependencies-automatically-propagation/README.md, docs/proposals/hpa/cronfederatedhpa.md, docs/proposals/mcs/remove-derived-mcs.md, docs/proposals/migration/design-of-seamless-cluster-migration-scheme.md, docs/proposals/resource-interpreter-webhook/README.md, docs/proposals/scheduling/521-scheduler-estimator/README.md, docs/proposals/scheduling/697-descheduler/README.md, docs/proposals/scheduling/multi-scheduling-group/README.md, test/e2e/aggregatedapi_test.go, test/e2e/federatedresourcequota_test.go, test/e2e/karmadactl_test.go, test/e2e/namespace_test.go, test/e2e/rescheduling_test.go, test/e2e/search_test.go
=> fix spell error in test and docs

test/e2e/framework/hpa.go, test/e2e/hpareplicassyncer_test.go, test/helper/resource.go
Add e2e to test hpa replicas syncer
Fixes #none
none
```release-note
```
=> e2e: add test case for hpa replicas syncer

.github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/lint-chart.yaml
Cherry pick of #4201 on release-1.7.
#4201: * Update chart-testing-action to v2.6.0
```release-note
NONE
```
=> [1.7] Automated cherry pick of #4201: * Update chart-testing-action to v2.6.0

operator/pkg/controller/karmada/planner.go, operator/pkg/deinit.go, operator/pkg/init.go, operator/pkg/util/kubeconfig.go
/kind feature
support install karmada on remote cluster
Fixes https://github.com/karmada-io/karmada/issues/3783
```release-note
`karmada operator`: Now able to install karmada on a remote cluster.
```
=> karmada operator: support install karmada on remote cluster

pkg/util/proxy/proxy.go, test/e2e/framework/karmadactl.go, test/e2e/karmadactl_test.go, test/e2e/suite_test.go, test/helper/resource.go
/kind bug
Fixes https://github.com/karmada-io/karmada/issues/4197
* Fix exec failure.
* Add karmadctl e2e framework.
Part of  #https://github.com/karmada-io/karmada/issues/4197
none
```release-note
`karmada-aggregated-apiserver`: Fix exec failure with karamada-aggregated-apiserver.
```
=> fix: fix exec failure with karamada-aggregated-apiserver

pkg/util/helper/workstatus.go
/kind bug  
The cache may be outdated before updating status of bindings, and we should only update the aggregated status and conditions, otherwise the other parts may be overridden.  
Fixes #
```release-note
```
=> only update necessary part of binding status

test/e2e/karmadactl_test.go
/kind cleanup
Using real karmadactl command is a better idea
Fixes #none
none
```release-note
```
=> e2e: adjust karmadactl e2e to use real command

pkg/util/helper/workstatus.go
Cherry pick of #4226 on release-1.7.
#4226: only update necessary part of binding status
```release-note
`karmada-controller-manager`: only update `aggregatedStatus` and `conditions` fields during `binding-status controller` updating status of binding 
```
=> Automated cherry pick of #4226: only update necessary part of binding status

pkg/search/proxy/store/util.go
Cherry pick of https://github.com/karmada-io/karmada/pull/4212 on release-1.7.
```
karmada-search`: Fix lock race affects watch RestChan not close, causing client watch api to hang
```
=> cherry pick of #4212: Fix lock race affects watch RestChan not close, causing client watch api to hang.

hack/verify-codegen.sh
/kind cleanup
We forget to check the generated code of operator
Fixes #none
none
```release-note
```
=> sh: verify operator code generation

test/e2e/karmadactl_test.go
/kind cleanup
e2e: adjust all karmadactl e2e to use real karmadactl command
Fixes #none
none
```release-note
```
=> e2e: adjust all karmadactl e2e to use real karmadactl command

pkg/scheduler/core/assignment.go, pkg/scheduler/core/assignment_test.go, pkg/scheduler/core/division_algorithm.go, pkg/util/helper/binding.go, pkg/util/helper/binding_test.go
/kind feature
divide replicas by static weight evenly
code implementation of proposal #4218
```release-note
```
=> implementation : divide replicas by static weight evenly

artifacts/deploy/karmada-aggregated-apiserver.yaml, artifacts/deploy/karmada-apiserver.yaml, artifacts/deploy/karmada-metrics-adapter.yaml, artifacts/deploy/karmada-search.yaml, charts/karmada/templates/karmada-aggregated-apiserver.yaml, charts/karmada/templates/karmada-apiserver.yaml, charts/karmada/templates/karmada-search.yaml, operator/pkg/controlplane/apiserver/mainfests.go, operator/pkg/controlplane/metricsadapter/mainfests.go
/kind cleanup
Part of #4191 
```release-note
Security enhancement.
```
=> set MinVersion to VersionTLS13 for tlsconfig

.github/workflows/OWNERS, charts/OWNERS, hack/OWNERS, operator/OWNERS, pkg/karmadactl/cmdinit/OWNERS, pkg/karmadactl/top/OWNERS, pkg/util/OWNERS
/kind cleanup
Nominate guys who are committing efforts to review PRs as the code owner:
- @chaosi-zju 
- @jwcesign 
- @whitewindmills 
- @chaunceyjiang
- @XiShanYongYe-Chang 
Fixes #
```release-note
NONE
```
=> Nominate code owners

README.md
doc: Add KubeCon talks to readme
Fixes #none
```release-note
```
=> doc: Add KubeCon talks to readme

docs/proposals/scheduling/replicas-assign/divide-replicas-by-static-weight-evenly.md
/kind design
divide replicas by static weight evenly
Fixes #
```release-note
```
=> proposal: divide replicas by static weight evenly

hack/local-up-karmada.sh
/kind cleanup
Fixes #
```release-note
None
```
=> fix a typo

hack/util.sh
/kind bug
Fixes #4311
```release-note
NONE
```
=> Fix local-up-karmada.sh is not working.

operator/pkg/util/apiclient/idempotency.go
/kind bug
If the operator reconcile again when failed to install karmada, the updation of service will conflict.
Fixes https://github.com/karmada-io/karmada/issues/4125
```release-note
karmada-operator: resolve resource version conflict when updating serivce
```
=> karmada-operator: resolve resource version conflict when updating serivce

.github/workflows/ci-schedule.yml, .github/workflows/ci.yml, .github/workflows/cli.yaml, .github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/release.yml, .github/workflows/swr-latest-image.yml, .github/workflows/swr-released-image.yml
/kind cleanup
Fixes #4331 
```release-note
Karmada(v1.8) is now built with Go1.20.11. 
```
=> upgrade golang version to v1.20.11

charts/karmada/templates/_karmada_webhook_configuration.tpl, operator/pkg/karmadaresource/webhookconfiguration/manifests.go, pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
/kind feature
none
```release-note
```
=> feat: add webhook for multiclusterservice to add the permanentid

test/e2e/framework/mcs.go, test/e2e/mcs_test.go, test/e2e/suite_test.go, test/helper/resource.go
/kind cleanup
Hold before https://github.com/karmada-io/karmada/pull/4329
```release-note
```
=> e2e: add mcs e2e with CrossCluster type

pkg/controllers/multiclusterservice/endpointslice_collect_controller.go, pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go, pkg/controllers/multiclusterservice/mcs_controller.go, pkg/util/constants.go, test/e2e/mcs_test.go
/kind cleanup
cleanup: change MultiClusterService corresponding label
Fixes #none
none
```release-note
```
=> cleanup: change MultiClusterService corresponding label

docs/CHANGELOG/CHANGELOG-1.8.md
This PR adds the release notes of release-1.8.
Fixes #
This release includes 230+ commits from 30+ contributors, see the full list of commits [here](https://github.com/karmada-io/karmada/compare/v1.8.0-alpha.0...master).
```release-note
NONE
```
=> Add changelog of release-1.8

cmd/controller-manager/app/controllermanager.go
/kind bug
/kind cleanup
Fix wrong feature gate writing with MultiClusterService. Introduced by #4347
Fixes #
```release-note
NONE
```
=> fix wrong featuregate writing with MultiClusterService

pkg/util/lifted/deployment_test.go, pkg/util/lifted/federatedhpa.go, pkg/util/lifted/federatedhpa_test.go, pkg/util/lifted/lua_oslib_safe.go, pkg/util/lifted/validatingfhpa.go, pkg/util/lifted/validatingmci_test.go
/kind bug
correct the license in the lifted directory
Parts of #4345
NONE
```release-note
NONE
```
=> correct the license in the lifted directory

test/e2e/mcs_test.go, test/helper/resource.go
/kind cleanup
cleanup: cleanup e2e of mcs
Fixes #none
```release-note
```
=> cleanup: cleanup e2e of mcs

pkg/controllers/multiclusterservice/endpointslice_collect_controller.go, pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
/kind cleanup
cleanup: make the name unified of mcs
Fixes #none
```release-note
```
=> cleanup: make the name unified of mcs

charts/karmada/README.md
Paragraph segmentation blurs, making it clearer.
Fixes #none
```release-note
```
=> doc: make the chart installation doc easier to understand.

test/e2e/search_test.go
e2e: Fix the occasional failure of mcs e2e
Please refer to: https://github.com/karmada-io/karmada/pull/4342#issuecomment-1835716549
Fixes none
```release-note
```
=> e2e: Fix the occasional failure of mcs e2e

.github/workflows/ci-schedule-compatibility.yaml
/kind cleanup
The latest version of karmada is updated to 1.8, so ```CI``` should also be updated.
Fixes #
NONE
```release-note
NONE
```
=> update karmada-version to 1.8 in CI

hack/cli-testing-environment.sh
directly make image from current source code in CLI ci pipeline
otherwise, CLI ci pipeline always pull released images, not enough to verify functionality
Fixes #
```release-note
```
=> Let cli testing based on current source code

pkg/scheduler/core/generic_scheduler_test.go
add test for static weight random remainder.
```release-note
```
=> add test for static weight random remainder.

test/e2e/search_test.go
Cherry pick of #4363 on release-1.8.
#4363: e2e: Fix the occasional failure of mcs e2e
```release-note
```
=> Automated cherry pick of #4363: e2e: Fix the occasional failure of mcs e2e

test/e2e/framework/constant.go, test/e2e/framework/pod.go, test/e2e/karmadactl_test.go
/kind cleanup
add e2e test for command ```karmadactl top pod```
Parts of #4223
NONE
```release-note
NONE
```
=> e2e: add e2e test for command karmadactl top pod

pkg/scheduler/core/generic_scheduler_test.go
add expand replicas test about even distribution of replicas
Fixes #4220
```release-note
```
=> add expand replicas test about even distribution of replicas

README.md
/kind cleanup
Karmada's incubation vote has passed :tada::tada::tada:, so this PR is working for update sandbox of README  to incubation.
Also we can waiting the PR https://github.com/cncf/toc/pull/986 is merged if necessary. 
Fixes #
```release-note
NONE
```
=> Update sandbox to incubation.

hack/util.sh
/kind cleanup
Please see: https://github.com/karmada-io/karmada/issues/4408
Fixes https://github.com/karmada-io/karmada/issues/4408
none
```release-note
```
=> fix: generate the code in correct path

MAINTAINERS.md
This PR adds Xiao Zhang(@wawa0210) to the maintainer list as per the vote result at https://github.com/karmada-io/community/issues/55.
Fixes #
```release-note
NONE
```
=> Put Xiao Zhang to the maintainer list

pkg/scheduler/core/generic_scheduler_test.go
add scale down test for even distribution of replicas
Fixes  part of #4220
```release-note
```
=> add scale down test for even distribution of replicas

.github/workflows/ci.yml, docs/CHANGELOG/CHANGELOG-1.5.md
This PR adds release notes for the coming v1.5.5 releases.
See the full change log from [here](https://github.com/karmada-io/karmada/compare/v1.5.4...release-1.5).
Fixes #
v1.5.5 will be the last patch release from release-1.5 as we only maintain 3 minor releases that are release-1.6~1.8.
```release-note
NONE
```
=> Add release notes of v1.5.5

docs/CHANGELOG/CHANGELOG-1.6.md
This PR adds release notes for the coming v1.6.5 releases.
See the full change log from [here](https://github.com/karmada-io/karmada/compare/v1.6.4...release-1.6).
Fixes #
```release-note
NONE
```
=> Add release notes of v1.6.5

docs/CHANGELOG/CHANGELOG-1.7.md
This PR adds release notes for the coming v1.7.2 releases.
See the full change log from [here](https://github.com/karmada-io/karmada/compare/v1.7.1...release-1.7).
Fixes #
```release-note
NONE
```
=> Add release notes of v1.7.2

docs/CHANGELOG/CHANGELOG-1.5.md, docs/CHANGELOG/CHANGELOG-1.6.md, docs/CHANGELOG/CHANGELOG-1.7.md, docs/CHANGELOG/CHANGELOG-1.8.md
This PR updates the release notes for the coming patch releases: v1.5.5, v1.6.5, v1.7.2, v1.8.1.
Fixes #
```release-note
NONE
```
=> Add release notes of v1.5.5, v1.6.5, v1.7.2, v1.8.1

pkg/controllers/multiclusterservice/mcs_controller.go
/kind bug
When update mcs ExposureType from CrossCluster to LoadBalancer, we need to remove the finalizer.
If not, the resource can't be deleted
Fixes #none
none
```release-note
`karmada-controller-manager`: clean the finalizer of mcs if the ExposureType transforms from CrossCluster to LoadBalancer.
```
=> fix: clean the finalizer of mcs if the ExposureType transforms from CrossCluster to LoadBalancer

pkg/controllers/multiclusterservice/mcs_controller.go
/kind bug
mcs-controller will watch svc/mcs, and when svc is updated, it will put the mcs in the reconcile queue, which could cause the unexpected conflicts with Policy.
For example:(Code Analysis)
1.CPP propagate the svc, and there is RB.
2.MCS in the process of deletion.
3.svc is updated.
4.The rb will be deleted.
Fixes #none
```release-note
`karmada-controller-manager`: ignore reconcile the mcs(triggered by svc) if the mcs is not CrossCluster
```
=> fix: ignore reconcile the mcs(triggered by svc/cluster) if the mcs is not CrossCluster

pkg/scheduler/core/generic_scheduler_test.go
add change static weight test for even distribution of replicas
CC @XiShanYongYe-Chang 
```release-note
```
=> add change static weight test for even distribution of replicas

pkg/scheduler/core/generic_scheduler_test.go
test of even distribution of replicas for add cluster scenario
CC @XiShanYongYe-Chang 
```release-note
```
=> test of even distribution of replicas for add cluster scenario

test/OWNERS
/kind cleanup
Nominate @Vacant2333 as the code reviewer for the E2E module. He has been making continuous contributions to this module and actively reviewing others' code. 
Hope he can continue to be active in the community. :)
Fixes #
```release-note
NONE
```
=> Nominate E2E code owners

README.md
/kind cleanup
doc: fix readme typo
Fixes #none
none
```release-note
```
=> doc: fix readme typo

examples/customresourceinterpreter/README.md
Add notes for karmada resourceinterpreter webhook example README.
Fixes #4478
```release-note
NONE
```
=> Add notes for karmada resourceinterpreter webhook example README

api/openapi-spec/swagger.json, pkg/apis/work/v1alpha2/binding_types.go, pkg/apis/work/v1alpha2/zz_generated.deepcopy.go, pkg/controllers/gracefuleviction/evictiontask.go, pkg/controllers/gracefuleviction/evictiontask_test.go, pkg/generated/openapi/zz_generated.openapi.go
Fixes https://github.com/karmada-io/karmada/issues/4402
```
NONE
```
=> fix(work):  motify gracefulEvictionTasks sub field creationTimestamp to pointer type

.golangci.yml, pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller_test.go
/kind cleanup
cleanup: enable revive(error-strings) checking
```release-note
```
=> cleanup: enable revive(error-strings) checking

pkg/scheduler/framework/runtime/framework.go
/kind cleanup
Correct RunScorePlugins method code comments
Fixes #
```release-note
```
=> cleanup RunScorePlugins code comments

.golangci.yml
/kind cleanup
cleanup: enable revive(error-return) checking
```release-note
```
=> cleanup: enable revive(error-return) checking

.golangci.yml, test/e2e/framework/karmadactl.go
/kind cleanup
cleanup: enable revive(receiver-naming) checking
```release-note
```
=> cleanup: enable revive(receiver-naming) checking

.golangci.yml
/kind cleanup
cleanup: enable revive(increment-decrement) checking
```release-note
```
=> cleanup: enable revive(increment-decrement) checking

pkg/karmadactl/apply/apply.go, pkg/karmadactl/describe/describe.go, pkg/karmadactl/exec/exec.go, pkg/karmadactl/get/get.go, pkg/karmadactl/interpret/check_test.go, pkg/karmadactl/interpret/execute_test.go, pkg/karmadactl/interpret/interpret.go, pkg/karmadactl/karmadactl.go, pkg/karmadactl/logs/logs.go, pkg/karmadactl/token/token.go, pkg/karmadactl/token/token_test.go, pkg/karmadactl/top/top.go, pkg/karmadactl/top/top_pods.go, pkg/metricsadapter/controller.go, pkg/util/worker.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> clean up deprecated codes

.golangci.yml, pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler.go, pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/top/top_pods.go, pkg/webhook/cronfederatedhpa/validating.go
/kind cleanup
cleanup: enable revive(blank-imports/indent-error-flow rule) checking
Part of https://github.com/karmada-io/karmada/issues/4490
none
```release-note
```
=> cleanup: enable revive(blank-imports/indent-error-flow rule) checking

.golangci.yml
/kind cleanup
This PR enables linting for the unreachable code.
Part of #4490
```release-note
NONE
```
=> Add linting for unreachable code

pkg/util/fedinformer/typedmanager/single-cluster-manager.go
/kind cleanup
Avoid situations where RUnlock cannot be performed in the presence of an error.
Fixes #
```release-note
NONE
```
=> defer RUnlock

hack/update-estimator-protobuf.sh
/kind bug
fix the issue of invalid protobuf execution
Fixes #4529
```release-note
```
=> fix the issue of invalid protobuf execution

pkg/scheduler/core/generic_scheduler_test.go
test of even distribution of replicas for removing cluster scenario
CC @XiShanYongYe-Chang the last case for this feature
```release-note
```
=> test of even distribution of replicas for removing cluster scenario

.github/workflows/ci-schedule-compatibility.yaml, .github/workflows/ci-schedule.yml
/kind flake
In order to add log collector to diagnose the [workflow failure](https://github.com/karmada-io/karmada/actions/workflows/ci-schedule-compatibility.yaml).
Fixes #
```release-note
```
=> collect kind log for ci-schedule workflow

test/e2e/preemption_test.go
Fixes #3787
```release-note
NONE
```
=> Add preemption E2E test

pkg/karmadactl/register/register.go
/kind bug
pull mode register add check cluster exists
Fixes #
https://github.com/karmada-io/karmada/issues/4527
```release-note
```
=> pull mode register add check cluster exists

.github/workflows/OWNERS, hack/OWNERS, pkg/karmadactl/OWNERS, pkg/search/OWNERS
/kind cleanup
Nominate guys who are committing efforts to review PRs as the code owner:
- @liangyuanpeng (missed from #4260 due to membership issue)
- @yanfeng1992 (missed from #4260 due to membership issue)
- @zhzhuang-zju 
Fixes #
```release-note
NONE
```
=> Nominate Yuan peng, Zhuang, and Yan feng as new reviewers

pkg/printers/storage/storage.go, pkg/printers/storage/storage_test.go, pkg/search/proxy/framework/plugins/cache/cache.go, pkg/util/lifted/corev1printers.go, pkg/util/lifted/corev1printers_test.go
Fixes #
```release-note
Implement node/pod tableconvert.
other resource keep use defaultTableConvert.
```
=> Implement node/pod tableconvert

.golangci.yml
ref: 
#2717  
#822 
Add static check to report the deprecated warnings
Fixes #
```release-note
NONE(user not facing this change)
```
=> chores(deps): support depguard rules in golang-lint

operator/pkg/util/apiclient/idempotency.go
/kind bug
Fixes #
```release-note
```
=> correct print info

hack/.import-aliases, pkg/scheduler/framework/testing/mock_interface.go, pkg/util/lifted/corev1printers.go, pkg/util/lifted/corev1printers_test.go
/kind good first issue
Add autoscaling/v1alpha1 import alias and Passed the `hack/verify-import-aliases.sh`
Fixes #4619
This is my first PR, if you have any question, please feel free to chat with me.
```release-note
NONE
```
=> feat: update hack/.import-alias

docs/CHANGELOG/CHANGELOG-1.9.md
This PR adds the release notes of the coming v1.9.0.
Fixes #
```release-note
NONE
```
=> Add release notes of v1.9

charts/index.yaml
/kind feature
follow up to v1.9.0 release
```release-note
publish helm `v1.9.0` version
```
=> chore: publish helm `v1.9.0` version

hack/.import-aliases
/kind cleanup
Fix import alias for remedy.
Fixes #NONE
NONE
```release-note
NONE
```
=> Fix import alias for remedy

api/openapi-spec/swagger.json, hack/tools/swagger/generateswagger.go, hack/update-codegen.sh, pkg/apis/remedy/v1alpha1/well_known_constants.go, pkg/generated/openapi/zz_generated.openapi.go
/kind feature
Add remedy api in the `swagger.json` .
Fixes #
```release-note
NONE
```
=> Add remedy api in the swagger.json

docs/proposals/remediation/cluster-status-based-remedy.md
/kind design
Add proposal for cluster remedy feature.
Part of #4658
```release-note
NONE
```
=> Add proposal for remedy

operator/pkg/controlplane/search/mainfests.go, operator/pkg/util/apiclient/idempotency.go
/kind bug
Fixes #4672
```release-note
`karmada-operator`: Fixed the `karmada-search` can not be deleted issue due to missing `app.kubernetes.io/managed-by` label.
```
=> fix: delete search-component failed

docs/CHANGELOG/CHANGELOG-1.6.md, docs/CHANGELOG/CHANGELOG-1.7.md, docs/CHANGELOG/CHANGELOG-1.8.md
This PR adds the release notes of the coming v1.6.6, v1.7.3, and v1.8.2 releases.
Fixes #
```release-note
NONE
```
=> Add release notes of v1.6.6, v1.7.3, v1.8.2

.github/workflows/ci-schedule-compatibility.yaml, .github/workflows/ci-schedule.yml, .github/workflows/ci.yml, .github/workflows/cli.yaml, .github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/release.yml, .github/workflows/swr-latest-image.yml, .github/workflows/swr-released-image.yml, README.md, go.mod, go.sum, hack/util.sh
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/4704
```release-note
Karmada(v1.10) is now built with Go1.21.8. 
```
=> upgrade golang version to v1.21.8

pkg/controllers/remediation/eventhandlers_test.go, pkg/controllers/remediation/remedy_controller.go, pkg/controllers/remediation/util.go, pkg/controllers/remediation/util_test.go, vendor/modules.txt, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/doc.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/testing.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/unconventionallisttypecrd.go, vendor/sigs.k8s.io/controller-runtime/pkg/controller/controllertest/util.go
/kind cleanup
- Add UT for remedy util function.
- Add UT for remedy controller event handler
Part of #4658
```release-note
NONE
```
=> Add UT for remedy util function and eventhandler

pkg/karmadactl/cmdinit/karmada/deploy.go, pkg/karmadactl/cmdinit/karmada/rbac.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> fix typo for karmadactl cmdinit

test/e2e/deploymentreplicassyncer_test.go, test/e2e/framework/hpa.go, test/helper/policy.go
add e2e test for deployment replicas syncer
Fixes #
```release-note
```
=> add e2e test for deployment replicas syncer

pkg/karmadactl/addons/init/global.go
/kind cleanup
Add more detail log for load karmada-host config and karmada-apiserver config.
Fixes #4684
```release-note
```
=> Add more detail log for load karmada-host config and karmada-apiserver config.

.github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml
/kind cleanup
Fixes #4727
I have verify this can resolve the problem.
check https://github.com/liangyuanpeng/karmada/actions/runs/8360167828/job/22885221022 , step of `Install Cosign`
```release-note
```
=> chore: Update sigstore/cosign-installer to v3.4.0.

pkg/resourceinterpreter/default/native/replica.go
/kind bug
The error log output format is missing parameters.
Fixes #
None
```release-note
```
=> Fix replica interpreter err log format

.github/workflows/OWNERS
/kind cleanup
Add myself to approver for github workflows.
I'm interesting in github workflows and have had multiple PRs and reviews on it And Still working on this in the future.
Fixes #
```release-note
```
=> Add liangyuanpeng to approver for github workflows.

pkg/apis/policy/v1alpha1/well_known_constants.go, pkg/apis/work/v1alpha2/well_known_constants.go, pkg/controllers/binding/common.go, pkg/detector/detector.go, pkg/util/helper/work.go, pkg/util/label.go
/kind cleanup
Partof https://github.com/karmada-io/karmada/issues/4711
TODO: relaese-note for user?
Fixes #
```release-note
The following labels have been removed and replaced by replacements respectively:
- `propagationpolicy.karmada.io/uid`, replaced by `propagationpolicy.karmada.io/permanent-id`;
- `clusterpropagationpolicy.karmada.io/uid`, replaced by `clusterpropagationpolicy.karmada.io/permanent-id`
- `resourcebinding.karmada.io/uid`, replaced by `resourcebinding.karmada.io/permanent-id`
- `clusterresourcebinding.karmada.io/uid`, replaced by `clusterresourcebinding.karmada.io/permanent-id`
- …
```
=> Delete the labels of uid.

.github/dependabot.yml
/kind cleanup
Let dependabot work for auto update github-actions to get rid of deprecated github actions.
Releated: https://github.com/karmada-io/karmada/issues/4669
Fixes #
```release-note
```
=> Add config for dependabot.

.github/workflows/release.yml
/kind cleanup
Stop krew update on release-1.7, see #4703 for more details.
Fixes #
```release-note
NONE
```
=> Stop krew update for release-1.7

.github/workflows/release.yml
/kind cleanup
Stop krew update on release-1.8, see #4703 for more details.
Fixes #
```release-note
NONE
```
=> Stop krew update for release-1.8

pkg/controllers/mcs/service_export_controller.go
/kind bug
The last few CI runs have been failing frequently, for example: https://github.com/karmada-io/karmada/actions/runs/8463439534/job/23186473124
Through analysis, it is found that a bug was introduced in #4737, which will cause when creating another new ServiceEport, it will mistakenly delete the endpointslice that collected by other ServiceExports.
Fixes #
```release-note
NONE
```
=> fix bug of wrong delete endpointslice collect from member cluster

test/e2e/suite_test.go
This PR corrects a small documentation error. 
Fixes small documentation errors. 
Fixes #4775
None
```release-note
NONE
```
=> Corrected poll timeout example

pkg/detector/detector.go
/kind cleanup
When creating or updating CRB, we should use the func `retry.RetryOnConflict`, that keeps same with RB.
```release-note
NONE
```
=> Use RetryOnConflict for applying CRB

pkg/controllers/status/work_status_controller.go, pkg/controllers/status/work_status_controller_test.go
Follow up the [comment](https://github.com/karmada-io/karmada/pull/4765#discussion_r1543800815)
cc @XiShanYongYe-Chang 
Fixes #
```release-note
```
=> Rename a function to match with updated behavior

docs/proposals/scheduling/activation-preference/lazy-activation-preference.md, test/e2e/lazy_activation_policy_test.go
/kind cleanup
- udpate lazy-activation-preference.md 
refer to https://github.com/karmada-io/karmada/pull/4804#discussion_r1566624578
- update the link in lazy_activation_policy_test.go
refer to https://github.com/karmada-io/karmada/pull/4804#discussion_r1568131752
Fixes #
```release-note
```
=> update lazy-activation-preference.md and lazy_activation_policy_test.go

hack/verify-staticcheck.sh
/kind cleanup
Many times, facing golangci-lint errors, such as ```File is not `gci`-ed with --skip-generated -s Standard -s Default -s Prefix```, do not know its meaning, and therefore do not know the specific modification method. At this time, we can automatically fix it through command `golangci-lint run --fix`, and we can understand the reason for the error by viewing the modification points through git diff.
Fixes #
Take #4622 for example，
```shell
(base) ➜  karmada git:(revive) ✗ hack/verify-staticcheck.sh 
Using golangci-lint version:
golangci-lint has version 1.52.2 built with go1.20.2 from da04413a on 2023-03-25T18:11:28Z …
```
=> provide a tips to fix golangci-lint error

pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cmdinit/utils/deploy.go
/kind cleanup
cc @zhzhuang-zju
Add the common code for karmadactl create deployment.
Fixes #
```release-note
```
=> karmadactl: add common code for create and wait deployments.

.github/workflows/ci.yml
/kind flake
upgrade `arduino/setup-protoc` from v1 to v3.
For related discussion see #4856
Fixes #
```release-note
```
=> upgrade arduino/setup-protoc from v1 to v3

docs/CHANGELOG/CHANGELOG-1.7.md, docs/CHANGELOG/CHANGELOG-1.8.md, docs/CHANGELOG/CHANGELOG-1.9.md
This PR updates the release notes for the coming patch releases: v1.7.4, v1.8.3, v1.9.1.
Fixes #none
```release-note
```
=> Add release notes of v1.7.4, v1.8.3, v1.9.1

.github/workflows/cli.yaml, .github/workflows/lint-chart.yaml, go.mod, go.sum, hack/local-up-karmada.sh, vendor/modules.txt, vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/kubeadminit/init.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/common/getport.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/provision.go, vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provision.go, vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go, vendor/sigs.k8s.io/kind/pkg/internal/apis/config/validate.go
/kind cleanup
This PR updates the kind and pin to the released version.
part of https://github.com/karmada-io/karmada/issues/4907
```release-note
NONE
```
=> Bump kind to v0.22.0

pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
**DO NOT MERGE** until the following PR have been merged: 
* #4875
/kind feature
feat: support update event in WorkloadRebalancer
When spec filed of WorkloadRebalancer updated, we shall refresh the workload list in status.observedWorkloads:
1. a new workload added to spec list, just add it into status list too and do the rebalance.
2. a workload deleted from previous spec list, keep it in status list if already success, and remove it if not.
3. a workload is modified, just regard it as deleted an old one and inserted a new one.
4. just list order is disrupted, no additional action.
Fixes  part of #4840 …
=> feat: support update event in WorkloadRebalancer

pkg/controllers/binding/common.go, pkg/controllers/binding/common_test.go, pkg/controllers/certificate/cert_rotation_controller.go, pkg/controllers/cluster/cluster_controller.go, pkg/controllers/execution/execution_controller.go, pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go, pkg/controllers/mcs/service_export_controller.go, pkg/controllers/multiclusterservice/endpointslice_collect_controller.go, pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go, pkg/controllers/multiclusterservice/mcs_controller.go, pkg/controllers/namespace/namespace_sync_controller.go, pkg/controllers/status/work_status_controller.go, pkg/controllers/unifiedauth/unified_auth_controller.go, pkg/util/helper/work.go, pkg/webhook/work/mutating.go
/kind cleanup
This PR mainly migrates the adding action of work-related labels and annotations to webhook. Let's focus on these labels and annotations in the work mutating, which make it easier to maintain.
```release-note
NONE
```
=> Use webhook to set associated labels and annotations of work

cmd/metrics-adapter/app/options/options.go, pkg/metricsadapter/controller.go, pkg/scheduler/scheduler.go
/kind cleanup
/kind bug
we forget to call `shutdown` to close workqueue in these two components.
* karmada-scheduler
* karmada-metrics-adapter
Fixes #
```release-note
NONE
```
=> Call shutdown after being stopped

pkg/resourceinterpreter/default/native/retain_test.go
/kind cleanup
Moving the unit tests from PR #4847
Fixes #
```release-note
NONE
```
=> unit test for interpreter retain (pv, pvc)

pkg/karmadactl/register/register.go
no special operation, this pr just remove duplicate pkg ref in karmadactl
Fixes #
NONE
```release-note
```
=> clean: remove duplicate util reference

test/e2e/framework/resourcebinding.go, test/e2e/framework/workloadrebalancer.go, test/e2e/suite_test.go, test/e2e/workloadrebalancer_test.go, test/helper/resource.go
add e2e for WorkloadRebalancer
Fixes part of #4840
```release-note
```
=> add e2e for WorkloadRebalancer

pkg/karmadactl/token/token.go
/kind cleanup
cleanup: adjust log print content when delete token by karmadactl.
These logs are misleading for users and security scanning tools, and can easily be mistaken for sensitive information such as printing `tokenID`.
Fixes #
```release-note
```
=> cleanup: adjust log print content when delete token by karmadactl

hack/tools/genkarmadactldocs/gen_karmadactl_docs.go, hack/tools/lifted-gen/lifted-gen.go, operator/pkg/util/util.go, pkg/karmadactl/cmdinit/utils/format.go, pkg/karmadactl/cmdinit/utils/util.go, pkg/util/constants.go
/kind cleanup
cleanup: grant the correct permissions when creating a file
Fixes #
```release-note
```
=> cleanup: grant the correct permissions when creating a file

ROADMAP.md
/kind cleanup
This PR updates the roadmap for the year 2024. 
Fixes #
```release-note
NONE
```
=> Update roadmap of 2024

operator/pkg/util/apiclient/wait.go, pkg/controllers/cluster/cluster_controller.go, pkg/karmadactl/cmdinit/karmada/check.go, pkg/karmadactl/util/check.go, test/e2e/clusteraffinities_test.go, test/e2e/failover_test.go, test/e2e/framework/cluster.go, test/e2e/mcs_test.go, test/e2e/namespace_test.go, test/e2e/propagationpolicy_test.go, test/e2e/resourceinterpreter_test.go, test/e2e/scheduling_test.go, test/e2e/suite_test.go, test/helper/request.go
/kind cleanup 
This PR is replace `wait.PollImmediate` to `wait.PollUntilContextTimeout`
Ref: https://github.com/karmada-io/karmada/issues/3835
Fixes #
```release-note
```
=> migrate wait.PollImmediate to wait.PollUntilContextTimeout

pkg/scheduler/scheduler.go
/kind feature
we should skip schedule deleting bindings cause it makes no sense.
Fixes #
```release-note
NONE
```
=> Skip schedule deleting bindings

hack/deploy-karmada.sh
/kind bug
Fixes #2722
```release-note
NONE
```
=> Bump cfssl

pkg/util/helper/work.go, pkg/webhook/work/mutating.go
/kind bug
/kind cleanup
Fixes #5003
```release-note
NONE
```
=> fix upgrade error with #5003

docs/CHANGELOG/CHANGELOG-1.10.md, docs/CHANGELOG/CHANGELOG-1.9.md
This PR adds the release notes of the coming v1.10.0.
Fixes #
```release-note
NONE
```
=> Add release notes of v1.10

docs/CHANGELOG/CHANGELOG-1.7.md, docs/CHANGELOG/CHANGELOG-1.8.md, docs/CHANGELOG/CHANGELOG-1.9.md
Add release notes of v1.7.5, v1.8.4, v1.9.2
Fixes #
```release-note
```
=> Add release notes of v1.7.5, v1.8.4, v1.9.2

.github/workflows/release.yml
/kind cleanup
Stop krew update on branch release-1.9, see #4703 for more details.
Fixes #
```release-note
NONE
```
=> Stop krew update for release-1.9

cmd/OWNERS, pkg/apis/OWNERS, pkg/controllers/OWNERS, pkg/resourceinterpreter/default/thirdparty/OWNERS, pkg/scheduler/OWNERS
/kind cleanup
This PR nominates @whitewindmills @yike21 as per their focus area.
Fixes #
```release-note
NONE
```
=> nominate code owners of scheduler, resourceinterpreter, apis

hack/tools/genkarmadactldocs/gen_karmadactl_docs.go, pkg/controllers/federatedhpa/metrics/client.go, pkg/controllers/multiclusterservice/endpointslice_collect_controller.go, pkg/search/proxy/framework/plugins/cluster/cluster.go, pkg/util/hash/hash.go, pkg/util/lifted/validatingmcs.go, pkg/util/proxy/upgrader.go, test/e2e/framework/karmadactl.go
/kind cleanup
fix code inspection errors
Fixes #
```release-note
NONE
```
=> fix code inspection errors

docs/CHANGELOG/CHANGELOG-1.10.md, docs/CHANGELOG/CHANGELOG-1.9.md
Add release notes of v1.9.3，v1.10.1
Fixes #
```release-note
NONE
```
=> Add release notes of v1.9.3，v1.10.1

README.md
/kind cleanup
Part of #5048
```release-note
NONE
```
=> [License]Add foaas badge in README.md

README.md
/kind cleanup
Part of #5048
See the [preview here](https://github.com/B1F030/karmada/blob/clomonitor/README.md).
```release-note
NONE
```
=> Modify OpenSSF Scorecard badge

pkg/controllers/mcs/endpointslice_controller.go
/kind feature
Fixes #5038
```release-note
`karmada-controller-manager`: Added work namespace/name annotation in the endpointslice resources to explain which work is associated
```
=> add work namespace/name annotations in the endpointslice resources

pkg/karmadactl/join/join.go
/kind feature
otherwise I need to setup a special context and use-context to be able to use join
Partially deals with #4695
```release-note
karamdactl join: add --karmada-context --karmada-as --karmada-as-group --karmada-as-uid
```
=> add --as-* options to join command

.github/dependabot.yml, .github/workflows/ci-schedule-compatibility.yaml
/kind cleanup
/kind cleanup: Update CI for Karmada 1.10 and remove release-1.7
Fixes #5060
=> Update ci 1.10

test/e2e/framework/cluster.go, test/e2e/remedy_test.go
Fix occasional e2e error for updating cluster conflict error in the remedy e2e test, ref: https://github.com/karmada-io/karmada/pull/5100#issuecomment-2194007161
Fixes #
```release-note
NONE
```
=> fix update cluster conflict error in the remedy e2e test

artifacts/kindClusterConfig/member3.yaml, hack/local-up-karmada.sh
/kind bug
ref to: https://github.com/karmada-io/karmada/issues/5052
Fixes https://github.com/karmada-io/karmada/issues/5052
**Does this PR introduce a user-facing change?**: None
=> fix:  fix the problem that local-up pull cluster cann't be managed by control plan in macos device

docs/CHANGELOG/CHANGELOG-1.10.md, docs/CHANGELOG/CHANGELOG-1.8.md, docs/CHANGELOG/CHANGELOG-1.9.md
/kind cleanup
Add release notes of v1.8.5, v1.9.4, v1.10.2
Fixes #NONE
```release-note
NONE
```
=> Add release notes of v1.8.5, v1.9.4, v1.10.2

charts/karmada/templates/_helpers.tpl, charts/karmada/templates/karmada-descheduler.yaml, charts/karmada/templates/karmada-scheduler-estimator.yaml, charts/karmada/templates/karmada-scheduler.yaml
/kind feature
We have implemented grpc's certificate authentication in the following installation：
- Installation from Source
- Installation of CLI Tools
- Install Karmada by Karmada Operator 
and the installation of Helm Chart needs to be adapted as well.
Fixes #5041
```release-note
```
=> charts: Adding TLS Certificate Authentication to gRPC

.github/workflows/release.yml
Cherry pick of #5110 on release-1.10.
#5110: add sbom to release assests
```release-note
```
=> Automated cherry pick of #5110: add sbom to release assests

.github/workflows/lint-chart.yaml
/kind feature
Part of #5048
```release-note
NONE
```
=> Define top level Permission for lint-chart.yaml (Chart Lint) workflow

operator/pkg/certs/certs.go
Improve code reusability
Fixes #
```release-note
NONE
```
=> Improve code reusability

pkg/apis/autoscaling/v1alpha1/cronfederatedhpa_types.go, pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go, pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler.go, pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go, pkg/registry/cluster/storage/aggregate.go, pkg/util/helper/cronfederatedhpa.go, pkg/util/lifted/discovery_test.go, pkg/webhook/cronfederatedhpa/validating.go, pkg/webhook/resourcedeletionprotection/validating.go, test/e2e/cronfederatedhpa_test.go, test/e2e/federatedhpa_test.go, test/e2e/framework/cronfederatedhpa.go, test/e2e/framework/federatedhpa.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Correct licenses format

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml, charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml, charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml, charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml, charts/karmada/_crds/bases/work/work.karmada.io_works.yaml, operator/config/crds/operator.karmada.io_karmadas.yaml, operator/pkg/apis/operator/v1alpha1/type.go, pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go, pkg/apis/policy/v1alpha1/propagation_types.go, pkg/apis/work/v1alpha1/work_types.go, pkg/apis/work/v1alpha2/binding_types.go
/kind cleanup
This PR unfies the colunm names and add missing age colunmn.
Follow up of https://github.com/karmada-io/karmada/pull/5077#discussion_r1663427424.
Fixes #
Here is the test against PropagationPolicy
```
[rainbowmango]# kubectl get propagationpolicies.policy.karmada.io 
NAME                CONFLICT-RESOLUTION   PRIORITY   AGE
nginx-propagation   Abort                 0          12s
```
```release-note
NONE
```
=> Unify column names and add missing age column

charts/karmada-operator/templates/karmada-operator-deployment.yaml, charts/karmada/templates/karmada-descheduler.yaml, charts/karmada/templates/karmada-scheduler-estimator.yaml, charts/karmada/templates/karmada-webhook.yaml
/kind cleanup
part of https://github.com/karmada-io/karmada/issues/5166
```release-note
NONE
```
=> Expose metrics port for helm installation

cmd/karmada-search/app/karmada-search.go, cmd/karmada-search/app/options/options.go, cmd/karmada-search/app/options/validation.go
/kind cleanup
Similar to #5184, we need to do the same thing in the `karmada-search` component.
Fixes #
```release-note
NONE
```
=> replace RecommendedOptions with needed subset options in karmada-search component

docs/CHANGELOG/CHANGELOG-1.10.md, docs/CHANGELOG/CHANGELOG-1.8.md, docs/CHANGELOG/CHANGELOG-1.9.md
/kind cleanup
Add release notes of v1.8.6, v1.9.5, v1.10.3
Fixes #
```release-note
```
=> Add release notes of v1.8.6, v1.9.5, v1.10.3

test/e2e/karmadactl_test.go
In this commit, we add tests for the `karmadactl token` command. These include creating, deleting, listing, and validating bootstrap tokens. We test scenarios such as successful token creation and deletion, error handling for invalid flag, and ensuring the correct format for tokens. The utility functions `extractTokenIDAndSecret` and `validateTokenFormat` are used to validate token format and extract token components.
Part of #4544
```release-note
NONE
```
=> test/e2e/karmadactl_test.go: test token command

pkg/controllers/multiclusterservice/endpointslice_collect_controller.go, pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go, pkg/controllers/multiclusterservice/mcs_controller.go, pkg/util/constants.go
/kind cleanup
Make cleanup with multiclusterservice controllers.
Fixes #
```release-note
NONE
```
=> make cleanup with multiclusterservice controllers

pkg/karmadactl/cmdinit/cert/cert_test.go
[issue:5171](https://github.com/karmada-io/karmada/issues/5171)
Fixes # [issue:5171](https://github.com/karmada-io/karmada/issues/5171)
```release-note
```
=> improve karmadactl unit test: check the cert file exist 

pkg/detector/detector.go
/kind cleanup
Through reviewing the e2e logs, it was found that when deleting `pp/cpp`, there is a chance that cleaning up the labels/annotations of the resource template might fail. To address this, we can add retries to the function `CleanupResourceTemplateMarks` and reduce the scope and impact of these retries.
Fixes #
```release-note
```
=> optimization: add retry when clean up mark from resourcetemplate failed

test/e2e/failover_test.go, test/e2e/framework/cluster.go, test/e2e/suite_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Fix incorrect error code judgment in e2e tests

pkg/scheduler/framework/runtime/framework.go
/kind cleanup
Update pluginToClusterScores length from filterPlugins length to scorePlugins length.
Fixes #
```release-note
NONE
```
=> [Cleanup] update pluginToClusterScores length from filterPlugins length to scorePlugins length

pkg/controllers/cluster/cluster_controller.go
/kind cleanup
refactors existing functions and methods in cluster_controller to utilize a unified context.Context instance
Fixes #
```release-note
NONE
```
=> optimize: used a unified context in cluster_controller reconcile

test/e2e/karmadactl_test.go
In this commit, we add e2e tests for the `karmadactl taint` command to ensure it handles various scenarios correctly. The tests include:
- Applying taints with different effects (NoSchedule, NoExecute) to a cluster.
- Reapplying taints without the `--overwrite` flag to ensure an error is returned.
- Overwriting existing taints using the `--overwrite` flag.
- Removing taints from a cluster.
- Running the taint command in `--dry-run` mode to ensure no actual changes are made.
- Verifying that taints were not applied during `--dry-run` mode.
- Ensuring the command returns an error for an invalid flag.
- Ensuring the command returns an error when attempting to taint a non-existent cluster.
Part …
=> test/e2e/karmadactl_test.go: test taint command

pkg/controllers/applicationfailover/crb_application_failover_controller.go, pkg/controllers/applicationfailover/rb_application_failover_controller.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> cleanup: Print seconds to avoid unreadable minutes

charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml, charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml, charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml, pkg/apis/policy/v1alpha1/propagation_types.go
/kind bug
bug: `spec.failover.application.purgeMode` can be set to any value.
Fixes #
```release-note
NONE
```
=> add validation for failover api

pkg/scheduler/core/assignment.go
/kind cleanup
I think the length of the left slice is set wrong.
Fixes #
```release-note
NONE
```
/cc @Garrybest @RainbowMango
=> update left slice length in the resortAvailableClusters func

pkg/scheduler/core/spreadconstraint/select_groups.go
/kind design
when len(groups) < minConstraint, there is need to enter dfs, make findFeasiblePaths faster.
Fixes #
```release-note
NONE
```
=> perf:make findFeasiblePaths faster

pkg/apis/work/v1alpha1/work_types.go, pkg/controllers/execution/execution_controller.go, pkg/controllers/execution/execution_controller_test.go, pkg/util/helper/work.go, test/e2e/clusterpropagationpolicy_test.go, test/e2e/propagationpolicy_test.go
/kind feature
Fixes #5118
```release-note
`API change`: Introduced `Dispatching` condition to represent the dispatching status.
```
=> work suspension: work status conditions

pkg/registry/cluster/storage/aggregate.go, pkg/util/lifted/validatingfhpa.go, test/e2e/karmadactl_test.go, test/e2e/mcs_test.go
/king cleanup
Fixes #
```release-note
```
=> chore: remove duplicate imports

pkg/util/eventfilter/eventfilter_test.go
This PR enhances the test coverage for the pkg/util/eventfilter package, increasing its test coverage from 26.7% to 100%. 
**Changes**
Tests for TestSpecificationChanged: Added tests to verify that changes in service ports, labels, and annotations are correctly detected.
ResourceChangeByKarmada(): This function checks if a resource change is influenced by Karmada-specific labels and annotations.
Implementing this new tests increased it's test coverage from 26.7% to 100%. This can be verified in the file directory i.e. pkg/util/eventfilter using command
`go test -coverprofile=coverage.out`
/kind feature
1. Enhanced the module's capability to detect and handle …
=> Added new test cases and improved test coverage of pkg/util/eventfilter

test/e2e/resource_test.go
Cherry pick of #5141 on release-1.10.
#5141: Fix test for corev1.LoadBalancerIngress,add IP model to VIP
```release-note
```
=> Automated cherry pick of #5141: Fix test for corev1.LoadBalancerIngress,add IP model to VIP

test/e2e/resource_test.go
flake test: daemonSet status collection testing failed
Fixes #5257
```release-note
```
=> flake test: daemonSet status collection testing failed

docs/proposals/karmadactl/enhance_karmadactl_maintenance_experience.md
/kind feature
Enhance karmadactl operation and maintenance experience
Parts of #5248 
```release-note
```
=> docs: add proposal of enhancing karmadactl

.github/workflows/ci-schedule-compatibility.yaml, .github/workflows/ci-schedule.yml, .github/workflows/ci.yml, .github/workflows/cli.yaml, .github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/release.yml, .github/workflows/swr-latest-image.yml, .github/workflows/swr-released-image.yml
/kind cleanup
Bump golang version to v1.20.14
Fixes #
```release-note
Bump golang version to `v1.20.14`
```
=> Bump golang version to v1.20.14

pkg/controllers/execution/execution_controller.go, pkg/controllers/execution/execution_controller_test.go
/kind feature
Based on discussion in #5354 
Fixes #
```release-note
```
=> fix: allow suspended work to get deleted

docs/CHANGELOG/CHANGELOG-1.10.md, docs/CHANGELOG/CHANGELOG-1.8.md, docs/CHANGELOG/CHANGELOG-1.9.md
Add release notes of v1.8.7, v1.9.6, v1.10.4
Fixes #
```release-note
```
=> Add release notes of v1.8.7, v1.9.6, v1.10.4

hack/README.md
Follow #2961
```release-note
NONE
```
=> Add note about local-down-karmada.sh script to hack README

docs/proposals/dispatch-suspension/README.md
/kind design
Add the description of the resource deletion event.
Fixes #
```release-note
NONE
```
=> add some corner case description for dispath suspension proposal

charts/karmada/templates/karmada-apiserver.yaml, charts/karmada/templates/kube-controller-manager.yaml, charts/karmada/values.yaml
/kind feature
In some scenarios, we need this customization.
Fixes #
```release-note
Support custom cluster service CIDR in the helm chart.
```
/assign @chaosi-zju
=> charts/karmada: support custom cluster service CIDR

charts/karmada/templates/karmada-descheduler.yaml, charts/karmada/templates/karmada-scheduler-estimator.yaml, charts/karmada/templates/karmada-scheduler.yaml
/kind bug
a quick fix of ca.crt not found in helm installation
detail refer to https://github.com/karmada-io/karmada/issues/5322#issuecomment-2285745220
long term resolution tracked by #5363
Fixes #5322
```release-note
```
=> a quick fix of ca.crt not found in helm installation

pkg/dependenciesdistributor/dependencies_distributor_test.go
/kind feature
The test case coverage for pkg/dependenciesdistributor/dependencies_distributor.go has been improved.
Fixes #
To verify the changes in the pkg/dependenciesdistributor/ directory run the following commands:
```
```
```release-note
NONE
```
=> Improved test coverage for dependencies_distributor in pkg/dependenciesdistributor

pkg/karmadactl/create/create.go, pkg/karmadactl/karmadactl.go, vendor/k8s.io/kubectl/pkg/cmd/create/create.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_clusterrole.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_clusterrolebinding.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_configmap.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_cronjob.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_deployment.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_ingress.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_job.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_namespace.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_pdb.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_priorityclass.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_quota.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_role.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_rolebinding.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_secret.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_secret_docker.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_secret_tls.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_service.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_serviceaccount.go, vendor/k8s.io/kubectl/pkg/cmd/create/create_token.go, vendor/k8s.io/kubectl/pkg/generate/generate.go, vendor/k8s.io/kubectl/pkg/util/hash/hash.go, vendor/modules.txt
/kind feature
add new command karmadactl create
```bash
$ karmadactl create ns test
namespace/test created
$ karmadactl get ns
NAME                 CLUSTER   STATUS   AGE     ADOPTION
... ...
test                 Karmada   Active   4s      N/A
$ karmadactl create -f sample-pod.yaml 
pod/nginx created
$ karmadactl get pods 
NAME    CLUSTER   READY   STATUS    RESTARTS   AGE
nginx   Karmada   0/1     Running   0          4s
```
Parts of #5249
```release-note
`karmadactl`: add new command `create` to create a resource from a file or from stdin in Karmada control plane.
```
=> add new command karmadactl create

pkg/karmadactl/attach/attach.go, pkg/karmadactl/karmadactl.go, vendor/k8s.io/kubectl/pkg/cmd/attach/attach.go, vendor/modules.txt
/kind feature
add new command karmadactl attach
Parts of #5249
```release-note
```
=> add new command karmadactl attach

pkg/detector/preemption_test.go
/kind feature
The test case coverage for pkg/detector/preemption.go has been improved.
Fixes #
To verify the changes in the pkg/detector/ directory run the following commands:
```
```
```release-note
NONE
```
=> Improved test coverage for preemption in pkg/detector

pkg/karmadactl/delete/delete.go, pkg/karmadactl/karmadactl.go
/kind feature
add new  command delete
Parts of  #5249
```release-note
`karmadactl`: add a new command `karmadactl delete` to delete resources
```
=> add new command delete

pkg/karmadactl/edit/edit.go, pkg/karmadactl/karmadactl.go, vendor/k8s.io/kubectl/pkg/cmd/edit/edit.go, vendor/modules.txt
/kind feature
add new command edit
Parts of #5249
```release-note
`karmadactl`: add new command `karmadactl edit` to edit a resource on the server
```
=> add new command edit

pkg/descheduler/descheduler.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> skip descheduling ResourceBinding which is being deleted

pkg/karmadactl/annotate/annotate.go, pkg/karmadactl/karmadactl.go, vendor/k8s.io/kubectl/pkg/cmd/annotate/annotate.go, vendor/modules.txt
/kind feature
add new command annotate
Parts of  #5249
```release-note
`karmadactl`: add new command `annotate` to update the annotations on a resource
```
=> add new command annotate

docs/CHANGELOG/CHANGELOG-1.11.md
add new release note for v1.11
Parts of  #5466
```release-note
```
=> add new release note for v1.11

pkg/registry/cluster/storage/aggregate.go
Fixes #5327 
```release-note
NONE
```
=> fix: aggregate apiserver http method to get

.github/dependabot.yml
/kind cleanup
Stop updating base images for release that is out of maintenance and add new releases.
Fixes #
```release-note
NONE
```
=> Stop updating images for release-1.8 and adding release-1.11

test/e2e/clusterpropagationpolicy_test.go, test/e2e/propagationpolicy_test.go
Recently, there have been many e2e failures related to suspension, like this: https://github.com/karmada-io/karmada/actions/runs/10791713495/job/29930012414
It is found that the logic of creating and modifying PP/CPP is too close to each other, which may cause the suspension effect to not be synchronized to the RB/CRB object.
Therefore, I added logic to wait for resources to be distributed to member clusters to avoid them being too close together.
In addition, some adjustments have been made to the E2E structure.
Fixes #
/cc @a7i @chaosi-zju @RainbowMango 
```release-note
NONE
```
=> Fix occasional suspension case failed

pkg/resourceinterpreter/OWNERS
/kind cleanup
I haven't participated in code reviews for this module in a long time, and I don't have much bandwidth to contribute at this point. Additionally, the module now has enough reviewers/approvers, so I think it's time to move on.
Fixes #
```release-note
none
```
=> Remove me from resourceinterpreter OWNERS

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/work/work.karmada.io_works.yaml, pkg/apis/work/v1alpha1/work_types.go, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
This PR corrects [comments of SuspendDispatching in Work API](https://github.com/karmada-io/karmada/blob/4f7dc2c4090aef96956bfcad7fa4aca5fd7c14c9/pkg/apis/work/v1alpha1/work_types.go#L61-L65).
Fixes #
```release-note
NONE
```
=> Correct SuspendDispatching comments and add notes.

pkg/scheduler/event_handler_test.go
This PR enhances the unit tests for the event handling mechanisms in the scheduler package. The improvements aim to increase code reliability, maintainability, and test coverage for the event handlers in the scheduler.
**Additions:**
1. pkg/scheduler/event_handler_test.go
1. pkg/scheduler/event_handler.go : 26.53% to 58.50%
/kind feature
```release-note
NONE
```
=> Added tests for pkg/scheduler/event_handler.go

operator/pkg/util/endpoint_test.go
In this commit, we unit test endpoint on getting control plane endpoint and API Service IP.
Part of #5491.
```release-note
NONE
```
=> operator/pkg/util: unit test endpoint

operator/pkg/karmadaresource/apiservice/apiservice_test.go
In this commit, we unit test the api service in the karmada resource operator pkg.
Part of #5491.
**Dependency**
This PR depends on #5602.
```release-note
NONE
```
=> operator/pkg/karmadaresource/apiservice: unit test apiservice

operator/pkg/controller/karmada/planner_test.go
In this commit, we introduce unit tests for operator `controller/karmada` package.
Part of #5491
```release-note
NONE
```
=> operator/pkg/controller/karmada: unit test Karmada controller

docs/CHANGELOG/CHANGELOG-1.12.md
publish release note for v1.12.0-alpha.1
Fixes #
```release-note
```
=> publish release note for v1.12.0-alpha.1

pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
/kind cleanup
This PR fixed a typo in the description of `InterpreterOperationAll`.
Fixes #
```release-note
NONE
```
=> Fix InterpreterOperationAll description typo

pkg/util/lifted/corev1printers_test.go
**Description:** 
This PR introduces comprehensive unit tests for pod-related functions in pkg/util/lifted/corev1printers.go. These additions significantly improve the test coverage and ensure the reliability of pod handling and printing logic in the Karmada project.
**Improvements:**
1. pkg/util/lifted/corev1printers_test.go
1. pkg/util/lifted/corev1printers.go: 53.90% to 95.30%
/kind feature
```release-note
NONE
```
=> Added second part of unit tests for pkg/util/lifted/corev1printers.go

docs/CHANGELOG/CHANGELOG-1.10.md, docs/CHANGELOG/CHANGELOG-1.11.md, docs/CHANGELOG/CHANGELOG-1.12.md, docs/CHANGELOG/CHANGELOG-1.9.md
According to the release roadmap, Karmada is about to release v1.12.0-beta.0. This PR is for releasing its release notes.
Fixes #
```release-note
NONE
```
=> publish release notes for v1.12.0-beta.0

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml, charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml, charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml, charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml, charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml, charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml, charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml, charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml, charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml, charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml, charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml, charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml, charts/karmada/_crds/bases/work/work.karmada.io_works.yaml, examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml, hack/update-crdgen.sh, operator/config/crds/operator.karmada.io_karmadas.yaml
/kind cleanup
This PR is split from #5807 which is huge and hard to review.
Fixes #
```release-note
NONE
```
=> Bump controller-gen to v0.16.5

operator/pkg/controller/karmada/controller.go, operator/pkg/controller/karmada/validating.go, operator/pkg/controller/karmada/validating_test.go, operator/pkg/init.go, operator/pkg/tasks/init/etcd.go
/kind cleanup
refactor operator module validation logic for Karmada objects
Fixes #
```release-note
```
=> refactor operator module validation logic for Karmada objects

pkg/apis/policy/v1alpha1/propagation_types.go
/kind cleanup
Update PurgeMode comments to address real-world use cases, based on the discussion on https://github.com/karmada-io/karmada/pull/5251#issuecomment-2418074371.
Part of https://github.com/karmada-io/karmada/issues/5788
```release-note
NONE
```
=> Update application failover purge mode comments

pkg/metricsadapter/controller.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go, pkg/search/controller.go, pkg/servicenameresolutiondetector/coredns/detector.go, pkg/sharedcli/ratelimiterflag/ratelimiterflag.go, pkg/util/worker.go
/kind cleanup
This PR adopts the generic rate limiter queue and removes the deprecated references.
Part of #5796
```release-note
NONE
```
=> Adopt generic ratelimter queue

docs/CHANGELOG/CHANGELOG-1.10.md, docs/CHANGELOG/CHANGELOG-1.11.md, docs/CHANGELOG/CHANGELOG-1.9.md
publish releasenote for release v1.9.9, v1.10.7, v1.11.3
Fixes #
NONE
```release-note
NONE
```
=> publish releasenote for release v1.9.9, v1.10.7, v1.11.3

charts/karmada-operator/README.md
This PR enhances the Karmada operator docs with instructions for creating and inspecting Karmada instances.
Fixes part of #5767
```release-note
NONE
```
=> Add Docs for Creating and Inspecting Karmada Instance by Operator

pkg/controllers/applicationfailover/common_test.go
/kind cleanup
Add ut for parseJSONValue function to cover the JSONPath main parse ability.
Fixes #
```release-note
NONE
```
=> Add ut for parseJSONValue function to cover the JSONPath main parse ability

docs/CHANGELOG/CHANGELOG-1.12.md
=> publish release note for v1.12.0

.github/dependabot.yml, .github/workflows/ci-image-scanning-on-schedule.yml, .github/workflows/ci-schedule-compatibility.yaml
/kind cleanup
Stop maintaining version 1.9 and maintain version 1.12
Fixes #
```release-note
NONE.
```
=> Stop maintaining version 1.9 and maintain version 1.12

.github/workflows/dockerhub-released-chart.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/release.yml
/kind feature
prevent some jobs running from forked repository. 
https://github.com/kubernetes-sigs/krew-index/pull/4265
https://github.com/kubernetes-sigs/krew-index/pull/4262
https://github.com/zhzhuang-zju/karmada/actions/runs/12228433540
https://github.com/zhzhuang-zju/karmada/actions/runs/12228433542
Fixes #
```release-note
```
=> prevent some jobs running from forked repository

hack/local-up-karmada.sh
/kind cleanup
simplify local-up-karmada.sh based on setup-dev-base.sh
Fixes #
```release-note
```
=> simplify local-up-karmada.sh based on setup-dev-base.sh

hack/deploy-karmada-by-operator.sh, hack/local-up-karmada-by-operator.sh
/kind cleanup
simplify local-up-karmada-by-operator.sh based on setup-dev-base.sh
Fixes #
```release-note
```
=> simplify local-up-karmada-by-operator.sh based on setup-dev-base.sh

docs/CHANGELOG/CHANGELOG-1.10.md, docs/CHANGELOG/CHANGELOG-1.11.md, docs/CHANGELOG/CHANGELOG-1.12.md, docs/CHANGELOG/CHANGELOG-1.9.md
Recently karmada merged in several bug fixes, so the release team decided to advance the patch release. Note that `v1.9.10` is the last patch version of `release-1.9`!
Fixes #
```release-note
```
=> publish release note for v1.9.10, v1.10.8, v1.11.4, v1,12.1

pkg/util/helper/work_test.go
/kind flake
After merging #5742, there is a flake test in the master branch, this is because of the change of #5779, as commented in https://github.com/karmada-io/karmada/pull/5742#issuecomment-2566086990
Fixes #
```release-note
NONE
```
=> fix flake test with GetWorksByBindingID func

hack/verify-license.sh, operator/pkg/controller/karmada/validating_test.go, pkg/resourceinterpreter/customized/webhook/serviceresolvers.go, pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go, pkg/util/helper/index.go, pkg/util/helper/index_test.go
Cherry pick of #5984 on release-1.12.
#5984: fix verify license lint error
```release-note
=> Automated cherry pick of #5984: fix verify license lint error

operator/README.md
This PR adds the documentation of exposing Karmda APIServer provisioned by the `karmada-opeator`.
Part of #5767
```release-note
NONE
```
=> Add docs for exposing Karmada APIServer provisioned by operator

docs/proposals/karmada-operator/component-priority-class-name/README.md
/kind design
- Details are contained in the proposal.
Fixes #
```release-note
NONE
```
=> Proposal: Add Support for Component Priority Class Configuration in Karmada Operator

docs/CHANGELOG/CHANGELOG-1.13.md
According to the [release cycle](https://karmada.io/docs/next/releases#the-release-cycle), it's time to release version v1.13.0.-alpha.2
Fixes #
```release-note
None.
```
=> publish release v1.13.0-alpha.2

charts/karmada/templates/kube-controller-manager.yaml
/kind cleanup
Fix a typo, cc @chaosi-zju 
Fixes #
```release-note
NONE
```
=> charts: fix typo in templates/kube-controller-manager.yaml

api/openapi-spec/swagger.json, charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml, pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
This PR explains how the interpreter webhook be resolved based on the effort at #5954 .
Part of #5954
```release-note
NONE
```
=> Explain the interpreter webhook comunication channel

docs/CHANGELOG/CHANGELOG-1.13.md
According to [Karmada's release cycle](https://karmada.io/docs/next/releases#the-release-cycle), the release team is preparing to release a rc version of v1.13.0 today. This pr is used to publish its release notes.
Fixes #
```release-note
```
=> publish release v1.13.0-rc.0

docs/proposals/karmada-operator/api-server-sidecard-containers/README.md
/kind design
- Details are contained in the proposal.
Fixes #
```release-note
NONE
```
=> Proposal: Add Support for API Server Sidecar Containers in Karmada Operator

pkg/search/controllers_test.go
Cherry pick of #5936 on release-1.12.
#5936: pkg/search/controllers_test: wait for cache sync
```release-note
NONE
```
=> Automated cherry pick of #5936: pkg/search/controllers_test: wait for cache sync

test/e2e/suites/base/search_test.go, test/e2e/suites/base/suite_test.go
add e2e test for karmada-search
Fixes #6065
```release-note
```
=> add e2e test for the case fixed by #6065

artifacts/deploy/karmada-controller-manager.yaml, artifacts/deploy/karmada-scheduler.yaml, pkg/features/features.go
/kind feature
This PR introduces the feature gate as per the [proposal](https://github.com/karmada-io/karmada/tree/master/docs/proposals/scheduling/binding-priority-preemption#feature-gate).
Part of #5961
```release-note
NONE
```
=> Introduce PriorityBasedScheduling feature gate 

pkg/apis/work/v1alpha2/binding_types_helper.go, pkg/scheduler/event_handler.go, pkg/scheduler/internal/heap/heap.go, pkg/scheduler/internal/heap/heap_test.go, pkg/scheduler/internal/queue/active_queue.go, pkg/scheduler/internal/queue/active_queue_test.go, pkg/scheduler/internal/queue/scheduling_queue.go, pkg/scheduler/internal/queue/types.go, pkg/scheduler/metrics/queue/metric_test.go, pkg/scheduler/metrics/queue/metrics.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_metrics_test.go, pkg/scheduler/scheduler_test.go
/kind feature
part of https://github.com/karmada-io/karmada/issues/5961
```release-note
NONE
```
=> priority scheduling: add priority queue

pkg/detector/detector.go, pkg/util/helper/priorityclass.go, pkg/util/helper/priorityclass_test.go
/kind feature
This PR builds application priority when creating ResourceBinding as per the [proposal](https://github.com/karmada-io/karmada/tree/master/docs/proposals/scheduling/binding-priority-preemption#karmada-controller-manager).
part of https://github.com/karmada-io/karmada/issues/5961
```release-note
`karmada-controller-manager`: Populate schedule priority when building ResourceBinding.
```
=> Build application priority when creating ResourceBinding

MAINTAINERS.md
There is already a Maintainers file in the Community repo, so leaving a link in the Karmada repo is enough.
Fixes #https://github.com/karmada-io/community/issues/111
```release-note
NONE
```
=> move Maintainers to community repo

docs/proposals/karmada-operator/custom-leaf-cert-validity/README.md
/kind design
Details are include in the proposal.
Fixes #
```release-note
NONE
```
=> Proposal: Add Support to Configure Leaf Certificate Validity Period in Karmada Operator

pkg/controllers/execution/execution_controller.go, pkg/controllers/status/work_status_controller.go, pkg/metrics/resource.go, pkg/util/objectwatcher/objectwatcher.go
/kind cleanup
This PR brings more specific operation counters for create/update/delete member cluster objects.
Fixes #
```release-note
karmada-controller-manager: metric `recreate_resource_to_cluster` has been merged into `create_resource_to_cluster`.
```
=> update object watcher metrics and simplify cluster object version recording

charts/index.yaml
/kind cleanup
add helm index v1.13.0
Fixes #
```release-note
`Helm chart`: Added helm index for 1.13 release.
```
=> add helm index v1.13.0

artifacts/deploy/karmada-aggregated-apiserver.yaml
/kind cleanup
Remove the extra symbol '/' from the `karmada-aggregated-apiserver.yaml`.
Fixes #
```release-note
NONE
```
=> remove extra symbol '/' in the karmada-aggregated-apiserver.yaml

pkg/karmadactl/register/register.go
/kind cleanup
rename `kubelient` to `kubeClient` for better understanding
Fixes #
```release-note
NONE
```
=> fix: typo error in karmadactl register

pkg/controllers/cluster/taint_manager.go
/kind cleanup
Update mismatch log info in the `taint-manager.go`
Fixes #
```release-note
NONE
```
=> update mismatch log info in the taint-manager

operator/README.md
add docs for configuring API Server sidecar in karmada operator
Parts of #6138
```release-note
NONE
```
=> add docs for configuring API Server sidecar in karmada operator

pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go, pkg/controllers/gracefuleviction/evictiontask.go, pkg/controllers/gracefuleviction/evictiontask_test.go, pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
Cherry pick of #6227 on release-1.11.
#6227: to prevent the generation judgment from always being false
```release-note
`karmada-controller-manager`: Fixed the issue that the gracefulEvictionTask of ResourceBinding can not be cleared in case of schedule fails.
```
=> Automated cherry pick of #6227: to prevent the generation judgment from always being false

.github/dependabot.yml, .github/workflows/ci-image-scanning-on-schedule.yml, .github/workflows/ci-schedule-compatibility.yaml, operator/config/samples/karmada.yaml
Update Karmada CI to release-1.13 and updating the karmada imageTag to v1.13.0
Fixes #6195
NONE
=> Update Karmada CI and Documentation

charts/karmada/README.md, operator/config/samples/karmada.yaml, pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
As time goes by, the versions of some dependencies or the documentation in the repo have become outdated. This pull request aims to make a unified update for these aspects.  
Fixes #NONE
```release-note
NONE.
```
=> Update alpine version used by karmadactl init

pkg/util/cluster.go
/kind cleanup
cleanup unused err check
Fixes #NONE
```release-note
NONE
```
=> cleanup unused err check

docs/CHANGELOG/CHANGELOG-1.11.md, docs/CHANGELOG/CHANGELOG-1.12.md, docs/CHANGELOG/CHANGELOG-1.13.md, docs/CHANGELOG/CHANGELOG-1.14.md
According to [Karmada's release cycle](https://karmada.io/docs/next/releases#the-release-cycle), the release team is preparing to release v1.14.0-alpha.1 the end of the month, along with patch version for the maintenance releases. This pr is used to publish its release notes
Fixes #
```release-note
NONE
```
=> publish release notes for v1.11.8,v1.12.5,v1.13.1,v1.14.0-alpha.1

test/e2e/suites/base/karmadactl_test.go
Part of #4544 
**Context**
Dependent on #5429
```release-note
NONE
```
=> test/e2e/karmadactl_test.go: test register command

.golangci.yml, cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, operator/pkg/tasks/init/cert_test.go, pkg/controllers/unifiedauth/unified_auth_controller_test.go, pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo_test.go, pkg/scheduler/scheduler_test.go
/kind cleanup
Fix lint issue - `ST1019: package "xxx" is being imported more than once (staticcheck)`.
Part of https://github.com/karmada-io/karmada/issues/6273
```release-note
NONE
```
=> Fix lint issue ST1019

.golangci.yml, pkg/controllers/ctrlutil/work.go, pkg/controllers/federatedhpa/federatedhpa_controller.go, pkg/controllers/multiclusterservice/mcs_controller.go, pkg/detector/detector.go, pkg/estimator/server/framework/interface.go, pkg/estimator/server/framework/plugins/resourcequota/resourcequota.go, pkg/scheduler/framework/interface.go, pkg/util/helper/mcs.go
/kind cleanup
Fix lint issue - `QF1003: could use tagged switch on operationResult (staticcheck)`.
Part of #6237
```release-note
NONE
```
=> Fix lint issue QF1003

.golangci.yml, hack/tools/gencomponentdocs/gen_component_docs.go, pkg/controllers/federatedhpa/federatedhpa_controller.go
/kind cleanup
Fix lint issue - `ST1005: error strings should not be capitalized (staticcheck)`.
Part of https://github.com/karmada-io/karmada/issues/6273
```release-note
NONE
```
=> Fix lint issue ST1005

docs/CHANGELOG/CHANGELOG-1.14.md
According to [Karmada's release cycle](https://karmada.io/docs/next/releases#the-release-cycle), the release team is preparing to release v1.14.0-alpha.2. This pr is used to publish its release notes.
Fixes #
```release-note
None.
```
=> publish release note for v1.14.0-alpha.2

.github/workflows/ci-schedule-compatibility.yaml, .github/workflows/ci-schedule.yml, .github/workflows/ci.yml, .github/workflows/installation-chart.yaml, .github/workflows/installation-cli.yaml, .github/workflows/installation-operator.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
=> chore: add kubernetes 1.32.0 to ci

test/e2e/framework/priorityclass.go, test/e2e/suites/base/schedule_priority_test.go, test/helper/priorityclass.go
/kind feature
Add e2e tests for #5961. 
Part of #5961
The e2e tests mainly test if the detector correctly populates the priority value of the Binding.
```release-note
None
```
=> feat: Add SchedulePriority e2e tests

.github/workflows/installation-chart.yaml
Follow-up on https://github.com/karmada-io/karmada/pull/5638#issuecomment-2822902938.
```release-note
NONE
```
=> .github/workflows/installation-charts.yaml: update Helm and Kustomize to latest versions

pkg/search/proxy/controller.go, pkg/search/proxy/framework/interface.go, pkg/search/proxy/framework/plugins/cache/cache.go, pkg/search/proxy/framework/plugins/cluster/cluster.go, pkg/search/proxy/framework/plugins/cluster/cluster_test.go, test/e2e/suites/base/search_test.go
/kind bug
Fixes #
```release-note
```
=> fix proxy request error with pb content type

.github/workflows/lint-chart.yaml
Cherry pick of #6318 on release-1.11.
#6318: .github/workflows: update helm and kustomize env
```release-note
None
```
=> Automated cherry pick of #6318: .github/workflows: update helm and kustomize env

pkg/features/features.go
This is the subtask for #6350 - FederatedResourceQuota Enhancement. Add new feature flag that will toggle the changes of the FederatedResourceQuota enhancement.
Fixes #
```release-note
NONE
```
=> add `FederatedQuotaEnforcement` feature flag

docs/CHANGELOG/CHANGELOG-1.14.md
Fixes #
According to Karmada's release cycle, the release team is preparing to release v1.14.0-rc.0 the middle of the month. This pr is used to publish its release notes
```release-note
None,
```
=> publish release note for v1.14.0-rc.0

operator/pkg/controller/karmada/validating.go
/kind feature
Follow up of #6348
1. This field is applicable only when ServiceType is set to LoadBalancer. 
2. The value must be a label-style identifier
```release-note
NONE
```
=> feat(controller.karmada): validateKarmadaAPIServer  validate lbClass

pkg/controllers/taint/clustertaintpolicy_controller.go
/kind feature
This pr does three things:
1. To ensure idempotency, sort the ClusterTaintPolicies by creation time.
2. Even if the Cluster object is in the process of being deleted, users may still need to add taints to the cluster,
3. Add ClusterTaintPolicy PredicatedFn.
Fixes #
```release-note
NONE
```
=> Sort policies in cluster-taint-policy-controller to ensure idempotency

docs/CHANGELOG/CHANGELOG-1.13.md, docs/CHANGELOG/CHANGELOG-1.14.md
According to Karmada's release cycle, the release team is preparing to release v1.14.0 the end of the month, along with patch version for the maintenance releases. This pr is used to publish its release notes
Fixes #
```release-note
```
=> publish release v1.14.0&v1.13.3

charts/karmada/templates/pre-install-job.yaml, charts/karmada/values.yaml
Fixes # https://github.com/karmada-io/karmada/issues/6436
```release-note
`Chart`: Introduced parameter `certs.auto.rootCAExpiryDays` for root ca certification expiry customization. 
```
=> feat: make expiry configurable for root ca cert

charts/index.yaml
/kind cleanup
Add helm index v1.14
Parts of #6451 
1. download the karmada-chart-v1.14.0.tgz to dir charts/karmada/
```bash
curl -L -o charts/karmada/karmada-chart-v1.14.0.tgz  https://github.com/karmada-io/karmada/releases/download/v1.14.0/karmada-chart-v1.14.0.tgz
```
2. run `helm repo index charts/karmada --url https://github.com/karmada-io/karmada/releases/download/v1.14.0 --merge charts/index.yaml`
3. run `mv charts/karmada/index.yaml charts/index.yaml`
4. Remove the generated code block under `entries.common` field
```release-note
```
=> add helm index v1.14

pkg/controllers/cluster/cluster_controller.go, pkg/controllers/cluster/taint_manager.go
Fixes #
Partof https://github.com/karmada-io/karmada/issues/6230
```release-note
NONE
```
=> JSON logging for cluster controllers

pkg/controllers/execution/execution_controller.go
structured  logging support. More details are highlighted in 
https://github.com/karmada-io/karmada/pull/6440 and 
https://github.com/karmada-io/karmada/issues/6230 
Fixes #
```
NONE
```
=> continue using klog with structured logging

.github/workflows/ci-image-scanning-on-schedule.yml, .github/workflows/ci-image-scanning.yaml, .github/workflows/release.yml
/kind cleanup
update trivy version
Parts of #6521
```release-note
```
=> [release-1.14] update trivy version

.github/workflows/ci-image-scanning-on-schedule.yml, .github/workflows/ci-image-scanning.yaml, .github/workflows/release.yml
/kind cleanup
update trivy version
Parts of #6521
```release-note
```
=> [release-1.13] update trivy version

docs/CHANGELOG/CHANGELOG-1.15.md
According to Karmada's release cycle, the release team is preparing to release v1.15.0-alpha.2 the middle of the month. This pr is used to publish its release notes
Fixes #
```release-note
```
=> publish release v1.15.0-alpha.2

pkg/controllers/federatedhpa/federatedhpa_controller.go, pkg/controllers/federatedhpa/metrics/client.go
This is part of https://github.com/karmada-io/karmada/issues/6230
Does this PR introduce a user-facing change?
Nope
=> Add Structured Logging for Federated HPA controller

pkg/controllers/status/rb_status_controller.go
Part of https://github.com/karmada-io/karmada/issues/6230
```release-note
None
```
=> JSON logging for RB Status Controller

pkg/controllers/mcs/service_export_controller.go
Cherry pick of #6434 on release-1.12.
#6434: wait for EndpointSlice informer synced when report
```release-note
`karmada-controller-manager`: Fixed the issue that EndpointSlice are deleted unexpectedly due to the EndpointSlice informer cache not being synced
```
=> Automated cherry pick of #6434: wait for EndpointSlice informer synced when report

pkg/controllers/status/work_status_controller.go
/kind cleanup
JSON logging support. More details are highlighted in #6230 
Logging Keys for Users to use in Log Alarms:
* `work`
* `namespace`
* `cluster`
* `kind`
* `key`
* `object`
* `reason`
* `reference`
This is part of #6230 
Does this PR introduce a user-facing change?
* Log messages will be different with structured keys.
* Some messages had their English reworded to match my American English expectations
Part of #6230 
I am unable to trigger all of these log messages so would appreciate a critical eye to ensure I interpreted the key correctly.
**Does this PR …
=> Work status controller structured logging

pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go, pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler.go, pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
/kind cleanup
**What this PR does / why we need it**: Better Log Ingestion, Efficient Querying, etc.
**Which issue(s) this PR fixes**: 
Partof #6230  
**Does this PR introduce a user-facing change?**: No
```release-note
```
=> structured logging for cronfederatedhpa controllers

pkg/webhook/resourcebinding/validating.go, pkg/webhook/resourcebinding/validating_test.go
/kind cleanup
This PR restructures the validating webhook for ResourceBinding to enhance its architecture and extensibility.
Fixes #
```release-note
NONE
```
=> Optimize the ResourceBinding validation webhook for better extensibility

pkg/karmadactl/interpret/interpret.go
File name should be `customization.yml` in one of the `karmadactl interpret` commands.
```release-note
NONE.
```
=> update -f flag description for karmadactl interpret

pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
/kind cleanup
Introduce a new Interpreter operation `InterpretComponent`. see https://github.com/karmada-io/karmada/pull/6665#discussion_r2287093245 for background.
Part of #6641
This is a follow up of #6659
```release-note
NONE
```
=> Introduce new interpreter operation InterpretComponent

pkg/detector/detector.go
/kind feature
This PR introduces the functionality to resolve resource components by leveraging the `GetComponents` interpreter hook when creating ResourceBinding and ClusterResourceBinding.
If the feature gate `MultiplePodTemplatesScheduling` is enabled and `GetComponents` is implemented, the controller will use `GetComponents` to obtain per-component replica and resource requirements, and will not call `GetReplicas`.
If the feature gate `MultiplePodTemplatesScheduling` is enabled and `GetComponents` is **not** implemented, the controller will fall back to `GetReplicas` for backward compatibility.
Part of #6641 …
=> Resolve binding components using GetComponents interpreter hook

pkg/util/validation/validation.go, pkg/util/validation/validation_test.go
/kind cleanup
policyv1alpha1.StatePreservation.Rules[*].AliasLabelName is the name that will be used as a label key when the preserved data is passed to the new cluster, so it needs to meet the requirements of the label key; otherwise, it will fail during injection, leading to internal processing errors. Therefore, we need to validate it.
Part of #6593
```release-note
NONE
```
=> add validation for policyv1alpha1.StatePreservation.Rules[*].AliasLabelName

pkg/webhook/interpreter/http.go, pkg/webhook/interpreter/http_test.go
Cherry pick of #6603 on release-1.14.
#6603: Fix the issue of infinite loop caused by connection failure
```release-note
`karmada-interpreter-webhook-example`: Fixed write response error for broken HTTP connection issue.
```
=> Automated cherry pick of #6603: Fix the issue of infinite loop caused by connection failure

pkg/resourceinterpreter/customized/declarative/configmanager/accessor.go, pkg/resourceinterpreter/customized/declarative/configmanager/accessor_test.go, pkg/resourceinterpreter/customized/declarative/configurable.go, pkg/resourceinterpreter/customized/declarative/luavm/lua.go, pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go, pkg/resourceinterpreter/interpreter.go
/kind feature
Implement `GetComponents` for `ConfigurableInterpreter`.
Part of #6641 
```release-note
NONE
```
=> Implement `GetComponents` for `ConfigurableInterpreter`

pkg/resourceinterpreter/default/thirdparty/thirdparty.go, pkg/resourceinterpreter/interpreter.go
/kind feature
Implement `GetComponents` for `ThirdpartyInterpreter`.
Part of #6641 
```release-note
NONE
```
=> Implement `GetComponents` for `thirdpartyInterpreter`

operator/config/samples/karmada.yaml
Update sample file of Karmada operator.
Part of #6724
```release-note
NONE
```
=> Update sample file of Karmada operator

charts/karmada-operator/values.yaml, hack/package-helm-chart.sh
/kind cleanup
automatic modify image version in helm operator chart when releasing.
ref to https://github.com/karmada-io/karmada/pull/6731#discussion_r2321869366
Fixes #
```bash
$ VERSION="v1.16.0" make package-chart
$ tar -zxvf karmada-operator-chart-v1.16.0.tgz -C operator
$ cat operator/karmada-operator/values.yaml 
karmadaOperatorImageVersion: &karmadaOperatorImageVersion v1.16.0
```
```release-note
```
=> automatic modify image version in helm operator chart when releasing

charts/index.yaml, hack/package-helm-chart.sh
/kind cleanup
ref to https://github.com/karmada-io/karmada/pull/6727#discussion_r2320668398
Fixes #
```bash
(base) ➜  karmada git:(appVersion) ✗ helm search repo my-karmada -l
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                      
my-karmada/karmada              v1.15.0         v1.15.0         A Helm chart for karmada         
my-karmada/karmada              v1.14.0         v1.14.0         A Helm chart for karmada         
my-karmada/karmada              v1.13.0         v1.13.0         A Helm chart for karmada         
my-karmada/karmada              v1.12.0         v1.12.0         A Helm chart for karmada …
```
=> revise charts appVersion

pkg/webhook/resourcebinding/validating.go, pkg/webhook/resourcebinding/validating_test.go
/kind bug
https://github.com/karmada-io/karmada/blob/eeff07ce6b3915010adb974a8af2e0831562e718/pkg/webhook/resourcebinding/validating.go#L378-L387
The field `ReplicaRequirements` is a pointer, and directly accessing `ReplicaRequirements.ResourceRequest` without checking for nil may cause a panic.
```bash
{"ts":1757920180065.1472,"caller":"runtime/runtime.go:142","msg":"Observed a panic","panic":"runtime error: invalid memory address or nil pointer dereference","panicGoValue":"\"invalid memory address or nil pointer dereference\"","stacktrace":"goroutine 18644 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x246c230, 0xc000550000}, {0x1db40a0, 0x35d2190})\n\t/root/home/gopath/pkg/mod/k8s.io/apimachinery@v0.33.2/ …
```
=> fix nil pointer dereference error
