karmada-io/karmada

README.md
Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
Fixes #
```release-note
```
=> add badges for project

.github/workflows/ci.yml, hack/run-e2e.sh
Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
Fixes #
```release-note
```
=> change ci workflow, use ubuntu-latest

ADOPTERS.md
Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind deprecation
> /kind design
> /kind failing-test
> /kind feature
> /kind flake
Fixes #
```release-note
```
=> add founding members to adopters.md

README.md
Signed-off-by: Leo Fang <leofang94@gmail.com>
> /kind bug
Fix typo in README
Fixes #291 
No
```release-note
NONE
```
=> Fix typo "karmadda" in README

.github/PULL_REQUEST_TEMPLATE.md
/kind bug
modify the pr template: comment out the kind examples
Fixes #
```release-note
```
=> modify the pr template: comment out the kind examples

pkg/karmadactl/join.go, pkg/karmadactl/unjoin.go
/kind cleanup
remove unecessary `todo` flag
Fixes #
```release-note
```
=> remove unecessary todo flag

README.md
Added community meeting and contact.
Fixes #
=> Add community meeting and contact

pkg/util/detector/detector.go
/kind feature
When multiple PropagationPolicy/ClusterPropagationPolicy match resource, the first PropagationPolicy/ClusterPropagationPolicy is matched alphabetically.
Fixes #
```release-note
NONE
```
=> match the first PropagationPolicy/ClusterPropagationPolicy in alphabetical order

pkg/karmadactl/join.go, pkg/util/membercluster_client.go
/kind feature
support to manage cluster by proxy
Fixes #257 
"NONE"
```release-note
```
=> support to manage cluster by proxy 

artifacts/deploy/policy.karmada.io_clusteroverridepolicies.yaml, artifacts/deploy/policy.karmada.io_overridepolicies.yaml, pkg/apis/policy/v1alpha1/override_types.go, pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go, pkg/util/overridemanager/overridemanager.go
/kind cleanup
Added more clear comments for the `Override` Policies.
Fixes #
Refer to https://github.com/karmada-io/karmada/pull/316#issuecomment-839418742.
=> Added more clear description for override API

hack/tools/tools.go
/kind cleanup
This PR fixes the import order to keep it consistent with rest of the code.
Fixes #308
```release-note
NONE
```
=> Fix import order

CONTRIBUTING.md, README.md
Signed-off-by: Long Dai <long0dai@foxmail.com>
Clean up whitenoise.
Fixes #
```release-note
```
=> docs: clean up whitenoise

.gitignore
<!--
Add one of the following kinds:
/kind feature
Add gitignore for vscode.
Fixes #
NONE
```release-note
```
=> Add gitignore for vscode

cmd/agent/app/options/options.go, pkg/controllers/cluster/cluster_controller.go, pkg/util/objectwatcher/objectwatcher.go, test/e2e/namespace_test.go
/kind cleanup
delete some blank lines in import, and fix duplicate import package problems
Fixes #
```release-note
```
=> fix blank lines of import packages and repeated import problems

pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
Signed-off-by: futuretea <1913508671@qq.com>
Fixes #338
```release-note
```
=> Fix panic when no clusters specified

cmd/controller-manager/app/controllermanager.go, cmd/controller-manager/app/options/options.go
/kind cleanup
Fixes #
add enalbe-leader-election flag
```release-note
```
=> Add enable-leader-election flag

pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
/kind bug
Fixes #338
The Score plugin also has bugs, the pull request will fix them all.
```release-note
```
=> scheduler: fix bug of plugin invalid memory address

.golangci.yml, pkg/karmadactl/join.go, pkg/util/detector/detector.go, pkg/util/helper/binding.go
/kind optimization
add golanci linter: whitespace
Fixes #
```release-note
```
=> add linters: whitespace and fix linter errors

artifacts/example/binding.yaml
/kind cleanup
Fixes #
```release-note
```
=> Fix api version

cmd/controller-manager/app/options/options.go
Signed-off-by: Kevin Wang <kevinwzf0126@gmail.com>
clean up lint failure after https://github.com/karmada-io/karmada/pull/336
Fixes #
```release-note
```
=> fix lint failure in controller-manager options.go

README.md
Signed-off-by: futuretea <1913508671@qq.com>
If the user is using a non-root user, they need modify the commands  in quick start manual.
Use `$HOME` instead of `/root` to be  more universal.
Fixes #
```release-note
NONE
```
=> Adjust non-root user in quick start

pkg/karmadactl/join.go
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/349
```release-note
```
=> Remove cluster namespace

Makefile, hack/docker.sh
Signed-off-by: Long Dai <long0dai@foxmail.com>
Fixes #
```release-note
```
=> ci: optimize image build

.github/workflows/ci.yml
Signed-off-by: Long Dai <long0dai@foxmail.com>
Golangci-lint Github Action' s log is not easy to read and we need to maintain two places for its version, so directly use script here.
Fixes #
```release-note
```
=> ci: use verify-staticcheck.sh instead

cmd/controller-manager/app/controllermanager.go
/kind cleanup
cleanup code
Fixes #
```release-note
```
=> makes error check consistent

Makefile
/kind cleanup
delete judgingwhether .go files exist or not
Fixes #
```release-note
```
=> remove Makefile SOURCES variable

artifacts/example/propagation_fieldsselector.yaml, pkg/util/constants.go, pkg/util/helper/policy.go, pkg/util/selector.go, pkg/util/validation/validation.go, pkg/webhook/clusterpropagationpolicy/validating.go, pkg/webhook/propagationpolicy/validating.go, test/e2e/fieldselector_test.go, test/helper/propagationpolicy.go
/kind feature
support schedule based on cluster provider/region/zone
Fixes #
"NONE"
=> support schedule based on cluster provider/region/zone

README.md
/kind optimization
prerequisites add go link to enable jumping to the official golang website
Fixes #
```release-note
```
=> README add go link

artifacts/deploy/policy.karmada.io_clusteroverridepolicies.yaml, artifacts/deploy/policy.karmada.io_overridepolicies.yaml, pkg/apis/policy/v1alpha1/override_types.go, pkg/util/constants.go, pkg/util/detector/detector.go, pkg/util/helper/binding.go, pkg/util/imageparser/parser.go, pkg/util/objectwatcher/retain.go, pkg/util/overridemanager/imageoverride.go, pkg/util/overridemanager/imageoverride_test.go, pkg/util/overridemanager/overridemanager.go
/kind feature
ImageOverrider  implementation
Fixes https://github.com/karmada-io/karmada/issues/313
```release-note
```
=> ImageOverrider Implementation

pkg/util/detector/detector.go, pkg/util/helper/binding.go
/kind bug
Refer to https://github.com/karmada-io/karmada/pull/374#issuecomment-849398018
=> Cleanup resource bindings when cluster propagation policy has been removed

artifacts/deploy/policy.karmada.io_clusteroverridepolicies.yaml, artifacts/deploy/policy.karmada.io_clusterpropagationpolicies.yaml, artifacts/deploy/policy.karmada.io_overridepolicies.yaml, artifacts/deploy/policy.karmada.io_propagationpolicies.yaml, artifacts/deploy/policy.karmada.io_replicaschedulingpolicies.yaml, artifacts/deploy/work.karmada.io_clusterresourcebindings.yaml, artifacts/deploy/work.karmada.io_resourcebindings.yaml, pkg/apis/policy/v1alpha1/override_types.go, pkg/apis/policy/v1alpha1/propagation_types.go, pkg/apis/policy/v1alpha1/replicascheduling_types.go, pkg/apis/work/v1alpha1/binding_types.go
/kind cleanup 
Fixes https://github.com/karmada-io/karmada/issues/348
```release-note
```
=> Add kubebuilder shortName tag

hack/local-up-karmada.sh
/kind bug
fix bug when startups `local-up-karmada.sh` in the path `karmada/hack/`
Fixes #394
NONE
=> bug fix wrong folder kickstart

hack/karmada-bootstrap.sh, hack/util.sh
/kind cleanup
we can get GOPATH by `go env GOPATH`, and just only once
Fixes #
```release-note
```
=> modify the way of getting GOPATH variable

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/controllers/status/cluster_status_controller.go
Signed-off-by: Garrybest garrybest@foxmail.com
/kind feature
According to #364
Fix #364
```release-note
```
=> using cached lister to get node summary

.github/ISSUE_TEMPLATE/good-first.md
/kind cleanup
Added an issue template for members to publish a good first issue.
Fixes #
```release-note
NONE
```
=> Add good first issue template

pkg/util/selector.go
/kind bug
Fixes #402 
```release-note
```
=> fix #402 replicaschedulingpolicy does not take effect

pkg/controllers/status/cluster_status_controller.go
/kind cleanup
Modify hard code in cluster_status_controller.
Fixes #
```release-note
```
=> modify hard code in cluster_status_controller

artifacts/agent/karmada-agent.yaml, cmd/agent/app/agent.go, cmd/agent/app/options/options.go, hack/deploy-karmada-agent.sh, pkg/karmadactl/options/global.go
=> Introduce --karmada-context flag to karmada-agent to select context in kubeconfig file

pkg/util/detector/detector.go
/kind cleanup
cleanup some clusterresourcebinding code
Fixes #
```release-note
```
=> Remove dead code

hack/OWNERS
/kind cleanup
Put @lfbear and @mrlihanbo on the owner list.
@lfbear and @mrlihanbo have made a great contribution to the project.
They will lead the automation work.
Fixes #
```release-note
NONE
```
/hold
for a while to see if guys have any comments
=> Add hack owners

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/util/helper/binding.go
/kind feature
clean up works when resource binding has been removed
Fixes #425 
"NONE"
=> clean up works when resource binding has been removed

pkg/controllers/status/cluster_status_controller.go
/kind cleanup
Tracked by https://github.com/karmada-io/karmada/pull/417#discussion_r649629376
Fixes #
```release-note
NONE
```
=> Split listNodesAndPods function

pkg/controllers/status/cluster_status_controller.go
/kind feature
calculate `ResourceSummary` in new cluster API
Fixes #
```release-note
None
```
=> calculate ResourceSummary in new cluster API

.github/ISSUE_TEMPLATE/good-first.md
/kind cleanup
The `/assign` command in a separated line will assign the issue to the author. This PR fixed this issue.
Fixes #
```release-note
NONE
```
=> Update good first template

pkg/controllers/cluster/cluster_controller.go
Fix redundant log in cluster_controller.go
Fixes #445
Hi @RainbowMango, how does this look?
Let me know if this needs any changes.
Thanks
```release-note
NONE
```
=> Fix redundant log

pkg/controllers/status/cluster_status_controller.go, pkg/util/resource.go
/kind bug
/kind cleanup
Clean up cluster resource calculation and modify pending pods calculation
Fixes #
```release-note
NONE
```
=> modify pending pods resource calculation

pkg/util/cluster.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> use meta.IsStatusConditionTrue in cluster.go

artifacts/deploy/policy.karmada.io_propagationpolicies.yaml, pkg/apis/policy/v1alpha1/propagation_types.go
/kind cleanup
Fixes #
```release-note
```
=> fix(controller): rm useless subresource status

.golangci.yml, pkg/karmadactl/join.go, pkg/scheduler/scheduler.go, pkg/util/helper/binding.go, pkg/util/objectwatcher/retain.go
/kind cleanup
Introduced [gocyclo](https://github.com/fzipp/gocyclo) for cyclomatic complexity check.
A function with a higher cyclomatic complexity requires more test cases to cover all possible paths and is potentially harder to understand. 
Fixes #
Ignored 4 issues to get this tool on board, and these issue tracked by #460 
```release-note
NONE
```
=> Enable gocyclo static check

.gitignore
/kind cleanup
Fixes #
```release-note
```
=> Add binary files to gitignore

pkg/controllers/status/cluster_status_controller.go
/kind cleanup
Fixes #465
```release-note
```
=> fix(controller): rm sub-resources from cluster api enablement list

pkg/controllers/status/workstatus_controller.go
https://github.com/karmada-io/karmada/issues/467
/kind bug
Fixes #
```release-note
```
=> Fix sync work status

.github/workflows/ci.yml
/kind cleanup
In order to not block PR, running E2E on a self-hosted environment.
Refer to #481 
```release-note
NONE
```
=> Run E2E on selfhosted environment

pkg/util/objectwatcher/objectwatcher.go
/kind bug
Resolve the 'AlreadyExist' conflicts in a 'Create' process.       
1. Check if the exist resource in member cluster is managed by karmada.
2. Avoid updating resources that not managed by karmada.
2. If the exist resource is managed by karmada, try to update it.
Fixes #477 
"NONE"
=> resolve the 'AlreadyExist' conflicts in a 'Create' process

pkg/util/objectwatcher/retain.go
/kind cleanup
Clear functions with cyclomatic complexity greater than 15.
retainServiceFields() with complexity 20:
https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/util/objectwatcher/retain.go#L61
Part of #460
=> Cleanup cyclomatic complexity with function retainServiceFields

pkg/controllers/cluster/cluster_controller.go
/kind bug
```release-note
NONE
```
=> Wait context done to satisfy Runnalble interface

.github/workflows/ci.yml, .github/workflows/image.yml
/kind cleanup
Pin testing VM to `ubuntu-18.04`.
Fixes #481 
```release-note
NONE
```
=> Pin testing environment to ubuntu-18.04

test/e2e/clusterpropagationpolicy_test.go, test/e2e/failover_test.go, test/e2e/namespace_test.go, test/e2e/overridepolicy_test.go, test/e2e/propagationpolicy_test.go, test/e2e/resource_test.go, test/e2e/scheduling_test.go, test/e2e/suite_test.go
Replace wait.Poll with wait.PollImmediate from e2e testing.
Fixes #492
Hi @RainbowMango, how does this look?
Let me know if this needs any changes.
Thanks
```release-note
NONE
```
=> replace wait.Poll with wait.PollImmediate from e2e testing

artifacts/deploy/policy.karmada.io_clusterpropagationpolicies.yaml, artifacts/deploy/policy.karmada.io_propagationpolicies.yaml, pkg/apis/policy/v1alpha1/propagation_types.go, pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
/kind cleanup
Part of #344 
```release-note
```
=> Update ReplicaScheduling type 

pkg/util/constants.go, pkg/util/detector/detector.go
/kind feature
Add Replicas and ReplicaResourceRequirements  in binding.spec.Resource when creating
Part of #344
NONE
```release-note
```
=> add object resource info to binding

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/util/helper/binding.go
/kind feature
Set replicas in work according to the info in target clusters
Part of #344
NONE
```release-note
```
=> ensure work with given replicas

artifacts/kindClusterConfig/member1.yaml, artifacts/kindClusterConfig/member2.yaml, hack/karmada-bootstrap.sh, hack/util.sh
/kind feature
add cluster connectivity in e2e. 
Fixes #
”NONE“
=> add cluster connectivity in e2e

pkg/scheduler/core/generic_scheduler.go, pkg/scheduler/scheduler.go, pkg/util/spreadstate.go
/kind feature
Part of #344
NONE
```release-note
```
=> scheduler with Duplicated ReplicaSchedulingStrategy

pkg/scheduler/framework/plugins/apiinstalled/api_installed.go, pkg/util/cluster.go, pkg/util/helper/cluster.go, pkg/util/helper/cluster_test.go, test/e2e/clusterpropagationpolicy_test.go, test/e2e/propagationpolicy_test.go
/kind cleanup
Minor change just refactored a util function.
Fixes #
```release-note
NONE
```
=> refactor utils for checking API enablements

cmd/controller-manager/app/controllermanager.go, cmd/controller-manager/app/options/options.go, pkg/controllers/namespace/namespace_sync_controller.go, pkg/util/apigroup.go, pkg/util/apigroup_test.go, pkg/util/detector/detector.go
/kind feature
Fixes https://github.com/karmada-io/karmada/issues/345 
```release-note
```
=> Add skippedPropagatingAPIs option

pkg/controllers/status/cluster_status_controller.go
/kind cleanup
Fixes #
```release-note
```
=> Remove duplicate import

pkg/scheduler/core/generic_scheduler.go
/kind feature
Part of #344
None 
**How to work with it**:
Create deployment like this
```
metadata:
name: nginx
labels:
app: nginx
spec:
replicas: 3
selector:
matchLabels:
app: nginx
template:
···
```
and policy like this
```
metadata:
name: example-policy
spec:
name: nginx
placement:
clusterNames:
- member1
- member2 …
```
=> implementation of aggregated ReplicaDivisionPreference strategy

pkg/util/helper/workstatus.go
/kind cleanup
Use meta.IsStatusConditionTrue in `IsResourceApplied`.
Fixes #
```release-note
NONE
```
=> cleanup: use meta.IsStatusConditionTrue

hack/util.sh
/kind bug
Solve problems in the CI workflow: 'setup e2e test environment'
Fixes #522
NONE
=> add docker Status check in util::check_clusters_ready

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/controllers/mcs/service_export_controller.go, pkg/util/helper/binding.go, pkg/util/helper/work.go
/kind cleanup
Clear functions with cyclomatic complexity greater than 15.
EnsureWork() with complexity 21:
https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/util/helper/binding.go#L154
Part of #460
=> Cleanup cyclomatic complexity with function EnsureWork

pkg/webhook/work/mutating.go
in out cluster  we had  a little service cidr range. 
we use a lot of headless service. but in karmada webhook remove clusterIP filed.  in sub cluster svc allocate a lot of ip.
Fixes #   webhook remove clusterIP=None filed
=> webhook: when clusterIP=None do not remove clusterIP

pkg/util/detector/detector.go, test/e2e/scheduling_test.go
/kind cleanup
This PR intends to add more logs for debugging failing cases found at [here](https://github.com/karmada-io/karmada/runs/3073902867).
Fixes #
```release-note
NONE
```
=> Add more debug logs for failing case.

pkg/controllers/hpa/hpa_controller.go, pkg/controllers/namespace/namespace_sync_controller.go, pkg/util/binding.go
/kind cleanup
Working with Notes with `TODO(@XiShanYongYe-Chang)`, refactor util.CreateOrUpdateWork with helper.CreateOrUpdateWork.
Fixes #
```release-note
NONE
```
=> Replace util.CreateOrUpdateWork with helper.CreateOrUpdateWork

pkg/scheduler/scheduler.go
/kind feature
binding in scheduler should retry util it is successful so the maxRetries may be removed
NONE
NONE
=> never drop binding in scheduler when failed

pkg/util/detector/detector.go
…move.
/kind bug
Fixes #553
@RainbowMango  please review it.
```release-note
```
=> cleanup waitlist after resource template is removed

cmd/controller-manager/app/controllermanager.go, pkg/util/apigroup.go, pkg/util/apigroup_test.go
/kind cleanup
This PR extended the `SkippedResourceConfig` to return an error when the input can't parse.
Fixes #
```release-note
NONE
```
/cc @pigletfly
=> Enable validation for --skipped-propagating-apis flag

test/e2e/scheduling_test.go
/kind bug
E2E run failed occasionally in #556 , so I add waiting logic when collecting the target clusters in cluster resource binding.
Fixes #558 
```release-note
NONE
```
=> Fix scheduling test failing

.github/workflows/ci.yml
Switch CI runner from GitHub Action to `selfhosted` because issue #566
Fixes #
```release-note
NONE
```
=> CI: switch runner to selfhosted

hack/util.sh
Reduce pod wait time  and the number of retries
Fixes #566
```release-note
```
=> CI: Reduce pod wait time  and the number of retries

docs/proposals/proposal-template/proposal-template.md
Added proposal template.
Fixes #
```release-note
NONE
```
=> Docs: Add proposal template

pkg/scheduler/framework/runtime/framework.go
/kind bug
Fixes #571
```release-note
NONE
```
=> fix bug: score plugin does not work

docs/frequently-asked-questions.md
Setup FAQ documentation and added the first item.
Fixes #
```release-note
NONE
```
cc @Tingtal
=> Docs: Add FAQ about What is the difference between PropagationPolicy and ClusterPropagationPolicy?

pkg/util/informermanager/multi-cluster-manager.go
/kind bug
No locks are required for the informer to `Start` or `WaitForCacheSync`.
Add `(m *multiClusterInformerManagerImpl) getManager(cluster string) (SingleClusterInformerManager, bool) ` to reduce the code of `RLock`/`RUnlock`
Fixes #
```release-note
NONE
```
=> informermanager: cleanup lock operation

pkg/util/detector/detector.go
/kind feature
skip disabled gvr when new informers
Fixes #581 
[edit by @RainbowMango ]
Fixes #536 
```release-note
```
=> skip disabled gvr when new informers 

hack/README.md
Introduction for the main script in hack directory
Fixes #
NONE
=> Docs: add hack guidelines

pkg/util/constants.go, pkg/util/overridemanager/imageoverride.go, pkg/util/overridemanager/imageoverride_test.go
/kind feature
add image override support for DaemonSet
Fixes #
NONE
=> Add image override support for DaemonSet

artifacts/deploy/work.karmada.io_clusterresourcebindings.yaml, artifacts/deploy/work.karmada.io_resourcebindings.yaml, pkg/apis/work/v1alpha1/binding_types.go, pkg/util/helper/workstatus.go
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/575
```release-note
```
=> Add applied result in aggregated status

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/clusterdiscovery/clusterapi/clusterapi.go, pkg/controllers/mcs/service_export_controller.go, pkg/controllers/status/cluster_status_controller.go, pkg/controllers/status/workstatus_controller.go, pkg/util/context.go, pkg/util/detector/detector.go, pkg/util/informermanager/multi-cluster-manager.go, pkg/util/informermanager/single-cluster-manager.go
/kind feature
Stop the informer before deleting the cluster.
Fixes #384
```release-note
NONE
```
=> informer-manager: stop the informer before deleting the cluster

README.md
Docs: introduce the usage 'CLUSTER_IP_ONLY=true' to the readme
Fixes #607
```release-note
NONE
```
=> Docs: introduce the usage 'CLUSTER_IP_ONLY=true' to the readme

.github/ISSUE_TEMPLATE/flaking-test.md
/kind cleanup
Added one issue template for reporting flaking test found in CI.
Fixes #
```release-note
NONE
```
=> Add flaking test issue template

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/controllers/status/cluster_status_controller.go, pkg/util/membercluster_client.go, test/e2e/namespace_test.go, test/e2e/suite_test.go
/kind cleanup
Split from #611. Refer to https://github.com/karmada-io/karmada/pull/611#discussion_r690956629
Fixes #
**Special notes for your reviewer**: 
```release-note
NONE
```
/assign @Garrybest 
/cc @mrlihanbo
=> Move QPS and Burst to cluster status controller

docs/proposals/configurable-local-value-retention/README.md, docs/proposals/runtime-value-retention/README.md
/kind design
Configurable local value retention proposal.
Fixes #
```release-note
NONE
```
=> Proposal: Configurable local value retention

pkg/karmadactl/join.go
/kind cleanup
Clear functions with cyclomatic complexity greater than 15.
JoinCluster() exceeded the limit:
https://github.com/karmada-io/karmada/blob/c37bedc1cfe5a98b47703464fed837380c90902f/pkg/karmadactl/join.go#L179
Part of #460
=> Cleanup cyclomatic complexity with function JoinCluster

test/e2e/tainttoleration_test.go
/kind cleanup
/kind flake
Update the cluster with retry to solve the possible conflics in #614 .
```
------------------------------
propagation with taint and toleration testing Deployment propagation testing 
deployment with cluster tolerations testing
/root/cz/karmada/test/e2e/tainttoleration_test.go:131
STEP: creating policy(karmadatest-29n/deploy-p5z)
STEP: adding taints to clusters
I0820 15:54:27.023959  224122 tainttoleration_test.go:72] Adding taints(cluster-toleration.karmada.io=member1:NoSchedule) to clusterName(member1)
I0820 15:54:27.053125  224122 tainttoleration_test.go:72] Adding taints(cluster-toleration.karmada.io=member2:NoSchedule) to clusterName(member2) …
```
=> fix flake: propagation with taint and toleration testing

pkg/controllers/status/cluster_status_controller.go, pkg/util/detector/detector.go, pkg/util/resource.go
/kind cleanup
Share `AddPodRequest` in `detector.go`.
Fixes #
```release-note
NONE
```
=> reuse AddPodRequest in detector.go

pkg/webhook/work/mutating.go
/kind feature
Remove the automatic generation secrets in ServiceAccount
Fixes #602
```release-note
NONE
```
=> Remove the automatic generation secrets in ServiceAccount

docs/override_policy.md
Added a draft document for override policy.
Fixes #
Only focus on new-added `CommandOverrider` and `ArgsOverrider`.
```release-note
NONE
```
cc @lfbear @betaincao @Tingtal
=> Docs: Add override policy doc

README.md
This PR added the `Compatibility Matrix`.
Fixes #583
```release-note
NONE
```
=> Add compatibility Matrix

pkg/karmadactl/config.go
Signed-off-by: zhuyaguang <zhuyaguang1368@163.com>
/kind cleanup
注释规范
Fixes #
```release-note
```
=> Annotation should be start with func name

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/util/helper/workstatus.go, vendor/k8s.io/client-go/util/retry/OWNERS, vendor/k8s.io/client-go/util/retry/util.go, vendor/modules.txt
=> Retry conflict errors when aggregating binding status

.github/workflows/ci.yml, hack/karmada-bootstrap.sh
switched runner to github action from self hosted
This PR reverts back runner to github actions from self hosted
Fixes #681
none
```release-note
```
=> switched runner to github action

pkg/controllers/cluster/cluster_controller.go
/kind cleanup
fix comment mistake in pkg/controllers/cluster/cluster_controller.go
NA
```release-note
NONE
```
=> fix comment mistake in pkg/controllers/cluster/cluster_controller.go

pkg/scheduler/scheduler.go
/kind cleanup
**What this PR does**:
Cleanup cyclomatic complexity with function getScheduleType,make its  cyclomatic complexity below 15
>   https://github.com/karmada-io/karmada/blob/dba61fa92e8d22fb2292f5e5cd50d188185d7a34/pkg/scheduler/scheduler.go#L323
Fixes #460 
```release-note
NONE
```
=> Cleanup cyclomatic complexity with function getScheduleType

pkg/scheduler/core/generic_scheduler.go
/kind bug
If ReplicaDivisionPreference is set to "Weighted" and WeightPreference is not set, scheduler will weight all clusters the same, not return Error.
Fixes #
```release-note
NONE
```
=> set default weightPreference when WeightPreference is not set

pkg/scheduler/cache/snapshot.go, pkg/scheduler/core/generic_scheduler.go, pkg/scheduler/scheduler.go
/kind bug
fix bug of choosing candidate clusters when failover schedule
Fixes #
"NONE"
=> fix bug of choosing candidate clusters when failover schedule

.gitignore
I modified .gitignore to ingore karmada bninary
Fixes #691
```release-note
```
=> Modify .gitignore to ingore karmada bninary

test/e2e/scheduling_test.go
/kind cleanup
Add e2e test of ReplicaScheduling.
Fixes #694 
```release-note
NONE
```
=> add E2E test of ReplicaScheduling

pkg/scheduler/scheduler.go
/king cleanup
It'a refactor subtask refer to https://github.com/karmada-io/karmada/issues/460,  and I found someone finished this task already, however, I think it can be more readable and getting rid of some duplicate code.
Fixes #https://github.com/karmada-io/karmada/issues/460
```release-note
None
```
=> refactor func getScheduleType

.github/ISSUE_TEMPLATE/question.md
/kind feature
Add issue template of question. 
Fixes #671 
old pr has been closed, this is a same pr.
```release-note
None
```
=> add issue template of question

.gitignore, Makefile, cluster/images/karmada-scheduler-estimator/Dockerfile, cmd/scheduler-estimator/app/options/options.go, cmd/scheduler-estimator/app/scheduler-estimator.go, cmd/scheduler-estimator/main.go, pkg/estimator/server/nodes/filter.go, pkg/estimator/server/nodes/node_info.go, pkg/estimator/server/replica/replica.go, pkg/estimator/server/server.go, pkg/util/resource.go
/kind feature
Add the core of karmada-replica-estimator according to #617 
Fixes Step 4 of  #617 
```release-note
NONE
```
=> Add karmada-scheduler-estimator component

README.md
Modify typo in readme to change karamda to karmada .
The readme displayed on the home page of the project is wrong, which is easy to cause misunderstanding to readers. Therefore, I have corrected it.
NONE
NONE
NONE
=> Modify typo in README

test/e2e/fieldselector_test.go, test/e2e/mcs_test.go, test/e2e/scheduling_test.go
/kind flake
Here is an e2e test run failed in master branch: 
https://github.com/karmada-io/karmada/runs/3670936744?check_suite_focus=true
This is caused by a conflict while updating an object, so i add retry function.
Fixes #
```release-note
NONE
```
=> Add retry when update object in E2E

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/controllers/execution/execution_controller.go
/kind cleanup
Fetch member workload from cache to reduce the pressure of member api server
Fixes #
```release-note
NONE
```
=> Get member workload from cache instead of api server

artifacts/deploy/karmada-scheduler-estimator.yaml, hack/deploy-scheduler-estimator.sh, hack/local-up-karmada.sh
/kind feature
This PR gives a way to deploy karmada-scheduler-estimator.
Fixes Step 7 of #617.
```release-note
Adding deployment script of karmada-scheduler-estimator.
```
=> add deploy script of scheduler estimator

artifacts/agent/karmada-agent.yaml, artifacts/deploy/controller-manager.yaml, artifacts/deploy/karmada-cert-secret.yaml, artifacts/deploy/karmada-etcd.yaml, artifacts/deploy/karmada-webhook-cert-secret.yaml
Signed-off-by: iawia002 <z2d@jifangcheng.com>
/kind cleanup
Remove extra spaces from artifacts YAML files.
Fixes #
```release-note
NONE
```
/assign @RainbowMango
=> Remove extra spaces from artifacts YAML files

docs/multi-cluster-service.md, docs/working-with-submariner.md, hack/create-cluster.sh
Add docs about working with submariner.
Fixes #
Relying on #736 .
```release-note
```
=> Add docs about working with submariner

charts/Chart.yaml, charts/README.md, charts/templates/_helpers.tpl, charts/templates/karmada_scheduler_estimator.yaml, charts/values.yaml
/kind feature
Support helm install scheduler estimator according to  #617 
Fixes #
```release-note
"NONE"
```
=> support helm install scheduler estimator

pkg/controllers/mcs/endpointslice_controller.go, pkg/controllers/status/cluster_status_controller.go, pkg/util/helper/unstructured.go, pkg/webhook/work/mutating.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> clean up unstructured conversion

docs/upgrading/README.md, docs/upgrading/v0.8-v0.9.md
This PR added draft upgrading instruction.
Fixes #
```release-note
NONE
```
=> Docs: Add upgrading instructions

docs/scheduler-estimator.md
Add scheduler-estimator docs. This doc is linked to #764.
Fixes step 9 of #617.
```release-note
add scheduler-estimator docs
```
=> add scheduler-estimator docs

charts/templates/_patch_webhook_in_clusterresourcebindings.tpl, charts/templates/_patch_webhook_in_resourcebindings.tpl, charts/templates/post-install-job.yaml, charts/templates/pre-install-job.yaml
Signed-off-by: jrkeen <jrkeen@hotmail.com>
/kind feature
#776 
Fixes #
```release-note
NONE
```
=> chart support multi version conversion

cmd/controller-manager/app/controllermanager.go, pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/controllers/binding/common.go
/kind feature
According to the #398, make modifications based on the #741, add ResourceBinding/ClusterResourceBinding Event.
Part of #398 
Fixes #741
```release-note
```
=> Add ResourceBinding/ClusterResourceBinding Event

pkg/estimator/client/general.go
/kind feature
Max allowed pod number is an invisible constraint when calculating max available replicas in general estimator.
This PR is related to #723.
Fixes #
```release-note
NONE
```
=> add pod constraint in general estimator

pkg/util/informermanager/multi-cluster-manager.go
/kind bug
Fixes #
None
```release-note
```
=> fix: stop informer manager Instance once

pkg/clusterdiscovery/clusterapi/clusterapi.go, pkg/karmadactl/join.go, pkg/karmadactl/unjoin.go
/kind feature
Fixes #
```release-note
```
=> Extract join,unjoin parameters and pass struct to avoid too many parameters in the signature

docs/install-kubectl-karmada.md
Added `kubectl-karmada Installation` document.
Fixes #
```release-note
NONE
```
=> docs: install kubectl-karmada

pkg/karmadactl/cordon.go
Signed-off-by: algebra2k <jackson.cloudnative@gmail.com>
Fixes #892
=> fix: tips for karmadactl help options

pkg/karmadactl/cordon.go
/kind flake
`karmadactl cordon` command doesn't need klog output.  Replace klog with fmt.
Fixes #
```release-note
NONE
```
=> Remove klog from karmadactl cordon

cmd/controller-manager/app/controllermanager.go
/kind bug
Fixes #906
```release-note
```
=> fix skipped-propagating-apis not take effect

charts/templates/post-install-job.yaml, charts/templates/pre-install-job.yaml, charts/values.yaml
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/912
```release-note
```
=> Make post-install-job pre-install-job image configurable

cmd/controller-manager/app/options/validation.go
/kind feature
Fixes #
```release-note
```
=> add controller-manager parameter validation

pkg/util/apigroup.go, pkg/util/apigroup_test.go
/kind design
Please refer to https://github.com/karmada-io/karmada/issues/924#issue-1045630856
Fixes #924
```release-note
NONE
```
=> Skip propagating events by default

pkg/karmadactl/cordon.go
Signed-off-by: wawa0210 <xiaozhang0210@hotmail.com>
/kind cleanup
Fixes #
```release-note
```
=> [Trival] remove muti error return when cordon.PatchOrReplace

pkg/features/features.go
/kind cleanup
At the end of #805, I forgot to update the comment of `FeatureGate`.
Fixes #
```release-note
NONE
```
/assign @RainbowMango
=> Update the comments of the FeatureGate instance

pkg/controllers/execution/execution_controller.go, pkg/controllers/mcs/service_export_controller.go, pkg/controllers/status/cluster_status_controller.go, pkg/controllers/status/workstatus_controller.go, pkg/util/membercluster_client.go, pkg/util/objectwatcher/objectwatcher.go, test/e2e/framework/cluster.go, test/e2e/namespace_test.go
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/921
```release-note
```
=> refactor object watcher interface

pkg/util/helper/binding.go
/kind bug
when we remove orphan works failed, we cannot print successful logs. so add `continue` statement to continue to the next loop, but not print successful logs.
Fixes #
```release-note
NONE
```
=> remove orphan works failed cannot print successful logs

cmd/controller-manager/app/controllermanager.go, hack/local-up-karmada.sh, pkg/karmadactl/cordon.go, pkg/karmadactl/get_flags.go, pkg/scheduler/scheduler.go, pkg/util/worker.go
/kind cleanup
do some minor cleanup
Fixes #
```release-note
```
=> cleanup some codes

hack/local-up-karmada.sh
/kind flake
Add greeting logo when karmada has started successfully, like below.
Fixes #
```release-note
```
=> add colorful greeting ascii art

charts/_crds/bases/config.karmada.io_resourceexploringwebhookconfigurations.yaml, pkg/apis/config/v1alpha1/explorewebhook_types.go
Modify `resourceexploringwebhookconfigurations` CRD to cluster scope.
Fixes #
```release-note
```
=> modify resourceexploringwebhookconfigurations to cluster scope

pkg/crdexplorer/crdexplorer.go, pkg/crdexplorer/customizedexplorer/configmanager/accessor.go, pkg/crdexplorer/customizedexplorer/configmanager/manager.go, pkg/crdexplorer/customizedexplorer/customized.go, pkg/crdexplorer/defaultexplorer/default.go, pkg/crdexplorer/defaultexplorer/healthy.go, pkg/crdexplorer/defaultexplorer/packing.go, pkg/crdexplorer/defaultexplorer/replica.go
/kind design
/kind feature
Add explore interface design for `Resource Explore Webhook`.
Part of #923 
```release-note
```
=> Add interface design for Resource Explore Webhook

cmd/controller-manager/app/controllermanager.go, pkg/crdexplorer/crdexplorer.go, pkg/crdexplorer/customizedexplorer/customized.go, pkg/crdexplorer/defaultexplorer/default.go, pkg/crdexplorer/defaultexplorer/replica.go, pkg/detector/detector.go, pkg/util/helper/binding.go
/kind feature
Setup custom resource explorer.
Fixes #
```release-note
NONE
```
=> Setup custom resource explorer

pkg/crdexplorer/crdexplorer.go, pkg/crdexplorer/customizedexplorer/configmanager/accessor.go, pkg/crdexplorer/customizedexplorer/configmanager/manager.go, pkg/crdexplorer/customizedexplorer/customized.go, pkg/crdexplorer/customizedexplorer/webhook/attributes.go, pkg/crdexplorer/customizedexplorer/webhook/explorereview.go, pkg/crdexplorer/defaultexplorer/default.go, pkg/crdexplorer/defaultexplorer/healthy.go, pkg/crdexplorer/defaultexplorer/packing.go, pkg/crdexplorer/defaultexplorer/replica.go, pkg/detector/detector.go, pkg/util/crdexplorer/rules.go, pkg/util/helper/unstructured.go
/kind feature
Match hooks and spawn remote calls to webhook.
Part of #923 
```release-note
```
=> Match hooks and spawn remote calls to webhook

pkg/apis/config/v1alpha1/explorereview_types.go, pkg/apis/config/v1alpha1/zz_generated.deepcopy.go, pkg/crdexplorer/customizedexplorer/webhook/attributes.go, pkg/crdexplorer/customizedexplorer/webhook/explorereview.go
/kind feature
We are going to add a `Status` filed to reflect it the request has been handled properly, so, rename the current field to make the room.
Fixes #
```release-note
NONE(as feature not released.)
```
=> Rename ExploreReview status to rawstatus

cmd/controller-manager/app/controllermanager.go, cmd/controller-manager/app/options/validation.go, cmd/controller-manager/app/options/validation_test.go
add validation test for a controller - manager and refactor the validation of controller-manager
Part of #919 
NONE
=> Feature add validation test

cmd/scheduler-estimator/app/options/validation.go, cmd/scheduler-estimator/app/options/validation_test.go, cmd/scheduler-estimator/app/scheduler-estimator.go
…tion of scheduler-estimator
add  scheduler-estimator flag validate 
Fixes #919 
```release-note
```
NONE
=> add validation test for scheduler-estimator

pkg/crdexplorer/customizedexplorer/customized.go, pkg/crdexplorer/customizedexplorer/webhook/attributes.go, pkg/crdexplorer/customizedexplorer/webhook/explorereview.go, pkg/webhook/explorer/decode.go, pkg/webhook/explorer/http.go, pkg/webhook/explorer/inject.go, pkg/webhook/explorer/response.go, pkg/webhook/explorer/webhook.go
/kind feature
Add hook handler interface and demo for resource explore webhook.
Part of #923 
```release-note
```
=> Add Hook handler interface

examples/README.md, examples/customresourceexplorer/apis/workload/v1alpha1/workload_types.go, examples/customresourceexplorer/webhook/main.go
/kind feature
Setup webhook example structure.
Fixes #
```release-note
NONE
```
=> Setup webhook example structure

pkg/util/secret.go
/kind bug
In [some cases](https://github.com/kubernetes/kubernetes/issues/98415), the first secret does not exist, we should continue to try subsequent secrets
Fixes #
```release-note
NONE
```
=> pkg/util/secret: Fix GetTargetSecret

pkg/karmadactl/get.go, pkg/karmadactl/karmadactl.go
/kind feature
Fixes #896
The current examples are shown in the picture below. If you need to add examples, please let me know
```release-note
```
=> add karmadactl get -h example

go.mod, pkg/crdexplorer/crdexplorer.go, pkg/crdexplorer/customizedexplorer/webhook/attributes.go, pkg/crdexplorer/customizedexplorer/webhook/explorereview.go, pkg/webhook/explorer/decode.go, pkg/webhook/explorer/response.go, vendor/modules.txt
/kind feature
Part of #923 
```release-note
```
=> adapt ObservedObject adding in resource explore webhook

pkg/crdexplorer/crdexplorer.go, pkg/crdexplorer/customizedexplorer/customized.go, pkg/crdexplorer/customizedexplorer/webhook/explorereview.go, pkg/crdexplorer/defaultexplorer/default.go
/kind feature
Part of #923 
```release-note
```
=> add retion explorer webhook call

pkg/webhook/crdexplorer/helper_test.go, pkg/webhook/crdexplorer/validating_test.go
/kind test
add unit test for webhook validation
part of #923 
```release-note
```
=> add unit test for webhook validation

docs/upgrading/README.md, docs/upgrading/v0.8-v0.9.md, docs/upgrading/v0.9-v0.10.md
Add upgrade document for v0.9-v0.10.
Fixes #
```release-note
NONE
```
=> Add upgrade document for v0.9-v0.10

Makefile
/kind cleanup
Fix failing test
https://github.com/karmada-io/karmada/runs/4273551922?check_suite_focus=true
Fixes #
```release-note
NONE
```
=> Enable build example image and push to registry

README.md
/kind cleanup
Our slack has been migrated to CNCF now. 
Fixes #
```release-note
NONE
```
=> Update slack link to CNCF channel

.gitignore
/kind bug
Add karmada-interpreter-webhook-example binary to .gitignore in alphabetical order.
Fixes #https://github.com/karmada-io/karmada/issues/1005
```release-note
NONE
```
=> Ignore karmada-interpreter-webhook-example binary

hack/.import-aliases
Fixes #1008
```release-note
None
```
=> Add import alias for config/v1alpha1

pkg/util/names/names_test.go
/kind bug
Fixes #
```release-note
```
=> Fix generate rb key

docs/upgrading/README.md
Update upgrade instructions.
Fixes #
```release-note
NONE
```
=> Update upgrade instruction about latest patch version selecting

pkg/util/gclient/gclient.go
/kind feature
Add `config v1alpha1` schemes to gclient.
Fixes #
```release-note
NONE
```
=> Add config v1alpha1 schemes to gclient

Makefile
/kind cleanup
add karmada-interpreter-webhook-example to make all/clean
Fixes #1017 
NONE
```release-note
```
=> add karmada-interpreter-webhook-example to make all/clean

pkg/util/apigroup.go, pkg/util/apigroup_test.go
Fixes #1018 
```release-note
```
=> ignore configv1alpha1 group in detector

.github/workflows/release.yml, .krew.yaml
Signed-off-by: Vincent Cui <dustise@live.com>
/kind flake
Update krew index when release published.
=> Update krew index when release published.

test/e2e/failover_test.go, test/e2e/fieldselector_test.go, test/e2e/framework/cluster.go, test/e2e/framework/deployment.go, test/e2e/framework/job.go, test/e2e/framework/namespace.go, test/e2e/framework/overridepolicy.go, test/e2e/framework/pod.go, test/e2e/framework/service.go, test/e2e/mcs_test.go, test/e2e/namespace_test.go, test/e2e/overridepolicy_test.go, test/e2e/propagationpolicy_test.go, test/e2e/resource_test.go, test/e2e/scheduling_test.go, test/e2e/tainttoleration_test.go
/kind cleanup
#835 has refactored part of the e2e framework, this pr refactor the rest.
Fixes #
```release-note
NONE
```
=> Refector: add framework for e2e

pkg/apis/work/v1alpha1/binding_types_conversion.go, pkg/estimator/client/accurate.go, pkg/estimator/client/general.go, pkg/util/resource.go
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/893#issuecomment-967077389
```release-note
NONE
```
=> optimize ResourceList in resource.go

pkg/util/names/names_test.go
Fixes #1021 
```release-note
```
=> add unit test for functions of generating names

hack/deploy-karmada.sh
/kind cleanup
Now `deploy-karmada.sh` will modify files in the repo so the git status is not clean. We could copy these files into temporary directory and have a cabundle replacement.
https://github.com/karmada-io/karmada/blob/b54a75ec24faccb617fc89e780e070dcf9221176/hack/deploy-karmada.sh#L200-L202
Fixes #
```release-note
NONE
```
=> copy CRD files and install in case modifying files in repo

pkg/detector/aggregate_status.go, pkg/util/helper/job.go
/kind feature
Fixes #
```release-note
NONE
```
=> add startTime and completionTime in job status

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/controllers/execution/execution_controller.go, pkg/controllers/status/workstatus_controller.go
/kind cleanup
Fixes #
```release-note
```
=> Add retry on update status

pkg/util/error_test.go
=> add ut for AggregateErrors

hack/README.md
Fixes #
```release-note
NONE
```
=> add estimator docs in hack directory

pkg/karmadactl/cordon.go, pkg/karmadactl/get.go
/kind cleanup
structure `CommandGetOptions` has some un-used fields, we can remove these.
karmadactl get/cordon cmds not clean, modify some logics.
Fixes #
```release-note
```
=> cleanup karmada ctl code

docs/reserved-namespaces.md
To remind users of karmada reserved namespaces
Fixes #985
```release-note
None
```
=> Add Reserved Namespace Rule

cmd/scheduler-estimator/app/scheduler-estimator.go, pkg/estimator/server/metrics/metrics.go, pkg/estimator/server/server.go, pkg/util/metrics/metrics.go, vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go, vendor/modules.txt
/kind feature
Fixes #
```release-note
NONE
```
=> add metrics for scheduler estimator

docs/proposals/resource-quota/README.md
Signed-off-by: as1919@qq.com
/kind design
Add a new proposal, KEP-377:  proposal about Karmada ResourceQuota
Fixes #377 
```release-note
proposal about Karmada ResourceQuota
```
=> add KEP-377: proposal about Karmada ResourceQuota

pkg/karmadactl/join.go
/kind cleanup
When the cluster already exist, we execute `karmadactl join`
```
[root@master67 karmada]# karmadactl join member68 --cluster-kubeconfig=/root/.kube/config 
Error: failed to patch secret /, error: resource name may not be empty
```
change to
```
[root@master67 karmada]# karmadactl join member68 --cluster-kubeconfig=/root/.kube/config
Error: failed to create cluster(member68) object. error: cluster(member68) already exist
```
And add the tip when joining successfully
```
[root@master67 karmada]# karmadactl join member68 --cluster-kubeconfig=/root/.kube/config
cluster(member68) is joined successfully
```
Fixes #
**Special notes for …
=> update error report when cluster already exist

README.md
Older versions are not recommended to users.  #1059 
Fixes #
```release-note
NONE
```
=> update the compatibility matrix

charts/templates/karmada_agent.yaml
/kind bug
karmada-agent deployed without resources, which is missing in the chart template, this PR fixed it.
NONE
=> add resources to karmada-agent in chart template

pkg/clusterdiscovery/clusterapi/clusterapi.go, pkg/controllers/mcs/service_export_controller.go, pkg/controllers/status/workstatus_controller.go, pkg/detector/detector.go, pkg/scheduler/scheduler.go, pkg/util/worker.go
/kind bug
Fixes #1068 
```release-note
NONE
```
=> fix slow enqueue of async worker

pkg/util/worker.go
/kind cleanup
Add some comment on the `AsyncWorker`.
Fixes #
```release-note
NONE
```
cc @Garrybest
=> Add more comment on AsyncWorker

charts/Chart.yaml, charts/README.md, charts/templates/etcd.yaml, charts/templates/karmada_apiserver.yaml, charts/templates/post-install-job.yaml, charts/templates/pre-install-job.yaml, charts/values.yaml
/kind feature
Enhance helm chart to support more scenes
Fixes #1072
By default, it is no different from the previous version. After adding some parameters in chart, we can support the deployment of multiple on the same cluster through different namespaces (for testing or...), support different karmada-apiserver service types, and support hostpath or pvc for ETCD, support multiple ETCD replicas.
```release-note
NONE
```
=> Chart enhancement

cmd/controller-manager/app/controllermanager.go, cmd/controller-manager/app/options/options.go
/kind cleanup
This PR uses the `StringSliceVar` method to optimize the `--controllers` flag, this will make the original code easier to use and read.
ref #1083
```release-note
NONE
```
/cc @RainbowMango @snowplayfire
=> Optimize the controllers flag

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/controllers/binding/common.go, pkg/util/helper/workstatus.go
/kind cleanup
Fixes #
```
status:
aggregatedStatus:
- clusterName: member1
conditions:
- lastTransitionTime: "2021-12-02T12:28:22Z"
message: the binding has been scheduled
reason: BindingScheduled
status: "True"
type: Scheduled
- lastTransitionTime: "2021-12-02T12:28:22Z"
message: Failed to apply all works, see status.aggregatedStatus for details
reason: FullyAppliedFailed
status: "False"
type: FullyApplied
```
"NONE"
=> update FullyApplied condition after aggregating works status

docs/working-with-velero.md
add document about how to use velero to backup karmada resources.
Fixes #
```release-note
```
=> add velero integration doc

docs/README.md
Setup documentation structure.
Fixes #
```release-note
NONE
```
=> Add document structure

pkg/util/names/names.go
/kind cleanup
Clean up the `names` package and modify the comments format.
Fixes #
```release-note
NONE
```
=> Cleanup names package

test/e2e/porting_workloads_test.go
See our previous discussion at https://github.com/karmada-io/karmada/pull/1098#discussion_r768253161
ref: https://github.com/karmada-io/karmada/pull/1098#issuecomment-993458453
```release-note
NONE
```
/assign @XiShanYongYe-Chang
=> Fix namespace issue in the porting workloads e2e test

cmd/controller-manager/app/controllermanager.go
/kind feature
Enhancement --controllers flag of karmada-controller-manager
Part of  #1085
```release-note
NONE
```
=> Enhancement --controllers flag of karmada-controller-manager

pkg/util/binding.go, pkg/util/binding_test.go
/kind bug
Fixes #1117
```release-note
NONE
```
=> fix panix in DivideReplicasByTargetCluster

go.mod, pkg/karmadactl/cmdinit/kubernetes/namespace.go, pkg/karmadactl/cmdinit/kubernetes/rbac.go, pkg/karmadactl/cmdinit/kubernetes/secret.go, pkg/karmadactl/cmdinit/kubernetes/services.go, vendor/modules.txt
/kind cleanup
replace github.com/pkg/errors with golang native errors
Fixes #
```release-note
```
=> replace github.com/pkg/errors with golang native errors

artifacts/example/cr_cluster.yaml
/kind bug
/kind cleanup
Fixes #
```release-note
```
=> Fix incorrect cluster demo yaml

test/e2e/overridepolicy_test.go, test/helper/policy.go
/kind feature
Add a e2e test for OverrideRules of OverridePolicy
****
Part of #1113 
```release-note
```
=> Add a e2e test for OverrideRules of OverridePolicy

pkg/scheduler/scheduler.go
/kind bug
Refer to [here](https://github.com/karmada-io/karmada/blob/master/pkg/util/worker.go#L89-L103)
Fixes #
```release-note
NONE
```
=> add rate limited when errors occur in scheduler

cmd/scheduler-estimator/OWNERS
/kind cleanup
@Garrybest  is the owner of `karmada-scheduler-estimator` but missed it from #808.
Fixes #
```release-note
NONE
```
=> Add Garrybest on the owner list of karmada-scheduler-estimator

pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
/kind cleanup
Part of #1113 
```release-note
NONE
```
=> Update webhook_configuration of `karmadactl init`

docs/README.md, docs/installation/install-kubectl-karmada.md, docs/installation/installation.md
Add Karmada installation document.
Fixes #
```release-note
NONE
```
cc @prodanlabs
=> Add installation document

docs/working-with-filebeat.md
Use Filebeat to collect logs of Karmada member clusters
Fixes #
NONE
```release-note
```
=> add filebeat doc

docs/working-with-prometheus.md
Use Prometheus to monitor Karmada member clusters
Fixes #
NONE
```release-note
```
=> add prometheus doc

pkg/util/rbac.go
/kind bug
fix the name of impersonate service account
Fixes #
"NONE"
=> fix the name of impersonate service account

docs/bash-auto-completion-on-linux.md
Add a document about using auto-completion of `karmadactl`
Part #1046 
I consider firstly introduce the auto-completion document of `karmadactl`, if there will be official support for `plugin` auto-completion, we'll supplement the document about `kubectl karmada`.
```release-note
NONE
```
=> Add auto-completion document for karmadactl

test/e2e/unjoin_test.go
/kind feature
Add e2e test for unjoining not ready cluster
Fixes #1055 
```release-note
```
=> Add e2e test for unjoining not ready cluster

cmd/controller-manager/app/controllermanager.go, examples/customresourceinterpreter/webhook-configuration.yaml, examples/customresourceinterpreter/webhook/app/workloadwebhook.go, pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/controllers/binding/common.go, pkg/controllers/context/context.go, pkg/resourceinterpreter/customizedinterpreter/customized.go, pkg/resourceinterpreter/defaultinterpreter/default.go, pkg/resourceinterpreter/defaultinterpreter/revisereplica.go, pkg/resourceinterpreter/interpreter.go, pkg/util/helper/unstructured.go, pkg/webhook/configuration/validating.go
/kind feature
This patch implements the `ReviseReplica` hook, check [resource interpreter webhook proposal](https://github.com/karmada-io/karmada/tree/master/docs/proposals/resource-interpreter-webhook) for more info.
The original code to modify the replica of `Deployment` and `Job` has been changed to use default interpreters, for custom resources, users only need to implement the corresponding webhook and return the patch that updates the replica, take our `workload` resource for example:
```go
func (e *workloadInterpreter) responseWithExploreReviseReplica(workload *workloadv1alpha1.Workload, req interpreter.Request) interpreter.Response {
wantedWorkload := …
```
=> Implementing the ReviseReplica hook

pkg/estimator/server/server.go
/kind cleanup
```release-note
NONE
```
=> simplify waitForCacheSync func

cmd/OWNERS, pkg/karmadactl/OWNERS
/kind cleanup
This PR put @lonelyCZ on the owner list.
@lonelyCZ made impressive contributions to the commands and significantly improved the user experience.
such as:
- #1132 leading the effort of `karmada promote`
- #1110 more print columns for rb,crb and work
Full list of contribution please refer to:
https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3AlonelyCZ+is%3Amerged
Fixes #
```release-note
NONE
```
=> Put lonelyCZ on the owner list

charts/README.md, charts/templates/_helpers.tpl, charts/templates/_karmada_apiservice.tpl, charts/templates/_karmada_system_namespace.tpl, charts/templates/_karmada_webhook_configuration.tpl, charts/templates/karmada-aggregated-apiserver.yaml, charts/templates/karmada_apiserver.yaml, charts/templates/karmada_cert.yaml, charts/templates/pre-install-job.yaml, charts/values.yaml
#1147
Fixes #1147
```release-note
```
=> support install karmada aggregated apiserver by helm

docs/README.md, docs/frequently-asked-questions.md, docs/userguide/cluster-registration.md
This PR added the cluster registration documents.
Fixes #1088
```release-note
NONE
```
=> Add cluster registration documents

hack/util.sh
/kind bug
Adapt for hostname in LoadBalancer, like AWS
Fixes #1118
```release-note
NONE
```
=> Adapt for hostname in LoadBalancer

docs/upgrading/README.md, docs/upgrading/v0.10-v1.0.md
Add upgrade document for v0.10-v1.0.
Fixes #
```release-note
NONE
```
=> Add upgrade document for v0.10-v1.0.

cmd/agent/app/agent.go, pkg/controllers/unifiedauth/ensure_impersonation_secret.go, pkg/karmadactl/join.go, pkg/registry/cluster/storage/proxy.go
/kind feature
As #1180 add impersonator secret reference to Cluster API, we need to update related logic to add impersonatorSecretRef for cluster object, not hard code.
Fixes #1077 
I also remove the `caBundle` value when collecting impersontionSecret from the member cluster.
```release-note
```
=> add impersonatorSecretRef for cluster object

pkg/karmadactl/cmdinit/cmdinit.go, pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cmdinit/utils/examples.go, pkg/karmadactl/cmdinit/utils/examples_test.go, pkg/karmadactl/karmadactl.go
/kind cleanup
Some people like to use `karmadactl`, so add it.
Fixes #
```release-note
NONE
```
/cc @RainbowMango @prodanlabs
=> Add parentCommand to make init command compatible with `karmadactl`

pkg/registry/cluster/storage/proxy.go
/kind cleanup
Now we will add all groups get from user info: 
https://github.com/karmada-io/karmada/blob/1aa32e5c108af10ce6007cdcb7215d9f80b73699/pkg/registry/cluster/storage/proxy.go#L102-L105
But some group like `system:unauthenticated`, `system:authenticated`, that user should not pay attention to, so need to skip them.
Fixes #
If the enumerated values are omitted, we can add them later.
```release-note
```
=> Ignore auto-generated user groups when proxy request

docs/working-with-filebeat.md
Signed-off-by: z00623291 <zhouhongcen1@huawei.com>
modify filebeat doc reference
NONE
```release-note
```
=> modify filebeat doc reference

hack/README.md, hack/local-up-karmada.sh, hack/util.sh
/kind bug
Changed the installation mode of kind
Fixes #1141 
@lfbear @RainbowMango
```release-note
NONE
```
=> changed the installation mode of k8s kind

charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml, charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml, charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml, charts/_crds/bases/work.karmada.io_resourcebindings.yaml, pkg/apis/policy/v1alpha1/propagation_types.go, pkg/apis/work/v1alpha2/binding_types.go
/kind feature
update apis for automatically propagate dependencies according to Step 1 of #705 .
Fixes Step 1 of #705 
"NONE"
=> update apis for automatically propagate dependencies

test/e2e/framework/workload.go, test/e2e/resourceinterpreter_test.go
/kind feature
Add e2e test case for #1149
Fixes #
```release-note
NONE
```
/cc @XiShanYongYe-Chang @RainbowMango
=> Add e2e test for the ReviseReplica hook

docs/README.md, docs/userguide/failover.md
add docs about the failover policy in karmada
Fixes #
"NONE"
=> add docs: failover policy overview

cmd/controller-manager/app/options/options.go
/kind cleanup
```release-note
NONE
```
=> add code comments for the karmada-controller-manager options

pkg/controllers/cluster/cluster_controller.go
/kind bug
As #828 merged, this code block is never called.
```release-note
NONE
```
=> remove unreachable code

pkg/karmadactl/cmdinit/utils/format.go, pkg/karmadactl/cmdinit/utils/kubeclient.go, pkg/karmadactl/cmdinit/utils/util.go, pkg/karmadactl/cmdinit/utils/util_test.go
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/1208
NONE
=> Comment should start with a whitespace

docs/installation/installation.md
The init command flags is crds.
```
Flags:
--crds string                                      Karmada crds resource.(local file e.g. --crds /root/crds.tar.gz) (default "https://github.com/karmada-io/karmada/releases/download/v0.10.1-262-gb3ee38dc-dirty/crds.tar.gz")
```
Fixes #
```release-note
```
=> installation document correction.

pkg/karmadactl/cmdinit/cert/cert.go, pkg/karmadactl/cmdinit/karmada/deploy.go, pkg/karmadactl/cmdinit/kubernetes/check.go, pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cmdinit/kubernetes/rbac.go, pkg/karmadactl/cmdinit/kubernetes/secret.go, pkg/karmadactl/cmdinit/kubernetes/serviceaccount.go, pkg/karmadactl/cmdinit/options/global.go
/kind cleanup
Normalized comments, etc.
Fixes #
```release-note
```
=> organize `karmadactl init` code

pkg/apis/cluster/types.go
/kind cleanup
Add comments for internal Cluster API.
Fixes #
```release-note
```
=> add comments for internal Cluster API

examples/README.md
Fixes https://github.com/karmada-io/karmada/issues/1136#issuecomment-1000994560
```release-note
NONE
```
=> Add Resource Interpreter Examples Document

pkg/karmadactl/join.go, pkg/karmadactl/options/global.go
/kind cleanup
Fixes #1166
```release-note
```
=> fix --cluster-namespace misleading description

docs/README.md, docs/userguide/resource-propagating.md
Add docs about how to `Deploy a simplest multi-cluster Deployment`.
Fixes #
```release-note
NONE
```
=> add docs: Deploy a simplest multi-cluster Deployment

docs/README.md, docs/contributors/devel/cherry-picks.md, hack/cherry_pick_pull.sh
Organize documents about cherry-picks according to #1210.
Fixes #1210
```release-note
NONE
```
=> Orgnize documents about cherry-picks

pkg/controllers/mcs/service_import_controller.go, pkg/controllers/status/cluster_status_controller.go, pkg/detector/aggregate_status.go
Signed-off-by: pigletfly wangbing.adam@gmail.com
Fixes #
```release-note
```
=> Retry on status update conflict

docs/userguide/resource-propagating.md
Add docs: Deploy deployment into a specified set of target clusters.
Fixes #
```release-note
```
=> Add docs: Deploy deployment into a specified set of target clusters

pkg/controllers/status/workstatus_controller.go
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/1235
```release-note
NONE
```
=> Focus on the functions syncWorkStatus and reflectStatus, modify comments and rename variable names

docs/installation/installation.md
Add documents for installing Karmada in Kind cluster.
Fixes #
```release-note
NONE
```
cc @prodanlabs
=> Add documents for installing Karmada in Kind

docs/userguide/cluster-registration.md
Added description about how Karmada CLI gets user and cluster configuration when registering cluster.
Fixes #1243 
```release-note
NONE
```
=> Improve register document

pkg/karmadactl/cmdinit/OWNERS
Put @prodanlabs to owner list, @prodanlabs did great contributions for the last release and contributed [Karmada installation feature](https://github.com/karmada-io/karmada/blob/master/docs/installation/installation.md#install-karmada-by-karmada-command-line-tool). He will continually lead the effort to iterate this feature.
Fixes #
```release-note
NONE
```
=> Put prodanlabs to owner list 

README.md
Update Kubernetes compatibilities for Kubernetes v1.22 and v1.23.
- v1.22:  Testing at CI environment (#1256)
- v1.23: Manually tested.
Fixes #
```release-note
NONE
```
=> Update Kubernetes compatibilities for v1.22 and v1.23

pkg/detector/detector.go
/kind bug
Fixes #
```release-note
karmada-controller-manager: Fixed ApplyPolicySucceed event type mistake
```
=> fix event type of apply policy

pkg/controllers/mcs/service_import_controller.go
Signed-off-by: ashley-rongfang <rongfang@huawei.com>
/kind cleanup
Fixes #1244
```release-note
NONE
```
=> Update first in RetryOnConflict

pkg/scheduler/scheduler.go
/kind cleanup
Fixes #1247 
```release-note
NONE
```
=> modify log type to Error when err ocurs

pkg/controllers/binding/common.go
/kind feature
fix cyclomatic complexity
Fixes #
```release-note
NONE
```
=> fix ensureWork cyclomatic complexity

docs/userguide/cluster-registration.md
Fixes #1279 
```release-note
NONE
```
=> Fix documentation mistake of cluster registration #1279

docs/README.md, docs/userguide/customizing-resource-interpreter.md
Added `CustomResourceInterpreter` document.
Fixes #1250
```release-note
NONE
```
=> Add resource interpreter document

pkg/karmadactl/cmdinit/kubernetes/deploy.go
karmada init: add more message for easy debug  when nodePort exist
Fixes #
```release-note
NONE
```
=> karmada init: add more message for easy debug  when nodePort exist

pkg/detector/compare_test.go
/kind cleanup
Fix typo in the `pkg/detector/compare_test.go`.
Fixes #
```release-note
NONE
```
=> Fix typo in the test log

pkg/resourceinterpreter/OWNERS
The [Resource Interpreter](https://github.com/karmada-io/karmada/tree/master/docs/proposals/resource-interpreter-webhook) is a very important feature of Karmada, @XiShanYongYe-Chang @iawia002 is the main author of the framework, this PR put both of them on the owner list, they will lead the effort to iterate this feature in the future.
Fixes #
If no objection, this PR will be merged by the end of this week.
```release-note
NONE
```
=> Nominate resource interpreter framework owners

pkg/util/helper/binding.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Fix ignore log error when error is isnotfound

test/e2e/framework/workload.go, test/e2e/resourceinterpreter_test.go
/kind feature
Add e2e test case for #1253
close #1237 
```release-note
NONE
```
/cc @XiShanYongYe-Chang @RainbowMango
=> Add e2e test for the AggregateStatus hook

docs/README.md, docs/userguide/configure-controllers.md
Added documents about configuring controllers.
Fixes #1249 
```release-note
NONE
```
=> Add documents about karmada controllers

pkg/detector/detector.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Fix log in detector

cmd/agent/app/agent.go, cmd/agent/main.go
/kind bug
```release-note
None
```
=> bug: agent's os.Exit will not wait for the defer function

cmd/aggregated-apiserver/app/options/options.go, cmd/aggregated-apiserver/main.go
/kind bug
Part of #https://github.com/karmada-io/karmada/issues/1313
```release-note
None
```
=> bug: aggregated-apiserver's os.Exit will not wait for the defer function

cmd/controller-manager/controller-manager.go
/kind bug
```release-note
None
```
=> bug: controller-manager's os.Exit will not wait for the defer function

docs/userguide/resource-propagating.md
Corrected grammar mistakes.
```release-note
NONE
```
=> Revised command output info

cmd/karmadactl/karmadactl.go
/kind bug
```release-note
None
```
=> bug: karmadactl's os.Exit will not wait for the defer function

cmd/kubectl-karmada/kubectl-karmada.go
/kind bug
```release-note
None
```
=> bug: kubectl karmada's os.Exit will not wait for the defer function

cmd/scheduler-estimator/main.go
/kind bug
```release-note
None
```
=> bug: estimator's os.Exit will not wait for the defer function

cmd/webhook/main.go
/kind bug
Fixes #1313
```release-note
None
```
=> bug: webhook's os.Exit will not wait for the defer function

OWNERS
Update repo owners.
Fixes #
```release-note
NONE
```
cc @Garrybest @XiShanYongYe-Chang 
Happy New Year! by the way.
=> Set up repo owners

pkg/karmadactl/get.go
/kind cleanup
`karmadaConfig` has been initialized in `pkg/karmadactl/karmadactl.go` that can use current kubeconfig and context by default.  
Fixes #
```release-note
NONE
```
=> Cleanup checking kubeconfig in karmadactl get

pkg/controllers/binding/common.go
/kind bug
Replica set by overridepolicy in its Plaintext will be reset by ReviseReplica interperterhook
Fixes https://github.com/karmada-io/karmada/issues/1347
NONE
```release-note
fix a bug that Replica set by overridepolicy will be reset by ReviseReplica interpreterhook
```
=> fix override result will be ignored by ReviseReplica issue

examples/customresourceinterpreter/workload-propagationpolicy.yaml, examples/customresourceinterpreter/workload.yaml
/kind feature
These files are from #1149 and can be used locally for resource interpreter related testing without having to manually create them yourself.
Fixes #
```release-note
NONE
```
/cc @RainbowMango @XiShanYongYe-Chang
=> Add workload sample files in custom resource interpreter example

pkg/detector/detector.go, pkg/util/helper/mcs.go
/kind cleanup
Fixes #
```release-note
NONE
```
=> Fix add retry on createorupdate

.github/workflows/release-image.yml
Signed-off-by: zach593 <zach_li@outlook.com>
/kind feature
build and upload images with static tags when release published
NONE
split from https://github.com/karmada-io/karmada/pull/1358
```release-note
NONE
```
=> build and upload images when publishing

pkg/controllers/namespace/namespace_sync_controller.go
return err when err occured
[edit by @RainbowMango]
/kind cleanup
namespace controller: error should be returned for reconciling.
Fixes #
```release-note
NONE
```
=> return err replace nil

charts/templates/karmada_apiserver.yaml, charts/values.yaml
/kind cleanup
Fixes #
```release-note
```
=> Chart: make `--max-requests-inflight` and `--max-mutating-requests-inflight` configurable

pkg/detector/detector.go
/kind bug
Per https://github.com/karmada-io/karmada/pull/1368#pullrequestreview-887901933
Fixes #
```release-note
karmada-controller-manager: Fixed a bug where resource binding not created occasionally.
```
=> cherry-pick #1368: "bugfix: resource binding not created occasionally"

pkg/scheduler/core/division_algorithm.go
/kind flake
delete some invalid logic in static weight strategy and it is no impact on functions. 
https://github.com/karmada-io/karmada/blob/5833252422306f62a69d6066aab0802d10ca7354/pkg/scheduler/core/division_algorithm.go#L100-L104
Fixes #
```release-note
NONE
```
=> delete some invalid logic in static weight strategy

pkg/karmadactl/cmdinit/cert/cert_test.go, pkg/karmadactl/cmdinit/utils/util_test.go
/kind feature
Remove temp files in tests
Fixes #
```release-note
Test completes without temporary files.
```
=> feat: remove temp files in tests

pkg/util/resource.go
/kind bug
Fixes #
```release-note
NONE
```
=> fix bugs of resource computing

pkg/resourceinterpreter/customizedinterpreter/customized.go, pkg/resourceinterpreter/defaultinterpreter/default.go, pkg/resourceinterpreter/defaultinterpreter/dependencies.go, pkg/resourceinterpreter/defaultinterpreter/dependencies_util.go, pkg/resourceinterpreter/interpreter.go
/kind feature
add default dependenciesInterpreter framework
Fixes #
```release-note
NONE
```
=> add default dependenciesInterpreter framework

cmd/descheduler/app/descheduler.go, cmd/descheduler/app/options/options.go, cmd/descheduler/app/options/validation.go, cmd/descheduler/app/options/validation_test.go, cmd/descheduler/main.go, pkg/apis/work/v1alpha2/events.go, pkg/controllers/status/workstatus_controller.go, pkg/descheduler/core/filter.go, pkg/descheduler/core/helper.go, pkg/descheduler/descheduler.go, pkg/descheduler/descheduler_test.go, pkg/estimator/client/accurate.go, pkg/estimator/client/interface.go, pkg/estimator/pb/generated.proto, pkg/estimator/pb/types.go, pkg/estimator/server/server.go, pkg/util/constants.go, pkg/util/helper/policy.go, pkg/util/helper/workstatus.go, pkg/util/worker.go
/kind feature
Fixes part of #1262 
```release-note
add karmada-descheduler
```
=> add karmada-descheduler

pkg/scheduler/core/generic_scheduler.go, pkg/scheduler/framework/interface.go, pkg/scheduler/framework/runtime/framework.go
/kind feature
Fixes #
```release-note
None
```
=> feat: quick return in filter phase when unsuccessful state returned

charts/_crds/bases/policy.karmada.io_federatedresourcequotas.yaml, pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
/kind cleanup
This PR set subresource:status for FederatedResourceQuota.
Fixes #
```release-note
NONE
```
=> Set subresource for federated resource quota

pkg/util/label_test.go
improve test coverage
Fixes #
```release-note
NONE
```
=> improve test coverage

docs/multi-cluster-ingress.md
Add docs for using MultiClusterIngress API to import external traffic to services in the member clusters.
Fixes #1079 
```release-note
None
```
/cc @RainbowMango @GitHubxsy @kevin-wangzefeng
=> [docs] Using MultiClusterIngress API

docs/multi-cluster-ingress.md
Correct the syntax errors in the document: docs/multi-cluster-ingress.md.
As comments on https://github.com/karmada-io/karmada/pull/1409#pullrequestreview-895016411
```release-note
NONE
```
=> [docs] Correct the syntax errors in the mci document

docs/upgrading/README.md, docs/upgrading/v1.0-v1.1.md
Add documentation for upgrading Karmada from v1.0 to v1.1.
Fixes #
```release-note
None
```
=> Add upgrade document about v1.0-v1.1

pkg/detector/detector.go
/kind cleanup
Fetch resource from cache instead of api server when reconciling rb
Fixes #
```release-note
NONE
```
=> Fetch resource from cache instead of api server

pkg/util/binding.go, pkg/util/binding_test.go
Signed-off-by: AllenZMC <zhongming.chang@daocloud.io>
/kind cleanup
remove redundant code and improve test coverage
Fixes #
```release-note
NONE
```
=> remove redundant code and improve test coverage

artifacts/deploy/webhook-configuration.yaml, cmd/webhook/app/webhook.go, pkg/webhook/federatedresourcequota/helper/helper.go, pkg/webhook/federatedresourcequota/validating.go, pkg/webhook/federatedresourcequota/validating_util.go
/kind feature
Add validation for federatedResourceQuota creation/update.
Somebody has raised this issue #1420 
```release-note
NONE
```
=> add validation for federatedResourceQuota create/update

pkg/controllers/binding/binding_controller.go, pkg/detector/detector.go
/kind cleanup
Fixes https://github.com/karmada-io/karmada/issues/1309
```release-note
NONE
```
=> moving RB status aggregating from detector to controller

docs/installation/installation.md
Update installation.md document.
Fixes #
```release-note
NONE
```
=> [docs] Update installation.md document

charts/templates/pre-install-job.yaml
/kind bug
use server-side apply to avoid karmada crds being too big
Fixes https://github.com/karmada-io/karmada/issues/1441
```release-note
NONE
```
=> Fix karmada crds being too big

charts/Chart.yaml
/kind cleanup
Fixes #
```release-note
NONE
```
=> Fix charts appVersion

pkg/resourceinterpreter/defaultinterpreter/retain.go
/kind feature
Ensure that the user can update the service nodeport, so don't retain service nodeport.
Fixes #1445 
```release-note
`karmada-controller-manager`: Don't retain service nodeport when updating service.
```
=> Don't retain service nodeport when updating service

charts/templates/karmada_agent.yaml
/kind bug
fix rbac in karmada_agent.yaml for charts
Fixes #1396
```release-note
helm-chart: fixed can't install karmada-agent as lack of permission issue.
```
=> fix rbac in karmada_agent.yaml for charts

pkg/karmadactl/cmdinit/karmada/deploy.go, pkg/karmadactl/cmdinit/karmada/webhook_configuration.go, pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cmdinit/kubernetes/deployments.go
Signed-off-by: sayaoailun <guojianwei007@126.com>
/kind bug
PR: #1416 
Fixes #
```release-note
`karmadactl`: Fixed `--namespace` flag of `init` command not work issue.
```
=> cherry-pick #1416: `karmadactl`: Fixed `--namespace` flag of `init` command not work issue.

pkg/util/apigroup.go
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>
/kind bug
Prevented network api from propagating
Fixes #1432 
```release-note
None
```
=> Prevented network api from propagating

pkg/util/binding.go, pkg/util/binding_test.go
/kind cleanup
reduce unnecessary code operations in some cases and improve test coverage
Fixes #
```release-note
NONE
```
=> accelerate merge clusters during schedule and improve test coverage

docs/userguide/promote-legacy-workload.md
Add a document for Karmadactl promote command.
Fixes #1303
The note in the end can fix #1303.
```release-note
NONE
```
=> Add a document for Karmadactl promote command

pkg/karmadactl/cmdinit/karmada/deploy.go, pkg/karmadactl/cmdinit/kubernetes/deployments.go
Signed-off-by: sayaoailun <guojianwei007@126.com>
/kind design
Fixes #
```release-note
Replace the hard coded namespace "karmada-system" in Karmada with the custom namespace set by --namespace flag of karmadactl init command
```
=> replace hard coded namespace with custom namespace

charts/templates/karmada-aggregated-apiserver.yaml, charts/templates/karmada_agent.yaml, charts/templates/karmada_apiserver.yaml, charts/templates/karmada_controller_manager.yaml, charts/templates/karmada_scheduler.yaml, charts/templates/karmada_scheduler_estimator.yaml, charts/templates/karmada_webhook.yaml, charts/templates/kube_controller_manager.yaml, charts/values.yaml
/kind cleanup
It's better to set `maxUnavailable` to 0
Fixes #
```release-note
NONE
```
=> [helm chart] make rolling update strategy configurable

artifacts/deploy/karmada-descheduler.yaml, cmd/descheduler/app/options/options.go, pkg/descheduler/core/helper.go, pkg/descheduler/descheduler.go
/kind bug
Fix some bugs of descheduler to avoid crash.
Fixes #
```release-note
NONE
```
=> fix descheduler crash

docs/descheduler.md
add docs for descheduler
Fixes part of #1262 
```release-note
NONE
```
=> add docs for descheduler

pkg/scheduler/scheduler.go
/kind cleanup
Replace update method with patch method when updating schedule result. 
Conflict error will happen in updating schedule result due to the resource binding controller may update binding's status frequently.
Fixes #
```release-note
karmada-scheduler: replace update method with patch method when updating schedule result
```
=> replace update method with patch method when updating schedule result

test/e2e/failover_test.go, test/e2e/rescheduling_test.go, test/helper/scheduler.go
optimize the logic of the  failover e2e test case to fix random failure
Fixes #
```release-note
NONE
```
=> optimize the failover e2e test case

cmd/webhook/app/webhook.go
/kind feature
Implement flags grouping for karmada-webhook
Fixes #
```release-note
NONE
```
=> Implement flags grouping for karmada-webhook

pkg/util/lifted/resourcehelpers_test.go, pkg/util/lifted/validateresourcequota_test.go, pkg/webhook/federatedresourcequota/validating.go, pkg/webhook/federatedresourcequota/validating_test.go
/kind feature
Add UT for FederatedResourceQuota validating.
Fixes #
```release-note
NONE
```
=> [UT] Add UT for FederatedResourceQuota validating

cmd/descheduler/app/descheduler.go, cmd/descheduler/app/options/options.go
/kind feature
Implement flags grouping for karmada-descheduler  #1485 
Fixes #
```release-note
NONE
```
=> Implement flags grouping for karmada-descheduler

cmd/scheduler/app/scheduler.go
Signed-off-by: zhangyukun <38148677+jameszhangyukun@users.noreply.github.com>
/kind feature
Implement flags grouping for karmada-scheduler
Part of #1485
```release-note
```
=> Implement flags grouping for karmada-scheduler

pkg/scheduler/core/generic_scheduler.go, pkg/scheduler/framework/interface.go, pkg/scheduler/framework/plugins/apiinstalled/api_installed.go, pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go, pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go, pkg/scheduler/framework/runtime/framework.go
/kind feature
extand the ScorePlugin and add NormalizeScore interface and support the ScoreWeight
a part of #1330
```release-note
NONE
```
=> extend the score process to support the normalizeScore and scoreWeight

.github/workflows/dockerhub-latest-image.yml
/kind cleanup
This PR added a workflow to publish `latest` images to DockerHub.
Fixes #
```release-note
NONE
```
=> Publish latest image to dockerhub

cmd/agent/app/agent.go, cmd/agent/app/options/options.go, cmd/controller-manager/app/controllermanager.go, pkg/controllers/execution/execution_controller.go
/kind feature
Per https://github.com/karmada-io/karmada/pull/1489#issuecomment-1072928655
Fixes #
```release-note
`karmada-agent`: Introduced several flags to specify controller's capacities:
- --rate-limiter-base-delay
- --rate-limiter-max-delay
- --rate-limiter-qps
- --rate-limiter-bucket-size
```
=> Add ratelimiter flags for karmada-agent

test/e2e/federatedresourcequota_test.go, test/e2e/framework/federatedresourcequota.go, test/e2e/framework/resourcequota.go, test/e2e/suite_test.go, test/helper/policy.go
/kind feature
Add e2e for FederatedResourceQuota sync.
Fixes #
```release-note
NONE
```
=> [E2E] Add e2e for FederatedResourceQuota sync

artifacts/deploy/karmada-controller-manager.yaml, test/e2e/dependenciesdistributor_test.go, test/e2e/framework/configmap.go, test/e2e/framework/deployment.go, test/e2e/framework/propagationpolicy.go, test/e2e/framework/secret.go, test/e2e/suite_test.go, test/helper/resource.go
add some e2e test cases for dependencies distributor.
Fixes #
```release-note
`karmada-controller-manager`: add e2e test for dependencies distributor
```
=> add e2e test for dependencies distributor

pkg/util/helper/pod_test.go
Signed-off-by: c30013971 <cuidengdeng@huawei.com>
/kind cleanup
add a ut for pod.go
Fixes #
```release-note
NONE
```
=> add a ut for pod.go

.github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, .github/workflows/swr-latest-image.yml, .github/workflows/swr-released-image.yml
/kind cleanup
This PR tidied workflow files that will be synced to `release-1.0` and `release-1.1` for publishing images.
Fixes #
```release-note
NONE
```
=> Tidy workflow of images publishment

pkg/util/helper/node_test.go
/kind cleanup
add ut for node helper
Fixes #
```release-note
NONE
```
=> add ut for node helper

charts/OWNERS
/kind cleanup
Seems the GitHub id `@algebra2k` has been changed to `@pidb`.
Fixes #
```release-note
NONE
```
=> Update owner file as owner changed his name.

pkg/karmadactl/get.go, pkg/karmadactl/promote.go
/kind feature
When there no resources, we need to output something
```
[root@master67 karmada]# ./karmadactl get ds
No resources found in default namespace.
```
Fixes #
```release-note
NONE
```
=> Add output information when no resource is found

docs/keps/cleanup-propagated-resources.md
/kind feature
Fixes https://github.com/karmada-io/karmada/issues/438
1) Similar proposal at kubefed project, https://github.com/kubernetes-sigs/kubefed/pull/1233
2) Currently only provide cluster-scope cleanup, not provide propagated-resource-scope cleanup
```release-note
```
=> cleanup propagated resources

README.md
This PR link the proposed issue for preparing the English meeting.
Fixes #
```release-note
NONE
```
=> English meeting start to propose

cmd/scheduler-estimator/app/options/options.go, pkg/estimator/server/nodes/filter.go, pkg/estimator/server/server.go, pkg/estimator/server/server_test.go, pkg/util/lifted/parallelism.go, test/helper/resource.go
/kind feature
Optimize estimator by using a parallelizer for performance.
Fixes #
```release-note
NONE
```
=> add parallelizer and benchmark test in estimator for performance

pkg/karmadactl/cmdinit/karmada/deploy.go, pkg/karmadactl/cmdinit/karmada/rbac.go, pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cmdinit/kubernetes/deployments.go, pkg/karmadactl/cmdinit/kubernetes/rbac.go, pkg/karmadactl/cmdinit/utils/rbac.go
/kind feature
karmadactl init: add cluster proxy rbac for admin when deploy Karmada  control plane
Part of #1546 
```release-note
NONE
```
=> karmadactl init: add cluster proxy rbac for admin when deploy Karmada  control plane

docs/userguide/configure-controllers.md
Add documents about Kubernetes `namespace` controller.
Fixes #
```release-note
NONE
```
/assign @Tingtal
=> Add document about namespace controller

Makefile
/kind cleanup
Cleanup unused parameters in Makefile:
```
REGISTRY_REGION
ACCESS_KEY
REGISTRY_LOGIN_KEY
SWR_SERVICE_ADDRESS
```
Fixes #
```release-note
NONE
```
=> Cleanup unused parameters in Makefile

docs/frequently-asked-questions.md
This PR added a FAQ about why Karmada requires `kube-controller-manager`.
Fixes #
```release-note
NONE
```
=> Add FAQ about why we need kube-controller-manager

examples/customresourceinterpreter/webhook/app/webhook.go
/kind feature
This was missing before, let me to add it. 
Implement flags grouping for customresourceinterpreter.
Fixes #
```release-note
NONE
```
=> Implement flags grouping for customresourceinterpreter

docs/userguide/configure-controllers.md
Add documents about why we need `garbagecollector` controller
Fixes #
```release-note
NONE
```
=> Add documents about why we need garbagecollector controller

pkg/resourceinterpreter/customizedinterpreter/customized.go, pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
/kind bug
when bugfix response's patch and patchType is nil, controller panic
Fixes https://github.com/karmada-io/karmada/issues/1578
```
NONE
```
=> fix: bugfix response's patch and patchType is nil, controller panic

pkg/detector/detector.go
/kind bug
Do not propagate service account token because it should be created by the member cluster.
Fixes #
```release-note
NONE
```
=> ignore to propagate service account token

Makefile
/kind bug
The env variable $(REGISTRY) is not passed to the script through the makefile
```release-note
NONE
```
=> fix makefile error

pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go, pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
/kind feature
add UT for aggregatestatus
None
=> add UT for aggregatestatus

charts/templates/_karmada_cluster_proxy_admin_rbac.tpl, charts/templates/post-install-job.yaml, charts/templates/pre-install-job.yaml
/kind bug
remove cluster-proxy-rbac from karmada-host cluster to karmada-apiserver
Fixes #1594
=> helm: remove cluster-proxy-rbac from karmada-host cluster to karmada-apiserver

pkg/util/condition_test.go
/kind cleanup
add ut for condition
Fixes #
```release-note
NONE
```
=> add ut for condition

cmd/scheduler/app/scheduler.go, pkg/scheduler/core/generic_scheduler.go, pkg/scheduler/framework/plugins/apiinstalled/api_installed.go, pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go, pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go, pkg/scheduler/framework/plugins/registry.go, pkg/scheduler/framework/plugins/spreadconstraint/spreadconstraint.go, pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go, pkg/scheduler/framework/runtime/framework.go, pkg/scheduler/framework/runtime/registry.go, pkg/scheduler/scheduler.go
/kind feature
Part of  https://github.com/karmada-io/karmada/issues/1371
```release-note
None
```
=> feat: introduce registry to initialize framework

pkg/scheduler/scheduler.go
Fixes #
```release-note
None
```
=> refactor: remove commented codes

hack/undeploy-karmada.sh
Signed-off-by: duanmeng <duanmeng@cmss.chinamobile.com>
/kind bug
add some prompt message in undeploy-karmada.sh
Fixes #1042
```release-note
NONE
```
=> add some prompt message in undeploy-karmada.sh

charts/README.md, charts/templates/_helpers.tpl, charts/templates/karmada_descheduler.yaml, charts/values.yaml
/kind feature
add karmada_descheduler for helm
Fixes #1262  helm: support helm install
/cc @Garrybest 
None
=> add karmada_descheduler for helm

pkg/util/validation/validation_test.go
/kind cleanup
improve test coverage for validation
Fixes #
```release-note
NONE
```
=> improve test coverage for validation

cmd/controller-manager/app/controllermanager.go, pkg/util/membercluster_client.go
Do nil check before using cluster secretRef
Fixes #1621 
None
```release-note
```
=> check if cluster secretRef is nil before using it

pkg/resourceinterpreter/defaultinterpreter/revisereplica_test.go
/kind cleanup
add ut for revisereplica
Fixes #
```release-note
NONE
```
=> add ut for revisereplica

pkg/descheduler/core/filter_test.go
/kind cleanup
add ut for filter
Fixes #
```release-note
NONE
```
=> add ut for filter

pkg/util/lifted/doc.go
As #1620 lifted a new file, update the lifted doc.
Fixes #
```release-note
NONE
```
=> update lifted doc

pkg/util/interpreter/rules_test.go
/kind cleanup
add ut for rules
Fixes #
```release-note
NONE
```
=> add ut for rules

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go
/kind cleanup
Fixes #
```release-note
```
=> skip reconciling loop quickly after workload gone

docs/proposals/caching/README.md
/kind feature
Caching member cluster resources for Karmada
Fixes #1245 
```release-note
NONE
```
=> [proposal] Caching member cluster resources for Karmada

pkg/apis/work/v1alpha2/binding_types_helper.go, pkg/apis/work/v1alpha2/binding_types_helper_test.go, pkg/scheduler/core/spreadconstraint/group_clusters.go, pkg/scheduler/core/spreadconstraint/group_clusters_test.go
/kind cleanup
Introduce `AssignedReplicasForCluster()` method to `ResourceBinding`/`ClusterResourceBinding`.
Fixes #
```release-note
NONE
```
=> Introduce AssignedReplicasForCluster for ResourceBinding

docs/frequently-asked-questions.md
Signed-off-by: Wang Bing <wangbing.adam@gmail.com>
add faq "install Karmada in a existing kubernetes cluster"
Fixes #
```release-note
NONE
```
=> docs: add FAQ about reuse kube-apiserver

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go
/kind cleanup
Add comments after #1636.
Fixes #
```release-note
NONE
```
=> Add comments about why resource template not exist

.github/workflows/fossa.yml
/kind cleanup
This PR updated the fossa API key and moved to secret. 
Fixes #
```release-note
NONE
```
=> Disable fossa on forked repository

pkg/util/lifted/doc.go, pkg/util/lifted/logs.go, pkg/util/lifted/logs_test.go
/kind cleanup
Fixes #
```release-note
NONE
```
/cc @XiShanYongYe-Chang
=> Add lifted information for logs.go

.github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml, Makefile
/kind bug
According to #1645, karmada run failed on arm docker. These PR will build images with multiple arch, both amd64 and arm64.
Fixes #1645
```release-note
Fixed image does not support for Arm platform issue.
```
=> Support multiple arch: amd64, arm64.

pkg/karmadactl/get.go
/kind feature
Add watch function for karmadactl get
Fixes #
```release-note
`karmadactl/kubectl-karmada`: Added `watch` function to `get` command.
```
=> Add watch function for karmadactl get

cmd/scheduler/app/scheduler.go, pkg/scheduler/scheduler.go, pkg/scheduler/scheduler_test.go
/kind feature
1. Currently  when we instantce `NewScheduler`, we passed in a named `Options` struct which contains too much useless fields, this PR made the parameters passed in when needed.  It's also easy to mock scheduler.
2. Add scheduler unit tests.
Fixes #
```release-note
None
```
=> introduce schedulerOptions to optimize scheduler instantiation

pkg/scheduler/core/spreadconstraint/group_clusters.go, pkg/scheduler/core/spreadconstraint/select_clusters.go, pkg/scheduler/core/spreadconstraint/select_clusters_by_cluster.go, pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go, pkg/scheduler/core/spreadconstraint/select_clusters_by_region_test.go, pkg/scheduler/core/spreadconstraint/util.go
/kind feature
support region spread constraint
a part of https://github.com/karmada-io/karmada/issues/1330
```release-note
`karmada-scheduler`: support spread constraint by region strategy.
```
=> support region spread constraint

docs/working-with-anp.md
unify variables for replace-proxy-agent.sh in the document
Fixes #
```release-note
NONE
```
=> uniform variables for scripts in document

pkg/util/helper/workstatus.go
/kind cleanup
Sort the `aggregatedStatus` field in `resourceBinding/clusterResourceBinding` by the `clusterName`.
Fixes #
```release-note
NONE
```
=> Sort the aggregatedStatus in rb/crb by the clusterName

test/e2e/resource_test.go
/kind cleanup
Add e2e for service status collection.
Part of #1593 
```release-note
NONE
```
=> [E2E] add e2e for serviceStatus collection

charts/templates/_helpers.tpl, charts/templates/etcd.yaml, charts/templates/karmada-aggregated-apiserver.yaml, charts/templates/karmada_apiserver.yaml
just adjust the format in charts
/kind cleanup
=> adjust the format in charts

Makefile, cluster/images/karmada-agent/Dockerfile, cluster/images/karmada-aggregated-apiserver/Dockerfile, cluster/images/karmada-controller-manager/Dockerfile, cluster/images/karmada-descheduler/Dockerfile, cluster/images/karmada-interpreter-webhook-example/Dockerfile, cluster/images/karmada-scheduler-estimator/Dockerfile, cluster/images/karmada-scheduler/Dockerfile, cluster/images/karmada-webhook/Dockerfile, hack/docker.sh, hack/util.sh, hack/version.sh
/kind feature
use [multistage](https://docs.docker.com/develop/develop-images/multistage-build/) to build docker images
Fixes #745
```release-note
```
=> refactor Dockerfile using multi-stage docker build

pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
/kind cleanup
add ut for dependencies
Fixes #
```release-note
NONE
```
=> add ut for dependencies

docs/working-with-gatekeeper.md
/kind feature
Add docs for users to run gatekeeper in karmada-controller-plane and use a demo polity. Later, we need to provide some karmada-owned policy to extend karmada ability.
Fixes #1614 
None
=> [Docs]Add karmada-gatekeeper-guide for users

Makefile, cluster/images/karmada-agent/Dockerfile, cluster/images/karmada-aggregated-apiserver/Dockerfile, cluster/images/karmada-controller-manager/Dockerfile, cluster/images/karmada-interpreter-webhook-example/Dockerfile, cluster/images/karmada-scheduler-estimator/Dockerfile, cluster/images/karmada-scheduler/Dockerfile, cluster/images/karmada-webhook/Dockerfile, hack/docker.sh, hack/util.sh, hack/version.sh
Cherry pick of #927 on release-1.1.
#927: refactor Dockerfile using multi-stage docker build
```release-note
None(infrastructure update)
```
=> Automated cherry pick of #927: refactor Dockerfile using multi-stage docker build

pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go, pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go, pkg/resourceinterpreter/defaultinterpreter/reflectstatus.go, pkg/util/helper/unstructured.go, test/e2e/framework/ingress.go, test/e2e/resource_test.go, test/e2e/suite_test.go, test/helper/resource.go
/kind cleanup
Add e2e for ingress status collection.
Part of #1593 
Upgrade Ingress from `extensions/v1beta1` to `networking.k8s.io/v1`.
```release-note
NONE
```
=> [E2E] add e2e for ingressStatus collection

docs/proposals/caching/README.md, pkg/resourceinterpreter/customizedinterpreter/configmanager/accessor.go
/kind cleanup
Correct the function name error in the comment
Fixes #
```release-note
NONE
```
=> Correct the function name error in the comment

docs/working-with-gatekeeper.md
/kind cleanup
Fix spelling mistakes
=> fix wehbhook error

hack/undeploy-karmada.sh
/kind cleanup
Fixes #
```release-note
NONE
```
=> Clear global resources while undeploy cluster

docs/override-policy.md
Add overridepolicy guide for users. Deprecate OverrideSpec.Overriders and use OverrideSpec.OverrideRules instead.
Fixes #1251 
None
=> [Docs]Add overridepolicy guide for users

test/e2e/aggregatedapi_test.go, test/e2e/porting_workloads_test.go, test/e2e/suite_test.go
/kind bug
Fixes #1724
```release-note
NONE
```
=> Add namespace propagated waiting check in the SynchronizedBeforeSuite

docs/userguide/propagate-dependencies.md
Add Propagate Dependencies user guide
Fixes #
```release-note
NONE
```
=> [Docs]: Add Propagate Dependencies user guide

.github/workflows/ci.yml, cluster/images/karmada-agent/Dockerfile, cluster/images/karmada-aggregated-apiserver/Dockerfile, cluster/images/karmada-controller-manager/Dockerfile, cluster/images/karmada-descheduler/Dockerfile, cluster/images/karmada-interpreter-webhook-example/Dockerfile, cluster/images/karmada-scheduler-estimator/Dockerfile, cluster/images/karmada-scheduler/Dockerfile, cluster/images/karmada-webhook/Dockerfile, hack/docker.sh
Use build defined in makefile instead of go build process on docker build stage 
Fixes #
```NONE
```
=> code optimization : use make build instead of go build on docker multi-stage build

hack/local-up-karmada.sh
/kind cleanup
Add mainland China time zone judgment to automatically confirm whether to use a proxy.
Is this better for Chinese users?
=> Add time zone interpretation for local-up-karmada.sh

hack/update-codegen.sh, hack/util.sh
/kind bug
Fix file will not updated after run `hack/update-codegen.sh`
Fixes #1730
```release-note
NONE
```
=> codegen will update in repository

docs/working-with-gatekeeper.md, docs/working-with-kyverno.md
/kind feature
Add karmada-kyverno-guide for users to manager OPA Policy in karmada. It seems that kyverno is more suitable for use in multi-cluster environments.
Fixes #1614 
=> [Docs]Add karmada-kyverno-guide for users

pkg/controllers/status/workstatus_controller.go
Signed-off-by: lv <yanru.lv@daocloud.io>
/kind feature
Fixes #
```release-note
```
=> [fix] delete work status 'Resource' field

hack/local-up-karmada.sh
/kind feature
revert time zone interpretation for local-up-karmada.sh
Fixes #1755
```release-note
NONE
```
=> revert time zone interpretation for local-up-karmada.sh

test/e2e/framework/daemonSet.go, test/e2e/framework/statefulSet.go, test/e2e/resource_test.go, test/e2e/suite_test.go, test/helper/resource.go
/kind cleanup
add e2e for jobStatus,daemonSetStatus,statefulSetStatus collection
part of #1593 
/cc @XiShanYongYe-Chang 
None
=> [e2e]add e2e for jobStatus,daemonSetStatus,statefulSetStatus collection

README.md
Signed-off-by: Mike Ng <ming@redhat.com>
Minor spelling and grammar fixes to the README of the repo.
Fixes # NA
```release-note
NONE
```
=> fix: update README to fix minor spelling and grammar mistakes.

pkg/karmadactl/cmdinit/cmdinit.go, pkg/karmadactl/cordon.go, pkg/karmadactl/get.go, pkg/karmadactl/join.go, pkg/karmadactl/logs.go, pkg/karmadactl/promote.go, pkg/karmadactl/taint.go, pkg/karmadactl/unjoin.go
/kind cleanup
Unify usage example template of karmadactl to avoid multiple formats. 
Fixes #
```release-note
NONE
```
=> Unify usage example template of karmadactl

.github/workflows/dockerhub-latest-image.yml, .github/workflows/dockerhub-released-image.yml
/kind bug
Fix https://github.com/karmada-io/karmada/pull/1740#issuecomment-1123293459
Fixes #
```release-note
NONE
```
=> fix docker hub push failed

hack/docker.sh
/kind bug
Fix https://github.com/karmada-io/karmada/pull/1740#issuecomment-1123382503
Fixes #
```release-note
None
```
=> fix readonly variable error in `docker.sh`

pkg/karmadactl/promote.go
/kind flake
modify variable format
Fixes #
```release-note
NONE
```
=> modify variable format using hump

pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
/kind bug
-->
Fixes #1767
Fixes #1767
```release-note
NONE
```
=> Fix occasionally TestAggregateJobStatus time error

hack/deploy-scheduler-estimator.sh
/kind bug
use member-cluster-context correctly
Fixes #1772 
```release-note
NONE
```
=> use member-cluster-context correctly

hack/build.sh, hack/util.sh
/kind bug
Compatible with mac os
Fixes #1779 
```release-note
NONE
```
=> compatible with mac os

pkg/karmadactl/cmdinit/cmdinit.go
/kind bug
/kind cleanup
wrong command example 
```release-note
NONE
```
=> fix karmadactl init examples

hack/deploy-karmada-agent.sh
/kind bug
Fixes #1769 
@RainbowMango @ikaven1024 
```release-note
NONE
```
=> fix 1769 karmada-agent build twice when execute local-up-karmada.sh

docs/installation/installation.md
update crd version in docs/installation/installation.md
/kind cleanup
=> update crd version

pkg/resourceinterpreter/interpreter.go
fix log format
```release-note
NONE
```
=> log format

pkg/karmadactl/logs.go
/kind cleanup
Modify karmadactl logs example.
Fixes #
```release-note
NONE
```
=> Modify karmadactl logs example

go.mod, pkg/karmadactl/describe.go, pkg/karmadactl/exec.go, pkg/karmadactl/karmadactl.go, pkg/karmadactl/logs.go
/kind feature
Add `exec` and `describe` function to `karmadactl`.
Fixes #1568 
```release-note
`karmadactl`: Added `exec` and `describe` sub-commands.
```
=> Add exec and describe function to karmadactl

charts/values.yaml
/kind cleanup
Add some comments for value.yaml
=> add comment for value.yaml

test/e2e/resource_test.go
add service e2e
/kind cleanup
```release-note
NONE
```
=> add e2e for nodePort service status collection

Makefile
/kind bug
Fixes #
```release-note
NONE
```
=> Correct prompt in makefile

docs/multi-cluster-ingress.md
=> fix syntax error

pkg/util/informermanager/keys/keys.go, pkg/util/informermanager/single-cluster-manager.go
/kind cleanup
Clear confusing comments
Fixes #
```release-note
NONE
```
=> Clear confusing comments

ROADMAP.md
/kind cleanup
This PR updated the draft roadmap for the year 2022.
Fixes #
```release-note
NONE
```
=> Update ROADMAP for 2022

README.md
Collect the talks for people to get to know Karmada easier.
Fixes #
People asking for talks [on slack](https://cloud-native.slack.com/archives/C02MUF8QXUN/p1652298556933279). 
```release-note
NONE
```
=> setup talks and references

cmd/agent/app/agent.go, cmd/aggregated-apiserver/app/aggregated-apiserver.go, cmd/controller-manager/app/controllermanager.go, cmd/descheduler/app/descheduler.go, cmd/karmada-search/app/karmada-search.go, cmd/karmadactl/karmadactl.go, cmd/kubectl-karmada/kubectl-karmada.go, cmd/scheduler-estimator/app/scheduler-estimator.go, cmd/scheduler/app/scheduler.go, cmd/webhook/app/webhook.go, examples/customresourceinterpreter/webhook/app/webhook.go, pkg/karmadactl/cmdinit/cmdinit.go, pkg/karmadactl/cmdinit/kubernetes/deploy.go, pkg/karmadactl/cordon.go, pkg/karmadactl/deinit.go, pkg/karmadactl/describe.go, pkg/karmadactl/exec.go, pkg/karmadactl/get.go, pkg/karmadactl/join.go, pkg/karmadactl/karmadactl.go, pkg/karmadactl/logs.go, pkg/karmadactl/promote.go, pkg/karmadactl/taint.go, pkg/karmadactl/unjoin.go, pkg/version/sharedcommand/sharedcommand.go, test/e2e/federatedresourcequota_test.go, test/e2e/karmadactl_test.go, test/e2e/namespace_test.go, test/e2e/rescheduling_test.go
/kind cleanup
Discard unused param in cmd functions
Fixes #
```release-note
NONE
```
=> Discard unused param in cmd functions

artifacts/deploy/karmada-aggregated-apiserver.yaml, charts/templates/karmada-aggregated-apiserver.yaml, docs/upgrading/v0.10-v1.0.md, pkg/karmadactl/cmdinit/kubernetes/deployments.go
Signed-off-by: anu491 <anutosh.bhat.21.linux@gmail.com>
kind deprecation
Removed Deprecated flag
Fixes #1807 
```
NONE
```
=> Removed Deprecated karmada-config flag

artifacts/deploy/karmada-aggregated-apiserver.yaml, charts/templates/karmada-aggregated-apiserver.yaml, pkg/karmadactl/cmdinit/kubernetes/deployments.go
/kind bug
add readiness for aa
Fixes #1836
```release-note
NONE
```
=> add readiness for aa

pkg/webhook/configuration/validating.go
/kind feature
Add `InterpretStatus` for supportedInterpreterOperation.
Fixes #
```release-note
NONE
```
=> Add InterpretStatus for supportedInterpreterOperation

docs/OWNERS
/kind cleanup
Put @Tingtal on the owner list.
@Tingtal is a professional English translator and has been making contributions to this project.
Fixes #
```release-note
NONE
```
=> Put Tingtal on owner list

pkg/karmadactl/deinit.go
/kind cleanup
Optimize deinit according former comments at #1337 
Fixes #
I have tested it in my enviroment and it works fine.
/cc @RainbowMango @prodanlabs 
```release-note
NONE
```
=> Optimize deinit according former comments

docs/upgrading/README.md, docs/upgrading/v1.1-v1.2.md
Added the upgrade guide for upgrading from v1.1 to v1.2.
Fixes #
```release-note
NONE
```
=> [doc] upgrade from v1.1 to v1.2

docs/installation/installation.md
Added the installation guide for the development environment to installation documents.
Fixes #
```release-note
NONE
```
=> Add install development environment to installation docs

api/openapi-spec/swagger.json, hack/tools/swagger/generateswagger.go, pkg/util/gclient/gclient.go
/kind feature
Part of #1794 
We could need to add it in upcoming release.
```release-note
NONE
```
=> Add karmada-search API swagger documents

Makefile, hack/release-helm-chart.sh, hack/util.sh
/kind cleanup
Add package helm chart scripts
use `make release-chart`, then:
Fixes #
NONE
=> Add package helm chart scripts

artifacts/deploy/karmada-scheduler.yaml, charts/templates/karmada_scheduler.yaml, pkg/karmadactl/cmdinit/kubernetes/deployments.go
/kind bug
And livenesProbe for karmada-scheduler
=> Add livenes for karmada-scheduler

pkg/karmadactl/describe.go, pkg/karmadactl/exec.go, pkg/karmadactl/get.go
/kind cleanup
delete unused parameter
Fixes #
```release-note
NONE
```
=> delete unused parameter

artifacts/deploy/karmada-descheduler.yaml, charts/templates/karmada_descheduler.yaml
/kind bug
/kind cleanup
add livenessProbe for descheduler
Fixes #
```release-note
NONE
```
=> add livenessProbe for descheduler

artifacts/deploy/karmada-scheduler-estimator.yaml, charts/templates/karmada_scheduler_estimator.yaml
/kind bug
/kind cleanup
add livenessProbe for scheduler-estimator
Fixes #
```release-note
NONE
```
=> add livenessProbe for scheduler-estimator

docs/working-with-flux.md
Improve docs with flux
Fixes #
NONE
=> Improve flux docs

artifacts/deploy/kube-controller-manager.yaml, charts/templates/kube_controller_manager.yaml
/kind bug
/kind cleanup
add livenessProbe for karmada-kube-controller-manager
Fixes #
```release-note
NONE
```
=> add livenessProbe for karmada-kube-controller-manager

docs/installation/install-kubectl-karmada.md
/kind cleanup
Make documentation descriptions clearer and make it easier for users to find the `kubectl-karmada` executable file
Fixes #
```release-note
NONE
```
=> Make documentation descriptions clearer 

artifacts/deploy/karmada-etcd.yaml, charts/templates/etcd.yaml
/kind bug
The etcd port seems  wrong.
=> adjust etcd port

docs/CHANGELOG/CHANGELOG-1.2.md
add changelog for v1.2
Fixes #
```release-note
```
=> add changelog for v1.2

docs/userguide/customizing-resource-interpreter.md
update `customizing-resource-interpreter.md` to describe with current state.
Fixes #
```release-note
NONE
```
=> [doc] update customizing-resource-interpreter.md

charts/README.md
/kind cleanup
Remove useless prefixes in console, making it easier for users to copy on the ui
Fixes #
```release-note
NONE
```
=> Remove useless prefixes in console for README.md

pkg/registry/search/storage/requestinfo_test.go
Signed-off-by: charlesQQ <charles_ali@qq.com>
Fixes  https://github.com/karmada-io/karmada/issues/1918
```
None
```
=> feat: add unit test for requestinfo

pkg/controllers/status/cluster_status_controller.go
/kind feature
Fixes #
```release-note
`karmada-controller-manager/karmada-agent`: cluster status controller now able to collect partial API list in case of discovery failure.
```
=> fix the incorrect use of ServerGroupsAndResources() in client-go

samples/guestbook/README.md, samples/guestbook/guestbook.yaml, samples/guestbook/guestbooks-clusterpropagationolicy.yaml, samples/guestbook/guestbooks-crd.yaml, samples/guestbook/guestbooks-overridepolicy.yaml, samples/guestbook/guestbooks-propagationpolicy.yaml
/kind cleanup
Better tell users how to use CRD in karmada
Fixes #
```release-note
NONE
```
=> Add a CRD sample

artifacts/example/resourceregistry.yaml
/kind cleanup
This PR added an example yaml of the `ResourceRegistry` which will be used to demonstrate what the API looks like and might be used for development.
Fixes #
```release-note
NONE
```
cc @liys87x
=> Add example yaml of ResourceRegistry

charts/templates/karmada-apiserver.yaml
Signed-off-by: mathlsj <mathlsj@outlook.com>
Fixes #
```release-note
```
=> disable StorageObjectInUseProtection admission plugin in charts

charts/README.md, docs/upgrading/README.md, docs/working-with-flux.md, docs/working-with-kyverno.md, hack/release-helm-chart.sh
/kind cleanup
1. Based on #1984, we will add a CI workflow for helm chart. And first we will modify helm chart dir. Meanwhile we need update docs.
2. Improve Flux docs which will be posted in Flux community.
Fixes # 
None
=> Improve docs about helm chart

docs/proposals/caching/README.md
/kind feature
Update the proposal based on the changes made on #1674 
Part of  #1794 
```release-note
NONE
```
=> update search proposal

pkg/karmadactl/cmdinit/kubernetes/statefulset.go
/kind bug
Keep ETCD storage paths consistent in different installation modes
Fixes #2001
```release-note
no
```
=> fix etcd-default-path

docs/scheduler-estimator.md
/kind cleanup
Improve scheduler-estimator.md
=>  Improve scheduler-estimator

docs/working-with-velero.md
update karmada working with velero docs
Fixes #
```release-note
```
=> update karamda working with velero md

docs/proposals/hpa/federated-hpa.md
=> fix typo mistake

artifacts/opensearch/karmada-opensearch-dashboards.yaml, artifacts/opensearch/karmada-opensearch.yaml, hack/deploy-karmada-opensearch.sh, hack/util.sh
/kind feature
Part of #1794
```release-note
add opensearch script for a developing purpose
```
=> add opensearch script for a developing purpose

docs/working-with-anp.md
=> Improve working-with-anp

docs/working-with-gatekeeper.md
/kind cleanup
Modify the docs for a little readability
Fixes #
```release-note
NONE
```
=> Improve working-with-gatekeeper.md

docs/userguide/aggregated-api-endpoint.md
Improve aggregated-api-endpoint
/kind cleanup
=> Improve aggregated-api-endpoint

docs/working-with-prometheus.md
Improve/docs-prometheus
/kind cleanup
=> improve docs-prometheus

docs/working-with-submariner.md
/kind cleanup
Fixes #
```release-note
NONE
```
=> Improve working-with-submariner

docs/working-with-kyverno.md
/kind cleanup
Improve working-with-kyverno.md
Fixes #
```release-note
NONE
```
=> Improve working-with-kyverno

.golangci.yml
/kind cleanup
Fixes #2009
```release-note
NONE
```
=> Enlarge timeout setting of golangci-lint

pkg/karmadactl/karmadactl.go
=> The package imports can be improved

cmd/OWNERS, pkg/karmadactl/OWNERS
/kind cleanup
@lonelyCZ made a great contribution to components framework and karmadactl in recently releases.
I'd like to sponsor him as the owner.
Fixes #
```release-note
NONE
```
=> Put lonelyCZ to owner files

pkg/karmadactl/cmdinit/OWNERS
/kind cleanup
As the `init` command author, @prodanlabs also helped maintain this feature in the latest releases. 
In order to not block his work, I'd like to sponsor him as the approver.
Fixes #
```release-note
NONE
```
=> Add prodanlabs to approver list

charts/OWNERS
/kind cleanup
@Poor12 made great contributions to the `Helm chart` feature in recent releases.
I'd like to sponsor him as a reviewer of chart.
Fixes #
```release-note
NONE
```
/assign @Poor12 
/assign @pidb
=> Put Poor12 to chart owner list

pkg/karmadactl/cmdinit/kubernetes/deployments.go
/kind cleanup
It is only the optimization of the format to ensure the consistency of the whole text.
Fixes # `NONE`
`NONE`
Does this PR introduce a user-facing change?:`NO`
=> improve deployments.go

pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
/kind cleanup
```release-note
NONE
```
=> improve webhook_configuration.go

pkg/printers/internalversion/printers_test.go, pkg/printers/tablegenerator.go, pkg/printers/tablegenerator_test.go
/kind feature
Update pkg/printers with Kubernetes v1.24.2
Fixes #2051
```release-note
NONE
```
=> Update pkg/printers with Kubernetes v1.24.2

artifacts/agent/karmada-agent.yaml, charts/karmada/templates/karmada-agent.yaml, cmd/agent/app/agent.go, cmd/agent/app/options/options.go, cmd/agent/app/options/validation.go, cmd/agent/app/options/validation_test.go, pkg/karmadactl/cmdinit/utils/examples.go
/kind cleanup
Add health probe for Karmada-agent
Fixes #
None
=> Add health probe for Karmada-agent

artifacts/deploy/karmada-search.yaml, charts/karmada/templates/karmada-search.yaml, cmd/karmada-search/app/options/options.go, cmd/karmada-search/app/options/validation.go
/kind feature
/kind cleanup
add health probe for karmada-search
Fixes #
```release-note
NONE
```
=> add health probe for karmada-search

docs/userguide/customizing-resource-interpreter.md, pkg/resourceinterpreter/defaultinterpreter/dependencies.go, pkg/util/constants.go, pkg/util/helper/unstructured.go
/kind feature
Add a CronJob to the default dependencinterpreter
Fixes #
```release-note
Add a CronJob to the default dependencinterpreter
```
=> Add a CronJob to the default dependencinterpreter

charts/karmada/README.md
/kind cleanup
I'm sorry, I forgot to modify the readme content in the last PR.  https://github.com/karmada-io/karmada/pull/1959
Fixes #
```release-note
NONE
```
=> update chart readme

pkg/util/secret.go, pkg/util/serviceaccount.go
/kind bug
support  join 1.24 k8s  
Fixes #1961
```release-note
NONE
```
=> bugfix: support  join 1.24 k8s: auto create secret when sa not create

charts/index.yaml, charts/karmada/README.md
/kind cleanup
Add helm repo index to helm install karmada without downloading karmada source code.
Fixes #1783 
NONE
=> Add helm repo index

pkg/search/controller.go
/kind bug
If  spec of resourceRegistry has not changed, we should not to registry reource informer  once again.  in the case, short circuit resourceRegistry update event.
Fixes #
```release-note
NONE
```
=> karmada-search: short circuit event hander for resourceRegistry updation

pkg/karmadactl/cordon.go, test/e2e/karmadactl_test.go
/kind cleanup
Add karmadactl cordon/uncordon test in e2e
Fixes #1831 
```release-note
NONE
```
=> [E2E] add karmadactl cordon/uncordon e2e test

.github/workflows/lint-chart.yaml, hack/local-up-karmada.sh
/kind cleanup
Upgrade kind version from v0.12.0 to v0.14.0.
Fixes #2088 
```release-note
NONE
```
=> upgrade kind version to v0.14.0

pkg/controllers/hpa/hpa_controller.go, pkg/controllers/mcs/service_export_controller.go
/kind cleanup
All NewAggregate function  are from utilerrors
Fixes #
```release-note
NONE
```
=> fix import error

.golangci.yml, pkg/karmadactl/cmdinit/kubernetes/deployments.go, pkg/search/controller.go
/kind cleanup
For prevent words misspell and imports do not format into three parts correctly
Fixes #
```release-note
NONE
```
=> Add misspell in golangci

docs/working-with-anp.md
Signed-off-by: windsonsea <haifeng.yao@daocloud.io>
Remove some minor errors about grammar
Fix text errors
CC @Arhell @rgrupesh , thanks.
NONE
=> [doc] Improve docs/working-with-anp.md

hack/deploy-scheduler-estimator.sh
/kind cleanup
Fixes #
```release-note
```
=> fix comments error in hack

hack/OWNERS
/kind cleanup
@ikaven1024 contributed a lot in recent releases, such as helping to build the release artifacts and review relevant PRs.
Fixes #
```release-note
NONE
```
=> Put ikaven1024 onto the hack owner list

.golangci.yml, pkg/karmadactl/cmdinit/kubernetes/rbac.go
/kind cleanup
Add gci to seperate goimports to three parts
Fixes #
```release-note
NONE
```
=> Add gci to seperate goimports to three parts

pkg/util/helper/binding.go, pkg/util/helper/work.go, pkg/util/helper/workstatus.go
/kind bug
fix binding reference key hash collision
Fixes #2071 
```release-note
NONE
```
=> fix binding reference key hash collision

test/e2e/resourceinterpreter_test.go
/kind cleanup
Support pull mode cluster for Retain testing.
Fixes #
```release-note
NONE
```
=> [E2E] support pull mode cluster for Retain testing

pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
/kind bug
Fix nil pointer and err formatting problems in updateConfiguration
Fixes #
```release-note
Fix nil pointer and err formatting problems in updateConfiguration
```
=> Fix nil pointer and err formatting problems in updateConfiguration

pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go, pkg/util/helper/unstructured.go
/kind bug
`karmada-controller-manager`/`karmada-agent` : fixed panic issue when dumps error infos.
Fixes #
```release-note
`karmada-controller-manager`/`karmada-agent` : fixed panic issue when dumps error infos.
```
=> `karmada-controller-manager`/`karmada-agent` : fixed panic issue when dumps error infos.

README.md
Update kubernetes compatibility in README.md
Fixes #
```release-note
NONE
```
=> Update kubernetes compatibility in README.md

samples/guestbook/README.md, samples/guestbook/guestbooks-clusterpropagationpolicy.yaml
Signed-off-by: wei.wei6 <wei.wei6@neolink.com>
Better tell users how to use CRD in karmada
Fixes #
```release-note
NONE
```
=> fix document format and spelling errors for guestbooks example

hack/util.sh
Fixed dockerfile line feed problem
Add one of the following kinds:
/kind bug
Fixes #https://github.com/karmada-io/karmada/issues/2114
```release-note
```
=> Fixed dockerfile line feed problem

pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go, pkg/controllers/hpa/hpa_controller.go, pkg/controllers/mcs/service_export_controller.go, pkg/dependenciesdistributor/dependencies_distributor.go, pkg/detector/detector.go, pkg/util/helper/binding.go, pkg/util/helper/mcs.go
/kind cleanup
tidy federated resource quota code.
Fixes #
please correct me if not
```release-note
NONE
```
=> cleanup federated resource quota

docs/contributors/devel/profiling-karmada.md
add pprof doc for Karmada.
Fixes #
None
=> Add pprof doc for Karmada

pkg/karmadactl/get.go
/kind feature
```sh
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) kubectl config get-contexts
CURRENT   NAME        CLUSTER     AUTHINFO    NAMESPACE
dce         dce         dce
dsp-dce     dsp-dce     dsp-dce
ik8s01      ik8s01      ik8s01      insight-system
*         karmada     karmada     karmada     demo
kind-kind   kind-kind   kind-kind
ocp         ocp         ocp
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) karmadactl get po -C ocp -n demo
NAME                              CLUSTER   READY   STATUS             RESTARTS   AGE
micro-dao-2048-74d69cb547-fhxzr   ocp       0/1     CrashLoopBackOff   1982       7d
micro-dao-2048-74d69cb547-vjqtr   ocp       0/1     CrashLoopBackOff   1966       7d
(⎈ …
```
=> allow to read namespace from the context field of karmada config when use the karmadactl get command

pkg/resourceinterpreter/customizedinterpreter/customized.go
/kind bug
Fixes https://github.com/karmada-io/karmada/issues/1703
```
`karmada-controller-manager`: Fixed return err in case of interpreter webhook returns nil patch and nil patchType.
```
=> fix: fix applyPatch when patch and patchType is nil

docs/proposals/clusterid/README.md
/kind feature
Add proposal of adoption of ClusterID.
Fixes #
```release-note
NONE
```
=> [Proposal] Adoption of ClusterID

pkg/karmadactl/exec.go
/feature
Fixes it is not to check `--cluster` in latest improvement.
Fixes #
/cc @RainbowMango @carlory 
```release-note
NONE
```
=> karmadactl exec: check if --cluster specify

pkg/karmadactl/logs.go, vendor/k8s.io/kubectl/pkg/cmd/logs/logs.go, vendor/k8s.io/kubectl/pkg/util/apply.go, vendor/k8s.io/kubectl/pkg/util/pod_port.go, vendor/k8s.io/kubectl/pkg/util/service_port.go, vendor/k8s.io/kubectl/pkg/util/umask.go, vendor/k8s.io/kubectl/pkg/util/umask_windows.go, vendor/k8s.io/kubectl/pkg/util/util.go, vendor/modules.txt
/kind feature
use kubectl logs to implement karmadactl logs in order to improve code reuse
```release-note
NONE
```
=> use kubectl logs to implement karmadactl logs

test/e2e/karmadactl_test.go
Fix flake e2e case: Karmadactl unjoin testing
Fixes #2176
```release-note
NONE
```
=> [E2E] fix flake e2e case: Karmadactl unjoin testing

pkg/search/backendstore/defaultstore.go, pkg/search/backendstore/opensearch.go, pkg/search/backendstore/store.go, pkg/search/controller.go
/kind cleanup
Remove unnecessary package alias
Fixes #
```release-note
NONE
```
=> Remove unnecessary package alias

pkg/controllers/binding/common_test.go
/kind cleanup
add ut for binding/common
Fixes #
```release-note
NONE
```
=> add ut for binding/common

pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go, pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
/kind feature
aggregate the pod failded and succeeded status
Fixes #2137 
```release-note
`karmada-controller-manager`:  `interpreter framework` starts to support Pod  `Failded` and `Succeeded`  aggregation.  
```
=> sync pod failded and succeeded status

pkg/karmadactl/promote.go
/kind cleanup
improve karmadactl promte -h
=> improve karmadactl promte -h

pkg/util/namespace_test.go
/kind cleanup
add ut for pkg/utils/namespace
Fixes #
pkg/utils/namespace.go coverage 100%
```release-note
NONE
```
=> [ut] add ut for pkg/utils/namespace

pkg/estimator/client/general.go
/kind cleanup
```release-note
NONE
```
=> fix inaccurate code comment in  pkg/estimator/client/general.go

cmd/controller-manager/app/controllermanager.go, pkg/util/restmapper/restmapper.go, pkg/util/restmapper/restmapper_test.go
[](url)**What type of PR is this?**
/kind feature
Add a new type cachedRESTMapper for performance improvement
Fixes #2105  
```
NONE
```
Here are the results of benchmark.
=> Add a New Type cachedRESTMapper 

docs/descheduler.md
After reading the descheduler document recently, I found that the format of the document is not uniform and the command is difficult to reuse, so now I optimize the document
Fixes #
```release-note
NONE
```
=> descheduler docs: increase the readability and reusability of documents

pkg/karmadactl/karmadactl.go
/kind feature
With increasement of subcommands that have different functions, perhaps, it is clearer to group them.
```
[root@master67 karmada]# ./karmadactl -h
karmadactl controls a Kubernetes Cluster Federation.
Basic Commands:
get           Display one or many resources
version       Print the version information
Cluster Registeration Commands:
init          Install karmada in kubernetes
deinit        Removes Karmada from Kubernetes
join          Register a cluster to control plane
unjoin        Remove the registration of a cluster from control plane
Cluster Management Commands:
cordon        Mark cluster as unschedulable
uncordon      Mark cluster as schedulable
taint …
```
=> Group the subcommands of karmadactl

pkg/apis/cluster/v1alpha1/events.go, pkg/controllers/cluster/cluster_controller.go, pkg/scheduler/core/generic_scheduler.go
Signed-off-by: likakuli <1154584512@qq.com>
/kind feature
let users to make decision whether to use unhealthy cluster in rb.
Fixes https://github.com/karmada-io/karmada/issues/1853
```release-note
None
```
=> feat: use taint instead of condition to filter cluster

pkg/registry/search/storage/requestinfo.go, pkg/registry/search/storage/requestinfo_test.go
Signed-off-by: luomonkeyking <luomonkeyking@gmail.com>
/kind bug
Fix the problem that karmada-search cannot query a single namespace
Fixes# [2221](https://github.com/karmada-io/karmada/issues/2221)
Need to check again if there are any changes or omissions
```
`karmada-search`: fixed can not query a single namespace issue.
```
=> karmada-search cannot query a single namespace

pkg/karmadactl/apply.go
/kind feature
```sh
(⎈ |karmada:default)➜  karmada git:(karmadactl-apply) kubectl get clusters
NAME   VERSION           MODE   READY   AGE
dce    v1.18.20          Push   False   93d
ik8s   v1.21.5           Push   True    22d
ocp    v1.11.0+d4cacc0   Push   True    92d
(⎈ |karmada:default)➜  karmada git:(karmadactl-apply) go run cmd/karmadactl/karmadactl.go apply -f ~/manifests.yaml --cluster ik8s
deployment.apps/micro-dao-2048 created
propagationpolicy.policy.karmada.io/micro-dao-2048-6d7f8d5f5b created
service/micro-dao-2048 created
propagationpolicy.policy.karmada.io/micro-dao-2048-76579ccd86 created
(⎈ |karmada:default)➜  karmada git:(karmadactl-apply) kubectl describe pp | grep -n2  "Cluster Affinity"
31-Spec:
32- …
```
=> karmadactl allow users to select one or many member clusters to propagate resources.

pkg/resourceinterpreter/defaultinterpreter/default.go, pkg/resourceinterpreter/interpreter.go, pkg/util/helper/job.go
/kind bug
This is a regression during the development where we added resource interpreter, this pr fixes it
For https://github.com/karmada-io/karmada/issues/2239
```release-note
NONE
```
=> Make sure to update resource status

charts/karmada/templates/post-install-job.yaml
Signed-off-by: zhixian <zhy0882@mail.ustc.edu.cn>
Fixes #2255
=> fix: create cluster apiservice in post install job

docs/multi-cluster-service.md
When I read the document directly, there was no corresponding display result, so it was not easy to understand. Therefore, the document was optimized and examples were added to facilitate users to understand the content of the document
Fixes #
```release-note
NONE
```
=> docs: add clearer documentation for multiple cluster services

api/openapi-spec/swagger.json, pkg/apis/policy/v1alpha1/override_types.go, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
Add overrider description for overridePolicy API
Fixes #
None
=> Add overrider description for overridePolicy API

pkg/karmadactl/OWNERS
/kind cleanup
`carlory` has met all the requirements to be a reviewer of karmadactl, according to https://github.com/karmada-io/community/blob/main/community-membership.md#requirements-1
Fixes #2270
```release-note
NONE
```
=> Put carlory onto the karmadactl owner list

docs/multi-cluster-ingress.md
After verifying and testing the multi-cluster ingress, incomplete commands were found in the document and the operation process was tedious. The PR optimized the problems found and simplified some steps
Fixes #
```release-note
NONE
```
=> docs: add clearer documentation for multiple cluster ingress

pkg/detector/detector.go
/kind feature
Fixes #
```release-note
NONE
```
=> add event error msg when failed to apply policy

api/openapi-spec/swagger.json, pkg/apis/cluster/types.go, pkg/apis/cluster/v1alpha1/types.go, pkg/apis/cluster/v1alpha1/zz_generated.conversion.go, pkg/generated/openapi/zz_generated.openapi.go
This PR propose the API change of [clusterid](https://github.com/karmada-io/karmada/tree/master/docs/proposals/clusterid) proposal.
Fixes #
```release-note
The `Cluster` API introduced an optional field named `ID` to uniquely identify the cluster.
```
=> Add ID to Cluster API

docs/working-with-istio-on-non-flat-network.md
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
Fixes #2288
```release-note
NONE
```
=> update istio-on-nonflat-network doc

pkg/util/resource.go, pkg/util/resource_test.go
/kind cleanup
Optimize code to reduce redundancy
Fixes #
```release-note
NONE
```
=> Optimize code to reduce redundancy

docs/userguide/propagate-dependencies.md, pkg/resourceinterpreter/defaultinterpreter/dependencies.go, pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
/kind feature
Propagate dependencies add support propagate ServiceAccount
Fixes #
```release-note
Propagate dependencies add support propagate ServiceAccount
```
=> Propagate dependencies add support propagate ServiceAccount

pkg/karmadactl/addons/OWNERS
/kind cleanup
Put wuyingjun-lucky onto karmadactl addons owner list
PR authored (20+) : https://github.com/karmada-io/karmada/pulls?q=is%3Apr+author%3Awuyingjun-lucky+is%3Aclosed 
PR reviewed: 
https://github.com/karmada-io/karmada/pull/2162
https://github.com/karmada-io/karmada/pull/2177
https://github.com/karmada-io/karmada/pull/2283
https://github.com/karmada-io/karmada/pull/2038
Fixes #
```release-note
NONE
```
=> Put wuyingjun-lucky onto karmadactl addons owner list

pkg/controllers/execution/execution_controller.go
/kind cleanup
Some resource's scope is `Cluster`, so we use `klog.KObj`
Fixes #
```release-note
NONE
```
=> cleanup event in execution_controller

hack/.import-aliases, pkg/search/backendstore/opensearch.go, pkg/search/backendstore/store.go, pkg/search/controller.go, pkg/util/gclient/gclient.go
/kind cleanup
As we add some groups of APIs, so we need to update the `hack/.import-aliases` file.
Fixes #
```release-note
NONE
```
=> update import aliases

pkg/util/apigroup.go
Signed-off-by: duanmeng <duanmengng_yewu@cmss.chinamobile.com>
/kind cleanup
Fixes #2321
```release-note
NONE
```
=> Put Lease to default SkippedResourceConfig

pkg/search/backendstore/opensearch.go
/kind cleanup
Clear conflict between variable `delete` and builtin function
Fixes #
```release-note
NONE
```
=> Clear conflict between variable `delete` and builtin function

pkg/search/backendstore/opensearch.go
/kind bug
opensearch: fixed panic issue when dumps error infos
Fixes #
```release-note
`karmada-search`: Fixed panic issue when dumps error info.
```
=> opensearch: fixed panic issue when dumps error infos

docs/installation/install-binary.md, docs/installation/installation.md
installation of binary high-availability `karmada` cluster.
Fixes #
```release-note
Increase the way to install karmada, use binary installation.
```
=> add docs: binary install karmada

pkg/scheduler/core/spreadconstraint/util_test.go
/kind cleanup
add ut for spreadconstraint
Fixes #
```release-note
NONE
```
=> add ut for spreadconstraint

pkg/karmadactl/describe.go, vendor/k8s.io/kubectl/pkg/cmd/describe/describe.go, vendor/modules.txt
/kind feature
use kubectl describe to implement karmadactl describe in order to improve code reuse
Fixes #
```release-note
NONE
```
=>  use kubectl describe to implement karmadactl describe

docs/proposals/resource-interpreter-webhook/README.md, pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go, pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
/kind cleanup
This PR renamed `InterpreterOperation` from `InterpretHealthy` to `InterpretHealth` for grammar concern.
Fixes #
```release-note
NONE
```
=> Rename interpreter operation health

pkg/apis/work/v1alpha2/binding_types_helper.go, pkg/apis/work/v1alpha2/binding_types_helper_test.go, pkg/controllers/cluster/taint_manager.go
/kind feature
This PR enables graceful eviction in taint manager but only takes effect when the feature gate is enabled.
Partof #2281
```release-note
NONE(part of graceful eviction)
```
=> Enable graceful eviction in taint manager

pkg/util/fedinformer/typedManager/multi-cluster-manager.go, pkg/util/fedinformer/typedManager/single-cluster-manager.go
/kind feature
Add typed shared informer cause in some scenes dynamic informer has bad performance.
Ref：#2318 
Fixes #
None
=> Add typed shared informer

pkg/dependenciesdistributor/dependencies_distributor.go, pkg/resourceinterpreter/defaultinterpreter/dependencies.go, pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go, test/e2e/dependenciesdistributor_test.go, test/e2e/framework/persistentvolumeclaim.go, test/e2e/suite_test.go, test/helper/resource.go
/kind feature
propagate dependencies support propagate pvc
Fixes #1887
```release-note
NONE
```
=> propagate dependencies support propagate pvc

examples/customresourceinterpreter/webhook-configuration.yaml, examples/customresourceinterpreter/webhook/app/workloadwebhook.go, pkg/resourceinterpreter/customizedinterpreter/customized.go, pkg/resourceinterpreter/defaultinterpreter/default.go, pkg/resourceinterpreter/defaultinterpreter/healthy.go, pkg/resourceinterpreter/defaultinterpreter/healthy_test.go, pkg/resourceinterpreter/interpreter.go, pkg/webhook/configuration/validating.go
/kind feature
Implement InterpretHealthy method for resource interpreter
Fixes #
```
`resource interpreter framework`: now able to interpret the resource health state.
```
=> implement InterpretHealth for resource interpreter

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/controllers/status/cluster_status_controller.go
/kind feature
update the dynamic informer in cluster status controller with typed informer
Ref: #2350 
Fixes #
NONE
=> update the dynamic informer in cluster status controller with typed informer

pkg/util/helper/binding_test.go
/kind cleanup
add ut for binding
Fixes #
```release-note
NONE
```
=> add ut for binding

test/e2e/framework/resourceregistry.go, test/e2e/search_test.go
Signed-off-by: huntsman_ly <huntsman_ly@sina.com>
Co-authored-by: liys87x <liyasong1987x@gmail.com>
/kind cleanup
add karmada-search e2e test
Fixes #
```release-note
```
=> [E2E] add karmada-search e2e test

pkg/util/helper/taint_test.go
/kind cleanup
improve ut for taint
Fixes #
```release-note
NONE
```
=> improve ut for taint

pkg/features/features.go
/kind feature
This PR introduced a feature gate and defaults in alpha state.
Part of #2379 
None
=> Add a feature gate for cluster resource custom modeling

pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go, pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go, pkg/util/constants.go
Signed-off-by: yusank <yusankurban@gmail.com>
kind bug
sync cluster scoped resources(like PV) status from member cluster to karmada cluster.
Fixes #2394 
NONE
NONE
=> fix: sync cluster level resource status

artifacts/deploy/karmada-scheduler.yaml, pkg/scheduler/event_handler.go, pkg/scheduler/metrics/metrics.go, pkg/scheduler/scheduler.go, test/e2e/failover_test.go, test/e2e/framework/constant.go
/kind feature
Fixes #1762
```release-note
Remove Failover from scheduler
```
=> remove Failover from scheduler

cmd/karmada-search/app/options/options.go, go.mod, pkg/search/proxy/cache_proxy.go, pkg/search/proxy/cache_proxy_test.go, pkg/search/proxy/cluster_proxy.go, pkg/search/proxy/controller.go, pkg/search/proxy/controller_test.go, pkg/search/proxy/store/cluster_cache.go, pkg/search/proxy/store/conversion.go, pkg/search/proxy/store/multi_cluster_cache.go, pkg/search/proxy/store/multi_cluster_cache_test.go, pkg/search/proxy/store/resource_cache.go, pkg/search/proxy/store/store.go, pkg/search/proxy/store/util.go
/kind feature
Implement for proxy cache
Part of #2372
```release-note
Users can access member cluster resource, supporting get/list/watch/update/patch/delete.
Subresource can be accessed too.
```
=> add proxy cache

pkg/search/backendstore/opensearch.go
karmada-search error log: Could not dynamically add mapping for field [app.name]. Existing mapping for [metadata.labels.app] must be of type object but found [text].
Co-authored-by: liys87x <liyasong1987x@gmail.com>
Signed-off-by: huntsman_ly <huntsman_ly@sina.com>
/kind bug
Fixes #2335 
```release-note
```
=> fix opensearch mapper_parsing_exception

cmd/agent/app/agent.go
/kind bug
Fixes #2403 
It can be restart in my environment now.
/cc @RainbowMango @yy158775 
```release-note
NONE(this bug hasn't been released.)
```
=> Fix it occur error when `karmada-agent` is restarted

pkg/apis/cluster/mutation/mutation.go, pkg/apis/cluster/mutation/mutation_test.go, pkg/apis/cluster/validation/validation.go, pkg/apis/cluster/validation/validation_test.go, pkg/registry/cluster/strategy.go
/kind feature
Add cluster resource model check if users edit cluster resource models.
Part of #2379 
None
=> add cluster resource model check

pkg/search/proxy/cluster_proxy.go, pkg/search/proxy/controller.go, pkg/search/proxy/store/multi_cluster_cache.go
/kind bug
1. Fix proxy get request will modify data in cache
2. change the error when creating member cluster resource.
Fixes #
```release-note
When creating resource defined in ResourceRegistry, `MethodNotSupported` error will be responsed
```
=> fix some problems in proxy

artifacts/deploy/karmada-etcd.yaml
/kind bug
Fix etcd livenessProbe to result to etcd restart according to #2097.
Fixes #2411 
cc @lonelyCZ 
None
=> fix etcd livenessProbe to result to etcd restart

artifacts/deploy/karmada-aggregated-apiserver.yaml, artifacts/deploy/karmada-controller-manager.yaml, artifacts/deploy/karmada-scheduler.yaml
/kind feature
Add CustomizedClusterResourceModeling feature gate for karmada-controller-manager and karmada-aggregated-apiserver and karmada-scheduler
Part of #2379 
None
=> add CustomizedClusterResourceModeling feature gate

pkg/controllers/status/cluster_status_controller.go
/kind feature
Make changes to cluster-status-controller to adopt cluster resource models, depends on #2367.
When create a fake node like:
```
allocatable:
cpu: "10"
memory: 100Gi
pods: 1M
```
It satisfy:
```
- grade: 4
ranges:
- max: "16"
min: "8"
name: cpu
- max: 128Gi
min: 64Gi
name: memory
```
status:
```
- count: 1
grade: 4
```
When change memory to 40Gi, it will not satisfy Grade 4, so status will:
```
- count: 1
grade: 3
- count: 0
grade: 4
```
When node num change to 7, the status will:
```
- count: 7
grade: 3
```
Part of #2379 
None
=> Make changes to cluster-status-controller to adopt cluster resource models

test/e2e/resourceinterpreter_test.go
/kind cleanup
Part of #2354 
NONE
=> add e2e test for InterpretHealth

test/e2e/framework/cluster.go, test/e2e/framework/dynamic.go, test/e2e/search_test.go
/kind cleanup
Add e2e test for proxy feature.
Part of #2372
=> [e2e] add proxy e2e test

hack/cherry_pick_pull.sh
/kind cleanup
Minor change: Fixed broken links.
` https://github.com/karmada-io/karmada/blob/master/docs/contributors/devel/cherry-picks.md` -->
` https://karmada.io/docs/contributor/cherry-picks`
Fixes #
```release-note
NONE
```
=> Fix broken links in cherry-pick script

pkg/resourceinterpreter/defaultinterpreter/retain.go
/kind bug
Fixes #2408
```release-note
`karmada-controller-manager`/`karmada-agent`: Now able to retain `.spec.claimRef` field of `PersistentVolume`.
```
=> retain PersistentVolume fields

charts/index.yaml, charts/karmada/README.md
/kind bug
Update the version of karmada  in Helm
```release-note
NONE
```
=> upgrade karmada version

pkg/karmadactl/cmdinit/cmdinit.go
/kind cleanup
Fixes #
improve karmada init help output
```release-note
Improve karmada init help output
```
=> improve karmada init help output 

hack/deploy-agent-and-estimator.sh, hack/deploy-karmada-agent.sh, hack/deploy-karmada-opensearch.sh, hack/deploy-karmada.sh, hack/deploy-scheduler-estimator.sh, hack/local-up-karmada.sh, hack/post-run-e2e.sh, hack/pre-run-e2e.sh, hack/remote-up-karmada.sh, hack/run-e2e.sh, hack/undeploy-karmada-agent.sh, hack/undeploy-karmada.sh, hack/util.sh, test/e2e/federatedresourcequota_test.go, test/e2e/framework/cluster.go, test/e2e/karmadactl_test.go, test/e2e/namespace_test.go, test/e2e/rescheduling_test.go, test/e2e/suite_test.go
/kind feature
This PR takes over #2091, fixed e2e test errors.
Fixes #2059
Fixes #2091
```release-note
NONE
```
=> do not switch context when deploy karmada

test/e2e/suite_test.go
As analyzed in https://github.com/karmada-io/karmada/pull/2298#issuecomment-1238836693, we need to enlarge the random string length in E2E test.
Fixes #
```release-note
NONE
```
=> Update RandomStrLength from 3 to 5 in E2E test

charts/index.yaml
/kind cleanup
Add repo index for 1.2.x
Fixes #2477 
None
=> Add repo index for 1.2.1 and 1.2.2

pkg/search/proxy/store/multi_cluster_cache.go
/kind bug
fix concurrent map writes panic while listing via proxy
```
fatal error: concurrent map writes
goroutine 1414 [running]:
runtime.throw({0x105907244?, 0x140017c8270?})
/Users/didi/sdk/go1.18.3/src/runtime/panic.go:992 +0x50 fp=0x14000a931e0 sp=0x14000a931b0 pc=0x10414cab0
runtime.mapassign_faststr(0x105f2fb40?, 0x14001a7eea0?, {0x1058f6675, 0xb})
/Users/didi/sdk/go1.18.3/src/runtime/map_faststr.go:212 +0x3bc fp=0x14000a93250 sp=0x14000a931e0 pc=0x10412819c
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.setNestedFieldNoCopy(0x14000a93348?, {0x105f2fb40?, 0x140017fb290}, {0x14000a933f8?, 0x140009b3de0?, 0x2?}) …
```
=> fix concurrent map writes panic while list via proxy

test/e2e/search_test.go
/kind bug
As say in https://github.com/karmada-io/karmada/issues/2488#issuecomment-1240452424, add wait proxy ready before test.
Fixes #2488
```release-note
NONE
```
=> [e2e] add wait for proxy ready

hack/deploy-scheduler-estimator.sh
fix deploy-scheduler-estimator.sh cannot generate correct kubeconfig file problem
Signed-off-by: raymondmiaochaoyue <raymondmiaochaoyue@didichuxing.com>
/kind bug
When used as [Cluster Accurate Scheduler Estimator For Rescheduling](https://karmada.io/docs/userguide/scheduling/scheduler-estimator) guided, the original `hack/deploy-scheduler-estimator.sh` have two problems:
(1) The <MEMBER_CLUSTER_KUBECONFIG> file is not flattened, and the `kubectl create secret generic` command will copy the <MEMBER_CLUSTER_KUBECONFIG> file's content directly without changing anything. So if the <MEMBER_CLUSTER_KUBECONFIG> contains none embedded cert reference like the following, karmada-scheduler-estimator will not be able to read the …
=> fix deploy-scheduler-estimator.sh cannot generate correct kubeconfig file problem

test/e2e/karmadactl_test.go
fix flaking test: karmadactl uncordon taint check
https://github.com/karmada-io/karmada/runs/8262020277?check_suite_focus=true
```log
Expected
<[]v1.Taint | len:1, cap:4>: [
{
Key: "cluster.karmada.io/not-ready",
Value: "",
Effect: "NoSchedule",
TimeAdded: {
Time: 2022-09-09T02:34:08Z,
},
},
]
to be empty
In [It] at: /home/runner/work/karmada/karmada/test/e2e/karmadactl_test.go:606
```
Fixes #2499 
```release-note
NONE
```
=> [E2E] fix flaking test: karmadactl uncordon taint check

cmd/agent/app/agent.go, cmd/controller-manager/app/controllermanager.go, pkg/descheduler/descheduler.go, pkg/estimator/server/server.go, pkg/scheduler/event_handler.go, pkg/search/controller.go
/kind feature
https://github.com/karmada-io/karmada/pull/1858#issuecomment-1134114741
Now it just removes `metadata.ManagedFields` since it's large and we never use it 
Fixes #1866
Looking forward to how much memory this can save
```release-note
NONE
```
=> Adopt transform func to save memory

pkg/dependenciesdistributor/dependencies_distributor.go, test/e2e/dependenciesdistributor_test.go, test/e2e/framework/deployment.go, test/e2e/framework/rbac.go, test/e2e/suite_test.go, test/helper/resource.go
/kind bug
After the `PP` is created, create the SA, and the SA will not be propagated.
Fixes #
Parts of #2035 
```release-note
NONE
```
=> propagate dependencies support propagate sa

README.md
/kind cleanup
This PR updated the outdated link from the badge. We shouldn't lead people to the old slack anymore.
Fixes #
```release-note
NONE
```
=> Update slack address in badge

pkg/karmadactl/karmadactl.go
/kind bug
fix typo(Registeration to Registration) in karmadactl
Fixes #2543
Just see #2543
NONE
```release-note
```
=> Fix a typo(Registeration) in CLI #2543

hack/docker.sh
/kind feature
This env var is used to provide additional arguments to the docker build command.
This typically allow to set HTTP proxy settings in the container only at build time. This was the original need described in #2553
Fixes #2553
An alternative specific to HTTP proxies is proposed in #2568
```release-note
NONE
```
=> Add a new env var `DOCKER_BUILD_ARGS`

charts/karmada/templates/_helpers.tpl
/kind cleanup
cleanup chart helper template.
Fixes #
```release-note
NONE
```
=> chart: cleanup chart helper template

pkg/controllers/binding/binding_controller.go, pkg/controllers/binding/cluster_resource_binding_controller.go, pkg/detector/detector.go, pkg/util/helper/workstatus.go
/kind cleanup
Stop publish duplicated event when there is nothing to change.
Fixes #
```release-note
NONE
```
=> stop publish duplicated event

artifacts/deploy/karmada-aggregated-apiserver.yaml, charts/karmada/templates/karmada-aggregated-apiserver.yaml, pkg/karmadactl/cmdinit/kubernetes/deployments.go
Signed-off-by: xin.li <xin.li@daocloud.io>
Add livenesProbe for karmada-aggregated-apiserver
/kind cleanup
Add livenesProbe for karmada-aggregated-apiserver
Fixes #
```release-note
NONE
```
=> Add livenesProbe for karmada-aggregated-apiserver

.github/workflows/ci.yml, Makefile
/kind cleanup
This PR enables code coverage and upload to [Codecov](https://app.codecov.io/gh).
Fixes #
Refer:
- https://github.com/codecov/codecov-action
- Coverage Report: https://app.codecov.io/gh/karmada-io/karmada/tree/pr_upload_coverage/pkg
```release-note
NONE
```
=> Upload code coverage to Codecov

pkg/version/version_test.go
add ut for pkg/version/version.go
/kind cleanup
```release-note
```
=> add ut for pkg/version/version.go
