pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap.go
pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
pkg/karmadactl/cmdinit/karmada/deploy.go
pkg/karmadactl/cmdinit/karmada/rbac.go
pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
pkg/karmadactl/cmdinit/karmada/webhook_configuration_test.go
pkg/karmadactl/cmdinit/utils/rbac.go
pkg/karmadactl/util/idempotency.go

/kind bug
/kind cleanup
When deploy karmada by `karmadactl init`, if `/var/lib/karmada-etcd` wasn't removed, the MutatingWebhookConfig and ValidateWebhookConfig will be not updated, lead to bad certificate.
```
I1118 17:55:47.030069   27650 deploy.go:91] Create MutatingWebhookConfiguration mutating-config.
I1118 17:55:47.042878   27650 webhook_configuration.go:195] MutatingWebhookConfiguration mutating-config already exists, skipping.
I1118 17:55:47.042937   27650 deploy.go:96] Create ValidatingWebhookConfiguration validating-config.
I1118 17:55:47.054390   27650 webhook_configuration.go:175] ValidatingWebhookConfiguration validating-config already exists, skipping.
```
It …

karmadactl init: fix MutatingWebhookConfig and ValidateWebhookConfig aren't updated

---

pkg/resourceinterpreter/configurableinterpreter/configurable.go
pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
pkg/resourceinterpreter/customizedinterpreter/customized.go
pkg/resourceinterpreter/defaultinterpreter/default.go
pkg/resourceinterpreter/interpreter.go
test/e2e/framework/resourceinterpretercustomization.go
test/e2e/resourceinterpreter_test.go
test/helper/config.go
test/helper/resource.go

/kind feature
add test case for resource interpreter customization:
- InterpretReplica
- ReviseReplica
part of https://github.com/karmada-io/karmada/issues/2371
```release-note
NONE
```

[E2E] add test case for resource interpreter customization

---

artifacts/deploy/kube-controller-manager.yaml
charts/karmada/templates/kube-controller-manager.yaml

Cherry pick of #2277 on release-1.3.
#2277: fix kube controller manager restart all the time
```release-note
`kube-controller-manager`:  Fixed liveness probe misconfiguration which caused kube-controller-manager to always `CrashLoopBackup`.
```

Automated cherry pick of #2277: fix kube controller manager restart all the time

---

pkg/karmadactl/interpret/check.go
pkg/karmadactl/interpret/execute.go
pkg/karmadactl/interpret/interpret.go
pkg/karmadactl/interpret/rule.go
pkg/karmadactl/karmadactl.go
pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go

/kind feature
add skeleton of interpreter command.
part of #2371
<details>
```bash
Check the valid of customizations. Or show the result of the rules running.
1. 
Check valid. Given the customization by NAME or '-f' option, this tool will check the rules in customization, and print
'PASS' or 'FAIL' for each rule. The fail reasons are also printed.
2. 
Execute rules and show result. Given the customization by NAME or '-f' option, the operation by 'operation' option, and
arguments by options(desired, desired-file, observed, observed-file, status, status-file, desired-replica),  this tool
will run the …
```

add interpret command

---

pkg/karmadactl/register/register.go

Signed-off-by: 宋文杰 <wenjie.song@daocloud.io>
/kind cleanup
karmadactl register add args check:   karmada apiserver endpoint expects exactly one argument
Fixes #
```release-note
karmada apiserver endpoint expects exactly one argument
```

karmadactl register add args check

---

pkg/resourceinterpreter/configurableinterpreter/configmanager/accessor.go
pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
pkg/resourceinterpreter/configurableinterpreter/configmanager/manager_test.go

/kind feature
Support users can define multiple `ResourceInterpreterCustomization`, for one operation, only one script will take effect.
Part of #2371 
```release-note
NONE (Part feature)
```

support users can define multiple resourceinterpretercustomization

---

.github/workflows/ci.yml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
This PR updates the default Go version for CI and releases bots to v1.17.13.
The reason why we don't use `1.17.x` is we need to know the Go version for each release so that we can track and figure out if it is affected by a security issue.
Fixes #
```release-note
Karmada(v1.2) is now built with Go1.17.13.
```

Build release-1.2 with go1.17.13

---

.github/workflows/ci.yml
.github/workflows/image.yml
.github/workflows/release.yml
.github/workflows/swr-released-image.yml

/kind cleanup
This PR updates the default Go version for CI and releases bots to v1.17.13.
The reason why we don't use 1.17.x is we need to know the Go version for each release so that we can track and figure out if it is affected by a security issue.
Fixes #
```release-note
Karmada(v1.1) is now built with Go1.17.13.
```

Build release-1.1 with go1.17.13

---

hack/deploy-karmada.sh
hack/util.sh

/kind bug
Fix deploy karmada-apiserver error by loadBalancer, there is two errors in scripts:
1. wait_service_external_ip should use "${HOST_CLUSTER_NAME}" context because context "karmada-apiserver" is available after append_client_kubeconfig.
2. When "{{range .status.loadBalancer.ingress}}{{.hostname}}" is empty, "external_ip" will be "<no value>".
Logs from "hack/deploy-karmada.sh":
```
Apply dynamic rendered apiserver service in /tmp/tmp.YDARfw2Jjk/karmada-apiserver.yaml.
deployment.apps/karmada-apiserver created
service/karmada-apiserver created
wait the karmada-apiserver ready...
pod/karmada-apiserver-547489884f-vdwcr condition met
Karmada API Server's IP is: …
```

Fix deploy karmada-apiserver error by loadBalancer

---

pkg/descheduler/descheduler.go

/kind bug
https://github.com/karmada-io/karmada/pull/2527
```
[root@dce-10-29-5-180 ~]# kubectl -n karmada-system logs karmada-descheduler-5b9f8ff755-kjxd5 --tail 10
}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup -member: no such host"
W1123 09:00:26.085826       1 logging.go:59] [core] [Channel #315 SubChannel #316] grpc: addrConn.createTransport failed to connect to {
"Addr": "-member:10352",
"ServerName": "-member:10352",
"Attributes": null,
"BalancerAttributes": null,
"Type": 0,
"Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp: lookup -member: no such host"
E1123 09:00:28.773837       1 …
```

fix descheduler estimator connection error

---

.github/workflows/ci.yml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml
README.md
go.mod
hack/util.sh
pkg/apis/cluster/validation/validation.go
pkg/controllers/cluster/cluster_controller.go
pkg/controllers/unifiedauth/unified_auth_controller.go
pkg/generated/clientset/versioned/fake/register.go
pkg/generated/clientset/versioned/scheme/register.go
pkg/printers/tablegenerator.go
pkg/sharedcli/commandusage.go
pkg/util/helper/job.go
pkg/util/lifted/deployment.go
pkg/util/lifted/requestinfo.go
pkg/util/lifted/visitpod.go
test/e2e/scheduling_test.go

/kind cleanup
This PR updates the default Go version for CI and releases bots to v1.19.3.
Since the dependency requires Go1.19+. 
Fixes #
The significant change:
> Go 1.19 adds support for links, lists, and clearer headings in doc comments. As part of this change, [gofmt](https://go.dev/cmd/gofmt) now reformats doc comments to make their rendered meaning clearer.
```release-note
Karmada(v1.4) is now built with Go1.19.3.
```

Update Golang version from v1.18.3 to v1.19.3

---

pkg/controllers/mcs/service_import_controller.go
pkg/events/events.go

/kind feature
Add event for MCS.
serviceImport:
```
Events:
Type    Reason                     Age   From                       Message
----    ------                     ----  ----                       -------
Normal  SyncDerivedServiceSucceed  74s   service-import-controller  Sync derived service for serviceImport(serve) succeed.
Normal  SyncWorkSucceed            74s   binding-controller         Sync work of resourceBinding(default/serve-serviceimport) successful.
Normal  AggregateStatusSucceed     74s   binding-controller         Update resourceBinding(default/serve-serviceimport) with AggregatedStatus successfully.
Normal  SyncSucceed                73s …
```

Add events for MCS

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/controllers/status/cluster_status_controller.go
pkg/metrics/cluster.go
pkg/metrics/cluster_test.go

/kind feature
Add metrics for cluster status, metrics name according to https://prometheus.io/docs/practices/naming/#metric-and-label-naming.
```
cluster_cpu_allocatable_number{cluster_name="member1"} 8
cluster_cpu_allocatable_number{cluster_name="member2"} 8
cluster_cpu_allocated_number{cluster_name="member1"} 1.95
cluster_cpu_allocated_number{cluster_name="member2"} 0.9500000000000001
cluster_memory_allocatable_bytes{cluster_name="member1"} 1.6817958912e+10
cluster_memory_allocatable_bytes{cluster_name="member2"} 1.6817958912e+10
cluster_memory_allocated_bytes{cluster_name="member1"} 3.0408704e+08
cluster_memory_allocated_bytes{cluster_name="member2"} 3.0408704e+08 …
```

Add metrics for cluster

---

pkg/karmadactl/register/register.go
pkg/karmadactl/util/apiclient/apiclient.go

/kind bug
```
[root@master67 karmada]# ./karmadactl register 10.10.103.67:32443 --token w1s6h8.6s2w87vbhs6rjphp --discovery-token-ca-cert-hash sha256:e40e2e42128b7fbd9df76ed1f829e0b3dcfd06c21b2a50a1d50de5c49e44b983 -v=6
I1124 14:36:16.076443   22896 loader.go:372] Config loaded from file:  /root/.kube/config
error: failed to read kubeconfig file , err: open : no such file or directory
```
It was introduced at #2752 
https://github.com/karmada-io/karmada/blob/63a67d7cbdb255297d9b889d5c3752e9b75a931b/pkg/karmadactl/register/register.go#L251-L255
It need to extract member cluster name from kubeconfig file if the name wasn't set, but the `o.KubeConfig` is nil, so this error …

Fix karmadactl register failed to read kubeconfig file

---

pkg/apis/cluster/validation/validation.go
pkg/apis/cluster/validation/validation_test.go

/kind feature
when we use the fieldSelector field of the clusterAffinity to select clusters, some cluster won't be selected and we will get this scheduler result that there're no fit clusters. 
for example, the provider of cluster contains chinese characters, the scheduler will not select this cluster. 
because the fieldSelector is converted to a labelSelector, the labelSelector will check the value.
FYI: 
- https://github.com/karmada-io/karmada/blob/master/pkg/util/selector.go#L110
- https://github.com/karmada-io/karmada/blob/23db2ac9d66b87033b855bd9f694defadc3d5b1c/vendor/k8s.io/apimachinery/pkg/labels/selector.go#L192 …

validate cluster fields

---

Makefile
hack/build.sh
hack/util.sh
hack/version.sh

/kind bug
```bash
$ echo >> README.md
$ make image-karmada-controller-manager
Building image for linux/amd64: docker.io/karmada/karmada-controller-manager:v1.3.0-452-g63a67d7c
...
```
Expect image: `docker.io/karmada/karmada-controller-manager:v1.3.0-452-g63a67d7c-dirty`
Fixes #
```release-note
fix dirty is not added in docker image tag
```

fix dirty is not added in docker image tag

---

pkg/resourceinterpreter/defaultinterpreter/prune/prune.go

/kind bug
Object watcher retains finalizers on member cluster when updating. Finalizers shouldn't be propagated to member cluster from control plane.
Fixes #2810
Finalizers will not be propagated to member cluster

do not propagate finalizers to member cluster

---

pkg/webhook/overridepolicy/mutating.go
pkg/webhook/propagationpolicy/mutating.go

/kind bug
Fixes #2598
Fixes #2597
karmada-webhook log:
```
I1123 12:06:11.103068       1 mutating.go:45] Mutating PropagationPolicy(/demo33-propagation-3fpnly) for request: CREATE
I1123 12:06:11.103098       1 mutating.go:50] Setting resource selector default namespace for policy: /demo33-propagation-3fpnly
I1123 12:06:11.106849       1 validating.go:35] Validating PropagationPolicy(kaihua-karmada-pair/demo33-propagation-3fpnly) for request: CREATE
I1123 12:06:11.120063       1 mutating.go:35] Setting resource selector default namespace for policy: /demo33-deployment-override
I1123 12:06:11.123010       1 validating.go:32] Validating OverridePolicy(kaihua-karmada-pair/demo33-deployment-override) for request: CREATE
``` …

fix setting resource selector default namespace for policy

---

pkg/webhook/overridepolicy/mutating.go
pkg/webhook/propagationpolicy/mutating.go

Cherry pick of #2858 on release-1.3.
#2858: fix setting resource selector default namespace for policy
```release-note
`karmada-webhook`: Fixed failed to set resource selector default namespace if the relevant OverridePolicy and PropagationPolicy with namespace unset issue.
```

Automated cherry pick of #2858: fix setting resource selector default namespace for policy

---

go.mod
pkg/karmadactl/interpret/execute.go
pkg/karmadactl/interpret/interpret.go
pkg/karmadactl/interpret/rule.go
pkg/karmadactl/util/genericresource/builder.go
pkg/karmadactl/util/genericresource/doc.go
pkg/karmadactl/util/genericresource/interface.go
pkg/karmadactl/util/genericresource/result.go
pkg/karmadactl/util/genericresource/visitor.go
pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
pkg/resourceinterpreter/configurableinterpreter/configurable.go

/kind feature
add skeleton of interpreter command.
part of #2371
Prepare a `get-replica.yml`
<details>
```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
name: get-replica
spec:
target:
customizations:
retention:
replicaResource:
luaScript: >
function GetReplicas(obj)
replica = obj.spec.replicas + 1
requirement = {}
return replica, requirement
end
```
</details>
and `deploy-nginx.yml`
<details>
```yaml
metadata:
name: nginx
spec:
selector:
matchLabels:
app: nginx
template: …
```

add execute mod for interpret command

---

pkg/controllers/cluster/taint_manager.go
pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/evictiontask.go
pkg/controllers/gracefuleviction/evictiontask_test.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
pkg/events/events.go
pkg/util/helper/binding.go

/kind feature
Add events for graceful eviction controller:
```
Events:
Type    Reason                           Age                 From                                           Message
----    ------                           ----                ----                                           -------
Normal  SyncWorkSucceed                  49s (x14 over 16m)  binding-controller                             Sync work of resourceBinding(default/nginx-deployment) successful.
Normal  AggregateStatusSucceed           49s (x14 over 16m)  binding-controller                             Update resourceBinding(default/nginx-deployment) with AggregatedStatus successfully.
Normal …
```

Add events for graceful eviction controller

---

artifacts/deploy/karmada-controller-manager.yaml
pkg/features/features.go

The `PropagateDeps` feautre hes been stably supported n multiple versions (since version v1.1). It is planned to enable the `PropagateDeps FeatureGate` by default and evolute it to beta.
This is a global gate. Users need to set the `.spec.propagateDeps` of the `PropagationPolicy/ClusterPropagationPolicy` to true to enable the releavant resources be propagated automatically.
Fixes #
```release-note
karmada-controller-manager: evolute PropagateDeps FeatureGate to Beta  and enable it by default
```

evolute PropagateDeps FeatureGate to Beta  and enable it by default

---

pkg/resourceinterpreter/configurableinterpreter/configurable.go
pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go
pkg/util/fixedpool/fixedpool.go
pkg/util/fixedpool/fixedpool_test.go

/kind cleanup
At present, we create a new Lua vm to run script for every calling. This pr create vm once, before running script, get vm from pool, reducing the cost of vm creating.
I test it with a demo, calling the script every 10ms:
```
const script = `
function GetReplicas(obj)
return 0, {}
end`
func main() {
vm := luavm.New(false, 10)
for range time.Tick(time.Millisecond * 10) {
_, _, err := vm.GetReplicas(&unstructured.Unstructured{}, script)
if err != nil {
fmt.Println(err)
os.Exit(1)
}
}
}
```
and implements `GetReplicas` in two ways:
- without pool : run in `luavm1` pod
- with pool:  run in `luavm2` pod
Even in `luavm2` cost little more memory(48M v.s. 36M), …

improve lua vm executing with pool

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/controllers/binding/binding_controller.go
pkg/controllers/binding/cluster_resource_binding_controller.go
pkg/controllers/execution/execution_controller.go
pkg/detector/detector.go
pkg/detector/policy.go
pkg/metrics/resource.go

/kind feature
As we consider the resource distribution latency as one of the important metrics to measure the multi-cluster system, we might need some metrics to some detailed steps.
A complete distribution contains: looking for a matched policy -> apply policy -> sync work -> sync workload to target cluster.
```
resource_find_matched_policy_duration_seconds_bucket{apiVersion="apps/v1",kind="Deployment",name="nginx",namespace="default",le="0.001"} 1
resource_find_matched_policy_duration_seconds_bucket{apiVersion="apps/v1",kind="Deployment",name="nginx",namespace="default",le="0.002"} 1
resource_find_matched_policy_duration_seconds_bucket{apiVersion="apps/v1",kind="Deployment …
```

Add metrics for resource

---

artifacts/deploy/karmada-controller-manager.yaml
charts/karmada/templates/karmada-scheduler.yaml
pkg/features/features.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go

* The `Failover` feature has been supported from v0.4.0. It is time to enable the Failover FeatureGate by default and evolute it to beta.
* `GracefulEviction` has been supported from v1.3.0.  Enable the GracefulEviction FeatureGate by default and evolute it to beta.
Fixes #none
none
```release-note
karmada-controller-manager: evolute Failover/GracefulEviction FeatureGate to Beta and enable it by default.
```

Evolute Failover/GracefulEviction FeatureGate  to beta version and  enable it by default

---

artifacts/deploy/karmada-aggregated-apiserver.yaml
artifacts/deploy/karmada-controller-manager.yaml
artifacts/deploy/karmada-scheduler.yaml
pkg/features/features.go

The CustomizedClusterResourceModeling feautre hes been stably supported since version v1.3. It is planned to enable the CustomizedClusterResourceModeling FeatureGate by default and evolute it to beta.
The detailed usage can be found in https://karmada.io/docs/next/userguide/scheduling/cluster-resources.
Fixes #
```release-note
karmada-controller-manager, karmada-aggregated-apiserver, karmada-scheduler: evolute CustomizedClusterResourceModeling FeatureGate to Beta  and enable it by default
```

Evolute CustomizedClusterResourceModeling to Beta and enable it by default

---

cmd/controller-manager/app/controllermanager.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/events/events.go

/kind feature
Add getDependencies to resource template
```
Events:
Type     Reason                  Age                 From                      Message
----     ------                  ----                ----                      -------
Warning  ApplyPolicyFailed       28s                 resource-detector         No policy match for resource
Normal   ApplyPolicySucceed      22s                 resource-detector         Apply policy(default/my-nginx-propagation) succeed
Normal   SyncWorkSucceed         22s (x7 over 22s)   binding-controller        Sync work of resourceBinding(default/my-nginx-deployment) successful.
Normal   AggregateStatusSucceed  22s (x7 over 22s) …
```

Add getDependencies and syncScheduleResultToDependencies event

---

pkg/karmadactl/interpret/OWNERS

/kind cleanup
This PR nominated @ikaven1024 and @XiShanYongYe-Chang as the resource interpreter framework owners.
refer to https://github.com/karmada-io/karmada/issues/2371.
Fixes #
```release-note
NONE
```

Nominate resource interpreter owners

---

pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go

/kind cleanup
This PR cleanup redundant pointer usage of atomic types for both `atomic.Value` and `atomic.Bool`,
they are safe to use the zero value.
echo from `atomic.Value`'s comment:
> The zero value for a Value returns nil from Load.
echo from `atomic.Bool`'s comment:
> The zero value is false.
Fixes #
```release-note
NONE
```

Remove redundant pointer use of atomic types

---

pkg/karmadactl/cmdinit/karmada/rbac.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go

/kind bug
`karmada-agent` need to permission to delete `work` resources.
```
E1205 07:30:10.437634       1 service_export_controller.go:459] Failed to delete work(karmada-es-member140/dc-demo-59r4p-58b774c749), Error: works.work.karmada.io "dc-demo-59r4p-58b774c749" is forbidden: User "system:node:member140" cannot delete resource "works" in API group "work.karmada.io" in the namespace "karmada-es-member140"
E1205 07:30:10.437688       1 service_export_controller.go:161] Failed to handle endpointSlice(default/dc-demo-59r4p) event, Error: works.work.karmada.io "dc-demo-59r4p-58b774c749" is forbidden: User "system:node:member140" cannot delete resource "works" in API group …
```

Fix that karmada-agent don't have permission to delete `work` resources

---

pkg/util/overridemanager/overridemanager.go
pkg/util/overridemanager/overridemanager_test.go

/kind feature
add implicit priority for OP and COP
like https://github.com/karmada-io/karmada/pull/2267
1. get the list of PP(or OP) that matches the workload.
2. sort the list by priority (I assume the list won't be so long, so performance won't be a concern here.)
3. for PP, we just pick the first item from the list, for OP, we apply the whole list by order.
```release-note
`karmada-controller-manager`: Now the `OverridePolicy` and `ClusterOverridePolicy` will be applied by implicit priority order. The one with lower priority will be applied …
```

add implicit priority for OP and COP

---

pkg/karmadactl/cmdinit/karmada/rbac.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go

Cherry pick of #2902 on release-1.4.
#2902: Fix that karmada-agent don't have permission to delete work
```release-note
`karmadactl`: Fixed `karmada-agent` installed by the `register` command can not delete works due to lack of permission issue.
```

Automated cherry pick of #2902: Fix that karmada-agent don't have permission to delete work

---

.github/workflows/ci.yml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
Golang community just released 1.18.9, this patch release addressed 2 security fixes.
See [release notes](https://go.dev/doc/devel/release#go1.18.9) for more information.
So we update the golang version from v1.18.8 to v1.18.9 .
Fixes #
```release-note
Karmada is now built with Go1.18.9.
```

Update Golang version from v1.18.8 to v1.18.9

---

.github/workflows/ci.yml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
Fixes #2907
```release-note
Karmada is now built with Golang 1.19.4.
```

Build with Go patch release 1.19.4

---

pkg/util/rbac.go
pkg/util/rbac_test.go

/kind bug
unified-auth-controller generates PolicyRules from given subjects for impersonation need deduplicate by name
Fixes #
```release-note
`karmada-controller-manager`: generate PolicyRules from given subjects for impersonation deduplicate
```

generate PolicyRules from given subjects for impersonation deduplicate

---

pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

Fixes #
```release-note
`karmadactl`: Fixed the default ValidatingWebhookConfiguration for `resourceinterpretercustomizations` not working issue.
```

fix resourceinterpretercustomizations webhook

---

pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

… not work
Signed-off-by: hejunhua <hejunhua@cestc.cn>
/kind bug
Part of #2921
```release-note
`karmadactl`: Fixed the default ValidatingWebhookConfiguration for `resourceinterpreterwebhook` not working issue.
```

Cherry pick #2915 to release-1.3: fix that validating for resourceinterpreterwebhookconfigurations

---

pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

… not work
Signed-off-by: hejunhua <hejunhua@cestc.cn>
/kind bug
Part of #2921
```release-note
`karmadactl`: Fixed the default ValidatingWebhookConfiguration for `resourceinterpreterwebhook` not working issue.
```

Automated cherry pick of #2915 upstream release 1.4

---

examples/karmadactlinterpret/observed-deploy-nginx.yaml
examples/karmadactlinterpret/resourceinterpretercustomization.yaml
pkg/resourceinterpreter/configurableinterpreter/luavm/kube.go
pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
pkg/resourceinterpreter/configurableinterpreter/luavm/lua_convert.go
pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go

/kind feature
When users use customization to implement `GetReplicas`, it's difficult to accurate the sum of resource quantity. This PR load the `kube` library to help do this work.
See the demo: https://github.com/karmada-io/karmada/blob/f6a9956c078c4886e88a3d98952d4ff3ecd319ba/pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go#L65-L70
part of #2371
```release-note
NONE
```

add kube lib for lua

---

pkg/util/names/names.go
pkg/util/names/names_test.go

Cherry pick of #2919 on release-1.2.
#2919: replace colon with point in the rbac resource name
```release-note
`karmadactl`: Fixed the error of resources whose name contains colons failing to be created when using `karmadactl promote`.
```

Automated cherry pick of #2919: replace colon with point in the rbac resource name

---

pkg/controllers/status/cluster_status_controller.go
test/e2e/resource_test.go

/kind bug
When cluster status is unhealthy, we should not stop informer manager because when apiserver recovered, workload can not sync to karmada control plane.
Reproduction：
1.Failover is close.
2.Deploy a deployment to m1 and m2.
3.m1 apiserver failed. The cluster status of m1 became false. Soon it recovered. The cluster status of m1 became true again.
4.Update the deployment in m1. But the control plane cannot perceive the change of deployment in m1.
Reason:
Informer of m1 didn't work and could not collect update events.
Fixes #2863 
```release-note …
```

Fix work status not sync to control plane when apiserver failed and recovered soon

---

pkg/resourceinterpreter/defaultinterpreter/healthy.go
pkg/resourceinterpreter/defaultinterpreter/healthy_test.go

/kind bug
When I apply the following yaml of the deployment and pp
```yaml
metadata:
name: nginx
labels:
app: nginx
spec:
replicas: 2
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- image: nginx:dfaadadffasdfa # image not exist
name: nginx
---
metadata:
spec:
name: nginx
placement:
clusterNames:
- 10-29-14-21
- 10-29-14-25
```
We can find that the health state of the resource under the resourceBinding is `Healthy`
```yaml
status:
aggregatedStatus:
- applied: true
clusterName: …
```

Fix misjudgment of deployment and statefuleset health status

---

pkg/resourceinterpreter/defaultinterpreter/healthy.go
pkg/resourceinterpreter/defaultinterpreter/healthy_test.go

Cherry pick of #2928 on release-1.4.
#2928: Fix Deployment and Statefulset health judgments
```release-note
Fix misjudgment of deployment and statefuleset health status
```

Automated cherry pick of #2928: Fix misjudgment of deployment and statefuleset health status

---

pkg/controllers/status/cluster_status_controller.go
test/e2e/resource_test.go

Cherry pick of #2930 on release-1.4.
#2930: fix work status not sync to control plane
```release-note
`karmada-controller-manager`/`karmada-agent`: Fixed failed to sync work status issue due to the informer being accidentally shut down.
```

Automated cherry pick of #2930: fix work status not sync to control plane

---

pkg/resourceinterpreter/configurableinterpreter/configmanager/accessor.go
pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
pkg/resourceinterpreter/configurableinterpreter/configmanager/manager_test.go
pkg/resourceinterpreter/configurableinterpreter/configurable.go
pkg/resourceinterpreter/configurableinterpreter/dependencyset.go
pkg/resourceinterpreter/configurableinterpreter/dependencyset_test.go
pkg/webhook/resourceinterpretercustomization/helper.go
pkg/webhook/resourceinterpretercustomization/helper_test.go
test/e2e/resourceinterpreter_test.go

/kind feature
Support multiple dependencyInterpreter lua script for one gvk resource
Part of #2371 
```release-note
`karmada-controller-manager`: Users are now able to apply multiple dependencies interpreter configurations.
```

Support multiple dependencyInterpreter lua script for one gvk

---

pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/event_handler.go
pkg/scheduler/scheduler.go
test/e2e/framework/cluster.go
test/e2e/rescheduling_test.go

/kind bug
* Fix resource hangover in member cluster when propagating missmatch
Fixes https://github.com/karmada-io/karmada/issues/2906
none
```release-note
`karmada-scheduler`: Fixed a corner case that re-schedule be skipped in case of the cluster becomes not fit.
```

fix a corner case that re-schedule be skipped in case of the cluster becomes not fit.

---

charts/karmada/templates/post-delete-job.yaml

/kind bug
if the resources associated with cert is failed to apply in pre-install job, and the whole process of installtion is failed, then while we delete the release of  karmada,  the err log is be throwed in post-delete job. due to those resource is not found in the cluster.
Fixes #
So, in the case, we should ignore err  when delete non-exist resource.
```release-note
NONE
```

fix post-delete job of chart

---

pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/event_handler.go
pkg/scheduler/scheduler.go
test/e2e/framework/cluster.go
test/e2e/rescheduling_test.go

Cherry pick of #2912 on release-1.4.
#2912: fix a corner case that re-schedule be skipped in case of the cluster becomes not fit.
```release-note
`karmada-scheduler`: Fixed a corner case that re-schedule be skipped in case of the cluster becomes not fit.
```

Automated cherry pick of #2912: fix a corner case that re-schedule be skipped in case of the cluster becomes not fit

---

test/e2e/failover_test.go
test/e2e/karmadactl_test.go
test/e2e/porting_workloads_test.go
test/e2e/rescheduling_test.go
test/e2e/resource_test.go
test/e2e/scheduling_test.go

Cherry pick of #2552 on release-1.3.
#2552: replace gomeme.Eventually with wait when logic has assertions
```release-note
NONE
```

Automated cherry pick of #2552: replace gomeme.Eventually with wait when logic has assertions

---

pkg/karmadactl/unjoin/unjoin.go

/kind bug
CommandUnjoinOption wait must be a positive duration， but now allow wait = 0
if wait = 0,  when use  func poller,  timeout=0
A timeout of 0 is interpreted as an infinity, and in such a case
it would be the caller's responsibility to close the done channel.
Failure to do so would result in a leaked goroutine.
Fixes #
```release-note
CommandUnjoinOption wait must be a positive duration
```

CommandUnjoinOption wait must be a positive duration

---

.github/workflows/release.yml

/kind cleanup
Since [krew ](https://github.com/kubernetes-sigs/krew) only caches the `latest` release, so we don't need to update it for v1.3.x releases. Otherwise, it will open an invalid PR, like https://github.com/kubernetes-sigs/krew-index/pull/2809.
Fixes #
```release-note
NONE
```

Stop update krew for release 1.3.x

---

pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go

/kind feature
Choose a specific Kubernetes version for the control plane.
Fixes #
see https://github.com/karmada-io/karmada/pull/2541 https://github.com/karmada-io/karmada/pull/2655
TEST
```
./karmadactl init --private-image-registry=daocloud.io/atsctoo --kube-image-tag=v1.18.20 --crds=/root/karmada/crds.tar.gz
```
```release-note
`karmadactl`: Introduced `--kube-image-tag` flag to the `init` command to specify the Kubernetes image version.
```

introduce kube-image-tag flag to karmadactl init

---

pkg/util/overridemanager/labelannotationoverrider.go
pkg/util/overridemanager/labelannotationoverrider_test.go

/kind bug
Fixes #2965
```release-note
`karmada-controller-manager`: Fixed `LabelsOverrider` and `AnnotationsOverrider` failed to add new items issue in case of `label`/`annotation` is nil.
```

fix failed to apply Label/Annotation Overriders

---

pkg/util/overridemanager/labelannotationoverrider.go
pkg/util/overridemanager/labelannotationoverrider_test.go

Cherry pick of #2971 on release-1.4.
#2971: fix failed to apply Label/Annotation Overriders
```release-note
`karmada-controller-manager`: Fixed `LabelsOverrider` and `AnnotationsOverrider` failed to add new items issue in case of `label`/`annotation` is nil.
```

Automated cherry pick of #2971: fix failed to apply Label/Annotation Overriders

---

pkg/karmadactl/cmdinit/karmada/rbac.go

/kind bug
* Grant karmada-agent permission to acccess resourceinterpretercustomizations
Fixes #2982 
none
```release-note
`karmadactl init`: Grant karmada-agent permission to access resourceinterpretercustomizations.
```

Grant karmada-agent permission to access resourceinterpretercustomizations

---

pkg/karmadactl/cmdinit/karmada/rbac.go

Cherry pick of #2984 on release-1.4.
#2984: Grant karmada-agent permission to access resourceinterpretercustomizations
```release-note
`karmadactl init`: Grant karmada-agent permission to access resourceinterpretercustomizations.
```

Automated cherry pick of #2984: Grant karmada-agent permission to access resourceinterpretercustomizations

---

hack/local-up-karmada.sh
pkg/karmadactl/join/join.go

Signed-off-by: helen <haitao.zhang@daocloud.io>
/kind feature
The current context should be used instead of the clustername when the `--cluster-context` parameter is not set.
Fixes #
When I don't want to provide the`--cluster-context` parameter and encounter obstacles customizing the clustername, clustername become the `--cluster-context`, but I don't have such a context.
```release-note
`karmadactl`: The `--cluster-context` flag of `init` command now takes `current-context` by default.
```

Karmadactl join: default use current context

---

pkg/scheduler/core/spreadconstraint/group_clusters.go
pkg/scheduler/core/spreadconstraint/select_clusters.go
test/e2e/framework/cluster.go
test/e2e/spread_by_region_test.go

/kind bug
Spread by region always failed when replicaDivisionPreference is Weighted and WeightPrefrence is nil.
```
metadata:
spec:
name: nginx
placement:
clusterNames:
- member1
- member2
replicaDivisionPreference: Weighted
spreadConstraints:
- maxGroups: 1
minGroups: 1
spreadByField: region
- maxGroups: 1
minGroups: 1
spreadByField: cluster
```
```
status:
conditions:
- lastTransitionTime: "2022-12-20T03:49:13Z"
message: Failed to apply all works, see …
```

[bugfix]when replicaDivisionPreference is Weighted and WeightPreference is nil

---

pkg/util/namespace.go
pkg/util/namespace_test.go
pkg/util/serviceaccount.go
pkg/util/serviceaccount_test.go

/kind bug
Referring to #2981, sometimes the namespace is created in advance, to give less privilege to Karmada. So if we want to create resource, checking if it exists is necessary
Fixes #2981 
@lonelyCZ 
```release-note
`karmada-agent`: Check if the resource exists before creating it. Sometimes the resource is created in advance, to give less privilege to Karmada.
```

Check if the resource exists before creating it

---

pkg/util/namespace.go
pkg/util/namespace_test.go
pkg/util/serviceaccount.go
pkg/util/serviceaccount_test.go

Cherry pick of #2988 on release-1.4.
#2988: Check if the resource exists before creating it
```release-note
`karmada-agent`: Check if the resource exists before creating it. Sometimes the resource is created in advance, to give less privilege to Karmada.
```

Automated cherry pick of #2988: Check if the resource exists before creating it

---

pkg/resourceinterpreter/defaultinterpreter/replica.go
pkg/resourceinterpreter/defaultinterpreter/revisereplica.go
pkg/resourceinterpreter/defaultinterpreter/revisereplica_test.go

/kind feature
built-in interpreter support statefulset
Fixes #3007 
```release-note
`karmada-controller-manager`: built-in interpreter support statefulset
```

built-in interpreter support statefulset

---

pkg/search/controller.go
pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go

/kind bug
I have three cluster member1, member2, member3，member1 status is not ready
I did a few steps
step1 create a resourceregistries for all cluster 
step 2  kubectl get --raw /apis/search.karmada.io/v1alpha1/search/cache/api/v1/nodes --kubeconfig /etc/karmada/karmada-apiserver.config, but get nothing
error log in karmada-search
I think the not ready cluster should be filtered out
Fixes #
```release-note
karmada-search: filter out not ready clusters
```

search filter out not ready cluster

---

pkg/search/controller.go
pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go

Cherry pick of #3010 on release-1.3.
#3010: search filter out not ready cluster
```release-note
karmada-search: filter out not ready clusters
```

Automated cherry pick of #3010: search filter out not ready cluster

---

pkg/karmadactl/util/genericresource/builder.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
/kind cleanup
Comparing with `==` will fail on wrapped errors, use `errors.Is` to check for a specific error，select the unmodified part in the following way
```sh
➜  karmada git:(master) git grep 'err ==' | grep -v ^vendor | sed 's/.*err == \([^ :),;.]\+\).*/\1/g' | grep Err | grep -v "err == nil" | sort -u
pkg/karmadactl/util/genericresource/builder.go:         if err == filepath.ErrBadPattern {
```
Fixes #
```release-note
NONE
```

Check for err judgments by `==` and fix it

---

pkg/scheduler/scheduler.go

/kind cleanup
Refer to https://github.com/kubernetes/kubernetes/blob/release-1.26/pkg/scheduler/util/utils.go#L123-L125
Fixes #
```release-note
NONE
```

avoid calling apiserver when scheduling result has no changes

---

.github/workflows/ci.yml

/kind cleanup
Use the automatic token, so that the task(`Install Protoc`) can be run in the forked repo.
https://docs.github.com/en/actions/security-guides/automatic-token-authentication
```release-note
NONE
```

Update protoc setup token

---

charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/util/helper/policy.go
pkg/webhook/clusterpropagationpolicy/mutating.go
pkg/webhook/propagationpolicy/mutating.go

/kind bug
Validate replicaSchedulingType and replicaDivisionPreference
Fixes #3013
```release-note
`karmada-webhook`: Validate replicaSchedulingType and replicaDivisionPreference.
```

fix: Validate replicaSchedulingType and replicaDivisionPreference

---

pkg/search/proxy/store/multi_cluster_cache.go
pkg/search/proxy/store/resource_cache.go

/kind bug
When a member cluster is down, stopping the proxy cache for this cluster takes a few seconds(as below log, stop the pods cache takes 9s)
```
I0106 17:25:07.764975   62644 resource_cache.go:35] Stop store for yjh-1 /v1, Resource=pods
I0106 17:25:16.609796   62644 resource_cache.go:35] Stop store for yjh-1 /v1, Resource=nodes
```
During stopping, it hold the lock of `MultiClusterCache`. This results in client requests will be blocked. Because request handlers also need this lock:
https://github.com/karmada-io/karmada/blob/7b4c541bb818fb1e2677311aa34d8ff17b73d119/pkg/search/proxy/store/multi_cluster_cache.go#L162-L168 …

stop proxy cache asynchronously

---

pkg/karmadactl/interpret/edit.go
pkg/karmadactl/interpret/interpret.go
pkg/util/interpreter/rule.go

/kind feature
add edit mode for karmadactl interpreter command.
part of #2371
Prepare `customization.yml`
```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterCustomization
metadata:
creationTimestamp: null
name: get-replica
spec:
customizations:
replicaResource:
luaScript: |-
function GetReplicas(obj)
replica = obj.spec.replicas
requirement = {}
return replica, requirement
end
target:
```
```
karmadactl interpret -f customization.yml --edit
```
Will open a default editor:
```lua
-- Please edit the object below. Lines beginning with a '--' …
```

add edit mode for karmadactl interpreter command

---

pkg/search/proxy/store/multi_cluster_cache.go
pkg/search/proxy/store/resource_cache.go

Cherry pick of #3027 on release-1.4.
#3027: stop proxy cache asynchronously
```release-note
`karmada-search`: avoid proxy request block when member cluster down.
```

Automated cherry pick of #3027: stop proxy cache asynchronously

---

pkg/util/overridemanager/labelannotationoverrider.go
pkg/util/overridemanager/labelannotationoverrider_test.go
pkg/util/validation/validation.go
pkg/util/validation/validation_test.go

/kind bug
fix: OverridePolicy of labels/annotations with composed-labels
Fixes #3028 
```release-note
`karmada-controller-manager`: `labelsOverrider/annotationsOverrider` supports `composed-labels`, like testannotation/projectId: <label-value>.
```

fix: OverridePolicy of labels/annotations with composed-labels

---

pkg/util/overridemanager/labelannotationoverrider.go
pkg/util/overridemanager/labelannotationoverrider_test.go
pkg/util/validation/validation.go
pkg/util/validation/validation_test.go

Cherry pick of #3037 on release-1.4.
#3037: fix: OverridePolicy of labels/annotations with
```release-note
`karmada-controller-manager`: `labelsOverrider/annotationsOverrider` supports `composed-labels`, like testannotation/projectId: <label-value>.
```

Automated cherry pick of #3037: fix: OverridePolicy of labels/annotations with

---

cmd/webhook/app/options/options.go

/kind flake
/kind cleanup
fix wrong note for the --metrics-bind-address .

fix wrong note for webhook --metrics-bind-address

---

pkg/sharedcli/profileflag/profileflag.go

/kind cleanup
fix typo note for pkg/sharedcli/profileflag/profileflag.go

fix typo note for pkg/sharedcli/profileflag/profileflag.go

---

examples/customresourceinterpreter/webhook-configuration.yaml
examples/customresourceinterpreter/webhook/app/workloadwebhook.go
pkg/webhook/configuration/validating.go
test/e2e/resourceinterpreter_test.go
test/helper/resource.go

Cherry pick of #3052 on release-1.4.
#3052: fix that the InterpretDependency operation is absent in the
```release-note
karmada-webhook: Fixed the issue that the InterpretDependency operation can't be registered.
```

Automated cherry pick of #3052: fix that the InterpretDependency operation is absent in the

---

cmd/agent/app/options/options.go
cmd/controller-manager/app/options/options.go

Signed-off-by: zhuzhenghao <zhenghao.zhu@daocloud.io>
/kind cleanup
Update wrong usage for flag --metrics-bind-address
Fixes #3072
```release-note
NONE
```

Update wrong usage for flag --metrics-bind-address

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
cmd/scheduler/app/options/options.go
cmd/scheduler/app/scheduler.go
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/apis/work/v1alpha2/binding_types.go
pkg/detector/detector.go
pkg/generated/openapi/zz_generated.openapi.go
pkg/scheduler/event_handler.go
pkg/scheduler/scheduler.go

/kind feature
Karmada ships with a default scheduler. If the default scheduler does not suit users' needs, it's recommended to implement their own scheduler. Now pp has schedulerName field but Karmada has not fully adopted it.
```
// SchedulerName represents which scheduler to proceed the scheduling.
// If specified, the policy will be dispatched by specified scheduler.
// If not specified, the policy will be dispatched by default scheduler.
// +optional
SchedulerName string `json:"schedulerName,omitempty"`
```
Fixes #279 
Part of #3024 
None …

Support multiple schedulers

---

pkg/util/annotation.go
pkg/util/annotation_test.go
pkg/util/label.go
pkg/util/label_test.go
pkg/util/objectwatcher/objectwatcher.go

/kind feature
Fixes #2896 
```release-note
`karmada-controller-manager`:  Retain the labels added to resources by member clusters
```

feat: Retain the labels added to resources by member clusters

---

cmd/scheduler/app/options/validation.go
cmd/scheduler/app/options/validation_test.go
pkg/webhook/clusterpropagationpolicy/validating.go
pkg/webhook/propagationpolicy/validating.go

/kind feature
Add validation for `--scheduler-name` option in `karmada-scheduler` and `schedulerName` field in policy.
Part of #3024 
None

Add schedulerName validation

---

pkg/search/proxy/framework/plugins/cluster/cluster.go

Cherry pick of #3098 on release-1.4.
#3098: support pod subresource (attach, exec, port-forward) through
```release-note
`karmada-search`: support pod subresource (attach, exec, port-forward) through global proxy
```

Automated cherry pick of #3098: support pod subresource (attach, exec, port-forward) through

---

cmd/agent/app/options/options.go
cmd/controller-manager/app/options/options.go
cmd/webhook/app/options/options.go

/kind cleanup
For components `karmada-controller-manager`, `karmada-agent`, `karmada-webhook`, we can disabling metrics by seting `metrics-bind-address` to the `0` value. So I add the statement in the flag usage.
Fixes #
```cmd
--metrics-bind-address string                   The TCP address that the controller should bind to for serving prometheus metrics(e.g. 127.0.0.1:8080, :8080). It can be set to "0" to disable the metrics serving. (default ":8080")
```
```release-note
NONE
```

Added the statement for disabling metrics

---

charts/karmada/templates/karmada-search.yaml

/kind feature
Fixes https://github.com/karmada-io/karmada/issues/3119
```release-note
Chart: karmada-search install support specify external etcd
```

karmada-search install by helm support specify external etcd

---

pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go

/kind cleanup
When the Pod has just been delivered and the status has not been received, aggregateStatusItems will be empty.
It will print "SHOULD-NEVER-HAPPEN, maybe Pod added a new state that Karmada don't know about." log which may confuse users.
Fixes #
None

Fix aggregate pod status when aggregateStatusItems are empty

---

pkg/detector/detector.go
pkg/detector/policy.go
test/e2e/clusterpropagationpolicy_test.go
test/e2e/framework/clusterpropagationpolicy.go
test/e2e/propagationpolicy_test.go

/kind feature
Now detector will reconcile only when pp's resourceSelector changes. So when other fields updates, resourceBindings will not synchronize this update of the policy.
For example, if you have propagated a policy(which propagateDeps's false) and deployment, now you want to update policy's propagateDeps to true. However, resourceBinding will not update this field after policy has changed.
It will also be an issue when we add `placement` to resourceBinding #2702.
The main reason is that detector will get obj from `waitingObjects` queue, then add it to the workqueue for reconciling. However, in the above case, the binding relationship of the object will not change, …

Detector watch pp fields changed other than resource selector

---

pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go

/kind feature
We need to count the number of running jobs.
Fixes #
```release-note
`karmada-controller-manager`: default interpreter supports cronJob aggregate status.
```

feat: default interpreter supports cronJob aggregate status

---

pkg/registry/cluster/strategy_test.go

Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
/kind cleanup
Change will never happen wrong unit tests, from the function implementation, the need to focus only on `corev1. TaintEffectNoExecute` types of `timeAdd` isn't empty
```golang
// MutateClusterTaints add TimeAdded field for cluster NoExecute taints only if TimeAdded not set.
func MutateClusterTaints(taints []corev1.Taint) {
for i := range taints {
if taints[i].Effect == corev1.TaintEffectNoExecute && taints[i].TimeAdded == nil {
now := metav1.Now()
taints[i].TimeAdded = &now
}
}
}
```
Fixes #
```release-note
NONE
```

Modify unit tests that never fail

---

.github/workflows/ci.yml
.github/workflows/lint-chart.yaml
hack/create-cluster.sh
hack/local-up-karmada.sh

/kind cleanup
The default kind version is too old now when using the latest `kubectl` it rise a warning, like:
```
WARNING: version difference between client (1.26) and server (1.23) exceeds the supported minor version skew of +/-1
```
This PR also adds Kubernetes `v1.26.0` to the E2E matrix.
Fixes #
1. I leave the [Kubernetes compatibility](https://github.com/karmada-io/karmada#kubernetes-compatibility) un-updated because we need to explain more about the compatibility and it is tracked by #2757.
2. We now got 6 Kubernetes versions in E2E matrix, we can't afford all versions, we need the rule to get rid of the burden. (no idea about that yet)
**Does …

Update default kind version and testing against v1.26.0

---

pkg/apis/work/v1alpha2/well_known_constants.go
pkg/util/annotation.go
pkg/util/annotation_test.go
pkg/util/helper/work.go
pkg/util/label.go
pkg/util/label_test.go
pkg/util/objectwatcher/objectwatcher.go

/kind feature
Fixes #2558
Fixes #1991
```release-note
`karmada-controller-manager`: support for removing annotations/labels propagated through karmada.
```

feat: support for removing annotations/labels propagated through karmada

---

artifacts/kindClusterConfig/general-config.yaml
hack/create-cluster.sh

/kind bug
The cluster fails to be created using the `hack/create-cluster.sh` script, and the installation of the weave fails because the installation address of the weave is changed. We installed the weave to use the submarier, but now the submarier does not use the weave. For details, see [here](https://github.com/submariner-io/shipyard/issues/858). Therefore, we also modify the weave accordingly.
Fixes #
```release-note
NONE
```

[bug-fix] update clueter-cluster shell

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
pkg/apis/work/v1alpha2/binding_types.go
pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
pkg/detector/detector.go
pkg/generated/openapi/zz_generated.openapi.go
pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/event_handler.go
pkg/scheduler/scheduler.go
test/e2e/clusterpropagationpolicy_test.go
test/e2e/propagationpolicy_test.go

Add placement for BindingSpec can reduce the dependency of policy and make API more clear. Now the component above will check the placement of bindingSpec first and switch to get placement by label if placement of bindSpec is empty.
It can be smoothly upgraded from a lower version to a higher version. If karmada-controller-manager upgrades, spec.placement will occur according to the placement of policy.
Upgrade path: upgrade crd --> upgrade karmada-controller-manager --> upgrade karmada-scheduler.
Fixes #
None

Add placement for bindingSpec

---

pkg/controllers/cluster/cluster_controller.go

/kind cleanup
In the previous version, we added the code for collecting clusterIDs to consider upgrade compatibility, now this logic can be removed.
Fixes #
```release-note
NONE
```

remove code for collecting clusterID under upgrading

---

pkg/karmadactl/util/bootstraptoken/bootstraptoken.go

/kind bug
Currently, the `karmadactl init` could not run correctly.
```
I0215 13:34:36.991956   23895 deploy.go:126] Initialize karmada bootstrap token
I0215 13:34:36.992119   23895 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: karmadactl/v0.0.0 (linux/amd64) kubernetes/$Format" 'https://10.10.103.67:32443/api/v1/namespaces/kube-system/secrets/bootstrap-token-2yhtwh'
I0215 13:34:36.995824   23895 round_trippers.go:553] GET https://10.10.103.67:32443/api/v1/namespaces/kube-system/secrets/bootstrap-token-2yhtwh 404 Not Found in 3 milliseconds
I0215 13:34:36.995866   23895 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 3 ms Duration 3 ms
I0215 …
```

Fix UpdateOrCreateToken get secrets err handling optimization

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
pkg/apis/work/v1alpha2/binding_types.go
pkg/generated/openapi/zz_generated.openapi.go

This PR added a `SchedulerObservedAffinityName` to ResourceBinding and ClusterResourceBinding according to [multiple scheduling group proposal](#3126).
Fixes #
```release-note
NONE
```

Add SchedulerObservedAffinityName to RB/CRB

---

pkg/util/names/names.go
pkg/util/names/names_test.go

Use `/` as the delimiter for  `GenerateBindingReferenceKey` function
In the following case, the key is not unique:
```go
left := names.GenerateBindingReferenceKey("a","b-c") 
right := names.GenerateBindingReferenceKey("a-b","c") 
```
Fixes https://github.com/karmada-io/karmada/issues/3143
```release-note
`karmada-controller-manager`: Make the result unique for `GenerateBindingReferenceKey` function.
```

Make the result unique for GenerateBindingReferenceKey function

---

pkg/util/names/names.go
pkg/util/names/names_test.go

/kind bug
The name of some resources like `ClusterRole` can contain uppercase characters, but the work object’s name follows the DNS domain name constraint, that is, it cannot contain uppercase characters, refer to `https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names`. I happened to encounter this problem in my environment, so I submitted this PR.
`Create ClusterRole`
`Create Work`
Fixes #
fix the bug that the work object may contain uppercase characters
```release-note
NONE
```

fix the bug that the work object may contain uppercase characters

---

pkg/util/names/names.go
pkg/util/names/names_test.go

Cherry pick of #3201 on release-1.2.
#3201: fix the bug that the work object may contain uppercase
```release-note
`karmada-controller-manager`: Fixed the issue that RBAC resources whose name contains uppercase characters can not be propagated.
```

Automated cherry pick of #3201: fix the bug that the work object may contain uppercase

---

pkg/dependenciesdistributor/dependencies_distributor.go
pkg/resourceinterpreter/defaultinterpreter/dependencies_test.go
test/e2e/dependenciesdistributor_test.go
test/e2e/framework/deployment.go
test/e2e/framework/rbac.go
test/e2e/suite_test.go
test/helper/resource.go

Cherry pick of #2524 on release-1.3.
#2524: propagate dependencies support propagate sa
```release-note
karmada-controller-manager: Fix the problem that ServiceAccount can be interpreted as a dependency, but may not be delivered
```

Automated cherry pick of #2524: propagate dependencies support propagate sa

---

pkg/util/validation/validation.go
pkg/util/validation/validation_test.go

/kind feature
/kind cleanup
fix bug that spreadconstraints are not validated correctly
Fixes #3231
```release-note
`karmada-webhook`: Introduced validation to ensure the `.spec.placement.spreadConstraints.maxGroups/minGroups` in PropagationPolicy is declared with a reasonable value.
```

fix bug that spreadconstraints are not validated correctly

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/generated/openapi/zz_generated.openapi.go

/kind cleanup
This PR updates the comments of [target cluster field](https://github.com/karmada-io/karmada/blob/eb569ff9b6d05413f10743236a30c30e4d7d8897/pkg/apis/policy/v1alpha1/override_types.go#L73) to explain the restrictions of field selector.
Fixes #3188
The comments is also suitable for `PropagationPolicy`.
```release-note
NONE
```

Add more comments about filed selector in cluster affinity

---

.github/workflows/ci.yml

/kind cleanup
To reduce the consumption of test resources, we can reduce the number of Kubernetes version support in CI E2E in the current CI Workflow.
We plan to change the supported versions to the latest three minor releases of Kubernetes, this can be considered to be roughly the same as the `End of Life` of the [Kubernetes release](https://kubernetes.io/releases/).
Part of #3235 
```release-note
NONE
```

reduce the number of kubernetes version support in CI E2E

---

.github/workflows/release.yml

/kind cleanup
Since [krew ](https://github.com/kubernetes-sigs/krew) only caches the `latest` release, so we don't need to update it for v1.4.x releases. Otherwise, it will open an invalid PR, like https://github.com/kubernetes-sigs/krew-index/pull/2809.
Fixes #
```release-note
NONE
```

Stop update krew for release 1.4.x

---

pkg/registry/cluster/strategy.go
pkg/registry/cluster/strategy_test.go
pkg/scheduler/event_handler.go

/kind feature
We should set the `generation` field of the Cluster object. When the `spec` part of the Cluster object changes, the `generation` value should increase. Its value begins with 1.
Fixes #
Do we need to pay attention to the changes in labels and annotations of the Cluster object?
```release-note
`karmada-aggregated-apiserver`: Increase `.metadata.generation` once desired state of the `Cluster` object is changed.
```

Increase `.metadata.generation` once desired state of the `Cluster` object is changed.

---

pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go

/kind feature
Fixes #3247
```release-note
`karmadactl` and `karmada-controller-mamager`: Add a lua string lib to the resource interpreter.
```

feat: Add a lua string and math lib to the resource interpreter.

---

charts/karmada/templates/karmada-controller-manager.yaml
charts/karmada/templates/kube-controller-manager.yaml
charts/karmada/values.yaml

/kind cleanup
Re-check pr fix. 
And i found there is a duplicate define for the controllers.
[https://github.com/karmada-io/karmada/pull/3240](https://github.com/karmada-io/karmada/pull/3240#issuecomment-1461610806)
Fixes #
```release-note
```

Add controllers config for karmada-controller-manager

---

pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go
pkg/karmadactl/cmdinit/kubernetes/statefulset.go

/kind feature
In a production environment, registry  are generally non-public. If the registry we get from the administrator is private, we need to configure the imagepullsecret in the application's yaml file.
So I think it would be better if `karmadactl init` could specify imagepullsecret.
Fixes #
```release-note
karmadactl: Add image pull secret flags for `karmadactl init`
```

karmadactl: add image pull secret flags for karmadactl init

---

pkg/detector/detector.go

/kind bug  
Merge labels in (cluster)resourcebinding when the binding is modifying no matter which kind of propagationpolicy is bind with.
Fixes #3238 
```release-note
`karmada-controller-manager`: Fixed the issue that RB/CRB labels are not merged when syncing new changes. 
```

merge labels when building RB/CRB by ClusterPropagationPolicy

---

charts/karmada/templates/karmada-controller-manager.yaml
charts/karmada/templates/karmada-descheduler.yaml
charts/karmada/templates/karmada-scheduler.yaml

/kind bug
When Using the latest version chart to install karmada, the logger will  throw following error:
```
[root@master ~]# kubectl logs -n  e2etest-instancedefaultiqo-lpl6b --tail 10  karmada-e2etest-instancedefaultiqo-scheduler-864855df46-8rhqb
E0313 03:26:44.609404       1 leaderelection.go:334] error initially creating leader election record: namespaces "e2etest-instancedefaultiqo-lpl6b" not found
E0313 03:26:48.721652       1 leaderelection.go:334] error initially creating leader election record: namespaces "e2etest-instancedefaultiqo-lpl6b" not found
E0313 03:26:51.725115       1 leaderelection.go:334] error initially creating leader election record: namespaces "e2etest-instancedefaultiqo-lpl6b" not found
E0313 …
```

fixed karmada controller flag

---

hack/verify-staticcheck.sh

/kind cleanup
This PR updates the way we setup golangci-lint, it will improve the efficiency.
`go install`/`go get` installation isn't recommended according to [golangci-lint documents](https://golangci-lint.run/usage/install/#install-from-source), one of the reasons is `it's slower than binary installation`.
Fixes #
Before the patch:
```bash
-bash-5.0# time hack/verify-staticcheck.sh 
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0
Congratulations!  All Go source files have passed staticcheck.
real	4m55.925s
user	13m54.114s
sys	1m19.474s
```
After this patch:
```bash
-bash-5.0# time hack/verify-staticcheck.sh 
Installing …
```

Install golangci-lint binary instead of from source

---

pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go

Cherry pick of #3256 on release-1.5.
#3256: feat: add string and math lib for lua
```release-note
`karmadactl`, `karmada-controller-mamager` and karmada-agent : Add a lua `string` and `math` lib to the resource interpreter.
```

Automated cherry pick of #3256: feat: add string and math lib for lua

---

pkg/controllers/unifiedauth/unified_auth_controller.go
pkg/controllers/unifiedauth/unified_auth_controller_test.go
pkg/util/rbac.go

/kind feature
We can [Proxy Global Resources](https://karmada.io/docs/next/userguide/globalview/proxy-global-resource/) through the `karmada-apiserver`. However, the `search/proxying` does not provide the unified authentication capability like the [cluster/proxy](Unified Authentication), as stated in #3176. 
The current pr supplements this capability.
Fixes #3176 
```release-note
`karmada-search`: implementing search proxy unifiedauth
```

implementing search proxy unifiedauth

---

pkg/util/fedinformer/keys/keys.go
pkg/util/fedinformer/keys/keys_test.go

/kind cleanup
When using a typed client, decoding to a versioned struct (not an internal API type), the apiVersion/kind information will be dropped. Therefore, the APIVersion/Kind information of runtime.Object needs to be verified.
See issue: https://github.com/kubernetes/kubernetes/issues/80609
Fixes #3275
@RainbowMango @whitewindmills 
```
NONE
```

bugfix: runtime.Object apiVersion/kind is empty 

---

.github/workflows/cli.yaml
artifacts/kindClusterConfig/general-config.yaml
hack/cli-testing-environment.sh

/kind cleanup
Now it lacks e2e for karmadactl init, so let's add it.
Fixes #3162
none
```release-note
```

Add e2e for karmadactl init

---

pkg/karmadactl/addons/disable.go
pkg/karmadactl/addons/enable.go

/kind bug
There were no options viewing by -h, but we need them.
```
[root@master67 karmada]# karmadactl addons enable -h
Enable Karmada addons from Kubernetes
Examples:
karmadactl addons enable all
......
karmadactl addons enable karmada-search --namespace karmada-system
Usage:
karmadactl addons enable [options]
Use "karmadactl options" for a list of global command-line options (applies to all commands).
```
Fixed it as shown below
```
[root@master67 karmada]# _output/bin/linux/amd64/karmadactl addons enable -h
Enable Karmada addons from Kubernetes
Examples:
karmadactl addons enable all
......
karmadactl addons enable karmada-search --namespace karmada-system
Options:
--apiservice-timeout=30:
Wait apiservice ready …
```

Fixed unable to view the options for karmadactl addons enable/disable

---

test/e2e/scheduling_test.go

Fix trigger rescheduling when replicaSchedulingType is duplicated.
Fixes #3302 
None

[e2e] Fix trigger rescheduling when replicaSchedulingType is duplicated

---

pkg/karmadactl/addons/disable.go
pkg/karmadactl/addons/enable.go

Cherry pick of #3298 on release-1.4.
#3298: Fixed unable to view the options for karmadactl addons
```release-note
karmadactl: fixed unable to view the options of `karmadactl addons enable/disable`.
```

Automated cherry pick of #3298: Fixed unable to view the options for karmadactl addons

---

pkg/controllers/status/cluster_status_controller.go

/kind cleanup
There is no need to call setTransitionTime before calling the SetStatusCondition method. From the code logic, call setTransitionTime is not required.
https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/cluster_status_controller.go#L180 and https://github.com/karmada-io/karmada/blob/master/pkg/controllers/status/cluster_status_controller.go#L205
Fixes #https://github.com/karmada-io/karmada/issues/3313
@XiShanYongYe-Chang 
```
NONE
```

Fix: remove the setTransitionTime from cluster status controller.

---

pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go

/kind cleanup
Cluster_locality can work normally for placement without replicaSchedulingStrategy.
~~Do not fill replicas in bindings when replicaScheduling is duplicated. Keep the schedule behavior consistent with replicaScheduling is nil.~~
Fixes #3289 
None

Fix cluster_locality plugin when replicaScheduling is nil

---

pkg/registry/search/storage/cache.go
pkg/registry/search/storage/search.go
pkg/search/apiserver.go

/kind feature
response actual resource list, then client code like `client-go` can decode response body into object corresponding to pre defined api type.
Fixes #3311
```release-note
`karmada-search`: response actual resource list from search api
```

response actual resource list from search api

---

hack/create-cluster.sh

/kind cleanup
Fixes #392
Run successfully:
```bash
> hack/create-cluster.sh host ~/.kube/karmada.config
Creating cluster "host" ...
Context "kind-host" renamed to "host".
Cluster "kind-host" set.
cluster "host" is created successfully!
You can now use your cluster with:
kubectl cluster-info --context host --kubeconfig /home/yjh/.kube/karmada.config
```
When `kind` run failed:
```
> hack/create-cluster.sh host ~/.kube/karmada.config
Creating cluster "host" ...
Creating cluster host failed, see detail log in /tmp/tmp.EfC6i2XMNN-kind.log.
```
```release-note
`hack`: correct context name in …
```

correct context name.

---

cmd/aggregated-apiserver/OWNERS
pkg/aggregatedapiserver/OWNERS
pkg/registry/OWNERS

/kind cleanup
This PR set the owners of [karmada-aggregated-apiserver](https://github.com/karmada-io/karmada/tree/master/cmd) as well as relevant package([registry](https://github.com/karmada-io/karmada/tree/master/pkg/registry)).
@XiShanYongYe-Chang leads the effort for this component, he should be on the owner list for faster iterations.
Fixes #
```release-note
NONE
```

Set aggregatedapiserver owners

---

pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
pkg/karmadactl/cmdinit/kubernetes/statefulset_test.go

Add UT for deploy.go and statefulset.go

---

hack/cli-testing-environment.sh
hack/util.sh

The CLI test workflow may fail intermittently due to node taints. For instance, refer to this example: https://github.com/karmada-io/karmada/actions/runs/4497846194/jobs/7913834536.
```
Start init karmada control plane...
I0323 06:57:27.213231   17694 deploy.go:176] kubeconfig file: /home/runner/.kube/karmada-host.config, kubernetes: https://172.18.0.3:6443/
error: failed to find a healthy node for karmada-etcd
```
And I checked when the node is ready, there are still taints:
node.kubernetes.io/not-ready:NoExecute
```json
[
{
"MemoryPressure":false,
"LastHeartbeatTime":"2023-03-23 02:23:39 +0000 UTC",
"LastTransitionTime":"2023-03-23 02:23:17 +0000 UTC",
"Reason":"KubeletHasSufficientMemory", …
```

Fix potential failure in CLI workflow.

---

pkg/karmadactl/util/apiclient/apiclient.go

/kind feature
Support to run karmadactl init within a pod by InClusterConfig.
Fixes #3335 
```release-note
karmadactl: support to run karmadactl init within a pod
```

Support to run karmadactl init within a pod

---

pkg/karmadactl/addons/enable.go
pkg/karmadactl/addons/init/enable_option.go
pkg/karmadactl/addons/search/manifests.go
pkg/karmadactl/addons/search/search.go
pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go
pkg/karmadactl/cmdinit/kubernetes/statefulset.go
pkg/karmadactl/options/global.go

/kind bug
Because currently, kubectl-karmada hardcoded cluster domain to `cluster.local`, it faild init control plane in a host cluster has cluster domain other than `cluster.local`
Fixes #3291
```release-note
`karmadactl`: Introduced `--host-cluster-domain` flag to command `init` and `addons` to specify the host cluster domain.
```

Add arg to specify cluster domain

---

pkg/controllers/status/cluster_condition_cache_test.go
pkg/karmadactl/cmdinit/kubernetes/deploy_test.go

/kind cleanup
Part of #3327 
NONE

Add UT for deploy.go

---

pkg/scheduler/event_handler.go
pkg/scheduler/scheduler_metrics_test.go

/kind cleanup
Currently, in our scheduler, there are many useless scheduling attempts, which may waste the performance of karmada-scheduler.
At first, I think it's due to the resourceVersion of the resource the resourceBinding is bound to. When status of resource templates is updated, the resourceVersion of this is updated which may cause the resourceBinding updated. When strategy is duplicated, it will always do a scheduling attempts. After I checked the code of detector, I found it's wrong.
```
func (d *ResourceDetector) OnUpdate(oldObj, newObj interface{}) {
unstructuredOldObj, err := helper.ToUnstructured(oldObj)
if err != nil {
klog.Errorf("Failed to transform oldObj, error: %v", err)
return
}
unstructuredNewObj, …
```

[Performance] Do not schedule when status/metadata of binding update

---

pkg/util/helper/workstatus.go

/kind cleanup
When the binding status is collected from the work, we check whether the binding status changes to reduce the number of updated. However, the result is always false when the status pointer is compared with bindingStatus, so we need to change the pointer to the struce.
Fixes #
```release-note
NONE
```

fix an issue where DeepEqual becomes invalid in aggregate binding status

---

pkg/karmadactl/addons/descheduler/descheduler.go
pkg/karmadactl/addons/enable.go
pkg/karmadactl/addons/estimator/estimator.go
pkg/karmadactl/addons/init/enable_option.go
pkg/karmadactl/addons/search/search.go

/kind feature
If we use 'karmadactl addons init' to enable multiple addons, it is a good experience to specify a global image repository for all images.
Fixes #
```release-note
`karmadactl`:  Support specify global image registry for enable addons.
```

Support specify global image registry for enable addons

---

pkg/karmadactl/deinit/deinit.go

/kind feature
Fixes #
`karmadactl deinit` will delete the namespace where karmda components are located. 
In some cases, this processing is too rough, which may delete other resources created by the user under the namespace (the user does not want to be cleaned up together), such as imagepullsecret, Qos settings, etc. 
If the user is given the opportunity to choose whether to clean up the entire namespace, it will have a better experience.
```release-note
karmadactl: Add `--purge-namespace` flags for `karmadactl deinit`.
```

feat: add --purge-namespace flags for `karmadactl deinit`, and default not delete namespace

---

pkg/util/validation/validation.go
pkg/util/validation/validation_test.go

/kind bug
Multiple same spread constraints should not be allowed.
Fixes #3356
```release-note
NONE
```

fix that multiple same spread constraints are allowed

---

pkg/util/fedinformer/genericmanager/multi-cluster-manager.go
pkg/util/fedinformer/genericmanager/single-cluster-manager.go
pkg/util/fedinformer/typedmanager/multi-cluster-manager.go
pkg/util/fedinformer/typedmanager/single-cluster-manager.go

Signed-off-by: wulixuan <wulixuan@bilibili.com>
/kind cleanup
Avoid multiple executions after rlock in concurrent scenarios
Fixes #3122
NONE
```release-note
NONE
```

Avoid multiple executions after rlock in concurrent scenarios

---

pkg/scheduler/scheduler.go
pkg/util/helper/patch.go
pkg/util/helper/patch_test.go

/kind cleanup
We should use patch helper instead of `jsonpatch`, it's reusable code for easy maintenance.
Fixes #
```release-note
NONE
```

use patch helper instead of jsonpatch

---

pkg/scheduler/core/assignment.go
pkg/scheduler/core/assignment_test.go
pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/scheduler.go

/kind cleanup
1. Unify the `assignReplicas` function when `placement.ReplicaSchedulingType()` is equal to `Duplicated`.
2. Refactor some codes to make it clearer.
Fixes #
None

Unify the assign replicas when duplicated

---

pkg/resourceinterpreter/default/thirdparty/manager.go
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/embed.go
pkg/resourceinterpreter/default/thirdparty/thirdparty.go
pkg/resourceinterpreter/interpreter.go

/kind feature
Predefine ConfigurableInterpreter for some well-known third-party projects.
Fixes #
```release-note
Predefine ConfigurableInterpreter for some well-known third-party projects.
```

feat: predefined configurableInterpreter

---

pkg/search/proxy/store/multi_cluster_cache.go
pkg/search/proxy/store/util.go

Cherry pick of #3376 on release-1.5.
#3376: if start many watcher to watch pod. pod resourceVersion will
```release-note
karmada-search: fix the problem that ResourceVersion base64 encrypted repeatedly when starting multiple informer to watch resource
```

Automated cherry pick of #3376: if start many watcher to watch pod. pod resourceVersion will

---

pkg/resourceinterpreter/default/thirdparty/OWNERS

/kind cleanup
This PR nominates @chaunceyjiang and @Poor12 as the owner of thirdparty resource interpreters.
@chaunceyjiang and @Poor12 as the mentor will work with @yike21 [on the LFX program](https://github.com/karmada-io/karmada/issues/3331).
Fixes #
```release-note
NONE
```
cc @chaunceyjiang @Poor12 
/assign @XiShanYongYe-Chang

Setup interpreter owners

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/desired-cloneset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/observed-cloneset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/status-file.yaml

/kind cleanup
Add third-party resources `apps.krusie.io/v1alpha1/CloneSet` into Resource Interpreter framework.
Part of #3331
@Poor12 
NONE
```release-note
This is the first resourceinterpretercustomization for krusie.
Maybe it's useful to add a function `getDependenciesFromPodTemplate` in `pkg\resourceinterpreter\configurableinterpreter\luavm\kube.go`.
The directory for those customizatons is pending.
```

Add customizations for apps.krusie.io/v1alpha1/CloneSet

---

operator/pkg/init.go
operator/pkg/tasks/init/apiserver.go
operator/pkg/tasks/init/etcd.go
operator/pkg/tasks/init/wait.go

/kind feature
I found ETCD, karmada apiserver and karmada aggregated apiserver have dependencies,  Their startup order should be：
etcd -> karmada apiserver -> karmada aggregated apiserver.
The karmada aggregated apiserver restart twice：
Fixes #
```release-note
NONE
```

karmada operator: optimize karmada aggregated apiserver startup

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/desired-statefulset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/observed-statefulset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/status-file.yaml

/kind cleanup
Add third-party resources `apps.krusie.io/v1beta1/StatefulSet` into Resource Interpreter framework.
According to [Note](https://openkruise.io/docs/user-manuals/advancedstatefulset), we can find that since Kruise v0.7.0, Advanced StatefulSet has been promoted to v1beta1, which is compatible with v1alpha1.
Part of #3331 
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `apps.krusie.io/v1beta1/StatefulSet`
```

add customizations for apps.krusie.io/v1beta1/StatefulSet

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/desired-daemonset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/observed-daemonset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/status-file.yaml

/kind cleanup
Add third-party resources `apps.krusie.io/v1alpha1/DaemonSet`  into Resource Interpreter framework.
Part of #3331 
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `apps.krusie.io/v1alpha1/DaemonSet`
```

add customizations for apps.krusie.io/v1alpha1/DaemonSet

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CronJob/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CronJob/testdata/desired-acj-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CronJob/testdata/observed-acj-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CronJob/testdata/status-file.yaml

/kind cleanup
Add third-party resources `apps.krusie.io/v1alpha1/AdvancedCronJob` into Resource Interpreter framework.
Part of #3331
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `apps.krusie.io/v1alpha1/AdvancedCronJob`
```

add customizations for apps.krusie.io/v1alpha1/AdvancedCronJob

---

charts/karmada/values.yaml

agent.tolerations in  values.yaml is a slice not a object.
In document: [https://github.com/karmada-io/karmada/blob/master/charts/karmada/README.md?plain=1#L254](https://github.com/karmada-io/karmada/blob/master/charts/karmada/README.md?plain=1#L254)
In most time, we change values.yaml to set value; but sometimes we use helm `--set-json` flags and will fail.
```shell
helm install xxx  --set-json 'agent={"tolerations":[{"effect":"NoSchedule","key":"node-role.kubernetes.io/master","operator":"Exists"}]}'
coalesce.go:220: warning: cannot overwrite table with non table for karmada.agent.tolerations (map[])
```
Fixes agent.tolerations type
**Does this PR …

fix(chart): fix agent.tolerations type

---

examples/karmadactlinterpret/README.md
examples/karmadactlinterpret/resourceinterpretercustomization.yaml

If the documents are updated, users can more easily find the `karmadactl interpret --operation ReviseReplica` section.
And it updates the example resourceinterpretercustomization with kube lib for building `dependencyInterpretation` lua.
Part of #3401 
NONE
```release-note
```

add an example for examples/karmadactlinterpret/README.md

---

pkg/util/overridemanager/commandargsoverride.go

/kind feature
CommandArgsOverrider supports Job
Fixes #
https://github.com/karmada-io/karmada/blob/4ed701069db31fda8f0ce898b3a5c2ad7d7423b1/pkg/util/overridemanager/imageoverride.go#L66-L71
Consistent with imageOverride.
```release-note
`karmada-controller-manager`:  CommandsOverrider and ArgOverride supports Job
```

feat: CommandArgsOverrider supports Job

---

pkg/scheduler/scheduler.go

/kind bug
Fixes #3361
```release-note
karmada-scheduler: Fixed unexpected re-scheduling due to mutating informer cache issue.
```

Avoid accidental impact for WeightPreference on the cache

---

pkg/scheduler/scheduler.go

Cherry pick of #3393 on release-1.5.
#3393: Avoid accidental impact for rb/crb's pointer on the cache
```release-note
karmada-scheduler: Fixed unexpected re-scheduling due to mutating informer cache issue.
```

Automated cherry pick of #3393: Avoid accidental impact for rb/crb's pointer on the cache

---

cmd/controller-manager/app/controllermanager.go
cmd/controller-manager/app/options/options.go
cmd/controller-manager/app/options/validation.go
pkg/controllers/context/context.go
pkg/controllers/namespace/namespace_sync_controller.go
pkg/detector/detector.go
pkg/detector/detector_test.go

/kind feature
Allows user settings to skip namespace propagation with specific prefixes/suffixes.
Like:   openshift-xxxxxx
Fixes #
```release-note
`karmada-controller-manager`: Allows setting wildcards for SkippedPropagatingNamespaces.
```

feat: Allows setting wildcards for SkippedPropagatingNamespaces

---

.github/workflows/ci-schedule-compatibility.yaml

/kind feature
Users may be confused about which version of kube-apiserver/kube-controller-manager to select for Karmada due to compatibility issues.  
This schedule workflow aims to determine the compatibility matrix.
Fixes #none
The testing result in my repo: https://github.com/jwcesign/karmada-demo/actions/runs/4518157931/jobs/7957840115
There are the following problems:
* If the e2e fails in v1.2.0 due to a deleted image reference,  how do we fix the failure?
```release-note
```

Add a workflow for conducting compatibility testing.

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/generated/openapi/zz_generated.openapi.go
pkg/util/validation/validation.go
pkg/util/validation/validation_test.go

/kind cleanup
Add validation for Failover. `TolerationSeconds`, `DelaySeconds` and `BlockPredecessorSeconds` cannot < 0.
Fixes #
None

Add validation for failover

---

cmd/controller-manager/app/options/options.go
pkg/util/names/names.go
pkg/util/names/names_test.go

/kind feature
allows users to propagate resources under the Kubernetes reserved namespace.
Fixes #3369 
```release-note
`karmada-controller-manager`: The `--skipped-propagating-namespaces` flags now can take regular expressions to represent namespaces and defaults to `kube-*`.
```

feat: allows users to propagate resources under the Kubernetes reserved namespace.

---

pkg/search/proxy/store/multi_cluster_cache.go
pkg/search/proxy/store/multi_cluster_cache_test.go
pkg/search/proxy/store/util.go
pkg/search/proxy/store/util_test.go

/kind bug
When paging query via karmada search proxy, if member cluster resources number is larger than page size (`limit`), the return `resourceVersion` and `continue` is not incorrect.
For example, there are two member clusters:
|    | Cluster1 | Cluster2 |
|--------|--------|--------|
| RV       | 123 | 456 |
| Pods   | 10 | 10 |
And client request with:
```
/apis/search.karmada.io/v1alpha1/proxying/karmada/proxy/api/v1/namespaces/default/pods?limit=5
```
**Incomplete  `resourceVersion`**
got:`{"cluster1":"123"}` (decoded), while want `{"cluster1":"123","cluster2":"456"}`
**Unreasonable `continue`**
There's no resource version in `continue`, and next page query will got a wrong rv. …

fix paging list in karmada search proxy

---

pkg/search/proxy/store/multi_cluster_cache.go
pkg/search/proxy/store/multi_cluster_cache_test.go
pkg/search/proxy/store/util.go
pkg/search/proxy/store/util_test.go

Cherry pick of #3402 on release-1.5.
#3402: fill cluster rv in proxying list
```release-note
`karmada-search`: fix paging list in karmada search proxy in large scale memeber clusters.
```

Automated cherry pick of #3402: fill cluster rv in proxying list

---

hack/undeploy-karmada.sh

/kind cleanup
The `karmada-controller-manager` clusterrole has removed at #2511, we don't need to delete it at `hack/undeploy-karmada.sh`, otherwith there is a error.
```
[root@master67 karmada]# hack/undeploy-karmada.sh /root/.kube/config kubernetes-admin@kubernetes
namespace "karmada-system" deleted
Error from server (NotFound): clusterroles.rbac.authorization.k8s.io "karmada-controller-manager" not found
```
Fixes #
```release-note
NONE
```

Cleanup the rbac that has been removed in hack/undeploy-karmada.sh

---

pkg/util/helper/taint_test.go
pkg/util/helper/workstatus_test.go
pkg/util/interpreter/rule_test.go

/kind cleanup
Part of #3327 
NONE

Add UT for workstatus.go and taint.go and rule.go

---

charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/util/validation/validation.go

/kind bug
affinityName cannot be set to an empty string.
Fixes #3441
```release-note
API change: The length of `AffinityName` in `PropagationPolicy` now be restricted to (1, 32], and must be a qualified name.
```

fix: affinityName can be set to an empty string

---

pkg/apis/work/v1alpha2/binding_types_helper.go
pkg/apis/work/v1alpha2/binding_types_helper_test.go

/kind bug
1.apply following yaml:
```yaml
metadata:
name: nginx
labels:
app: nginx
spec:
replicas: 3
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- image: nginx
name: nginx
---
metadata:
spec:
name: nginx
placement:
clusterNames:
- member1
- member2
clusterTolerations:
- effect: NoExecute
key: fail-test
operator: Exists
tolerationSeconds: 10
replicaDivisionPreference: Weighted
weightPreference:
staticWeightList: …
```

Correct the issue of adding duplicate eviction tasks

---

pkg/controllers/gracefuleviction/evictiontask.go
pkg/controllers/gracefuleviction/evictiontask_test.go

/kind bug
Avoid the same cluster appearing in both spec.clusters and spec.gracefulEvictionTasks.
There are basicly two solutions:
1. Adjust the scheduler. Make sure that scheduler will not schedule resource templates to those cluster in gracefulEvictionTasks.
2. Adjust the controller. For those clusters that appear at the same time, keep the clusters in spec.clusters and delete the clusters in spec.gracefulEvictionTask.
When the scheduler can dispatch to a cluster in gracefulEvictionTasks, it means that the cluster has a high probability of recovering from the abnormal state when it was evicted. From this point of view, option 2 is a better choise.
Fixes #
**Special notes for your …

Avoid the same cluster appearing in both spec.clusters and spec.gracefulEvictionTasks

---

hack/cli-testing-environment.sh
hack/util.sh

* Fixing probability of failure in CLI workflow: https://github.com/karmada-io/karmada/actions/runs/4795320108/jobs/8529724228?pr=3461
The test result is here: https://github.com/jwcesign/karmada/actions/runs/4795828813/jobs/8530865325
Fixes #none
@Poor12 
```release-note
```

Fixing probability of failure in CLI workflow

---

pkg/scheduler/event_handler.go
pkg/scheduler/scheduler.go

By analyzing: https://github.com/karmada-io/karmada/issues/3390#issuecomment-1506471651
When processing `clusteraffinities`, we can determine whether the current binding has been synchronized by checking `SchedulerObservedGeneration`. Otherwise, we can obtain the latest binding object through the `karmadaClient`.
Fixes #3390 
Alternative solution:
Place `SchedulerObservedAffinityName` filed into `binding.spec`.
```release-note
NONE
```

flake: [ClusterAffinities] propagation testing

---

pkg/scheduler/scheduler.go

/kind bug
Ensure the latest schedulerObservedGeneration if do not need to schedule.
Fixes #3454 
Fixes #3467 
This PR need to cherry-pick.
```
`karmada-scheduler`: Fixed the issue of inconsistent Generation and SchedulerObservedGeneration.
```

Ensure the latest schedulerObservedGeneration if do not need to schedule

---

api/openapi-spec/swagger.json
pkg/apis/cluster/types.go
pkg/apis/cluster/v1alpha1/types.go
pkg/generated/openapi/zz_generated.openapi.go

This PR fixes the translation of one term from Chinese to english
Considering that `pkg/apis/cluster/types.go`  and `pkg/apis/cluster/v1alpha1/types.go` contains all the phrases both are in English, but one word has to be translated into English from Chinese. 
Fixes #3260 
Thanks for reviewing my PR. Feedbacks and suggestions are welcome. @RainbowMango 
```
NONE
```

fix: Chinese to English term

---

pkg/scheduler/framework/plugins/clustereviction/cluster_eviction.go
pkg/scheduler/framework/plugins/registry.go
pkg/util/helper/cluster.go
pkg/util/helper/cluster_test.go
test/e2e/failover_test.go

/kind feature
Add a clusterEviction plugin to filter cluster which has been evicted.
Part of #3169 
```
karmada-scheduler: add a clusterEviction plugin.
```

Add a clusterEviction plugin

---

pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go

/kind bug
When there are tasks in the GracefulEvictionTasks queue, graceful-eviction-controller will not work after restarting karmada-controller-manager.
Fixes #
```release-note
`karmada-controller-manager`: Fixed a corner case that when there are tasks in the GracefulEvictionTasks queue, graceful-eviction-controller will not work after restarting karmada-controller-manager.
```

fix: graceful-eviction still works after an unexpected restart of karmada-controller-manager

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/desired-helmrelease.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/observed-helmrelease.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/status-file.yaml

/kind cleanup
Add third-party resource `helm.toolkit.fluxcd.io/v2beta1/HelmRelease` into Resource Interpreter framework.
Part of #3331 
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `helm.toolkit.fluxcd.io/v2beta1/HelmRelease`
```

add customizations for helm.toolkit.fluxcd.io/v2beta1/HelmRelease

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/desired-helmrepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/observed-helmrepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/status-file.yaml

/kind cleanup
Add third-party resources source.toolkit.fluxcd.io/v1beta2/HelmRepository into Resource Interpreter framework.
Part of #3331
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `source.toolkit.fluxcd.io/v1beta2/HelmRepository`
```

add customizations for source.toolkit.fluxcd.io/v1beta2/HelmRepository

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/desired-helmchart.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/observed-helmchart.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/status-file.yaml

/kind cleanup
Add third-party resources `source.toolkit.fluxcd.io/v1beta2/HelmChart` into Resource Interpreter framework.
Part of #3331 
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `source.toolkit.fluxcd.io/v1beta2/HelmChart`
```

add customizations for source.toolkit.fluxcd.io/v1beta2/HelmChart

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/desired-gitrepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/observed-gitrepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/status-file.yaml

/kind cleanup
Add third-party resources `source.toolkit.fluxcd.io/v1/GitRepository` into Resource Interpreter framework.
Part of #3331 
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `source.toolkit.fluxcd.io/v1/GitRepository`
```

add customizations for source.toolkit.fluxcd.io/v1/GitRepository

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/desired-kustomization.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/observed-kustomization.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/status-file.yaml

/kind cleanup
Add third-party resource `kustomize.toolkit.fluxcd.io/v1/Kustomization` into Resource Interpreter framework.
Part of #3331 
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `kustomize.toolkit.fluxcd.io/v1/Kustomization`
```

add customizations for kustomize.toolkit.fluxcd.io/v1/Kustomization

---

operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/etcd/etcd.go
operator/pkg/controlplane/webhook/webhook.go
operator/pkg/tasks/init/component.go
operator/pkg/util/patcher/pather.go

/kind feature
we should support that user can set custom labels and annotations to karmada component workloads.
Here is test results:
Karmada CR yaml:
The etcd pod yaml:
Fixes #
```release-note
NONE
```

karmada operator: support custom labels and  annotations

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/desired-bucket.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/observed-bucket.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/status-file.yaml

/kind cleanup
Add third-party resources `source.toolkit.fluxcd.io/v1beta2/Bucket` into Resource Interpreter framework.
Part of #3331 
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `source.toolkit.fluxcd.io/v1beta2/Bucket`
```

add customizations for source.toolkit.fluxcd.io/v1beta2/Bucket

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/desired-ocirepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/observed-ocirepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/status-file.yaml

/kind cleanup
Add third-party resources `source.toolkit.fluxcd.io/v1beta2/OCIRepository` into Resource Interpreter framework.
Part of #3331 
@Poor12 
NONE
```release-note
`Resource Interpreter`: Support `source.toolkit.fluxcd.io/v1beta2/OCIRepository`
```

add customizations for source.toolkit.fluxcd.io/v1beta2/OCIRepository

---

pkg/controllers/applicationfailover/common.go
pkg/controllers/applicationfailover/common_test.go
pkg/controllers/applicationfailover/crb_application_failover_controller.go
pkg/controllers/applicationfailover/rb_application_failover_controller.go

/kind feature
This PR fix two bugs in application failover:
1. When the workload is in an unhealthy state and the tolerationSeconds has not yet expired, and the user manually clears the workload, the `workloadUnhealthyMap` will not be cleared, which will cause the tolerationSeconds to not work during the second application failover. To solve this issue, we use the `binding.NamespacedName` as the key instead of resource.gvk.
2. When the workload is in an unhealthy state and the tolerationSeconds has not yet expired, the workload came back to healthy now, we need to cleanup the cluster in `workloadUnhealthyMap`.
Fixes # …

Fix application failover

---

operator/pkg/certs/certs.go

/kind bug
When the service type of karmada apiserver is `ClusterIP`, we will add a empty dns or IP to AltNames object. It will thorw below error:
```shell
cannot parse IP address of length 0
```
Fixes #
```release-note
NONE
```

karmada operator: fixed adding altName to certification

---

pkg/registry/search/storage/cache.go

/kind bug
Adding HTTP response headers for k8s native clients to decode normally
Fixes:Search service request returns text/plain by default
```release-note
karmada-search: http response add content-type header
```

Fix:search http response add content-type header

---

pkg/registry/search/storage/cache.go

Cherry pick of #3505 on release-1.4.
#3505: fix:search http response add content-type header
```release-note
karmada-search: http response add content-type header
```

Automated cherry pick of #3505: fix:search http response add content-type header

---

pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go

/kind bug
fix an issue where DeepEqual becomes invalid in federated-resource-quota-status-controller
Fixes #3519
```release-note
NONE
```

Fix DeepEqual in federated-resource-quota-status-controller;

---

pkg/search/proxy/store/resource_cache.go

/kind cleanup
If some resurce is absent in member cluster, we can't troubleshoot what resource is missing. karmada-search's log:
```
E0506 10:36:58.331703       1 cacher.go:450] cacher (): unexpected ListAndWatch error: the server could not find the requested resource; reinitializing...
```
After add `GroupResource`, karmada-search's log:
```
E0506 10:36:58.331703       1 cacher.go:450] cacher (examples.foo.io): unexpected ListAndWatch error: the server could not find the requested resource; reinitializing...
```
Fixes #
```release-note
NONE
```

add GroupResource

---

operator/pkg/apis/operator/v1alpha1/defaults.go
operator/pkg/constants/constants.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/manifests.go
operator/pkg/tasks/deinit/component.go
operator/pkg/tasks/init/component.go
operator/pkg/util/naming.go

/kind feature
Desheduler is one of the more common components that we need to support.
Here is test results:
add configuration in CR resource:
```yaml
kind: Karmada
metadata:
spec:
components:
KarmadaDescheduler: {}
```
these pod of karmada descheduler is running:
```shell
NAME                                                    READY   STATUS    RESTARTS   AGE
karmada-demo-aggregated-apiserver-587bc5c697-dt6wh      1/1     Running   0          65s
karmada-demo-apiserver-55968d9f8c-ffdx7                 1/1     Running   0          106s
karmada-demo-controller-manager-64455f7fd4-49q5v        1/1     Running   0          58s …
```

karmada operator: implement installing karmada descheduler

---

pkg/controllers/binding/common.go
pkg/controllers/certificate/cert_rotation_controller.go
pkg/controllers/cluster/cluster_controller.go
pkg/controllers/execution/execution_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
pkg/controllers/hpa/hpa_controller.go
pkg/controllers/mcs/endpointslice_controller.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/mcs/service_import_controller.go
pkg/controllers/namespace/namespace_sync_controller.go
pkg/controllers/unifiedauth/unified_auth_controller.go
pkg/util/constants.go

/kind feature
Adds the well-known `"app.kubernetes.io/managed-by"` label to resources created by karmada controllers
We need a way to bypass creation of some ClusterRole/Rolebindings by our OPA Gatekeeper and we don't have a consistent label to select on. Not all the resources in this PR are needed by us (mostly just needed unified auth) but wanted to keep it consistent across controllers.
N/A
```release-note
Add the reserved label `karmada.io/managed` to resources created by karmada controllers.
```

add managed-by label to resources created by karmada controllers

---

charts/karmada/templates/_karmada_webhook_configuration.tpl
operator/pkg/karmadaresource/webhookconfiguration/mainfests.go
pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

/kind bug
add missing federatedresourcequota validate config
Fixes #
https://github.com/karmada-io/karmada/blob/master/artifacts/deploy/webhook-configuration.yaml#L156-L169
```release-note
`karmada-webhook`: add missing federatedresourcequota validate config.
```

fix: add missing federatedresourcequota validate config

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/customizations_tests.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/desired-policy.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/observed-policy.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/status-file.yaml

/kind cleanup
Add third-party resources `kyverno.io/v1/Policy` into Resource Interpreter framework.
Part of #3331 
@Poor12 @chaunceyjiang 
NONE
```release-note
`Resource Interpreter`: Support `kyverno.io/v1/Policy`
```

add customizations for kyverno.io/v1/Policy

---

pkg/controllers/binding/binding_controller.go
pkg/controllers/binding/cluster_resource_binding_controller.go
test/e2e/failover_test.go
test/e2e/framework/deployment.go

OverridePolicy does not work. When binding-controller watches a new op, it will traverse all related Bindings and requeue those objects hit by overrideRS. If one of the Bindings fails to be processed, it will return nil directly which may cause the op event to be lost.
Fixes #3532 
```release-note
```

Fix overridePolicy do not work when failed to process one of the matched binding

---

cmd/controller-manager/app/controllermanager.go
cmd/controller-manager/app/options/options.go
pkg/detector/detector.go

/kind feature
Recently, we encountered a slow restart issue where it took 15 minutes to clear the items in queues. We suspect that the number of workers in pp/cpp could be one of the reasons for this problem. Therefore, it would be reasonable to add a concurrency configuration for this.
Although the pp/cpp reconcile function appears to be capable of handling concurrency, the number of workers is hardcoded as `1`. Please let me know if there is any particular reason for this.
Fixes #
```release-note
`karmada-controller-manager`: Introduced `--concurrent-propagation-policy-syncs`/`--concurrent-cluster-pro …
```

enable concurrency for pp and cpp

---

pkg/controllers/gracefuleviction/evictiontask.go
pkg/controllers/gracefuleviction/evictiontask_test.go

/kind bug
When susspresion and graciously Tasks coexist in the GracefulEvictionTask queue, the graciously task cannot work.
Fixes #
Once the PurgeMode of Applicationfailover is set to Never, graceful eviction does not work.
Because the `retryInterval` is always less than 0.
```release-note
NONE
```

fix: When suppression and graciously Tasks coexist in the GracefulEvictionTask queue,  the graciously task cannot work.

---

.golangci.yml
hack/tools/swagger/lib/storage.go
hack/verify-staticcheck.sh
pkg/karmadactl/cmdinit/cert/cert_test.go
pkg/karmadactl/cmdinit/utils/examples_test.go
pkg/webhook/multiclusteringress/validating.go

/kind cleanup
This PR updates golangci-lint to v1.52.2 which including go1.20 support.
This PR is required by #3565.
Fixes #
```release-note
NONE
```

Update golangci-lint to v1.52.2

---

.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml
README.md
go.mod
hack/util.sh

/kind cleanup
This PR updates the default Go version for CI and releases bots to v1.20.4.
Since we are going to update the Kubernetes dependencies to v1.27.2 which requires Go1.20+.
Fixes #
```release-note
Karmada(v1.6) is now built with Go1.20.4.
```

Update Golang version from v1.19.5 to v1.20.4

---

pkg/controllers/status/cluster_status_controller_test.go

/kind cleanup
Part of #3327 
NONE

Add UT for pkg/controllers/status/cluster_status_controller_test.go

---

pkg/controllers/binding/binding_controller_test.go
pkg/util/testing/mock_manager.go
test/helper/manager.go

Signed-off-by: zishen <softwarebtg@163.com>
/kind cleanup
Part of #3327
NONE

Add UT for pkg/controllers/binding/binding_controller.go

---

pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go
pkg/search/proxy/store/cluster_cache.go
pkg/search/proxy/store/multi_cluster_cache.go
pkg/search/proxy/store/multi_cluster_cache_test.go
pkg/search/proxy/store/resource_cache.go
pkg/search/proxy/store/store.go
pkg/search/proxy/store/store_test.go
pkg/search/proxy/store/util.go
pkg/search/proxy/store/util_test.go
pkg/search/proxy/testing/mock_store.go

/kind feature
Fixes #3445
```release-note
`karmada-search`: support namespace filter in RR for search proxy.
```

Support namespace filter in RR for search proxy

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/argoproj.io/v1alpha1/Workflow/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/argoproj.io/v1alpha1/Workflow/customizations_tests.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/argoproj.io/v1alpha1/Workflow/testdata/desired-workflow.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/argoproj.io/v1alpha1/Workflow/testdata/observed-workflow.yaml

/kind cleanup
Add third-party resources `argoproj.io/v1alpha1/Workflow` into Resource Interpreter framework.
Part of #3331 
Only workflow-level resources and requirements are collected. The template-level resources which can be generated by workflow are ignored.
NONE
```release-note
`Resource Interpreter`: Support `argoproj.io/v1alpha1/Workflow`
```

add customizations for argoproj.io/v1alpha1/Workflow

---

pkg/controllers/status/work_status_controller_test.go

/kind cleanup
Part of #3327 
NONE

Add UT for pkg/controllers/status/work_status_controller.go

---

.github/workflows/ci.yml

Signed-off-by: zishen <softwarebtg@163.com>
/kind cleanup
For Node12 has been adapt to Node16, see ：https://github.com/arduino/setup-protoc/issues/59
so this comment should be removed.
Fixes #
NONE

remove ci todo annotation of adopt Node16

---

hack/deploy-karmada.sh

ISSUE: https://github.com/karmada-io/karmada/issues/3560
fix "hack/deploy-local-karamada.sh" base64 usage in mac M1, in mac this usage should add "-i" or use "<" to redirect input
from PR: https://github.com/karmada-io/karmada/pull/3561
Fixes #
```release-note
```

fix_deploy_sh_base64_usage

---

operator/cmd/operator/app/options/options.go
operator/pkg/controlplane/manifests.go
operator/pkg/deinit.go
operator/pkg/init.go

/kind cleanup
Do some operator cleanup.
Fixes #
```release-note
None
```

operator cleanup

---

charts/karmada/templates/_helpers.tpl
charts/karmada/templates/_karmada_bootstrap_token_configuration.tpl
charts/karmada/templates/_karmada_cluster_proxy_admin_rbac.tpl
charts/karmada/templates/karmada-apiserver.yaml
charts/karmada/templates/post-install-job.yaml
charts/karmada/templates/pre-install-job.yaml
charts/karmada/values.yaml

/kind feature
Support Karmada installed by helm to use karmadactl register.
Part of #3280 
The usage is that:
1. We need to specify a hostIP in a cert signed by `CA` in `charts/karmada/values.yaml` to provide external service. Like below, `10.10.103.67` is a hostIP.
```yaml
certs:
mode: auto
auto:
expiry: 43800h
hosts: [
"kubernetes.default.svc",
"*.etcd.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}",
"*.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}",
"*.{{ .Release.Namespace }}.svc",
"localhost",
"127.0.0.1",
"10.10.103.67"  # add a hostIP
]
```
2. Executing `helm install karmada -n karmada-system --create-namespace …

Support Karmada installed by helm to use karmadactl register

---

charts/karmada/_crds/bases/work.karmada.io_works.yaml
pkg/apis/work/v1alpha1/work_types.go

/kind cleanup
Consider adding a shortname to work? Because in our environment, I found that the resources of other teams are also called work. Is the name work too generic? Add a shortname to facilitate the distinction
Fixes #
```release-note
API change:  Introduced short name `wk` for `Work` resource.
```

Add kubebuilder shortName for work

---

pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/core/util.go
test/e2e/scheduling_test.go

/kind bug
Fix zero deployment can still propagate to member clusters when EnableEmptyWorkloadPropagation flag is false
Fixes #3495 
```release-note
`karmada-scheduler`: Fixed the issue that empty deployment can still be propagated to member clusters even when `--enableEmptyWorkloadPropagation` flag is false.
```

Fix zero deployment can still propagate to member clusters when EnableEmptyWorkloadPropagation flag is false

---

.github/workflows/lint-chart.yaml

/kind feature
In this pr https://github.com/karmada-io/karmada/pull/3524, the chart karmada-operaoter is introduced and the chart lint ci step is missing
Fixes #3579 
```release-note
NONE
```

add chart lint ci step for karmada-operaoter chart

---

pkg/modeling/modeling.go
pkg/modeling/modeling_test.go

Cherry pick of #3591 on release-1.3.
#3591: Change the length of modelSortings array for panic of index
```release-note
`karmada-controller-manager`: Fixed the panic issue in case of the grade number of resourceModel is less than the number of resources.
```

Automated cherry pick of #3591: Change the length of modelSortings array for panic of index

---

pkg/apis/cluster/scheme/regiser.go
pkg/apis/search/scheme/register.go

/kind cleanup
The `Scheme.AddUnversionedTypes` code in the init function is redundant because this part of the logic already exists in `metav1.AddToGroupVersion`.
https://github.com/karmada-io/karmada/blob/master/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/register.go#L75
Fixes #
```release-note
NONE
```

api: delete the useless Scheme.AddUnversionedTypes code

---

.github/workflows/release.yml

/kind cleanup
Remove [update-krew-index](https://github.com/karmada-io/karmada/blob/release-1.5/.github/workflows/release.yml#L39-L46) from branch release-1.5.
Fixes #3624 
```release-note
```

Stop update-krew for release-1.5.x

---

charts/karmada/_crds/bases/autoscaling.karmada.io_federatedhpas.yaml
pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go

Add printcolumn for FederatedHPA
```
NAME         REFERENCE-KIND   REFERENCE-NAME   MINPODS   MAXPODS   REPLICAS   AGE
nginx-test   Deployment       nginx            1         10        1          5d1h
```
Unlike the native HPA, FederatedHPA cannot print the target utilization as the limit of CRD. As far as I know, CRD‘s print column only supports definite json path.
The native hpa is like:
```
NAME         REFERENCE          TARGETS        MINPODS   MAXPODS   REPLICAS   AGE
nginx-test   Deployment/nginx   <unknown>/10   1         10        0          3h59m
```
Fixes #
```
api-change: …
```

Add printcolumn for FederatedHPA

---

pkg/resourceinterpreter/default/native/aggregatestatus.go
pkg/resourceinterpreter/default/native/aggregatestatus_test.go

/kind feature
supports aggregating the status of a pod's initContainer
Fixes #
```release-note
`karmada-controller-manager`: supports aggregating the status of a pod's initContainer.
```

feat: supports aggregating the status of a pod's initContainer

---

pkg/controllers/applicationfailover/common_test.go
pkg/controllers/applicationfailover/crb_application_failover_controller_test.go
pkg/controllers/applicationfailover/rb_application_failover_controller_test.go
pkg/controllers/status/crb_status_controller_test.go
pkg/controllers/status/rb_status_controller_test.go

/kind cleanup
Part of #3327 
NONE

Add ut for `pkg/controllers/applicationfailover` and `pkg/controllers/status`

---

pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/core/util.go
test/e2e/scheduling_test.go

Cherry pick of #3496 on release-1.5.
#3496: fix When EnableEmptyWorkloadPropagation flag is false zero
```release-note
`karmada-scheduler`: Fixed the issue that empty deployment can still be propagated to member clusters even when `--enableEmptyWorkloadPropagation` flag is false.
```

Automated cherry pick of #3496: fix When EnableEmptyWorkloadPropagation flag is false zero

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
hack/verify-crdgen.sh

/kind cleanup
Verify-crdgen.sh now do not verify the `karmada` crd of karmada-operator.
Fixes #
None

Fix verify-crdgen.sh do not verify operator

---

operator/pkg/apis/OWNERS

/kind cleanup
This PR added me to the list of Karmada Operator APIs, the option [no_parent_owners](https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#owners) ensures I won't be missed from review of API changes.
Fixes #
```release-note
NONE
```
Assigning operator owners:
/assign @calvin0327 @lonelyCZ @Poor12

Setup operator API owners

---

docs/proposals/caching/README.md
docs/proposals/resource-aggregation-proxy/README.md

Enabling the resource caching feature allows users with access to `search/proxy` to get/list/describe resources without any restrictions on RBAC in member clusters. However, modifying the RBAC will still be restricted.  
This restriction should be actively proposed.
Fixes #none
```release-note
```

doc: Add the limitations of search proxy

---

pkg/apis/autoscaling/v1alpha1/well_known_constants.go
pkg/metricsadapter/provider/resourcemetrics.go

/kind bug
when different clusters have the same pod name, the annotations of different metrics have the same value
Fixes #
```release-note
`karmada-metrics-adapter`: fix when different clusters have the same pod name, the annotations of different metrics have the same value
```

metrics-adapter: when different clusters have the same pod name, the annotations of different metrics have the same value

---

.github/workflows/release.yml

/kind feature
Related to https://github.com/karmada-io/karmada/pull/3652
karmadactl will parse the version(the version comes from the git tag) and download the crds.tar.gz from GitHub release URL.
for example, with `v1.1.1-6-gf20c721a`, the  download URL will be `https://github.com/karmada-io/karmada/releases/download/v1.1.1/crds.tar.gz`
with `v1.7.0-alpha.1-3-gf20c721a`, the download URL will be `https://github.com/karmada-io/karmada/releases/download/v1.7.0-alpha.1/crds.tar.gz`.
This means we need to upload the crds.tar.gz for each release(no matter if it's path release, minor release, or pre-release).
Part of https://github.com/karmada-io/karmada/issues/3633
**Special notes for your …

feat: Release crds.tar.gz in release workflow

---

test/e2e/framework/deployment.go
test/e2e/resourceinterpreter_test.go

/kind cleanup
It changes the test case from update the `.status.readyReplicas to 3` operation to wait the `.status.readyReplicas==3` operation, which is more reasonable.
Part of #3640 
```release-note
```

cleanup the ci about interpreter-interpret-health test

---

pkg/controllers/execution/execution_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
pkg/controllers/status/cluster_status_controller.go
pkg/controllers/status/work_status_controller.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/detector/detector.go
pkg/util/helper/workstatus.go

/kind cleanup
The resource object which get from controller is a brand new memory. There will be not any risk of mutating the cache.
See https://github.com/karmada-io/karmada/pull/3538#issuecomment-1549124143 and [controller-runtime examples](https://github.com/kubernetes-sigs/controller-runtime/blob/main/examples/builtins/controller.go). 
Fixes #
None

Delete redundant deepcopy

---

cmd/controller-manager/app/controllermanager.go
pkg/controllers/cluster/cluster_controller.go

/kind cleanup
Now when unjoining the cluster, the implementation of work is deleted by deleting the cluster execution space, because the namespace-controller of kube-controller-manager implements the logic of deleting the namespace, which will cause a delay of 5 seconds, resulting in frequent reentry of cluster objects in the karmada-controller-manager cluster-controller, I think the current implementation is a bit flawed
Fixes #3113
```release-note
NONE
```

unjoin cluster check namespace reduce cluster enqueue 

---

pkg/karmadactl/addons/init/enable_option.go
pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/register/register.go
pkg/version/release.go
pkg/version/release_test.go

/kind cleanup
We are now introducing a pre-release that follows the K8s release process. However, in the previous implementation, there was an issue with the image tag used during initialization. Here's an example:
```
karmadactl git version: v1.7.0-alpha.1-3-gf20c721a
Once parsed, the card will utilize version 1.7.0 and Karmada's image tag will also be set to version 1.7.0, which has not yet been released.
```
To fix this problem, we will parse `v1.7.0-alpha.1-3-gf20c721a` as `v1.7.0-alpha.1`, which is what this patch does.
But with this patch, each release should have the CRD assets, which should be done in another PR.
Fixes https://github.com/karmada-io/karmada/issues/3633
**Special …

feat: Fix version parse

---

.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
hack/docker.sh

/kind feature
Let images of kamada signed with cosign. 
It would be help with the implementation of supply chain security practices on the user side.
Part1 of #3435
After sign you can see the signatures from command of `cosign verify xxx`
Just like that:
```
lan@lan:~/repo/git/karmada$ cosign verify lypgcs/karmada-search:sign_images
Verification for index.docker.io/lypgcs/karmada-search:sign_images --
The following checks were performed on each of these signatures:
- The cosign claims were validated
- Existence of the claims in the transparency log was verified offline
- Any certificates were verified against the Fulcio roots. …
```

Sign images

---

artifacts/deploy/karmada-metrics-adapter-apiservice.yaml
cmd/metrics-adapter/app/options/options.go
pkg/metricsadapter/adapter.go
pkg/metricsadapter/controller.go
pkg/metricsadapter/multiclient/client.go
pkg/metricsadapter/provider/custommetrics.go

/kind feature
support custom metrics for metrics adapter
Part  of #3632
```release-note
`karmada-metrics-adapter`: support custom metrics for metrics adapter
```

feat: support custom metrics for metrics adapter

---

pkg/util/restmapper/restmapper.go

/kind cleanup
Now cachedRESTMapper will do nothing but return an error when users do not pass versions parameter. But for the underlying RESTMapper, it can get the corresponding `RESTMapping` without versions. The reference code is [here](https://github.com/kubernetes/apimachinery/blob/6b1428efc73348cc1c33935f3a39ab0f2f01d23d/pkg/api/meta/restmapper.go#LL466C1-L466C1). So when no versions pass, we'd better try to consult the underlying mappers.
Fixes #
None

Fix cached RESTMapper when pass no versions

---

pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/options/global.go

/kind feature
see https://github.com/karmada-io/karmada/pull/3453
Fixes #3406
Fixes #3611
/cc @lonelyCZ @XiShanYongYe-Chang 
```release-note
`karmadactl`: The `--wait-component-ready-timeout` flag has been introduced in the `init` command to specify the component installation timeout.
```

karmadactl init add timeout flag

---

hack/deploy-k8s-metrics-server.sh

/kind feature
When using FederatedHPA, `metrics-server` needs to be installed in member clusters.
So we provider a script to install `metrics-server` in member cluster conveniently.
Fixes #none
Testing report:
```sh
root@karmada [02:38:05 PM] [~/workspace/git/karmada] [install-script *]
-> # k get pods -A
NAMESPACE            NAME                                            READY   STATUS    RESTARTS   AGE
karmada-system       karmada-agent-648c99647-qvkf5                   1/1     Running   0          3d23h
karmada-system       karmada-agent-648c99647-tfw2m                   1/1     Running   0          3d23h
kube-system …
```

feat: Add script to deploy k8s metrics-server in member cluster

---

pkg/resourceinterpreter/default/native/aggregatestatus.go
pkg/resourceinterpreter/default/native/aggregatestatus_test.go

/kind bug
fix aggregateCronJobStatus panic
Fixes #
When job is not successful even once, `lastSuccessfulTime` will always be`nil`. Printing logs at this time will cause a panic.
```release-note
`karmada-controller-manager`: fix panic when printing log when lastSuccessfulTime of cronjob is nil.
```

fix panic when printing log when lastSuccessfulTime of cronjob is nil

---

.github/workflows/ci.yml
hack/local-up-karmada.sh
hack/util.sh

/kind flake
for CI stability
Fixes #3667 
@RainbowMango @XiShanYongYe-Chang @yike21 
```release-note
```

fix: repair flaking test job of setup e2e test environment

---

pkg/controllers/federatedhpa/federatedhpa_controller.go
pkg/controllers/federatedhpa/replica_calculator.go

/kind feature
hpa-controller supports custom metrics, depends on #3638.
Fixes #
None

hpa-controller supports custom metrics

---

.github/workflows/ci.yml

**What this PR does**:
It simply ignores codecov errors and does not let ci tests fail in case.
Fixes #3674 
```release-note
NONE
```

ignoring codecov errors in ci

---

.github/workflows/ci-schedule-compatibility.yaml
.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/dockerhub-latest-chart.yml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-chart.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/fossa.yml
.github/workflows/lint-chart.yaml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind flake
We expect the Kind version to be v0.17.0, but the ubuntu image in our CI Runner now comes with kind@v0.20.0. The error mentioned above almost always occurs in ubuntu-20.04 when using kind@v0.20.0, but it runs normally on ubuntu-22.04.
Our CI logic checks whether there is a kind command and if so, it will not install it again, so we are using the kind@v0.20.0 that comes with the image by default . Therefore, the solution is either to upgrade to ubuntu-22.04 or force installation of kind@v0.17 .
https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0
Fixes #3667 
@RainbowMango @XiShanYongYe-Chang  …

upgrade CI ubuntu image

---

test/e2e/propagationpolicy_test.go

/kind cleanup
Should be queried on member clusters rather than the control plane.
Fixes #
```release-note
NONE
```

e2e: should be queried on member clusters rather than the control plane

---

pkg/util/objectwatcher/objectwatcher.go

/kind bug
fix the Applied of ResourceBinding is always true
Fixes #3708 
```release-note
`karmada-controller-manager`: fix the Applied of ResourceBinding is always true.
```

fix the Applied of ResourceBinding is always true

---

charts/karmada/_crds/bases/autoscaling.karmada.io_federatedhpas.yaml
pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go
pkg/generated/openapi/zz_generated.openapi.go

/kind cleanup
This PR clean up some nits including field tags and comments.
Fixes #
```release-note
NONE
```

cleanup FederatedHPA API

---

pkg/util/objectwatcher/objectwatcher.go

Cherry pick of #3709 on release-1.5.
#3709: fix the Applied of ResourceBinding is always true
Part of #3720 
```release-note
`karmada-controller-manager`: Fixed `Applied` condition of ResourceBinding is always true issue.
```

Automated cherry pick of #3709: fix the Applied of ResourceBinding is always true

---

operator/config/samples/karmada.yaml
operator/pkg/constants/constants.go

/kind feature
```
[root@master-01 ~]# k -n test get karmada.operator.karmada.io/karmada-demo -oyaml
kind: Karmada
metadata:
creationTimestamp: "2023-06-27T07:12:57Z"
finalizers:
- operator.karmada.io/finalizer
generation: 2
labels:
operator.karmada.io/disable-cascading-deletion: "false"
resourceVersion: "746734041"
uid: 423ea5fe-b848-4b5f-b51a-aaeed83b6ea7
spec:
components:
etcd:
local:
imageRepository: registry.k8s.io/etcd
imageTag: 3.5.3-0
replicas: 1
resources: {}
volumeData:
volumeClaim:
metadata: {}
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 3Gi
karmadaAPIServer:
imageRepository: …
```

update karmada operator  default karmada  version

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/helper.go
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/controller/karmada/controller.go
operator/pkg/controller/karmada/planner.go

/kind feature
In init and deinit, we need more informations to observe the karmada current status.
here is test result:
```shell
kubectl get karmada -n test
NAME           READY   AGE
karmada-demo   False   27m
```
the cr status message:
Fixes #
```release-note
NONE
```

karmada operator: add conditions to karmada cr

---

operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/webhook/webhook.go
operator/pkg/init.go
operator/pkg/tasks/init/apiserver.go
operator/pkg/tasks/init/component.go
operator/pkg/tasks/init/data.go
operator/pkg/util/patcher/pather.go

/kind feature
In some scenarios, users need to update karmada components arguments, disable or enable featurGates.
For featueGate, we only support global featureGates, It's work for all of karmada components.
Fixes #
Test results:
I want to change karmada apiserver log level to 5 and add enable `PropagateDeps` featureGate.
the Karmada CR yaml:
```yaml
kind: Karmada
metadata:
spec:
components:
karmadaAPIServer:
serviceType: NodePort
extraArgs:
v: "5"
featureGates:
PropagateDeps: true
```
the karmada apiserver arguments:
the karmada controllerManager featuregates:
**Does this PR …

Karmada Operator: support custom arguments and featureGates

---

pkg/util/validation/validation.go

/kind bug 
Fixes https://github.com/karmada-io/karmada/issues/3738
```release-note
`karmada-webhook`: When application failover is enabled, users are prevented from setting propagateDeps to `false`.
```

fix: when application failover is enabled but propagateDeps is set to false, the failover has no effect

---

operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/manifests.go

/kind feature
Karmada components have the ability of leader elect, but not yet used in manifests of karmada operator.
Fixes #
```release-note
NONE
```

Karmada Operator: Add Leader Elect to Manifests

---

.github/workflows/lint-chart.yaml

/kind feature
The `set-output` is be deprecated，we need set the variable in step to `$GITHUB_OUTPUT` env.
Ref: 
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#example-of-setting-an-output-parameter
https://github.com/helm/chart-testing-action#example-workflow
Fixes https://github.com/karmada-io/karmada/issues/3752
```release-note
NONE
```

Update set-output command in lint-chart ci

---

pkg/karmadactl/options/options.go

/kind cleanup
The SetOutput will be Deprecated
https://github.com/kubernetes/kubernetes/blob/75889ecec5d30cbe1dcb6636d5334b21b4378e9c/staging/src/k8s.io/kubectl/pkg/cmd/options/options.go#L51C1-L52C17
Fixes #
```release-note
NONE
```

Use SetOut and/or SetErr instead SetOutput

---

pkg/util/fedinformer/genericmanager/multi-cluster-manager.go
pkg/util/fedinformer/genericmanager/single-cluster-manager.go
pkg/util/fedinformer/typedmanager/multi-cluster-manager.go
pkg/util/fedinformer/typedmanager/single-cluster-manager.go

Cherry pick of #3123 on release-1.5.
#3123: Avoid multiple executions after rlock in concurrent scenarios
```release-note
NONE
```
#3763

Automated cherry pick of #3123: Avoid multiple executions after rlock in concurrent scenarios

---

pkg/util/validation/validation.go

Cherry pick of #3739 on release-1.6.
#3739: fix: when application failover is enabled but propagateDeps
```release-note
`karmada-webhook`: When application failover is enabled, users are prevented from setting propagateDeps to `false`.
```

Automated cherry pick of #3739: fix: when application failover is enabled but propagateDeps

---

operator/pkg/karmadaresource/webhookconfiguration/manifests.go
pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

add cronfederatedhpa webhook for karmadactl and karmada-operator
Part of https://github.com/karmada-io/karmada/issues/3746
```release-note
`karmadactl` and `karmada-operator`: add the missing cronfederatedhpa webhook.
```

add cronfederatedhpa webhook for karmadactl and karmada-operator

---

hack/deploy-metrics-adapter.sh

/kind cleanup
When karmada kubeconfig is different from host kubeconfig, this script can't deploy the metrics-adapter.
Fixes #none
```release-note
```

cleanup: Adapt metrics-adapter deploying script to more generic scenario

---

charts/karmada/templates/_helpers.tpl
charts/karmada/templates/karmada-search.yaml

Cherry pick of #3777 on release-1.6.
#3777: chart: fix karmada search external etcd no volume mount
```release-note
Chart: Fixed the issue that `karmada-search` no ETCD secret volume mount when using external ETCD.
```

Automated cherry pick of #3777: chart: fix karmada search external etcd no volume mount

---

charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
docs/proposals/networking/multiclusterservice.md
pkg/apis/networking/v1alpha1/service_types.go
pkg/generated/openapi/zz_generated.openapi.go

/kind cleanup
clarify the meaning when the port of MCS is empty
Fixes #
https://github.com/kubernetes-sigs/mcs-api/blob/master/pkg/apis/v1alpha1/serviceimport.go#L108-L109
The port of `ServiceImport` is a required field, but the port of MCS is optional.
```release-note
NONE
```

feat: Change the port of MCS to required.

---

pkg/controllers/binding/binding_controller.go
pkg/controllers/binding/cluster_resource_binding_controller.go
pkg/controllers/execution/execution_controller.go
pkg/detector/detector.go
pkg/detector/policy.go
pkg/metrics/resource.go

/kind cleanup
As https://github.com/karmada-io/karmada/issues/3790 described, if there are many works, the metrics query response will be too big. The root reason is:
The label contains namespace/name/apiVersion, and for different resources, the entries are separate.
To delete these labels, all the resources will use the same one, for example:
Before:
```
work_sync_workload_duration_seconds_bucket{name="nginx",namespace="karmada-es-member2",result="success",le="+Inf"} 1
work_sync_workload_duration_seconds_bucket{name="mysql",namespace="karmada-es-member2",result="success",le="+Inf"} 1
```
After:
```
work_sync_workload_duration_seconds_bucket{result="success",le="+Inf"} 2
```
Regardless of the amount of resources …

fix: reduce the number of metrics by merging entries 

---

pkg/apis/work/v1alpha2/binding_types.go
pkg/scheduler/core/division_algorithm.go
pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/framework/plugins/apienablement/api_enablement.go
pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
pkg/scheduler/framework/types.go
pkg/scheduler/helper.go
pkg/scheduler/helper_test.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind feature
Fixes #3586
```release-note
karmada-scheduler: Introduce new schedule condition reasons, NoClusterFit, SchedulerError, Unschedulable, Success.
```

feat: optimize scheduling condition semantics

---

pkg/util/membercluster_client.go
pkg/util/round_trippers.go

/kind feature
Since we have add proxy headers in cluster API, I'd like to implement proxy headers of cluster API.
Fixes #
```
`karmada-controller-manager`: implement proxy header of cluster API
```

Implement proxy headers of cluster API

---

pkg/util/restmapper/restmapper.go
pkg/util/restmapper/restmapper_test.go

/kind cleanup
The reason why we introduced the [cachedRESTMapper](https://github.com/karmada-io/karmada/blob/d27faeac953043c2274bb8787bbbaaafa7d0dcd6/pkg/util/restmapper/restmapper.go#L25) is to improve performance, especially when retrieve the GVR as per a GVR, such as [here](https://github.com/karmada-io/karmada/blob/d27faeac953043c2274bb8787bbbaaafa7d0dcd6/pkg/detector/detector.go#L565).
We built the `cachedRESTMapper` [based on controller-runtime DynamicRESTMapper](https://github.com/karmada-io/karmada/blob/d27faeac953043c2274bb8787bbbaaafa7d0dcd6/pkg/util/restmapper/restmapper.go#L92-L106), but there is a breaking change happened in [v0.15.0](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.15.0) …

build cached restmapper based on Kubernetes restmapper

---

pkg/detector/detector.go
pkg/detector/preemption.go
pkg/util/helper/binding.go
pkg/util/names/names.go

/kind feature
implement propagation policy preemption: high-priority pp/cpp -> low-priority pp/cpp.
part of [feature](https://github.com/karmada-io/karmada/issues/3787)
```release-note
NONE
```

feat: implement propagation policy priority preemption

---

pkg/detector/policy.go

/kind bug
Fixed a boundary case where the `propagationpolicy.karmada.io/name` in the label of the resource template would not be removed when deleting PP.
Fixes #3847 
```release-note
`karmada-controller-manager`:  Fixed a boundary case where the `propagationpolicy.karmada.io/name` in the label of the resource template would not be removed after deleting PP.
```

fix: when the PP is deleted, the propagationpolicy.karmada.io/name label in the resource template's labels is not removed.

---

pkg/detector/policy.go

Cherry pick of #3848 on release-1.6.
#3848: fix: When the PP is deleted, the
```release-note
`karmada-controller-manager`:  Fixed a boundary case where the `propagationpolicy.karmada.io/name` in the label of the resource template would not be removed after deleting PP.
```

Automated cherry pick of #3848: fix: When the PP is deleted, the

---

charts/karmada/templates/karmada-controller-manager.yaml

/kind bug
in this issue,Error occurs when using helm upgrade karmada, here add post-upgrade in karmada-controller-manager.yaml
Fixes #3813 
```release-note
NONE
```

fix: can not upgrade karmada controller manager deployment with helm upgrade

---

pkg/karmadactl/register/register.go
pkg/util/credential.go
pkg/util/namespace.go
pkg/util/namespace_test.go

Fixes #2862 
when adding a cluster to karmada, it will has a label indicating that the namespace was created by karmada to avoid accidental deletion.:
```release-note
karmadactl join/register, karmada-agent: Add labels on the namespace created by karmada.
```

feat: Add label on the namespace created by karmada

---

pkg/search/proxy/store/multi_cluster_cache_test.go

/kind cleanup
Refer to https://github.com/karmada-io/karmada/pull/3730#issuecomment-1654850120
```release-note
NONE
```

fix ut in TestMultiClusterCache watch

---

test/e2e/seamless_migration_test.go

add e2e test for #3821 
Fixes #3824 
none

test: add e2e test for seamless migration 

---

pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
pkg/webhook/cronfederatedhpa/validation.go

/kind bug
1. When scaling FederatedHPA, `rule.targetMinReplicas` is 5 and `rule.targetMaxReplicas` is nil, this is valid. 
2. Record CronFederatedHPA.status history with the right `appliedMinReplicas` and `appliedMaxReplicas`
Fixes #none
```release-note
NONE(This bug has been released)
```

fix: fix bugs about validation of targetMinReplicas<=targetMaxReplicas and CronFederatedHPA status record

---

pkg/detector/detector.go
pkg/detector/policy.go
pkg/detector/preemption.go

/kind feature
implement preemption between propagation policies
part of [feature](https://github.com/karmada-io/karmada/issues/3787)
```release-note
NONE
```

feat: implement preemption between propagation policies

---

.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
This PR updates the default Go version for CI and release bots to v1.20.6.s
Fixes #3864 
```release-note
Karmada(v1.7) is now built with Go1.20.6.
```

Updated Golang version from v1.20.4 to v1.20.6

---

cmd/controller-manager/app/controllermanager.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/dependenciesdistributor/dependencies_distributor_test.go

/kind cleanup
Make some cleanup in the dependencies distributor:
- Change some unnecessary exposed member variables to internal variables.
- Delete some redundant code.
- Modify inappropriate method or variable names.
Fixes #
```release-note
NONE
```

Make some cleanup in dependencies distributor

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/controllers/federatedhpa/federatedhpa_controller.go
pkg/util/constants.go

/kind feature  
Now, the default timeout for waiting cache syncing in `controller-runtime` is 2 minutes. If we have a lot resources on the fed control plane, the default timeout might be reached and the process would return with an error like:  
```
E0801 06:15:22.538099       1 controllermanager.go:154] controller manager exits unexpectedly: [failed to wait for build-resource-informers for work caches to sync: timed out waiting for cache to be synced, failed waiting for all runnables to end within grace period of 30s: context deadline exceeded
```  
And the `karmada-controller-manager` would be hard to restart successfully.  
Fixes #
**Special notes for your reviewer**:  
The log …

use ClusterCacheSyncTimeout for resources on fed control plane as well

---

pkg/dependenciesdistributor/dependencies_distributor.go
pkg/detector/detector.go
pkg/util/eventfilter/eventfilter.go
pkg/util/eventfilter/eventfilter_test.go

/kind bug
Fix dependent resources being created and deleted repeatedly when the dependent resource has a status field.
Fixes #
When dependent resources only change state, there is no need to modify dependent resources in member clusters.
```release-note
`karmada-controller-manager`: fix dependent resources being created and deleted repeatedly when the dependent resource has a status field.
```

fix: fix dependent resources being created and deleted repeatedly when the dependent resource has a status field.

---

pkg/controllers/cluster/cluster_controller.go
pkg/events/events.go
pkg/util/helper/taint.go
pkg/util/helper/taint_test.go
test/e2e/failover_test.go

/kind cleanup
Refactor:
1. Now the former `UpdateClusterControllerTaint` is an unclear naming. Changed to `UpdateClusterTaints`.
2. `UpdateClusterControllerTaint` do two things. The first is generate the updated taints based on the taintsAdd and taintsRemove. The Second is update the cluster taints which is generated above. Splitting functions makes responsibilities more single.
3. `updateClusterTaints` should be a method of the cluster-controller by its responsibility. This is also good for joining events.
4. `RemoveTargetClusterFailed` is triggered by updating the termating taint failure. It should be merged into `TaintClusterFailed`.
```
Events:
Type    Reason …
```

Refactor the func and event of taint cluster

---

.github/workflows/release.yml

This PR updates the version of a7ul/tar-action used in our GitHub Actions workflow from v1.1.0 to v1.1.3. The update is needed to address two deprecation warnings. The first is regarding the use of Node.js 12 which is being deprecated and will default to Node.js 16. The second concerns the deprecation of the set-output command. Both of these issues are handled in v1.1.3 of a7ul/tar-action.
Fixes #3871
This change has no impact on the functionality of our workflows. It's a minor version update to stay aligned with the best practices and remove deprecation warnings.
None
```release-note …
```

Upgrade a7ul/tar-action to v1.1.3

---

pkg/detector/detector.go
pkg/detector/policy.go
pkg/util/helper/binding.go
pkg/util/label.go
pkg/util/label_test.go

/kind bug
avoid updating directly cached resource template.
Fixes #3878
```release-note
karmada-controller-manager: Avoid updating directly cached resource template.
```

fix bug: avoid updating directly cached resource template

---

pkg/detector/detector.go
pkg/detector/policy.go
pkg/util/helper/binding.go
pkg/util/label.go
pkg/util/label_test.go

Cherry pick of #3879 on release-1.5.
#3879: avoid updating directly cached resource template for clean up
```release-note
`karmada-controller-manager`: Avoid updating directly cached resource templates.
```

Automated cherry pick of #3879: avoid updating directly cached resource template for clean up

---

artifacts/deploy/webhook-configuration.yaml
charts/karmada/templates/_karmada_webhook_configuration.tpl
operator/pkg/karmadaresource/webhookconfiguration/manifests.go
pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

/kind flake
fix e2e test accidently timeout failure.
#3825
@chaunceyjiang @XiShanYongYe-Chang 
```release-note
```

update validate-resourceinterpretercustomization webhook timeout from 3s to 10s

---

artifacts/deploy/admin-clusterrole-aggregation.yaml
artifacts/deploy/kube-controller-manager.yaml
hack/deploy-karmada.sh

/kind feature
`admin` is a built-in ClusterRole in Kubernetes. It collects rules from other clusterRoles through aggregation method. This logic is managed by the `clusterrole-aggregation-controller` in kube-controller-manager, so we need to enable this controller.
In addition, we also need to grant `admin` the permissions to handle Karmada resources, including read and write access.
Part of #3916 
```release-note
karmada-kube-controller-manager: grant admin clusterrole with karamda resource permission
```

grant clusterrole admin with karamda resource permission

---

pkg/controllers/federatedhpa/replica_calculator.go

/kind bug
Fix plain metric calculation error when usageRatio == 1.0 which I fixed in https://github.com/kubernetes/kubernetes/pull/117845
Fixes #
```release-note
`kamrada-controller-manager`: Fix federated-HPA plain metric calculation is incorrect when usageRatio == 1.0, keep same with resource replicas.
```

fix federated-hpa plain metric calc

---

pkg/karmadactl/get/get.go

/kind cleanup
We have added labels to the resources in the member cluster to indicate whether the current resource is propagated by Karmada:
https://github.com/karmada-io/karmada/blob/1953a0ee50d9d452b9ca5fffdb2f60338eed0b63/pkg/util/constants.go#L26-L30
Therefore, we can directly process this label in the `karmadactl get` command, without needing to retrieve RB/CRB resources.
Fixes #
One reason for this change is that we cannot assume that users using karmadactl by default have the authority to get rb/crb resources.
```release-note
NONE
```

[karmadactl get] judge with label on the resources determine whether resource is adopted by Karmada

---

pkg/util/overridemanager/overridemanager_test.go

/kind flake
Actually, this doesn't trigger any bugs, but it ought to be of the form \`"{{string}}"\`. Otherwise there will be no double quotes when converting to a string and cause a marshal error in encoding/json. Just in case developers want to add a unit test on plaintext overrider later, I create this pr.
Fixes #
```release-note
None
```

improve overridemanager test

---

docs/proposals/service-discovery/README.md

proposal for native service discovery

---

cmd/descheduler/app/descheduler.go
cmd/scheduler-estimator/app/scheduler-estimator.go
cmd/scheduler/app/scheduler.go
pkg/sharedcli/profileflag/profileflag.go

/kind bug
Avoid slow http attack.
Fixes #3945 
```
Security: Sets an upper bound for all components on the lifetime of idle keep-alive connections and time to read the headers of incoming requests.
```
@RainbowMango @XiShanYongYe-Chang PTAL

add http limit for the Slowloris attack

---

pkg/modeling/modeling.go

/kind cleanup
Check for invaild index to avoid the panic.
Related:
- https://github.com/karmada-io/karmada/issues/3854
Fixes #
```release-note
NONE
```

ResourceSummary add check index for -1

---

operator/pkg/karmadaresource/webhookconfiguration/webhookconfiguration.go
operator/pkg/tasks/init/apiserver.go
operator/pkg/tasks/init/etcd.go
operator/pkg/tasks/init/karmadaresource.go
operator/pkg/tasks/init/wait.go
operator/pkg/util/apiclient/idempotency.go
operator/pkg/util/endpoint.go

Fixes https://github.com/karmada-io/karmada/issues/3935
```release-note
NONE
```

update operator default timeout

---

cmd/aggregated-apiserver/app/options/options.go
pkg/aggregatedapiserver/apiserver.go
pkg/registry/cluster/storage/proxy.go
pkg/registry/cluster/storage/proxy_test.go
pkg/registry/cluster/storage/storage.go

/kind cleanup
When using the proxy function provided by karmada-aggregated-apiserver to access member cluster resources. The current implementation needs to obtain the impersonator secret corresponding to the member cluster in real time each time.
In large-scale scenarios, the number of requests to karmada-apiserver will increase, and I think cached queries should be used
Fixes #
```release-note
`karmada-aggregated-apiserver` : Proxy connect get cluster impersonator secret use secretLister
```

Proxy connect get cluster impersonator secret use secretLister

---

charts/karmada/templates/karmada-resource-clusterrole.yaml

/kind feature
add admin clusterrole for karmada resources when helm install
Part of https://github.com/karmada-io/karmada/issues/3916
Test:
install by helm, and create the clusterroles
```release-note
add admin clusterrole for karmada resources when helm install
```

Feat: Add karmada resource clusterrole for helm install

---

pkg/controllers/status/cluster_status_controller_test.go

/kind cleanup
After the controller runtime update [here](https://github.com/kubernetes-sigs/controller-runtime/pull/2259),  test case need to be adapted.
Fixes #3730 
@RainbowMango @XiShanYongYe-Chang

repair the cluster_status_controller_test

---

api/openapi-spec/swagger.json
pkg/apis/cluster/types.go
pkg/apis/cluster/v1alpha1/types.go
pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
pkg/apis/cluster/zz_generated.deepcopy.go
pkg/generated/openapi/zz_generated.openapi.go

This PR extends the `Cluster` API by adding a new field `Zones` to represent zones of a member cluster.
Fixes #3413
```release-note
API change: Introduced a new field `Zones` to represent multiple zones of a member cluster.
```

Extend Cluster API to support multiple zones

---

pkg/registry/search/storage/cache.go

/kind bug
Fixes #3960
When listing from an  Infromer, it returns reference of objects in `cache`.
https://github.com/karmada-io/karmada/blob/48a37ab5b1f535eaa2c70e3b6ca52909fa78372e/vendor/k8s.io/client-go/tools/cache/thread_safe_store.go#L245-L253
When two or more search requests come at the same time, and all requests list objects from informer and add cluster annotation into the same objecs, it raises crash.
https://github.com/karmada-io/karmada/blob/5763248181ed3a90684b36b4d5d2ffea2c68d987/pkg/registry/search/storage/cache.go#L141
```release-note
`karmada-search`: Fixed a panic due to concurrent …
```

fix addAnnotationWithClusterName crash

---

charts/karmada/templates/karmada-agent.yaml
charts/karmada/templates/karmada-aggregated-apiserver.yaml
charts/karmada/templates/karmada-apiserver.yaml
charts/karmada/templates/karmada-controller-manager.yaml
charts/karmada/templates/karmada-descheduler.yaml
charts/karmada/templates/karmada-scheduler-estimator.yaml
charts/karmada/templates/karmada-scheduler.yaml
charts/karmada/templates/karmada-search.yaml
charts/karmada/templates/karmada-webhook.yaml
charts/karmada/templates/kube-controller-manager.yaml
charts/karmada/values.yaml

/kind feature
Currently there's not a way to render PodDisruptionBudget for critical resources such as kube-apiserver
Fixes #
```release-note
helm: support PodDisruptionBudget for resources
```

helm: support PodDisruptionBudget for resources

---

pkg/resourceinterpreter/default/native/dependencies.go
pkg/resourceinterpreter/default/native/dependencies_test.go
pkg/util/helper/policy.go
pkg/util/helper/policy_test.go
pkg/webhook/clusterpropagationpolicy/mutating.go
pkg/webhook/propagationpolicy/mutating.go

/kind feature
Fixes #
```release-note
`karmada-controller-manager`: Added dependencies of ServiceImport to the default interpreter.
```

feat: Refactor the mechanism for propagating serviceexport derived svc and eps.

---

pkg/registry/search/storage/cache.go

Cherry pick of #3966 on release-1.4.
#3966: fix addAnnotationWithClusterName crash
```release-note
`karmada-search`: Fixed a panic due to concurrent mutating objects in the informer cache.
```

Automated cherry pick of #3966: fix addAnnotationWithClusterName crash

---

pkg/detector/detector.go
pkg/detector/preemption.go

/kind feature
This PR provides a temporary solution for corner case: 
```
After the priority(.spec.priority) of PropagationPolicy changed from high priority (e.g. 5) to 
low priority(e.g. 3), we should try to check if there is a PropagationPolicy(e.g. with priority 4) 
that could preempt the targeted resources.
```
Fixes #
See https://github.com/karmada-io/karmada/pull/3684#issuecomment-1645075275 for the background discussion.
In addition, this PR focuses on dealing with `PropagationPolicy`, if it is acceptable, the `ClusterPropagationPolicy` should do a similar thing.
Test steps:
1. Apply two policies (`foo` with priority 5 and `bar` with priority …

Response to priority change of PropagationPolicy

---

pkg/detector/detector.go
pkg/detector/preemption.go

/kind feature
This PR provides a temporary solution for corner case:
```
After the priority(.spec.priority) of ClusterPropagationPolicy changed from high priority (e.g. 5) to 
low priority(e.g. 3), we should try to check if there is a ClusterPropagationPolicy(e.g. with priority 4) 
that could preempt the targeted resources.
```
**Which issue(s) this PR fixes:**
Fixes #
Part of https://github.com/karmada-io/karmada/issues/3787
**Special notes for your reviewer:**
See https://github.com/karmada-io/karmada/pull/3684#issuecomment-1645075275 for the background discussion.
In addition, this PR focuses on dealing with `ClusterPropagationPolicy`, the PR of `PropagationPolicy` see #3965.
**Test steps:**
1. Apply two policies (foo …

Response to priority change of ClusterPropagationPolicy

---

operator/pkg/tasks/init/crd.go
operator/pkg/util/util.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
pkg/karmadactl/cmdinit/utils/util.go

/kind cleanup
Reduce permissions for directories created by karmada itself.
From 755 to 700. Prevent unauthorized users from modifying content.
Fixes #
@RainbowMango @whitewindmills @XiShanYongYe-Chang

Remove the execute permission from the directory

---

pkg/apis/cluster/mutation/mutation.go
pkg/apis/cluster/mutation/mutation_test.go

/kind cleanup
transform zone to zones
part of https://github.com/karmada-io/karmada/issues/3952
@XiShanYongYe-Chang @whitewindmills
none

transform zone to zones

---

cmd/agent/app/agent.go
pkg/karmadactl/join/join.go
pkg/util/cluster.go

/kind feature
/kind cleanup
deprecate cluster-zone flag and introduce cluster-zones flag
part of https://github.com/karmada-io/karmada/issues/3952
```release-note
`karmadactl`:  Deprecated `--cluster-zone` flag which will be removed in future releases and introduced `--cluster-zones` flag.
```

feat: deprecate cluster-zone flag and introduce cluster-zones flag

---

pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
pkg/controllers/federatedhpa/federatedhpa_controller.go

/kind cleanup
Having only one CronFederatedHPA/FederatedHPA, it will be reconciled even if the status is updated, which is unnecessary.
Fixes #none
none
```release-note
```

cleanup: do not reconcile when the resoruce generation doesn't change

---

pkg/karmadactl/cmdinit/karmada/deploy.go
pkg/karmadactl/cmdinit/karmada/rbac.go
pkg/karmadactl/cmdinit/karmada/rbac_test.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go
pkg/karmadactl/cmdinit/utils/rbac.go
pkg/karmadactl/cmdinit/utils/rbac_test.go

feat: karmadactl init: grant clusterrole admin with karamda resource permission
Part of #3916 
```release-note
karmadactl init: grant clusterrole admin with karamda resource permission
```

feat: karmadactl init: grant clusterrole admin with karamda resource permission

---

pkg/controllers/federatedhpa/federatedhpa_controller.go
pkg/controllers/federatedhpa/metrics/client.go
pkg/metrics/resource.go

Part of #3946 
```release-note
Instrumentation: Introduced `federatedhpa_process_duration_seconds` and `federatedhpa_pull_metrics_duration_seconds` for FederatedHPA, which will be emitted by `karmada-controller-manager`.
```

feat: add performance metrics for FederatedHPA

---

pkg/apis/policy/v1alpha1/well_known_constants.go
pkg/apis/work/v1alpha2/well_known_constants.go
pkg/controllers/binding/common.go
pkg/controllers/binding/common_test.go
pkg/controllers/execution/execution_controller.go
pkg/controllers/execution/execution_controller_test.go
pkg/controllers/status/work_status_controller_test.go
pkg/detector/detector.go
pkg/detector/preemption.go
pkg/util/annotation.go
pkg/util/memberclusterinformer/memberclusterinformer_test.go
test/helper/resource.go

/kind feature
As mentioned in #4000
Part of #4000 
none
```release-note
`karmada-controller-manager`: Include the UID of the owner resource in labels and provide the details in annotations. If users are using related labels as label selectors, they should switch to using the UID as the label selector.
```

feature: Add the UID of the owner resource in labels and include the details in annotations.

---

pkg/scheduler/core/spreadconstraint/group_clusters.go
pkg/scheduler/core/spreadconstraint/select_clusters_test.go

/kind feature
/kind cleanup
Adopt `zones` in scheduler spread by constraints.
part of https://github.com/karmada-io/karmada/issues/3952
@RainbowMango @whitewindmills @huone1 

feat: adopt zones in scheduler spread by constraints

---

go.mod
pkg/util/proxy/proxy.go
pkg/util/proxy/upgrade_dialer.go
pkg/util/proxy/upgrader.go

/kind bug
In case of a member cluster joined Karmada with a proxy([like apiserver-network-proxy](https://karmada.io/docs/next/userguide/clustermanager/working-with-anp/)), the `karmadactl exec` not work and rasing errors:
```
-bash-5.0# karmadactl exec -n karmada-system -C member3 karmada-agent-7f65fcc9b7-b59bm -- ls 
error: You must be logged in to the server (Unauthorized)
```
Fixes #
Reproduce steps:
1. Launch Karmada environment by `hack/local-up-karmada.sh` against v1.7.0.
2. Deploy apiserver-network-proxy as per [Deploy ANP for Pull mode](https://karmada.io/docs/next/userguide/clustermanager/working-with-anp/) docs which will guide you to :
* …

karmadactl exec command not work with clusters that enabled proxy

---

.github/workflows/release.yml

/kind cleanup
Remove [update-krew-index](https://github.com/karmada-io/karmada/blob/11fac252b618dd26de530293e60b9faab9872507/.github/workflows/release.yml#L39-L46) from branch release-1.6.
Fixes #4019
```release-note
NONE
```

stop update krew for release 1.6

---

pkg/karmadactl/addons/search/manifests.go
pkg/karmadactl/addons/search/search.go
pkg/karmadactl/cmdinit/cert/cert.go
pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go

/kind feature
Users may have existing etcd cluster which is under well maintenance by a team, so it's better to use such etcd cluster, rather than setup new one. (a poor one, maybe)
Fixes #3897
~~**NOT** tested yet, for review only, if this pr is worth to go on finishing, I will continue.~~
```release-note
`karmadactl`: The `init` now can setup production ready HA control plane by using an external HA etcd cluster.
```

karmadactl init with external etcd

---

go.mod
pkg/util/proxy/proxy.go
pkg/util/proxy/upgrade_dialer.go
pkg/util/proxy/upgrader.go

Cherry pick of #4020 on release-1.7.
#4020: fix karmada can not execute exec command with proxy url and
```release-note
`karmada-aggregated-apiserver`: Fixed the issue that can not proxy `exec` request to a proxy issue.
```

Automated cherry pick of #4020: fix karmada can not execute exec command with proxy url and

---

artifacts/deploy/karmada-aggregated-apiserver-apiservice.yaml
artifacts/deploy/karmada-metrics-adapter-apiservice.yaml
artifacts/deploy/karmada-metrics-adapter.yaml
artifacts/deploy/karmada-search-apiservice.yaml
hack/deploy-karmada.sh
hack/deploy-metrics-adapter.sh

/kind feature
**Backupground:** `insecureSkipTLSVerify=true` means prohibit clientside from verifing the cert of serverside, this is an unsafe configuration, we can avoid unnecessary unsafe configurations.
This PR mainly aims to remove `insecureSkipTLSVerify` in YAML artifacts used by `deploy-karmada.sh`.
part of #4024
I have finished following verification test：
> kubectl --context karmada-apiserver get apiservice | grep -E 'NAME | karmada-system'
> E0904 21:14:51.103247 3048272 memcache.go:287] couldn't get resource list for custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0904 21:14:51.103864 3048272 …

remove insecureSkipTLSVerify in local-up-karmada script

---

charts/karmada/templates/_helpers.tpl
charts/karmada/templates/_karmada_apiservice.tpl
charts/karmada/templates/pre-install-job.yaml

/kind feature
**Backupground:** `insecureSkipTLSVerify=true` means prohibit clientside from verifing the cert of serverside, this is an unsafe configuration, we can avoid unnecessary unsafe configurations.
This PR mainly aims to remove `insecureSkipTLSVerify` in helm chart.
part of #4024
You can test `helm install` by following bash script:
```bash
#!/bin/bash
kind delete clusters --all; rm -r ~/.karmada/; rm ~/.kube/*.config; rm -r /etc/karmada
cd /root/home/gopath/src/github.com/karmada
hack/create-cluster.sh karmada-host ~/.kube/karmada.config
export KUBECONFIG=~/.kube/karmada.config:~/.kube/karmada-apiserver.config
for img in `cat …
```

remove insecureSkipTLSVerify in helm chart

---

pkg/detector/policy.go

/kind flake
remove the `ApplyPolicyFailed` event for objects not match any policy and add a log for debugging purposes.
Fixes #4038
```release-note
`karmada-controller-manager`: Skip emitting the `ApplyPolicyFailed` event for the resource template which does not match any PropagationPolicy.
```

Don't send an event when the object not matched any propagation policy

---

operator/pkg/tasks/deinit/component.go

/kind bug
Fixes #4030
When the karmada instance is removed, the metrics-adapter does not have a corresponding de-init, causing the pod to remain. 
```release-note
`karmada-operator`: Fixed the issue that karmada-metrics-adapter was not removed after deleting a Karmada instance.
```

uninstall metrics adapter when karmada cluster remove

---

pkg/controllers/status/cluster_status_controller_test.go
pkg/controllers/status/work_status_controller_test.go
pkg/util/membercluster_client_test.go

/kind feature
Backupground: insecureSkipTLSVerify=true means prohibit clientside from verifing the cert of serverside, this is an unsafe configuration, we can avoid unnecessary unsafe configurations.
This PR mainly aims to remove insecureSkipTLSVerify in `UT`.
part of #4024
```release-note
none
```

remove insecureSkipTLSVerify in UT test

---

operator/pkg/tasks/deinit/component.go

Cherry pick of #4056 on release-1.7.
#4056: uninstall metrics adapter when karmada cluster remove
```release-note
`karmada-operator`: Fixed the issue that karmada-metrics-adapter was not removed after deleting a Karmada instance.
```

Automated cherry pick of #4056: uninstall metrics adapter when karmada cluster remove

---

operator/pkg/controller/karmada/planner.go
operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/etcd/etcd.go
operator/pkg/controlplane/metricsadapter/metricsadapter.go
operator/pkg/controlplane/webhook/webhook.go
operator/pkg/util/patcher/pather.go

/kind feature
The karmada operator does not support users to explicitly set the resource scale of each component. But resource planning will be different in different scenarios, so we can provide explicit configuration
from https://github.com/karmada-io/karmada/pull/3732#discussion_r1301425856
```release-note
`karmada-operator`: Support config required resources for each Karmada component.
```
Test Results
karmada instance yaml with resources config
```yaml
kind: Karmada
metadata:
spec:
components:
etcd:
local:
imageRepository: …
```

support config karmada components resources

---

cmd/agent/app/agent.go
cmd/agent/app/options/options.go
pkg/karmadactl/register/register.go

/kind bug
User want to registry cluster in pull mode with region as well as zones field
Fixes #
NONE
```release-note
`karmadactl`: Introduced `--cluster-zones` flag to `register` command to declare cluster zones during registering a cluster.
`karmada-agent`: Introduced `--cluster-zones` flag to declare cluster zones during registering a cluster.
```

make pull cluster to be able to register with zones

---

pkg/resourceinterpreter/default/native/aggregatestatus.go
pkg/resourceinterpreter/default/native/aggregatestatus_test.go
pkg/resourceinterpreter/default/native/reflectstatus.go
pkg/resourceinterpreter/default/native/reflectstatus_test.go

/kind feature
HPA status aggregation. Aggregate the HPA status from different clusters onto the control plane HPA resource template using a resource interpreter, with the involved state field being .status.currentReplicas.
part of #4057
You can test it by：
```bash
kind delete clusters --all; rm -r ~/.karmada/; rm ~/.kube/*config; rm -r /etc/karmada
hack/local-up-karmada.sh
export KUBECONFIG=~/.kube/karmada.config:~/.kube/members.config
cat >/tmp/hpa.yaml<<EOF
metadata:
name: nginx
labels:
app: nginx
horizontalpodautoscaler.karmada.io/name: nginx
spec:
replicas: 1
selector:
matchLabels:
app: nginx
template: …
```

aggregate the HPA status from member clusters into control plane

---

operator/pkg/controller/karmada/planner.go
operator/pkg/controlplane/apiserver/mainfests.go
operator/pkg/controlplane/manifests.go
operator/pkg/controlplane/metricsadapter/mainfests.go
operator/pkg/controlplane/webhook/mainfests.go
operator/pkg/tasks/init/upload.go

/kind feature
We should expose the kubeconfig to access the karmada apiserver after installing karmada instance.
So, reference the secret of kubeconfig to `Karmada.Status.SecretRef`.
```shell
kubectl get karmada -n karmada-test-08 karmada-test-08       
NAME              READY   AGE
karmada-test-08   True    21m
---
kubectl get secret -n karmada-test-08 karmada-test-08-admin-config -ojsonpath='{.data.kubeconfig}' | base64 -d > karmada-apiserver.config
---
kubectl --kubeconfig karmada-apiserver.config get crds
NAME                                                         CREATED AT
clusteroverridepolicies.policy.karmada.io                    2023-07-13T07:25:59Z
clusterpropagationpolicies.policy.karmada.io …
```

karmada-operator: add karmada apiserver kubeconfig to karmada status

---

pkg/karmadactl/register/register.go

/kind feature
make pull cluster to be able to register with proxy-server
Fixes #
```release-note
`karmadactl`: Introduced `--proxy-server-address` flag to `register` command to declare proxy server during registering a cluster.
```

make pull cluster to be able to register with proxy-server

---

cmd/controller-manager/app/controllermanager.go
pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller.go
pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller_test.go
vendor/k8s.io/client-go/scale/fake/client.go
vendor/modules.txt

/kind feature  
As https://github.com/karmada-io/karmada/issues/4057
Fixes #
```release-note
```

add replicas syncer for resources with HPA

---

artifacts/deploy/karmada-controller-manager.yaml
cmd/controller-manager/app/controllermanager.go
pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_controller.go
pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
pkg/controllers/hpareplicassyncer/hpa_scale_ref_worker.go
pkg/resourceinterpreter/default/native/aggregatestatus.go
pkg/resourceinterpreter/default/native/retain.go
pkg/resourceinterpreter/default/native/retain_test.go
pkg/util/constants.go

/kind feature
Write a controller to watch the creation of HPA. Once there is a change in HPA, It will add a label to the target resource pointed by HPA. Then we only need to check if the resource has this specific label here to determine whether we need to perform the retain operation.
part of #4058
~another mthod：#4075~
we should choose just one between two.
Test Method：same as #4064
Test Report：
```release-note
Introduced retain operation to deployments if it is controlled by a HPA and the HPA has been propagated, which means member cluster deployments replicas will be controlled by member cluster …
```

retain for hpa controlled Deployment resource (labels method)

---

pkg/controllers/federatedhpa/federatedhpa_controller.go

/kind bug
To fix  a nil pointer bug which panics karmada-controller-manager.
Following the FHPA guide outlined in our documentation and applying these FHPA resources in the karmada cluster can cause the karmada-controller-manager to panic.
```
apiVersion: autoscaling.karmada.io/v1alpha1
kind: FederatedHPA
metadata:
name: nginx
spec:
scaleTargetRef:
name: nginx
minReplicas: 1
maxReplicas: 10
behavior:
scaleDown:
stabilizationWindowSeconds: 10
scaleUp:
stabilizationWindowSeconds: 10
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 10
``` 
here is stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference …
```

fix fhpa panic when SelectPolicy is nil

---

.github/workflows/ci.yml

/kind flake
Handling or maximizing github runner out-of-disk space error.
Fixes #4107
Reason：Runner is assigned `84GB` disk by default, but the system itself and pre-installed software occupy nearly 68GB, besides there about `4GB` swap. Then, when we installed Karmada by `local-up-karmada.sh` script, it occupy about 10GB, so there's really not much space left.
before install Karmada:
after install Karmada:
Here comes the key point, **refer to [Handling or maximizing github runner out-of-disk space error:](https://saturncloud.io/blog/github-action-ecr-optimizing-disk-space/#handling-or-maximizing-github-runner-out-of-disk-space-error)**
here added two …

clean ci runner disk space

---

hack/install-cli.sh

/kind bug
The interactive doesn't work in the one click installation during a repeated installation/upgrade scenario.
Possible reason is that the pipe (|) transfers the standard input of the script to the output of the pipe, which causes some commands that require user interaction (such as mv) to not work properly. If need it to be interactive, redirect the standard input of the mv command to /dev/tty.
Fixes #4091
```release-note
NONE
```

Fix interactive checks in one-click installations

---

pkg/webhook/multiclusterservice/validating.go

/kind bug
Fix to validate spec.types of MultiClusterService Webhook
Fixes #
/cc @yike21 @XiShanYongYe-Chang 
```release-note
'karmada-webhook': Fixed to validate spec.types of MultiClusterService api.
```

Fix to validate spec.types of MultiClusterService Webhook

---

pkg/controllers/federatedhpa/federatedhpa_controller.go

/kind bug
To fix a nil pointer bug which panics karmada-controller-manager.
Following the FHPA guide outlined in our documentation and applying these FHPA resources in the karmada cluster can cause the karmada-controller-manager to anic.
```
apiVersion: autoscaling.karmada.io/v1alpha1
kind: FederatedHPA
metadata:
name: nginx
spec:
scaleTargetRef:
name: nginx
minReplicas: 1
maxReplicas: 10
behavior:
scaleDown:
stabilizationWindowSeconds: 10
scaleUp:
stabilizationWindowSeconds: 10
metrics:
- type: Resource
resource:
name: cpu
target:
type: Utilization
averageUtilization: 10
```
here is stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered] …
```

fix: fix fhpa controller panic when SelectPolicy is nil

---

.github/workflows/ci-schedule-compatibility.yaml
.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml

/kind cleanup
Kubernetes v1.28.2 is out, update karmada CI with v1.28.0
Fixes #
```release-note
Update CI with kubernetes v1.28.0
```

Update CI with 1.28

---

cmd/scheduler/app/options/options.go
cmd/scheduler/app/scheduler.go
pkg/scheduler/scheduler.go

/kind feature
schedulerOptions add support for RateLimiterOptions
Fixes #
```release-note
`karmada-scheduler`: Introduced rate limiter options including: `--rate-limiter-base-delay`, `--rate-limiter-max-delay`, `--rate-limiter-qps`, and `--rate-limiter-bucket-size`, the default value not changed compared to previous version.
```

schedulerOptions add support for RateLimiterOptions

---

.github/workflows/ci.yml

Cherry pick of #4106 on release-1.5.
#4106: clean ci runner disk space
```release-note
```

Automated cherry pick of #4106: clean ci runner disk space

---

operator/pkg/constants/constants.go

/kind feature
````bash
[root@master-01 ~]# k -n test get karmada.operator.karmada.io/karmada-demo -oyaml
kind: Karmada
metadata:
creationTimestamp: "2023-06-27T07:12:57Z"
finalizers:
- operator.karmada.io/finalizer
generation: 2
labels:
operator.karmada.io/disable-cascading-deletion: "false"
resourceVersion: "746734041"
uid: 423ea5fe-b848-4b5f-b51a-aaeed83b6ea7
spec:
components:
etcd:
local:
imageRepository: registry.k8s.io/etcd
imageTag: 3.5.9-0
replicas: 1
resources: {}
volumeData:
volumeClaim:
metadata: {}
spec:
accessModes:
- ReadWriteOnce
resources:
requests:
storage: 3Gi
karmadaAPIServer:
imageRepository: …
```

update karmada operator default karmada version

---

.github/workflows/ci-image-scanning.yaml

/kind cleanup
Runs Trivy as GitHub action to scan Docker container image for vulnerabilities. 
We talked about this task at [Community Meeting 2023-01-17](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit?pli=1#heading=h.yrs5d1w97tdg).
Fixes #
Please see https://github.com/zhzhuang-zju/karmada/actions/runs/6530626808/job/17730271059 for more specific effects.
```release-note
NONE
```

CI: add image scanning

---

pkg/scheduler/event_handler.go

/kind bug
enqueueAffectedBindings and enqueueAffectedCRBs add schedulerNameFilter
Fixes #
```release-note
`karmada-scheduler`: add schedulerName filter when enqueue affected RB/CRB
```

EnqueueAffectedBindings and enqueueAffectedCRBs add schedulerNameFilter

---

.github/workflows/ci-image-scanning.yaml

/kind cleanup
When the code is merged into the ```master``` branch, ```trivy``` will scan images for vulnerabilities. This PR uploads trivy scan results to GitHub Security tab for easy viewing and analysis.
Fixes #
none
```release-note
NONE
```

ci: upload trivy scan results to GitHub Security tab

---

pkg/scheduler/event_handler.go

Cherry pick of #4139 on release-1.7.
#4139: enqueueAffectedBindings and enqueueAffectedCRBs add
```release-note
```

Automated cherry pick of #4139: enqueueAffectedBindings and enqueueAffectedCRBs add

---

.github/workflows/ci.yml
Makefile

/kind cleanup
This PR enables unit tests for `karmada-operator` related functionalities, the tests under `./operator/...` will be launched by `make test` and the coverage will be uploaded to [CodeCov](https://codecov.io/gh/karmada-io/karmada) along with the others.
Fixes #
I happened to see the unit test is missing when I looked at #4130 at https://github.com/karmada-io/karmada/pull/4130#discussion_r1361937835.
```release-note
NONE
```

Enable unit test for operator and upload coverage to CODECOV

---

pkg/registry/search/storage/resourceregistry.go

Referring to #4141
we cannot access resource ```ResourceRegistry``` with its ```singularName```.
Fixes #4141
none
```release-note
`karmada-search`:  fix cannot access ResourceRegistry with its singularName.
```

fix: cannot access ResourceRegistry with its singularName

---

pkg/registry/search/storage/resourceregistry.go

Cherry pick of #4144 on release-1.5.
#4144: fix: cannot access ResourceRegistry with its singularName
```release-note
`karmada-search`: Fixed can not access ResourceRegistry issue due to misconfigured singular name.
```

Automated cherry pick of #4144: fix: cannot access ResourceRegistry with its singularName

---

pkg/registry/search/storage/resourceregistry.go

This reverts commit fab54b30c1a9b64f4ebaeebf67b9fe3aef85ae03.
Revert "fix: cannot access ResourceRegistry with its singularName". Branch release-1.5 itself does not have the problem described in issue #4141, and changing ```DefaultQualifiedResource: searchapis.Resource("resourceRegistries")``` to ```DefaultQualifiedResource: searchapis.Resource("resourceregistries")``` will cause incompatibility in the upgrade scenario.
Fixes #
none
```release-note
none
```

Revert "fix: cannot access ResourceRegistry with its singularName"

---

cmd/scheduler/app/options/options.go

/kind feature
scheduler add LeaderElection config
Fixes #
```release-note
`karmada-scheduler`: Introduced leaderElection options including: `--leader-elect-lease-duration`, `--leader-elect-renew-deadline`, `--leader-elect-retry-period`, the default value not changed compared to previous version.
```

Introduced leaderElection options including: `--leader-elect-lease-duration`, `--leader-elect-renew-deadline`, `--leader-elect-retry-period`

---

pkg/controllers/status/cluster_status_controller.go
pkg/modeling/modeling.go
pkg/modeling/modeling_test.go

Fix issue #3854 
karmada-controller-manager: panic: runtime error: index out of range
Fixes #3854 
none

Fix: karmada-controller-manager: panic: runtime error: index out of range

---

operator/cmd/operator/app/operator.go
operator/pkg/apis/operator/v1alpha1/defaults.go
operator/pkg/constants/constants.go
operator/pkg/init.go

/kind feature
operator can judge which version karmada to install by operator itself's image version, inteaed of using fixed version in constant variable. (so, we will no longger need to manually submit PR like #3718)
how to test it:
```bash
#!/bin/bash
kind delete clusters --all; rm -rf ~/.karmada/; rm -rf ~/.kube/*.config; rm -rf /etc/karmada
cd path/to/karmada  # clone my submited code, and cd to your karmada repo path
hack/create-cluster.sh karmada-host ~/.kube/karmada-host.config
export KUBECONFIG=~/.kube/karmada-host.config
export VERSION="latest"
export REGISTRY="docker.io/karmada"
make image-karmada-operator GOOS="linux" --directory=.
kind …
```

fix: karmada-operator install default version karmada

---

pkg/controllers/status/common.go
pkg/controllers/status/crb_status_controller.go
pkg/controllers/status/rb_status_controller.go

/kind bug
Referring to #4137
When the deployment is updated in spe, we need to trigger the status update. To resolve the inconsistent generation.
Fixes #4137
none
```release-note
`karmada-controller-manager`: Fixed inconsistent generation issue between `metadata.generation` and `status.observedGeneration`.
```

fix: Sync workload's status.observedGeneration if it's updated

---

.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
This PR updates the default Go version for CI and release bots to v1.20.10
Fixes #4166
```release-note
Karmada(v1.8) is now built with Go1.20.10.
```

Updated Golang version from v1.20.6 to v1.20.10

---

.github/workflows/release.yml

/kind cleanup
With the old workflow, it will generate the charts multiple times: https://github.com/karmada-io/karmada/actions/runs/6621950672/job/17987099745
Which is not necessary. So let's change it and only generate it one time and upload it.
Fixes #none
Test result: https://github.com/jwcesign/karmada/actions/runs/6626074810/job/17998272299
```release-note
```

ci: fix uploading chart assests multiple times

---

.github/workflows/ci-image-scanning.yaml

Previously, the results of the image scan were uploaded to ```security tab```, and only those with write permissions to this repo could see it. Now, the image-scanning results will be displayed in the new workflow, and anyone with read permissions can see it.
Fixes #none
Test result: https://github.com/zhzhuang-zju/karmada/actions/runs/6637457822
```release-note
```

ci: image-scanning increases results display

---

pkg/registry/search/storage/resourceregistry.go

/kind cleanup
Referring to #4144, there is a problem in the upgrade scenario of resource ```resourceregistry```.  We need to solve it, otherwise the relevant data will be lost after the upgrade.
Refer to #4141
none
```release-note
NONE
```

fix: resourceregistry is incompatible in the upgrade scenario

---

pkg/karmadactl/addons/metricsadapter/manifests.go
pkg/karmadactl/addons/metricsadapter/metricsadapter.go
pkg/karmadactl/addons/search/manifests.go
pkg/karmadactl/addons/search/search.go
pkg/karmadactl/cmdinit/cert/cert.go
pkg/karmadactl/cmdinit/karmada/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go
pkg/karmadactl/cmdinit/options/global.go
pkg/karmadactl/options/global.go

/kind feature
Backupground: insecureSkipTLSVerify=true means prohibit clientside from verifing the cert of serverside, this is an unsafe configuration, we can avoid unnecessary unsafe configurations.
This PR mainly aims to remove insecureSkipTLSVerify in `karmadactl`.
part of #4024
You can test by following bash script:
```bash
kind delete clusters --all; rm -rf ~/.karmada/; rm -rf ~/.kube/*.config; rm -rf /etc/karmada
cd /root/home/gopath/src/github.com/karmada
hack/create-cluster.sh karmada-host ~/.kube/karmada.config
export KUBECONFIG=~/.kube/karmada.config
make karmadactl
_output/bin/linux/amd64/karmadactl init
_output/bin/linux/amd64/karmadactl …
```

remove insecureSkipTLSVerify in karmadactl

---

charts/index.yaml

/kind feature
publishes 1.7.1 helm release
I am able to pull 1.7.1
```
Error: accumulating resources: accumulation err='accumulating resources from '../base/': '/Users/amir.alavi/workspace/k8s-clusterset/kustomize/base' must resolve to a file': recursed accumulation of path '/Users/amir.alavi/workspace/k8s-clusterset/kustomize/base': Error: chart "karmada" version "v1.7.1" not found in https://raw.githubusercontent.com/karmada-io/karmada/master/charts repository
: unable to run: ...
```
Follow up to https://github.com/karmada-io/karmada/releases/tag/v1.7.1
```release-note
`Helm chart`: Added helm index …
```

helm: index 1.7.1

---

pkg/registry/cluster/storage/proxy_test.go
pkg/registry/cluster/storage/storage.go
pkg/util/proxy/proxy.go
pkg/util/proxy/proxy_test.go

/kind feature
Fixes https://github.com/karmada-io/karmada/issues/4182
If I change the following line to false:
https://github.com/karmada-io/karmada/blob/3267155766f69083d211c4bc804e8bda4b18fd4d/pkg/util/proxy/proxy.go#L79
It will have the following error in `karmada-aggregated-apiserver`:
And karmadactl couldn't list the pods in member clusters:
With this PR, everything works fine
```release-note
`karmada-aggregated-apiserver`: Add ca to check the validation of the member clusters' server certificate.
```

feat: Add ca to check the validation of the member clusters' server certificate

---

pkg/karmadactl/cmdinit/kubernetes/deployments.go

/kind cleanup
Set --tls-min-version string with a security version VersionTLS13. Then we don't need to be concerned about the ciphers anymore.
Fixes #
fix CVE-2016-2183
According to the discussion results at https://github.com/karmada-io/karmada/pull/4070
```release-note
`karmadactl`: The `karmada-apiserver` and `karmada-aggregated-apiserver` installed by the `init` command will take `--tls-min-version=VersionTLS13` by default.
```

set MinVersion to VersionTLS13 for tlsconfig in karmada-apiserver

---

cmd/agent/app/agent.go
operator/pkg/controlplane/metricsadapter/mainfests.go
operator/pkg/karmadaresource/apiservice/apiservice.go
operator/pkg/karmadaresource/apiservice/manifest.go
operator/pkg/tasks/init/component.go
operator/pkg/tasks/init/karmadaresource.go
pkg/karmadactl/join/join.go

/kind feature
Backupground: insecureSkipTLSVerify=true means prohibit clientside from verifing the cert of serverside, this is an unsafe configuration, we can avoid unnecessary unsafe configurations.
This PR mainly aims to remove insecureSkipTLSVerify in `Operator`.
part of #4024
You can test by following bash script:
```bash
kind delete clusters --all; rm -rf ~/.karmada/; rm -rf ~/.kube/*.config; rm -rf /etc/karmada
cd /root/home/gopath/src/github.com/karmada
hack/create-cluster.sh karmada-host ~/.kube/karmada-host.config
export KUBECONFIG=~/.kube/karmada-host.config
export VERSION="latest"
export REGISTRY="docker.io/karmada"
make …
```

remove insecureSkipTLSVerify in operator

---

charts/karmada/templates/karmada-controller-manager.yaml

/kind bug
before
```
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
name: karmada-controller-manager
namespace: karmada-system
labels:
app: karmada-controller-manager
spec:
selector:
matchLabels:
app: karmada-controller-manager
maxUnavailable: 20%---  # <--- this is the issue
---
```
after:
```yaml
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
name: karmada-controller-manager
namespace: karmada-system
labels:
app: karmada-controller-manager
spec:
selector:
matchLabels:
app: karmada-controller-manager
maxUnavailable: 20%
---
```
N/A
```release-note
fixed helm render of …
```

fix: helm podDisruptionBudget for controller-manager

---

.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/lint-chart.yaml

/kind cleanup
helm chart testing action is broken, https://github.com/karmada-io/karmada/actions/runs/6706548301/job/18223260799
xref: 
- https://github.com/helm/chart-testing-action/issues/132
- https://github.com/helm/chart-testing-action/issues/133
I have try to update to v2.5.0 and it's not working. https://github.com/liangyuanpeng/karmada/actions/runs/6714930957 
And v2.6.0 can fix it.
Since we are using cosign separately, it is better to follow the notification to upgrade the installer version.
So this PR have two change:
- Update chart-testing-action to v2.6.0
- Update cosigin-installer to v3.1.1   see https://blog.sigstore.dev/cosign-releases-bucket-deprecation/
Fixes #
**Special …

Update chart-testing-action to v2.6.0 and cosigin-installer to v3.1.1

---

pkg/karmadactl/addons/metricsadapter/manifests.go
pkg/karmadactl/addons/search/manifests.go

/kind cleanup
Fixes #
https://github.com/karmada-io/karmada/issues/4191
```release-note
`karmadactl`: The `karmada-search` and `karmada-metrics-adapter` installed by the `addon` command will take `--tls-min-version=VersionTLS13` by default.
```

set MinVersion to VersionTLS13 for tlsconfig in karmada-search and karmada-metrics-adapter

---

operator/config/samples/karmada.yaml
operator/pkg/constants/constants.go
operator/pkg/tasks/init/karmadaresource.go
operator/pkg/util/util.go
operator/pkg/util/util_test.go

Cherry pick of #4130 on release-1.7.
#4130: Operator support work with crds v1.7.0
This PR have two changed:
- cherry pick of #4130
- fix typo for method of util ReplaceYamlForReg
```release-note
`karmada-operator`: Fixed can not load Karmada v1.7.0 crds issue.
```

[1.7] Automated cherry pick of #4130: Operator support work with crds v1.7.0

---

.github/workflows/release.yml

/kind feature
This PR adds the operator helm chart artifacts to the release, so in a future PR the charts/index.yaml file can be updated to point to these artifacts. Users will then be able to pull the operator chart. This follows the same flow as the existing karmada helm chart.
Currently, the release workflow only pushes the chart to the docker registry, but it utilizes the same name and tag as the image artifact, which results in [this error](https://github.com/helm/helm/issues/10968)
no existing issue to reference
```release-note
NONE
```

publish karmada operator helm chart archive

---

operator/pkg/karmadaresource/apiservice/apiservice.go
operator/pkg/karmadaresource/apiservice/manifest.go
operator/pkg/tasks/init/component.go
operator/pkg/tasks/init/karmadaresource.go

/kind bug
fix the latest Karmada-operator cannot install karmada instance
Fixes #4209
Two bugs fixed in this pr
1. Karmada instance Aggregated service is installed on the correct namespace karmada-system
2. Fix karmada instance Aggregated service externalName to the correct value, which should be the service corresponding to karmada control plane
the example instance yaml
```yaml
kubectl apply -f - <<EOF
kind: Karmada
metadata:
EOF
```
the results
```bash
➜  karmada git:(master) ✗ kubectl get po -n test
NAME                                                    READY   STATUS    RESTARTS   AGE …
```

fix karmada instance aggregated service externalName error

---

hack/update-estimator-protobuf.sh

/kind bug
latest protoc version：
```bash
$ protoc --version
libprotoc 25.0
```
but we validate protoc version as:
```shell
if [[ -z "$(which protoc)" || "$(protoc --version)" != "libprotoc 3."* ]]; then
```
actually `libprotoc 25.0` is ok, so we should adjust validation as
```shell
if [[ -z "$(which protoc)" || $(protoc --version | sed -r "s/libprotoc ([0-9]+).*/\1/g") -lt 3 ]]; then
```
> if protoc not exist or its version lower than 3.x.x, we report error
Fixes #4213
```release-note
none
```

fix libprotoc version validation error

---

pkg/search/proxy/store/util.go

/kind bug
When the `result` channel of `watchMux` is blocked, it will cause `goroutine` leak and lock race. this problem affects the client watch api interface to hang when consuming `watch.RestChan`.
fetch goroutine stack:
```
curl http://localhost:6062/debug/pprof/goroutine?debug=1
```
Through the `goroutine` stack below, there are `1892` goroutines blocked in `runtime_SemacquireMutex`.
```
1892 @ 0x439936 0x44a80c 0x44a7e6 0x466ba5 0x1a1a5fd 0x1a1a5de 0x1a1a32a 0x46acc1
967 @ 0x439936 0x405565 0x40511d 0x1a1a691 0x1a1a32a 0x46acc1
573 @ 0x439936 0x44a80c 0x44a7e6 0x466ba5 0x474fa5 0x476576 0x476555 0x1a1a132 0x18e1a0d 0x18ce325 0x16aadc2 0x18cd8fb 0x79d3cf 0x16acb6c 0x79d3cf 0x1a3cbcb 0x79d3cf 0x18da0a6 0x16aadc2 …
```

karmada-search: Fix lock race affects watch RestChan not close, causing client watch api to hang.

---

pkg/util/helper/workstatus.go

Cherry pick of #4226 on release-1.6.
#4226: only update necessary part of binding status
```release-note
`karmada-controller-manager`: only update `aggregatedStatus` and `conditions` fields during `binding-status controller` updating status of binding 
```

Automated cherry pick of #4226: only update necessary part of binding status

---

pkg/search/proxy/store/util.go

Cherry pick of https://github.com/karmada-io/karmada/pull/4212 on release-1.6.
```
karmada-search`: Fix lock race affects watch RestChan not close, causing client watch api to hang
```

cherry pick of #4212: Fix lock race affects watch RestChan not close, causing client watch api to hang.

---

pkg/karmadactl/get/get.go
pkg/karmadactl/top/top.go
pkg/karmadactl/top/top_pods.go
pkg/karmadactl/util/validate.go
pkg/karmadactl/util/validate_test.go

/kind feature
add cluster flags for karmadactl top pod
Fixes #4217 
Extracted some public methods for subsequent implementation of the ```top node``` command
```release-note
Add cluster flags to query the resource status of the cluster pod. Like
➜  karmada git:(top) ✗ karmadactl top po  -Cmember1
NAME         CLUSTER   CPU(cores)   MEMORY(bytes)   
mycurlpods   member1   0m           1Mi 
```

add cluster flags for karmadactl top pod

---

.github/workflows/ci-schedule-compatibility.yaml

Part of #4111
this PR have two change:
- let workflow of `APIServer compatibility` do not fail-fast
- split the step of setup `e2e test environment` to fix timeout
Since the workflow is scheduled to trigger, I will trigger it immediately in my repo.
https://github.com/liangyuanpeng/karmada/actions/runs/6864906349
This workflow is working for reproduce to problem of setup e2e test env timeout.
The error log say:
```shell
...
Waiting for running.................................................................................................................................................................................................. …
```

fix test env timeout of APIServer compatibility

---

pkg/detector/detector.go
pkg/detector/detector_test.go

/kind feature
While implementing Karmada to support the distribution of resources under the "kube-system" namespace, the "configmap/extension-apiserver-authentication" object created by kube-apiserver should not be distributed to member clusters.
Fixes #4228
NONE
```release-note
`karmada-controller-manager`: Ignored `configmap/extension-apiserver-authentication` from propagation.
```

Restrict “configmap/extension-apiserver-authentication” object from being distributed to member clusters

---

pkg/detector/detector.go

/kind bug
/kind cleanup
Fixes #4233
```release-note
`karmada-controller-manager`: Fix the bug that losing the chance to un-claim resource template in case of PropagationPolicy/ClusterPropagationPolicy is removed.
```

ensure resource template be un-claimed when deleting policy

---

pkg/resourceinterpreter/default/native/prune/prune.go

/kind cleanup
Since kubernetes 1.27,  `batch.kubernetes.io/job-name` and `batch.kubernetes.io/controller-uid` labels are added for job pods. It's add the prefix of `batch.kubernetes.io` for label.
This PR will resolve the problem of https://github.com/karmada-io/karmada/pull/4108#issuecomment-1752688150
And Aggregated Status of RB:
```yaml
Status:
Aggregated Status:
Applied Message:  Failed to apply all manifests (0/1): Job.batch "tools-n25m5" is invalid: [spec.template.metadata.labels[batch.kubernetes.io/controller-uid]: Invalid value: map[string]string{"app":"tools", "batch.kubernetes.io/controller-uid":"0325fbba-6129-43e9-89f4-c363d580dc76", "batch.kubernetes.io/job-name":"tools-n25m5", …
```

Remove label of job for kubernetes 1.27

---

pkg/resourceinterpreter/default/native/prune/prune.go

Cherry pick of #4160 on release-1.7.
#4160: Prune job label for kubernetes 1.27,prefix with
```release-note
`karmada-controller-manager`: Pruned job labels `batch.kubernetes.io/controller-uid` and `batch.kubernetes.io/job-name` which were introduced by Kubernetes 1.27.
```

Automated cherry pick of #4160: Prune job label for kubernetes 1.27,prefix with

---

artifacts/deploy/karmada-etcd.yaml
charts/karmada/templates/etcd.yaml
operator/pkg/controlplane/etcd/etcd.go
operator/pkg/controlplane/etcd/mainfests.go
pkg/karmadactl/cmdinit/kubernetes/statefulset.go

/kind cleanup
set golang's default secure cipher suites as etcd's cipher suites to fix [CVE-2016-2183](https://github.com/advisories/GHSA-w2rw-pv8p-h9c8).
Parts of  #4191
none
```release-note
Fixed CVE-2016-2183 by setting golang's secure cipher suites as etcd's cipher suites
```

set golang's secure cipher suites as etcd's cipher suites

---

docs/proposals/service-discovery/README.md

/kind design
In the process of implementing the program, it was found that some points of function implementation were not described in the proposal, so here is a revision to further refine the implementation of the program, and some additions to the implementation of the key points.
Fixes #
```release-note
NONE
```

Added MCS Kubernetes native implementation details

---

pkg/resourceinterpreter/defaultinterpreter/prune/prune.go

Cherry pick of #4160 on release-1.5.
#4160: Prune job label for kubernetes 1.27,prefix with
```release-note
`karmada-controller-manager`: Pruned job labels `batch.kubernetes.io/controller-uid` and `batch.kubernetes.io/job-name` which were introduced by Kubernetes 1.27.
```

[1.5] Automated cherry pick of #4160: Prune job label for kubernetes 1.27,prefix with

---

pkg/resourceinterpreter/default/native/prune/prune.go

Cherry pick of #4160 on release-1.6.
#4160: Prune job label for kubernetes 1.27,prefix with
```release-note
`karmada-controller-manager`: Pruned job labels `batch.kubernetes.io/controller-uid` and `batch.kubernetes.io/job-name` which were introduced by Kubernetes 1.27.
```

[1.6] Automated cherry pick of #4160: Prune job label for kubernetes 1.27,prefix with

---

cmd/aggregated-apiserver/app/options/options.go
pkg/aggregatedapiserver/apiserver.go
pkg/registry/cluster/storage/aggregate.go
pkg/registry/cluster/storage/proxy.go
pkg/registry/cluster/storage/storage.go
pkg/util/proxy/proxy.go

/kind feature
Fixes #
```release-note
`karmada-aggregated-apiserver`: Cross-cluster unified query
```

feat: Cross-cluster unified query

---

pkg/scheduler/core/common.go
pkg/scheduler/core/generic_scheduler.go

/kind feature
Expose assignReplicas and selectClusters function to external schedulers
Fixes #4279
@wangyang0616
```release-note
none
```

Expose assignReplicas and selectClusters function to external schedulers

---

go.mod
pkg/apis/policy/v1alpha1/well_known_constants.go
pkg/apis/work/v1alpha2/well_known_constants.go
pkg/controllers/binding/common.go
pkg/controllers/binding/common_test.go
pkg/controllers/execution/execution_controller.go
pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/detector/detector.go
pkg/detector/preemption.go
pkg/util/helper/work.go
pkg/util/label.go
pkg/util/label_test.go

/kind feature
Referring to https://github.com/karmada-io/karmada/issues/4000
Part of https://github.com/karmada-io/karmada/issues/4000
none
```release-note
`karmada-controller-manager`: add resource id label to PP/CPP/RB/Work.
```

feat: add resource id label

---

pkg/karmadactl/promote/promote.go

Part of #4036 
WIP
```release-note
karmadactl: support promote dependent resources automatically
```

feat: support promote dependent resources automatically

---

pkg/apis/cluster/mutation/mutation.go
pkg/apis/cluster/mutation/mutation_test.go
pkg/apis/cluster/types.go
pkg/apis/cluster/v1alpha1/types.go
pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
pkg/apis/cluster/validation/validation.go
pkg/apis/cluster/validation/validation_test.go
pkg/controllers/status/cluster_status_controller_test.go
pkg/estimator/client/general.go
pkg/modeling/modeling.go
pkg/modeling/modeling_test.go
pkg/registry/cluster/strategy_test.go

/kind feature
resourceModels supports extended resources
Fixes #4050
Demo：https://h3ld32xlpo.feishu.cn/wiki/Rj5mwS3TCigHY4kMKzhcqTggnlg
A perfect way to edit extension resource model in cluster object is like:
```shell
for cluster in "member1" "member2"; do
kubectl --context karmada-apiserver patch cluster ${cluster} -n karmada-system --type='json' -p '[
{"op": "add", "path": "/spec/resourceModels/0/ranges/-", "value": {"name": "karmada.io/gpu", "min": "0", "max": "4"}},
{"op": "add", "path": "/spec/resourceModels/1/ranges/-", "value": {"name": "karmada.io/gpu", "min": "4", "max": "8"}},
{"op": "add", "path": "/spec/resourceModels/2/ranges/-", …
```

resourceModels supports extended resources

---

charts/karmada/templates/_helpers.tpl
charts/karmada/templates/_karmada_apiservice.tpl
charts/karmada/templates/karmada-metrics-adapter.yaml
charts/karmada/values.yaml

/kind feature
feat: support install metrics adapter with chart
Fixes #3626 
Testing result:
1.Install
2.join cluster
3.query metrics
```release-note
`karmada-metrics-adapter`: Support install metrics-adapter with helm.
```

feat: support install metrics adapter with chart

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
pkg/apis/networking/v1alpha1/service_types.go
pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
pkg/generated/openapi/zz_generated.openapi.go
pkg/webhook/multiclusterservice/validating.go
pkg/webhook/multiclusterservice/validating_test.go

Referring to https://github.com/karmada-io/karmada/pull/4287
none
```release-note
```

api: define API for MultiClusterService

---

hack/create-cluster.sh

/kind feature
improvement of create-cluster.sh script, so that it can support MacOS
* MacOS not support `mktemp --suffix`
* In `date +%s%N` command, not support `%N` format
Fixes #4294
CC @chaunceyjiang
Test Report：
```shell
$ hack/create-cluster.sh member4  ~/.kube/member4.config
Creating cluster "member4" ...
Context "kind-member4" renamed to "member4".
Cluster "kind-member4" set.
cluster "member4" is created successfully!
You can now use your cluster with:
kubectl cluster-info --context member4 --kubeconfig /Users/chaosi/.kube/member4.config
```
```release-note
none
```

create cluster script support MacOS

---

operator/pkg/controlplane/apiserver/mainfests.go
operator/pkg/controlplane/metricsadapter/mainfests.go

/kind bug
Found a `tab character` that violates indentation.
fixed operator manifests format.
The origin pr:  https://github.com/karmada-io/karmada/pull/4198
```release-note
NONE
```

karmada-operator: fixed operator manifests format

---

operator/pkg/certs/certs.go

/kind bug
Correct DNSNames of karmada-apiserver certificate in operator installation mode
Fixes #4322
NONE
```release-note
NONE
```

Correct DNSNames of karmada-apiserver certificate in operator installation mode

---

cmd/controller-manager/app/controllermanager.go
pkg/apis/networking/v1alpha1/service_types.go
pkg/apis/networking/v1alpha1/well_known_constants.go
pkg/controllers/multiclusterservice/mcs_controller.go
pkg/events/events.go
pkg/util/constants.go
pkg/util/helper/mcs.go

/kind feature
Referring to https://github.com/karmada-io/karmada/pull/4287
none
```
`karmada-controller-manager`: Introduced `multiclusterservice` controller to sync MultiClusterService.
```

feat: List&watch mcs and service, reconcile the work in execution namespace

---

pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/util/constants.go
pkg/util/helper/mcs.go

/kind feature
Firstly, member1 and member2 are in the consumption clusters set,
Then, the consumption clusters set changes to member1.
We should clean the endpointslice dispatched to member2 before.
Fixes #none
none
```release-note
```

feat: clean the endpointslice if the current cluster is not in the mcs consumption clusters

---

artifacts/agent/karmada-agent.yaml
artifacts/deploy/karmada-controller-manager.yaml
cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/controllers/multiclusterservice/mcs_controller.go
pkg/features/features.go
pkg/util/constants.go
test/e2e/mcs_test.go

/kind feature
Add `MultiClusterService` FeatureGate to allow users to decide whether to enable MultiClusterService functionality.
Part of #4294 
```release-note
Introduced `MultiClusterService` feature gate which now defaults to `alpha`.
```

Add MultiClusterService FeatureGate

---

test/e2e/federatedresourcequota_test.go

There is e2e failure: https://github.com/karmada-io/karmada/actions/runs/7057108479/job/19210332348
The reason is:
And I tried in my local env, if there is a resource quota in the ns, the pod creation(without setting resource requests will be rejected):
There are too many resource without the resource request setting: https://github.com/karmada-io/karmada/blob/61283676bb7fe72041c22fea18f476eaaff6d29a/test/helper/resource.go#L233
So, let's just make FederatedResourceQuota e2e as serial to avoid affecting other e2e.
Fixes #none
```release-note
```

e2e: make FederatedResourceQuota e2e as serial to avoid affecting other e2e

---

pkg/util/lifted/deployment_test.go
pkg/util/lifted/federatedhpa.go
pkg/util/lifted/federatedhpa_test.go
pkg/util/lifted/lua_oslib_safe.go
pkg/util/lifted/validatingfhpa.go
pkg/util/lifted/validatingmci_test.go

Cherry pick of #4344 on release-1.8.
#4344: correct the license in the lifted directory
```release-note
NONE
```

Automated cherry pick of #4344: correct the license in the lifted directory

---

charts/index.yaml

/kind feature
This publishes the v1.8.0 release and adds the karmada-operator chart. The karmada-operator chart was added to the release in [this PR](https://github.com/karmada-io/karmada/pull/4205)
```release-note
`Helm chart`: Updated helm index for 1.8.0 release, and added the karmada-operator chart.
```

Update helm index to v1.8.0 and add the karmada-operator chart

---

.github/workflows/ci-schedule.yml

This PR is working for fix CI of `CI Schedule Workflow`, Now, it's always failed with kubernetes 1.21.0 and v1.22.7 of  member cluster, here is the error log:
```
[FAILED] Timed out after 420.001s.
Expected
<bool>: false
to equal
<bool>: true
In [It] at: /home/runner/work/karmada/karmada/test/e2e/framework/deployment.go:82 @ 12/03/23 18:24:15.332
Full Stack Trace
github.com/karmada-io/karmada/test/e2e/framework.WaitDeploymentPresentOnClusterFitWith({0xc00067d3e9, 0x7}, {0xc00079fd28, 0x11}, {0xc0006d3ce4, 0xc}, 0xc0009e7380)
/home/runner/work/karmada/karmada/test/e2e/framework/deployment.go:82 +0x62b
github.com/karmada-io/karmada/test/e2e/framework.WaitDeploymentPresentOnClustersFitWith.func1() …
```

Delete k8s v1.21 and v1.22 from CI Schedule Workflow.

---

pkg/controllers/multiclusterservice/mcs_controller.go
pkg/util/helper/mcs.go

/kind feature
Referring to https://github.com/karmada-io/karmada/pull/4287
**Which issue(s) this PR fixes:**
**Special notes for your reviewer:**
none
**Does this PR introduce a user-facing change?:**
`karmada-controller-manager`: Introduced `multiclusterservice` controller to sync MultiClusterService.

feat: sync mcs work when cluster joined or unjoin

---

pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/util/constants.go

/kind feature
Part of 
none
```release-note
`karmada-controller-manager`: dispatch eps to the newly joined consumption clusters
```

feat: dispatch eps to the newly joined consumption clusters

---

cluster/images/Dockerfile
cluster/images/buildx.Dockerfile
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy_test.go

/kind cleanup
bump alpine to 3.18.5 to address CVE-2023-5363
Fixes #
```bash
➜  karmada git:(master) ✗ trivy image --format table  docker.io/karmada/karmada-operator:new 
2023-12-06T10:42:09.997+0800    INFO    Need to update DB
2023-12-06T10:42:09.997+0800    INFO    DB Repository: ghcr.io/aquasecurity/trivy-db
2023-12-06T10:42:09.997+0800    INFO    Downloading DB...
41.17 MiB / 41.17 MiB [-----------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 1.89 MiB p/s 22s
2023-12-06T10:42:33.531+0800    INFO    Vulnerability scanning is …
```

bump alpine to 3.18.5 to address CVE concerns

---

charts/karmada/templates/karmada-metrics-adapter.yaml

/kind bug
With this change in v1.8: https://github.com/karmada-io/karmada/pull/4303, karmada-metrics-adapter is part of the helm chart when install karmada.
This change is to make karmada-metrics-adapter installation in components with host when set.
```release-note
NONE
```

make metrics-adapter chart installation optional

---

cluster/images/Dockerfile
cluster/images/buildx.Dockerfile
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy_test.go

Cherry pick of #4376 on release-1.8.
#4376: bump alpine to 3.18.5 to address CVE concerns
```release-note
`release1.8`: The base image `alpine` now has been promoted from `alpine:3.18.3` to `alpine:3.18.5`
```

Automated cherry pick of #4376: bump alpine to 3.18.5 to address CVE concerns

---

.github/ISSUE_TEMPLATE/question.md
ADOPTERS.md
docs/proposals/resource-aggregation-proxy/README.md
samples/guestbook/README.md

/kind cleanup
Fix wrong reference website for docs.
Fixes #
```release-note
NONE
```

Fix wrong reference website for docs.

---

charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
pkg/apis/work/v1alpha1/work_types.go

/kind feature
When we debug, `kubectl get work -A` is only shown the `NAME`, not `KIND`, which will take more time to check the kind of manifests of work.
So directly show the kind by additionalPrinterColumns.
Fixes #
The best is to show all kind of manifests, because it possibly contains multi manifests in one work. But I don't find an easy way to implement it. Now, it only show the first manifests kind.
```
[root@master67 ~]# kapi get work -A
NAMESPACE            NAME                              KIND                 APPLIED   AGE
karmada-es-member1   cert-manager-674b866f4c           Namespace …
```

Add additionalPrinterColumns `KIND` for Work CRD

---

pkg/controllers/status/common.go
pkg/util/helper/patch.go
pkg/util/helper/patch_test.go

Change-Id: Ia0b5fde0b9d69f73aa6c2e3135e2590a6a503075
/kind cleanup
Discribed in  #4093
Fixes #4093
```release-note
`karmada-controller-manager: use Patch() instead of Update() when updating workload status because error rate is too high.`
```

Use Patch() when binding-status controller update workload's status

---

charts/karmada/templates/karmada-descheduler.yaml
charts/karmada/templates/karmada-scheduler-estimator.yaml
charts/karmada/templates/karmada-webhook.yaml

- add resources to webhook chart
- add descheduler as part of container's name
Does webhook need livenessProbe?
Fixes #
```release-note
```

add resources to webhook chart

---

pkg/util/proxy/proxy.go

Fixes #4370 
```
`karmadactl`: Fixed return err in case of  secret.spec. caBundle is nil
```

fix(util/proxy): fix tls.config when secret.spec.caBundle is nil

---

pkg/util/proxy/proxy.go

Cherry pick of #4371 on release-1.8.
#4371: fix(util/proxy): fix tls.config when secret.spec.caBundle is
```release-note
`karmadactl`: Fixed return err in case of `secret.spec.caBundle` is nil
```

Automated cherry pick of #4371: fix(util/proxy): fix tls.config when secret.spec.caBundle is

---

charts/karmada/README.md
charts/karmada/templates/karmada-scheduler-estimator.yaml
charts/karmada/values.yaml

/kind feature
make estimator config in helm values as a list
https://github.com/karmada-io/karmada/issues/4050#issuecomment-1832454205
Fixes #4368
```release-note
```

make estimator config in helm values as a list

---

.github/workflows/ci.yml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
Bump Golang version from v1.19.5 to v1.19.13 to address potential security concerns.
Fixes #
See Golang v1.19 release notes [here](https://go.dev/doc/devel/release#go1.19).
We will tag a new patch release for release-1.5, and it might be the last patch release as Karmada maintains the last 3 minor releases.
```release-note
Karmada is now built with Go1.19.13. 
```

[release-1.5] Bump Golang to v1.19.13

---

operator/pkg/apis/operator/v1alpha1/defaults.go
operator/pkg/constants/constants.go
operator/pkg/controlplane/search/mainfests.go
operator/pkg/controlplane/search/search.go
operator/pkg/karmadaresource/apiservice/apiservice.go
operator/pkg/karmadaresource/apiservice/manifest.go
operator/pkg/tasks/deinit/component.go
operator/pkg/tasks/init/component.go
operator/pkg/util/naming.go

/kind feature
feat: support install karmada search with operator
Fixes #
```bash
➜  karmada git:(master) ✗ export KUBECONFIG=~/.kube/karmada-host.config     
➜  karmada git:(master) ✗ kubectl get pods -nkarmada-system -owide     
NAME                                              READY   STATUS    RESTARTS   AGE   IP           NODE                         NOMINATED NODE   READINESS GATES
karmada-aggregated-apiserver-dc9bdf584-spw5b      1/1     Running   0          13m   10.34.0.9    karmada-host-control-plane   <none>           <none>
karmada-apiserver-7dc5fc74f6-2g2h4                1/1     Running   0          14m   10.34.0.8 …
```

feat: support install karmada search with operator

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
hack/update-crdgen.sh
operator/config/crds/operator.karmada.io_karmadas.yaml

/kind bug
generate Embedded ObjectMeta in the CRDs
Fixes #4128
none
```release-note
NONE
```

generate Embedded ObjectMeta in the CRDs

---

pkg/controllers/status/work_status_controller.go

/kind bug
1.K8s create multiple endpointslice for one service.
2.Karmada collects these endpointslice to control plane as work.
3.K8s delete some endpointslice.
4.Karmad work_status_controller.go will detect this and recreate it.
We expect the endpointslice will be deleted correctly.
Fixes #none
none
```release-note
`karmada-controller-manager`: Fixed the issue that always trying to re-create resources that should not be propagated.
```

skip recreating resources that is not supposed to be propagated

---

pkg/controllers/multiclusterservice/mcs_controller.go

/kind bug
When new clusters are joined, we should propagate the service to the new clusters.
Before, if the providerClusters/consumerClusters are empty, there was no modification even new clusters are joined.
In this scenario, the scheduler will not schedule the service to the newly joined clusters.
So we should update the RB to trigger it.
Fixes #none
none
```release-note
```

fix: Update RB once new clusters are added to trigger the propagation of service to these new clusters

---

charts/karmada/templates/post-delete-job.yaml
charts/karmada/templates/post-install-job.yaml
charts/karmada/templates/pre-install-job.yaml
charts/karmada/values.yaml

/kind feature
Could we also make "helm.sh/hook-delete-policy": hook-succeeded configurable in [post-install-job.yaml](https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/post-install-job.yaml#L20C5-L20C33). We want to keep the job pod for debugging issues if post-install job fails
Fixes part of #4368
```release-note
```

make hook-delete-policy in helm job configurable

---

.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
Bump Golang version from v1.20.4 to v1.20.12 to address potential security concerns.
Fixes #
See Golang v1.20 release notes [here](https://go.dev/doc/devel/release#go1.20).
```release-note
Karmada is now built with Go1.20.12. 
```

[release-1.6] Bump Golang to go1.20.12

---

.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
Bump Golang version from v1.20.6 to v1.20.12 to address potential security concerns.
Fixes #
See Golang v1.20 release notes [here](https://go.dev/doc/devel/release#go1.20).
```release-note
Karmada is now built with Go1.20.12. 
```

[release-1.7] Bump Golang to v1.20.12

---

.github/workflows/ci-schedule-compatibility.yaml
.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
Bump Golang version from v1.20.11 to v1.20.12 to address potential security concerns.
Fixes #
See Golang v1.20 release notes [here](https://go.dev/doc/devel/release#go1.20).
```release-note
Karmada is now built with Go1.20.12. 
```

[release-1.8] Bump Golang to v1.20.12

---

.github/workflows/ci.yml
.github/workflows/cli.yaml

/kind flake
We now run e2e test on multi releases version of Kubernetes, if e2e test failed at just one releases version, the other e2e test will be interrupted by fast fail strategy.
It is not conducive to check the root cause of failure, so it is advised to disable fast fail strategy.
Fixes #
```release-note
```

prevent CI from fast fail when just one k8s version e2e failed

---

pkg/detector/detector.go

/kind bug
Fixes #4233
```release-note
`karmada-controller-manager`: Fix the bug that losing the chance to un-claim resource template in case of deleting ClusterPropagationPolicy.
```

ensure resource template be un-claimed when deleting cluster policy

---

docs/CHANGELOG/CHANGELOG-1.8.md

This PR adds release notes for the coming v1.8.1 releases.
See the full change log from [here](https://github.com/karmada-io/karmada/compare/v1.8.0...release-1.8).
Fixes #
```release-note
NONE
```

Add release notes of v1.8.1

---

pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/controllers/multiclusterservice/mcs_controller.go
pkg/events/events.go
pkg/util/constants.go
pkg/util/helper/mcs.go

/kind feature
It's better to report the event if he service doesn't exist or endpointslice api is disabled, convenient for troubleshooting.
Fixes #none
test result:
```release-note
```

feat: report event when the service doesn't exist/when endpointslice api is disabled

---

pkg/controllers/status/work_status_controller.go

/kind bug
continue to execute InterpretHealth even if statusRaw is nil, otherwise, the graceful eviction controller could not parse the service's health status, the EvictionTask will be kept for 10min, details described in https://github.com/karmada-io/karmada/issues/4430
Fixes #4430
Test Report：
```yaml
status:
aggregatedStatus:
- applied: true
clusterName: member1
health: Healthy
- applied: true
clusterName: member2
health: Healthy
- applied: true
clusterName: member3
health: Healthy
conditions:
- lastTransitionTime: "2023-12-20T07:52:02Z"
message: Binding has been scheduled successfully.
reason: Success
status: "True"
type: Scheduled
- …
```

execute InterpretHealth even if statusRaw is nil

---

pkg/webhook/multiclusterservice/validating.go
pkg/webhook/multiclusterservice/validating_test.go

/kind feature
Currently, the north-south traffic routing is implemented through ServiceImport/ServiceExport by collecting EndpointSlice from member clusters to Karmada control plane for Work resources. 
The east-west MCS will also collect EndpointSlice for Work, and both sides will jointly manage the overlay of Work operations.
If both types are configured at the same time, when the north-south Work is overlaid (mcs label is deleted), the east-west MCS cannot synchronize the provider cluster's endpointslice to consumer clusters.
This PR temporarily prohibits mixed configuration and will resolve related conflict issues in future updates.
Part of …

feat: prevent updates to mcs.types or when multiple types are involved.

---

pkg/controllers/status/common.go
pkg/controllers/status/crb_status_controller.go
pkg/controllers/status/rb_status_controller.go

/kind bug  
**Which issue(s) this PR fixes**:  
Fixes #4339 
```release-note
`karmada-controllr-manager`: concurrency of `binding-status controller` inherit from the concurrency of `binding` declared in global options
```

add forType in binding status controller to inherit concurrency declared in global options

---

pkg/karmadactl/register/register.go

/kind bug
karmada agent deployment namespace and leader-elect-resouce-namespace should be consistent
now we install karmada agent in a new namespace, but leader-elect-resouce-namespace is karmada-system
Fixes #
```release-note
`karmadactl`:  Register cluster install karmada-agent should set leader-elect-resouce-namespace
```

register cluster install karmada-agent should set leader-elect-resouce-namespace

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go

/kind cleanup
NewManager option
// Deprecated: Use Cache.Namespaces instead.
Namespace string
// Deprecated: Use Cache.SyncPeriod instead.
SyncPeriod *time.Duration
Fixes #
```release-note
NONE
```

cleanup controllerruntime deprecated option SyncPeriod Namespace

---

pkg/controllers/status/common.go
pkg/controllers/status/crb_status_controller.go
pkg/controllers/status/rb_status_controller.go

Cherry pick of #4340 on release-1.6.
#4340: add forType in binding status controller to inherit
```release-note
`karmada-controllr-manager`: concurrency of `binding-status controller` inherit from the concurrency of `binding` declared in global options
```

Automated cherry pick of #4340: add forType in binding status controller to inherit

---

.github/workflows/ci-schedule-compatibility.yaml
.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/lint-chart.yaml

/kind cleanup
/hold
kubernetes 1.29 has been released, but there may be no need to rush to add 1.29 to CI. This is currently a placeholder.
Fixes #
```release-note
NONE
```

Add kubernetes v1.29.0 to CI

---

pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/core/util.go

/kind cleanup
simply optimizing the scheduler log
* lack of result of `assignReplicas`
* the meaning of logs of "Target cluster" is unclear
Fixes #
```release-note
none
```

simply optimizing the scheduler log

---

test/e2e/failover_test.go

/kind cleanup
Referring to https://github.com/karmada-io/karmada/issues/4455#issuecomment-1868693978, check whether the deployment disappears in the recovered clusters after cluster recovery.
Fixes #4455
```release-note
```

e2e: check whether the deployment disappears in the recovered clusters

---

go.mod
go.sum
vendor/modules.txt

/kind  cleanup
bump golang.org/x/crypto to v.0.17.0 to address CVE-2023-48795
Fixes #
```shell
(base) ➜  karmada git:(crypt) ✗ trivy image  --format table --exit-code  1 --ignore-unfixed --vuln-type  os,library  --severity  UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL karmada/karmada-controller-manager:latest 
2024-01-02T10:13:21.474+0800    INFO    Vulnerability scanning is enabled
2024-01-02T10:13:21.474+0800    INFO    Secret scanning is enabled
2024-01-02T10:13:21.474+0800    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-01-02T10:13:21.474+0800    INFO    Please see also …
```

bump golang.org/x/crypto to v.0.17.0

---

.golangci.yml
pkg/karmadactl/util/genericresource/visitor.go
test/e2e/framework/federatedresourcequota.go

/kind cleanup
Enable lint of revive(superfluous-else)
Partof https://github.com/karmada-io/karmada/issues/4490
```release-note
NONE
```

Cleanup: enable lint of revive(superfluous-else)

---

examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
hack/update-crdgen.sh

/kind bug
add Embedded metadata field for workload CRD
Fixes #4507 
none
```release-note
NONE
```

fix: add Embedded metadata field for workload CRD

---

.golangci.yml
pkg/controllers/federatedhpa/monitor/metrics.go

/kind cleanup
cleanup: enable revive(package-comments) checking,  this rule warns on undocumented packages and when packages comments are detached to the package keyword.
Parts of #4490 
```shell
(base) ➜  karmada git:(comment) ✗ hack/verify-staticcheck.sh
Using golangci-lint version:
golangci-lint has version 1.52.2 built with go1.20.2 from da04413a on 2023-03-25T18:11:28Z
Congratulations!  All Go source files have passed staticcheck.
```
```release-note
NONE
```

cleanup: enable revive(package-comments) checking

---

.golangci.yml

/kind cleanup
cleanup: enable revive (range/error-naming) checking.
- `range`: suggests a shorter way of writing ranges that do not use the second value.
- `error-naming`: variables of type error must be named with the prefix `err` for the sake of readability, 
```bash
> ./hack/verify-staticcheck.sh
Using golangci-lint version:
golangci-lint has version 1.52.2 built with go1.20.2 from da04413a on 2023-03-25T18:11:28Z
Congratulations!  All Go source files have passed staticcheck.
```
```release-note
```

cleanup: enable revive(range/error-naming) checking

---

.golangci.yml

/kind cleanup
cleanup: enable revive(errorf/dot-imports) checking. 
Description: Importing with . makes the programs much harder to understand because it is unclear whether names belong to the current package or to an imported package.
Description: It is possible to get a simpler program by replacing errors.New(fmt.Sprintf()) with fmt.Errorf(). This rule spots that kind of simplification opportunities.
Parts of #4490
```release-note
```

cleanup: enable revive(errorf/dot-imports) checking

---

pkg/dependenciesdistributor/dependencies_distributor.go

/kind bug
Fix misjudgment when updating attached binding.
We should return `nil` after successfully updating attached binding.
Fixes #
```release-note
NONE
```

Fix misjudgment when updating attached binding

---

.golangci.yml
pkg/controllers/federatedhpa/federatedhpa_controller.go

/kind cleanup
cleanup: enable revive(var-declaration rule) checking
Part of https://github.com/karmada-io/karmada/issues/4490
none
```release-note
```

cleanup: enable revive(var-declaration rule) checking

---

operator/pkg/certs/certs.go

/kind bug
When the client accesses the server, the client will verify whether the altNames of the server's certificate contains the server's domain name. If not, the verification will fail. 
Operator installation scenario, if karmada is installed in a namespace other than 'karmada-system', like 'test', there are two scenarios below：
- When karmada-apiserver access APIService, like v1alpha1.cluster.karmada.io, the cert of 'karmada-demo-aggregated-apiserver' will be verified to see if its altNames contains 'karmada-system/karmada-demo-aggregated-apiserver'
- When karmada-apiserver access webhook, like validatingwebhookconfigurations, the cert of 'karmada-demo-webhook' will be verified to see if its altNames contains …

add cfg.Namespace.svc to apiServerAltNames in operator installation mode

---

.golangci.yml
pkg/controllers/status/work_status_controller_test.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/util/proxy/upgrade_dialer.go

/kind cleanup
cleanup: enable revive(var-naming rule) checking
Part of #4490 
none
```release-note
```

cleanup: enable revive(var-naming rule) checking

---

.github/workflows/ci-schedule-compatibility.yaml

/kind cleanup
Test is using autoscaling/v2 for HorizontalPodAutoscaler, and this version is GA from kubernetes v1.23.0, so it always failed.
https://github.com/karmada-io/karmada/pull/4366 have cleanup it for CI Schedule Workflow and this PR is working for `APIServer compatibility`
see workflow of APIServer compatibility :
- https://github.com/karmada-io/karmada/actions/runs/7440408040
- https://github.com/karmada-io/karmada/actions/runs/7433650631
Releated:
- https://github.com/karmada-io/karmada/issues/4111
Fixes #
Once this PR is merged,    Most CIs of the workflow of `APIServer compatibility` will be green, except for the …

Delete k8s v1.21 and v1.22 from workflow of APIServer compatibility.

---

hack/local-up-karmada.sh
hack/util.sh

/kind feature
The `./hack/local-up-karmada.sh` did not execute successfully but no error was reported when I installed docker but docker was not enabled.
```shell
~/Code/github/karmada #v1.7.2 ❯ ./hack/local-up-karmada.sh                                                                                                                                                                                  
Preparing: 'kind' existence check - passed
Preparing: 'kubectl' existence check - passed
Preparing kindClusterConfig in path: /tmp/tmp.GcYYjKiQ1p
~/Code/github/karmada #v1.7.2 ❯ docker ps
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```
So I want to make sure docker is …

chore: verify whether docker is available by executing docker ps command

---

.golangci.yml
operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/search/search.go
operator/pkg/controlplane/webhook/webhook.go
pkg/controllers/hpareplicassyncer/hpa_replicas_syncer_predicate.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/status/cluster_status_controller_test.go
pkg/controllers/status/work_status_controller_test.go
pkg/karmadactl/promote/promote.go
pkg/metricsadapter/provider/externalmetrics.go
pkg/webhook/multiclusterservice/validating.go

/kind cleanup
This PR enables linting for the unused parameters in the functions.
Part of #4490
```release-note
NONE
```

Add linting for unused parameters

---

.golangci.yml

/kind cleanup
enable golangci-lint context-as-argument, context-keys-type and unexported-return checking
Part of #4490
```release-note
NONE
```

enable golangci-lint context-as-argument, context-keys-type and unexported-return checking

---

pkg/resourceinterpreter/customized/declarative/luavm/lua.go
pkg/util/lifted/lua/loadlib_safe.go
pkg/util/lifted/lua/oslib_safe.go
pkg/util/lifted/lua/oslib_safe_test.go

/kind cleanup
In order to use the Lua interpreter as safely as possible, we do not allow users to load modules using the path patterns defined in package.path (for Lua files) and package.cpath (for C libraries) when interpreting resources with lua scripts, which may potentially grant providers access to modules loaded outside the sandbox.
In addition, there are some basic functions that are also unsafe, referring to [the comments in gopher-lua](https://github.com/yuin/gopher-lua/issues/27#issuecomment-100413385). Therefore, we need to disable these functions.
Fixes #
```release-note
NONE
```

remove unsafe lua load library function

---

hack/scan-image-vuln.sh

/kind cleanup
Sometimes, we eliminate image vulnerabilities by upgrading dependencies. We can use this script to confirm locally whether the vulnerability has been completely eliminated.
Fixes #
```shell
(base) ➜  karmada git:(crypt) ✗ hack/verify-vuln.sh false CVE-2023-45142,CVE-2023-45333
Preparing: 'trivy' existence check - pass
start image scan
2024-01-02T16:19:00.464+0800    INFO    Vulnerability scanning is enabled
2024-01-02T16:19:00.465+0800    INFO    Secret scanning is enabled
2024-01-02T16:19:00.465+0800    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-01-02T16:19:00.465+0800    INFO …
```

add scan-image-vuln.sh to do image-scanning with trivy

---

.github/workflows/ci-schedule-compatibility.yaml
.github/workflows/ci-schedule.yml

Now `https://github.com/karmada-io/karmada/actions/workflows/ci-schedule.yml` and `https://github.com/karmada-io/karmada/actions/workflows/ci-schedule-compatibility.yaml` both failed almost, there are different errors(cluster creation timeout and e2e case failed).
The problem could be github resource limitations, I limit the concurrency to 2 and test it: https://github.com/jwcesign/karmada/actions/runs/6468715625/job/17561283243
Part of #4111 
none
```release-note
```

ci: fix schedule ci workflow failure

---

pkg/resourceinterpreter/customized/declarative/luavm/lua.go
pkg/util/lifted/lua/oslib_safe.go

/kind cleanup
The os package has already been added in `setlib` (using the wrong package name), there is no need to preload the os package again.
After modification, the `os.date()` and `os.time()` functions can be called normally.
Fixes #
```release-note
NONE
```

Remove redundant os preload in lua vm

---

hack/scan-image-vuln.sh

/kind cleanup
add flag -f format to scan-image-vuln.sh
```bash
(base) ➜  karmada git:(revive) ✗ hack/scan-image-vuln.sh -s -f json 
Preparing: 'trivy' existence check - pass
start image scan
---------------------------- the image scanning result of Image <<docker.io/karmada/karmada-controller-manager:latest>> ----------------------------
{
"SchemaVersion": 2,
"CreatedAt": "2024-01-20T10:08:27.58630979+08:00",
"ArtifactName": "docker.io/karmada/karmada-controller-manager:latest",
"ArtifactType": "container_image",
"Metadata": {
"OS": {
"Family": "alpine",
"Name": "3.19.0"
},
"ImageID": "sha256:147eb2dcae81afe73109bd8e1efacf6fcd90aa98c8d8739cac527651e84d78d8",
"DiffIDs": [ …
```

add flag -f format to scan-image-vuln.sh

---

.github/workflows/ci-schedule.yml

/kind cleanup
This workflow always failed:
```
[Invalid workflow file: .github/workflows/ci-schedule.yml#L45](https://github.com/karmada-io/karmada/actions/runs/7602918824/workflow)
The workflow is not valid. .github/workflows/ci-schedule.yml (Line: 45, Col: 9): Unexpected value 'max_attempts' .github/workflows/ci-schedule.yml (Line: 46, Col: 9): Unexpected value 'timeout_minutes'
```
So this pr is working for fix format error when introducing `nick-fields/retry`.
/assign @RainbowMango @jwcesign 
Here is the test of trigger : https://github.com/karmada-io/karmada/actions/runs/7605882134
Fixes # …

Fix github action yaml format

---

.golangci.yml
hack/verify-staticcheck.sh
pkg/apis/cluster/validation/validation_test.go
pkg/printers/internalversion/printers_test.go
pkg/scheduler/core/assignment.go
pkg/scheduler/core/spreadconstraint/select_clusters.go
pkg/search/proxy/store/util.go
pkg/util/binding_test.go
pkg/util/helper/workstatus.go
pkg/util/validation/validation.go

/kind cleanup
This PR bumps golangci-lint from v1.52.2 to v1.55.2.
Fixes #4490
This PR also included the left checks in #4490.
This PR fixed the following issues:
```bash
golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T12:59:25Z
pkg/apis/cluster/validation/validation_test.go:316:27: G601: Implicit memory aliasing in for loop. (gosec)
errs := ValidateCluster(&testCase.cluster)
^
pkg/scheduler/core/assignment.go:183:9: indent-error-flow: if block ends with a return statement, so drop this else and outdent its block (revive)
} else {
return state.scheduledClusters, nil
} …
```

bump golangci-lint to v1.55.2

---

pkg/search/controller.go
pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go

/kind bug
When crd exists in the karmada control plane but does not exist in the member cluster, search will report an error.
Checks for member crd should be added
karmada version: 1.5
Fixes #
```release-note
`karmada-search`: Add the logic of checking whether the resource API to be retrieved is installed in the cluster.
```

search add check member cluster api enable

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/detector/detector.go
pkg/detector/handler.go
pkg/detector/policy.go
pkg/generated/openapi/zz_generated.openapi.go
pkg/util/eventfilter/eventfilter.go
pkg/util/fedinformer/handlers.go
pkg/util/fedinformer/keys/keys.go
pkg/util/policy.go
pkg/util/worker.go

/kind feature
Introduced a lazy activation preference to PropagationPolicy/ClusterPropagationPolicy.
ActivationPreference indicates how the referencing resource template will be propagated, in case of policy changes.
If empty, the resource template will respond to policy changes immediately, in other words, any policy changes will drive the resource template to be propagated immediately as per the current propagation rules.
If the value is 'Lazy' means the policy changes will not take effect for now but defer to the resource template changes, in other words, the resource template will not be propagated as per the current propagation rules until there is an update on it.
This is an experimental feature that might help in …

Introduced a lazy activation preference to PropagationPolicy/ClusterPropagationPolicy

---

pkg/search/proxy/framework/plugins/cache/cache.go

if accept set application/json;as=Table;g=meta.k8s.io;v=v1beta1.
scope not support TableConvertor will return code 406.
Signed-off-by: niuyueyang <719415781@qq.com>
/kind bug
Fixes #
```release-note
support accept content type as=Table into karmada-search.
```

Support accept content type as=Table into karmada-search.

---

pkg/search/controller.go
pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go

Cherry pick of #4554 on release-1.8.
#4554: search add check member cluster api enable
```release-note
`karmada-search`: Add the logic of checking whether the resource API to be retrieved is installed in the cluster.
```

Automated cherry pick of #4554: search add check member cluster api enable

---

pkg/scheduler/core/assignment.go
pkg/scheduler/core/assignment_test.go

/kind bug
Please see https://github.com/karmada-io/karmada/issues/4560
Fixes #4560
Please note：
As described in: https://github.com/karmada-io/karmada/issues/4560#issuecomment-1911303202
Due to the changes in the score plugin, the scheduling results of instance counts may oscillate among multiple clusters.
We should find a better way to fix this in the future.
none
```release-note
`karmada-scheduler`: reschedule the replicas of the disappear clusters in PP/CPP.
```

fix: reschedule the replicas of the disappear clusters in PP

---

pkg/controllers/mcs/endpointslice_controller.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/controllers/multiclusterservice/mcs_controller.go
pkg/util/constants.go
test/e2e/mcs_test.go

/kind feature
We will ultimately follow the design document: https://docs.google.com/document/d/1FxgRW9k8udjNKUU_P-vIaRZx7AC1qDjA5UAtcuG3nIU/edit#heading=h.20scsy1urk74 to implement the management of EndpointSlice by listing and watching mcs/mci concurrently. Track this in issue https://github.com/karmada-io/karmada/issues/4292.
This PR is just a temporary fix for the concurrent use of mcs/mci.
None
none
```release-note
```

feat: add manager label to eps work to avoid the conflicts between mcs/serviceexport

---

pkg/search/proxy/framework/plugins/cache/cache.go

Cherry pick of #4580 on release-1.8.
#4580: if accept set
```release-note
karmada-search: support accept content type `as=Table` in the proxy global resource function.
```

Automated cherry pick of #4580: if accept set

---

cluster/images/Dockerfile
cluster/images/buildx.Dockerfile
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy_test.go

/kind cleanup
bump alpine to 3.19.1 to address[CVE-2024-0727](https://avd.aquasec.com/nvd/cve-2024-0727)
Fixes #4597
```sh
➜  karmada git:(image-alpine) ✗ make image-karmada-operator
set -e;\
target=$(echo karmada-operator);\
make $target GOOS=linux;\
VERSION='v1.7.0-alpha.1-858-g2c5163ffb' REGISTRY="docker.io/karmada" BUILD_PLATFORMS=linux/amd64 hack/docker.sh $target
BUILD_PLATFORMS=linux/amd64 hack/build.sh karmada-operator
!!! Building karmada-operator for linux/amd64:
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=amd64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.7.0-alpha.1-858-g2c5163ffb -X …
```

bump alpine to 3.19.1 to address CVE concerns

---

hack/tools/tools.go

/kind cleanup
The build constraint `// +build` has been deprecated since Go 1.17 and replaced by `//go:build`.
The redundant constraint was [introduced while we using Go1.17](https://github.com/karmada-io/karmada/pull/1299/files#r803441093). Now it's time to cleanup it.
Fixes #
Echo the [Go docs](https://pkg.go.dev/cmd/go#hdr-Build_constraints) here for reference:
> Go versions 1.16 and earlier used a different syntax for build constraints, with a "// +build" prefix. The gofmt command will add an equivalent //go:build constraint when encountering the older syntax.
```release-note
NONE
```

Remove deprecated build constraints

---

hack/tools/preferredimports/preferredimports.go
hack/verify-import-aliases.sh

/kind cleanup
```shell
(base) ➜  karmada git:(revive) ✗ hack/verify-import-aliases.sh 
checking-imports: 
/root/home/workspace/code/karmada/test/helper                                   etoota
```
The output result of the script ```hack/verify-import-aliases.sh``` is confusing. 
Refer to https://github.com/karmada-io/karmada/blob/0aec7b58dc2a3be1063345f83383f4b366921aee/hack/tools/preferredimports/preferredimports.go#L261-L265
the reason is that there is no line break, and `\r` is added, resulting in the output results overlapping on the same line.
Fixes #
```shell
(base) ➜  karmada git:(revive) ✗ hack/verify-import-aliases.sh
checking-imports: …
```

Optimize the display of the hack/verify-import-aliases.sh

---

operator/pkg/util/apiclient/idempotency.go

/kind bug
I deploy the karmada control plane by karmada-operator
when i modify the karmada CR, I hope the karmada-operator  redploy the karmada control plane
But I'm getting the following error
Fixes #4639
```release-note
```

fix: update service failed when reconcile

---

api/openapi-spec/swagger.json
cmd/controller-manager/app/controllermanager.go
pkg/controllers/remediation/eventhandlers.go
pkg/controllers/remediation/remedy_controller.go
pkg/controllers/remediation/util.go
pkg/util/gclient/gclient.go

/kind feature
Add remedy controller  to sync Cluster resource, according to the cluster status condition, condition matching is performed through remedy, and then the actions required to be performed by the cluster are calculated.
Fixes #
```release-note
NONE
```

Add remedy controller to reconcile with cluster status condition and remedy resource.

---

pkg/controllers/remediation/eventhandlers.go
pkg/controllers/remediation/remedy_controller.go

/kind bug
fix panic when updating `remedy.spec.clusteraffinity` to empty. 
This problem is introduced in #4655 .
Part of #4658
```release-note
NONE
```

fix panic when update remedy.spec.clusteraffinity to empty

---

docs/proposals/scheduling/activation-preference/lazy-activation-preference.md

/kind design
In the scenario where `Policy` responsibilities are separated from `Resource` responsibilities,  one role is dedicated to `Policy` management, which is referred to as cluster administrator, and the other role is dedicated to `Resource` management, which is referred to as user. The cluster administrator would preconfigure some `Policies` for users, then the users apply their own `Resources` and propagated them according to the preconfigured `Policy`.
However, the administrator has requests to modify the `Policy` in the future, such as migrating propagation clusters. As the current `Policy` modification is effective immediately, the modification will affect the propagation status of a large …

Proposal of the LazyActivation preference for Policy

---

charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
pkg/apis/remedy/v1alpha1/remedy_types.go
pkg/scheduler/framework/testing/mock_interface.go

/kind feature
Set the enum value for the `operator` field in Remedy API.
Part of #4658 
```release-note
NONE
```

Set enum value for operator in Remedy API

---

pkg/detector/preemption.go
vendor/github.com/emirpasic/gods/lists/arraylist/arraylist.go
vendor/github.com/emirpasic/gods/lists/arraylist/enumerable.go
vendor/github.com/emirpasic/gods/lists/arraylist/iterator.go
vendor/github.com/emirpasic/gods/lists/arraylist/serialization.go
vendor/github.com/emirpasic/gods/lists/lists.go
vendor/github.com/emirpasic/gods/queues/priorityqueue/iterator.go
vendor/github.com/emirpasic/gods/queues/priorityqueue/priorityqueue.go
vendor/github.com/emirpasic/gods/queues/priorityqueue/serialization.go
vendor/github.com/emirpasic/gods/queues/queues.go
vendor/github.com/emirpasic/gods/trees/binaryheap/binaryheap.go
vendor/github.com/emirpasic/gods/trees/binaryheap/iterator.go
vendor/github.com/emirpasic/gods/trees/binaryheap/serialization.go
vendor/modules.txt

/kind feature
/kind cleanup
Using the natural ordering properties of red-black trees to sort the listed policies to ensure the higher priority (Cluster)PropagationPolicy being processed first to avoid possible multiple preemption.
Fixes #
```release-note
NONE
```

Optimize deprioritized policy preemption logic

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
operator/pkg/controlplane/apiserver/apiserver.go

/kind feature
add extra annotations for service of karmada apiserver.
details please see below issue:
Fixes https://github.com/karmada-io/karmada/issues/4634
```release-note
`karmada-operator`: The service of `karmada-apiserver` is now able to be annotated to best fit third-party add-ons.
```

operator: add extra annotations for service of karmada apiserver

---

README.md

/kind cleanup
Generates the badge as per the `latest` release instead of the alpha release.
Fixes #
See the new badge at [here](https://github.com/RainbowMango/karmada/tree/pr_update_release_badge). (Before this PR gets merged.)
```release-note
NONE
```

Update release badge to show latest release

---

test/e2e/deploymentreplicassyncer_test.go
test/e2e/framework/hpa.go
test/helper/policy.go

This reverts commit a21848da138c73709d4c9aa861e5f5055b7950a3.
/kind flake
The e2e test in #4716 has cccasional error, just as https://github.com/karmada-io/karmada/actions/runs/8336573479/job/22814077291
This reason has been located, which is a bug in #4707.
Due to the current inconvenience of merging non-e2e codes, I revert this e2e PR first, and then submit a bugfix PR later.
Fixes #
```release-note
```

Revert "add e2e test for deployment replicas syncer"

---

pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller.go

/kind bug
fix deployment replicas syncer in case deployment status changed before label added
how to produce:
1. propagate deployment with 1 replicas to two clusters by static weight 1:1 strategy policy.
2. propagate hpa which `minReplicas=2` to two clusters.
then, we may observed the following results in order:
1. hpa scale deployment in member1 cluster from 1 to 2.
2. deployment status change collected, its status.replicas change from 1 to 2.
3. `hpaScaleTargetMarker` add label `retain-replicas` to deployment.
4. get deployment and see `ready/expect=2/1`
in this case, `deploymentReplicasSyncer` didn't do anything because after `retain-replicas` labeled, the deployment's `spec` and `status` had no changes.
**Which …

fix deployment replicas syncer in case deployment status changed before label added

---

test/e2e/lazy_activation_policy_test.go
test/helper/policy.go

/kind cleanup
We need to test the `Lazy activation` policy.
Part of: #4607
```release-note
NONE
```

Add e2e test for lazy propogation policy: Policy created before resource

---

.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-image.yml

/kind cleanup
cosigin team say it will happen in 1.13.x, need to update to v1.2.3 (: 
https://github.com/sigstore/cosign-installer/issues/158#issuecomment-2010958383
The reason is cosigin team publish a new TUF trust root, see https://blog.sigstore.dev/tuf-root-update/
verifyed it at full the workflow: https://github.com/liangyuanpeng/karmada/actions/runs/8367696249/job/22910549544
CI is green.
Fixes #4727
```release-note
Karmada images is signing with cosigin v2.2.3
```

chore: bump cosigin to v2.2.3.

---

pkg/detector/detector.go
pkg/util/helper/work.go

/kind bug
Using the `MergeAnnotation` function will filter out existing keys. When the key value that needs to be marked changes, such as policy preemption, resource recovery, we need to use the `ReplaceAnnotation` function to replace the value of the key in the annotation.
Fixes #
```release-note
`karmada-controller-manager`: Fixed incorrect annotation markup when policy preemption occurs.
```

fix wrong annotation marks on resource

---

pkg/controllers/mcs/endpointslice_controller.go
pkg/controllers/mcs/service_export_controller.go
pkg/util/constants.go

/kind bug
After the karmada control plane resource is deleted and the propagated resource in the member cluster is also deleted, but the deletion event of the `EndpointSlice` resource has not been processed by the controller in the control plane, the `karmada-controller-manager` is restarted due to an OOM reason. `EndpointSlice` resources are not deleted from the Karmada control plane.
Fixes #
```release-note
`karmada-controller-manager`: Fixed the issue of EndpointSlice residual in case of the karmada-controller-manager restart.
```

Fix eps remain when karmada-controller-manager restart

---

pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller.go
pkg/resourceinterpreter/default/native/reflectstatus.go

/kind bug
This PR mainly handles **two problem**:
**1、Problem 1**
we should make sure the latest collected status.replicas is synced from binding to template.
e.g: user set deployment.spec.replicas = 2, then sum replicas in binding.status becomes 2, however, if now deployment.status.replicas is still 1, we shouldn't update spec.replicas to 1 until status.replicas becomes 2.
**2、Problem 2**
as described in #4758, fix deployment replicas syncer in case that the `status.replicas` in `aggregatedStatus` of binding is 0.
actually, if member cluster deployment is controlled by hpa, its status.replicas must > 0 (since hpa.minReplicas > 0),
so, if its `status.replicas` is 0, means the status haven't been collected from member …

fix deployment replicas syncer in case that `status.replicas` haven't been collected from member cluster to template

---

pkg/controllers/binding/common.go
pkg/controllers/binding/common_test.go
pkg/controllers/execution/execution_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
pkg/controllers/status/work_status_controller.go
pkg/controllers/status/work_status_controller_test.go
pkg/util/objectwatcher/objectwatcher.go

/kind bug
Karmada will generate the work namespace/name labels on the resources propagated to member clusters:
- work.karmada.io/namespace
- work.karmada.io/name
When the created resource name is longer than 63 characters, those labels will cause the resource to fail to be created successfully in the member cluster.
So we need to remove those labels from resources propagated to member clusters.
Fixes #4683 
```release-note
karmada-controller-manager: remove the work namespace/name labels from resources propagated to member clusters
```

Remove work label on the member cluster resource

---

.github/workflows/cli.yaml

/kind cleanup
This PR updates the `engineerd/setup-kind` to eliminate the warnings. 
See #4669 for more details.
Fixes #
```release-note
NONE
```

Replace engineerd/setup-kind with helm/kind-action

---

pkg/detector/detector.go
pkg/util/helper/work.go

Cherry pick of #4751 on release-1.7.
#4751: fix wrong annotation marks on resource
```release-note
`karmada-controller-manager`: Fixed incorrect annotation markup when policy preemption occurs.
```

Automated cherry pick of #4751: fix wrong annotation marks on resource

---

pkg/detector/detector.go
pkg/util/annotation.go
pkg/util/annotation_test.go
pkg/util/helper/work.go
pkg/util/label.go

/kind cleanup
Learn from #4751, to avoid ambiguity and to be consistent with the Annotation naming convention:
https://github.com/karmada-io/karmada/blob/57c1989667d826864aa09105daa04434e2c75dd9/pkg/util/annotation.go#L29-L51
remove old MergeAnnotation func and rename ReplaceAnnotation to MergeAnnotation.
Fixes #
```release-note
NONE
```

remove old MergeAnnotation func and rename ReplaceAnnotation to MergeAnnotation

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go

/kind cleanup
When configuring CRD naming and scope the valid marker should be the format `+kubebuilder:resource:xxx`, but the operator mistakenly marked `+kubebuilder:xxx`, which makes the mark doesn't work.
Fixes #
I found this during updating the [controller-tools](https://github.com/karmada-io/karmada/blob/70afc1ad6d170bd4773b5e7a9735a4116816f814/hack/update-crdgen.sh#L22) to v0.12.0+, and I found the plural name of Operator changed to `Karmada` instead of `Karmadas`. That means the pinned plural name not work.
```release-note
NONE
```

Fixe invalid kubebuilder marker, that makes pinned plural name does not work.

---

charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
pkg/apis/autoscaling/v1alpha1/cronfederatedhpa_types.go
pkg/apis/autoscaling/v1alpha1/federatedhpa_types.go
pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go
pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
pkg/apis/networking/v1alpha1/ingress_types.go
pkg/apis/networking/v1alpha1/service_types.go
pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
pkg/apis/policy/v1alpha1/override_types.go
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/apis/remedy/v1alpha1/remedy_types.go
pkg/apis/work/v1alpha1/binding_types.go
pkg/apis/work/v1alpha1/work_types.go
pkg/apis/work/v1alpha2/binding_types.go

/kind cleanup
When the controller-tools generate the CRDs, it [guesses the plural name](https://github.com/kubernetes-sigs/controller-tools/blob/80fc62f695b13677135377f47b61c61908661f10/pkg/crd/spec.go#L66) by [github.com/gobuffalo/flect](https://github.com/gobuffalo/flect) if the plural name is not explicitly specified.
But the rule of generating plural names might change over different [github.com/gobuffalo/flect](https://github.com/gobuffalo/flect) versions. See https://github.com/kubernetes-sigs/controller-tools/pull/804#discussion_r1178098768 for an example.
So, this PR pin plural name for all APIs to avoid this unexpected change.
(We don't depend on [github.com/gobuffalo/flect](https://github.com/gobuffalo/flect), …

Pin plural name for all APIs to avoid unexpected change

---

pkg/util/helper/work.go
pkg/util/label.go
pkg/util/label_test.go

/kind bug
Fixes #4781
```release-note
karmada-controller-manager: Fix the problem that labels cannot be deleted via Karmada propagation.
```

labels cannot be deleted via Karmada propagation

---

cmd/metrics-adapter/app/options/options.go

/kind feature
add pprof option to metrics-adapter.
refer to [Profiling Karmada](https://karmada.io/docs/next/developers/profiling-karmada/#enable-profiling).
Fixes #
```release-note
```

add pprof option to metrics-adapter

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml
charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml
charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
hack/update-crdgen.sh
operator/config/crds/operator.karmada.io_karmadas.yaml

/kind cleanup
This PR bumps controller-tools and refreshes the generated CRDs.
Fixes #
Notable changes of controller-tools:
- v0.9.0 removed redundant .status of generated CRD
- v0.12.0 removed redundant .metadata.creationTimestamp of generated CRD
```release-note
NONE
```

Update controller-gen to v0.13.0

---

pkg/util/helper/work.go
pkg/util/label.go
pkg/util/label_test.go

Cherry pick of #4784 on release-1.9.
#4784: labels cannot be deleted via Karmada propagation
```release-note
karmada-controller-manager: Fix the problem that labels cannot be deleted via Karmada propagation.
```

Automated cherry pick of #4784: labels cannot be deleted via Karmada propagation

---

pkg/controllers/applicationfailover/crb_application_failover_controller.go
pkg/controllers/applicationfailover/rb_application_failover_controller.go
pkg/controllers/binding/binding_controller.go
pkg/controllers/binding/binding_controller_test.go
pkg/controllers/binding/cluster_resource_binding_controller.go
pkg/controllers/certificate/cert_rotation_controller.go
pkg/controllers/cluster/cluster_controller.go
pkg/controllers/cluster/taint_manager.go
pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
pkg/controllers/execution/execution_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
pkg/controllers/mcs/service_import_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/controllers/namespace/namespace_sync_controller.go
pkg/controllers/status/cluster_status_controller.go
pkg/controllers/status/cluster_status_controller_test.go
pkg/controllers/status/crb_status_controller.go
pkg/controllers/status/rb_status_controller.go
pkg/controllers/status/work_status_controller.go
pkg/controllers/status/work_status_controller_test.go
pkg/controllers/unifiedauth/unified_auth_controller.go

/kind cleanup
The Controller will requeue the Request to be processed again if an error is non-nil or Result.Requeue is true, an error is non-nil has higher priority. Therefore, there is no need to set Result.Requeue to true when the error is non-nil.
Fixes #
```release-note
NONE
```

when controller return error is non-nil not need to set Result.Requeue 

---

pkg/util/helper/work.go

/kind bug
Since labels will be overwritten every time they are updated and created, this causes `work.karmada.io/permanent-id` to constantly change.
I add some debug logs in karmada-webhook to capture the bug:
Fixes #
```release-note
karmada-controller-manager: Fix the problem that work.karmada.io/permanent-id constantly changes with every update.
```

Use merge strategy to avoid work.karmada.io/permanent-id changes

---

pkg/metricsadapter/adapter.go
pkg/metricsadapter/controller.go
pkg/metricsadapter/provider/resourcemetrics.go

When there is a large amount of pod usage in the member cluster, metrics-adapter will consume a lot of memory. The reason is that it caches all the information of all pods in the cluster. However, we don't need all this information, so we trim some of the information to reduce memory usage.
/kind bug
Fixes #
The core idea of this PR is to use `TransformFunc` to trim the fields that pod and node need to buffer. Currently, it only retains fields such as `name`, `namespace`, `labels`, etc. Other fields are not needed, so we do not need to cache them.
```release-note
karmada-metrics-adapter: reduce memory …
```

karmada-metrics-adapter: reduce memory usage

---

cmd/kubectl-karmada/kubectl-karmada.go

/kind cleanup
/kind bug
The command `kubectl-karmada` cannot be automatically completed because `use` and it's name do not match.
`karmadactl` can do it but `kubectl-karmada` cannot.
after fixing it.
```release-note
NONE
```

rename the use of kubectl-karmada

---

test/e2e/framework/deployment.go
test/e2e/framework/propagationpolicy.go
test/e2e/lazy_activation_policy_test.go

add e2e test for lazy propagation policy
Involving:
* Simple Case 2 ([Policy created after resource](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#simple-case-2-policy-created-after-resource))
* Combined Case 5 ([Propagate dependencies](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#combined-case-5-propagate-dependencies))
* Combined Case 6 ([Propagate dependencies](https://github.com/chaosi-zju/karmada/blob/lazy-proposal/docs/proposals/scheduling/activation-preference/lazy-activation-preference.md#combined-case-6-propagate-depen …

add e2e test for lazy propagation policy

---

.github/workflows/ci-image-scanning.yaml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/fossa.yml
.github/workflows/lint-chart.yaml

/kind cleanup
PartOf https://github.com/karmada-io/karmada/issues/4761
skip the push event for dependabot
Fixes #4761
```release-note
```

ci:  fix dependabot can not access the secrets

---

pkg/controllers/multiclusterservice/mcs_controller.go

/kind bug
The label `resourcebinding.karmada.io/permanent-id` of mcs binding may be lost when updating, the reason is similar to https://github.com/karmada-io/karmada/pull/4793.
Fixes #
```release-note
karmada-controller-manager: fix the bug of mcs binding losing resourcebinding.karmada.io/permanent-id label.
```

Fix the bug of mcs binding losing resourcebinding.karmada.io/permanent-id label

---

pkg/util/helper/work.go

Cherry pick of #4793 on release-1.8.
#4793: Use merge strategy to avoid work.karmada.io/permanent-id
```release-note
karmada-controller-manager: Fix the problem that work.karmada.io/permanent-id constantly changes with every update.
```

Automated cherry pick of #4793: Use merge strategy to avoid work.karmada.io/permanent-id

---

pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go

/kind feature
#4789 
Part of #4789 
```release-note
`karmadactl`: Introduced `--image-pull-policy` flag to the `init` command, which will be used to specify the image pull policy of all components.
```

Add image-pull-policy flag for karmada init cmd

---

pkg/apis/work/v1alpha1/well_known_constants.go
pkg/apis/work/v1alpha2/well_known_constants.go
pkg/controllers/binding/binding_controller.go
pkg/controllers/binding/cluster_resource_binding_controller.go
pkg/controllers/binding/common.go
pkg/controllers/binding/common_test.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/util/helper/binding.go
pkg/util/helper/binding_test.go
pkg/util/helper/work.go
pkg/util/helper/workstatus.go

/kind feature
```
resourcebinding.karmada.io/key -> resourcebinding.karmada.io/permanent-id
clusterresourcebinding.karmada.io/key -> clusterresourcebinding.karmada.io/permanent-id
```
part of https://github.com/karmada-io/karmada/issues/4711
```release-note
`karmada-controller-manager`: The labels `resourcebinding.karmada.io/key` and `clusterresourcebinding.karmada.io/key` has been deprecated and not be populated in Work objects(replaced by `resourcebinding.karmada.io/permanent-id` and `clusterresourcebinding.karmada.io/permanent-id` respectively).
```

Deprecate key labels of rb/crb

---

pkg/controllers/multiclusterservice/mcs_controller.go

Cherry pick of #4818 on release-1.9.
#4818: Fix the bug of mcs binding losing
```release-note
`karmada-controller-manager`: Fixed the bug of mcs binding losing resourcebinding.karmada.io/permanent-id label.
```

Automated cherry pick of #4818: Fix the bug of mcs binding losing

---

charts/karmada/Chart.lock
charts/karmada/Chart.yaml

/kind feature
upgrade `bitnami/common` dependency in karmada chart
no related issue, but as part of another pr https://github.com/karmada-io/karmada/pull/4785
in this pr, we combine all image secrets together, this is reduce similar code like :
```
{{/*
Return the proper Docker Image Registry Secret Names
*/}}
{{- define "karmada.agent.imagePullSecrets" -}}
{{ include "common.images.pullSecrets" (dict "images" (list .Values.agent.image) "global" .Values.global) }}
{{- end -}}
```
but this is introduce another problem, `bitnami/common@1.x.x` will not handle duplicate secret names in chart,  after upgrade it to `bitnami/common@2.x.x`, it will use `uniq` to remove duplicate secret names in …

feat: upgrade karmada chart dependency

---

pkg/util/cluster.go

/kind cleanup
Function `CreateOrUpdateClusterObject` is used to create cluster object in karmada control plane, or update it if it has been existed. 
https://github.com/karmada-io/karmada/blob/da7689f715aa7c8424a6e14d99be8536f5f1f77a/pkg/util/cluster.go#L145-L151
`reflect.DeepEqual(cluster.Spec, clusterObj.Spec)` It doesn't make sense to compare the `cluster` to the `clusterobj`, it should be the `cluster` to the `mutate(cluster)` in order to correctly determine if an update is needed.
Fixes #
```release-note
```

make DeepEqual judgments more efficient

---

pkg/detector/detector.go
pkg/util/constants.go

/kind feature
See https://github.com/karmada-io/karmada/pull/4743#discussion_r1560637648
```release-note
NONE
```

Add finalizer for propagation policy

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations.yaml

/kind feature
Fixes #
```release-note
```

feat: show `status.labelSelector` for CloneSet

---

pkg/util/helper/taint_test.go

This `fmt.Print` causes an unexpected line in stdout for test run output JSON, which causes an error for future possible go test tools. And we don't use it anyway, so I think it's better to remove it.
```console
{"Time":"2024-04-19T23:11:03.422137+07:00","Action":"output","Package":"command-line-arguments","Test":"TestGetMinTolerationTime/no_noExecuteTaints","Output":"-1ns"}
```
Fixes #
```release-note
NONE
```

Remove print in test

---

.github/workflows/ci.yml
Makefile

/kind feature
I want to introduce gotestsum as the test output format instead of the current gotest tool.
Follow closed PR #4850
Fixes #
```release-note
NONE
```

Adopt gotestsum

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/defaults.go
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/apiserver/mainfests.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/etcd/etcd.go
operator/pkg/controlplane/etcd/mainfests.go
operator/pkg/controlplane/manifests.go
operator/pkg/controlplane/metricsadapter/mainfests.go
operator/pkg/controlplane/metricsadapter/metricsadapter.go
operator/pkg/controlplane/search/mainfests.go
operator/pkg/controlplane/search/search.go
operator/pkg/controlplane/webhook/mainfests.go
operator/pkg/controlplane/webhook/webhook.go

/kind feature
https://github.com/karmada-io/karmada/issues/4789
Part of https://github.com/karmada-io/karmada/issues/4789
```release-note
Allow the user to specify `imagePullPolicy` in Karmada CR when installing via karmada-operator.
```

Add image-pull-policy field for karmada-operator

---

charts/karmada-operator/templates/_helpers.tpl
charts/karmada-operator/templates/post-hook-configmap.yaml
charts/karmada-operator/templates/post-hook-job.yaml
charts/karmada-operator/templates/post-hook-rbac.yaml
charts/karmada-operator/templates/post-hook-serviceacconut.yaml
charts/karmada-operator/values.yaml

/kind feature
the crd will not be updated when upgrading karmada operator chart.
so, we can support a way, run a job to apply crd resource after installing operator deployment.
Fixes #
and i have test for this:
```bash
$ helm install karmada-operator -n karmada-system --create-namespace ./charts/karmada-operator --dependency-update
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/chenwen/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /Users/chenwen/.kube/config
NAME: karmada-operator
LAST DEPLOYED: Mon Mar 11 15:44:35 2024
NAMESPACE: karmada-system
STATUS: …
```

operator: update operator crd when upgrading chart

---

pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/controllers/namespace/namespace_sync_controller.go
pkg/controllers/unifiedauth/unified_auth_controller.go

/kind bug
When we create a namespace with a length of 63, the namespace will not be synchronized to the member cluster. The error reported in `karmada-controller-manager` is as follows:
```log
objectwatcher.go:102] Failed to create resource(kind=Namespace, /test12345678901234567890123456789012345678901234567890123456789) in cluster member1, err is Namespace "test12345678901234567890123456789012345678901234567890123456789" is invalid: metadata.labels: Invalid value: "test12345678901234567890123456789012345678901234567890123456789-56889cc77": must be no more than 63 characters
E0424 07:43:38.082314       1 execution_controller.go:261] Failed to create resource(/test12345678901234567890123456789012345678901234567890123456789 …
```

replace work namespace/name labels with annotations

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml
charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml
charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml
charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
hack/update-crdgen.sh
operator/config/crds/operator.karmada.io_karmadas.yaml

/kind cleanup
This PR bumps controller-tools and refreshes the generated CRDs.
Fixes #4873
Notable changes of controller-tools:
- Remove usages of deprecated io/ioutil
- Add support for empty maps or lists
- CRD: Respect multiline comments at godocs
`NONE`

Update controller-gen version from v0.13.0 to v0.14.0

---

pkg/detector/detector.go
test/e2e/clusterpropagationpolicy_test.go
test/e2e/coverage_docs/clusterpropagationpolicy_test.md
test/e2e/coverage_docs/propagationpolicy_test.md
test/e2e/propagationpolicy_test.go

/kind cleanup
Remove annotaions when pp/cpp is deleted
Fixes #
```release-note
NONE
```

e2e: Remove annotaions when pp/cpp is deleted

---

pkg/controllers/execution/execution_controller.go
pkg/util/objectwatcher/objectwatcher.go

/kind cleanup
Split from https://github.com/karmada-io/karmada/pull/4813.
See https://github.com/karmada-io/karmada/pull/4813#discussion_r1560759930
```release-note
NONE
```

ObjectWatcher.Delete checks if resource can be deleted

---

artifacts/deploy/webhook-configuration.yaml
charts/karmada/templates/_karmada_webhook_configuration.tpl
cmd/webhook/app/webhook.go
operator/pkg/karmadaresource/webhookconfiguration/manifests.go
pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
pkg/util/label.go
pkg/webhook/clusterpropagationpolicy/mutating.go
pkg/webhook/clusterresourcebinding/mutating.go
pkg/webhook/propagationpolicy/mutating.go
pkg/webhook/resourcebinding/mutating.go
pkg/webhook/work/mutating.go

/kind feature
Please referring to: https://github.com/karmada-io/karmada/issues/4000 and https://github.com/karmada-io/karmada/pull/4199#discussion_r1393842038
Part of https://github.com/karmada-io/karmada/issues/4000
The corresponding yaml configuration will be done in another PR.
```release-note
```

feat: add permanent id label to pp/cpp/rb/crb/work resources

---

cmd/controller-manager/controller-manager.go
cmd/metrics-adapter/main.go
cmd/webhook/main.go
examples/customresourceinterpreter/webhook/main.go

/kind cleanup
Refer to #4868, when `karmada-webhook` is started, the error `log.SetLogger(...) was never called; logs will not be displayed` will be displayed, which is very confusing. 
Here's the answer to why this log appears and how to fix it.
Viewing the function call chain, refer to: https://github.com/karmada-io/karmada/blob/95bf37f4d4b82cd9ab68e5879020c070acec1ce0/vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/webhook.go#L178-L184
If the log of webhook is nil, it will end up calling 
https://github.com/karmada-io/karmada/blob/95bf37f4d4b82cd9ab68e5879020c070acec1ce0/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go#L54-L72
And the `SetLogger` is not called within the first 30 seconds of a binaries …

silence the 'log.SetLogger(...) was never called; logs will not be displayed' error

---

charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
pkg/apis/config/v1alpha1/resourceinterpretercustomization_types.go

/kind feature
The resource name `resourceinterpretercustomizations` is too long. When the automatic completion plug-in cannot be used in the environment, it is a headache to enter such a long name during operation and maintenance.
Fixes #
```release-note
Add a short name for resourceinterpretercustomizations CRD resource.
```

add short name for resourceinterpretercustomizations

---

pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go

/kind bug
fix patching WorkloadRebalancer failed due to misuse of shared slices.
in previous code:
```go
// get previous status and update basing on it
newStatus = rebalancer.Status
if len(newStatus.ObservedWorkloads) == 0 {
newStatus = c.buildWorkloadRebalancerStatus(rebalancer)
}
```
actually `newStatus` and `rebalancer.Status` shared the slice of `rebalancer.Status.ObservedWorkloads`.
if this slice didn't change from nil to non-nil or occurs expansion, modification to `newStatus` will also be applied to the `rebalancer.Status`, which will lead to `patch status` failed. 
Fixes part of #4840 …

fix patching WorkloadRebalancer failed due to misuse of shared slices

---

.github/workflows/ci.yml

/kind cleanup
Refer to https://github.com/karmada-io/karmada/issues/4901, we need to remove the redundant path settings in `ci.yaml` to fix the action error with no go.sum file.
Fixes #4901
none
```release-note
NONE
```

fix the action error with no go.sum file

---

.github/workflows/ci-schedule-compatibility.yaml

/kind cleanup
there are two changes:
1. fix the artifact name, It has been incorrect in the past.
2. let setup-go to using go.mod for setup go version.
Fixes #
```release-note
```

chore: fix ghaction APIServer compatibility

---

pkg/util/proxy/proxy.go

/kind cleanup
remove extra import and reuse proxyutil
N/A
```release-note
```

chore: reuse proxyutil import for proxy

---

cmd/karmadactl/karmadactl.go
vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/oidc.go
vendor/modules.txt

/kind feature
In our clusters, OIDC authentication is required for cluster operation auditing and access control. This is also a common authentication method. I believe it can be integrated into Karmada.
NONE
```release-note
NONE
```

feat: add client-go oidc auth provider

---

pkg/controllers/workloadrebalancer/workloadrebalancer_controller_test.go

**DO NOT MERGE** until the following PR have been merged: 
* #4875
add ut for WorkloadRebalancer controller
Fixes part of #4840
```release-note
```

add ut for WorkloadRebalancer controller

---

test/e2e/federatedhpa_test.go
test/e2e/suite_test.go

add e2e for FederatedHPA and metrics-adapter.
Fixes #
```release-note
```

add e2e for FederatedHPA and metrics-adapter

---

hack/local-up-karmada.sh

/kind cleanup
Clean up dangling images after each run of `hack/local-up-karmada.sh`.
Fixes #4914
```release-note
NONE
```

Clean up dangling images

---

pkg/util/helper/work.go
pkg/webhook/work/mutating.go

/kind cleanup
Since the PR(https://github.com/karmada-io/karmada/pull/4474) has been merged, we're going to remove those codes which generate work permanent ID outside of webhook.
Fixes #
```release-note
NONE
```

cleanup dead code of generating Work permanent id

---

hack/update-estimator-protobuf.sh

/kind cleanup
fix broken link
Fixes #
With the release of k8s release v1.24 and newer, the protoc versions it restricts are also being updated. And k8s begin to tighten checking of protoc version in https://github.com/kubernetes/kubernetes/pull/115243. Do we need to synchronize operations on the version of protoc in karmada repo？  cc @RainbowMango @Garrybest 
```release-note
```

chore: fix broken link

---

pkg/controllers/mcs/service_export_controller.go
pkg/util/credential_test.go

/kind cleanup
The `wait.PollUtil` methods was deprecated in Kubernetes v1.27 (https://github.com/kubernetes/kubernetes/pull/107826), so we need migrate `wait.PollUtil` to `wait.PollUtilContextCancel`
Parts of #3835
```release-note
```

migrate wait.PollUntil to wait.PollUntilContextCancel

---

operator/pkg/util/template.go
pkg/karmadactl/addons/utils/template.go

/kind cleanup
Go provides two template packages, one for `text/template` and the other for `html/template`. `html/template` is basically the same as `text/template`, but `text/template` has no protection for XSS or any type of HTML encoding, while `html/template` adds security protection such as HTML encoding and has stronger functions.
Fixes #
```release-note
```

cleanup: replace text/template with html/template

---

pkg/karmadactl/util/genericresource/visitor.go

/kind cleanup
silence gosec warning G107
Fixes #
Silence gosec warning G107:  Potential HTTP request made with variable url by replacing `http.Get` with `http.NewRequest` and `http.DefaultClient.Do`
```release-note
NONE
```

silence gosec warning G107

---

test/e2e/workloadrebalancer_test.go

/kind flake
fix e2e unstable failure caused by taint cluster.
In this new merged e2e, we add a taint `{Key: "workload-rebalancer-test", Effect: corev1.TaintEffectNoExecute}` to member1 cluster.
Though it has specified key, we mistakenly think that it has no effect on other e2e cases. Actually, as long as the cluster has `NoExecute` taint, no matter what the key it is, could affect other e2e cases.
Fixes #
```release-note
```

fix e2e unstable failure caused by taint cluster

---

pkg/resourceinterpreter/default/native/prune/prune.go
pkg/resourceinterpreter/default/native/prune/prune_test.go

/kind bug
We noticed that karmada and member cluster controller-manager are fighting against each other where we get over 6k updates for a single deployment per hour.
the culprit seems to be the revision annotation.
Fixes #
while generally the karmdaa setup doesn't run the Deployment controller on the karmada-apiserver, it does support promoting resources which can lead to having these annotations cause a diff with the member cluster(s).
```release-note
fix: prune deployment revision annotations
```

fix: prune deployment revision annotation

---

pkg/controllers/multiclusterservice/mcs_controller.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/detector/detector.go

/kind cleanup
Since the PR(https://github.com/karmada-io/karmada/pull/4474) has been merged, we're going to remove those codes which generate binding permanent ID outside of webhook.
Same as https://github.com/karmada-io/karmada/pull/4928
Fixes #
```release-note
NONE
```

cleanup dead code of generating binding permanent id

---

pkg/detector/detector.go

/kind cleanup
#4950 introduced a lint issue which will block PRs:
> Error: pkg/detector/detector.go:26:2: "github.com/google/uuid" imported and not used) (typecheck)
Fixes #
Haven't figured out why CI cannot detect it at #4950.
cc @whitewindmills 
```release-note
NONE
```

fix golint issue introduced by #4950

---

pkg/controllers/cluster/taint_manager.go
pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go

/kind cleanup
1. Add empty judgment for placement in taint-manager, avoid panic when the obtained placement is nil:
https://github.com/karmada-io/karmada/blob/90b461603c8025edc9696e3a0c54181e36b4b607/pkg/controllers/cluster/taint_manager.go#L267
2. Add more logs to facilitate fault locating.
Fixes #
In order to make the program more robust, nil judgment is added. 
This is because when users define their own scheduler, the placement recorded in the annotation in the binding may be empty.
```release-note
NONE
```

[Cleanup] Add empty judgment for placement in taint-manager

---

test/e2e/workloadrebalancer_test.go

add more e2e for WorkloadRebalancer
Fixes part of #4840
```release-note
```

add more e2e for WorkloadRebalancer

---

pkg/webhook/clusterpropagationpolicy/mutating.go
pkg/webhook/clusterpropagationpolicy/validating.go
pkg/webhook/propagationpolicy/mutating.go
pkg/webhook/propagationpolicy/validating.go

/kind feature
Add protection mechanism for the permanent ID, see https://github.com/karmada-io/karmada/pull/4949#discussion_r1606293748
Fixes #
```release-note
NONE
```

Add validation on policy permanent ID

---

pkg/karmadactl/join/join.go
pkg/util/cluster.go

This PR removed the deprecated flag `--cluster-zone` from `karmadactl join` command.
Fixes #
```release-note
`karmadactl`: The flag `--cluster-zone`, which was deprecated in release 1.7 and replaced by `--cluster-zones`, now has been removed.
```

Removed deprecated --cluster-zone from karmadactl join command

---

.github/dependabot.yml

/kind cleanup
support auto bump container images with dependabot, but I'm not sure whether we should treat release branch like this, it's means we need to update release branch from this file when a new release is out.
option2 is only auto bump container image for master and cherry pick the PR of dependabot to release branch if need.
Fixes #4908
```release-note
```

chore: support auto bump container images with dependabot.

---

.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/fossa.yml
.github/workflows/lint-chart.yaml

/kind cleanup
cherry pick https://github.com/karmada-io/karmada/pull/4762 to release-1.7, after https://github.com/karmada-io/karmada/pull/4932, dependabot will create PR for release branchs, and we need to skip some push event for dependabot.
releated: 
- https://github.com/karmada-io/karmada/pull/4972
Fixes #
```release-note
```

[1.7] chore: skip push event for branches of dependabot.

---

.github/workflows/ci-image-scanning.yaml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/fossa.yml
.github/workflows/lint-chart.yaml

/kind cleanup
cherry pick https://github.com/karmada-io/karmada/pull/4762 to release-1.8, after https://github.com/karmada-io/karmada/pull/4932, dependabot will create PR for release branchs, and we need to skip some push event for dependabot.
releated: 
- https://github.com/karmada-io/karmada/pull/4975
Fixes #
```release-note
```

[1.8] chore: skip push event for branches of dependabot.

---

docs/proposals/scheduling/workload-rebalancer/workload-rebalancer.md

/kind design
Proposal of introducing a rebalance mechanism to actively trigger rescheduling of resource.
Assuming the user has propagated the workloads to member clusters, in some scenarios the current replicas distribution
is not the most expected, such as:
* replicas migrated due to cluster failover, while now cluster recovered.
* replicas migrated due to application-level failover, while now each cluster has sufficient resources to run the replicas.
* as for `Aggregated` schedule strategy, replicas were initially distributed across multiple clusters due to resource
constraints, but now one cluster is enough to accommodate all replicas.
Therefore, the user desires for an approach to trigger …

Proposal of introducing a rebalance mechanism to actively trigger rescheduling of resource

---

.github/workflows/ci-schedule-compatibility.yaml
.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml

/kind cleanup
kubernetes 1.30 is live, This allows us to use 1.30 for testing in CI. If we still want to use 1.27 for CI testing, we can add 1.30 to the scheduler workflow first.
https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci-schedule-compatibility.yaml
and
https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci-schedule.yml
Fixes #
```release-note
```

ci: add kubernetes 1.30

---

pkg/dependenciesdistributor/dependencies_distributor.go
pkg/dependenciesdistributor/dependencies_distributor_test.go
pkg/util/helper/binding.go
pkg/util/helper/binding_test.go

/kind cleanup
In the dependencies distributor module, we have two kinds of binding, one is the binding that is followed, and the other is the binding that follows.
We have a clear explanation of these names:
https://github.com/karmada-io/karmada/blob/0084c8a97eba3b9ff3a0a355cbc95531bcb5c634/pkg/dependenciesdistributor/dependencies_distributor.go#L83-L84
But in the code, some places are not named according to such names, which makes us a little confused when reading the code and we need to repeatedly confirm the intent of the code.
Therefore, this PR unified the confusing naming and modified some comments.
In addition, the code uses two words, `depended` and `dependencies`, which correspond to the binding that is followed …

cleanup: update relate binding name and comments for ease of understanding

---

pkg/dependenciesdistributor/dependencies_distributor.go
pkg/util/constants.go

/kind feature
In dependencies distributor module, we need to deal with independent binding cleanup with the right pattern -- control with finalizer, so I add a new finalizer `karmada.io/binding-dependencies-distributor`.
In addition, in the issue #1741, we can see that the label value of `resourcebinding.karmada.io/depended-by-xxx` will exceed 63 characters, we need to use the binding permanent ID to replace it, this also prompts us to use finalizer to clean up resources.
Fixes #
```release-note
NONE
```

add binding dependencies distributor finalizer to the independent binding

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml
pkg/apis/apps/v1alpha1/workloadrebalancer_types.go
pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
pkg/controllers/workloadrebalancer/workloadrebalancer_controller_test.go
pkg/generated/openapi/zz_generated.openapi.go
test/e2e/framework/workloadrebalancer.go
test/e2e/workloadrebalancer_test.go

/kind feature
Support auto delete WorkloadRebalancer when time up:
referring to [Automatic Cleanup for Finished Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/).
Introduces field `ttlSecondsAfterFinished` which limits the lifetime of a WorkloadRebalancer that has finished execution 
(finished execution means each target workload is finished with result of `Successful` or `Failed`).
* If this field is set, `ttlSecondsAfterFinished` after the WorkloadRebalancer finishes, it is eligible to be automatically deleted.
* If this field is unset, the WorkloadRebalancer won't be automatically deleted.
* If this field is set to zero, the WorkloadRebalancer becomes eligible to be deleted immediately …

support auto delete WorkloadRebalancer when time up

---

pkg/karmadactl/cmdinit/kubernetes/deployments.go

/kind feature
refer to https://github.com/karmada-io/karmada/pull/4976#issuecomment-2132557294 and https://github.com/karmada-io/karmada/pull/4976#issuecomment-2132565157 and https://github.com/karmada-io/karmada/pull/4976#issuecomment-2132577100
Fixes #
```release-note
`karmadactl`:  The policy for when to pull a container image now is `IfNotPresent in `init` command.
````

[1.9] karmadactl init: set default value of imagePullPolicy to IfNotPresent

---

.github/workflows/ci-image-scanning.yaml
.github/workflows/ci.yml
.github/workflows/cli.yaml
.github/workflows/fossa.yml
.github/workflows/lint-chart.yaml

/kind cleanup
cherry pick https://github.com/karmada-io/karmada/pull/4762 to release-1.9, after https://github.com/karmada-io/karmada/pull/4932, dependabot will create PR for release branchs, and we need to skip some push event for dependabot.
releated: 
- https://github.com/karmada-io/karmada/pull/4971
Fixes #
```release-note
```

[1.9] chore: skip push event for branches of dependabot.

---

.github/OWNERS

This PR nominates @liangyuanpeng @zhzhuang-zju as the owners of infrastructure.
@liangyuanpeng and @zhzhuang-zju contributed a lot to improve the infrastructure, such as :
- Introduced dependabot for automated dependency management
- Introduced trivy for security scanning
- Maintains test matrix 
- And so on.
Fixes #
```release-note
NONE
```
/hold
for current owners to vote and approval
/assign @ikaven1024 @lfbear @mrlihanbo

nominate infra owners

---

.golangci.yml
hack/verify-staticcheck.sh

/kind cleanup
This PR enabled the deprecation check which was disabled by #3730 during the dependency update.
Fixes #3835
```release-note
NONE
```

Enable deprecation check and bump golangci-lint to v1.59.0

---

pkg/dependenciesdistributor/dependencies_distributor.go

/kind feature
Fixes #1741
```release-note
karmada-controller-manager: fix depended-by label value exceed 63 characters in dependencies-distributor
```

Fix depended-by label value exceed 63 characters in dependencies-distributor

---

pkg/dependenciesdistributor/dependencies_distributor.go

/kind cleanup
Remove unused id label in the dependencies distributor, ref talk: https://github.com/karmada-io/karmada/pull/4989#discussion_r1618124114
Fixes #
```release-note
Deprecation: The label `resourcebinding.karmada.io/depended-id` on attached ResourceBinding now has been deprecated and removed now as it never been used.
```

remove unused id label in the dependencise distributor

---

pkg/karmadactl/register/register.go

/kind bug
register cluster creates agent deployment missing --cluster-namespace parameter
Fixes #
```release-note
`karmadactl`:  Fix register cluster creates agent missing --cluster-namespace parameter
```

fix register cluster creates agent missing --cluster-namespace parameter

---

pkg/estimator/server/estimate.go
pkg/estimator/server/framework/interface.go
pkg/estimator/server/framework/runtime/framework.go
pkg/estimator/server/framework/runtime/framework_test.go
pkg/scheduler/core/util.go

/kind bug
Bugfix related to maxReplica estimation.
**Testing**
Local:
```
mszacillo@HXQDWP921L estimator % go test ./...
?   	github.com/karmada-io/karmada/pkg/estimator/client	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/pb	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/framework	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/framework/plugins	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/metrics	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/nodes	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/server/replica	[no test files]
?   	github.com/karmada-io/karmada/pkg/estimator/service …
```

Account for unschedulable plugin result during maxreplica estimation

---

test/e2e/framework/resource/karmada/remedy.go
test/e2e/remedy_test.go
test/e2e/suite_test.go

/kind cleanup
Add e2e for the remedy feature.
Part of #4658 
```release-note
NONE
```

Add e2e for remedy

---

pkg/apis/policy/v1alpha1/well_known_constants.go
pkg/controllers/multiclusterservice/mcs_controller.go
pkg/detector/detector.go
pkg/detector/policy.go

/kind cleanup
Part of #4711 
```release-note
The following labels that were deprecated(replaced by `propagationpolicy.karmada.io/permanent-id` and `clusterpropagationpolicy.karmada.io/permanent-id`) at release-10 now have been removed:
- propagationpolicy.karmada.io/namespace
- propagationpolicy.karmada.io/name
- clusterpropagationpolicy.karmada.io/name
```

Remove pp/cpp namespace/name labels

---

README.md

/kind cleanup
This PR added OSSF [scorecard badges](https://github.com/ossf/scorecard?tab=readme-ov-file#scorecard-badges) to README.
The badge is required by some tools like https://clomonitor.io/. 
The current score is 5.9, we are going to improve it specifically. 
Fixes #
See the [preview here](https://github.com/RainbowMango/karmada/blob/594e1867c8b1fe868665a6249037f3e8e5fdfe69/README.md).
```release-note
NONE
```

Add OSSF scorecard badges

---

pkg/controllers/cronfederatedhpa/cronfederatedhpa_job.go
pkg/controllers/execution/execution_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
pkg/controllers/mcs/service_import_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/controllers/multiclusterservice/mcs_controller.go
pkg/controllers/remediation/remedy_controller.go
pkg/controllers/status/cluster_status_controller.go
pkg/controllers/status/work_status_controller.go
pkg/util/helper/status.go
pkg/util/helper/workstatus.go

/kind feature
I encountered a certain probability conflict problem during the update, which was caused by irregular update status logic.
We should follow best practices like [controllerutil.CreateOrUpdate](https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/controller/controllerutil/controllerutil.go#L276), that is, get latest binding as baseline before updating.
But controller-runtime has not supported the status sub-resource to create or udpate, see issue: https://github.com/kubernetes-sigs/controller-runtime/issues/1725
So I decided to contribute a utility function for updating status.
Fixes # …

Integrate UpdateStatus function

---

pkg/estimator/server/estimate.go
pkg/estimator/server/framework/interface.go
pkg/estimator/server/framework/runtime/framework.go
pkg/estimator/server/framework/runtime/framework_test.go
pkg/scheduler/core/util.go

Cherry pick of #5012 on release-1.9.
#5012: Account for unschedulable plugin result during maxreplica
```release-note
`karmada-scheduler-estimator`: Fixed the `Unschedulable` result returned by plugins to be treated as an exception issue.
```

Automated cherry pick of #5012: Account for unschedulable plugin result during maxreplica

---

charts/karmada/templates/_helpers.tpl
charts/karmada/templates/karmada-aggregated-apiserver.yaml
charts/karmada/templates/karmada-apiserver.yaml
charts/karmada/templates/karmada-controller-manager.yaml
charts/karmada/templates/karmada-descheduler.yaml
charts/karmada/templates/karmada-metrics-adapter.yaml
charts/karmada/templates/karmada-scheduler.yaml
charts/karmada/templates/karmada-search.yaml
charts/karmada/templates/karmada-static-resource-job.yaml
charts/karmada/templates/karmada-webhook.yaml
charts/karmada/templates/kube-controller-manager.yaml
charts/karmada/templates/post-delete-job.yaml
charts/karmada/templates/post-install-job.yaml
charts/karmada/templates/pre-install-job.yaml
charts/karmada/values.yaml

/kind feature
/kind flake
helm install karmada components in order, for detailed discussion, see issue #4917
Fixes #4917
```release-note
```

helm install karmada components in order

---

pkg/controllers/remediation/remedy_controller.go
pkg/controllers/status/cluster_status_controller.go
test/e2e/remedy_test.go

/kind cleanup
In order to fix the ci error:
https://github.com/karmada-io/karmada/actions/runs/9410947609/job/25923580671
https://github.com/karmada-io/karmada/actions/runs/9413749877/job/25931419319?pr=4986
Root error:
The cluster-status-controller updates cluster status while remedy-controller is updating cluster status, `remedyActions` field is overwritten by the cluster-status-controller.
Fixes #
```release-note
karmada-controller-manager: fixes an issue where the cluster-status-controller overwrites the remedyActions field.
```

fixes an issue where the cluster-status-controller overwrites the remedyActions field

---

pkg/controllers/remediation/remedy_controller.go
pkg/controllers/status/cluster_status_controller.go

Cherry pick of #5030 on release-1.10.
#5030: fix-remedy-e2e-errors
```release-note
`karmada-controller-manager`: Fixed an issue that the cluster-status-controller overwrites the remedyActions field.
```

Automated cherry pick of #5030: fix-remedy-e2e-errors

---

test/e2e/lazy_activation_policy_test.go

/kind cleanup
For better test coverage.
Part of the #4607
```release-note
NONE
```

Add combined case 3 in the lazy activation policy tests

---

pkg/apis/work/v1alpha2/well_known_constants.go
pkg/controllers/binding/common.go
pkg/resourceinterpreter/default/native/aggregatestatus.go
pkg/resourceinterpreter/default/native/reflectstatus.go
pkg/resourceinterpreter/default/native/status_type.go

Part of #4870, #5021
```release-note
karmada-controller-manager & karmada-agent: Only make `observedGeneration=generation` for federated deployment when all members' statuses are algined with its federated resource template generation.
```

Align federated Deployment's observedGeneration semantics with its native
