karmada-io/karmada

- Makefile
- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/version.go
- pkg/version/base.go
- pkg/version/version.go
> /kind feature
Support `karmadactl` version command that's can print some version information for debug like `kubectl version`.
Fixes #264
> feature: support version command for karmadactl

- artifacts/deploy/cluster.karmada.io_clusters.yaml
- pkg/apis/cluster/v1alpha1/types.go
- pkg/util/validation/validation.go
- pkg/util/validation/validation_test.go
- pkg/webhook/cluster/validating.go
/kind feature
As described in #257, some member clusters are behind a proxy, for those clusters need to specify a proxy URL.
Part of #257
The `ProxyURL` provided by kubernetes v1.19+.
https://github.com/kubernetes/client-go/issues/351
https://github.com/kubernetes/kubernetes/pull/81443
> support configuring an explict proxy URL for member cluster

- pkg/util/detector/detector.go
/kind feature
Since `ClusterPropagationPolicy` is allowed to point to a namespace scoped resource, so in the scenario a `ResourceBinding` rather than `ClusterResourceBinding` should be created.
Fixes #300 
NONE
```release-note
```
> Generate resourcebinding from clusterpropagationpolicy based on the "namespace" exist of the coming resource

- .golangci.yml
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/propagationpolicy/propagationpolicy_controller.go
- pkg/util/overridemanager/overridemanager.go
As described in this issue: https://github.com/karmada-io/karmada/issues/308#issue-883181898
We usually group import paths in the order of std packages --> third-party packages-->karmada packages
If we enable this check on golangci-lint, we don't need to care about this on code review.
when this is check failed, golangci-lint will report :
```
File is not `goimports`-ed with -local github.com/karmada-io/karmada (goimports)
```
Fixes #
```release-note
NONE
```
> Enable goimports local prefix check

- pkg/scheduler/scheduler.go
- pkg/util/overridemanager/overridemanager.go
- pkg/util/overridemanager/shadow.go
/kind feature
When more than one OverridePolicy/ClusterOverridePolicy matched with resource and cluster name, sort ploicies by name and apply to resource object one by one.
```release-note
NONE
```
> sort OverridePolicy/ClusterOverridePolicy by name when more than one policy matched

- pkg/util/detector/detector.go
/kind cleanup
`helper` package has defined a const string to represent resource kind: deployment , so don't need to use string `"Deployment"` literal
Fixes #
```release-note
```
> use const string instead of string literal

- pkg/scheduler/scheduler.go
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
/kind bug
When `json.Marshal` returns an error, `scheduleResourceBinding` and `scheudleClusterResourceBinding` should return an error
Fixes #
```release-note
```
> scheduler: fix the schedule function error return

- pkg/scheduler/scheduler.go
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
/kind bug
I think when `cache.MetaNamespaceKeyFunc` call on one `binding` fails, don't cause all other `binding` to be skipped
Fixes #
```release-note
```
> scheduler: fix the handling of the *PropatationPolicy updates

- pkg/karmadactl/join.go
Signed-off-by: Iceber Gu <wei.cai-nat@daocloud.io>
/kind bug
It doesn't actually create an `sa` in dry-run mode, so we can't get the `sa`
```sh
╰─➤  ./karmadactl join caiwei --dry-run
E0518 13:49:02.092163   40844 join.go:218] Failed to retrieve service account(/) from cluster. err: serviceaccounts "karmada-caiwei" not found
E0518 13:49:02.092318   40844 join.go:229] Failed to get service account secret from  cluster. error: serviceaccounts "karmada-caiwei" not found
E0518 13:49:02.092328   40844 join.go:91] Error: serviceaccounts "karmada-caiwei" not found
```
Fixes #
```release-note
```
> karmadactl: fix join in dry-run mode

- README.md
- artifacts/deploy/karmada-apiserver.yaml
- hack/create-cluster.sh
- hack/delete-cluster.sh
- hack/deploy-karmada.sh
- hack/local-up-karmada.sh
- hack/remote-up-karmada.sh
- hack/util.sh
1. Two kinds of karmada deployment:
+ deploy to local cluster by kind `local-up-karmada.sh`
+ deploy to remote(stand-alone) cluster `remote-up-karmada.sh`
2. Multi-clusters kebuconfig Integrate in one config file, default in:  /root/.kube/karmda.config. use `kubectl config use-context` to switch.
3. Add some tips in installation step
Fixes #310
- Add '--bind-address' and remove 'host' in probe: keep it can pass when deploying to remote(stand-alone) cluster
- The 2nd argument in 'hack/create-cluster.sh' change to optional, default is current KUBECONFIG
- There is no longer to delete the existed kubeconfig file when run 'hack/create-cluster.sh'
- Save …
> Optimize installation

- artifacts/example/policy_with_labelSelector.yaml
- pkg/scheduler/scheduler.go
/kind bug
reschedule resource bindings when reference cluster propagation policy update
Fixes #
```
I0527 11:41:31.429725       1 scheduler.go:250] Requeue ResourceBinding(default/nginx-deployment) as placement changed.
I0527 11:41:31.434221       1 scheduler.go:420] Reschedule binding(default/nginx-deployment) as placement changed
I0527 11:41:31.434310       1 scheduler.go:427] Don't need to schedule binding(default/nginx-deployment)
I0527 11:46:15.891444       1 scheduler.go:417] Start scheduling binding(cr-test-clusterrole)
I0527 11:46:15.891676       1 scheduler.go:427] Don't need to schedule …
```
> reschedule resource bindings when reference cluster propagation policy update

- test/e2e/overridepolicy_test.go
- test/helper/overridepolicy.go
- test/helper/resource.go
add e2e of imageoverride with https://github.com/karmada-io/karmada/pull/370
```
SSS
------------------------------
[OverridePolicy] apply overriders testing Deployment imageOverride with empty predicate test 
deployment imageOverride testing
/root/karmada/test/e2e/overridepolicy_test.go:61
STEP: creating propagationPolicy(karmadatest-nm6/deploy-xr4)
STEP: creating overridePolicy(karmadatest-nm6/deploy-xr4)
STEP: creating deployment(karmadatest-nm6/deploy-xr4)
STEP: check if deployment present on member clusters have correct image value
I0527 12:18:46.108427   22970 overridepolicy_test.go:74] Waiting for deployment(karmadatest-nm6/deploy-xr4) present on cluster(member1)
I0527 12:18:51.112567   22970 …
```
> add e2e of imageoverride

- .golangci.yml
- pkg/controllers/status/cluster_status_controller.go
- pkg/scheduler/framework/runtime/framework.go
- pkg/util/detector/detector.go
- pkg/util/helper/binding.go
/kind cleanup
Error found during golint scan: `G601: Implicit memory aliasing in for loop. (gosec)`. It may lead to unintended behavior. See [Using reference to loop iterator variable](https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable).
> enable gosec and fix warnings

- hack/util.sh
/kind feature
Save the contents of the client certificate and client key to kubeconfig instead of their file path.
Though it works well now, it will occur a mistake when deploying the karmada agent, because it can not find the certificate files path in the agent container.
Fixes #
NONE
> Embed certs to kubeconfig

- hack/update-codegen.sh
- hack/util.sh
/king bug
run `make verify`, error output is 
```
hack/verify-all.sh
Generating with deepcopy-gen
hack/../hack/../hack/update-codegen.sh: line 14: deepcopy-gen: command not found
make: *** [Makefile:82: verify] Error 127
```
cmd `make verfify` will install some tools or packages in `$GOPATH/bin` and then run some installed package related commands, so if we don't add `$GOPATH/bin` to `env PATH` before, `linux os` cannot find binary, and so error is `command not found`
to solve this problem, we can export  `$GOPATH/bin` to `env PATH` in scripts
And the GOPATH is a path list, we just need the first path.
According to go help gopath:
```
The GOPATH environment variable lists places …
```
> after install package, add $GOPATH/bin to env PATH

- pkg/util/imageparser/parser.go
- pkg/util/imageparser/parser_test.go
- pkg/util/informermanager/keys/keys.go
- pkg/util/informermanager/keys/keys_test.go
/kind cleanup
When implementing the `type Stringer interface` with a pointer receiver, then the `String()` method will only be called for a pointer of that type. 
The significant change is reflected in the log:
```
// without the patch
I0602 04:30:41.048943       1 detector.go:149] Reconciling object: { v1 Secret default default-token-kdmsv}
// with the patch, the output will using the customized info instead of the raw structure.
I0602 07:57:38.249626       1 detector.go:149] Reconciling object: v1, kind=Namespace, karmada-es-member2
```
Fixes #
More details please refer to [here](https://stackoverflow.com/questions/52240972/implement-stringer-interfa …
> Change the receiver of Stringer interface implementation

- Makefile
Reverts karmada-io/karmada#334
The `dependency` of a `target` in the makefile is used to make sure the `target` up to date.
Revert #334 will make all binaries and images re-build when a change happens on the `*.go` file. 
Fixes #
It's my bad that didn't catch it in the previous review. Thanks @mrlihanbo point it out.
```release-note
NONE
```
cc @daixiang0 @gy95 
/priority important-soon
> Revert "remove Makefile SOURCES variable (#334)"

- artifacts/agent/karmada-agent.yaml
- hack/deploy-karmada-agent.sh
- hack/deploy-karmada.sh
- hack/karmada-bootstrap.sh
- hack/run-e2e.sh
/kind feature
Refactor `hack/karmada-bootstrap.sh` and `hack/deploy-karmada-agent.sh`
Fixes #372
- `hack/deploy-karmada-agent.sh`:
+ Removed default value for 'karmada API server kubeconfig' and 'member3 kubeconfig', and change to user input
+ Fit for standalone cluster
+ Auto separating kind-created cluster and standalone cluster (by cluster name prefix 'kind-')
- `hack/karmada-bootstrap.sh`:
+ Merge all clusters' kubeconfig to 2 files, karmada-host & karmada-apiserver into 'karmada.config', all member clusters into 'members.config'<sup>[1]</sup>
+ Karmada API server installation has been taken over by script `hack/local-up-karmada.sh`
+ Karmada …
> Refactor karmada bootstrap

- pkg/controllers/execution/execution_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/util/helper/workstatus.go
Create `informer` to sync resource status back to karmada cluster only when resource applied success.
In my case, the target cluster has no `CRD` the resource belong to, so keep getting `informer` err in the log of `karmada`'s controller management.
For common sense, the sync back informer should be created only when resource applied success in the target cluster.
Fixes #
```release-note
```
> No informer for sync status back when k8s resource applied failed to member clusters

- artifacts/deploy/cluster.karmada.io_clusters.yaml
- pkg/apis/cluster/v1alpha1/types.go
/kind bug
When your member cluster has a kind of resource that is empty APIResources in APIResourceList, such as the following, you will not get the current cluster status after joined the member cluster. Finally, Karmada can not send workload to the cluster.
```
v1.APIResourceList{
TypeMeta: v1.TypeMeta{
Kind:       "APIResourceList",
APIVersion: "v1",
},
GroupVersion: "external.metrics.k8s.io/v1beta1",
APIResources: []v1.APIResource{},
}
```
Fixes #450
I chose the plan that set the `Resources` to an optional field. 
https://github.com/karmada-io/karmada/blob/3f99da3024cd63cd5cec3c43cd782b37d30a96fa/pkg/apis/cl …
> Change APIEnablement.Resources to an optional field

- pkg/controllers/execution/execution_controller.go
- pkg/util/objectwatcher/objectwatcher.go
/kind bug
adopt applying manifest to member cluster when resource with the same name and kind already exists
Fixes #
```
status:
conditions:
- lastTransitionTime: "2021-06-26T07:43:36Z"
message: 'Failed to apply all manifests (0/1): deployments.apps "nginx" already exists'
reason: AppliedFailed
status: "False"
type: Applied
```
```
E0626 03:21:01.704622       1 objectwatcher.go:71] Failed to create resource nginx, err is deployments.apps "nginx" already exists 
E0626 03:21:01.704640       1 execution_controller.go:231] Failed to create resource in the given member cluster member1, err is deployments.apps …
```
> adopt applying manifest to member cluster when resource with the same name and kind already exists

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/controllers/cluster/cluster_controller.go
/kind feature
When the lease of a cluster is time out, we set the conditon `unknown`.
Fixes #385
Refer to [NodeLifecycleController](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/controller/nodelifecycle/node_lifecycle_controller.go)
```release-note
NONE
```
> monitor cluster health in cluster_controller

- artifacts/deploy/karmada-apiserver.yaml
/kind bug
StorageObjectInUseProtection admission plugin will add "kubernetes.io/pvc-protection" finalizers to pvc we create in karmada apiserver.  It results in that we can't delete the pv/pvc in karmada apiserver because we disable pvc-protection controller in karmada kube controller manager.
Fixes #
"NONE"
> disable StorageObjectInUseProtection admission plugin

- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/framework/interface.go
- pkg/scheduler/framework/plugins/apiinstalled/api_installed.go
- pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
- pkg/scheduler/framework/plugins/registry.go
- pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
- pkg/scheduler/framework/runtime/framework.go
- pkg/scheduler/scheduler.go
As talked here:https://github.com/karmada-io/karmada/pull/442#issuecomment-862336738
We decide to add a new scheduler plugin to address the issue:
Stop propagation resource to a cluster which do not has required api installed at scheduler phase.
Signed-off-by: pengli <justdoit.pli@gmail.com>
Fixes #
```release-note
```
> Add new scheduler plugin for checking if required api has installed in target cluster

- pkg/util/detector/detector.go
The log is misleading when we successfully cleaned up labels from a resource template as the `on cluster: %s` is always empty, since newWorkload.GetClusterName() always be empty.
Fixes # https://github.com/karmada-io/karmada/issues/414
```release-note
```
> Fix misleading logs

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
- cmd/webhook/app/webhook.go
- pkg/controllers/hpa/hpa_controller.go
- pkg/controllers/mcs/service_export_controller.go
- pkg/controllers/namespace/namespace_sync_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/util/constants.go
- pkg/util/helper/binding.go
- pkg/util/helper/cache.go
- pkg/util/helper/predicate.go
- pkg/util/helper/work.go
- pkg/util/helper/workstatus.go
/kind feature
Add feature: Multi-Cluster Services.
This is first step of mcs implementation: when a serviceExport was created in member cluster, service-export-controller will collect related endpointSlices to karmada-apiserver.
**How to work with it:**
1. Create serviceexport api in karmada-apiserver and member cluster `member1`;
```
serviceexports.multicluster.x-k8s.io
```
2. Create deploy and svc in member cluster `member1`:
```yaml
metadata:
name: serve
namespace: demo
spec:
replicas: 1
selector:
matchLabels:
app: serve
template:
metadata:
labels:
app: serve
spec:
containers:
- name: serve
image: …
```
> Add ServiceExport controller to report EndpointSlice

- README.md
- artifacts/agent/karmada-agent.yaml
- artifacts/deploy/karmada-apiserver.yaml
- hack/deploy-karmada-agent.sh
- hack/deploy-karmada.sh
- hack/remote-up-karmada.sh
- hack/undeploy-karmada.sh
- hack/util.sh
/kind feature
Further optimizing get started experiences
Fixes #434
Some facets:
- document: add `karmada-agent` install script usage in `README.md`
- keep the latest version for `karmada-agent` when installing, remove `imagePullPolicy: IfNotPresent` from `artifacts/agent/karmada-agent.yaml` when deploys to standalone cluster, and add rebuilding image when deploys to the local cluster.
- [UNIGNORABLE] change the service type of karmada-apiserver to `LoadBalancer` when remote install. because 1. it's no longer to find a work node or a master node to install karmada, 2. karmada-agent could access the `LoadBalancer` IP rather than a `Cluster` IP across …
> Karmada-agent install script support the standalone cluster and some misc

- pkg/util/cluster.go
- pkg/util/objectwatcher/objectwatcher.go
- test/e2e/clusterpropagationpolicy_test.go
- test/e2e/propagationpolicy_test.go
/kind bug
Resolve the 'AlreadyExist' conflicts in a 'Create' process.
Fixes #477 
"NONE"
> resolve AlreadyExists conflict when create resource in member cluster

- artifacts/deploy/multicluster.x-k8s.io_serviceexports.yaml
- artifacts/deploy/multicluster.x-k8s.io_serviceimports.yaml
- hack/deploy-karmada.sh
/kind cleanup
Copied the MCS-API crd definition from [mcs-api@v0.1.0](https://github.com/kubernetes-sigs/mcs-api/tree/f240320550758017c2e33e6cbe9648522aa91e72/pkg/apis/v1alpha1) and I want these APIs(CRDs) to be installed by default.
Fixes #
```release-note
NONE
```
/assign @lfbear @mrlihanbo
> Get MCS APIs installation by default

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/mcs/endpointslice_controller.go
- pkg/controllers/mcs/service_export_controller.go
- pkg/util/helper/mcs.go
- pkg/util/names/names.go
/kind feature
After member clusters reporting EndpointSlice which wrap with work, karmada controller manager will collect endpointslices from executionNamespace to serviceexport namespace. Follow #484
> Collect endpointslices from executionNamespace to serviceexport namespace

- test/e2e/suite_test.go
/kind cleanup
Given the E2E testing fails from time to time, but the testing can be barely reproducible from the local side. 
So, the gap might be caused by the virtual environment's performance. 
This PR intends to increase the timeout and getting a report after multiple testing.
Fixes #
Timeout = 120s:
- Succeed:
- Failed:
```release-note
NONE
```
/hold
> Increase E2E poll timeout setting

- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/mcs/service_import_controller.go
/kind feature
Add feature: Multi-Cluster Services. Follow #484 
When user create a serviceImport to import service, karmada will derive a service from the serviceImport object. This derived service can be discoveried across member clusters. 
**How to work with it:**
Create ServiceImport:
```yaml
apiVersion: multicluster.x-k8s.io/v1alpha1
kind: ServiceImport
metadata:
name: serve
namespace: demo
spec:
type: ClusterSetIP
ports:
- port: 80
protocol: TCP
```
Then get service in `demo` namespace:
```
kubectl get service -n demo
NAME            TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
derived-serve   ClusterIP   10.104.29.174   <none>        80/TCP    71m
```
> Derive service from ServiceImport

- pkg/scheduler/core/generic_scheduler.go
- pkg/util/helper/binding.go
/kind feature
Part of #344 
**How to work with it**:
Create deployment like this 
```
metadata:
name: nginx
labels:
app: nginx
spec:
replicas: 3
selector:
matchLabels:
app: nginx
template:
···
```
and policy like this 
```
metadata:
name: example-policy
spec:
name: nginx
placement:
clusterNames:
- member1
- member2
replicaDivisionPreference: Weighted
weightPreference: 
staticWeightList:
clusterNames: [member1]
weight: 1
clusterNames: …
```
> scheduler with weighted ReplicaDivisionPreference

- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/mcs/service_export_controller.go
- pkg/util/constants.go
- pkg/util/helper/predicate.go
/kind feature
For now, all `Work` resources under the execution namespace(prefixed by `execution-es-`) will be propagated to member clusters.
But for some scenarios, we want to collect or report some resources from member clusters, the resources still need to report to the execution namespace.
This PR provides a way to indicate a Work should be prevented from propagating.
Fixes #
```release-note
NONE
```
> Suppress reported work from propagating

- pkg/controllers/mcs/service_import_controller.go
- pkg/util/constants.go
- pkg/util/helper/policy.go
- pkg/webhook/clusterpropagationpolicy/mutating.go
- pkg/webhook/propagationpolicy/mutating.go
/kind feature
Add feature: Multi-Cluster Services. Follow #484, #494, #504
When user create a PropagationPlicy/ClusterPropagationPolicy to propagate serviceImport, karmada will add ResourceSelectors to propagation derived-service and endpointslices related to the serviceImport.
> Mutate policy's ResourceSelectors in webhook

- cmd/agent/app/agent.go
- pkg/util/helper/predicate.go
/kind feature
It's another part of #513 , for `pull-mode` controllers，some work are also need not to prapagate to member clusters.
Fixes #
```release-note
```
> suppress reported work from propagating in agent

- .github/workflows/ci.yml
- hack/run-e2e.sh
/kind cleanup
There were lots of falling tests recently, unfortunately, no logs for investigating.
This PR enables collecting E2E logs by GitHub Action.
Fixes #
Just collected the logs from `karmada-host` cluster.
For the member cluster will be done by following PR.
```release-note
NONE
```
> enable log collection for e2e testing

- artifacts/deploy/karmada-scheduler.yaml
- artifacts/deploy/karmada-webhook.yaml
- artifacts/deploy/kube-controller-manager.yaml
- test/e2e/failover_test.go
- test/e2e/tainttoleration_test.go
/kind cleanup
This PR tries to fix a falling case that happened at [here](https://github.com/karmada-io/karmada/runs/3052344774).
```
I0713 01:24:23.459833   29721 suite_test.go:204] Got 3 member cluster and all in ready state.
There are 3 clusters
propagation with taint and toleration testing Deployment propagation testing 
deployment with cluster tolerations testing
/home/runner/work/karmada/karmada/test/e2e/tainttoleration_test.go:102
STEP: creating policy(karmadatest-zwm/deploy-htz)
STEP: adding taints to clusters
add taints to cluster member1add taints to cluster member2add taints to cluster member3STEP: creating deployment(karmadatest-zwm/deploy-htz)
STEP: check if deployment(karmadatest-zwm/deploy-htz) only …
```
> Fix taints testing failling.

- cmd/agent/app/agent.go
- hack/deploy-karmada-agent.sh
- pkg/util/cluster.go
- pkg/util/namespace.go
/kind bug
Fix 2 bugs.
1. When environment `KUBECONFIG` is nil, use `${HOME}/.kube` instead to record current kubeconfig.
2. Create namespace `karmada-cluster` where cluster lease is created.
Fixes #
```release-note
NONE
```
> fix bugs of agent deployment

- hack/update-codegen.sh
/kind bug
fix `make verify` generated codes output package is `./` but not `$GOPATH/src/`
Fixes #412
```release-note
```
> fix make verify cmd generated codes output package is ./

- pkg/util/annotation.go
- pkg/util/detector/detector.go
- pkg/util/objectwatcher/retain.go
- test/e2e/scheduling_test.go
/kind bug
When overridepolicy's overriders modified, the resource's annotations have not been updated in member clusters.
Fixes #507 
I will merge the annotations from `desire object` and `member cluster object`, this resulting in old annotations which added by overridepolicy can not be removed from newest object. Because we don't know which annotations are added by user before, and which annotations are setted by controllers in a member cluster.
```release-note
```
> Fix Resource's annotation have not been updated after the overridepolicy updated

- artifacts/kindClusterConfig/karmada-host.yaml
- hack/create-cluster.sh
- hack/deploy-karmada-agent.sh
- hack/deploy-karmada.sh
- hack/karmada-bootstrap.sh
- hack/local-up-karmada.sh
- hack/remote-up-karmada.sh
- hack/util.sh
/kind feature
The local installation script `hack/local-up-karmada.sh` supports macOS
Fixes #486
- fix sed command on macOS (macOS>10.9)
- clear 'REMOTE_MODE' and 'KARMADA_API_SERVER_IP' in hack/deploy-karmada.sh, there are no longer related:  'REMOTE_MODE' decides how to install karmada, kind-cluster(local) or standalone cluster(remote). 'KARMADA_API_SERVER_IP' will auto find by installation mode.
- add  GOOS="linux" for the command `make images` for compiling 'linux version' binary for docker image on macOS
- macOS network: add a mac IP for the karmada-host cluster and karmada-apiserver cluster because member clusters need to access the …
> Adapt for macOS in local(kind) environment

- pkg/util/detector/detector.go
- pkg/util/helper/unstructured.go
/kind bug
Currently, we are using [SingleClusterInformerManager][1] to watch PropagationPolicy and ClusterPropagationPolicy changes, but in the reconcile loop, we are using the controller manager's client to retrieve the resources, like:
https://github.com/karmada-io/karmada/blob/aa5abf29e271ef7c0b76dad4f95d02b41d36a64d/pkg/util/detector/detector.go#L706
The `Client` is generated from the controller manager and it will retrieve objects from it's not from the [SingleClusterInformerManager][1]'s cache.  So, sometimes there will be a delay that after [SingleClusterInformerManager][1] received an event but can't get it from the controller manager's cache. A similar issue can be found at …
> fix informer cache delay issue

- artifacts/deploy/controller-manager.yaml
- pkg/controllers/mcs/service_export_controller.go
- pkg/util/constants.go
- test/e2e/mcs_test.go
- test/e2e/suite_test.go
/kind cleanup
Add e2e test for feature Multi-Cluster Service.
```
[MCS] Multi-Cluster Service testing Connectivity testing 
Export Service from source-clusters, import Service to destination-clusters
/root/cz/karmada/test/e2e/mcs_test.go:272
STEP: Propagation ServiceExport to member clusters
STEP: Check if ServiceExport present on member clusters
STEP: Propagation ServiceImport to member clusters
STEP: Check if ServiceImport present on member clusters
STEP: Create hello Deployment and hello Service in member1 cluster
STEP: Create ServiceExport(karmadatest-jfk/hello-xdn)
STEP: Create PropagationPolicy(karmadatest-jfk/export-hello-xdn-policy) to propagate ServiceExport
STEP: …
```
> Add e2e test for MCS feature 

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/controllers/namespace/namespace_sync_controller.go
- pkg/util/detector/detector.go
/kind feature
Fixes https://github.com/karmada-io/karmada/issues/342
```release-note
```
> controller-manager: introduce --skipped-propagating-namespaces flag

- pkg/util/worker.go
/kind cleanup
In karmada-controller-manager  log file, there are much error info:
```
worker.go:115] Ignore nil item from queue
```
This is useless and disturbing.
The reason for this is the changes of resources which not managed by Karmada  in member cluster will be wathched.
Fixes #
```release-note
NONE
```
> prevent nil key from queue

- pkg/scheduler/core/generic_scheduler.go
- pkg/util/binding.go
/kind feature
Part of #344
How to work with it:
Create deployment like this
```
metadata:
name: nginx
labels:
app: nginx
spec:
replicas: 3
selector:
matchLabels:
app: nginx
template:
···
```
and policy like this
```
metadata:
name: example-policy
spec:
name: nginx
placement:
clusterNames:
- member1
- member2
replicaDivisionPreference: Aggregated
```
and we will get a binding with the following clusters, result may be …
> Replicas changes with aggregated ReplicaDivisionPreference

- pkg/util/detector/detector.go
- pkg/util/helper/unstructured.go
/kind bug
Part of #545 ,  use resourceBinding lister which generated from the SingleClusterInformerManager to get ResourceBinding, rather than get it from controller-runtime Client, prevent target object not found due to delay.
Fixes #
```release-note
NONE
```
> use RB lister generated from the SingleClusterInformerManager

- artifacts/deploy/policy.karmada.io_clusterpropagationpolicies.yaml
- artifacts/deploy/policy.karmada.io_propagationpolicies.yaml
- pkg/apis/policy/v1alpha1/propagation_types.go
/kind cleanup
Restrict `replicaSchedulingStrategy` values by `kubebuilder validation`.
Fixes #
```release-note
NONE
```
/cc @qianjun1993 @Garrybest
> added validation rules to replicaSchedulingStrategy

- test/e2e/suite_test.go
/kind cleanup
We support auto create namespace with [namespace_sync_controller](https://github.com/karmada-io/karmada/blob/master/pkg/controllers/namespace/namespace_sync_controller.go), so we needn't to create namespace for each member cluster explicitly.
Fixes #
```release-note
NONE
```
> E2E: Stop prepare namespace for member clusters

- pkg/util/worker.go
/kind bug
When user misdeleting someone namespace in member cluster, namespace will be recreated in member cluster, but resources which under namespace will not be recreated. Resources template in karmada controller-plane still exist.
Fixes #
```release-note
NONE
```
> Fix an issue when misdeleting namespace in member cluster

- pkg/util/detector/detector.go
/kind cleanup
For better integrate with `argo-cd`, we should resolve `ObservedGeneration` to let argo-cd know the health status.
Fixes #
Refer to https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#deployment-replicaset-statefulset-daemonset
```release-note
NONE
```
> sync observed generation

- cmd/controller-manager/app/controllermanager.go
/kind cleanup
Logs have been initialized in `controller-manager.go`.
https://github.com/karmada-io/karmada/blob/df355a2267613127ddc0039bf4b7f4b39b642249/cmd/controller-manager/controller-manager.go#L15-L16
Fixes #
```release-note
NONE
```
> clean up logs init in controller-manager

- pkg/util/constants.go
- pkg/util/objectwatcher/retain.go
/kind bug
When user create a pvc in karmada and propagate it to member clusters, there will be an error when update pvc in member cluster:
```
E0727 20:23:58.228500      13 objectwatcher.go:121] Failed to update resource(kind=PersistentVolumeClaim, xxx/xxx), err is PersistentVolumeClaim "xxx" is invalid: spec: Forbidden: spec is immutable after creation except resources.requests for bound claims
core.PersistentVolumeClaimSpec{
AccessModes:      []core.PersistentVolumeAccessMode{"ReadWriteOnce"},
Selector:         nil,
Resources:        core.ResourceRequirements{Requests: core.ResourceList{s"storage": {i: resource.int64Amount{value: 1}, s: "1", Format: "DecimalSI"}}},
- …
```
> Retain pvc volumeName when updating

- pkg/scheduler/cache/snapshot.go
- pkg/scheduler/scheduler.go
- pkg/util/binding.go
/kind bug
Set flag `--failover=true` in karmada-scheduler.
User create propagationPolicy to propagate resource:
```yaml
metadata:
name: example-policy
spec:
...
placement:
clusterNames:
- member1
- member2
```
Rescheduling is triggered when `member2` cluster becomes not ready.
CandidateClusters will be calculate in:
https://github.com/karmada-io/karmada/blob/77c99f18b0a3ed58c4609566e4ef8588296e5fab/pkg/scheduler/scheduler.go#L734
The `candidateClusters` isn't the real candidate clusters which conform with propagationPolicy. This error causes the propagationPolicy to be incorrectly updated to: …
> Fix an error in cluster fault rescheduling

- pkg/karmadactl/config.go
- pkg/karmadactl/join.go
/kind bug
/kind cleanup
When user join cluster to karmada, karmada-controller-plane will create a secret to record cluster certification, and add ownerreference with cluster so that when cluster was deleted, the secret will also be deleted. In our code, we add incorrect cluster apiVersion with correct:
```yaml
ownerReferences:
- apiVersion: policy.karmada.io/v1alpha1
blockOwnerDeletion: true
controller: true
kind: Cluster
name: member1
uid: 81995a12-069d-4d40-b108-5ef892fb67fb
```
Fixes #
```release-note
NONE
```
> Fix an bug when add secret ownerreference with cluster

- pkg/apis/policy/v1alpha1/well_known_labels.go
- pkg/apis/work/v1alpha1/well_known_labels.go
- pkg/controllers/binding/binding_controller.go
- pkg/controllers/binding/cluster_resource_binding_controller.go
- pkg/controllers/hpa/hpa_controller.go
- pkg/controllers/mcs/endpointslice_controller.go
- pkg/controllers/namespace/namespace_sync_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/scheduler/scheduler.go
- pkg/util/constants.go
- pkg/util/detector/detector.go
- pkg/util/helper/binding.go
- pkg/util/helper/workstatus.go
- pkg/util/objectwatcher/objectwatcher.go
- pkg/util/worker.go
/kind cleanup
Move labels to apis, so third-party operators can use these labels without  import the whole karmada project,.
Fixes #
```release-note
```
> Move wellknown labels to apis package

- pkg/util/helper/binding.go
/kind cleanup
remove duplicated constants in binding.go
Fixes #
```release-note
```
> remove duplicated constants in binding.go

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/scheduler.go
- cmd/webhook/app/options/options.go
- cmd/webhook/app/webhook.go
- pkg/util/constants.go
/kind bug
Now the leader election is a mess, some module uses leader election as default options but some other does not. So I try to clean up this leader election code. Meanwhile, `karmada-agent` now does not use leader election so if we deploy 2 replicas, there will arise some competition errrors.
Now leader election will be a default option. The lease will be created into `karmada-system`.
Fixes #
```release-note
NONE
```
> Leader election: clean up and add leader election to agent

- pkg/apis/cluster/v1alpha1/well_known_taints.go
- pkg/karmadactl/cordon.go
- pkg/karmadactl/karmadactl.go
In some cases, users want to be able to manually cordon or uncordon scheduling for a cluster via the command line, web ui, as in the case of kubernetes provides cordon and uncordon with kubectl.
/kind design
/kind feature
**What this PR does**:
1. add the `Spec.Unschedulable` property to cluster api to specification that the cluster is unschedulable, default is false.
2. add clusterunschedulable schedule algorithm plugin to filter clusters with `Spec.Unschedulable==ture`, but if toleration `cluster.karmada.io/unschedulable` taint in `PropagationPolicy`, it will be ignored.
3.  implement reschedulable for unschedulable schedule type.
**Cluster unschedulable design**:
1. the user through `karmadactl cordon foo` cluster
2. the …
> cluster unschedulable support for schedulers

- hack/karmada-bootstrap.sh
- hack/local-up-karmada.sh
- hack/util.sh
/kind feature
Users can bootstrap Karmada control plane and members clusters on macOS, and solved the communication between Karmada cluster and member clusters by using MacOS host IP
This is also a todo after https://github.com/karmada-io/karmada/pull/538
Fixes #
Change details:
- function util::install_kubectl adapts for other OS except for Linux
- add an optional parameter(Host IP) in `hack/karmada-bootstrap.sh` to allow users to expose the API server of clusters
- extract the codes that get macOS'IP interactively out of `hack/local-up-karmada.sh` to add a function `util::get_macos_ipaddress` in `hack/util.sh` 
- add rendering files in …
> Adapt karmada-bootstrap.sh for macOS

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/clusterdiscovery/clusterapi/clusterapi.go
- pkg/clusterdiscovery/clusterapi/handler.go
- pkg/karmadactl/join.go
- pkg/karmadactl/unjoin.go
- pkg/util/detector/detector.go
- pkg/util/names/names.go
/kind feature
Add cluster lifecycle management using the [cluster-api](https://github.com/kubernetes-sigs/cluster-api).
**Which cluster version of cluster-api do we need?**
`v1alpha4`
**How to use it?**
-  Create a Secret object with `cluster-api management cluster`'s kubeconfig info, just like:
```yaml
apiVersion: v1
stringData:
kubeconfig: |-
xxx
kind: Secret
metadata:
name: cluster-api-kubeconfig
namespace: karmada-system
```
- Then modify `karmada-controller-manager` deployment, add new cluster-api kubeconfig path:
```yaml
metadata:
name: karmada-controller-manager
namespace: karmada-system
labels:
app: karmada-controller-manager …
```
> Add cluster lifecycle management using the cluster-api

- pkg/controllers/status/cluster_status_controller.go
/kind cleanup
It is not necessary to call `getClusterHealthStatus` once in addition to `wait.Poll`, `wait.Poll ` will automatically retry
`wait.PollImmediate` is more appropriate than `wait.PollImmediate`
Fixes #
```release-note
```
> Delete the extra getClusterHealthStatus logic and use the wait.Poll framework directly

- pkg/controllers/status/cluster_status_controller.go
/kind cleanup
After PR #597, I can see a misleading log from `karmada-controller-manager`:
```
I0816 03:49:03.714941       1 cluster_status_controller.go:142] Cluster(member2) back to online after retry.
```
This log represents a cluster `back to` online state, and should not be printed in normal situations.
Fixes #
```release-note
NONE
```
/cc @Garrybest
> Cleanup: update misleading log

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/scheduler.go
- cmd/webhook/app/options/options.go
- cmd/webhook/app/webhook.go
/kind feature
Add client qps and burst option of karmada-apiserver and kube-apiserver. When cluster is large, the default qps and burst option will slow us down.
Fixes #
```release-note
Add client qps and burst option of karmada-apiserver and kube-apiserver.
```
> add client QPS and burst options to components

- artifacts/deploy/policy.karmada.io_clusteroverridepolicies.yaml
- artifacts/deploy/policy.karmada.io_overridepolicies.yaml
- artifacts/example/overridepolicy_command.yaml
- pkg/apis/policy/v1alpha1/override_types.go
- pkg/util/overridemanager/commandargsoverride.go
- pkg/util/overridemanager/commandargsoverride_test.go
- pkg/util/overridemanager/overridemanager.go
/kind feature
Introduce the `CommandOverrider` and `ArgsOverrider` to support the differentiation of container's command and args, like ImageOverrider not implementation by Plaintext.
Fixes #540 
```release-note
Introduce the `commandOverrider` and `ArgsOverrider` to clusterOverridePolicier and overridePolicier.
```
> Command and Args Overrider

- pkg/util/helper/unstructured.go
- pkg/util/objectwatcher/retain.go
/kind cleanup
Retain necessary fields in Pod object when update pod in `karmada controller-plane`, as noted in https://github.com/karmada-io/karmada/pull/641#issuecomment-903524449 .
Related to #641 
Before retaining fileds is performed, i convert unstructed object to `Pod`, and finally convert `Pod` to unstructed object.
```release-note
NONE
```
> retain necessary fields in Pod object

- pkg/controllers/status/cluster_status_controller.go
- pkg/util/informermanager/single-cluster-manager.go
/kind feature
Delete cluster lease controller after cluster is deleted according to #590.
Fixes #
```release-note
NONE
```
> stop the lease controller when cluster does not exist

- artifacts/deploy/karmada-apiserver.yaml
/kind bug
when creating a pod resource in karmada, and distribute it to member cluster, but the token is different of member cluster.
Fixes #627 
```release-note
NONE
```
> Disable ServiceAccount admission plug-in in karmada apiserver

- pkg/util/detector/detector.go
- test/e2e/mcs_test.go
/kind feature
stop delete resourcebinding when the related policy is deleted 
Fixes #505
```release-note
```
> keep ResourceBinding when removing PropagationPolicy

- pkg/controllers/cluster/cluster_controller.go
/kind flake
I issue this PR in order to remove health data explicitly when a cluster is being deleted, though the health data are deleted in the monitor loop. https://github.com/karmada-io/karmada/blob/c37bedc1cfe5a98b47703464fed837380c90902f/pkg/controllers/cluster/cluster_controller.go#L263-L269
I'm new to karmada and have not tested with this, but consider the situation here:
Say a cluster CR have been deleted during the duration of `ClusterMonitorPeriod` https://github.com/karmada-io/karmada/blob/c37bedc1cfe5a98b47703464fed837380c90902f/pkg/controllers/cluster/cluster_controller.go#L94-L98 then in the monitor loops later on, client.List() will not be able to get the deleted …
> remove health data explicitly when a cluster is being deleted

- pkg/util/overridemanager/imageoverride.go
- pkg/util/overridemanager/overridemanager.go
/kind cleanup
Currently, the method of obtaining JSON patches in ImageOverrider is difficult to read and error-prone. For a resource with replicas of a deterministic type, we can convert from Unstructured object to certain type, then easily extract json patches from `PodSpec`.
Fixes #
```release-note
NONE
```
> refactor imageoverride: use converted resouce to extract json patches

- pkg/controllers/binding/common.go
…0, calculateReplicas func divide by 0
/kind bug
when staticWeightList weight sum is 0, calculateReplicas will panic. 
```
staticWeightList:
clusterNames:
- qcbj1
weight: 0
```
```
E0818 06:55:02.820591       1 runtime.go:78] Observed a panic: "integer divide by zero" (runtime error: integer divide by zero)
goroutine 962 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19e0d20, 0x2a43220)
/Users/xiaorui.zoux/work/karmada/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/xiaorui.zoux/work/karmada/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x19e0d20, 0x2a43220) …
```
> fix panic: when the summary weight is zero

- pkg/util/detector/detector.go
/kind bug
remove propagation policy namespace label from resource binding when reference propagation policy is deleted.
Fixes #
"NONE"
> cleanup label from resource template after PP is removed

- cmd/controller-manager/app/controllermanager.go
the resetConfig variable should obviously be restConfig
this PR fixes the typo
Just a simple typo
NONE
```release-note
```
> resetConfig should be restConfig

- cmd/agent/app/options/options.go
- cmd/controller-manager/app/options/options.go
- cmd/scheduler/app/options/options.go
/kind feature
User may want to deploy karmada to different namespace, so it makes sense to change `Options.LeaderElection.ResourceNamespace` to be configurable.
Fixes #
```release-note
karmada-controller-manager/karmada-scheduler/karmada-agent: introduced --leader-elect-resource-namespace flag to specify the namespace of resource object that is used for locking during leader election.
```
> introduce --leader-elect-resource-namespace flag

- .gitignore
- Makefile
- cmd/kubectl-karmada/kubectl-karmada.go
- pkg/karmadactl/cordon.go
- pkg/karmadactl/join.go
- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/unjoin.go
- pkg/karmadactl/version.go
/kind feature
Support kubectl karmada plugin.
Fixes #
```
kubectl karmada controls a Kubernetes Cluster Federation.
Usage:
karmada [flags]
karmada [command]
Available Commands:
cordon      Mark cluster as unschedulable
help        Help about any command
join        Register a cluster to control plane
uncordon    Mark cluster as schedulable
unjoin      Remove the registration of a cluster from control plane
version     Print the version info
Flags:
--add-dir-header                   If true, adds the file directory to the header of the log messages
--alsologtostderr                  log to standard error …
```
> introduce kubectl plugin

- pkg/controllers/binding/common.go
/kind bug
the scenario in #706 happened because the work object won't be deleted immediately when deleting due to the existing finalizer.  
Fixes #706 
"NONE"
> cleanup status after work object gone

- charts/Chart.yaml
- charts/README.md
- charts/_crds/cluster.karmada.io_clusters.yaml
- charts/_crds/multicluster.x-k8s.io_serviceexports.yaml
- charts/_crds/multicluster.x-k8s.io_serviceimports.yaml
- charts/_crds/policy.karmada.io_clusteroverridepolicies.yaml
- charts/_crds/policy.karmada.io_clusterpropagationpolicies.yaml
- charts/_crds/policy.karmada.io_overridepolicies.yaml
- charts/_crds/policy.karmada.io_propagationpolicies.yaml
- charts/_crds/policy.karmada.io_replicaschedulingpolicies.yaml
- charts/_crds/work.karmada.io_clusterresourcebindings.yaml
- charts/_crds/work.karmada.io_resourcebindings.yaml
- charts/_crds/work.karmada.io_works.yaml
- charts/templates/_helpers.tpl
- charts/templates/_karmada_system_namespace.tpl
- charts/templates/_karmada_webhook_configuration.tpl
- charts/templates/etcd.yaml
- charts/templates/karmada_agent.yaml
- charts/templates/karmada_apiserver.yaml
- charts/templates/karmada_cert.yaml
- charts/templates/karmada_controller_manager.yaml
- charts/templates/karmada_kubeconfig.yaml
- charts/templates/karmada_scheduler.yaml
- charts/templates/karmada_webhook.yaml
- charts/templates/kube_controller_manager.yaml
- charts/templates/post-install-job.yaml
- charts/templates/pre-install-job.yaml
- charts/values.yaml
/kind feature
Support deploy by helm.  #652
Fixes #
```release-note
NONE
```
> feature: support helm chart

- pkg/util/detector/detector.go
- test/e2e/scheduling_test.go
/kind bug
After **move ReplicaResourceRequirements and Replicas into ResourceBindingSpec**(refer to #637), when update binding object, it will not update the fields: `.spec.replicas` and `.spec.replicaRequirements`, as a result, the deployment does not reschedule when the number of replicas changes. 
During the E2E test #696, the deployment replicas are directly updated without checking：
https://github.com/karmada-io/karmada/blob/f717c3ab0cf38436d7972b890e8cf20e2977741f/test/e2e/scheduling_test.go#L453-L459
This time is too short, equivalent to no update.
The above two points cause occasional E2E failures like this: …
> Update binding object with replicas and replicaRequirements

- cmd/controller-manager/app/controllermanager.go
- pkg/version/sharedcommand/sharedcommand.go
- pkg/version/version.go
/kind feature
```bash
$ ./karmada-controller-manager version
karmada-controller-manager version: version.Info{GitVersion:"v0.8.0-105-g0f2345d", GitCommit:"0f2345d7f17d8aec16d53feaa53636b76684f3c4", GitTreeState:"clean", BuildDate:"2021-09-11T07:18:24Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
Part of #716
```release-note
`karmada-controller-manager` introduced a `version` command to represent version information.
```
> Introduced version command to karmada-controller-manager

- cmd/agent/app/agent.go
- cmd/scheduler-estimator/app/scheduler-estimator.go
- cmd/scheduler/app/scheduler.go
- cmd/webhook/app/webhook.go
/kind feature
```
$ ./karmada-scheduler version
karmada-scheduler version: version.Info{GitVersion:"v0.8.0-106-gb2b36a2-dirty", GitCommit:"b2b36a2aaf9038684e96a6c56c1589dbb43bef37", GitTreeState:"dirty", BuildDate:"2021-09-13T03:13:33Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ ./karmada-webhook version
karmada-webhook version: version.Info{GitVersion:"v0.8.0-106-gb2b36a2-dirty", GitCommit:"b2b36a2aaf9038684e96a6c56c1589dbb43bef37", GitTreeState:"dirty", BuildDate:"2021-09-13T03:13:33Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
```
$ ./karmada-agent version
karmada-agent version: version.Info{GitVersion:"v0.8.0-106-gb2b36a2-dirty", …
```
> add version command to components

- README.md
- docs/installation/fromsource.md
/kind cleanup
As discussed at the last community meeting, we are gonna clean up `README`.
This PR moves `I have present cluster for installing` part to a separated file.
Fixes #
```release-note
NONE
```
> docs: move installation docs out of readme

- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/scheduler.go
- pkg/estimator/client/accurate.go
- pkg/estimator/client/cache.go
- pkg/estimator/client/general.go
- pkg/estimator/client/interface.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/scheduler.go
- pkg/util/dial.go
- pkg/util/error.go
- pkg/util/names/names.go
/kind feature
Modify scheduler to support calling scheduler-estimator for estimating max available replicas. 
Fixes Step 6 of #617.
Now the scheduler does not call scheduler-estimator defaultly. We could open this switch in the future.
```release-note
NONE
```
> karmada-scheduler: integrate karmada-scheduler-estimator

- pkg/scheduler/cache/cache.go
- pkg/scheduler/scheduler.go
/kind feature
There is no need to use an extra map for caching because the cluster lister (indexer of `memclusterInformer`) has already preserved all member clusters.
Use cluster lister instead of map to implement scheduler cache.
Fixes #727
```release-note
NONE
```
> Use cluster lister instead of map to implement scheduler cache

- pkg/controllers/status/cluster_status_controller.go
/kind feature
/kind bug
Now the `pods` resource has been aggregated in `cluster.status.resourceSummary.allocatable` since the kubernetes node has a `pods` resource in `node.Status.Allocatable`. However, a pod resource request will not explicitly specify the `pods` resource. So it must be aggregated independently.
Fixes #
```release-note
NONE
```
> add resource pod in cluster.status.resourceSummary

- artifacts/kindClusterConfig/general-config.yaml
- hack/create-cluster.sh
/kind feature
Adapt to the deployment of [Submariner](https://github.com/submariner-io/submariner).
Fixes #
Use the `hack/create-cluster.sh` script to create a kind cluster in the following three modifications:
- `POD CIDR` and `SERVICE CIDR` needs to be specified.
- The created kind cluster uses the `weave` CNI instead of the default `kindnet` CNI.
- The created kind cluster has a worker node.
```release-note
`POD CIDR` and `SERVICE CIDR` needs to be specified.
```
> adapt to the deployment of Submariner

- pkg/estimator/client/accurate.go
- pkg/estimator/client/interface.go
- pkg/scheduler/core/generic_scheduler.go
/kind bug
According to https://github.com/karmada-io/karmada/pull/742#issuecomment-926301019
Fixes #
```release-note
NONE
```
> back off to general estimator when scheduler estimator is unavailable

- pkg/controllers/binding/common.go
/kind bug
Fixes # when matchClusters is empty controller will crash
when matchClusters is empty this line will panic.
```
desireReplicaInfos[sortedClusters[i].ClusterName]++
```
> fix: when matchClusters is empty controller will crash

- pkg/controllers/status/workstatus_controller.go
- pkg/util/worker.go
Signed-off-by: iawia002 <z2d@jifangcheng.com>
/kind cleanup
Complete the TODO, move `GenerateKey` function out of the `worker.go` file.
Fixes #
```release-note
NONE
```
> Move GenerateKey function out of the worker file

- pkg/controllers/mcs/service_export_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/util/helper/cache.go
/kind bug
When I create a deployment and propagate it to the member clusters, and then delete pod `karmada-controller-manager-xxx` in `karmada-host` cluster, the new created `karmada-controller-manager` pod will be panic:
```log
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19e7e98]
goroutine 1367 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetResourceVersion(...)
/root/cz/karmada/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go:282
github.com/karmada-io/karmada/pkg/util/objectwatcher.RetainClusterFields(0xc000528b30, 0x0, …
```
> fix controller-manager crash when consuming informer before initialized

- pkg/apis/cluster/v1alpha1/types.go
- pkg/karmadactl/join.go
- pkg/util/membercluster_client.go
Signed-off-by: iawia002 <z2d@jifangcheng.com>
/kind cleanup
Move the `token` and `caData` definitions to the API definition file.
Fixes #
I see another TODO in this file:
```go
// TODO(RainbowMango): change ca bundle key to 'ca.crt'.
```
Are we sure about this? k/k uses the `caBundle` name in several places, If we are sure about this, I can submit another PR to change it. cc @RainbowMango 
```release-note
NONE
```
/assign @RainbowMango
> Move the token and caData definitions to the API definition file

- artifacts/deploy/karmada-scheduler.yaml
- hack/deploy-agent-and-estimator.sh
- hack/deploy-scheduler-estimator.sh
- hack/local-up-karmada.sh
/kind feature
1. Now karmada-agent will be deployed into member clusters. Actually, it can be deployed in any real clusters as long as we have both karmada-kubeconfig and member-kubeconfig. So I modify the agent deployment script to make it more compatible by using karmada-kubeconfig and member-kubeconfig.
2. It is noticed that karmada-scheduler-estimator of all clusters must be deployed into karmada-host due to scheduler connnection. From the user's point of view, they may deploy agent and estimator together when a new cluster needs to be joined into karmada. So `deploy-agent-and-estimator.sh` script will use `deploy-karmada-agent.sh` and `deploy-scheduler-estimator.sh`to …
> deploy karmada-agent and karmada-scheduler-estimator

- pkg/controllers/binding/binding_controller.go
- pkg/controllers/binding/cluster_resource_binding_controller.go
- pkg/util/constants.go
- pkg/util/detector/detector.go
- pkg/util/helper/binding.go
/kind bug
Add finalizer in ResourceBinding and ClusterResourceBinding to delete works.
If we delete workload while karmada-controller-manager crashes, this will make sure **(Cluster)ResourceBinding remains until controller-manager is ready, then it handles the delete event to delete related works**.
Fixes #708
I followed [this](https://github.com/karmada-io/karmada/issues/708#issue-990675467) and verified it works in my local environment.
```release-note
NONE
```
> Add finalizer in (Cluster)ResourceBinding to delete works

- cmd/scheduler/app/scheduler.go
- go.mod
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/metrics/metrics.go
- pkg/scheduler/metrics/metrics_record.go
- pkg/scheduler/scheduler.go
- vendor/modules.txt
/kind feature
Fixes First Four part of # 695
```release-note
NONE
```
> add metrics for scheduler

- pkg/controllers/hpa/hpa_controller.go
- pkg/util/constants.go
/kind cleanup
As the [kubernetes doc](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents) said, cross-namespace ownerReference is invalid.
> In v1.20+, if the garbage collector detects an invalid cross-namespace ownerReference, or a cluster-scoped dependent with an ownerReference referencing a namespaced kind, a warning Event with a reason of OwnerRefInvalidNamespace and an involvedObject of the invalid dependent is reported. You can check for that kind of Event by running kubectl get events -A --field-selector=reason=OwnerRefInvalidNamespace.
Fixes #
**Does this PR …
> Remove invalid ownerReference in HPA controller

- charts/_crds/bases/cluster.karmada.io_clusters.yaml
- charts/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
- charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
- charts/_crds/bases/policy.karmada.io_overridepolicies.yaml
- charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml
- charts/_crds/bases/policy.karmada.io_replicaschedulingpolicies.yaml
- charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
- charts/_crds/bases/work.karmada.io_resourcebindings.yaml
- charts/_crds/bases/work.karmada.io_works.yaml
- hack/update-crdgen.sh
- pkg/apis/policy/v1alpha1/replicascheduling_types.go
- pkg/controllers/hpa/hpa_controller.go
Signed-off-by: RainbowMango <qdurenhongcai@gmail.com>
/kind cleanup
This PR deprecated RSP. A warning will be raised when people try to create the objects.
Fixes #
```release-note
The API `ReplicaSchedulingPolicy` has been deprecated and will be removed from the following release. The feature now has been integrated into `ReplicaScheduling`.
```
> Deprecate ReplicaSchedulingPolicy API

- pkg/clusterdiscovery/clusterapi/clusterapi.go
- pkg/karmadactl/options/global.go
- pkg/karmadactl/unjoin.go
- test/e2e/namespace_test.go
Signed-off-by: wawa0210 <xiaozhang0210@hotmail.com>
/kind feature
Introduce --wait flag for karmada join and unjoin command
We can control the timeout of join and unjoin by passing the wait parameter, such as 
Two minutes timeout during unjoin
```
karmadactl unjoin CLUSTER_NAME --cluster-kubeconfig=<KUBECONFIG> --wait 2m
```
Fixes #
```release-note
```
> Introduce --wait flag for karmada unjoin command

- cmd/karmadactl/karmadactl.go
- pkg/karmadactl/cordon.go
- pkg/karmadactl/get.go
- pkg/karmadactl/join.go
- pkg/karmadactl/unjoin.go
/kind feature
When I execute command incorrectly,  reporting an error is very unfriendly! 
```
[root@master67 karmada]# karmadactl join
F1029 11:19:57.904391    5914 join.go:73] Error: cluster name is required
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0xc000182001, 0xc0005300a0, 0x4a, 0x9f)
/root/lonelyCZ/karmada-lonelyCZ/karmada/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2ceda00, 0xc000000003, 0x0, 0x0, 0xc0004565b0, 0x0, 0x2439540, 0x7, 0x49, 0x0)
/root/lonelyCZ/karmada-lonelyCZ/karmada/vendor/k8s.io/klog/v2/klog.go:975 +0x1e5
k8s.io/klog/v2.(*loggingT).printf(0x2ceda00, 0xc000000003, 0x0, 0x0, 0x0, 0x0, 0x1dad45f, 0x9, 0xc000070a00, 0x1, ...) …
```
> replace err report with RunE

- pkg/estimator/client/accurate.go
- pkg/estimator/client/general.go
- pkg/estimator/client/interface.go
- pkg/estimator/server/server.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/util/constants.go
/kind feature
Now estimator only logs the max replicas and time elapse when calculating max available replicas. See [here](https://github.com/karmada-io/karmada/blob/f00208d6f85b5d45f58ba07887ade59dc000f3f9/pkg/estimator/server/server.go#L191-L201) .
I add the resource object reference into gRPC context of metadata. It is significant for tracing replica estimation of scheduler.
Fixes #
```release-note
NONE
```
> add object reference information when calling gRPC

- pkg/controllers/status/workstatus_controller.go
/kind cleanup
I found the following message in log:
```
E1101 07:50:08.574255       1 workstatus_controller.go:149] Failed to sync status as invalid key:
```
I run the following code in my IDE:
```
func generateKey(obj interface{}) interface{} {
return ""
}
func main() {
test := generateKey("")
if test == nil {
fmt.Println("is nil")
}else {
fmt.Println("not nil")
}
}
```
The result show that `""` is not equal to `nil`.
if return "", the empty key will add to queue:
```
func (w *asyncWorker) EnqueueRateLimited(obj runtime.Object) {
key, err := w.keyFunc(obj)
if err != nil {
klog.Warningf("Failed to generate key for obj: %s", obj.GetObjectKind().GroupVersionKind())
return
}
if …
```
> prevent empty key from queue

- pkg/controllers/mcs/service_export_controller.go
- pkg/controllers/status/cluster_status_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/util/constants.go
- pkg/util/informermanager/multi-cluster-manager.go
- pkg/util/informermanager/single-cluster-manager.go
/kind bug
There exists a scenario that some of joined cluster are unhealth in karmada. At the moment, if karmada controller manager restart, it will be blocked in `WaitForCacheSync` process until the unhealth cluster recovers. 
Fixes #
"NONE"
> add Timeout in WaitForCacheSync

- artifacts/deploy/karmada-scheduler.yaml
- charts/templates/karmada_scheduler.yaml
- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/scheduler.go
- pkg/features/features.go
- pkg/scheduler/scheduler.go
Signed-off-by: iawia002 <z2d@jifangcheng.com>
/kind feature
Introduce the feature gates package to allow users to control whether to enable/disable some global features, this can also be used in other components in the future.
Fixes #701
I directly removed the `--failover` flag. I don’t know if we need to ensure compatibility in the current version.
```release-note
Introduce feature gates for the scheduler component.
```
> Introduce feature gates for the scheduler component

- cmd/scheduler/app/options/validation.go
- cmd/scheduler/app/options/validation_test.go
- cmd/scheduler/app/scheduler.go
- cmd/scheduler/main.go
/kind feature
part of #919
If the scheduler command parameter is incorrect, it will exit abnormally and output the entire stack information
so add karmada-scheduler flags verification logic
Fixes #
```release-note
```
> add karmada-scheduler flags verification logic

- charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
- charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml
- charts/_crds/bases/policy.karmada.io_replicaschedulingpolicies.yaml
- pkg/apis/policy/v1alpha1/replicascheduling_types.go
- pkg/scheduler/core/division_algorithm.go
- pkg/scheduler/core/division_algorithm_test.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/core/util.go
- pkg/util/binding.go
- pkg/util/helper/binding.go
- test/helper/resource.go
- test/helper/scheduler.go
Co-authored-by: junqian <junqian@tencent.com>
/kind feature
/kind cleanup
This PR is the implementation of #841. Note that the `generic_scheduler.go` is too long to add more codes, so I try to separate the division and util codes into multiple files. 
The algorithm is a little bit complicated. For sake of accuracy, I add 4 tests, including 20 test cases to test core algorithm in `division_algorithm.go`. This PR is a little bit large, hope to receive you guys' review. 
/cc @RainbowMango @kevin-wangzefeng @qianjun1993 @XiShanYongYe-Chang @mrlihanbo @gf457832386 
By the way, this PR is  co-authored by @qianjun1993.
Fixes #
**Special notes for …
> divide replicas weighted by AvailableReplicas

- cmd/agent/app/agent.go
- cmd/agent/app/options/validation.go
- cmd/agent/app/options/validation_test.go
- cmd/agent/main.go
/kind feature
part of #919
If the agent command parameter is incorrect, it will exit abnormally and output the entire stack information
so add karmada-agent flags verification logic
Fixes #
```release-note
```
> add agent flag validate

- pkg/karmadactl/join.go
when we get resource failed, and error is not found, we should continue to try to get resources again. but not return errror. should return nil and continue to exec `conditionFunc`.
Fixes #
```release-note
```
> continue try to get resource when not found

- pkg/controllers/binding/common.go
- pkg/detector/detector.go
- pkg/util/binding.go
- pkg/util/constants.go
/kind feature
Add Job scheduling in scheduler. We divide replicas by `spec.parallelism`. And the `spec.completions` could be divided weighted by scheduling result.
Fixes #893
```release-note
support job scheduling
```
> support job scheduling

- artifacts/deploy/webhook-configuration.yaml
- charts/templates/_karmada_webhook_configuration.tpl
- cmd/webhook/app/webhook.go
- pkg/apis/config/v1alpha1/explorewebhook_types.go
- pkg/webhook/crdexplorer/helper.go
- pkg/webhook/crdexplorer/validating.go
/kind feature
Add the validation for `ResourceExploringWebhookConfiguration` creation/update, the restriction complies with the API definition.
For example, when I create a `ResourceExploringWebhookConfiguration` object with following yaml:
```yaml
// example-rewc.yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceExploringWebhookConfiguration
metadata:
name: example
webhooks:
- name: foo.example.com
rules:
- operations: ["ExploreRetaining", "ExploreHealthy", "ExploreTest"]
apiGroups: ["foo.example.com"]
apiVersions: ["*"]
resources: ["foos"]
scope: "Namespaced"
clientConfig:
url: https://xxx:443/explore-foo
caBundle: xxx
failurePolicy: Fail
exploreReviewVersions: …
```
> Add the validation for ResourceExploringWebhookConfiguration

- pkg/crdexplorer/defaultexplorer/default.go
/kind bug
Fix bug introduced by #951 where always parse objects as a `Deployment`.
Fixes #
```release-note
```
> Fix job can not schedule issue

- pkg/controllers/status/cluster_status_controller.go
- pkg/estimator/server/nodes/filter.go
- pkg/scheduler/framework/plugins/apiinstalled/api_installed.go
- pkg/util/helper/node.go
/kind cleanup
function `getReadyStatusForNode` and function `IsNodeReady` implement the function to predict whether node is ready or not, the two functions are the same, so just keep only one and move it to the common file.
Fixes #
```release-note
```
> unify IsNodeReady function

- cmd/agent/app/options/validation.go
- pkg/util/validation/validation.go
/kind cleanup
add more validations for cluster name, using function `validation.ValidateClusterName` to validate cluster name.
Fixes #
```release-note
```
> add more validations for cluster name

- pkg/util/objectwatcher/objectwatcher.go
/kind bug
Refer to #969 for more details.
Fixes #969 
```release-note
karmada-controller-manager: now delete resources from member cluster uses "Background" as default delete option.
```
> Set background cacscade deletion by default

- pkg/karmadactl/get.go
Signed-off-by: Phil-sun <sunxh0000@163.com>
/kind bug
In release 0.9.0, the version of work karmada used is v1alpha2, but in get.go, it's still v1alpha1. And the conversion from alpha1 to alpha2 had certification error like following
```Error: conversion webhook for work.karmada.io/v1alpha2, Kind=ResourceBinding failed: Post "https://karmada-webhook.karmada-system.svc:443/convert?timeout=30s": x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ca")```
IMHO, changing it into v1alpha2 will be okay.
Fixes #938 …
> update work version in get.go

- hack/local-up-karmada.sh
/kind cleanup
The following command can not run on the latest version of macOS(v12.0.1)
```
sed -i "2a RUN echo -e http://mirrors.ustc.edu.cn/alpine/v3.7/main/ > /etc/apk/repositories\n" ${REPO_ROOT}/cluster/images/karmada-controller-manager/Dockerfile
```
For compatibility, I change another way which transforms an appendage into a replacement to implement it.
Because it is different between Linux and macOS for the appendage syntax and the same for the replacement syntax.
Fixes #
```release-note
```
> Solve compatibility for 'sed' on macOS v12.0.1

- pkg/apis/config/v1alpha1/explorereview_types.go
- pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
- pkg/crdexplorer/crdexplorer.go
- pkg/crdexplorer/defaultexplorer/default.go
/kind feature
Add `ObservedObject` field to ExploreRequest, and it will be set in case of retaining fields from an observed object to the desired object.
Fixes #
```release-note
NONE
```
cc @XiShanYongYe-Chang @gy95
> Add ObservedObject field to ExploreRequest

- cmd/scheduler-estimator/app/scheduler-estimator.go
/kind bug
#962 will lead to an exit of scheduler-estimator without any logs.
Fixes #
```release-note
NONE
```
> fix issue of scheduler-estimator exit

- Makefile
- cmd/agent/app/options/validation_test.go
/kind bug
Fixes #993 
Because `ValidateClusterName` function has been changed in `cmd/agent/app/options/validate.go` leading to unit test failed, so update it.
```release-note
NONE
```
> enable unit test for cmd

- cmd/controller-manager/app/controllermanager.go
- cmd/scheduler-estimator/app/scheduler-estimator.go
- cmd/scheduler/app/scheduler.go
/kind cleanup
There's already a standard function `JoinHostPort` to help us combine host and port into a network address. So we don't need to use string format to do this thing.
Fixes #
```release-note
```
> using net.JoinHostPort to generate a network address

- pkg/util/objectwatcher/objectwatcher.go
/kind bug
Fixed a panic: (shouldn't use the return pointer if there is an error)
```
W1120 12:20:23.134396       1 customized.go:143] Failed calling webhook examples/workloads.example.com: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://karmada-interpreter-webhook-example.karmada-system.svc:443/interpreter-workload?timeout=3s": dial tcp: lookup karmada-interpreter-webhook-example.karmada-system.svc on 10.96.0.10:53: no such host
E1120 12:20:23.134524       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 275 [running]: …
```
> Fix panic: invalid memory address or nil pointer dereference

- Makefile
- cluster/images/karmada-interpreter-webhook-example/Dockerfile
- examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml
- examples/customresourceinterpreter/webhook-configuration.yaml
- examples/customresourceinterpreter/webhook/app/options/options.go
- examples/customresourceinterpreter/webhook/app/webhook.go
- examples/customresourceinterpreter/webhook/app/workloadwebhook.go
- examples/customresourceinterpreter/webhook/main.go
/kind feature
Add webhook demo for crd resource explorer.
Part of #923 
How to use this demo:
1. make image
```
export VERSION=latest
make image-karmada-interpreter-webhook-example
```
2. load image with kind
```
kind load docker-image swr.ap-southeast-1.myhuaweicloud.com/karmada/example-interpreter-webhook:latest --name karmada-host
```
3. create deployment
```
kubectl --context karmada-host create -f examples/customresourceinterpreter/example-interpreter-webhook.yaml
```
4. create resource-explore-webhook-configuration(need to replace CA)
```
kubectl create -f …
```
> Add resource interpreter webhook example

- cmd/kubectl-karmada/kubectl-karmada.go
- pkg/karmadactl/get.go
- pkg/karmadactl/join.go
/kind cleanup
Because `RunE` could report error, so we don't need `klog.Errorf` in karmadactl. Otherwise, there are repetitive error output.
```
[root@master67 karmada]# karmadactl join memeber69 --karmada-context=test
E1109 22:15:01.842240   12623 join.go:147] failed to get control plane rest config. context: test, kube-config: , error: context "test" does not exist
Error: context "test" does not exist
```
Fixes #
BTW, clearn `fmt.Fprintf(os.Stderr, "%v\n", err)` in `kubectl-karmada.go`, and modify `pkg/karmadactl/get.go` because error strings should not be capitalized. …
> Clean klog errorf in karmadactl

- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/scheduler.go
/kind cleanup
the `policyLister` was introduced in #108, after #213 we don't need this lister anymore so I think we should remove it to avoid misunderstanding for people reading the code.
Fixes #
```release-note
NONE
```
/cc @mrlihanbo @RainbowMango
> Remove unused policyLister in the genericScheduler

- pkg/scheduler/core/division_algorithm.go
- pkg/scheduler/core/division_algorithm_test.go
/kind cleanup
There are a lot of code logic to be optimized, the following is an example:
1. This makes the program not run the way as we want 
Change the location of the code block will solve the problem 
2. Furthermore, the running time of the program written in this way will depend on the value of `remainReplicas`. But if `remainReplicas` is much larger than the length of `desireReplicaInfos`, the first method runs  obviously not as fast as the second method.
First method:
Second method:
3. So we can choose the faster method based on the size relationship between the value of `remainReplicas` and the length of `desireReplicaInfos`:
A part of issue #972
**Special notes for your …
> Logic patch for dividing remaining replicas to clusters

- pkg/util/annotation.go
/kind cleanup
For annotations set by controllers in a member cluster we won't overwrite them. But for annotations set by user in resource template, we should support to update them.  Before this commit, annotations can't update if resource has been propagated which is unreasonable.
Fixes #794 #650
"NONE"
> support update object annotations

- pkg/util/names/names.go
Signed-off-by: huangminjie <minjie.huang@daocloud.io>
/kind bug
Fixes #
```release-note
```
> fix: fix GenerateBindingReferenceKey bug

- pkg/clusterdiscovery/clusterapi/clusterapi.go
- pkg/karmadactl/get.go
- pkg/karmadactl/join.go
- pkg/karmadactl/options/global.go
- pkg/karmadactl/unjoin.go
- test/e2e/namespace_test.go
/kind cleanup
`ClusterNamespace` is not a flag that is need by all commands. iInorder to use `GlobalCommandOptions` in next commands, like `cordon`、`taint`, we should remove it from GlobalCommandOptions.
Fixes #
Like I mention it #946 
```release-note
NONE
```
> Remove ClusterNamespace from GlobalCommandOptions

- cmd/agent/main.go
- cmd/controller-manager/controller-manager.go
- cmd/scheduler-estimator/main.go
/kind cleanup
Estimator does not use controller-runtime, so there is no need to initialize `sigs.k8s.io/controller-runtime/pkg/metrics`.
Fixes #
```release-note
NONE
```
> clean up metrics package init

- .golangci.yml
- docs/working-with-submariner.md
- go.mod
- hack/tools/preferredimports/preferredimports.go
- hack/update-import-aliases.sh
- hack/util.sh
- hack/verify-import-aliases.sh
- vendor/modules.txt
/kind cleanup
Starting in Go 1.17, installing executables with go get is deprecated. go install may be used instead.
Fixes #918 
```release-note
NONE
```
> Replace go get with go install

- pkg/controllers/binding/binding_controller.go
- pkg/controllers/binding/cluster_resource_binding_controller.go
- pkg/util/helper/binding.go
- pkg/util/helper/workstatus.go
/kind cleanup
In the v0.9.0 version of karmada, in order to prevent incompatibility when upgrading, I kept the resolve logic of the original label, now we have released v0.10.0 version, this logic can be removed.
Fixes #
```release-note
NONE
```
> delete the TODO logic with binding labels

- pkg/detector/compare.go
- pkg/detector/compare_test.go
- pkg/detector/detector.go
/kind cleanup
- The logic of function **LookForMatchedPolicy** (**LookForMatchedClusterPolicy** is the same) is to filter `PropagationPolicy` and select the smallest lexicographical one among the matched `PropagationPolicies`, but there is no need to sort.
- It optimizes the time complexity from `O(nlogn)` to `O(n)`, accelerating the process of matching. 
- Furthermore, more strategies of selecting `PropagationPolicy` can be added to function **getHigherPriorityPropagationPolicy** in the future.
```release-note
NONE
```
> Optimization the process of getting PropagationPolicy with higher priority

- pkg/karmadactl/join.go
Signed-off-by: Pilipalaca <85749695@qq.com>
/kind feature
In the clusterlist,provider is a display column,so it should be manuall specified when join a member cluster.After manually specifiying the provider,you can get the specified provider throuh apiserver.
Fixes #1023
Join with provider,then get it from apiserver:
```release-note
```
> Specify the provider manually.

- pkg/controllers/status/cluster_status_controller.go
- pkg/util/condition.go
/kind cleanup
To solve the problem I met in #922 
Fixes #922 
step1: create an invalid apiservice in member cluster
```
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
name: v1alpha1.custom-metrics.metrics.k8s.io
spec:
insecureSkipTLSVerify: true
group: custom-metrics.metrics.k8s.io
groupPriorityMinimum: 1000
versionPriority: 5
service:
name: api
namespace: custom-metrics
version: v1alpha1
```
then, you can get the following cluster status:
```
status:
conditions:
- lastTransitionTime: "2021-11-23T07:37:54Z"
message: 'failed to get the list of APIs installed in the member cluster: …
```
> add conditions for cluster status

- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/taint.go
/kind feature
Fixes #882 
`pkg/karmadactl/taint/utils.go` is originated from `k8s.io\kubectl\pkg\cmd\taint\utils.go`, but the `corev1.Node` have been changed to `v1alpha1.Cluster`, I am not sure where to set it. 
The result is shown below
```
[root@master67 ~]# karmadactl taint clusters member68 my.name=taint:NoSchedule
I1030 23:06:06.389611   22092 taint.go:269] cluster/member68 tainted
[root@master67 ~]# kubectl get cluster member68 --template={{.spec.taints}}
[map[effect:NoSchedule key:my.name value:taint]]
[root@master67 ~]# karmadactl taint clusters member68 my.name=taint:NoSchedule-
I1030 …
```
> Implement karmadactl taint to add taints into a cluster

- cmd/webhook/app/options/validation.go
- cmd/webhook/app/options/validation_test.go
- cmd/webhook/app/webhook.go
/kind feature
part of #919
If the scheduler command parameter is incorrect, it will exit abnormally and output the entire stack information so add karmada-wehook flags verification logic
Fixes #
```release-note
```
> add karmada-wehook flags verification logic

- pkg/scheduler/scheduler.go
/kind cleanup
As discussed with @RainbowMango at last meeting, it's not a good idea to branch by schedule types because it's tricky for us to extend scheduler behavior
Get ready for #829
Fixes #
```release-note
NONE
```
> Refactor schedule type

- pkg/karmadactl/taint_test.go
Unit test for karmadactl taint.
Fixes #
I have two opinions below:
1. I only add unit tests of  tool function in this pr. I observe that test whole taint command in kubernetes by importing `testClient`. It is complex and needing to import a lot of dependence, so I haven't introduce it yet. And I consider it is required more disscution. 
2. I consider whether provide single folder for each subcommand, because there are more subcommands and UTs as the project develops.
/cc @RainbowMango @XiShanYongYe-Chang 
```release-note
NONE
```
> Add UT for karmadactl taint

- cmd/controller-manager/app/options/options.go
- pkg/controllers/namespace/namespace_sync_controller.go
- pkg/detector/detector.go
- pkg/util/names/names.go
some namespaces(like karmada-test, karmada-dev, kube-test, etc.) will be propagated
Signed-off-by: huangminjie <minjie.huang@daocloud.io>
/kind feature
change namespace filter rule
some namespaces(like karmada-test, karmada-dev, kube-test, etc.) should be propagated.
reslove this issue [985](https://github.com/karmada-io/karmada/issues/985)
Refer to #985
```release-note
```
> feature: change namespace filter rule

- artifacts/example/policy_with_labelSelector.yaml
/kind bug
example bug fix，Important
Fixes # #1045
/assign @RainbowMango
NONE
```本意是想比如指定了cluster1,cluster2,cluster3三个集群，maxGroups和minGroups为2，然后当其中一个集群不可用时，会调度到剩下的那个集群上。
```
> Example bugFix：artifacts/example/policy_with_labelSelector.yaml 

- .github/ISSUE_TEMPLATE/bug-report.md
Users should provide kubectl-karmada or karmadactl version on bug report. #1059
Fixes #1059
NONE
> update bug report template

- pkg/controllers/binding/binding_controller.go
- pkg/controllers/binding/cluster_resource_binding_controller.go
- pkg/scheduler/scheduler.go
- pkg/util/condition.go
- pkg/util/helper/binding.go
- test/e2e/framework/deployment.go
/kind cleanup
1. update `Scheduled` conditon when failed scheduling
2. remove `FirstSchedule`, reconcile schedule once applied policy is different from the latest propogation policy.
Fixes #
```
conditions:
- lastTransitionTime: "2021-11-19T07:34:38Z"
message: 'failed to assignReplicas: failed to scaleUp: clusters resources are
not enough to schedule, max 6 replicas are support'
reason: BindingFailedScheduling
status: "False"
type: Scheduled
```
"NONE"
> update Scheduled conditon when failed scheduling

- pkg/scheduler/core/division_algorithm.go
- pkg/scheduler/core/division_algorithm_test.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/core/util.go
- pkg/scheduler/scheduler.go
- pkg/util/helper/binding.go
/kind feature
Now scale scheduling has a particular process without share the same logic with normal scaleduling. Here shows some problems:
1. The code is too complicated.
2. If a new cluster has added, the scale scheduling could not make the new one as a candidate because the process does not contain a replica estimation step. The result of candidate clusters are based on the previous scheduling result. See [here](https://github.com/karmada-io/karmada/blob/763a50ef3c3edda7f561a3ab88b3a079a5b35f61/pkg/scheduler/core/division_algorithm.go#L143-L149)
Now the two steps have been merged. Actually, the first scheduling is a special kind of `scaling up`. There is no need to separate the two kinds.
**Which issue(s) this PR …
> karmada-scheduler: merge scalescheduling with normal scheduling

- pkg/apis/cluster/v1alpha1/cluster_utils.go
- pkg/apis/cluster/v1alpha1/cluster_utils_test.go
/kind cleanup
https://github.com/karmada-io/karmada/blob/85920e7ef49afc66325b85a37de97a662a7913c1/pkg/scheduler/core/generic_scheduler.go#L62
Currently we printed the `feasibleClusters` information in the generic_scheduler, but the `feasibleClusters` is an array of pointers, which makes the printed log completely unreadable:
```
I1206 06:22:54.370778       1 generic_scheduler.go:62] feasible clusters found: [0xc000858000 0xc000858200]
```
So I added a `String()` method to the `Cluster` object to make the log readable:
```
I1206 06:51:59.916405       1 generic_scheduler.go:62] feasible clusters found: [member1 member2]
```
Fixes #
**Does this PR …
> Print pointer variables correctly in the scheduler log

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
Add one of the following kinds:
/kind feature
Fixes #
```release-note
```
> add flag `--controllers`: a list of controllers to enable

- pkg/apis/work/v1alpha2/well_known_labels.go
- pkg/util/annotation.go
- pkg/util/objectwatcher/objectwatcher.go
/kind feature
This is part of https://github.com/karmada-io/karmada/discussions/1039, We finally decided to use the annotation solution, we will introduce the following annotation to control the takeover strategy when encountering resources with the same name:
```go
// ResourceConflictResolutionAnnotation is added to the resource template to specify how to resolve the conflict
// in case of resource already existing in member clusters.
// The valid value is:
//   - overwrite: always overwrite the resource if already exist. The resource will be overwritten with the
//     configuration from control plane.
// Note: Propagation of the resource template without this annotation …
```
> Introduce ResourceConflictResolution annotation to control the strategy for managing resources with the same name

- test/e2e/framework/deployment.go
- test/e2e/framework/propagationpolicy.go
- test/e2e/porting_workloads_test.go
/kind feature
Add e2e test for #1087, we create a deployment on the target cluster (member1) first, then create a resource template and a propagation policy, and check the deployment's replicas, at this time, the number of Pods is equal to 2 * the original replicas, then update the deployment, add the ResourceConflictResolution annotation, and then check the deployment's replicas again, now the number of Pods is equal to 3 * the original replicas(the existing deployment of another cluster has been managed).
```
STEP: Creating Namespace(karmadatest-lpw)
STEP: Creating Deployment(karmadatest-lpw/deploy-8s2)
STEP: Creating PropagationPolicy(karmadatest-lpw/deploy-8s2)
STEP: …
```
> Add e2e test for managing existing resources scenario

- hack/.import-aliases
/kind cleanup
We don't rely on this package `k8s.io/kubernetes` in our code, so remove it from .import-aliases.
Fixes #
```release-note
NONE
```
> Cleanup k8s.io/kubernetes from .import-aliases

- charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
- charts/_crds/bases/work.karmada.io_resourcebindings.yaml
- charts/_crds/bases/work.karmada.io_works.yaml
- pkg/apis/work/v1alpha1/work_types.go
- pkg/apis/work/v1alpha2/binding_types.go
/kind feature
```bash
[root@master67 karmada]# kubectl get work -A
NAMESPACE          NAME               APPLIED   AGE
karmada-es-bj-47   nginx-687f7fb96f   True      19m
[root@master67 karmada]# kubectl get rb -A
NAMESPACE   NAME               SCHEDULED   FULLYAPPLIED   AGE
default     nginx-deployment   True        True           19m
```
Fixes #1101 
```release-note
NONE
```
> Add more printcolumn for rb, crb and work when executing kubectl get

- pkg/util/objectwatcher/objectwatcher.go
/kind bug
/kind cleanup
Retain ownerReferences since they will typically be set by controllers in a member cluster.
Fixes #
```release-note
```
> retain ownerReferences when update member cluster object

- artifacts/example/clusteroverridepolicy.yaml
- artifacts/example/example-override.yaml
- artifacts/example/overridepolicy_command.yaml
- artifacts/example/overridepolicy_image.yaml
- artifacts/example/overridepolicy_simple.yaml
- pkg/util/overridemanager/overridemanager.go
/kind feature
* Implementing the new OverrideRules
* update [example artifacts](https://github.com/karmada-io/karmada/tree/master/artifacts/example) accordingly
See #1113 for more info.
We will now expand the `OverrideRules` into individual `policyOverriders` based on the filtering conditions:
```go
type policyOverriders struct {
name       string
namespace  string
overriders policyv1alpha1.Overriders
}
```
We use the following `overrideRules` as an example:
```yaml
overrideRules:
clusterNames:
- member1
- member2
overriders:
plaintext:
- operator: add
path: /metadata/annotations
value:
foo: bar
clusterNames:
- member2
overriders: …
```
> Implementing the new OverrideRules

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/controllers/mcs/service_export_controller.go
- pkg/controllers/status/cluster_status_controller.go
- pkg/controllers/status/workstatus_controller.go
/kind feature
```
I1215 12:51:03.337598       1 cluster_status_controller.go:87] Syncing cluster status: ntgxh-d
E1215 12:51:33.343648       1 cluster_status_controller.go:252] Failed to sync cache for cluster: ntgxh-d, error: informer for /v1, Resource=pods hasn't synced
E1215 12:51:33.343680       1 cluster_status_controller.go:149] Failed to get or create informer for Cluster ntgxh-d. Error: informer for /v1, Resource=pods hasn't synced.
```
```
synced := c.InformerManager.WaitForCacheSyncWithTimeout(cluster.Name, util.CacheSyncTimeout)
if synced == nil {
return fmt.Errorf("no informerFactory for cluster %s exist", cluster.Name)
}
for _, gvr := range gvrs {
if !synced[gvr] {
return fmt.Errorf("informer for %s hasn't …
```
> set default for clusterCacheSync timeout and make it configurable

- pkg/scheduler/core/division_algorithm.go
/kind cleanup
Remove redundant sort in `scaleUpScheduleByReplicaDivisionPreference` as the target clusters have been sorted in `calAvailableReplicas`
https://github.com/karmada-io/karmada/blob/f7b2a91eed08c65c2d534b31068dd19dffdbca30/pkg/scheduler/core/util.go#L73
Fixes #
```release-note
NONE
```
> Remove redundant sort in scale up schedule

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
/kind cleanup
This patch updates the comments I mentioned in https://github.com/karmada-io/karmada/pull/1093#pullrequestreview-829967849 and now the all controllers list in flag is not hard-coded:
```
--controllers strings                           A list of controllers to enable. '*' enables all on-by-default controllers, 'foo' enables the controller named 'foo', '-foo' disables the controller named 'foo'. All controllers: binding, cluster, clusterStatus, endpointSlice, execution, hpa, namespace, serviceExport, serviceImport, workStatus. (default [*])
```
Fixes #1085 …
> controller-manager: automatically generate all controllers list in flag

- artifacts/deploy/webhook-configuration.yaml
- charts/templates/_karmada_webhook_configuration.tpl
- cmd/webhook/app/webhook.go
- pkg/util/validation/validation.go
- pkg/util/validation/validation_test.go
- pkg/webhook/overridepolicy/validating.go
/kind feature
```yaml
[root@master67 karmada]# cat /root/lonelyCZ/yaml/override.yaml 
kind: OverridePolicy
metadata:
name: example-override
namespace: default
spec:
targetCluster:
labelSelector:
matchLabels:
location: us
overriders:
plaintext:
- operator: add
path: /metadata/annotations
value:
foo: bar
overrideRules:
clusterNames:
- member1
- member2
overriders:
plaintext:
- operator: add
path: /metadata/annotations
value:
foo: bar
```
```bash
[root@master67 karmada]# kubectl apply -f /root/lonelyCZ/yaml/override.yaml
Error from server (overrideRules and (overriders …
```
> Implementing karmada-webhook of validating OverridePolicy

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/execution/execution_controller.go
- pkg/controllers/mcs/service_export_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/util/helper/cache.go
/kind cleanup
Abort deleting workload when the member cluster is unready, otherwise we can't unjoin the member cluster when the member cluster is unready
Fixes #438
"NONE"
> abort deleting workload when the member cluster is unready

- artifacts/deploy/webhook-configuration.yaml
- charts/templates/_karmada_webhook_configuration.tpl
- cmd/webhook/app/webhook.go
- pkg/webhook/clusteroverridepolicy/validating.go
/kind feature
```bash
[root@master67 yaml]# kubectl apply -f clusteroverride.yaml 
Error from server (overrideRules and (overriders or targetCluster) can't co-exist): error when creating "clusteroverride.yaml": admission webhook "clusteroverridepolicy.karmada.io" denied the request: overrideRules and (overriders or targetCluster) can't co-exist
```
Part of #1113 
```release-note
NONE
```
> Implementing karmada-webhook of validating ClusterOverridePolicy

- charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
- charts/_crds/bases/work.karmada.io_resourcebindings.yaml
- cmd/controller-manager/app/controllermanager.go
- pkg/apis/work/v1alpha2/binding_types.go
- pkg/apis/work/v1alpha2/events.go
- pkg/controllers/binding/binding_controller.go
- pkg/controllers/execution/execution_controller.go
- pkg/detector/detector.go
- pkg/scheduler/scheduler.go
/kind cleanup
Most of users are more familiar with native kubernetes resources, add events to resource template is more friendly for users to use karmada.
Fixes #1016 
```
[root@karmada-lhb ~]#  kubectl describe deployments.apps nginx 
Name:                   nginx
Namespace:              default
CreationTimestamp:      Sun, 05 Dec 2021 14:53:00 +0800
Labels:                 app=nginx
propagationpolicy.karmada.io/name=nginx-propagation
propagationpolicy.karmada.io/namespace=default
Annotations:            <none>
Selector:               app=nginx
Replicas:               2 desired | 2 updated | 2 total | 2 …
```
> add events to resource template

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/utils/examples.go
/kind feature
change the default path to `/etc/karmada`
```
root@dev-k8s-master01:~# ./kubectl-karmada init -h
...
-d, --karmada-data string                              karmada data path. kubeconfig cert and crds files (default "/etc/karmada")
...
root@dev-k8s-master01:~# ls -lrt /etc/karmada/
total 76
-rw------- 1 root root  1675 Dec 21 15:19 ca.key
-rw-r--r-- 1 root root  1115 Dec 21 15:19 ca.crt
-rw------- 1 root root  1679 Dec 21 15:19 etcd-server.key
-rw-r--r-- 1 root root  1269 Dec 21 15:19 etcd-server.crt
-rw------- 1 root root  1675 Dec 21 15:19 etcd-client.key
-rw-r--r-- 1 root root  1168 Dec 21 15:19 etcd-client.crt
-rw------- 1 root root  1675 Dec 21 15:19 …
```
> change the default path of `karmadactl init`

- pkg/apis/policy/v1alpha1/override_utils.go
- pkg/util/overridemanager/overridemanager.go
- pkg/util/overridemanager/overridemanager_test.go
/kind cleanup
Continues #1114
This patch combines two similar `getOverridersFromClusterOverridePolicies`, `getOverridersFromOverridePolicies` methods into one, this makes it easier to maintain the method without having to copy the code.
And I have added some unit tests for the new `getOverridersFromOverridePolicies` method.
Fixes #
```release-note
NONE
```
> Refactor the matching method in overridemanager

- pkg/util/resource.go
/kind bug
If a pod request zero scalar resource, like `alpha.kubernetes.io/nvidia-gpu: '0'`, but the node does not have a resource called `alpha.kubernetes.io/nvidia-gpu`, scheduler-estimator will return 0 max replicas. It does not match what kubernetes does. In kubernetes, the zero scalar resource would be ignored even the node does not have this type of resource.
Fixes #
```release-note
NONE
```
> fix division bugs when pod request zero scalar resource

- artifacts/agent/clusterrole.yaml
- artifacts/agent/namespace.yaml
- artifacts/agent/serviceaccount.yaml
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/unifiedauth/unified_auth_controller.go
- pkg/karmadactl/join.go
- pkg/util/constants.go
- pkg/util/names/names.go
- pkg/util/rbac.go
/kind feature
1. create a service account for impersonation when joining clusters.
2. add impersonation config sync controller
Fixes #
self test:
step1: create a clusterrole in karmada control plane
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
name: karmada-cluster-proxy
rules:
- apiGroups:
- '*'
resources:
- cluster/proxy
resourceNames:
- member1
- member2
verbs:
- '*'
- nonResourceURLs:
- '*'
verbs:
- get
```
step2: create a clusterrolebinding in karmada control plane
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: karmada-cluster-proxy …
```
> add impersonation config sync controller

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/context/context.go
/kind feature
Add `--controllers` flag to karmada-agent and move `ControllerContext` to a separate package.
```
--controllers strings                           A list of controllers to enable. '*' enables all on-by-default controllers, 'foo' enables the controller named 'foo', '-foo' disables the controller named 'foo'. All controllers: clusterStatus, execution, serviceExport, workStatus. (default [*])
```
close #1127
```release-note
Add --controllers flag to karmada-agent.
```
> Add --controllers flag to karmada-agent and move ControllerContext to a separate package

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/check.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deployments.go
- pkg/karmadactl/cmdinit/kubernetes/namespace.go
- pkg/karmadactl/cmdinit/kubernetes/node.go
- pkg/karmadactl/cmdinit/kubernetes/rbac.go
- pkg/karmadactl/cmdinit/kubernetes/secret.go
- pkg/karmadactl/cmdinit/kubernetes/serviceaccount.go
- pkg/karmadactl/cmdinit/kubernetes/services.go
- pkg/karmadactl/cmdinit/kubernetes/statefulset.go
- pkg/karmadactl/cmdinit/options/global.go
- pkg/karmadactl/cmdinit/utils/format.go
- pkg/karmadactl/karmadactl.go
/kind cleanup
/kind feature
Simplify command flags.
No need to specify master IP, the default karmada-apiserver IP is kubernetes master IP. If kubernetes has no master role set, 3 node IPs will be randomly select.
```
W1223 15:31:31.404221 1585024 node.go:29] the kubernetes cluster does not have a Master role.
I1223 15:31:31.404258 1585024 node.go:37] randomly select 3 Node IPs in the kubernetes cluster.
I1223 15:31:31.406495 1585024 deploy.go:120] karmada apiserver ip: [172.31.6.145 172.31.6.147 172.31.6.148]
```
Fixes #
```
prodan@ubuntu:/opt/workspaces/karmada$ ./kubectl-karmada init -h
install karmada in kubernetes.
Usage:
karmada init [flags] …
```
> update `kubectl-karmada init`

- artifacts/agent/namespace.yaml
- artifacts/agent/serviceaccount.yaml
- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/unifiedauth/ensure_impersonation_secret.go
- pkg/controllers/unifiedauth/unified_auth_controller.go
- pkg/karmadactl/join.go
- pkg/util/namespace.go
- pkg/util/serviceaccount.go
/kind feature
#1104 add a new feature `unified auth`, it will create an impersonation serviceaccount in member clusters and collect related secret from member cluster to karmada control-plane.
Based on this, consider the upgrade scenario, for member clusters that have been added to karmada, we need to do the same things.
Fixes #
For the push mod cluster, the logic for the upgrade can be deleted in the next version.
```release-note
```
> Upgrade for unified auth

- docs/installation/fromsource.md
- hack/README.md
- hack/deploy-karmada-agent.sh
- hack/deploy-karmada.sh
- hack/remote-up-karmada.sh
- hack/undeploy-karmada.sh
/kind feature
When users deploy karmada by `remote-up-karmada.sh`, if the karmada-apiserver is the `clusterIP`, the agent can't be joined. And the network mode of `karmada-apiserver` pod is `hostNetwork`, so directly assigning this IP as karmada-apiserver ip.
Because `undeploy-karmada.sh` is suited for two mode, it needn't default for kind mode.
Fixes #
I have tested it in my environment.
```release-note
NONE
```
> Replace clusterIP with hostIP in karmada-kubeconfig when using remote-up-karmada.sh

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- pkg/karmadactl/join.go
- pkg/registry/cluster/storage/proxy.go
- pkg/util/cluster.go
- pkg/util/namespace.go
/kind feature
After #1122, #1158, we need to access `pull` Cluster through karmada wit AA, first of all, we need to complete ClusterSpec(proxy server and API endpoint) and create related impersonator secret for impersonation(#1104).
Fixes #1077 
```release-note
```
/cc @mrlihanbo @RainbowMango
> completes ClusterSpec and create impernator secret for pull mode cluster

- pkg/karmadactl/cmdinit/utils/examples.go
Output the karmada logo, karmada is ready.
```
root@dev-k8s-master01:~# ./kubectl-karmada init --karmada-data /etc/karmada-test -p 7443 --crds https://github.com/karmada-io/karmada/releases/download/v0.10.1/crds.tar.gz --etcd-storage-mode hostPath 
I1227 22:32:27.984272 2323359 deploy.go:104] kubeconfig file: /root/.kube/config, kubernetes: https://172.31.6.145:6443
W1227 22:32:28.013674 2323359 node.go:30] the kubernetes cluster does not have a Master role.
I1227 22:32:28.013708 2323359 node.go:38] randomly select 3 Node IPs in the kubernetes cluster.
I1227 22:32:28.015578 2323359 deploy.go:124] karmada apiserver ip: [172.31.6.145 172.31.6.147 172.31.6.148]
I1227 22:32:28.401439 2323359 cert.go:230] Generate ca …
```
> Log print karmada text logo

- pkg/apis/cluster/v1alpha1/types.go
- pkg/printers/interface.go
- pkg/printers/internalversion/printers.go
- pkg/printers/internalversion/printers_test.go
- pkg/printers/storage/storage.go
- pkg/printers/tablegenerator.go
- pkg/registry/cluster/storage/storage.go
/kind feature
As #1122 merged, cluster crd has been moved to aggregation apiserver. 
We need to expose more than name/creation timestamp columns for cluster api
Fixes #
```release-note
NONE
```
>  expose more than name/creation timestamp columns for cluster api

- cmd/aggregated-apiserver/app/options/options.go
- pkg/aggregatedapiserver/apiserver.go
- pkg/registry/cluster/storage/proxy.go
- pkg/registry/cluster/storage/storage.go
/kind bug
In the `pkg/registry` package, we should use the internal API version for cluster resources instead of a specific API version. 
```release-note
NONE
```
> remove the karmada client from aggregated-apiserver

- docs/working-with-anp.md
For the member cluster that joins karmada in pull mode, we need to provide a method to connect the network between the karmada control plane and the member clusters, so that karmada-aggregated-apiserver can access the pull mode member clusters. 
Deploying [apiserver-network-proxy](https://github.com/kubernetes-sigs/apiserver-network-proxy) to achieve appeal is one of the methods. 
Fixes #1077 
```release-note
NONE
```
> deploy apiserver-network-proxy

- hack/post-run-e2e.sh
- hack/pre-run-e2e.sh
- hack/run-e2e.sh
- hack/util.sh
- test/e2e/framework/workload.go
- test/e2e/resourceinterpreter_test.go
- test/e2e/suite_test.go
- test/helper/resource.go
/kind feature
Fixes #1136 
Install workload CRD by `pre-run-e2e.sh` that seemly need not to deploy cpp to propagation `workload` CRD, which is not closely related to interpreter test.
```release-note
NONE
```
/cc @RainbowMango @XiShanYongYe-Chang @iawia002
> Run karmada-interpreter-webhook-example in CI

- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deployments.go
/kind bug
Due to the change of crds, the method of `karmadactl init` to initialize aAPIService resource object should be `create` instead of `update`。
Fixes #1204
init logs
```
I0103 01:11:44.866334  951612 deploy.go:104] kubeconfig file: /root/.kube/config, kubernetes: https://172.31.6.145:6443
W0103 01:11:44.881014  951612 node.go:30] the kubernetes cluster does not have a Master role.
I0103 01:11:44.881037  951612 node.go:38] randomly select 3 Node IPs in the kubernetes cluster.
I0103 01:11:44.883599  951612 deploy.go:124] karmada apiserver ip: [172.31.6.145]
I0103 01:11:45.185244  951612 cert.go:230] …
```
> Fix karmadactl init not found v1alpha1.cluster.karmada.io object

- hack/util.sh
/kind cleanup
What: add error message when wait file exist timeout 
Why: call util::wait_file_exist() timeout but had no message return that causes confused.
> add error message when wait file exist timeout

- docs/userguide/cherry-picks.md
- hack/cherry_pick_pull.sh
/kind feature
As [release-1.0](https://github.com/karmada-io/karmada/tree/release-1.0) published, we need a script to backport some PRs from master to release branches.
```release-note
add a script and document for cherry-pick pull
```
> add script and doc for cherry_pick_pull

- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deployments.go
Cherry pick of #1207 on release-1.0.
#1207: Fix karmadactl init not found v1alpha1.cluster.karmada.io
For details on the cherry pick process, see the [cherry pick requests](https://github.com/karmada-io/karmada/blob/master/docs/userguide/cherry-picks.md) page.
```release-note
karmadactl: fixed `init` can not update APIService issue.
```
> Automated cherry pick of #1207: Fix karmadactl init not found v1alpha1.cluster.karmada.io

- pkg/util/helper/binding.go
- pkg/util/resource.go
/kind bug
1. If pod limits are specified, but requests are not, default requests to limits.
2. If Overhead is being utilized, add to the total requests for the pod.
Fixes #
```release-note
NONE
```
> fix bug of resource computing

- pkg/controllers/execution/execution_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/util/helper/workstatus.go
/kind cleanup
There are two backoff options for `retry.RetryOnConflict`:
```go
// DefaultRetry is the recommended retry for a conflict where multiple clients
// are making changes to the same resource.
var DefaultRetry = wait.Backoff{
Steps:    5,
Duration: 10 * time.Millisecond,
Factor:   1.0,
Jitter:   0.1,
}
// DefaultBackoff is the recommended backoff for a conflict where a client
// may be attempting to make an unrelated modification to a resource under
// active management by one or more controllers.
var DefaultBackoff = wait.Backoff{
Steps:    4,
Duration: 10 * time.Millisecond,
Factor:   5.0,
Jitter:   0.1,
}
```
The main difference between the two `backoff` is the retry interval(different `Factor`).
In our …
> Replace all the retry.DefaultBackoff with retry.DefaultRetry

- charts/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
- charts/_crds/bases/policy.karmada.io_overridepolicies.yaml
- pkg/apis/policy/v1alpha1/override_types.go
- pkg/util/overridemanager/overridemanager.go
- pkg/util/validation/validation.go
Mark `spec.targetCluster` and `spec.overriders` deprecated in favor of `.spec.overrideRules`.
Fixes #1113 
```release-note
OverridePolicy/ClusterOverridePolicy: The `.spec.targetCluster` and `spec.overriders` have been deprecated in favor of `spec.overrideRules`.
```
> mark override policy spec.targetCluster and spec.overriders deprecated

- docs/working-with-anp.md
Complete missing step for `working-with-anp.md`. After deploying ANP, we need to add command flags `cluster-api-endpoint` and `proxy-server-address` for karmada-agent deployment.
Fixes #
```release-note
NONE
```
> Complete missing step for working-with-anp

- pkg/scheduler/scheduler.go
/kind bug
when **updateBindingScheduledConditionIfNeeded** return error, we should retry it in next loop according to the comments
but the error will not be used as a return value. 
https://github.com/karmada-io/karmada/blob/9167f9bce4fac02634bc3568977f24d0ae4b3213/pkg/scheduler/scheduler.go#L418-L423
just return nil even if **updateBindingScheduledConditionIfNeeded** return error
https://github.com/karmada-io/karmada/blob/9167f9bce4fac02634bc3568977f24d0ae4b3213/pkg/scheduler/scheduler.go#L456-L458
NONE
```release-note
NONE
```
> [scheduler]fix a defer execution sequence problem

- pkg/detector/detector.go
Cherry pick of #1267 on release-1.0.
#1267: fix event type of apply policy
```release-note
karmada-controller-manager: Fixed ApplyPolicySucceed event type mistake(should be `Normal` but `Warning`).
```
> Automated cherry pick of #1267: fix event type of apply policy

- pkg/scheduler/event_handler.go
- pkg/scheduler/scheduler.go
/kind feature
it is a code structure optimizition to split the code about resource event into event_handler.go
change **WaitForCacheSync**  to **s.informerFactory.WaitForCacheSync** for all imformer's resource sync and not just synchronization of  the  resource binding 
https://github.com/karmada-io/karmada/blob/361978a3bf339db62b27757eacb45cf8194135ac/pkg/scheduler/scheduler.go#L190-L192
Fixes #
NONE
NONE
```release-note
```
> [optimize]split the code about resource event into event_handler.go

- pkg/controllers/binding/common.go
- pkg/detector/detector.go
- pkg/resourceinterpreter/customizedinterpreter/customized.go
- pkg/resourceinterpreter/interpreter.go
- pkg/util/interpreter/rules.go
- pkg/util/objectwatcher/objectwatcher.go
/kind cleanup
`HookEnabled` interface with resource interpreter feature can be refactored to need objectGVK instead of object parameter.
Fixes #
```release-note
NONE
```
> Update HookEnabled interface with resourceinterpreter

- cmd/webhook/app/options/options.go
- cmd/webhook/app/webhook.go
/kind feature
Some users want to config the [TLS MinVersion](https://github.com/golang/go/blob/897b3da2e079b9b940b309747305a5379fffa6ec/src/crypto/tls/common.go#L685-L695) for karmada-webhook.
Fixes #1272 
```release-note
karmadactl: Introduced `--tls-min-version` flag to specify the minimum TLS version.
```
> introduce --tls-min-version flag to karmada-webhook

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
/kind cleanup
It is a temporary solution. Should be rebased into release-1.0.
Fixes https://github.com/karmada-io/karmada/issues/1260#issuecomment-1012982605
```release-note
Fixed controller resync slow down reconcile issue.
```
> stop resync for controllers

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
Cherry pick of #1265 on release-1.0.
#1265: set resync period to 0
```release-note
Fixed controller resync slow down reconcile issue.
```
> Automated cherry pick of #1265: set resync period to 0

- pkg/karmadactl/get.go
/kind feature
Optimize output content.
```bash
[root@master67 karmada]# ./karmadactl get pod -o wide
NAME                     CLUSTER   READY   STATUS      RESTARTS   AGE    IP             NODE       NOMINATED NODE   READINESS GATES   ADOPTION
nginx-6799fc88d8-4dkqm   member1   1/1     Running     0          3d5h   10.244.0.102   master68   <none>           <none>            N
pi--1-7rpgp              member1   0/1     Completed   0          10h    10.244.0.103   master68   <none>           <none>            N
pi--1-h7zdq              member1   0/1     Completed   0          10h    10.244.0.105   master68   <none>           <none>            N
pi--1-z65zd              member1 …
```
> Optimize karmadactl get to output more information

- hack/util.sh
/kind feature
When the pod is in crashloopback state and there are no events to help troubleshoot the error, we need to query the pod's log to get more debug information.
for example: the webhook program fails to start due to a code logic error
```
kubectl logs info:
386
--skip_headers                     If true, avoid header prefixes in the log messages
387
--skip_log_headers                 If true, avoid headers when opening log files
388
--stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
389
--tls-min-version string           Minimum TLS version supported. Possible values: VersionTLS10, VersionTLS11, VersionTLS12, VersionTLS13. …
```
> print pod's log when waiting pod ready timeout

- artifacts/agent/karmada-agent.yaml
- artifacts/deploy/controller-manager.yaml
- artifacts/deploy/karmada-aggregated-apiserver.yaml
- artifacts/deploy/karmada-scheduler-estimator.yaml
- artifacts/deploy/karmada-scheduler.yaml
- artifacts/deploy/karmada-webhook.yaml
/kind feature
Now, most Karmada components run only 1 replica in our CI environment, but users might deploy more than one replicas in the industry environment.
Enable multi-replica in the CI environment that may help find some issues.
Fixes #1078 
```release-note
NONE
```
> Enable multi replicas in CI 

- pkg/detector/detector.go
/kind bug
/kind flake
The root cause is as the follow process:
We must **add the resource to waiting list before looking up the matched propagation policy**, so that the matched resource can always be found when reconciling propagation policies
Fixes #1195
```release-note
NONE
```
> bugfix: resource binding is not created when creating resources and propagation policies at the same time

- cmd/scheduler/main.go
/kind bug
os.Exit will not wait for the defer function
Fixes #
```release-note
Fix failed flushing logs when scheduler os.Exit(1).
```
> os.Exit will not wait for the defer function

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
/kind bug
Fixes part of #1260
```release-note
`karmada-controller-manager`/`karmada-agent`: introduced `--resync-period` flag to specify reflectors resync period(defaults to 0 means no resync)
```
> Introduce `--resync-period` flag to specify reflector resync period

- pkg/controllers/status/cluster_status_controller.go
/kind cleanup
if apiResourceList is not sorted, the cluster object will keep updating.
Fixes #
```release-note
karmada-controller-manager/karmada-agent: Fixed cluster status continually updating issue which is due to unordered apiEnablements.
```
> fixed apiEnablements unordered issue

- hack/create-cluster.sh
/kind flake
support the specified Version and the default version is the same as hack/local-up-karmada.sh when using hack/create-cluster.sh to create kind cluster 
Fixes #
```release-note
NONE
```
> set the kindest/node default version to v1.22.0 in create-cluster.sh

- pkg/scheduler/core/division_algorithm.go
- pkg/scheduler/core/division_algorithm_test.go
- pkg/scheduler/core/util.go
/kind bug
because the spreadconstraints[i].maxgroup define the max cluster number, So the target cluster number  could not  be greater than it in any scenario.
The difference between the current cluster and the scheduled cluster is not considered when calculating the scheduled replicas
Fixes #1323 
let's test it According to the issue #1323  operation
before scaleup
```
spec:
clusters:
- name: member1
replicas: 55
- name: member2
replicas: 55
replicas: 110
```
after scaleup
```
spec:
clusters:
- name: member2
replicas: 95
- name: member3
replicas: 85
replicas: 180
```
NONE …
> fix spreadconstraints[i].MaxGroups Invalidation when scaleup replicas

- pkg/karmadactl/get.go
/kind bug
Before, we execute `karmadactl get deploy nginx -C member1 -o yaml`, the output is unreadable.
```yaml
[root@master67 karmada]# karmadactl get deploy nginx -C member1 -o yaml
apiVersion: meta.k8s.io/v1
columnDefinitions:
- description: 'Name must be unique within a namespace. Is required when creating
resources, although some resources may allow a client to request the generation
of an appropriate name automatically. Name is primarily intended for creation
idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names'
format: name
name: Name
priority: 0
type: string
- description: ""
format: ""
name: …
```
> Fix karmadactl get -o yaml|json

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
/kind cleanup
Fixes #
```release-note
karmada-controller-manager: Introduced `--metrics-bind-address` flag to specify the customized address for metrics.
```
> Introduce `--metrics-bind-address` flag to `karmada-controller-manager`

- cmd/aggregated-apiserver/app/options/options.go
/kind feature
informerfactory uses --kubeconfig to communicate with coreapiserver, we should reuse the same configuration.
```go
func (o *CoreAPIOptions) ApplyTo(config *server.RecommendedConfig) error {
if o == nil {
return nil
}
// create shared informer for Kubernetes APIs
var kubeconfig *rest.Config
var err error
if len(o.CoreAPIKubeconfigPath) > 0 {
loadingRules := &clientcmd.ClientConfigLoadingRules{ExplicitPath: o.CoreAPIKubeconfigPath}
loader := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, &clientcmd.ConfigOverrides{})
kubeconfig, err = loader.ClientConfig()
if err != nil {
return fmt.Errorf("failed to load kubeconfig at %q: …
```
> deprecate --master and --karmada-config flags for aggregrated-apiserver

- cmd/aggregated-apiserver/app/options/options.go
- cmd/controller-manager/app/options/options.go
- cmd/scheduler/app/options/options.go
- cmd/webhook/app/options/options.go
/kind cleanup
As discussed in https://github.com/karmada-io/karmada/pull/1336#pullrequestreview-875652444, we need to modify the usage description of `kubeconfig` flag to the correct meaning.
Fixes #
```release-note
Modify the kubeconfig usage description of the `karmada-controller-manager/karmada-scheduler/karmada-webhook/karmada-aggregated-apiserver` executable file.
```
> improve the usage description of `--kubeconfig` flag

- cmd/controller-manager/app/options/options.go
- cmd/webhook/app/options/options.go
- cmd/webhook/app/webhook.go
/kind feature
Some users want to config the MetricsBindAddress and HealthProbeBindAddress for karmada-webhook.
Fixes #
It can be set to "0" to disable the metrics serving and health probe serving.
```release-note
karmada-webhook: Introduced --metrics-bind-address and --health-probe-bind-address flags.
```
> Introduce `--metrics-bind-address` and `--health-probe-bind-address` flags to `karmada-webhook`

- .github/workflows/image.yml
Signed-off-by: zach593 <zach_li@outlook.com>
/kind bug
fixed some build/CI bugs and **add automated image builds when publish new releases**
- latest images didn't carry "GitVersion"
- versioned karmadactl/kubectl-karmada still ref to latest images, it causes https://github.com/karmada-io/karmada/issues/1291#issuecomment-1018307337 
just please feel free to let me know if there is anything needs improvements
```release-note
None
```
> fixes gitVersion is missing from the latest image issue

- pkg/detector/detector.go
/kind bug
The workaround in [#1199](https://github.com/karmada-io/karmada/pull/1199#issuecomment-1019813479) does not work with [multiple workers](https://github.com/karmada-io/karmada/pull/1321), so this pr does 2 things
1. Revert #1199
2. If the matched policy is not found, retry once to avoid the bug
Fixes #1195
```release-note
NONE
```
> Rework "bugfix: resource binding not created occasionally"

- cmd/scheduler-estimator/app/scheduler-estimator.go
- pkg/controllers/execution/execution_controller.go
- pkg/controllers/mcs/service_export_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/estimator/server/metrics/metrics.go
- pkg/estimator/server/replica/replica.go
- pkg/estimator/server/server.go
- pkg/estimator/server/server_test.go
- pkg/util/helper/cache.go
- pkg/util/helper/pod.go
- pkg/util/informermanager/single-cluster-manager.go
- pkg/util/workload/deployment.go
- vendor/k8s.io/client-go/discovery/cached/memory/memcache.go
- vendor/k8s.io/client-go/dynamic/fake/simple.go
- vendor/modules.txt
/kind feature
Implement GetUnschedulableReplicas for estimator so that the descheduler could know how many unschedulable replicas exist.
Fixes part of #1262
```release-note
Implement GetUnschedulableReplicas for estimator
```
> Descheduler: Implement GetUnschedulableReplicas for estimator

- hack/local-up-karmada.sh
/kind feature
To demonstrate the MCI feature, `ingress-nginx` will be deployed on the `karmada-host` cluster to access services in the member cluster. Therefore, the network between `karmada-host`, `member1` and `member2` needs to be connected.
Fixes #
```release-note
NONE
```
/cc @mrlihanbo @RainbowMango
> connect networks between karmada-host, member1 and member2

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/clusterdiscovery/clusterapi/clusterapi.go
- pkg/controllers/context/context.go
- pkg/controllers/status/workstatus_controller.go
- pkg/controllers/unifiedauth/unified_auth_controller.go
- pkg/detector/detector.go
/kind feature
Make controller reconcile concurrent configurable
Fixes #
```release-note
`karmada-controller-manager`: Introduced several flags to specify controller's capacities:
- --concurrent-work-syncs
- --concurrent-namespace-syncs
- --concurrent-resource-template-syncs
- --concurrent-cluster-syncs
- --concurrent-clusterresourcebinding-syncs
- --concurrent-resourcebinding-syncs
`karmada-agent`: Introduced several flags to specify controller's capacities:
- --concurrent-work-syncs
- --concurrent-cluster-syncs
The larger number of these flags means …
```
> introduce concurrent flags to controllers

- charts/_crds/kustomization.yaml
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
- pkg/util/constants.go
/kind feature
Add federated-resource-quota-sync-controller to sync FederatedResourceQuota to member clusters. When cluster joins, karmada will automatically sync ResourceQuota to the cluster.
Fixes #
Relying on #1387 
```release-note
Add FederatedResourceQuota sync controller.
```
> Add FederatedResourceQuota sync controller

- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
/kind feature
Add federated-resource-quota-status-controller to collect status form works created by federated-resource-quota-sync-controller.
Fixes #
Relying on #1398 
When we apply a demo federatedResourceQuota:
```yaml
kind: FederatedResourceQuota
metadata:
name: quota-demo
spec:
overall:
cpu: "1000"
memory: 200Gi
staticAssignments:
- clusterName: member1
hard:
cpu: "100"
memory: 10Gi
- clusterName: member2
hard:
cpu: "300"
memory: 20Gi
```
Then we can get it like:
```yaml
kind: FederatedResourceQuota
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: | …
```
> Add FederatedResourceQuota status controller

- pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
- pkg/util/helper/binding.go
- pkg/util/helper/work.go
- pkg/util/helper/workstatus.go
/kind cleanup
Functions `func GetWorks(c client.Client, ls labels.Set) (*workv1alpha1.WorkList, error)` and `func GetWorksByLabelSelector(c client.Client, selector labels.Selector) (*workv1alpha1.WorkList, error)` have the same effect, eliminating one of them.
Fixes #
```release-note
NONE
```
> remove duplicated `GetWorks` function

- pkg/util/secret.go
/kind bug
when secret exist, will return empty secret: https://github.com/karmada-io/karmada/blob/master/pkg/util/secret.go#L46 
it will return error when create cluster:
```
W0123 15:16:21.031729 2061975 cluster.go:106] failed to create cluster(kind-kind-k8s-1-23). error: Cluster.cluster.karmada.io "kind-kind-k8s-1-23" is invalid: [spec.secretRef.namespace: Required value, spec.secretRef.name: Required value, spec.impersonatorSecretRef.namespace: Required value, spec.impersonatorSecretRef.name: Required value]
W0123 15:16:21.031749 2061975 cluster.go:50] failed to create cluster(kind-kind-k8s-1-23). error: Cluster.cluster.karmada.io "kind-kind-k8s-1-23" is invalid: [spec.secretRef.namespace: Required value, …
```
> fix:  karmada join failed when secret exist

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- go.mod
- pkg/clusterdiscovery/clusterapi/clusterapi.go
- pkg/controllers/binding/binding_controller.go
- pkg/controllers/binding/cluster_resource_binding_controller.go
- pkg/controllers/context/context.go
- pkg/controllers/execution/execution_controller.go
- pkg/controllers/mcs/service_export_controller.go
- pkg/controllers/status/cluster_status_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/dependenciesdistributor/dependencies_distributor.go
- pkg/descheduler/descheduler.go
- pkg/detector/detector.go
- pkg/scheduler/scheduler.go
- pkg/util/ratelimiter/rate_limiter.go
- pkg/util/worker.go
/kind cleanup
introduce flags for user to tune ratelimiter
Fixes #
```release-note
`karmada-controller-manager`: Introduce several flags to specify controller's capacities:
- --rate-limiter-base-delay
- --rate-limiter-max-delay
- --rate-limiter-qps
- --rate-limiter-bucket-size
```
> Introduce ratelimiter flags

- pkg/karmadactl/cmdinit/karmada/check.go
- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- vendor/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/helper/helpers.go
- vendor/modules.txt
/kind feature
Add check for cluster apiservice when install karmada with kubectl-karmada
Fixes #1422
```release-note
feature: Add check for cluster apiservice when install karmada with kubectl-karmada
```
> Wait for APIService status when installing karmada with `karmadactl init`

- pkg/scheduler/core/division_algorithm.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/core/util.go
- pkg/scheduler/event_handler.go
- pkg/scheduler/scheduler.go
- test/e2e/rescheduling_test.go
/kind feature
support rescheduling when deleting a cluster
Fixes #829
Fixes #1411
This PR does not consider the spreadconstraints and it will be considered in the scheduler refactoring .
```release-note
`karmada-scheduler`: Workload is now able to reschedule after the cluster be unregistered.
```
> [feature]support rescheduling when deleting a cluster

- pkg/karmadactl/karmadactl.go
/kind bug
fix bug: fix can not use '-v 6' to set log level when run kubectl-karmada
Fixes #
```release-note
fix bug: fix can not use '-v 6' to set log level when run kubectl-karmada
```
> fix bug: fix can not use '-v 6' to set log level when run kubectl-karmada

- pkg/scheduler/core/generic_scheduler.go
- test/e2e/rescheduling_test.go
/kind flake
fix the failover e2e test failed
the rescheduling 
Fixes #
```release-note
NONE
```
> fix failing failover testing

- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deployments.go
Signed-off-by: sayaoailun <guojianwei007@126.com>
/kind bug
The flag `-n` of karmadactl doesn't work as expected
Fixes #
```release-note
`karmadactl`: Fixed `--namespace` flag of `init` command not work issue.
```
> `karmadactl`: Fixed `--namespace` flag of `init` command not work issue.

- api/openapi-spec/swagger.json
- hack/tools/swagger/generateswagger.go
- hack/tools/swagger/lib/render.go
- hack/tools/swagger/lib/storage.go
- hack/update-codegen.sh
- hack/update-swagger-docs.sh
- pkg/apis/cluster/v1alpha1/types.go
- pkg/apis/config/v1alpha1/doc.go
- pkg/apis/config/v1alpha1/resourceinterpreterwebhook_types.go
- pkg/apis/networking/v1alpha1/doc.go
- pkg/apis/networking/v1alpha1/ingress_types.go
- pkg/apis/policy/v1alpha1/doc.go
- pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
- pkg/apis/policy/v1alpha1/override_types.go
- pkg/apis/policy/v1alpha1/propagation_types.go
- pkg/apis/work/v1alpha1/doc.go
- pkg/apis/work/v1alpha1/work_types.go
- pkg/apis/work/v1alpha2/binding_types.go
- pkg/apis/work/v1alpha2/doc.go
- pkg/generated/openapi/zz_generated.openapi.go
/kind feature
Automatically generate API document for Karmada CRD.
Fixes #1367 
I researched this function in multiple project these days, and I found that most projects implement CRUD of the APIs  by themselves and then regenerate it into documentation.
If we only want the default CRUD interface, we need to register the CRD into the API Server first and then export the default interface.
There is no better way yet and what do you think of this？
Now just to show the effect, there's a lot of detail need to be completed.
```release-note …
```
> Generate API documents for Karmada CRD

- pkg/scheduler/core/division_algorithm.go
/kind cleanup
this fix is a supplement to this fix #1383 .
There is a problem that the rb spec.Clusters is not updated to cluster A finally  in the following scenario:
Fixes #
```release-note
NONE
```
> fix rb spec.Clusters is incorrent in some scenarios

- charts/Chart.yaml
/kind bug
Fixes https://github.com/karmada-io/karmada/issues/1339
```release-note
`helm chart`: fix version constraints skip pre-releases issue.
```
> [helm chart] fix version constraints skip prerelease issue

- charts/Chart.yaml
Cherry pick of #1444 on release-1.1.
#1444: Fix helm charts k8s version check
```release-note
`helm chart`: fix version constraints skip pre-releases issue.
```
> Automated cherry pick of #1444: Fix helm charts k8s version check

- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/utils/format.go
/kind feature
When the current host uses init to install karmada multiple times, the installation fails because the data directory of karmada is not empty.
Fixes #1454 
Fixes #1467
```release-note
`karmadactl`: Fixed `init` failure due to data path not clean issue.
```
> delete the karmada data directory before installing with init

- cmd/webhook/app/options/options.go
- cmd/webhook/app/webhook.go
/kind feature
Make webhook server certificate name and key name configurable. 
Fixes #
```release-note
`karmada-webhook`: introduced `--tls-cert-file-name` and `--tls-private-key-file-name` flags to specify server certificate and private key.
```
> make webhook server certificate name and key name configurable

- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/utils/format.go
Cherry pick of #1455 on release-1.0.
#1455: delete the karmada data directory before installing with init
```release-note
`karmadactl`: Fixed `init` failure due to data path not clean issue.
```
> Automated cherry pick of #1455: delete the karmada data directory before installing with init

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
/kind bug
Fixes #1430 
```release-note
Fix `karmadactl init` can not read KUBECONFIG environment variable issue
```
/cc @RainbowMango  @XiShanYongYe-Chang @prodanlabs
> Fix `karmadactl init` can not read KUBECONFIG environment variable issue

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/sharedcli/commandusage.go
- pkg/sharedcli/docs.go
- pkg/sharedcli/klogflag/klogflag.go
- vendor/k8s.io/component-base/term/OWNERS
- vendor/k8s.io/component-base/term/term.go
- vendor/modules.txt
/kind feature
Grouping flags for better readability.
Full help info now is:
<details>
<summary>Click here for full output</summary>
-bash-4.2# ./karmada-controller-manager --help 
The karmada controller manager runs a bunch of controllers
Usage:
karmada-controller-manager [flags]
Available Commands:
karmada-controller-manager completion                      generate the autocompletion script for the specified shell
karmada-controller-manager help                            Help about any command
karmada-controller-manager version                         Print the version information.
Generic flags:
--bind-address string …
> grouping flags for karmada-controller-manager

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
Cherry pick of #1437 on release-1.1.
#1437: can not read KUBECONFIG
```release-note
Fix `karmadactl init` can not read KUBECONFIG environment variable issue
```
> Automated cherry pick of #1437: fix `karmadactl init` can not read KUBECONFIG environment variable issue

- cmd/agent/app/agent.go
/kind feature
It make flags of command clearer. 
Fixes #
I'm not sure the place of `group.go` should be, and leave it here for the time being.
```release-note
NONE
```
> Implement flags grouping for karmada-agent

- .github/workflows/ci.yml
/kind feature
Support run CI with multi version kubernetes.
Fixes #
Current kubernetes versions:
- v1.21
- v1.22
- v1.23
```release-note
Support run CI with multi version kubernetes
```
> [CI] Support run CI with multi version kubernetes

- cmd/scheduler-estimator/app/options/options.go
- cmd/scheduler-estimator/app/scheduler-estimator.go
/kind feature
Implement flags grouping for karmada-scheduler-estimator #1485
Fixes #
```release-note
NONE
```
> Implement flags grouping for karmada-scheduler-estimator

- cmd/aggregated-apiserver/app/aggregated-apiserver.go
/kind feature
Implement flags grouping for karmada-aggregated-apiserver #1485 
Fixes #
```release-note
NONE
```
> Implement flags grouping for karmada-aggregated-apiserver

- pkg/dependenciesdistributor/dependencies_distributor.go
/kind bug
Bugfixs of dependencies distributor :
1. Enqueue the resource binding that has been scheduled to member clusters. 
2. Update Resource info when update attached bindings. 
3. Add some logs.
Fixes #
```release-note
`karmada-controller-manager`: Fixed ResourceBinding maybe prevents en-queue in case of schedule failure.
```
> bugfixs of dependencies distributor 

- Makefile
/kind cleanup
Inspired by #1498.
This PR added endpoints for components to build and push images to DockerHub.
These endpoints are intended to be invoked by GitHub workflow or manual. 
Fixes #
Try it with the following environments:
$ export REGISTRY_USER_NAME=<DockerHub username>
$ export REGISTRY_PASSWORD=<DockerHub password>
```release-note
NONE
```
> enable build multi platforms image

- pkg/dependenciesdistributor/dependencies_distributor.go
Cherry pick of #1499 on release-1.1.
#1499: bugfix: enqueue the resource binding that has been scheduled to member clusters.
```release-note
`karmada-controller-manager`: Fixed ResourceBinding maybe prevents en-queue in case of schedule failure.
```
> Automated cherry pick of #1499: bugfix: enqueue the resource binding that has been

- Makefile
Cherry pick of #1502 on release-1.0.
#1502: enable build multi platforms image
```release-note
NONE
```
Note: This is not a bug fix but it'll help build images after the new release is cut.
> Automated cherry pick of #1502: enable build multi platforms image

- .github/workflows/ci.yml
/kind cleanup
This PR sets ` hack/verify-swagger-docs.sh` which is contributed by #1510(@lonelyCZ) in the CI workflow.
Fixes #
```release-note
NONE
```
> Verify swagger docs in CI

- pkg/util/helper/workstatus.go
- pkg/util/helper/workstatus_test.go
/kind bug
add the Judgment Condition **len(clusterNames) != 0** to fix #1511
Fixes #1511
```release-note
`karmada-controller-manager`: Fixed the `FullyApplied` condition of `ResourceBinding/ClusterResourceBinding` mislabeling issue in case of non-scheduled. 
```
> Fixed the `FullyApplied` condition of `RB/CRB` mislabeling issue in case of non-scheduled.

- pkg/util/helper/workstatus.go
- pkg/util/helper/workstatus_test.go
Cherry pick of #1512 on release-1.1.
#1512:  fix the fulluapplied status is wrong in some scenario
```release-note
`karmada-controller-manager`: Fixed the `FullyApplied` condition of `ResourceBinding/ClusterResourceBinding` mislabeling issue in case of non-scheduled. 
```
> Automated cherry pick of #1512:  fix the fulluapplied status is wrong in some scenario

- test/e2e/mcs_test.go
/kind cleanup
In order to avoid resource residue caused by processing errors during the judgment process, move the cleaning step to `ginkgo.AfterEach`.
Fixes #
```release-note
NONE
```
> [E2E] move clean operation to AfterEach

- pkg/controllers/binding/common.go
/kind bug
When execution controller update resource failed, the work's fully applied condition will be set to `False`, but the `ManifestStatuses ` won't be changed(as updated failed). Under this circumstance，binding controller also need to aggregate  work status.
Fixes #
```release-note
`karmada-controller-manager`: Fixed RB/CRB controller can't aggregate status in case of work condition update issue.
```
> bugfix: update binding status when work's applied condition status changed

- pkg/controllers/binding/common.go
Cherry pick of #1513 on release-1.1.
#1513: bugfix: aggregate status to binding when work's applied condition status changed
```release-note
`karmada-controller-manager`: Fixed RB/CRB controller can't aggregate status in case of work condition update issue.
```
> Automated cherry pick of #1513: bugfix: aggregate status to binding when work's applied condition status changed

- cluster/images/karmada-agent/Dockerfile
- cluster/images/karmada-aggregated-apiserver/Dockerfile
- cluster/images/karmada-controller-manager/Dockerfile
- cluster/images/karmada-descheduler/Dockerfile
- cluster/images/karmada-interpreter-webhook-example/Dockerfile
- cluster/images/karmada-scheduler-estimator/Dockerfile
- cluster/images/karmada-scheduler/Dockerfile
- cluster/images/karmada-webhook/Dockerfile
- hack/local-up-karmada.sh
/kind cleanup
This PR updated the alpine base image from v3.7 to v3.15.1 because v3.7 is not supported now.
Fixes #
```release-note
NONE
```
> bump alpine base image from v3.7 to v3.15.1

- artifacts/deploy/cluster-proxy-admin-rbac.yaml
- hack/deploy-karmada.sh
/kind feature
`system:admin` should have highest authority to access all member cluster, so add rbac for admin when deploy Karmada control plane.
Part of #1329 
For this https://github.com/karmada-io/karmada/pull/1478#issuecomment-1076274176 , we need to discuss where to put notifications to users.
```release-note
NONE
```
> Add cluster proxy rbac for admin when deploy Karmada control plane

- pkg/karmadactl/get.go
- pkg/karmadactl/get_flags.go
/kind feature
step1: Use `cluster/proxy` to access resources of member clusters.
step2: Authorize `system:admin` to use `cluster/proxy` when join a member cluster to control plane.
When users don't have right to use `cluster/proxy` resource:
```
[root@master67 karmada]# ./karmadactl get pod
Error: users "system:admin" is forbidden: User "system:serviceaccount:karmada-cluster:karmada-impersonator" cannot impersonate resource "users" in API group "" at the cluster scope
```
Fixes #1329 
There are some key points needing to resolve.
```release-note
Enable …
```
> Enable `karmadactl get` command to leverage aggregated API

- .github/workflows/dockerhub-released-image.yml
- .github/workflows/swr-released-image.yml
- Makefile
/kind cleanup
Build and push release image to SWR and DockerHub.
Fixes #
Before #1515  we add `mp-image-karmada-descheduler` in Makefile, but `release-1.1` do not have `karmada-descheduler` in Makefile.
```release-note
Build and push release image to SWR and DockerHub.
```
> Build and push release image to SWR and DockerHub

- pkg/controllers/binding/common.go
/kind cleanup
For job completions setting, the judgement  `resourceInterpreter.HookEnabled(clonedWorkload.GroupVersionKind(), configv1alpha1.InterpreterOperationReviseReplica)`  is not needed. 
https://github.com/karmada-io/karmada/blob/042762b096a918866f91c6b663962942bb0958c9/pkg/controllers/binding/common.go#L98-L117
Fixes #
This pr is just a code readability optimization.
```release-note
NONE
```
> update the judgement for setting completions with job

- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/framework/interface.go
- pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
- pkg/scheduler/framework/plugins/clusterlocality/cluster_locality.go
- pkg/scheduler/framework/plugins/registry.go
- pkg/scheduler/scheduler.go
/kind feature
Currently, the spreadConstraint choose clusters just by clusterName.
in the rescheduling scenario, we hope the replicas in the scheduled clusters are not Migrated when they meet the filter conditions.
The plugin clusterlocality is aim to supply the preferred policy to favors cluster that already have requested.
a part of https://github.com/karmada-io/karmada/issues/1330
```release-note
add a score plugin clusterLocality to favors cluster that already have requested
```
> add plugin clusterLocality to favor cluster

- test/e2e/aggregatedapi_test.go
For failing test: https://github.com/karmada-io/karmada/runs/5700580290?check_suite_focus=true
The failing reason: when a serviceAccount is created in the member cluster, the namespace where the resource resides has not been propagated by the karmada control-plane.
Fixes #
```release-note
[E2E] fix failing e2e case for namespace not found
```
> [E2E] fix failing e2e case for namespace not found

- pkg/detector/detector.go
/kind cleanup
In karmada, resource binding won't be deleted if reference propagation policy is deleted. It will trigger reschedule if the status of reference resource changes, which will lead to endless requeue due to the reference propagation policy is deleted.
```
I1228 07:07:22.664714       1 event.go:291] "Event occurred" object="default/nginx-deployment" kind="ResourceBinding" apiVersion="work.karmada.io/v1alpha2" type="Warning" reason="ScheduleBindingFailed" message="propagationpolicy.policy.karmada.io \"nginx-propagation\" not found"
```
Fixes #
The pr works with #1178  …
> update binding's labels when it's policy has been deleted

- hack/util.sh
/kind cleanup
When I used hack/local-up-karmada.sh to install karmada for the first time in local, the k8s cluster was not created due to the image. Since there was no reminder and I didn’t know where the log file was, I had to look at the docker log for query reasons. I think it is necessary to remind the user in the script where the cluster creation log is located
> [fix] Add a log reminder for creating a cluster

- docs/userguide/configure-controllers.md
This PR set up the documentation about the controller we inherited from Kubernetes.
And takes the `serviceaccount-token` controller as a start.
Fixes #655 
```release-note
NONE
```
> Add documents about controllers inherited from kubernetes.

- hack/local-up-karmada.sh
/kind bug
If you do not install docker, you must execute it later to report an error，But before the error was reported, kind was already trying to use docker to create a cluster.
like:
$./hack/local-up-karmada.sh
Creating cluster karmada-host
Creating cluster member1
Creating cluster member2
Creating cluster member3
make: 进入目录“/root/karmada”
VERSION=latest hack/docker.sh karmada-aggregated-apiserver
hack/docker.sh:行15: docker: 未找到命令
make: *** [image-karmada-aggregated-apiserver] 错误 127
I think a detection of whether docker is installed should be added in font
> [fix] Add docker existence check

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/controllers/context/context.go
disable hpa controller by default
Fixes #1569 
```release-note
`karmada-controller-manager`: The `hpa` controller is disabled by default now.
```
> disable `hpa` controller by default

- artifacts/agent/karmada-agent.yaml
- hack/deploy-karmada-agent.sh
- pkg/karmadactl/get.go
/kind feature
Implement `karmadactl get` to support pull mode cluster through aggregated-apiserver.
Fixes #1091
```release-note
Implement `karmadactl get` to support pull mode cluster
```
> Implement `karmadactl get` to support pull mode cluster

- cluster/images/karmada-agent/Dockerfile
- cluster/images/karmada-aggregated-apiserver/Dockerfile
- cluster/images/karmada-controller-manager/Dockerfile
- cluster/images/karmada-interpreter-webhook-example/Dockerfile
- cluster/images/karmada-scheduler-estimator/Dockerfile
- cluster/images/karmada-scheduler/Dockerfile
- cluster/images/karmada-webhook/Dockerfile
- hack/local-up-karmada.sh
Cherry pick of #1519 on release-1.0.
#1519: bump alpine base image from v3.7 tov3.15.1
```release-note
The base image `alpine` has been promoted to `v3.15.1`.
```
> Automated cherry pick of #1519: bump alpine base image from v3.7 tov3.15.1

- pkg/scheduler/framework/plugins/registry.go
- pkg/scheduler/framework/plugins/spreadconstraint/spreadconstraint.go
- pkg/scheduler/scheduler.go
/kind feature
add one filter plugin to filter cluster that Provider/Zone/Region Property is not in the Cluster
a part of https://github.com/karmada-io/karmada/issues/1330
```release-note
```
> add filter plugin ClusterProperty to filter cluster

- docs/userguide/customizing-resource-interpreter.md
- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
/kind feature
add aggregateStatusInterpreter for daemonSet and statefulSet， so we can get status of ds and sts from controller plane.
Fixes #1544 
```
`karmada-controller-manager`: Added default `AggregateStatus` webhook for `DaemonSet` and `StatefulSet`.
```
> enable aggregateStatusInterpreter for daemonSet and statefulSet

- pkg/karmadactl/get.go
/kind bug
Fix
```
[root@master67 karmada]# ./karmadactl get deploy nginx -C member1 -o yaml
metadata:
annotations:
......
observedGeneration: 1
readyReplicas: 1
replicas: 1
updatedReplicas: 1
Error: cluster(member1): %!s(<nil>)
```
Fixes #
Found an oversight.
```release-note
NONE
```
> Fix `karmadactl get -o yaml|json` reporting null error

- pkg/resourceinterpreter/customizedinterpreter/customized.go
- pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
Cherry pick of #1584 on release-1.1.
#1584: fix: bugfix response's patch and patchType is nil, controller
```
`karmada-controller-manager`: Fixed panic in case of interpreter webhook returns nil patch.
```
> Automated cherry pick of #1584: fix: bugfix response's patch and patchType is nil, controller

- test/e2e/aggregatedapi_test.go
- test/e2e/clusterpropagationpolicy_test.go
- test/e2e/dependenciesdistributor_test.go
- test/e2e/failover_test.go
- test/e2e/federatedresourcequota_test.go
- test/e2e/fieldselector_test.go
- test/e2e/mcs_test.go
- test/e2e/namespace_test.go
- test/e2e/overridepolicy_test.go
- test/e2e/porting_workloads_test.go
- test/e2e/propagationpolicy_test.go
- test/e2e/rescheduling_test.go
- test/e2e/resource_test.go
- test/e2e/resourceinterpreter_test.go
- test/e2e/scheduling_test.go
- test/e2e/tainttoleration_test.go
- test/e2e/unjoin_test.go
- test/helper/resource.go
/kind cleanup
Follow the Ginkgo rule [`Declare in container nodes, initialize in setup nodes`](https://onsi.github.io/ginkgo/#extracting-common-setup-beforeeach), so I move the initialize code into `setup nodes`.
Fixes #
```release-note
NONE
```
> [E2E] Declare in container nodes, initialize in setup nodes

- docs/installation/installation.md
- pkg/karmadactl/cmdinit/utils/examples.go
/kind bug
After Karmada installed. The show example has a error. In 'Pull' mode example step 2 create a karmada-system namespace. In step 3 use `kubectl create -f karmada-agent.yaml` create agent will generate an error that the karmada-system already exist.In step 3 should use this command  `kubectl create -f karmada-agent.yaml` create agent.
Fixes #
```release-note
`karmadactl: fixed the `karmada-system` namespace already existing issue when deploying `karmada-agent` issue.
```
> fix pull mode example bug

- .gitignore
Add OSX trash to gitignore file
There will be .DS_Store file produced in the karmada project that should be ignored when work on macos  
```release-note
NONE
```
> add OSX trash to gitignore

- docs/installation/installation.md
- pkg/karmadactl/cmdinit/utils/examples.go
Cherry pick of #1604 on release-1.1.
#1604: fix pull mode example error
```release-note
`karmadactl: fixed the `karmada-system` namespace already existing issue when deploying `karmada-agent` issue.
```
> Automated cherry pick of #1604: fix pull mode example error

- charts/README.md
- charts/templates/post-delete-job.yaml
- charts/values.yaml
/kind bug
Remove remaining resource (configmaps、secret) when using helm uninstall，but it seems hard to remove resources like sa、clusterrole according to helm cause helm cannot gc those resource in pre/post job.
Fixes #1587 
None
> Remove remaining resource when using helm uninstall

- test/e2e/aggregatedapi_test.go
- test/e2e/clusterpropagationpolicy_test.go
- test/e2e/dependenciesdistributor_test.go
- test/e2e/failover_test.go
- test/e2e/fieldselector_test.go
- test/e2e/mcs_test.go
- test/e2e/overridepolicy_test.go
- test/e2e/porting_workloads_test.go
- test/e2e/propagationpolicy_test.go
- test/e2e/rescheduling_test.go
- test/e2e/resource_test.go
- test/e2e/resourceinterpreter_test.go
- test/e2e/scheduling_test.go
- test/e2e/tainttoleration_test.go
- test/e2e/unjoin_test.go
- test/helper/resource.go
/kind cleanup
Move cleanup to ginkgo setup node, and try to make each ginkgo spec independent of each other. Prepare for parallel E2E running.
Fixes #
```release-note
NONE
```
> [E2E] move cleanup to ginkgo setup node

- hack/run-e2e.sh
- test/e2e/failover_test.go
- test/e2e/federatedresourcequota_test.go
- test/e2e/framework/ginkgo_decorator.go
- test/e2e/mcs_test.go
- test/e2e/namespace_test.go
- test/e2e/rescheduling_test.go
- test/e2e/resourceinterpreter_test.go
- test/e2e/suite.go
- test/e2e/suite_test.go
- test/e2e/tainttoleration_test.go
- test/e2e/unjoin_test.go
/kind cleanup
Set e2e to run in parallel. Speed up e2e running.
Fixes #
Use ginkgo `--randomize-all` to randomize all specs together, 
Use ginkgo `-p` flags to run in parallel.
```release-note
NONE
```
> [E2E] Set e2e to run in parallel

- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/core/spreadconstraint/group_clusters.go
- pkg/scheduler/core/spreadconstraint/select_clusters.go
- pkg/scheduler/core/spreadconstraint/select_clusters_by_cluster.go
- pkg/scheduler/core/spreadconstraint/select_clusters_test.go
- pkg/scheduler/core/spreadconstraint/util.go
/kind feature
consider available resources when selecting clusters.
when spread constraint is setted, the available resources may be insufficient for workload currently.
For example
cluster constraint minGroup=maxGroup=2   needReplicas = 80，
the cluster information is following as
|clusterName|member1|member2|member3|
|-----|----|-----|-----|
| score| 60 | 50| 40|
| AvailableReplicas| 40 | 30|60
Although member1 and member2 have higher scores，the sum of AvailableReplicas is less than needReplicas，
so the result is member1 and member3
a part of https://github.com/karmada-io/karmada/issues/1330
**Does this PR …
> [optimize]Consider available resources when selecting clusters

- cmd/aggregated-apiserver/app/options/options.go
- pkg/registry/cluster/storage/storage.go
- pkg/util/lifted/requestinfo.go
/kind bug
The current `karmada-aggregated-apiserver` cannot identify requests with `watch` or `follow` URL RawQuery as `LongRunningRequestCheck`:
https://github.com/kubernetes/apiserver/blob/ac613d389acee636c827a241b1eba448e6b15f3a/pkg/server/config.go#L371
So, the default request timeout is 60 seconds:
https://github.com/kubernetes/apiserver/blob/ac613d389acee636c827a241b1eba448e6b15f3a/pkg/server/config.go#L347
Therefore, the `LongRunningFunc` method needs to be customized.
Part of #1618 
```release-note
Fix timeout when request of `-w` or `logs -f` …
```
> [AA] fix timeout when request of `-w` or `logs -f` flags with cluster/proxy

- cmd/aggregated-apiserver/app/options/options.go
- pkg/registry/cluster/storage/storage.go
- pkg/util/lifted/requestinfo.go
Cherry pick of #1620 on release-1.1.
#1620: fix timeout when request of -w or logs -f with cluster/proxy
```release-note
`karmada-aggregate-apiserver`: Fixed timeout issue when request `cluster/proxy` with options `-w` or `logs -f` from `karmadactl get`.
```
> Automated cherry pick of #1620: fix timeout when request of -w or logs -f with cluster/proxy

- pkg/registry/cluster/storage/proxy.go
Signed-off-by: pangshaoqiang <pangsq9413@gmail.com>
/kind bug
`location` is used when the proxy dial on the upstream server for upgrade requests. Without the query params 
in`RawQuery`, `exec` request will be rejected by the upstream apiserver. 
Fixes https://github.com/karmada-io/karmada/issues/1618
```release-note
`karmada-aggregate-apiserver`: Fixed exec failed: `error: unable to upgrade connection: you must specify at least 1 of stdin, stdout, stderr`
```
> Fix pod exec through cluster/proxy

- pkg/registry/cluster/storage/proxy.go
Cherry pick of #1632 on release-1.1.
#1632: Fix pod exec through cluster/proxy
```release-note
`karmada-aggregate-apiserver`: Fixed exec failed: `error: unable to upgrade connection: you must specify at least 1 of stdin, stdout, stderr`
```
> Automated cherry pick of #1632: Fix pod exec through cluster/proxy

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/status/workstatus_controller.go
- pkg/resourceinterpreter/customizedinterpreter/customized.go
- pkg/resourceinterpreter/customizedinterpreter/webhook/resourceinterpretercontext.go
- pkg/resourceinterpreter/defaultinterpreter/default.go
- pkg/resourceinterpreter/defaultinterpreter/default_test.go
- pkg/resourceinterpreter/defaultinterpreter/reflectstatus.go
- pkg/resourceinterpreter/defaultinterpreter/reflectstatus_test.go
- pkg/resourceinterpreter/interpreter.go
- pkg/util/helper/unstructured.go
- pkg/util/helper/workstatus.go
/kind feature
Add ReflectStatus ResourceInterperter interface to grab workload status, so as to support granularity control of workload status collection.
Fixes #
The default implementation of some resources kind(such as `deployment`) is not added. 
Add default reflectstatus implementation with:
- Deployment kind
- Service kind
- Ingress kind
- Job kind
- DaemonSet kind
- StatefulSet kind
```release-note
Supports granularity control of workload status collection with InterpretStatus InterpreterOperation.
```
> Add ReflectStatus ResourceInterperter interface to grab workload status

- .github/workflows/dockerhub-released-image.yml
- Makefile
Cherry pick of #1649 on release-1.1.
#1649: Support multiple arch: amd64, arm64.
```release-note
Fixed image does not support for Arm platform issue.
```
> Automated cherry pick of #1649: Support multiple arch: amd64, arm64.

- charts/templates/_karmada_webhook_configuration.tpl
I don't think the 'karmada-system' namespace should be hard-coded in the helm chart
/kind cleanup
> remove karmada-system in chart

- pkg/printers/internalversion/printers.go
- pkg/printers/internalversion/printers_test.go
Improved the output of `kubectl get cluster -o wide`, add  ApiEndpoint field to `-o wide`
When the number of clusters is large, we need `-o wide` to identify the cluster, as `-o yaml` displays long information,make users hard to  recognize the cluster
```release-note
NONE
```
> improved the output of 'kubectl get cluster -o wide'

- .github/workflows/dockerhub-latest-image.yml
- .github/workflows/dockerhub-released-image.yml
/kind bug
drop unnecessary ci job for docker hub image building.
Fixes #1680
```release-note
NONE
```
> remove arch for dockerhub image ci

- pkg/karmadactl/cmdinit/kubernetes/deployments.go
/kind bug
The default namespace of karmada-controller-manager is `karmada-system`. Installing karmada in a namespace other than `karmada-system` will cause karmada-controller-manager to fail to elect a leader.
Fixes #
```release-note
`karmadactl: Fixed karmada-controller-manager args not honor customized namespace issue.`
```
> Fix karmadactl init  karmada-controller-manager leader elect failure

- .github/workflows/dockerhub-released-image.yml
Cherry pick of #1681 on release-1.0.
#1681: remove arch for dockerhub image ci
```release-note
```
> Automated cherry pick of #1681: remove arch for dockerhub image ci

- pkg/karmadactl/cmdinit/kubernetes/deployments.go
Cherry pick of #1683 on release-1.1.
#1683: add `leader-elect-resource-namespace` flags
```release-note
`karmadactl: Fixed karmada-controller-manager args not honor customized namespace issue.`
```
> Automated cherry pick of #1683: add `leader-elect-resource-namespace` flags

- pkg/karmadactl/cmdinit/cmdinit.go
/kind cleanup
https://github.com/karmada-io/karmada/pull/1519: bump alpine base image from v3.14.3 tov3.15.1
Fixes #
```release-note
NONE
```
> bump  default alpine image of karmadactl init from v3.14.3 to v3.15.1

- pkg/karmadactl/cmdinit/options/global.go
/kind cleanup
update UserName of kubeconfig with clusterNmae perfix
Fixes #1700
```release-note
NONE
```
> update UserName of kubeconfig with clusterNmae perfix

- examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml
- examples/customresourceinterpreter/webhook-configuration.yaml
- hack/deploy-karmada.sh
- hack/post-run-e2e.sh
- hack/pre-run-e2e.sh
/kind cleanup
Install the [metallb](https://github.com/metallb/metallb) when we run with `hack/pre-run-e2e.sh`. As a result we can create a `LoadBalancer` type service for `karmada-interpreter-webhook-example`, in this way, in a CI test environment built with Kind, the service can be accessed directly from the member cluster.
Fixes #
```release-note
NONE
```
> Creating Loadbalancer Type Service by Installing the Metallb

- pkg/controllers/mcs/service_export_controller.go
- pkg/util/helper/workstatus.go
/kind cleanup
The `ServiceExport` resource does not have the status filed. Therefore, the work status of the ServiceExport type should not be collected during work status collection. In this case, the information in work status is not suitable to determine whether the work contains ServiceExport.
So I change to use `.spec.workload.manifests` to judge whether the work contains `ServiceExport`.
Fixes #
```release-note
NONE
```
> Update judge work contains serviceExport with .spec.workload.manifests

- hack/verify-codegen.sh
- hack/verify-crdgen.sh
/kind cleanup
As discussed in https://github.com/karmada-io/karmada/pull/1713#pullrequestreview-960438916, we need to add verify `crdgen` and `codegen` for `examples/customresourceinterpreter/apis` directory.
Fixes #
```release-note
NONE
```
> verify crdgen and codegen for examples directory

- charts/_crds/bases/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
- charts/_crds/bases/networking.karmada.io_multiclusteringresses.yaml
- charts/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
- charts/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
- charts/_crds/bases/policy.karmada.io_federatedresourcequotas.yaml
- charts/_crds/bases/policy.karmada.io_overridepolicies.yaml
- charts/_crds/bases/policy.karmada.io_propagationpolicies.yaml
- charts/_crds/bases/search.karmada.io_resourceregistries.yaml
- charts/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
- charts/_crds/bases/work.karmada.io_resourcebindings.yaml
- charts/_crds/bases/work.karmada.io_works.yaml
- examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
- hack/update-crdgen.sh
/kind cleanup
[controller-tools@v0.8.0] is built with Kubernetes@v1.23, which is consistent with Karmada dependencies.
Fixes #
/hold
wait for #1674
```release-note
NONE
```
> Bump controller-tools to v0.8.0

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/utils/kubeclient.go
/kind feature
Fixes #1744 
```release-note
`karmadactl`: Introduced `--context` flag to specify the context name to use.
```
> Add --context for karmadactl init

- pkg/controllers/status/workstatus_controller.go
/kind cleanup
For resources that do not have status(such as Secret, Configmap, etc), we can do not collect resource status in `Work` object to avoid unnecessary work status updates.
Fixes #
```release-note
NONE
```
> Skip reflect work status when resource has empty status

- pkg/karmadactl/promote.go
…d overwrite annotation
/kind bug
Partof #1758
```release-note
`karmadactl: fixed a panic which due to nil annotation during promote resources to Karmada.`
```
> fixed a panic which due to nil annotation during promote resources to Karmada

- pkg/karmadactl/promote.go
/kind bug
Fixes #1758
```release-note
`karmadactl`: Fixed `promote` command can not migrate cluster-scoped resource issue. 
```
> fixed a bug where not-namespaced resource could not be promoted

- docs/userguide/configure-controllers.md
- pkg/controllers/context/context_test.go
/kind bug
add ut for IsControllerEnabled, and updated the configure-controllers.md to avoid users misconfiguring the disable controller
Fixes #1780 
```release-note
NONE
```
> add ut for IsControllerEnabled and update configure-controllers.md

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deployments.go
- pkg/karmadactl/cmdinit/kubernetes/statefulset.go
/kind feature
support kube-image-mirror-country and kube-image-registry
Fixes #
https://github.com/karmada-io/karmada/issues/1753
```release-note
NONE
```
> feature_1753:support kube-image-mirror-country and kube-image-registry

- test/e2e/suite_test.go
/kind cleanup
When I run e2e test locally , I always failed  because out of time 
before :
We should set the config polltimeout  flexible
After 
Fixes #
```release-note
NONE
```
> Set timeout configs flexible when run e2e before

- pkg/karmadactl/get.go
- pkg/karmadactl/promote.go
/kind feature
Enable `karmadactl promote` command to support AA, not to directly use `secret`. Meanwhile, retain `--cluster-kubeconfig` and `--cluster-context` to allow users to use this command when AA is not enabled.
Fixes #1695 
```release-note
Enable `karmadactl promote` command to support AA
```
> Enable `karmadactl promote` command to support AA

- .gitignore
/kind cleanup
As #1740 move generated binary to _output directory, the karmada binary statement in `.gitignore` is no longer useful.
Fixes #
```release-note
NONE
```
> Remove karmada binary in .gitignore

- docs/userguide/aggregated-api-endpoint.md
Network plug-ins need to be deployed only if the network is one-way.
The reason for using PULL mode may also be to relieve pressure on the Karmada control plane, not necessarily because of network failure, so it should be described more accurately.
Fixes #
/cc @XiShanYongYe-Chang 
```release-note
NONE
```
> Update notes for Pull mode cluster in AA document

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/apis/cluster/v1alpha1/well_known_taints.go
- pkg/controllers/cluster/cluster_controller.go
- pkg/controllers/context/context.go
- pkg/controllers/unifiedauth/ensure_impersonation_secret.go
- pkg/util/cluster.go
- pkg/util/helper/taint.go
- pkg/util/helper/taint_test.go
- pkg/util/lifted/validateclustertaints.go
- vendor/modules.txt
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
- vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
/kind feature
Add taints for the clusters which are unhealthy for a period of time.
Fixes part of #1762 
```release-note
`karmada-controller-manager`: Introduced `--failover-eviction-timeout` to specify the grace period of eviction. Tants(`cluster.karmada.io/not-ready` or `cluster.karmada.io/unreachable`) will be set on unhealthy Cluster clusters after the period.
```
> enhance cluster lifecycle management: add taints for the clusters which are unhealthy for a period of time

- pkg/util/helper/policy.go
/kind flake
optimize the validating webhook for spreadconstraint
cluster constraint must be configured when the field spreadConstraints is set
Fixes #
NONE
```release-note
```
> optimize the validating webhook for spreadconstraint

- pkg/util/helper/workstatus.go
fix when the type of svc is nodeport. resourcebindings FULLYAPPLIED field is False
/kind bug
Fixes #1797 
```release-note
NONE
```
> fix when the type of svc is nodeport. resourcebindings FULLYAPPLIED field is False

- pkg/karmadactl/deinit.go
- pkg/karmadactl/karmadactl.go
/kind feature
remove karmada on kubernetes. 
Fixes #1296
Just delete karmada, will not delete the resources of karmada members.
```
root@dev-k8s-master01:~# ./kubectl-karmada deinit -h
remove karmada on kubernetes
Usage:
karmada deinit [flags]
Examples:
kubectl karmada deinit
kubectl karmada deinit --force
kubectl karmada deinit --recursive
Flags:
-f, --force                 skip delete confirmation
-h, --help                  help for deinit
-d, --karmada-data string   karmada data path. kubeconfig cert and crds files (default "/etc/karmada")
-n, --namespace string      Kubernetes namespace (default …
```
> karmadactl add deinit subcommand

- pkg/karmadactl/taint.go
/kind bug
fix karmadactl taint failed
Fixes https://github.com/karmada-io/karmada/issues/1823
```release-note
`karmadactl`: fixed karmadactl can not taint while karmada control plane config is not located on default path
```
> fix karmadactl taint failed

- hack/undeploy-karmada-agent.sh
/kind feature
The script makes it easy to undeploy karmada agent from a member cluster. Of course, this only applies to member clusters that are joined with `hack/deploy-karmada-agent` script.
Fixes #
```release-note
Add script `hack/undeploy-karmada-agent.sh`
```
> Add a script to undeploy karmada agent from a member cluster

- pkg/karmadactl/taint.go
Cherry pick of #1825 on release-1.0.
#1825: fix karmadactl taint failed
```release-note
`karmadactl`: fixed karmadactl can not taint while karmada control plane config is not located on default path
```
> Automated cherry pick of #1825: fix karmadactl taint failed

- .github/workflows/release.yml
- Makefile
- hack/release.sh
/kind flake
Implement for https://github.com/karmada-io/karmada/pull/1814#issuecomment-1131870145
Fixes #
After run `make release`, tars are created in `_output/release` with sha256 checksum.
```
$ ls _output/release/
karmadactl-darwin-amd64.tgz         karmadactl-linux-amd64.tgz         kubectl-karmada-darwin-amd64.tgz         kubectl-karmada-linux-amd64.tgz
karmadactl-darwin-amd64.tgz.sha256  karmadactl-linux-amd64.tgz.sha256  kubectl-karmada-darwin-amd64.tgz.sha256  kubectl-karmada-linux-amd64.tgz.sha256
karmadactl-darwin-arm64.tgz         karmadactl-linux-arm64.tgz …
```
> [refactor] add release to Makefile

- pkg/karmadactl/cmdinit/utils/examples.go
Signed-off-by: bruce <zhangyongxi_yewu@cmss.chinamobile.com>
/kind bug
when I Register cluster with 'Pull' mode，I find that an Error that "error building kubeconfig of karmada control plane: context "karmada" does not exist" in the log of karmada-agent pod, and the karmada-agent pod is CrashLoopBackOff. The reason is that the arg "karmada-context" of karmada-agent is hardcoded as a wrong value "karmada".
Fixes #
```release-note
NONE
```
> karmada agent can't find context of karmada-apiserver.config

- cmd/aggregated-apiserver/app/options/options.go
/kind feature
/kind cleanup
`karmada-aggregated-apiserver`: The deprecated flags `--karmada-config` and `--master` in v1.1 have been removed from the codebase.
Fixes #
```release-note
`karmada-aggregated-apiserver`: The deprecated flags `--karmada-config` and `--master` in v1.1 have been removed from the codebase.
```
> remove deprecated flags for karmada-aggregated-apiserver

- cmd/karmada-search/app/options/options.go
- pkg/registry/search/storage/cache.go
- pkg/registry/search/storage/opensearch.go
- pkg/registry/search/storage/requestinfo.go
- pkg/registry/search/storage/search.go
- pkg/search/apiserver.go
/kind feature
Support `karmada-search` component search interface.
Part of #1794
The k/v `cluster.karmada.io/name` is added to the response resource's annotation to indicate that which cluster it comes from.
What are the suggestions for naming this keyword?
```release-note
Support karmada-search component search interface.
```
**How to use it**:
- Create a `ResourceRegistry` cr:
```yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
name: test
spec:
targetCluster:
clusterNames:
- member1 …
```
> Support karmada-search component search interface

- test/e2e/framework/deployment.go
- test/e2e/framework/job.go
- test/e2e/framework/namespace.go
- test/e2e/framework/pod.go
- test/e2e/framework/resourcequota.go
- test/e2e/framework/secret.go
- test/e2e/framework/service.go
- test/e2e/framework/workload.go
- test/e2e/resource_test.go
/kind flake
/kind cleanup
Add more detailed error info to help us determine whether the abnormal running of the `clusterClient` when wait resource exist on the member clusters.
Part of #1841 
```release-note
NONE
```
> [E2E] log more err info when wait resource exist on member clusters

- pkg/controllers/execution/execution_controller.go
- pkg/controllers/mcs/endpointslice_controller.go
- pkg/controllers/mcs/service_export_controller.go
- pkg/controllers/status/cluster_status_controller.go
- pkg/controllers/status/workstatus_controller.go
- pkg/controllers/unifiedauth/unified_auth_controller.go
/kind bug
Some controller uses `SetupWithManager` with event handlers. However, this handler takes effect in global, i.e., other watched kinds will also be filtered by this global handler. This is not a correct usage because in most cases we only want to filter objects in `For` function (Please see [here](https://github.com/karmada-io/karmada/blob/master/vendor/sigs.k8s.io/controller-runtime/pkg/builder/controller.go#L136-L144)). So these predicated functions should be moved into `ForOption`.
Fixes #
```release-note
NONE
```
> fix implicit issue for event filter

- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/scheduler.go
- pkg/scheduler/core/division_algorithm.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/core/util.go
- pkg/scheduler/core/util_test.go
- pkg/scheduler/scheduler.go
Signed-off-by: charlesQQ <charles_ali@qq.com>
/kind feature
allow propagate workload to cluster but replicas is zero; if don't want to do that, cluster should not exist in PP spec.clusterAffinity.clusterNames field
Fixes #1573
```
rb's spec.clusters have cluster that replicas is zero
scheduler  add a  new command line  option  enable-propagate-empty-workLoad
```
> feat: allow propagate workload to cluster but replicas is zero

- docs/working-with-flux.md
Signed-off-by: Mike Ng <ming@redhat.com>
- Enhance the Flux integration doc by fixing minor spelling and grammar mistakes.
- Remove references/links to maintenance mode only legacy Flux GitHub repos.
Fixes # NA
```release-note
NONE
```
> doc fix: update flux integration doc to remove legacy repos links and fix minor spelling and grammar mistakes.

- test/helper/resource.go
/kind flake
The [CI run failed](https://github.com/karmada-io/karmada/runs/6663713820?check_suite_focus=true) with E2E `JobStatus collection testing`, related `karmada-controller-manager` log info:
```log
2022-05-31T02:03:09.607149676Z stderr F I0531 02:03:09.606420       1 job.go:32] Grab job(karmadatest-682/job-mr4) status from cluster(member1), active: 1, succeeded 0, failed: 2
2022-05-31T02:03:09.607168476Z stderr F I0531 02:03:09.606492       1 job.go:32] Grab job(karmadatest-682/job-mr4) status from cluster(member2), active: 1, succeeded 0, failed: 2
2022-05-31T02:03:09.607194776Z stderr F I0531 02:03:09.606550       1 job.go:32] Grab job(karmadatest-682/job-mr4) …
```
> update perl image for latest image run err

- pkg/registry/search/storage/cache.go
/kind bug
In karmada search feature, fix panic when adding a new key in nil annotation.
Fixes #
```release-note
`karmada-search`: Fixed panic when the resource annotation is nil.
```
> fix add annotation when annotation is nil

- pkg/karmadactl/cmdinit/kubernetes/deploy.go
The etcd in `karmadactl init` looks like it's already using version 3.5.1-0 :https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/cmdinit/kubernetes/deploy.go#L45 .
Perhaps these two places should also be consistent.
/kind cleanup
> adjust etcd version

- cmd/karmada-search/app/options/options.go
- pkg/apis/search/scheme/register.go
- pkg/registry/search/storage/cache.go
- pkg/search/apiserver.go
/kind feature
Support to search resources with labels, such as:
```
kubectl get --raw /apis/search.karmada.io/v1alpha1/search/cache/apis/apps/v1/namespaces/default/deployments?labelSelector=app=nginx
kubectl get --raw /apis/search.karmada.io/v1alpha1/search/cache/apis/apps/v1/namespaces/default/deployments?labelSelector=app!=nginx
```
Fixes #
```release-note
Support to search resources with labels.
```
> Support to search resources with labels

- test/helper/resource.go
Cherry pick of #1926 on release-1.0.
#1926: update perl image for latest image run err
```release-note
NONE
```
> Automated cherry pick of #1926: update perl image for latest image run err

- artifacts/deploy/karmada-apiserver.yaml
- artifacts/deploy/karmada-etcd.yaml
- artifacts/deploy/kube-controller-manager.yaml
- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
/kind feature
Update default kube-apiserver from v1.21 to v1.22 
Fixes #1923
```release-note
Update default kube-apiserver from v1.21 to v1.22
```
> Update default kube-apiserver from v1.21 to v1.22

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/statefulset.go
/kind cleanup
when input wrong `etcd-storage-mode`  like `kubectl karmada init --etcd-storage-mode pvc`  karmada will fallback to `emptyDir`. This does not meet user expectation. May be throw a error to user is better.
```
Error: unsupported etcd-storage-mode pvc. See 'kubectl karmada init --help'
```
when input wrong `etcd-storage-mode`, `statefulset.go` will fallback to `emptyDir` in default branch
```
switch i.EtcdStorageMode {
case "PVC":
mode := corev1.PersistentVolumeFilesystem
persistentVolumeClaim := corev1.PersistentVolumeClaim{
TypeMeta: metav1.TypeMeta{
APIVersion: "v1",
Kind:       "PersistentVolumeClaim",
},
ObjectMeta: metav1.ObjectMeta{
Namespace: i.Namespace,
Name:      etcdContainerDataVolumeMountName, …
```
> when type wrong etcd-storage-mode throw error

- hack/local-up-karmada.sh
- hack/remote-up-karmada.sh
- hack/util.sh
/kind feature
when installing Karmada from source, sometimes, it's needed to do proxy setting in China mainland.
Fixes #
```release-note
`remote-up-karmada.sh`: Support doing proxy setting in China mainland when installing Karmada from source.
```
> do proxy setting in China mainland when installing Karmada from source

- api/openapi-spec/swagger.json
- pkg/apis/cluster/types.go
- pkg/apis/cluster/v1alpha1/types.go
- pkg/apis/cluster/v1alpha1/zz_generated.conversion.go
- pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
- pkg/apis/cluster/zz_generated.deepcopy.go
- pkg/generated/openapi/zz_generated.openapi.go
As described in https://github.com/karmada-io/karmada/issues/257, some member clusters are behind a proxy. And some proxies will request clients to provide necessary headers during a CONNECT request, like authorization information.
NONE
none
```release-note
`Cluster API`: Added `ProxyHeader` optional field to specify the HTTP header required by the proxy server.
```
> add ProxyHeader API

- pkg/search/backendstore/defaultstore.go
Co-authored-by: liys87x <liyasong1987x@gmail.com>
Signed-off-by: huntsman_ly <huntsman_ly@sina.com>
/kind bug
Since `SingleClusterInformerManager.ForResource` uses `==` to determine whether the handler exists, `backendstore.Default` need to return a comparable `cache.ResourceEventHandler`.
Fixes #1952  
```release-note
`karmada-search`: Fixed a panic issue `comparing uncomparable type cache.ResourceEventHandlerFuncs`.
```
> fix(karmada-search): uncomparable `cache.ResourceEventHandler`

- pkg/search/backendstore/defaultstore.go
Cherry pick of #1951 on release-1.2.
#1951: fix(karmada-search): uncomparable
```release-note
`karmada-search`: Fixed a panic issue `comparing uncomparable type cache.ResourceEventHandlerFuncs`.
```
> Automated cherry pick of #1951: fix(karmada-search): uncomparable

- pkg/karmadactl/promote.go
- pkg/util/names/names.go
- test/e2e/karmadactl_test.go
/kind bug
Fix promoting failed if a resource with other kind used same name has promoted before
Fixes https://github.com/karmada-io/karmada/issues/1821
```release-note
`karmadactl`: fixed karmadactl promoting failed if a resource with other kind used same name has promoted before
```
> Fix promoting failed if a resource with other kind used same name has promoted before

- pkg/controllers/mcs/service_import_controller.go
/kind bug
When ServiceImportType is Headless, it should be ignored
Refer to [shouldIgnoreImport](https://github.com/kubernetes-sigs/mcs-api/blob/e851d9e462/pkg/controllers/serviceimport.go#L76)
Fixes #
```release-note
NONE
```
> When ServiceImportType is Headless, it should be ignored

- pkg/apis/work/v1alpha2/well_known_labels.go
- pkg/controllers/execution/execution_controller.go
- pkg/util/helper/work.go
- pkg/util/helper/work_test.go
/kind feature
add syncEvent from execution_controller to resource.
For example if we describe deployment we can see event from execution-controller
```
...
Events:
Type     Reason                  Age                 From                  Message
----     ------                  ----                ----                  -------
Warning  ApplyPolicyFailed       22s                 resource-detector     No policy match for resource
Normal   ApplyPolicySucceed      22s (x3 over 22s)   resource-detector     Apply policy(default/nginx-propagation) succeed
Normal   SyncWorkSucceed         22s (x9 over 22s)   binding-controller    Sync work of …
```
> add syncEvent from execution_controller to resource

- pkg/apis/cluster/v1alpha1/well_known_constants.go
- pkg/registry/search/storage/cache.go
- pkg/search/backendstore/opensearch.go
/kind cleanup
Minor modification for code specification.
Fixes #
I've been learning karmada's code, please correct me if not.
```release-note
`karmada-search`: The annotation `cluster.karmada.io/name` which is used to represent the source of cache now has been changed to `resource.karmada.io/cached-from-cluster`.
```
> rename cache resource annotation

- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/scheduler.go
- pkg/scheduler/scheduler.go
/kind feature
Fixes https://github.com/karmada-io/karmada/issues/1371
Now we can initialize OutOfTree Plugin like below, then we can compile  customized karmada scheduler.
```
command := app.NewSchedulerCommand(stopChan,
app.WithPlugin(apiinstalled.Name, apiinstalled.New),
)
```
```release-note
None
```
> feat: add outOfTree plugin entry when initializing scheduler

- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
- pkg/resourceinterpreter/interpreter.go
- pkg/util/helper/job.go
- test/e2e/resource_test.go
/kind bug
When a job is propagated but the status has not been collected, resource interpreter may reflect job status as `Completed`, so we should not reflect status in this circumstance. 
Fixes #
```release-note
`karmada-controller-manager`: Fixed `Job` status might be incorrectly marked as `Completed` issue.
```
> fix bugs of aggregating job status

- docs/userguide/customizing-resource-interpreter.md
- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
Signed-off-by: bruce <zhangyongxi_yewu@cmss.chinamobile.com>
/kind feature
When I try to propagate or promote a pod, I found that the status of pod is always pending and never changed. 
Fixes #1988
```release-note
`karmada-controller-manager`:  `interpreter framework` starts to support Pod status aggregation.  
```
> sync status of pod

- .github/workflows/lint-chart.yaml
- charts/karmada/Chart.yaml
- charts/karmada/values.yaml
/kind feature
use [CT](https://github.com/helm/chart-testing)  to validate  chart:
there are three phase:
* `ct changed`:  check the chart file change of chart on target branch
* `ct lint`: check the yaml file format of chart under charts directory
* `ct install`: install chart instant on a kind cluster
Fixes #
Please correct me if not.
```release-note
NONE
```
> add chart lint ci workflow

- charts/karmada/templates/karmada-agent.yaml
- charts/karmada/templates/karmada-controller-manager.yaml
- charts/karmada/templates/karmada-descheduler.yaml
- charts/karmada/templates/karmada-scheduler.yaml
/kind cleanup
Since we support installing Karmada via Helm with configurable namespace，when we use namespace which is not Karmada-system, we met errors below:
```
E0613 02:27:46.329703       1 leaderelection.go:334] error initially creating leader election record: namespaces "karmada-system" not found
E0613 02:27:49.110394       1 leaderelection.go:334] error initially creating leader election record: namespaces "karmada-system" not found
E0613 02:27:51.836602       1 leaderelection.go:334] error initially creating leader election record: namespaces "karmada-system" not found
E0613 02:27:54.912496       1 leaderelection.go:334] error initially creating leader election …
```
> Add leaderelection namespace for helm chart

- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
- pkg/resourceinterpreter/interpreter.go
- pkg/util/helper/job.go
- test/e2e/resource_test.go
Cherry pick of #1987 on release-1.2.
#1987: fix bugs of aggregating job status
```release-note
`karmada-controller-manager`: Fixed `Job` status might be incorrectly marked as `Completed` issue.
```
> Automated cherry pick of #1987: fix bugs of aggregating job status

- pkg/karmadactl/unjoin.go
Signed-off-by: bruce <zhangyongxi_yewu@cmss.chinamobile.com>
/kind flake
when unjoining a cluster with a non-existent clustername, there is no any output on the console. It's better to output a Error message, I think...
Fixes #
none
> add Error message when unjoining cluster with a non-existent clustername

- pkg/karmadactl/deinit.go
/kind cleanup
When deinit for karmada:`kubectl karmada deinit`, the output for yes or no is:
Mybe it shoud be:
> modify output for deinit

- pkg/clusterdiscovery/clusterapi/clusterapi.go
- pkg/karmadactl/cordon.go
- pkg/karmadactl/join.go
- pkg/karmadactl/options/global.go
- pkg/karmadactl/promote.go
- pkg/karmadactl/taint.go
- pkg/karmadactl/unjoin.go
- test/e2e/federatedresourcequota_test.go
- test/e2e/karmadactl_test.go
- test/e2e/namespace_test.go
- test/e2e/rescheduling_test.go
/kind bug
the `dry-run` flag is not supported by the all sub-commands of `karmadactl`. i.e. `describe`, `exec`, `log`.
```release-note
NONE
```
> remove dry-run from GlobalCommandOptions

- pkg/karmadactl/join.go
/kind feature
`kubectl-karmada` & `karmadactl`: Introduced `--cluster-zone` and `--cluster-region` flag to `join` command to specify zone and region of joining cluster. 
Fixes #
```release-note
`kubectl-karmada` & `karmadactl`: Introduced `--cluster-zone` and `--cluster-region` flag to `join` command to specify zone and region of joining cluster. 
```
> Manually specify the Zone and Region of the cluster

- pkg/clusterdiscovery/clusterapi/clusterapi.go
- pkg/karmadactl/cordon.go
- pkg/karmadactl/join.go
- pkg/karmadactl/options/global.go
- pkg/karmadactl/promote.go
- pkg/karmadactl/taint.go
- pkg/karmadactl/unjoin.go
- test/e2e/federatedresourcequota_test.go
- test/e2e/karmadactl_test.go
- test/e2e/namespace_test.go
- test/e2e/rescheduling_test.go
Cherry pick of #2023 on release-1.2.
#2023: remove dry-run from GlobalCommandOptions
```release-note
`karmadactl`: Removed `--dry-run` flag from `describe`, `exec` and `log` commands.
```
> Automated cherry pick of #2023: remove dry-run from GlobalCommandOptions

- pkg/controllers/cluster/cluster_controller.go
- pkg/controllers/status/cluster_status_controller.go
/kind cleanup
It's pointless to update lease for push mode clusters since the cluster status controller is at the control-plane
Meanwhile it's consuming goroutines
Fixes #
```release-note
`karmada-controller-manager`: Stopped reporting and refreshing `lease` for clusters with `Push` mode.
```
> Skip updating lease for push mode clusters

- hack/local-up-karmada.sh
- hack/util.sh
/kind feature
When users or e2e exec `local-up-karmada.sh` to install mutils-cluster karmada env.  We should ensure that the three member(member1,member2,member3) clusters have joined the karmada control cluster and there `condition` are all ready.
Fixes https://github.com/karmada-io/karmada/issues/2057
please correct me if not.
```release-note
NONE
```
> wait cluster status to be ready after exec local-up-karmada.sh

- pkg/util/objectwatcher/objectwatcher.go
/kind bug
When create failed we need to return error in `objectwatcher.go`.
Fixes #2072 
```release-note
bugfix: return err when create resource failed
```
> [bugfix]Return err when create resource failed

- .github/workflows/ci.yml
/kind feature
Support Kubernetes v1.24 in our CI E2E test.
Fixes #
```release-note
NONE
```
> [CI] support k8s v1.24 in ci test

- test/e2e/karmadactl_test.go
/kind bug
After #2023 is merged, the DryRun has been removed from `GlobalCommandOptions `
Fixes #
```release-note
NONE
```
> fix karmadactl e2e

- Makefile
Do not start new tests after the first test failure
Fixes # https://github.com/karmada-io/karmada/issues/2073
```release-note
```
> do not start new tests after the first test failure

- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/scheduler.go
- pkg/scheduler/scheduler.go
/kind bug
/kind feature
In pull mode, if the network of the member cluster and karmada are not two-way communication， `scheduler-estimator` is not available.，In this scenario, we need to add a flag to disable `scheduler-estimator` in pull mode.
For example, my cluster2 is in pull mode, and scheduler-estimator is not installed, the scheduler has been looking for karmada-scheduler-estimator-cluster2.
```
root@dev-karmada-cluster02:~# kubectl  --kubeconfig /etc/karmada/karmada-apiserver.config get cluster
NAME       VERSION   MODE   READY   AGE
cluster1   v1.23.8   Push   True    72m
cluster2   v1.22.0   Pull   True    69m
```
```
I0625 09:19:38.584300       1 cache.go:87] …
```
> karmada-scheduler add disable-scheduler-estimator-in-pull-mode flag 

- pkg/karmadactl/get_flags.go
/kind cleanup
ConfigFlags is used to build a kcmdutil.Factory for a karmada-apiserver and a member cluster, it won't be used as karmadactl flags. 
```release-note
NONE
```
> remove useless function in the get_flags.go file

- docs/userguide/customizing-resource-interpreter.md
- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
- pkg/util/helper/unstructured.go
/kind feature
PVC used frequently. I think that build-in interpreter aggregatestatus should contain PVC
Fixes #2065 
```release-note
`karmada-controller-manager`:  `interpreter framework` start to support PVC status aggregation.  
```
> sync status of pvc

- pkg/controllers/binding/common.go
/kind bug
label ` work.karmada.io/namespace` is used by `workstatus_controller::getClusterNameFromLabel` for aggregate workload status is possible to be overwritten by `overridepolicy`
here is the example
```
metadata:
name: nginx
labels:
app: nginx
spec:
replicas: 1
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- image: nginx
name: nginx
---
metadata:
spec:
name: nginx
placement:
clusterNames:
- suzhou-app1
``` …
> avoid required label override by overridepolicy

- Makefile
/kind cleanup
As mentioned by @ikaven1024 at https://github.com/karmada-io/karmada/pull/2082#issuecomment-1172850852,
The UT test is totally disabled now, revert the change to get it back.
Fixes #
```release-note
NONE
```
> Revert PR 2082

- pkg/karmadactl/deinit.go
/kind feature
`deinit` add param of `force`
Easy automation tool integration
Fixes #
```release-note
`karmadactl`: Added `--force` flag to `deinit` to skip confirmation.
```
> feature: `deinit` add param of `force`

- test/e2e/federatedresourcequota_test.go
- test/e2e/karmadactl_test.go
- test/e2e/namespace_test.go
/kind cleanup
Extend the waiting time for the CI cluster to unjoin.
Fixes #
We have encountered multiple instances of cluster unjoin waiting timeout, for example:
https://github.com/karmada-io/karmada/runs/7147675356?check_suite_focus=true
https://github.com/karmada-io/karmada/runs/7173520524?check_suite_focus=true
Detail error log:
```log
• [FAILED] [108.312 seconds]
Karmadactl cordon/uncordon testing [DeferCleanup][needCreateCluster]
/home/runner/work/karmada/karmada/test/e2e/karmadactl_test.go:480
cordon cluster
/home/runner/work/karmada/karmada/test/e2e/karmadactl_test.go:500
uncordon cluster …
```
> Extend the waiting time for CI cluster unjoin

- cmd/descheduler/app/descheduler.go
- cmd/scheduler-estimator/app/scheduler-estimator.go
- cmd/scheduler/app/scheduler.go
/kind cleanup
Now components such as Karmada-scheduler import net/http/pprof and use DefaultServeMux. It will lead to unable to control the switch of pprof. We should use custom mux instead of DefaultServeMux in order to disable pprof.
Fixes #
None
> Use custom mux instead of DefaultServeMux

- pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
Cherry pick of #2117 on release-1.2.
#2117: Fix nil problem in updateConfiguration
```release-note
`karmada-controller-manager`/`karmada-agent` : fixed panic issue when dumps error infos.
```
> Automated cherry pick of #2117: Fix nil problem in updateConfiguration

- charts/karmada/README.md
- charts/karmada/templates/_helpers.tpl
- charts/karmada/templates/etcd.yaml
- charts/karmada/templates/karmada-agent.yaml
- charts/karmada/templates/karmada-aggregated-apiserver.yaml
- charts/karmada/templates/karmada-apiserver.yaml
- charts/karmada/templates/karmada-controller-manager.yaml
- charts/karmada/templates/karmada-descheduler.yaml
- charts/karmada/templates/karmada-scheduler-estimator.yaml
- charts/karmada/templates/karmada-scheduler.yaml
- charts/karmada/templates/karmada-search.yaml
- charts/karmada/templates/karmada-webhook.yaml
- charts/karmada/templates/kube-controller-manager.yaml
- charts/karmada/templates/pre-install-job.yaml
- charts/karmada/values.yaml
/kind feature
If set global image registry, we yet need support global images pull recret.
Test:
Fixes #
Please correct me if not
```release-note
NONE
```
> chart: support global image pull secrets

- pkg/karmadactl/get.go
- pkg/karmadactl/join.go
- pkg/karmadactl/promote.go
- pkg/karmadactl/unjoin.go
/kind cleanup
The same parameter（--cluster-namespace） has different usage in different command execution, and the parameter usage in the join command is difficult to understand
Run `karmadactl join -h` to get the usage of --cluster-namespace
```
➜  karmada git:(master) go run cmd/karmadactl/karmadactl.go join -h
Flags:
--cluster-namespace string    Namespace in the control plane where member secrets cluster are stored. (default "karmada-cluster")
```
Run `karmadactl unjoin -h` to get the usage of --cluster-namespace
```
➜  karmada git:(master) go run cmd/karmadactl/karmadactl.go unjoin -h
Flags:
--cluster-namespace string    Namespace in the control plane where member cluster are stored. (default "karmada-cluster")
``` …
> karmadactl:modify the usage of cluster-namespace

- pkg/detector/detector.go
/kind cleanup
As [gvrDisabled](https://github.com/karmada-io/karmada/blob/61072d117c36cd25fc3777101abe669a34313f53/pkg/detector/detector.go#L169) has ignored the specified resource when building shared informer, so we need to add that checking in `EventFilter`.
Fixes #
```release-note
NONE
```
> Remove unused check in detector resource Eventifilter

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/aggregated-apiserver/app/options/options.go
- cmd/aggregated-apiserver/app/options/validation.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- cmd/descheduler/app/descheduler.go
- cmd/descheduler/app/options/options.go
- cmd/descheduler/app/options/validation_test.go
- cmd/karmada-search/app/options/options.go
- cmd/scheduler-estimator/app/options/options.go
- cmd/scheduler-estimator/app/options/validation_test.go
- cmd/scheduler-estimator/app/scheduler-estimator.go
- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/options/validation_test.go
- cmd/scheduler/app/scheduler.go
- cmd/webhook/app/options/options.go
- cmd/webhook/app/options/validation_test.go
- cmd/webhook/app/webhook.go
- pkg/sharedcli/profileflag/profileflag.go
/kind feature
Since we need to do some performance tests for karmada components, we found that there are still some components which do not support pprof.
Because each components have different implementing logic, some are based on genericAPIServer, some are base on controller-runtime(controller-runtime now do not support pprof https://github.com/kubernetes-sigs/controller-runtime/pull/1943). In this PR, we unify the config to enable pprof.
Fixes #
```Karmada-agent, Karmada-aggregated-apiserver, Karmada-controller-manager, Karmada-descheduler, Karmada-search, Karmada-scheduler, …
```
> Add pprof for karmada components

- test/e2e/karmadactl_test.go
/kind bug
Here `kubeClient` control `karmada control plane`, not to check deployment propagated to member cluster.
Fixes #
/cc @XiShanYongYe-Chang 
```release-note
NONE
```
> [E2E] Fix check whether deployment propagated to member cluster

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/deinit.go
/kind cleanup
Unify the style of command line descriptions:
```
(⎈ |karmada:kube-system)➜  karmada git:(fix-karmadactl) go run cmd/karmadactl/karmadactl.go
karmadactl controls a Kubernetes Cluster Federation.
Usage:
karmadactl [flags]
karmadactl [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
cordon      Mark cluster as unschedulable
deinit      removes Karmada from Kubernetes
describe    Show details of a specific resource or group of resources in a cluster
exec        Execute a command in a container in a cluster
get         Display one or many resources
help        Help about any command
init        install karmada in kubernetes.
join        Register a cluster to …
```
> improve karmadactl description

- pkg/karmadactl/promote.go
/kind cleanup
The short usage of cluster parameters lowercase in karmadactl promote different from other modules, all uppercase now
run `karmadactl promote -h`
```
➜  karmada git:(fix-option-lowercase) go run cmd/karmadactl/karmadactl.go promote -h
Promote resources from legacy clusters to karmada control plane. Requires the cluster be joined or registered.
Usage:
karmadactl promote <RESOURCE_TYPE> <RESOURCE_NAME> -n <NAME_SPACE> -C <CLUSTER_NAME> [flags]
Examples:
karmadactl promote deployment nginx -n default -C cluster1
karmadactl promote deployment.v1.apps nginx -n default -C cluster1
karmadactl promote deployment nginx -n default -C cluster1 -o yaml|json
karmadactl promote secret default-token -n default -C cluster1 …
```
> karmadactl:modify the cluster parameter from lowercase to uppercase

- test/e2e/karmadactl_test.go
Cherry pick of #2147 on release-1.2.
#2147: Fix check whether deployment propagated to member cluster
```release-note
NONE
```
> Automated cherry pick of #2147: Fix check whether deployment propagated to member cluster

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- pkg/karmadactl/join.go
- pkg/util/cluster.go
- pkg/util/cluster_test.go
- pkg/util/clusterrole.go
- pkg/util/credential.go
- pkg/util/credential_test.go
- pkg/util/secret.go
Signed-off-by: charlesQQ <charles_ali@qq.com>
/kind feature
Allowed karmada-agent  report secret for Pull mode cluster
Part of  https://github.com/karmada-io/karmada/issues/1946
```
`karmada-agent`: Introduced `--report-secrets` flag to allow secrets to be reported to the Karmada control plane during registering.
```
> feat: agent report secret

- pkg/karmadactl/get.go
- pkg/karmadactl/join.go
- pkg/karmadactl/options/global.go
- pkg/karmadactl/promote.go
- pkg/karmadactl/unjoin.go
/kind cleanup
This PR just fixed some misleading and/or outdated comments about `--cluster-namespace` flag.
Fixes #
Found this when I review the #1350.
```release-note
NONE
```
> Fixed misleading or outdate comments about --cluster-namespace flag

- go.mod
- pkg/karmadactl/describe.go
- pkg/karmadactl/exec.go
- pkg/karmadactl/get.go
- pkg/karmadactl/logs.go
- pkg/karmadactl/promote.go
- vendor/k8s.io/kubectl/pkg/cmd/apiresources/apiresources.go
- vendor/k8s.io/kubectl/pkg/cmd/apiresources/apiversions.go
- vendor/k8s.io/kubectl/pkg/cmd/exec/exec.go
- vendor/k8s.io/kubectl/pkg/util/completion/completion.go
- vendor/modules.txt
/kind feature
use `kubectl exec` to implement `karmadactl exec` in order to improve code reuse
```release-note
`karmadactl exec` support the `--namespace` flag
```
> use kubectl exec to implement karmadactl exec and introduce the `--namespace` flag

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- pkg/karmadactl/join.go
Signed-off-by: charlesQQ <charles_ali@qq.com>
/kind feature
karmada-agent add new flag for registering cluster 
Fixes #
```
`karmada-agent`: Introduced `--cluster-provider` and `--cluster-region` flags to specify cluster-provider and cluster-region during registering.
```
> feat: add cluster agent register flag

- pkg/karmadactl/get.go
/kind bug
When using karmadactl get to specify a clustername that does not exist in the kubeconfig file, an error is reported:
```shell
$ karmadactl --kubeconfig=/etc/karmada/karmada-apiserver.config get po -C local1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1951352]
goroutine 1 [running]:
github.com/karmada-io/karmada/pkg/karmadactl.(*CommandGetOptions).setClusterProxyInfo(0xc000521540, 0xc0000da900, {0xc0001335f0, 0x6}, 0x5)
/root/karmada/pkg/karmadactl/get.go:940 +0xd2
github.com/karmada-io/karmada/pkg/karmadactl.(*CommandGetOptions).Run(0xc000521540, {0x2092268, 0xc0001420b0}, 0xc0000ebc30, {0xc000642400, 0x1, 0x4}) …
```
> Fix karmadactl get -C error

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/promote.go
- pkg/karmadactl/taint.go
- pkg/version/sharedcommand/sharedcommand.go
/kind cleanup
Unify the style of command line descriptions
```
➜  ~ kubectl karmada -h     
karmadactl controls a Kubernetes Cluster Federation.
Usage:
karmadactl [flags]
karmadactl [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
cordon      Mark cluster as unschedulable
deinit      Removes Karmada from Kubernetes
describe    Show details of a specific resource or group of resources in a cluster
exec        Execute a command in a container in a cluster
get         Display one or many resources
help        Help about any command
init        Install karmada in kubernetes.
join        Register a cluster to control plane
logs        Print the logs for a container in a pod …
```
> improve karmadactl command line description

- go.mod
- pkg/karmadactl/apply.go
- pkg/karmadactl/karmadactl.go
- vendor/github.com/jonboulle/clockwork/.editorconfig
- vendor/github.com/jonboulle/clockwork/.gitignore
- vendor/github.com/jonboulle/clockwork/LICENSE
- vendor/github.com/jonboulle/clockwork/README.md
- vendor/github.com/jonboulle/clockwork/clockwork.go
- vendor/github.com/jonboulle/clockwork/ticker.go
- vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
- vendor/k8s.io/kubectl/pkg/cmd/apply/apply.go
- vendor/k8s.io/kubectl/pkg/cmd/apply/apply_edit_last_applied.go
- vendor/k8s.io/kubectl/pkg/cmd/apply/apply_set_last_applied.go
- vendor/k8s.io/kubectl/pkg/cmd/apply/apply_view_last_applied.go
- vendor/k8s.io/kubectl/pkg/cmd/apply/patcher.go
- vendor/k8s.io/kubectl/pkg/cmd/apply/prune.go
- vendor/k8s.io/kubectl/pkg/cmd/delete/delete.go
- vendor/k8s.io/kubectl/pkg/cmd/delete/delete_flags.go
- vendor/k8s.io/kubectl/pkg/cmd/util/editor/crlf/crlf.go
- vendor/k8s.io/kubectl/pkg/cmd/util/editor/editoptions.go
- vendor/k8s.io/kubectl/pkg/cmd/util/editor/editor.go
- vendor/k8s.io/kubectl/pkg/cmd/wait/wait.go
- vendor/k8s.io/kubectl/pkg/util/apply.go
- vendor/k8s.io/kubectl/pkg/util/pod_port.go
- vendor/k8s.io/kubectl/pkg/util/prune/prune.go
- vendor/k8s.io/kubectl/pkg/util/service_port.go
- vendor/k8s.io/kubectl/pkg/util/umask.go
- vendor/k8s.io/kubectl/pkg/util/umask_windows.go
- vendor/k8s.io/kubectl/pkg/util/util.go
- vendor/modules.txt
/kind feature
Some opensource products is deployed by a long-size yaml,such as calico https://docs.projectcalico.org/manifests/calico.yaml. this pr provide an easy way to deploy it to member cluster.
```sh
(⎈ |karmada:default)➜  karmada git:(karmadactl-apply) go run cmd/karmadactl/karmadactl.go apply -h
Apply a configuration to a resource by file name or stdin and propagate them into member clusters. The resource name must be specified. This resource will be created if it doesn't exist yet. To use 'apply', always create the resource initially with either 'apply' or 'create --save-config'.
JSON and YAML formats are accepted.
Alpha Disclaimer: the --prune functionality is not …
```
> karmadactl support apply command

- pkg/karmadactl/cmdinit/cmdinit.go
Signed-off-by: luomonkeyking <luomonkeyking@gmail.com>
/kind bug
Prevent data loss after etcd restart
Fixes #
Modify the default storage type of etcd to hostpath
I don't know if there is any omission, if there is any trouble, please correct me
NONE
> Modify the default storage type of etcd to hostPath

- pkg/karmadactl/describe.go
- pkg/karmadactl/exec.go
- pkg/karmadactl/get.go
/kind feature
```
(⎈ |karmada:default)➜  karmada git:(master) go run cmd/karmadactl/karmadactl.go describe -h
Show details of a specific resource or group of resources in a cluster
Usage:
karmadactl describe (-f FILENAME | TYPE [NAME_PREFIX | -l label] | TYPE/NAME) (-C CLUSTER)
Examples:
...
(⎈ |karmada:default)➜  karmada git:(remove-DisableFlagsInUseLine) go run cmd/karmadactl/karmadactl.go describe -h
Show details of a specific resource or group of resources in a cluster
Usage:
karmadactl describe (-f FILENAME | TYPE [NAME_PREFIX | -l label] | TYPE/NAME) (-C CLUSTER) [flags]
Examples:
...
```
```release-note
NONE
```
> enable addition of [flags] to the usage line 

- pkg/karmadactl/get.go
/kind bug
After #1478 is merged,  the `--cluster-namespace` flag should be removed.
```release-note
`karmadactl`: remove the `--cluster-namespace` flag for `get` command.
```
> remove unused flag for karmadactl get

- pkg/karmadactl/promote.go
- test/e2e/karmadactl_test.go
/kind bug
After #1795 is merged, the --cluster-namespace flag should be removed.
```release-note
`karmadactl`: removed the `--cluster-namespace` flag for `promote` command.
```
> remove unused flag for karmadactl promote

- pkg/util/secret.go
- pkg/util/serviceaccount.go
Cherry pick of #1972 on release-1.1.
#1972: auto create secret when sa not create
```release-note
karmadactl: support join kubernetes v1.24
```
> Automated cherry pick of #1972: auto create secret when sa not create

- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/apis/cluster/mutation/mutation.go
- pkg/controllers/cluster/cluster_controller.go
- pkg/controllers/cluster/common.go
- pkg/controllers/cluster/taint_manager.go
- pkg/controllers/context/context.go
- pkg/controllers/hpa/hpa_controller.go
- pkg/descheduler/core/filter.go
- pkg/registry/cluster/strategy.go
- pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
- pkg/util/binding.go
- pkg/util/binding_test.go
- pkg/util/helper/policy.go
- pkg/util/helper/taint.go
- pkg/util/worker.go
/kind feature
Add taint manager for NoExecute manager.
Fixes part of #1762
```release-note
`karmada-controller-manager`: Introduced `taint manager` to cluster controller to evict workloads from clusters with `no-execute` taint. 
```
> add NoExecute taint manager

- pkg/karmadactl/get.go
/kind cleanup
```release-note
NONE
```
> remove useless field from CommandGetOptions

- hack/util.sh
/kind bug
`git diff` does not normally reflect whether the current git repository has been modified, for example, adding a new file into repo.
FYI https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L61
```sh
(⎈ |ik8s01:karmada-system)➜  karmada git:(fix-hack-utils) make karmadactl
LDFLAGS='-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.2.0-310-g156e329f -X github.com/karmada-io/karmada/pkg/version.gitCommit=156e329f447bf60426b64c4a3441ff194319b288 -X github.com/karmada-io/karmada/pkg/version.gitTreeState=clean -X github.com/karmada-io/karmada/pkg/version.buildDate=2022-07-20T14:26:37Z' BUILD_PLATFORMS=darwin/arm64 hack/build.sh karmadactl …
```
> fix wrong GO_LDFLAGS when the git tree status is dirty

- cmd/agent/app/agent.go
- pkg/karmadactl/promote.go
- pkg/search/controller.go
/kind feature
As is talked in #2187，we add a new type cachedRESTMapper for performance improvement in controller-manager，we should apply it to other Karmada components.
Fixes #
/cc @yy158775 @RainbowMango
> Apply cachedRESTMapper for other Karmada components

- pkg/karmadactl/cmdinit/cmdinit.go
/kind bug
```shell
$ karmadactl version
karmadactl version: version.Info{GitVersion:"v1.2.0-311-gdb983ed", GitCommit:"db983ed7fc1244a5d20c17932663a86e866c65a6", GitTreeState:"clean", BuildDate:"2022-07-15T02:06:25Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```
The crds version example output is stable, Will not change with karmadactl version, maybe we can optimize this place
Fixes #
Test result:
```release-note
NONE
```
> fix karmada init help crd version

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/execution/execution_controller.go
/kind cleanup
Since `ClusterClientSetFunc` is no more used by execution-controller, cleanup this field.
Fixes #
None
> Cleanup ClusterClientSetFunc field in execution-controller

- artifacts/deploy/webhook-configuration.yaml
The original webhook call timeout is 3s, with this time, our CI always has a timeout error, so I extend the timeout period of webhook to 10s.
Fixes #
```release-note
NONE
```
> Extend the timeout period of webhook to 10s

- pkg/karmadactl/describe.go
Signed-off-by: TheStylite <848099532@qq.com>
/kind feature
```
(⎈ |karmada:default)➜  karmada git:(fix-karmadactl-describe) karmadactl describe po -C ocp micro-dao-2048-74d69cb547-vjqtr -n demo
Error: unknown shorthand flag: 'n' in -n
(⎈ |karmada:default)➜  karmada git:(fix-karmadactl-describe) kubens demo
Context "karmada" modified.
Active namespace is "demo".
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-describe) karmadactl describe po -C ocp micro-dao-2048-74d69cb547-vjqtr
Name:           micro-dao-2048-74d69cb547-vjqtr
Namespace:      demo
Priority:       0
Node:           nodedsp07.ocp.ats.io/10.23.105.11
Start Time:     Thu, 30 Jun 2022 16:13:57 +0800
Labels:         dce.daocloud.io/app=micro-dao-2048 …
```
> karmadactl describe support the --namespace flag

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cordon.go
- pkg/karmadactl/deinit.go
- pkg/karmadactl/describe.go
- pkg/karmadactl/exec.go
- pkg/karmadactl/get.go
- pkg/karmadactl/join.go
- pkg/karmadactl/logs.go
- pkg/karmadactl/promote.go
- pkg/karmadactl/taint.go
- pkg/karmadactl/unjoin.go
- pkg/version/sharedcommand/sharedcommand.go
/kind cleanup
The existing print example implementation functions have string concatenation, which is not maintainable, so use templates like Kubectl
If we execute` karmadactl get -h`, it will print
```
➜  karmada git:(fix-karmadactl-example) ✗ go run cmd/karmadactl/karmadactl.go get -h     
Display one or many resources
Usage:
karmadactl get [NAME | -l label | -n namespace]  [flags]
Examples:
karmadactl get pods
karmadactl get pods -o wide
karmadactl get pods -C member1
karmadactl get replicasets nginx
karmadactl get deployments.v1.apps -o json
karmadactl get -o template deployment/nginx -C member1 --template={{.spec.replicas}}
karmadactl get rs,services
karmadactl get rs/nginx-cb87b6d88 service/kubernetes
```
**Which …
> karmadactl-example:print example by templates like kubectl

- cmd/karmadactl/karmadactl.go
- cmd/kubectl-karmada/kubectl-karmada.go
/kind  feature
We have introduced `k8s.io/component-base/cli` at #2049, but for `karmadactl`, we need to preety-print the error refering https://github.com/kubernetes/kubernetes/blob/01f80aefeb4c1e85b29bdc006f3d407c6ed43fd8/cmd/kubectl/kubectl.go#L28-L34
```
[root@master67 karmada]# karmadactl get p
E0710 17:03:14.590436   32212 run.go:74] "command failed" err="[cluster(member2): the server doesn't have a resource type \"p\", cluster(member1): the server doesn't have a resource type \"p\"]"
```
change to
```
[root@master67 karmada]# ./karmadactl get p
cluster(member1): the server doesn't have a resource type "p"
cluster(member2): the server doesn't have a resource type "p"
``` …
> karmadactl pretty-print the error and exit with an error

- charts/karmada/templates/post-install-job.yaml
- docs/upgrading/README.md
- hack/deploy-karmada.sh
Simplify build scripts for kubectl apply when handling kustomization resources.
`kubectl apply -k` was direct commands to achieve the goals.
The edited script was used to install karmada.
/kind flake
There was a simply way to do it.
None
`./hack/local-up-karmada.sh` tested successfully.
None
```release-note
None
```
> chore: simplify build scripts for kubectl apply when handling kustomization resources

- pkg/karmadactl/get.go
Cherry pick of https://github.com/karmada-io/karmada/pull/2171 on release-1.2.
#2171 :Fix karmadactl get -C error
/kind bug
```release-note
`karmadactl`: Fixed a panic issue when retrieving resources from an unknown cluster(`karmadactl get xxx --cluster=not-exist`).
```
> Automated cherry-pick: Merge pull request #2171 :Fix karmadactl get -C error

- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
Cherry pick of #2241 on release-1.2.
#2241: Fix: ArgoCD can not assess Deployment health status.
```release-note
`karmada-controller-manager`: Fixed Argo CD can not assess Deployment health status issue.
```
> Automated cherry pick of #2241: Fix: ArgoCD can not assess Deployment health status.

- pkg/karmadactl/join.go
- pkg/karmadactl/unjoin.go
/kind cleanup
When we perform join or unjoin, we can enter two or more path parameters, as shown below
```
➜  karmada git:(master) go run cmd/karmadactl/karmadactl.go join foo bar
E0705 21:47:46.045738   75252 run.go:74] "command failed" err="failed to get joining cluster config. error: context \"foo\" does not exist"
exit status 1
```
However, we only allow the user to enter the cluster name, and I understand that Complete() is used to complete the parameter and Validate() is used to check whether the user input is valid, so I put the validation of args into Validate(). errors.New() is no longer used,just use fmt.Errorf().
in this PR, it can be
```
➜  karmada git:(fix-args-validate) go run cmd/karmadactl/karmadactl.go …
```
> karmadactl:modify join and unjoin validation

- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
/kind bug
We disabled `ObservedGeneration` aggregation at #1586 for `Deployment`( and not enable for`StatefulSet`/`DaemonSet`), that leads to Argo CD can't assess the health status issue.
#2218 fixed the `Deployment` part, and the current PR fixes the rest.
Fixes #
Both #2218 and current PR should be cherry-picked to release-1.2.
```release-note
`karmada-controller-manager`: Fixed Argo CD can not assess StatefulSet/DaemonSet health status issue.
```
> Fixed Argo CD can not assess StatefulSet and DaemonSet health status issue

- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
Cherry pick of #2252 on release-1.2.
#2252: Fixed Argo CD can not assess StatefulSet and DaemonSet health
```release-note
`karmada-controller-manager`: Fixed Argo CD can not assess StatefulSet/DaemonSet health status issue.
```
> Automated cherry pick of #2252: Fixed Argo CD can not assess StatefulSet and DaemonSet health

- pkg/detector/detector.go
- pkg/detector/eventfilter.go
- pkg/detector/eventfilter_test.go
/kind feature
Reduce the number of reconciliations on update in detector
Fixes #
Test detector using the deployment and propagationpolicy in {repo}/samples/nginx, and change the parmaters as the follow steps:
* create nginx-propagation with weightPreference member1:1, menber2:2
* create nginx-deployment with replicas 1
* change nginx-deployment replicas to 3
* change nginx-propagation weightPreference to member1:2, member2:1
* change nginx-deployment replicas to 5
* change nginx-propagation weightPreference to member1:2, member2:3
* delete nginx-deployment
* delete nginx-propagation
the count number of reconciliations and interceptiosn as follows: …
> Reduce the number of reconciliations on update in detector

- pkg/karmadactl/apply.go
- pkg/karmadactl/describe.go
- pkg/karmadactl/exec.go
- pkg/karmadactl/get.go
- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/logs.go
/kind feature
take iostreams as a func parameter that can be used by logs, get, describe and exec.
```release-note
NONE
```
> take iostreams as a func parameter 

- pkg/apis/work/v1alpha2/binding_types_helper.go
- pkg/apis/work/v1alpha2/binding_types_helper_test.go
- pkg/controllers/cluster/taint_manager.go
- pkg/util/binding.go
/kind cleanup
This PR introduced `RemoveCluster` method to `ResourceBinding` and `ClusterResourceBinding`, which could be used to cleanup a specific cluster in scenarios like `cluster unjoin`.
Fixes #
```release-note
NONE
```
> Introduce RemoveCluster helper method for RB/CRB

- pkg/registry/search/storage/requestinfo.go
- pkg/registry/search/storage/requestinfo_test.go
Cherry pick of #2227 on release-1.2.
#2227: modify contains-merge-commits
```
karmada-search: fixed can not query a single namespace issue.
```
> Automated cherry pick of #2227: karmada-search cannot query a single namespace

- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/binding/common.go
- pkg/controllers/namespace/namespace_sync_controller.go
- test/e2e/clusteroverridepolicy_test.go
- test/e2e/framework/clusteroverridepolicy.go
- test/helper/policy.go
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
/kind feature
Fixes #2236
support ClusterOverridePolicy in namespaces_sync_controller
```release-note
`karmada-controller-manager`: `namespace` controller starts to apply `ClusterOverridePolicy` during propagation namespaces.
```
> support ClusterOverridePolicy in namespaces_sync_controller

- charts/karmada/_crds/bases/networking.karmada.io_multiclusteringresses.yaml
- charts/karmada/_crds/bases/policy.karmada.io_clusteroverridepolicies.yaml
- charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
- charts/karmada/_crds/bases/policy.karmada.io_federatedresourcequotas.yaml
- charts/karmada/_crds/bases/policy.karmada.io_overridepolicies.yaml
- charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
- charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
- charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
- charts/karmada/_crds/bases/work.karmada.io_works.yaml
- pkg/apis/networking/v1alpha1/ingress_types.go
- pkg/apis/policy/v1alpha1/federatedresourcequota_types.go
- pkg/apis/policy/v1alpha1/override_types.go
- pkg/apis/policy/v1alpha1/propagation_types.go
- pkg/apis/work/v1alpha1/binding_types.go
- pkg/apis/work/v1alpha1/work_types.go
- pkg/apis/work/v1alpha2/binding_types.go
Signed-off-by: hejianpeng <hejianpeng2@huawei.com>
/kind feature
with this PR allow user get all karamda CR via `kubectl get karmada-io`
also support list resources by `kubectl get policy-karmada-io`
more information can be found [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#categories)
cc @XiShanYongYe-Chang @RainbowMango 
Fixes #
```release-note
Karmada APIs now are grouped by 'karmada-io' category. People can use `kubectl get karmada-io` command gets all Karmada resources.
```
> support CRD category

- charts/karmada/templates/karmada-webhook.yaml
/kind bug
when we install karmada with chart and not to set the release to `karmada`. the webhook `svc` is not work:
reproduce: 
```shell
helm install kariship  -n karmada-system --dependency-update  --create-namespace  ./charts/karmada --debug
```
webhook deploy info:
webhook svc info:
Fixes #
Please corrent me if not.
```release-note
Helm Chart: Fixed the webhook service mismatch issue in case of customized release name.
```
> fix webhook svc chart temp

- pkg/karmadactl/addons/addons.go
- pkg/karmadactl/addons/descheduler/descheduler.go
- pkg/karmadactl/addons/descheduler/manifests.go
- pkg/karmadactl/addons/disable.go
- pkg/karmadactl/addons/enable.go
- pkg/karmadactl/addons/estimator/estimator.go
- pkg/karmadactl/addons/estimator/manifests.go
- pkg/karmadactl/addons/init/addon.go
- pkg/karmadactl/addons/init/disable_option.go
- pkg/karmadactl/addons/init/enable_option.go
- pkg/karmadactl/addons/init/global.go
- pkg/karmadactl/addons/init/list_option.go
- pkg/karmadactl/addons/install/install.go
- pkg/karmadactl/addons/list.go
- pkg/karmadactl/addons/search/manifests.go
- pkg/karmadactl/addons/search/search.go
- pkg/karmadactl/addons/utils/idempotency.go
- pkg/karmadactl/addons/utils/template.go
- pkg/karmadactl/cmdinit/karmada/check.go
- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deployments.go
- pkg/karmadactl/karmadactl.go
- pkg/util/names/names.go
Co-authored-by: duanmeng <duanmeng_yewu@cmss.chinamobile.com>
/kind feature
Add karmadactl addons subcommand
Fixes https://github.com/karmada-io/karmada/issues/1957
```release-note
NONE
```
> Add karmadactl addons subcommand

- cmd/webhook/app/options/options.go
- cmd/webhook/app/webhook.go
- pkg/util/helper/taint.go
- pkg/webhook/clusterpropagationpolicy/mutating.go
- pkg/webhook/propagationpolicy/mutating.go
/kind feature
Add default tolerations, defaultNotReadyTolerationSeconds and defaultUnreachableTolerationSeconds, for pp and cpp.
Refer to https://github.com/kubernetes/kubernetes/blob/24753aa8a4df8d10bfd6330e0f29186000c018be/plugin/pkg/admission/defaulttolerationseconds/admission.go
Fixes #
```release-note
`karmada-webhook`: Added default tolerations, defaultNotReadyTolerationSeconds and defaultUnreachableTolerationSeconds, for (Cluster)PropagationPolicy.
```
> add default tolerations for pp and cpp

- pkg/karmadactl/apply.go
/kind bug
The two descriptions seems don't match
This should probably be `karmadactl`
**Does this PR introduce a user-facing change?:**
`NONE`
> fix karmadactl apply help

- pkg/controllers/mcs/endpointslice_controller.go
- pkg/controllers/status/cluster_status_controller.go
- pkg/dependenciesdistributor/dependencies_distributor.go
- pkg/detector/detector.go
- pkg/estimator/server/replica/replica.go
- pkg/resourceinterpreter/customizedinterpreter/configmanager/manager.go
- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus.go
- pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
- pkg/resourceinterpreter/defaultinterpreter/dependencies.go
- pkg/resourceinterpreter/defaultinterpreter/prune/prune.go
- pkg/resourceinterpreter/defaultinterpreter/reflectstatus.go
- pkg/resourceinterpreter/defaultinterpreter/replica.go
- pkg/resourceinterpreter/defaultinterpreter/retain.go
- pkg/util/helper/unstructured.go
- pkg/util/overridemanager/imageoverride.go
/kind cleanup
Instead of adding a conversion function for each resource, we should replace it with a generic conversion function.
> optimize unstructured convert methods

- docs/userguide/aggregated-api-endpoint.md
When we install Karmada using `hack/local-up-karmada.sh`, the kubeconfig file is stored under `${HOME}/.kube`, so `$HOME` is not necessarily set to `/root`, and can be seen in `local-up-karmada.sh` as follows
```shell
KUBECONFIG_PATH=${KUBECONFIG_PATH:-"${HOME}/.kube"}
MAIN_KUBECONFIG=${MAIN_KUBECONFIG:-"${KUBECONFIG_PATH}/karmada.config"}
HOST_CLUSTER_NAME=${HOST_CLUSTER_NAME:-"karmada-host"}
KARMADA_APISERVER_CLUSTER_NAME=${KARMADA_APISERVER_CLUSTER_NAME:-"karmada-apiserver"}
MEMBER_CLUSTER_KUBECONFIG=${MEMBER_CLUSTER_KUBECONFIG:-"${KUBECONFIG_PATH}/members.config"}
MEMBER_CLUSTER_1_NAME=${MEMBER_CLUSTER_1_NAME:-"member1"}
MEMBER_CLUSTER_2_NAME=${MEMBER_CLUSTER_2_NAME:-"member2"} …
```
> docs: changed the way to get the kubeconfig path in aggregation api

- pkg/controllers/status/workstatus_controller.go
Signed-off-by: yy158775 <1584616775@qq.com>
/kind feature
When the object's status changed,it will not collect status if the Work object being deleted. 
Fixes #
NONE
```release-note
NONE
```
Here are my tests:
Step 1:
kubectl apply -f samples/nginx/propagationpolicy.yaml
kubectl apply -f samples/nginx/deployment.yaml
Step 2:
Add finalizer to Work object in order to avoid being deleted.
Step 3:
Add finalizer to Deployment object in order to avoid being deleted.
Step 4:
Delete Work.Because of finalizer Work and Deployment will not  be deleted.
Step 5:
In order to make status changed,we can delete …
> stop update status if Work object in terminating state

- pkg/scheduler/scheduler.go
- pkg/util/helper/patch.go
- pkg/util/helper/patch_test.go
/kind feature
Set `.status.schedulerObservedGeneration` of ResourceBinding after schedule.
Partof #2281
```release-note
NONE(include in graceful eviction feature)
```
> patch resourcebinding instead of update and update observed generation.

- pkg/karmadactl/join.go
- pkg/util/credential.go
Fix "namespace "karmada-cluster" not found" when cluster is being registered with "pull" mode
Signed-off-by: wuzhongjian <wuzhongjian_yewu@cmss.chinamobile.com>
/kind bug
After installed karmada through "kubectl karmada init", and then registering the member cluster with ‘pull’ mode, the agent log reports an error ”namespace \"karmada-cluster"\ not found“，so the ”karmada-cluster“ namespace needs to be created by default when the karmada control plane is initialized.
Fixes #
```release-note
NONE
```
> fix karmada-agent can not ensure default namespace issue

- pkg/karmadactl/cmdinit/utils/kubeclient.go
- pkg/karmadactl/config.go
/kind bug
If we use the same `karmadaConfig` object, and call method `GetClientConfig` more than once. The first time it would set the `ExplicitPath` and `Precedence` successfully. But the second time it would set `Precedence` with the value of `ExplicitPath` the first time set.
Fixes #
NONE
> Adjust the order of kubeconfig loadingRules

- pkg/controllers/binding/binding_controller.go
- pkg/controllers/binding/cluster_resource_binding_controller.go
- pkg/util/helper/binding.go
- pkg/util/helper/workstatus.go
- pkg/util/helper/workstatus_test.go
/kind feature
Make changes to `binding-controller` to adopt graceful eviction:  when finding orphan work, exclude the works in the cluster that exists in the `.spec.gracefulEvictionTasks` of binding object.
Part of #2281
```release-note
NONE(include in graceful eviction feature)
```
> Make changes to binding-controller to adopt graceful eviction

- pkg/features/features.go
/kind feature
This PR introduced a feature gate and defaults in `alpha` state.
Part of #2281
The new feature gate presents in the command line as expected:
```
--feature-gates mapStringBool                                                                                                                                                                                              
A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
AllAlpha=true|false (ALPHA - default=false)
AllBeta=true|false (BETA - default=false)
Failover=true|false (ALPHA - default=false)
GracefulEviction=true|false (ALPHA - …
```
> Introduce graceful eviction feature gate and mark feature in alpha state

- pkg/search/backendstore/opensearch.go
Cherry pick of #2331 on release-1.2.
#2331: fixed panic issue when dumps error infos
```release-note
`karmada-search`: Fixed panic issue when dumps error info.
```
> Automated cherry pick of #2331: fixed panic issue when dumps error infos

- charts/karmada/templates/_karmada_apiservice.tpl
/kind bug
When use the helm cmd install karmada without any component,  but the search `APIService` is be deployed togother. 
if we want to delete a namespace in karmada cluster, the following error message will be report:
Because when we delete namespace, the k8s will delete all of the resource with delete verb in the namespace, incloude of  AA resource. But the search conponent is not be installed by default,  the apiserver not find the server of search.
Fixes #
Please correct me if not.
```release-note
NONE
```
> disabled search APIService chart resource by default

- pkg/karmadactl/join.go
/kind bug
As is talked in #1350,  add warnings when config cluster-namespace as karmada-system.
```
root@ecs-3fa1:~/karmada/cmd/karmadactl# ./karmadactl join member3 --cluster-namespace=karmada-system
W0711 14:26:46.498568 1809697 join.go:140] karmada-system is always reserved for Karmada control plane. We do not recommend using karmada-system to store secrets of member clusters. It may cause mistaken cleanup of resources.
```
Fixes #1350 
None
> Add warnings when config cluster-namespace as karmada-system

- pkg/scheduler/scheduler.go
- pkg/scheduler/scheduler_test.go
/kind feature
Fixes #
```release-note
patch resourcebinding and clusterresourcebinding instead of update and update observed generation.
add test for them
```
>  patch resourcebinding instead of update and update observed generation.

- cmd/agent/app/agent.go
- pkg/controllers/cluster/cluster_controller.go
- pkg/karmadactl/join.go
- pkg/util/cluster.go
/kind feature
To add spec.id in karmada control plane's Cluster object.
refer to #2017
Fixes #
```release-note
Collect cluster's kube-system namespace uuid into Cluster object.
```
Here are Verification Results,
When use hack/local-up-karmada to start,you can find the result:
1.push mode
the same as kube-system's Namespace in Cluster. 
2.pull mode
The result is the same as above.
When upgrading,the existed Cluster objects will have spec.id field.
Push and Pull mode both have the same result.
> add ID the unique identifier for push and pull mode's cluster

- artifacts/deploy/karmada-controller-manager.yaml
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/controllers/context/context.go
- pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
- pkg/controllers/gracefuleviction/evictiontask.go
- pkg/controllers/gracefuleviction/evictiontask_test.go
- pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
/kind feature
- Add `grace-eviction-period` flag for `karmada-controller-manager` to specifies the timeout period waiting for the grace-eviction-controller performs the final removal when the workload(resource) has been moved to the graceful eviction tasks.
- Add `grace-eviction-controller` which performs the following two things:
- Firstly, set the `creationTimestamp` for task in the binding's `spec.gracefulEvictionTasks`.
- Secondly, after the task times out, delete the task from the binding's `spec.gracefulEvictionTasks`.
part #2281
```release-note …
```
> Add grace-eviction-controller to evict cluster workload

- cmd/agent/app/agent.go
- cmd/controller-manager/app/controllermanager.go
- pkg/controllers/status/cluster_status_controller.go
- pkg/util/fedinformer/typedmanager/multi-cluster-manager.go
- pkg/util/fedinformer/typedmanager/single-cluster-manager.go
/kind cleanup
Rename package name from `typedManager` to `typedmanager`
Fixes #
None
> Rename package name of typedmanager

- cmd/controller-manager/app/controllermanager.go
- pkg/apis/cluster/v1alpha1/events.go
- pkg/apis/cluster/v1alpha1/well_known_constants.go
- pkg/controllers/cluster/cluster_controller.go
/kind feature
Remove cluster scheduling result in spec.clusters when the cluster is terminating.
part of #1762
Fixes #1995
```release-note
NONE
```
> remove TargetCluster when cluster is terminating

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- cmd/controller-manager/app/controllermanager.go
- cmd/controller-manager/app/options/options.go
- pkg/controllers/context/context.go
- pkg/controllers/status/cluster_status_controller.go
/kind feature
This PR actually takes over #1858, fixed comments.
Fixes #1858
```release-note
`karmada-controller-manager`/`karmada-agent`: Introduced `--enable-cluster-resource-modeling` flag to enable or disable cluster modeling feature.
```
> Introduce `--enable-cluster-resource-modeling` to customize resource modeling feature

- artifacts/deploy/karmada-aggregated-apiserver.yaml
- artifacts/deploy/karmada-apiserver.yaml
- artifacts/deploy/karmada-cert-secret.yaml
- artifacts/deploy/karmada-etcd.yaml
- artifacts/deploy/karmada-search.yaml
- artifacts/deploy/kube-controller-manager.yaml
- artifacts/deploy/secret.yaml
- examples/README.md
- hack/deploy-karmada.sh
- hack/pre-run-e2e.sh
- hack/util.sh
/kind feature
Standardize the generation and management of certificates to prepare for certificate authentication and certificate rotation.
Fixes #
```release-note
NONE
```
> Standardize the generation and management of certificates

- go.mod
- pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/utils/configmap.go
- pkg/karmadactl/cmdinit/utils/rbac.go
/kind feature
Part of #2282 
```
[root@master67 karmada]# kubectl get configmap -n kube-public cluster-info -o yaml --kubeconfig /etc/karmada/karmada-apiserver.config
apiVersion: v1
data:
kubeconfig: |
apiVersion: v1
clusters:
- cluster:
certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFmTVJBd0RnWURWUVFLRXdkcllYSnQKWVdSaE1Rc3dDUVlEVlFRREV3SmpZVEFlRncweU1qQTRNREl3T0RVMk5EZGFGdzB6TWpBM016QXdPRFUyTkRkYQpNQjh4RURBT0JnTlZCQW9UQjJ0aGNtMWhaR0V4Q3pBSkJnTlZCQU1UQW1OaE1JSUJJakFOQmdrcWhraUc5dzBCCkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRkUzF2eEIwQkd0RElBS1k …
```
> Set open cluster-info to distribute root CA certificates

- pkg/resourceinterpreter/defaultinterpreter/healthy.go
- pkg/resourceinterpreter/defaultinterpreter/healthy_test.go
/kind feature
add default resource interpreter for interpretHealth
Part of #2354
The method for health check is referred to https://github.com/jessesuen/argo-cd/blob/37a58fb9f1a2d7e20fe8e37a93ffa2e66b0eb9c7/util/health/health.go 
NONE
> add default interpreter for interpretHealth

- cmd/agent/app/agent.go
- pkg/karmadactl/join.go
- pkg/util/cluster.go
- pkg/util/cluster_test.go
Signed-off-by: yy158775 <1584616775@qq.com>
/kind bug
prevent the same cluster repeating to join karmada.
Fixes https://github.com/karmada-io/karmada/issues/1351
```
The same cluster repeatedly join has two scenarios.
One is use karmadactl to join push mode cluster.
Before join,the cluster member1,member2,member3 has joined in karmada.
Now we use member4 as the cluster's name to join the member1's cluster to control plane.
karmadactl join member4 --cluster-kubeconfig=~/.kube/members.config --cluster-context=member1
Results:
error: failed to create cluster(member4) object. error: cluster(id:fc1c4701-34c9-4a4b-afc2-296ecefe0c2d) already exist
The other …
```
> avoid joining the same cluster repeatedly

- api/openapi-spec/swagger.json
- cmd/aggregated-apiserver/app/options/options.go
- pkg/apis/cluster/mutation/mutation.go
- pkg/apis/cluster/types.go
- pkg/apis/cluster/v1alpha1/types.go
- pkg/features/features.go
- pkg/generated/openapi/zz_generated.openapi.go
- pkg/registry/cluster/strategy.go
/kind feature
Set default model for cluster.
Grade 0 is like:
Grade 8 is like:
--feature-gates mapStringBool                                                                                                                    
A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
APIListChunking=true|false (BETA - default=true)
APIPriorityAndFairness=true|false (BETA - default=true)
APIResponseCompression=true|false (BETA - default=true)
APIServerIdentity=true|false (ALPHA - default=false)
APIServerTracing=true|false (ALPHA - default=false)
AllAlpha=true|false (ALPHA - default=false)
AllBeta=true|false (BETA - default=false) …
> Set default model for cluster

- api/openapi-spec/swagger.json
- charts/karmada/_crds/bases/work.karmada.io_clusterresourcebindings.yaml
- charts/karmada/_crds/bases/work.karmada.io_resourcebindings.yaml
- charts/karmada/_crds/bases/work.karmada.io_works.yaml
- pkg/apis/work/v1alpha1/binding_types_conversion.go
- pkg/apis/work/v1alpha1/work_types.go
- pkg/apis/work/v1alpha2/binding_types.go
- pkg/generated/openapi/zz_generated.openapi.go
/kind feature
We need to collect resource health status in the `Work` and `RsourceBinding/ClusterResourceBinding` objects to indicate the health of the resources that are applied to the member cluster, so I added the `health` field in the  `Work` and `RsourceBinding/ClusterResourceBinding`  API.
Fixes #
```release-note
Add health field in the Work and RsourceBinding/ClusterResourceBinding API
```
> add health field in the binding and work api

- charts/karmada/templates/_karmada_webhook_configuration.tpl
/kind cleanup
cleanup misconfigured validation webhook from the chart.
Fixes #2254
```release-note
NONE
```
> fix: remove unexpected validate webhook in configuration

- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/token.go
- pkg/karmadactl/util/bootstraptoken/bootstraptoken.go
- pkg/util/lifted/pubkeypin/pubkeypin.go
- pkg/util/lifted/pubkeypin/pubkeypin_test.go
- pkg/util/secret.go
- vendor/k8s.io/cluster-bootstrap/util/secrets/secrets.go
- vendor/modules.txt
/kind feature
```
[root@master67 karmada]# ./karmadactl token -h
This command manages bootstrap tokens. It is optional and needed only for advanced use cases.
In short, bootstrap tokens are used for establishing bidirectional trust between a client and a server. A bootstrap
token can be used when a client (for example a member cluster that is about to join control plane) needs to trust the
server it is talking to. Then a bootstrap token with the "signing" usage can be used. bootstrap tokens can also function
as a way to allow short-lived authentication to the API Server (the token serves as a way for the API Server to trust
the client), for example for doing the TLS Bootstrap. …
```
> Implement karmadactl token command to manage bootstrap tokens

- go.mod
- go.sum
- pkg/modeling/modeling.go
- pkg/modeling/modeling_test.go
- vendor/github.com/emirpasic/gods/LICENSE
- vendor/github.com/emirpasic/gods/containers/containers.go
- vendor/github.com/emirpasic/gods/containers/enumerable.go
- vendor/github.com/emirpasic/gods/containers/iterator.go
- vendor/github.com/emirpasic/gods/containers/serialization.go
- vendor/github.com/emirpasic/gods/trees/redblacktree/iterator.go
- vendor/github.com/emirpasic/gods/trees/redblacktree/redblacktree.go
- vendor/github.com/emirpasic/gods/trees/redblacktree/serialization.go
- vendor/github.com/emirpasic/gods/trees/trees.go
- vendor/github.com/emirpasic/gods/utils/comparator.go
- vendor/github.com/emirpasic/gods/utils/sort.go
- vendor/github.com/emirpasic/gods/utils/utils.go
- vendor/modules.txt
/kind feature
This PR introduced a feature of cluster resource modeling
Part of https://github.com/karmada-io/karmada/issues/772
This pr is for issue https://github.com/karmada-io/karmada/issues/772 cluster resource modeling code implementation part.
None
My solution is the picture below:
The system defaults to 11 grade levels. The grading of each grade is as shown above. For example, the resource configuration of grade =2 model is as follows
```
resourceModel:
- grade:
cpu: "2"
memory: 4Gi
count: 34
```
grade = 2, which means cpu belongs to (2C, 4C], memory belongs to (2G, 4G], left open and right closed.
Users can also …
> Cluster resource modeling

- pkg/controllers/status/workstatus_controller.go
- pkg/resourceinterpreter/defaultinterpreter/default.go
- pkg/util/helper/workstatus.go
/kind feature
As we import health field with Work API in #2351, we plan to:
- Reflect `Work` health status for recording the healthy state of the current resource.
- Assemble `ResourceBinding/ClusterResourceBinding` health item status for recording the healthy state of the current resource running in the member cluster.
Preparing for subsequent graceful evictions #2281 
Fixes #
```release-note
NONE(include in graceful eviction feature)
```
> Reflect health status for recording the healthy state of the current resource

- charts/templates/_karmada_webhook_configuration.tpl
- charts/templates/post-install-job.yaml
Cherry pick of https://github.com/karmada-io/karmada/pull/2401 https://github.com/karmada-io/karmada/pull/2258 on release-1.2.
https://github.com/karmada-io/karmada/pull/2401: fix: remove unexpected validate webhook in configuration
https://github.com/karmada-io/karmada/pull/2258: fix: create cluster apiservice in post install job
```release-note
`Helm Chart`: Fixed misconfigured `MutatingWebhookConfiguration`. 
`Helm Chart`: added missing `APIService` configuration for `karmada-aggregated-apiserver`.
```
> Automated cherry pick of #2401: fix: remove unexpected validate webhook in configuration #2258: fix: create cluster apiservice in post install job

- pkg/karmadactl/cmdinit/karmada/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/utils/examples.go
- pkg/karmadactl/cmdinit/utils/examples_test.go
/kind feature
Print the new cluster register way after finishing karmadactl init.
```
------------------------------------------------------------------------------------------------------
█████   ████   █████████   ███████████   ██████   ██████   █████████   ██████████     █████████
░░███   ███░   ███░░░░░███ ░░███░░░░░███ ░░██████ ██████   ███░░░░░███ ░░███░░░░███   ███░░░░░███
░███  ███    ░███    ░███  ░███    ░███  ░███░█████░███  ░███    ░███  ░███   ░░███ ░███    ░███
░███████     ░███████████  ░██████████   ░███░░███ ░███  ░███████████  ░███    ░███ ░███████████
░███░░███    ░███░░░░░███  ░███░░░░░███  ░███ ░░░  ░███  ░███░░░░░███  ░███    ░███ ░███░░░░░███
░███ ░░███ …
```
> Optimize `karmadactl init` to output example

- pkg/controllers/status/workstatus_controller.go
/kind bug
In the pr #2425 we encountered a CI error https://github.com/karmada-io/karmada/runs/8028253698?check_suite_focus=true and the component `karmada-controller-manager` error log shows as below:
```log
2022-08-26T01:43:46.835385736Z stderr F W0826 01:43:46.835129       1 customized.go:148] Failed calling webhook examples/workloads.example.com: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://172.18.0.6:443/interpreter-workload?timeout=3s": context deadline exceeded
2022-08-26T01:43:46.835568337Z stderr F E0826 01:43:46.835487       1 workstatus_controller.go:289] Failed to reflect status for …
```
> [bugfix] fix error of reflectStatus failed when call resourceInterpreter

- pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
- pkg/controllers/gracefuleviction/evictiontask.go
- pkg/controllers/gracefuleviction/evictiontask_test.go
- pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
/kind feature
When we evict workload replicas from the failover cluster in the `ResourceBinding/ClusterResourceBinding`, we need to perceive the health status of the current scheduling result of the binding to make the eviction more graceful. If the status is healthy, we can evict workload replicas directly. Otherwise, wait for the timeout period.
Part of #2281 
```release-note
NONE(include in graceful eviction feature)
```
> Perceiving the health status of cluster scheduling results in graceful evictions

- pkg/controllers/status/workstatus_controller.go
Cherry pick of #2428 on release-1.2.
#2428: fix error of reflectStatus failed when call
```release-note
`karmada-controller-manager`/`karmada-agent`: Fixed an resource status can not be collected issue in case of Resource Interpreter returns an error.
```
> Automated cherry pick of #2428: fix error of reflectStatus failed when call

- artifacts/agent/karmada-agent.yaml
- cmd/agent/app/options/options.go
- pkg/estimator/client/general.go
/kind feature
Schedule base on cluster resource modeling.
Test By default models:
Resource models are like:
```
- grade: 2
ranges:
- max: "4"
min: "2"
name: cpu
- max: 32Gi
min: 16Gi
name: memory
- grade: 3
ranges:
- max: "8"
min: "4"
name: cpu
- max: 64Gi
min: 32Gi
name: memory
```
status is like:
```
- count: 1
grade: 2
- count: 6
grade: 3
```
When schedule a replicas:
```
spec:
replicas: 1
......
spec:
containers:
- image: nginx
name: nginx
resources:
requests:
cpu: 3
memory: 20Gi
``` 
schedule result:
```
I0824 03:14:15.763667       1 util.go:72] Target cluster: [{member1 7} {member2 0} {member3 0}]
```
When change pod resources to 3C and 40Gi:
schedule result:
``` …
```
> Schedule based on cluster resource model

- pkg/controllers/cluster/cluster_controller.go
/kind feature
There should be a taint during the period before the state of the newly added cluster becomes ready
Fixes #
```release-note
NONE
```
> Add NotReady taint to the new cluster

- pkg/scheduler/event_handler.go
- test/e2e/rescheduling_test.go
/kind feature
Fixes #2261
When a new cluster is joined, if the `Placement` is empty or the `replicaSchedulingType` is `Duplicated`. Will propagate resources to the new cluster
```release-note
Reschedule ResourceBinding when adding a cluster
```
> Reschedule ResourceBinding when adding a cluster

- charts/values.yaml
Cherry pick of #1691 on release-1.1.
#1691: fix karmada-apiserver pending when helm upgrade
```release-note
`Helm Chart`: Fixed `karmada-apiserver` always in pending in case of upgrade issue.
```
> Automated cherry pick of #1691: fix karmada-apiserver pending when helm upgrade

- charts/karmada/templates/kube-controller-manager.yaml
- charts/karmada/templates/pre-install-job.yaml
Signed-off-by: ndx-robot <xiao.zhang@daocloud.io>
/kind bug
At present, in the karmada charts, the kube-controller configuration is incorrect, which causes the certificate to not work properly after it is issued.
Fixes #
```release-note
```
> fix karmada chart kube-controller cluster-signing config error

- artifacts/deploy/kube-controller-manager.yaml
- charts/karmada/templates/kube-controller-manager.yaml
/kind feature
At present, karmada controller-plane does not support the ability to issue certificates through csr, but we can access karmada controller-plane by issuing certificates with different permissions through csr, which is very meaningful
Fixes #
```release-note
```
> karmada controller-plane supports the ability to issue certificates via csr

- artifacts/deploy/karmada-controller-manager.yaml
- artifacts/deploy/karmada-webhook.yaml
- cmd/controller-manager/app/controllermanager.go
- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/framework/interface.go
- pkg/scheduler/framework/plugins/apienablement/api_enablement.go
- pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
- pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
- pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
- pkg/scheduler/framework/runtime/framework.go
- test/e2e/rescheduling_test.go
/kind feature
When we use `taint_toleration` plug-in in the scheduler to filter clusters, we should ignore those clusters that have been scheduled and leave them to the `taint-manager` for processing.  This way, the cluster failover eviction will be performed only in the `taint-manager`.
Fixes #
```release-note
karmada-scheduler: don't consider the older cluster when filtering with taint_toleration
```
> [karmada-scheduler] don't consider the older cluster when filtering with taint_toleration

- pkg/scheduler/core/spreadconstraint/group_clusters.go
/kind bug
Fix bug of panic when `replicaDivisionPreference` is `Weighted` and `WeightPreference` is nil at the same time:
```yaml
replicaSchedulingType: Divided 
replicaDivisionPreference: Weighted
```
Fixes #2447 
```release-note
karmada-sechduler: Fix panic when `replicaDivisionPreference` is `Weighted` and `WeightPreference` is nil.
```
> [bugfix] when replicaDivisionPreference is Weighted and WeightPreference is nil

- pkg/scheduler/core/spreadconstraint/group_clusters.go
Cherry pick of #2451 on release-1.2.
#2451: fix bug of #2447: when replicaDivisionPreference is Weighted
```release-note
`karmada-sechduler`: Fixed a panic issue when `replicaDivisionPreference` is `Weighted` and `WeightPreference` is nil.
```
> Automated cherry pick of #2451: fix bug of #2447: when replicaDivisionPreference is Weighted

- .github/workflows/ci.yml
- .github/workflows/dockerhub-latest-image.yml
- .github/workflows/dockerhub-released-image.yml
- .github/workflows/fossa.yml
- .github/workflows/release.yml
- .github/workflows/swr-latest-image.yml
- .github/workflows/swr-released-image.yml
/kind cleanup
The Ubuntu-18.04 environment is deprecated and will be removed on December 1st, 2022. For more details, see https://github.com/actions/runner-images/issues/6002
Fixes #
Our CI jobs are affected by the brownout periods :):
https://github.com/karmada-io/karmada/actions/runs/2903700379
The reason why I didn't choose the newer `ubuntu-22.04` is that it's not the stable(GA) one by now.
Just echo from the [Label Schema](https://github.com/actions/runner-images#label-scheme):
> In general the -latest label is used for the latest OS image version that is GA
```release-note
NONE
```
> bump ci runner to ubuntu-20.04 as ubuntu-18.04 is deprecated.

- .github/workflows/ci.yml
- .github/workflows/dockerhub-latest-image.yml
- .github/workflows/dockerhub-released-image.yml
- .github/workflows/fossa.yml
- .github/workflows/release.yml
- .github/workflows/swr-latest-image.yml
- .github/workflows/swr-released-image.yml
Cherry pick of #2404 on release-1.2.
#2404: bump ci runner to ubuntu-20.04 as ubuntu-18.04 is deprecated.
```release-note
NONE
```
> Automated cherry pick of #2404: bump ci runner to ubuntu-20.04 as ubuntu-18.04 is deprecated.

- test/e2e/framework/cluster.go
- test/e2e/framework/customresourcedefine.go
- test/e2e/karmadactl_test.go
add e2e for collecting cluster status after #2397 
Fixes #
cc @XiShanYongYe-Chang 
None
> [e2e] add e2e for cluster status

- hack/deploy-karmada.sh
/kind cleanup
The cffsl_vserion is updated to v1.6.2. Because the previous version has runtime error in go 1.19. And v1.6.2 can run correctly in go1.18 and 1.19.
Fixes #
[edit by @RainbowMango]
This PR address the discussion at https://github.com/karmada-io/karmada/issues/2405#issuecomment-1223495053.
And we asked the newest release by https://github.com/cloudflare/cfssl/issues/1242.
cc @liys87x @jingxiaolu 
```release-note
NONE
```
> update cfssl version to v1.6.2

- pkg/karmadactl/deinit.go
Signed-off-by: wuzhongjian <wuzhongjian_yewu@cmss.chinamobile.com>
Prompt the user to delete the default path of etcd data to deinit karmada
Fixes #
```release-note
NONE
```
> Add default path prompt for deinit to delete etcd data

- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/logs.go
- pkg/karmadactl/util/factory.go
/kind feature
At present, there are many places in karmadactl, which are building clients and factories repeatedly, such as init, get, log, exec, etc.
The purpose of this PR is to provide a unified place to get clients accessing the cluster and factories needed to access sub-clusters.
With this change, after a little refactoring, the following files can be removed in the future:
- https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/get_flags.go
- https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/config.go
- https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/options/global.go
An example of the alpha command is provided to make it easier for reviewers to understand the usage. It …
> introduce factory interface for karmadactl

- pkg/karmadactl/exec.go
- pkg/karmadactl/karmadactl.go
/kind feature
Part of #2349 
Test:
```shell
(⎈ |karmada:default)➜  karmada git:(karmadactl-exec) go run cmd/karmadactl/karmadactl.go exec -n kube-system -it -C ocp master-etcd-nodedsp01.ocp.ats.io ls /
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bin   dev  exports  lib    media  opt	root  sbin  sys  usr
boot  etc  home     lib64  mnt	  proc	run   srv   tmp  var
(⎈ |karmada:default)➜  karmada git:(karmadactl-exec) go run cmd/karmadactl/karmadactl.go exec -it -C ocp logging-eventrouter-1-k6n87 ls
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a …
```
> karmadactl exec uses factory to access member cluster

- pkg/search/proxy/cluster_proxy.go
- pkg/search/proxy/cluster_proxy_test.go
- pkg/search/proxy/store/multi_cluster_cache.go
- pkg/search/proxy/store/multi_cluster_cache_test.go
- pkg/search/proxy/store/util.go
- test/e2e/search_test.go
/kind feature
add annotation `resource.karmada.io/cached-from-cluster` to objects returned by proxy, staying the same with search.
Fixes #2463
```release-note
Objects returned by proxy will have `resource.karmada.io/cached-from-cluster` to indicate which member cluster from.
```
> add cache source annotation for objects returned by proxy

- pkg/karmadactl/addons/disable.go
- pkg/karmadactl/addons/enable.go
- pkg/karmadactl/addons/list.go
- pkg/karmadactl/apply.go
- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cordon.go
- pkg/karmadactl/deinit.go
- pkg/karmadactl/describe.go
- pkg/karmadactl/exec.go
- pkg/karmadactl/get.go
- pkg/karmadactl/join.go
- pkg/karmadactl/logs.go
- pkg/karmadactl/promote.go
- pkg/karmadactl/register.go
- pkg/karmadactl/taint.go
- pkg/karmadactl/token.go
- pkg/karmadactl/unjoin.go
/kind feature
After #2283 is merged, Flags are renamed to options. We should disable flags in useline for karmada sub command.
```release-note
NONE
```
> disable flags in use line

- pkg/search/proxy/controller.go
/kind feature
When accessing resources via proxy, metrics only records `proxying`, can't see real resources:
```
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="0.05"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="0.1"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version=" …
```
> add native resource metrics in proxy

- pkg/util/fedinformer/transform.go
- pkg/util/fedinformer/transform_test.go
/kind bug
When transformFunc ignores name and namespace of Pod，informer will only save one Pod.
Test Result After this PR:
```
nodeSummary:
readyNum: 2
totalNum: 2
....
allocated:
cpu: 1050m
memory: 340Mi
pods: "12"
```
Fixes #
```
`karmada-controller-manager`/`karmada-agent`: Fixed pod information can not be collected issue when building resource summary.
```
> Fixed pod can not be collected issue when building resource summary

- pkg/karmadactl/cmdinit/utils/examples.go
/kind bug
modify the MEMBER_CLUSTER_NAME command acquisition when registering cluster.
what happened：
```text
Karmada is installed successfully.
Register Kubernetes cluster to Karmada control plane.
Register cluster with 'Push' mode
Step 1: Use "karmadactl join" command to register the cluster to Karmada control plane. --cluster-kubeconfig is kubeconfig of the member cluster.
(In karmada)~# MEMBER_CLUSTER_NAME="cat ~/.kube/config  | grep current-context | sed 's/: /\n/g'| sed '1d'"
(In karmada)~# karmadactl --kubeconfig /etc/karmada/karmada-apiserver.config  join ${MEMBER_CLUSTER_NAME} --cluster-kubeconfig=$HOME/.kube/config
Step 2: Show members of karmada
(In karmada)~# kubectl  --kubeconfig …
```
> fix MEMBER_CLUSTER_NAME command usage

- pkg/karmadactl/describe.go
- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/logs.go
/kind feature
Part of#2349
Test:
```shell
(⎈ |karmada:default)➜  karmada git:(karmadactl-describe) go run cmd/karmadactl/karmadactl.go describe -C ocp po logging-eventrouter-1-k6n87
Name:           logging-eventrouter-1-k6n87
Namespace:      default
Priority:       0
Node:           nodedsp06.ocp.ats.io/10.23.105.10
Start Time:     Sat, 23 Jul 2022 09:41:47 +0800
Labels:         component=eventrouter
deployment=logging-eventrouter-1
deploymentconfig=logging-eventrouter
logging-infra=eventrouter
provider=openshift
Annotations:    openshift.io/deployment-config.latest-version: 1
openshift.io/deployment-config.name: logging-eventrouter …
```
> karmadactl describe uses factory to access member cluster

- pkg/util/fedinformer/transform.go
- pkg/util/fedinformer/transform_test.go
Cherry pick of #2489 on release-1.3.
#2489: fix pod lister only list a pod
```release-note
`karmada-controller-manager`/`karmada-agent`: Fixed pod information can not be collected issue when building resource summary.
```
> Automated cherry pick of #2489: fix pod lister only list a pod

- test/e2e/aggregatedapi_test.go
- test/e2e/framework/workload.go
- test/e2e/search_test.go
I found a new flaking test in master branch:
https://github.com/karmada-io/karmada/runs/8267105862?check_suite_focus=true
It still report:
```log
"nodes \"member1-control-plane\" not found",
```
We need to use `g` for assert in `gomega.Eventually(func(g gomega.Gomega) {}` block.
Fixes #
```release-note
NONE
```
/cc @ikaven1024 @RainbowMango Can you help review it?
> [E2E] fix flaking test: search proxy get node report not found

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
/kind feature
When I need to specify the related version of k8s, I mistakenly write flag as args, which causes the specified version to fail without any error and install the default v1.24.2 kube-controller-manager.
I have browsed the source code of relevant parts of init, and I think args can be disabled to ensure correct input.
for example:
```shell
karmadactl init --kubeconfig ./kind-multi-node2/config --karmada-apiserver-image=k8s.gcr.io/kube-apiserver:v1.18.20 karmada-kube-controller-manager-image=k8s.gcr.io/kube-controller-manager:v1.18.20
```
Fixes #
```release-note
karmadactl prohibit input …
```
> cmdinit prohibit passing in additional parameters

- pkg/karmadactl/cmdinit/karmada/rbac.go
/kind bug
I just found that `service_export_controller` is used by `karmada-agent`, it need to create work to collect `endpointSlices`, so the `karmada-agent` need to permission to create `Works`.
```
I0914 08:35:33.330001       1 service_export_controller.go:150] Begin to sync EndpointSlice default/dc-demo-ff75r.
E0914 08:35:33.411613       1 work.go:64] Failed to create/update work karmada-es-member140/dc-demo-ff75r-78db6c96f5. Error: works.work.karmada.io is forbidden: User "system:node:member140" cannot create resource "works" in API group "work.karmada.io" in the namespace "karmada-es-member140"
E0914 08:35:33.411669       1 service_export_controller.go:325] Failed to …
```
> Fix that the ServiceExport can't be reported to control plane by karmada-agent

- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/utils/ip.go
- pkg/karmadactl/cmdinit/utils/ip_test.go
Fixes #
If k8s is in ipv6 mode, then the apiserverUrl of karmada should in `http://[ipv6_address]:32443`  format.
```release-note
NONE
```
> fix karmadactl init pending when k8s is in ipv6 mode

- pkg/karmadactl/cmdinit/karmada/rbac.go
Cherry pick of #2515 on release-1.3.
#2515: Fix that the ServiceExport can't be reported to control plane
```release-note
`karmada-agent`: Fixed `ServiceExport` controller can not report `endpointSlices` issue(due to miss `create` permission)
```
> Automated cherry pick of #2515: Fix that the ServiceExport can't be reported to control plane

- pkg/controllers/unifiedauth/unified_auth_controller.go
- pkg/util/rbac.go
- test/e2e/aggregatedapi_test.go
/kind bug
As talked in https://github.com/karmada-io/karmada/issues/2480#issuecomment-1240372168 and #2495, we need to use cluster impersonate secret ref in `unified-auth-controller` when generating ClusterRoleBinding. As a result, we can access subCluster resources through the `aggregate-apiserver`  when the cluster uses different namespaces to store secrets.
Fixes #2495 
```release-note
karmada-controller-manager: use cluster secret ref namespace in unified-auth-controller when generate ClusterRoleBinding
```
> Use Cluster secret ref namespace in unified-auth-controller when generate ClusterRoleBinding

- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/utils/ip.go
- pkg/karmadactl/cmdinit/utils/ip_test.go
Cherry pick of #2450 on release-1.3.
#2450: fix karmadactl init pending when k8s is in ipv6 mode
```release-note
`karmadactl`: Fixed `init` can not honor IPV6 address issue when generating kubeconfig file.
```
> Automated cherry pick of #2450: fix karmadactl init pending when k8s is in ipv6 mode

- pkg/controllers/unifiedauth/unified_auth_controller.go
- pkg/util/rbac.go
- test/e2e/aggregatedapi_test.go
Cherry pick of #2516 on release-1.3.
#2516: Use Cluster secret ref namespace in
```release-note
karmada-controller-manager: use cluster secret ref namespace in unified-auth-controller when generate ClusterRoleBinding
```
> Automated cherry pick of #2516: Use Cluster secret ref namespace in

- hack/util.sh
Signed-off-by: mrningyang <mrningyangning@didiglobal.com>
/kind bug
Fix bug of hack/util.sh, which will lead to failure when run hack/local-up-karmada.sh with environment CHINA_MAINLAND=true
Fixes #2521
Just see #2521
```NONE
```
> fix a gramma that is not accepted by GNU `sed` command

- hack/local-up-karmada.sh
/kind bug
If users want to set the cluster name by themselves like
```
xxx@ecs-3fa1 [03:13:06 PM] [~/workspace/git/karmada] [master *]
-> % tail ~/.zshrc
export PATH=$PATH:/home/jw/workspace/sf:/usr/local/go/bin/
export HOST_CLUSTER_NAME=jw-karmada-host
export MEMBER_CLUSTER_1_NAME=jw-member1-push
export MEMBER_CLUSTER_2_NAME=jw-member2-push
export PULL_MODE_CLUSTER_NAME=jw-member3-pull
export KIND_LOG_FILE=${HOME}/workspace/log/karmada
```
It will have errors:
Bugs in script to set clusters name by users
none
```release-note
none
```
> Add user-specific cluster name support

- pkg/karmadactl/cmdinit/kubernetes/deployments.go
/kind bug
Now karmada-cntoller-manager don't need sa to connect apiserver, so delete it
related with: https://github.com/karmada-io/karmada/pull/2523
related with: https://github.com/karmada-io/karmada/pull/2523
```release-note
none
```
> Delete service-account for karmada-controller-manager

- test/e2e/failover_test.go
- test/e2e/karmadactl_test.go
- test/e2e/porting_workloads_test.go
- test/e2e/rescheduling_test.go
- test/e2e/resource_test.go
- test/e2e/scheduling_test.go
/kind cleanup
Using assertions in `wait.PollImmediate` breaks the cyclic waiting process, resulting in failure.
Meanwhile, as the error message suggests:
```
When you, or your assertion library, calls Ginkgo's Fail(),
Ginkgo panics to prevent subsequent assertions from running.
Normally Ginkgo rescues this panic so you shouldn't see it.
However, if you make an assertion in a goroutine, Ginkgo can't capture the
panic.
To circumvent this, you should call
defer GinkgoRecover()
at the top of the goroutine that caused this panic.
Alternatively, you may have made an assertion outside of a Ginkgo
leaf node (e.g. in a container node or some out-of-band function) …
```
> [E2E] replace gomeme.Eventually with wait when logic has assertions

- pkg/karmadactl/deinit.go
Signed-off-by: helen <helenfrank@protonmail.com>
/kind feature
`deinit -h` need print options
Fixes #
A novice who has just come into contact with karmada thinks it is very important for `deinit -h` to have options.
it`s me ^-^
```release-note
`karmadactl`: Fixed options of `deinit` can not be shown issue.
```
> `karmadactl`: Fixed options of `deinit` can not be shown issue.

- .github/workflows/ci.yml
- artifacts/kindClusterConfig/general-config.yaml
- artifacts/kindClusterConfig/member1.yaml
- artifacts/kindClusterConfig/member2.yaml
- hack/deploy-karmada.sh
- hack/local-up-karmada.sh
- hack/post-run-e2e.sh
- hack/pre-run-e2e.sh
Update E2E environment to k8s v1.25
Add test k8s 1.25 test
none
tests:
```shell
jw@ecs-3fa1 [05:23:49 PM] [~/workspace/git/karmada-diff/karmada-update-kind] [update-kind-to-1.25 *]
-> % docker ps
CONTAINER ID   IMAGE                  COMMAND                  CREATED          STATUS          PORTS                       NAMES
fbddb01e5fc7   kindest/node:v1.25.0   "/usr/local/bin/entr…"   13 minutes ago   Up 12 minutes   127.0.0.1:35387->6443/tcp   jw-member3-pull-control-plane
aa7a0a51ab49   kindest/node:v1.25.0   "/usr/local/bin/entr…"   13 minutes ago   Up 12 minutes   127.0.0.1:34003->6443/tcp …
```
>  Update kind to 0.15 to support deploy k8s 1.25 environment

- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
/kind bug
This PR cause following error: https://github.com/karmada-io/karmada/pull/2297
```
jw@ecs-3fa1 [02:58:20 PM] [~/workspace/git/karmada-diff/karmada] [release-1.3]
-> % kubectl karmada init  --karmada-data=/home/jw/workspace/karmada_data
I0920 14:58:26.229852 3193825 deploy.go:145] kubeconfig file: /home/jw/.kube/karmada.config, kubernetes: https://192.168.1.237:42213
I0920 14:58:26.244413 3193825 deploy.go:165] karmada apiserver ip: [172.18.0.6]
I0920 14:58:26.620751 3193825 cert.go:229] Generate ca certificate success.
I0920 14:58:26.845036 3193825 cert.go:229] Generate karmada certificate success.
I0920 14:58:27.031043 3193825 cert.go:229] Generate apiserver …
```
> karmadactl: Fix karmada-data directory not inilization isssue

- go.mod
- go.sum
- vendor/gopkg.in/yaml.v3/decode.go
- vendor/gopkg.in/yaml.v3/parserc.go
- vendor/modules.txt
- vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
- vendor/sigs.k8s.io/kind/pkg/apis/config/v1alpha4/types.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/create/actions/waitforready/waitforready.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeadm/config.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/kubeconfig/internal/kubeconfig/paths.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/loadbalancer/const.go
- vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provision.go
- vendor/sigs.k8s.io/kind/pkg/cluster/nodeutils/util.go
- vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go
- vendor/sigs.k8s.io/kind/pkg/internal/apis/config/types.go
/kind cleanup
This PR updates kind from v0.14.0 to v0.15.0, which will be used to [create kuberentes v1.25 clusters in E2E](https://github.com/karmada-io/karmada/blob/ab889889faa84b5a1c1ad89241862b642b3cfb4c/test/e2e/suite_test.go#L168).
Fixes #
```release-note
NONE
```
> Update kind dependency to get ready for testing against kubernetes v1.25

- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
Cherry pick of #2548 on release-1.3.
#2548: Fix bugs about karmada-data dir lost
```release-note
`karmadactl`: Fixed `--karmada-data` directory not initialization issue in `init` command.
```
> Automated cherry pick of #2548: Fix bugs about karmada-data dir lost

- hack/post-run-e2e.sh
- hack/pre-run-e2e.sh
Signed-off-by: jwcesign [jiangwei115@huawei.com](mailto:jiangwei115@huawei.com)
There is a bug in metallb: https://github.com/metallb/metallb/issues/1597
Disable the webhook-mode, also it has not effects for our test case.
There is a bug in metallb: https://github.com/metallb/metallb/issues/1597
Disable the webhook-mode, also it has not effects for our test case.
none
```release-note
none
```
> Disable webhook-mode for metallb

- pkg/karmadactl/deinit.go
Cherry pick of #2540 on release-1.2.
#2540: deinit help fix
```release-note
`karmadactl`: Fixed options of `deinit` can not be shown issue.
```
> Automated cherry pick of #2540: deinit help fix

- pkg/util/names/names.go
- pkg/util/names/names_test.go
- test/e2e/clusterpropagationpolicy_test.go
- test/e2e/framework/rbac.go
- test/e2e/propagationpolicy_test.go
- test/e2e/suite_test.go
- test/helper/resource.go
/kind bug
/kind feature
As talked about in #2392, when we propagate RBAC resources, whose names contain colon characters, it will report err.
The reason is that colons are allowed in names in validations for these resources, but this is different from name validations for CRD resources:
https://github.com/kubernetes/kubernetes/blob/f0823c0f59d6ea8e2ad0dc4e3fe0f2b396c9185f/pkg/apis/rbac/validation/validation.go#L124
https://github.com/kubernetes/kubernetes/blob/f0823c0f59d6ea8e2ad0dc4e3fe0f2b396c9185f/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/validator.go#L60
Fixes #2392  …
> replace colon with point in the rbac resource name

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/node.go
/kind feature
Fixes https://github.com/karmada-io/karmada/issues/2537
```release-note
`karmadactl`: Introduced `--karmada-apiserver-advertise-address` flag to specify Karmada APIserver's address to the `init` sub-command.
```
> introduce karmada-apiserver-advertise-address

- pkg/detector/detector.go
- pkg/util/selector.go
/kind feature
If more than one PP matches the object, we shuold choose the most suitable one. However, now we select PP by alphabetical order, it does not make any sense.
There are 4 types of implicit priority here, ordered by descend.
1. Name: ResourceSelector contains object Name and matches the object.
2. LabelSelector: ResourceSelector contains a LabelSelector and matches the object.
3. All: ResourceSelector has no Name or LabelSelector, which selects all target objects in the namespace.
4. MisMatch: ResourceSelector does not match the object.
For example:
```yaml
metadata:
name: nginx-propagation-1
spec: …
```
> add implicit priority for PP

- hack/post-run-e2e.sh
- hack/pre-run-e2e.sh
- pkg/karmadactl/join.go
- pkg/karmadactl/register.go
- pkg/karmadactl/unjoin.go
/kind cleanup
When we have the following command in mind, we will have the following printed help information. The printed prompt has `karamada` in it, but it should be `karmada`, and this pr corrects all positions involved in that misspelling.
`karmadactl join -h` or `karmadactl unjoin -h` or `karmadactl register -h`
```shell
$ karmadactl join -h
Join registers a cluster to control plane.
Examples:
specified, take the cluster name as the context
karmadactl join CLUSTER_NAME --cluster-kubeconfig=<KUBECONFIG>
```
Fixes #
```release-note
NONE
```
> karmadactl: modify the wrong noun for karmadactl

- .golangci.yml
- hack/verify-staticcheck.sh
/kind cleanup
This PR updates golangci-lint, and deprecates some linters:
```
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
Fixes #
Following warnings raised that should be solved or ignored before this PR.
```
pkg/sharedcli/profileflag/profileflag.go:42:14: G114: Use of …
```
> Update golangci-lint from 1.46.2 to 1.49.0

- hack/post-run-e2e.sh
- hack/pre-run-e2e.sh
- pkg/karmadactl/join.go
- pkg/karmadactl/unjoin.go
Cherry pick of #2608 on release-1.1.
#2608: Modify the wrong noun for karmadactl
```release-note
NONE(fixed typo in CLI usage)
```
> Automated cherry pick of #2608: Modify the wrong noun for karmadactl

- charts/karmada/templates/_helpers.tpl
- charts/karmada/templates/karmada-controller-manager.yaml
- charts/karmada/values.yaml
/kind feature
we want to use the feature gate `Propagate dependent`, we have not a swith to open the feature.
Fixes #
please correct me if not
```release-note
NONE
```
> chart: support controller manager feature gate

- pkg/karmadactl/cordon.go
/kind feature
In the current version, multiple cluster name should not be passed in.
Fixes #
```release-note
NONE
```
> Add args greater than one

- api/openapi-spec/swagger.json
- charts/karmada/_crds/bases/policy.karmada.io_clusterpropagationpolicies.yaml
- charts/karmada/_crds/bases/policy.karmada.io_propagationpolicies.yaml
- pkg/apis/policy/v1alpha1/propagation_types.go
- pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
People might be confused about why the behavior of `ResourceSelectors` is different between `PropagationPolicy` and `OverridePolicy`.(see #2618)
This PR adds a clear comment on it to eliminate ambiguity according to [the discussion](https://github.com/karmada-io/karmada/pull/422#issuecomment-858222351).
Fixes #
With this patch, when applying with an empty resource selector as follow:
```bash
-bash-4.2# cat samples/nginx/propagationpolicy.yaml 
metadata:
spec:
resourceSelectors: []
...
```
An error would raise up:
```bash
The PropagationPolicy …
```
> Update comments for ResourceSelectors in PropagationPolicy to eliminate ambiguity

- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/framework/interface.go
- pkg/scheduler/framework/plugins/apienablement/api_enablement.go
- pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity.go
- pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint.go
- pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go
- pkg/scheduler/framework/types.go
/kind feature
Add scheduling diagnosis when no clusters fit. Here is the example.
Warning  ScheduleBindingFailed   2s (x10 over 4s)  karmada-scheduler  0/3 clusters are available: 1 cluster(s) had untolerated taint {dedicated: special-user}, 2 cluster(s) didn't have the API resource.
Fixes #
```release-note
add scheduling diagnosis
```
> add scheduling diagnosis

- .github/workflows/ci.yml
- .github/workflows/dockerhub-latest-image.yml
- .github/workflows/dockerhub-released-image.yml
- .github/workflows/fossa.yml
- .github/workflows/lint-chart.yaml
- .github/workflows/release.yml
- .github/workflows/swr-latest-image.yml
- .github/workflows/swr-released-image.yml
According to the [GitHub Action announcement](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/), all actions begin running on Node16 since the Node12 has been out of support.
This PR updates actions to support Node16:
- actions/checkout
- actions/setup-go
- docker/setup-qemu-action
- docker/setup-buildx-action
- docker/login-action
- actions/upload-artifact
Fixes #
The [arduino/setup-protoc](https://github.com/karmada-io/karmada/blob/362f77ad13bd448242b19651e61a18ac01c44670/.github/workflows/ci.yml#L42) also needs an update, but [it ](https://github.com/arduino/setup-protoc) doesn't …
> Bump GitHub Actions to run on Node16

- pkg/karmadactl/cmdinit/kubernetes/node.go
Signed-off-by: Lan Liang <gcslyp@gmail.com>
/kind bug
Now, it just panic when can not found that can be scheduled for AddNodeSelectorLabels. Add  return error and talk user what happen.
```
[root@watchdog karmadactl]# go run karmadactl.go  --kubeconfig config5621 init --kube-image-registry=lank8s.cn
I1004 02:29:11.960379    4001 deploy.go:154] kubeconfig file: config5621, kubernetes: https://192.168.56.21:6443
panic: assignment to entry in nil map
```
After PR :
```
[root@watchdog karmadactl]# go run karmadactl.go  --kubeconfig config5621 init --kube-image-registry=lank8s.cn
I1004 03:05:15.460215    5110 deploy.go:154] kubeconfig file: config5621, kubernetes: https://192.168.56.21:6443
error: have no node can be …
```
> raise an error when there is no healthy nodes for etcd installation

- pkg/karmadactl/addons/init/global.go
/kind cleanup
This cluster is used on the enable and disable command lines, and the description here obviously does not match the actual description of the cluster
```release-note
NONE
```
> addons enable cluster flag usage description wrong

- pkg/karmadactl/cordon.go
- pkg/karmadactl/karmadactl.go
- test/e2e/karmadactl_test.go
Signed-off-by: helen <helenfrank@protonmail.com>
/kind feature
Part of [#2349](https://github.com/karmada-io/karmada/issues/2349)
Test
```shell
kind-multi-node1 cluster cordoned
kind-multi-node1 cluster already cordoned
kind-multi-node1 cluster uncordoned
kind-multi-node1 cluster already uncordoned
```
```release-note
NONE
```
> karmadactl cordon&uncordon uses factory to access cluster

- charts/karmada/templates/karmada-cert.yaml
- charts/karmada/templates/post-install-job.yaml
- charts/karmada/values.yaml
fix use custom certs lead to post-install-job failed and kube-controller-manager crash by missing /etc/karmada/pki/server-ca.key
/kind bug
helm install 使用自定义证书
- post-install-job 运行失败，`kubectl apply -f /static-resources --kubeconfig /etc/kubeconfig` 因为yaml格式问题运行不了,导致安装失败
- kube-controller-manager 运行时报错no such file缺失`/etc/karmada/pki/server-ca.key `，custom模式没有传入，auto是有的
Fixes https://github.com/karmada-io/karmada/issues/2628#issuecomment-1277002908  提到的问题
```release-note
NONE
```
> helm chart support configuration for ca key

- hack/install-cli.sh
/kind feature
Add scripts to support one-click installation of cli tools.
```
curl -s https://raw.githubusercontent.com/Poor12/karmada/add-scripts-to-install-karmadactl/hack/install.sh | sudo bash
[INFO]  Downloading metadata https://api.github.com/repos/karmada-io/karmada/releases/latest
[INFO]  Using 1.3.0 as release
[INFO]  Downloading hash https://github.com/karmada-io/karmada/releases/download/v1.3.0/karmadactl-linux-amd64.tgz.sha256
[INFO]  Downloading binary https://github.com/karmada-io/karmada/releases/download/v1.3.0/karmadactl-linux-amd64.tgz
[INFO]  Verifying binary download
[INFO]  Installing karmadactl to /usr/local/bin/karmadactl
```
**Which issue(s) this PR …
> Add scripts to install cli tools

- cmd/descheduler/app/options/options.go
- cmd/scheduler/app/options/options.go
- cmd/scheduler/app/scheduler.go
- pkg/descheduler/descheduler.go
- pkg/estimator/client/cache.go
- pkg/scheduler/scheduler.go
- pkg/util/names/names.go
- pkg/util/names/names_test.go
/kind feature
Part of #2526 
```release-note
`karmada-scheduler`/`karmada-scheduler-descheduler`: Introduced `--scheduler-estimator-service-prefix` flag for discovery estimators.
```
> scheduler & descheduler introduce scheduler-estimator-service-prefix flag

- pkg/scheduler/cache/cache.go
- pkg/scheduler/cache/snapshot.go
- pkg/scheduler/core/generic_scheduler.go
Signed-off-by: mathlsj <mathlsj@outlook.com>
Fix clusterInfoSnapshot may be nil it will caused painc
Fixes # 
```release-note
```
> Fix clusterInfoSnapshot may be nil it will caused painc

- hack/verify-all.sh
/kind cleanup
(1) When run `make verify` in command line, there is no indication what verify script is running.
(2) The current running sequence is not optimized. 
I often spend 3 minutes running`verify-codegen.sh`, only find `verify-staticcheck.sh` or `verify-import-aliases.sh` fail. `verify-staticcheck.sh` only needs 5 seconds to execute. `verify-import-aliases.sh` only needs 1.5 seconds to execute.
I reorder them based on two factors:
1. Less Execution time item should be executed first.
2. More likely to fail item should be executed first.
Every script execution time measured by `time` command:
| script                   | time      |
| …
> reorder `make verify`

- pkg/karmadactl/get.go
- pkg/karmadactl/karmadactl.go
/kind feature
Fixes #
Part of [#2349](https://github.com/karmada-io/karmada/issues/2349)
Test
```shell
go run ./cmd/karmadactl/karmadactl.go -kubeconfig /etc/karmada/karmada-apiserver.config  -n test1 -C kind-multi-node1 get po                                                                         
NAME                      CLUSTER            READY   STATUS    RESTARTS   AGE
nginx1-56db585f94-lsv8b   kind-multi-node1   1/1     Running   0          5d13h
```
```release-note
NONE
```
> karmadactl get uses factory to access cluster

- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/token.go
/kind feature
Part of #2349 
/cc @carlory @helen-frank 
```release-note
NONE
```
> karmadactl token uses factory to access cluster

- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/taint.go
/kind feature
Fixes #
Part of[#2349](https://github.com/karmada-io/karmada/issues/2349)
Test
```shell
go run ./cmd/karmadactl/karmadactl.go --kubeconfig /etc/karmada/karmada-apiserver.config taint clusters kind-multi-node1 bar:NoSchedule
cluster/kind-multi-node1 tainted
kubectl --kubeconfig /etc/karmada/karmada-apiserver.config get clusters kind-multi-node1 -oyaml | grep -C 5 taints                                         
namespace: karmada-cluster
secretRef:
name: kind-multi-node1
namespace: karmada-cluster
syncMode: Push
taints:
- effect: NoSchedule
key: bar
status:
apiEnablements:
- groupVersion: admissionregistration.k8s.io/v1
go run ./cmd/karmadactl/karmadactl.go --kubeconfig …
```
> karmadactl taint uses factory to access cluster

- pkg/scheduler/core/generic_scheduler.go
- pkg/scheduler/framework/interface.go
- pkg/scheduler/framework/runtime/framework.go
- pkg/scheduler/framework/runtime/metrics_recorder.go
- pkg/scheduler/metrics/metrics.go
/kind feature
Add metrics_recorder for scheduler framework so we can measure the performance of each scheduler plugin.
```
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0001"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0002"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0004"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0008"} 1
karmada_scheduler_framework_extension_point_duration_seconds_buc …
```
> Add metrics_recorder for scheduler framework

- pkg/controllers/unifiedauth/unified_auth_controller.go
Do nil check before using cluster ImpersonatorSecretRef
Fixes #2674
None
```release-note
- `karmada-controller-manager`: Fixed the panic when cluster ImpersonatorSecretRef is nil.
```
> `karmada-controller-manager`: Fixed the panic when cluster ImpersonatorSecretRef is nil.

- cmd/agent/app/agent.go
- cmd/agent/app/options/options.go
- pkg/controllers/certificate/cert_rotation_controller.go
- pkg/controllers/context/context.go
- pkg/karmadactl/register.go
/kind feature
Part of #2282 
```release-note
karmada-agent: introduce auto certificate rotation function
karmadactl: introduce --enable-cert-rotation option to register command
```
> Implement auto certificate rotation function for karmada-agent

- pkg/controllers/unifiedauth/unified_auth_controller.go
Cherry pick of #2675 on release-1.3.
#2675: check if cluster ImpersonatorSecretRef is nil before using it
```release-note
`karmada-controller-manager`: Fixed the panic when cluster ImpersonatorSecretRef is nil.
```
> Automated cherry pick of #2675: check if cluster ImpersonatorSecretRef is nil before using it

- pkg/apis/policy/v1alpha1/well_known_constants.go
- pkg/controllers/namespace/namespace_sync_controller.go
/kind feature
Referring to: https://github.com/karmada-io/karmada/issues/2525
Customers may not want to sync some specific namespace
Fixes  #https://github.com/karmada-io/karmada/issues/2525
```release-note
Introduced resource label `namespace.karmada.io/skip-auto-propagation: "true"` which can label the namespaces that should be skipped from auto propagation.
```
> Add label "namespace.karmada.io/skip-auto-propagation" to control whether to propagate ns to member clusters

- .github/workflows/lint-chart.yaml
- charts/karmada/templates/karmada-apiserver.yaml
Recently chart-lint sometimes failed, such as https://github.com/karmada-io/karmada/actions/runs/3350829274/jobs/5551890843.
There are mainly two reasons:
1. Timeout. The installation of the release could not be completed within the given time(400s).
2. Post-install job failed. This is mainly because karmada-apiserver is always not ready due to readinessProbe. The job will install the crd but it cannot visit karmada-apiserver. After backoffLimit, it will fail in the end.
Fixes #
None
> fix chart lint failure

- pkg/karmadactl/cmdinit/kubernetes/node.go
/kind feature
if the k8s cluster is v1.24, we can not use the previous label to select  master node.
Fixes #
please correct me if not.
```release-note
NONE
```
> karmadactl are compatible with v1.24 master node label

- pkg/search/proxy/controller_test.go
/kind cleanup
The original test used `fmt.Printf` without `\n` to print log, this will cause stdout be polluted. Polluted stdout will cause GoLand parse test result failure.
This is similar to this issue: <https://github.com/karmada-io/karmada/issues/2671>
```release-note
NONE
```
> Fix Test Not Success in GoLand

- pkg/util/helper/predicate.go
- pkg/util/helper/predicate_test.go
/kind cleanup
When we predicate for update event, we shall predicate both the old and new object.
For example: https://github.com/karmada-io/karmada/blob/12ed0204436291c32645fa2148a041e609f38213/pkg/util/helper/predicate.go#L101-L107
When a work is updated to add `Suppressed` label, this predication will filter out this event, and client will never known the work is updated.
Part of #2579
```release-note
NONE
```
> improve predicate.go

- README.md
/kind cleanup
The kubernetes compatibility version of Karmada declared in the document is inconsistent with the `kubeVersion` set in chart:https://github.com/karmada-io/karmada/blob/master/charts/karmada/Chart.yaml#L18
Fixes #
```release-note
```
> modify README.md for Kubernetes compatibility

- pkg/controllers/cluster/cluster_controller.go
/kind cleanup
optimize error message for `collectIDForClusterObjectIfNeeded`, It's clear to konw which cluster failed to update cluster ID.
Fixes #
```release-note
NONE
```
> optimize error message for collectClusterID

- pkg/karmadactl/token.go
/kind bug
Fix that setting `--kubeconfig` and `--karmada-context` flags is invalid.
Fixes #
```release-note
NONE
```
> Fix karmadactl token that can't set `--kubeconfig`

- pkg/detector/detector.go
- pkg/detector/policy.go
/kind bug
Disable the preemption matching of pp/cpp priority.
Fixes #2727 
```release-note
karmada-controller-manager: Disable the preemption matching of pp/cpp priority.
```
> Disable the preemption matching of pp/cpp priority

- pkg/detector/detector.go
- pkg/detector/policy.go
Cherry pick of #2734 on release-1.3.
#2734: Disable the preemption matching of pp/cpp priority
```release-note
karmada-controller-manager: Disable the preemption matching of pp/cpp priority.
```
> Automated cherry pick of #2734: Disable the preemption matching of pp/cpp priority

- .github/workflows/ci.yml
/kind cleanup
There is an open issue on `CodeCov` that would fail when uploading coverage reports.
As per https://github.com/codecov/codecov-action/issues/598#issuecomment-1302610539, we can improve it by providing an upload token.
This PR does:
1. Prevent code coverage upload from the forked repo
2. Introduce upload token to increase successful uploads
Fixes #
According to the test result, the upload coverage step could be skipped, see:
https://github.com/RainbowMango/karmada/actions/runs/3390765450/jobs/5635308741
```release-note
NONE
```
> Increase codecov successful uploads

- pkg/descheduler/descheduler.go
/kind cleanup
```
Events:
Type    Reason                    Age                    From                 Message
----    ------                    ----                   ----                 -------
Normal  DescheduleBindingSucceed  2m54s (x8 over 119m)   karmada-descheduler  , 1 total descheduled replica(s)Binding has been descheduled, 1 replica(s) in cluster(member1)
(⎈ |karmada-apiserver:default)➜  ~ kubectl describe  rb nginx-deployment
```
Fixes #
```release-note
NONE
```
> Make event messages more readable

- .github/workflows/release.yml
/kind cleanup
Since [krew ](https://github.com/kubernetes-sigs/krew) only caches the `latest` release, so we don't need to update it for v1.2.x releases. Otherwise, it will open an invalid PR, like https://github.com/kubernetes-sigs/krew-index/pull/2657.
Fixes #
```release-note
NONE
```
> Stop update krew for release 1.2.x

- .github/workflows/release.yml
/kind cleanup
Since [krew ](https://github.com/kubernetes-sigs/krew)only caches the latest release, so we don't need to update it for v1.1.x releases. Otherwise, it will open an invalid PR, like https://github.com/kubernetes-sigs/krew-index/pull/2657.
Fixes #2743
> Stop update krew for release 1.1.x

- pkg/resourceinterpreter/configurableinterpreter/configmanager/accessor.go
- pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
- pkg/resourceinterpreter/configurableinterpreter/configurable.go
- pkg/resourceinterpreter/interpreter.go
Signed-off-by: zhangyukun <38148677+jameszhangyukun@users.noreply.github.com>
/kind feature
add  framework cache and reorganize configurations Resource Interpreter
Part of #2371 
Fixes #
```release-note
NONE (Part feature)
```
> Resource Interpreter Framework cache and reorganize configurations

- pkg/apis/cluster/v1alpha1/events.go
- pkg/controllers/cluster/cluster_controller.go
/kind feature
Add the CreateExecutionSpaceSucceed and RemoveExecutionSpaceSucceed event.
```
Events:
Type    Reason                       Age   From                Message
----    ------                       ----  ----                -------
Normal  CreateExecutionSpaceSucceed  8s    cluster-controller  Created execution space(karmada-es-member1) for cluster(member1).
Normal  TaintClusterByStatusSucceed  8s    cluster-controller  Taint cluster by status succeed: add([{cluster.karmada.io/not-ready  NoSchedule <nil>}]), remove([]).
Normal  TaintClusterByStatusSucceed  8s    cluster-controller  Taint cluster by status succeed: add([]), remove([{cluster.karmada.io/not-ready …
```
> Add the CreateExecutionSpaceSucceed and RemoveExecutionSpaceSucceed event

- pkg/karmadactl/cordon.go
/kind feature
karmadactl uncordon add dryrun
Fixes #
Test
```shell
Mark cluster as schedulable.
Examples:
karmadactl uncordon foo
Options:
--dry-run=false:
Run the command in dry-run mode, without making any server requests.
--karmada-context='':
The name of the kubeconfig context to use
-n, --namespace='':
If present, the namespace scope for this CLI request
Usage:
karmadactl uncordon CLUSTER [options]
Use "karmadactl options" for a list of global command-line options (applies to all commands).
```
```release-note
karmadactl uncordon add dryrun
```
> karmadactl uncordon add dryrun

- cmd/controller-manager/app/controllermanager.go
- pkg/apis/work/v1alpha2/events.go
- pkg/detector/detector.go
- pkg/util/overridemanager/overridemanager.go
/kind feature
Add override policy apply event. Now users can get events from workloads to know whether override policy is applied succeessfully.
```
Events:
Type     Reason                      Age                    From                  Message
----     ------                      ----                   ----                  -------
Normal   SyncWorkSucceed             3m57s                  binding-controller    Sync work of resourceBinding(default/nginx-deployment) successful.
Normal   AggregateStatusSucceed      3m57s                  binding-controller    Update resourceBinding(default/nginx-deployment) with AggregatedStatus successfully.
Warning  SyncFailed …
```
> Add override policy apply event

- pkg/controllers/binding/cluster_resource_binding_controller.go
Clean up before https://github.com/karmada-io/karmada/issues/2695
```release-note
NONE
```
Overridepolicy will never work for cluster_resource_binding_controller
Reason :
```1:  cluster_resouce_binding will only be created for cluster-scoped resources in detector_controller```
```2:  overridepolicy will only work for namespace-scoped resources in override_manager```
```So cluster_resource_binding_controller do not need to watch the event for overridepolicy```
> remove overridepolicy trigger on cluster_resource_binding_controller

- pkg/detector/detector.go
- pkg/detector/policy.go
- pkg/util/helper/binding.go
- pkg/util/helper/binding_test.go
- pkg/util/helper/policy.go
- pkg/util/label.go
- pkg/util/label_test.go
- pkg/webhook/clusterpropagationpolicy/validating.go
- pkg/webhook/propagationpolicy/validating.go
- test/e2e/clusterpropagationpolicy_test.go
- test/e2e/framework/clusterpropagationpolicy.go
- test/e2e/framework/deployment.go
- test/e2e/framework/propagationpolicy.go
- test/e2e/framework/rbac.go
- test/e2e/propagationpolicy_test.go
/kind feature
Allow users to update the `.spec.resourceSelectors` filed of `PropagationPolicy/ClusterPropagationPolicy`.
Fixes #
```release-note
karmada-controller-manager: allow users to update the `.spec.resourceSelectors` filed of `PropagationPolicy/ClusterPropagationPolicy`.
```
> allow to update the resourceSelector of PropagationPolicy/ClusterPropagationPolicy

- pkg/karmadactl/apply.go
- pkg/karmadactl/cordon.go
- pkg/karmadactl/describe.go
- pkg/karmadactl/exec.go
- pkg/karmadactl/get.go
- pkg/karmadactl/join.go
- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/logs.go
- pkg/karmadactl/options/global.go
- pkg/karmadactl/promote.go
- pkg/karmadactl/taint.go
- pkg/karmadactl/token.go
- pkg/karmadactl/unjoin.go
/kind feature
These code comes multiple times, we may extract them as one function.
Fixes #
Port #2611 
```release-note
NONE
```
> New Factory global flags merge function

- pkg/karmadactl/cmdinit/utils/format.go
- pkg/webhook/interpreter/http.go
/kind bug
`io.ReadAll` has no restrictions on memory request, which can easily lead to DoS attacks. Add limitReader can limit the memory.
Fixes #
```
`Security`: Add limitReader to `io.ReadAll` which could limit the memory request and avoid DoS attacks.
```
> Add limitReader to io.ReadAll

- pkg/clusterdiscovery/clusterapi/clusterapi.go
- pkg/karmadactl/addons/addons.go
- pkg/karmadactl/apply/apply.go
- pkg/karmadactl/cordon/cordon.go
- pkg/karmadactl/deinit/deinit.go
- pkg/karmadactl/describe/describe.go
- pkg/karmadactl/exec/exec.go
- pkg/karmadactl/get/get.go
- pkg/karmadactl/join/join.go
- pkg/karmadactl/karmadactl.go
- pkg/karmadactl/logs/logs.go
- pkg/karmadactl/promote/promote.go
- pkg/karmadactl/register/register.go
- pkg/karmadactl/taint/taint.go
- pkg/karmadactl/taint/taint_test.go
- pkg/karmadactl/token/token.go
- pkg/karmadactl/unjoin/unjoin.go
- test/e2e/aggregatedapi_test.go
- test/e2e/federatedresourcequota_test.go
- test/e2e/karmadactl_test.go
- test/e2e/namespace_test.go
- test/e2e/rescheduling_test.go
/kind cleanup
Package subcommands of karmadactl to make it clearer, and it is easy to add UT for subcommands.
Fixes #
```release-note
NONE
```
> Package subcommands of karmadactl to make it clearer

- pkg/karmadactl/cmdinit/utils/format.go
- pkg/webhook/interpreter/http.go
Cherry pick of #2765 on release-1.3.
#2765: Add limitReader to io.ReadAll
```release-note
`Security`: Add limitReader to `io.ReadAll` which could limit the memory request and avoid DoS attacks.
```
> Automated cherry pick of #2765: Add limitReader to io.ReadAll

- pkg/apis/work/v1alpha1/events.go
- pkg/controllers/status/workstatus_controller.go
/kind feature
Add reflectStatusToWork and InterpretHealth event to `work` object.
```
Events:
Type    Reason                      Age                    From                    Message
----    ------                      ----                   ----                    -------
Normal  SyncSucceed                 6m28s                  execution-controller    Sync work (nginx-687f7fb96f) to cluster(member1) successful.
Normal  InterpretHealthSucceed      6m27s (x3 over 6m28s)  work-status-controller  Interpret health of object(Deployment/default/nginx) as unhealthy.
Normal  ReflectStatusToWorkSucceed  6m21s (x6 over 6m28s)  work-status-controller  Reflect status for …
```
> Add reflectStatusToWork and InterpretHealth event

- charts/karmada/README.md
- charts/karmada/templates/karmada-descheduler.yaml
/kind bug
the descheduler missing name suffix after install with helm.
Fixes #
```release-note
NONE
```
> chart: add descheduler name suffix of chart deployment manifest

- pkg/controllers/binding/binding_controller.go
- pkg/controllers/binding/cluster_resource_binding_controller.go
- test/e2e/clusteroverridepolicy_test.go
- test/e2e/overridepolicy_test.go
/kind bug
Fixes https://github.com/karmada-io/karmada/issues/2695
```release-note
`karmada-controller-manager`: Fix clusterOverridePolicy and overridePolicy with nil resource selector could not work
```
> Fix overridepolicy with nil resource selector could not work

- pkg/controllers/binding/binding_controller.go
- pkg/controllers/binding/cluster_resource_binding_controller.go
- test/e2e/clusteroverridepolicy_test.go
- test/e2e/overridepolicy_test.go
Cherry pick of #2771 on release-1.3.
#2771: fix overridepolicy with nil resource selector could not work
```release-note
`karmada-controller-manager`: Fix clusterOverridePolicy and overridePolicy with nil resource selector could not work
```
> Automated cherry pick of #2771: fix overridepolicy with nil resource selector could not work

- pkg/resourceinterpreter/configurableinterpreter/luavm/lua_convert.go
- pkg/resourceinterpreter/configurableinterpreter/luavm/lua_convert_test.go
/kind bug
The lua converter can't handle such object: `{"nodeClaim":[]}`
Fixes https://github.com/karmada-io/karmada/pull/2731#discussion_r1015424696
```release-note
NONE
```
> fix error when convert from empty lua table

- pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
- pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go
/kind bug
Now our `decodeValue` can't handle complex type, for example `[]workv1alpha2.AggregatedStatusItem`. This patch improves this function, supporting all the types.
Fixes #
```release-note
NONE
```
> improve decodeValue for Lua

- charts/karmada/templates/karmada-controller-manager.yaml
In our chart install workflow, use `post-job` to install all karmada crds. there is a problem, the karmada-controller-manager  is be installed before the job due to it always not running. becuase the karmada resource is not be `informer`:
so, we can install the karmada controller manager after the job have done.
Fixes #
please correct me if not.
```release-note
NONE
```
> chart: optimize pod startup order

- pkg/search/proxy/store/util.go
- pkg/search/proxy/store/util_test.go
/kind bug
"Resource Aggregation Proxy" uses json to merge multiple cluster ResourceVersions. Original it's serialized directly from `map[string]string`, the result string is like following without base64 encoding:
```
{"cluster1":"1","cluster2":"2"}
```
We must make sure the returned json string is stable, because client might use this string for equality comparison. But hash map's key iteration order is not determined. So instead we convert the map to a slice, and the slice must be sorted by `Cluster` field before encoding. …
> Resource Aggregation Proxy: make multi cluster ResourceVersion string stable

- pkg/controllers/unifiedauth/unified_auth_controller.go
- pkg/events/events.go
/kind feature
Add SyncImpersonationConfig event
```
Events:
Type    Reason                          Age                    From                     Message
----    ------                          ----                   ----                     -------
Normal  SyncImpersonationConfigSucceed  4m45s (x2 over 4m45s)  unified-auth-controller  Sync impersonation config succeed.
```
Part of #2472 
```
`Instrumentation`: Introduced the `SyncImpersonationConfigSucceed` and `SyncImpersonationConfigFailed` to the `cluster` object. 
```
> Add SyncImpersonationConfig event

- pkg/detector/policy.go
/kind bug
For detail see #2779 
Fixes #2779 
```release-note
karmada-controlle-managerr: ignore resource that do not match with policy before apply policy
```
> [bugfix] ignore resource that do not match with policy before apply policy

- test/e2e/clusteroverridepolicy_test.go
- test/e2e/overridepolicy_test.go
/kind flake
https://github.com/karmada-io/karmada/issues/2804#issuecomment-1316519640
Fixes #2804
This patch maybe needs to rebase to the previous release.
```release-note
NONE
```
> [e2e] mark test case `Test clusterOverridePolicy with nil resourceSelectors` as serial

- pkg/resourceinterpreter/configurableinterpreter/configmanager/accessor.go
- pkg/resourceinterpreter/configurableinterpreter/configmanager/manager.go
- pkg/resourceinterpreter/configurableinterpreter/configurable.go
- pkg/resourceinterpreter/configurableinterpreter/luavm/lua.go
- pkg/resourceinterpreter/configurableinterpreter/luavm/lua_test.go
- pkg/resourceinterpreter/interpreter.go
Signed-off-by: zhangyukun <38148677+jameszhangyukun@users.noreply.github.com>
/kind feature
Resource Interpreter interfaces implements
part of #2371 
Fixes #
```release-note
NONE (Part feature)
```
> Resource Interpreter implements the interfaces

- pkg/detector/policy.go
Cherry pick of #2786 on release-1.3.
#2786: ignore resource that do not match with policy before apply
```release-note
karmada-controlle-managerr: ignore resource that do not match with policy before apply policy
```
> Automated cherry pick of #2786: ignore resource that do not match with policy before apply

- pkg/karmadactl/cmdinit/kubernetes/deployments.go
/kind feature
Add liveness probe into kube-controller-manager. 
others have already liveness probe.
.
```release-note
karmadactl: add liveness probe into the kube-controller-manager component
```
> karmadactl: add liveness probe into kube-controller-manager

- pkg/karmadactl/cmdinit/cmdinit.go
- pkg/karmadactl/cmdinit/kubernetes/deploy.go
- pkg/karmadactl/cmdinit/kubernetes/deployments.go
- pkg/karmadactl/cmdinit/kubernetes/statefulset.go
/kind feature
At present, it is mainly used for offline installation karmada to simplify installation commands.
Fixes #
Port of #2541 
Test
```shell
I1019 00:34:22.710879 1942695 deploy.go:188] kubeconfig file: /root/.kube/config, kubernetes: https://10.29.12.229:44230
I1019 00:34:22.732691 1942695 deploy.go:208] karmada apiserver ip: [172.18.0.4]
I1019 00:34:23.492457 1942695 cert.go:229] Generate ca certificate success.
I1019 00:34:23.695980 1942695 cert.go:229] Generate karmada certificate success.
I1019 00:34:24.011098 1942695 cert.go:229] Generate apiserver certificate success.
I1019 00:34:24.497476 1942695 cert.go:229] Generate front-proxy-ca …
```
> introduce `--private-image-registry` flag to `karmadactl init`

- test/e2e/clusteroverridepolicy_test.go
- test/e2e/overridepolicy_test.go
Cherry pick of #2811 on release-1.3.
#2811: mark test case  as serial
```release-note
NONE
```
> Automated cherry pick of #2811: mark test case  as serial

- test/e2e/clusterpropagationpolicy_test.go
- test/e2e/propagationpolicy_test.go
/kind flake
e2e will occasionally fail because it takes about 1s to sync cache in karmada-controller(get this from log). So we must increase the waiting time.
Fixes #none
none
```release-note
none
```
> e2e: wait till the informer's cache is synced in karmada-controller
