README.md

/kind cleanup
Part of #5048
See the [preview here](https://github.com/B1F030/karmada/blob/clomonitor/README.md).
```release-note
NONE
```

Add Artifact HUB badge

---

artifacts/deploy/karmada-apiserver.yaml
artifacts/deploy/kube-controller-manager.yaml
hack/deploy-karmada.sh

/kind cleanup
The workflow of APIServer compatibility is failing when it's running with master, see 
- https://github.com/karmada-io/karmada/pull/4898
- https://github.com/karmada-io/karmada/actions/runs/8950239870/job/24585393557
The reason is master is running with karmada-apiserver v1.27.11, and the workflow of `APIServer compatibility` is change the version of karmada-apiserver by patching karmada-apiserver, and actually it's happening the downgrade/upgrade of karmada-apiserver, it's always failing if karmada-apiserver have add some new API. For now, it's `flowcontrol.apiserver.k8s.io/v1beta3`, 
available with v1.26, so it will always failed if karmada-apiserver downgrade to lessthan v1.26
So this PR is working for …

chore: let kube version of artifaces/deploy/karmada-apiserver versionsupport configuration.

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/desired-kustomization.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/observed-kustomization.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kustomize.toolkit.fluxcd.io/v1/Kustomization/testdata/status-file.yaml

/kind feature
Part of #4870 
Fixes #
NONE
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of Kustomization with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated Kustomization's observedGeneration semantics with its native

---

pkg/karmadactl/join/join.go

/kind cleanup
[original PR](https://github.com/karmada-io/karmada/pull/5016) added these options with host prefix, but the intent was to signal that it's about the karmada api
this was never release so rename should be fine
```release-note
rename join command options from --host-as-* to --karmada-as-*
```

rename host-as-* to karmada-as-*

---

pkg/resourceinterpreter/default/native/replica.go

/kind bug
Fixes #
```release-note
`karmada-controller-manager`: Fixed the issue that the default resource interpreter doesn't accurately interpret the numbers of replicas.
```

Fix the bug in interpreting the replicas of Job

---

pkg/resourceinterpreter/default/native/replica.go

Cherry pick of #5095 on release-1.10.
#5095: Fix the bug in interpreting the replicas of Job
```release-note
`karmada-controller-manager`: Fixed the issue that the default resource interpreter doesn't accurately interpret the numbers of replicas.
```

Automated cherry pick of #5095: Fix the bug in interpreting the replicas of Job

---

cmd/agent/main.go
operator/cmd/operator/operator.go

/kind cleanup
silence the 'log.SetLogger(...) was never called' error for `karmada-agent`
Fixes #4868
Similar PR: #4885
```release-note
```

silence the 'log.SetLogger(...) was never called' error

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/desired-statefulset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/observed-statefulset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1beta1/StatefulSet/testdata/status-file.yaml

/kind feature
Align federated StatefulSet's observedGeneration semantics with its native
Part of #4870 
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of StatefulSet with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated StatefulSet's observedGeneration semantics with its native

---

pkg/resourceinterpreter/customized/declarative/luavm/kube.go
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations_tests.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/testdata/desired-flinkdeployment.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/testdata/observed-flinkdeployment.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/testdata/status-file.yaml

/kind feature
This PR adds a default resource customization for FlinkDeployments. Below is a summary of the supported default interpretations:
**Supported**
1. InterpretHealth
- We monitor the internal flink state that is added to the FlinkDeployment status via Flink Operator: `spec.status.jobStatus.state`. FlinkDeployments can enter errored states due to user related code issues, rather than due to bad cluster health or lack of cluster resources. As a result we want to differentiate from these cases so that Karmada only reschedules these apps when needed. 
- We chose to mark FlinkDeployments as `Unhealthy` only if the internal flink state is trapped in a non-terminal state - these states include:
1. CREATED (job was …

Adding FlinkDeployment CRD to supported third party resource customizations

---

.github/workflows/release.yml

/kind cleanup
[SBOM](https://www.aquasec.com/cloud-native-academy/supply-chain-security/sbom/): A Software Bill of Materials, is an inventory of all of the components that exist within a software resource, such as third-party libraries or modules. SBOMs can identify components that developers integrated directly into an application by importing them into its source code, as well as dependencies (which aren’t a direct part of an application but that are installed or run when the application is deployed). 
[SPDX](https://spdx.dev/): An open standard capable of representing systems with software components in as SBOMs and other AI, data and security references supporting a range of risk management use cases.
I'd like to add …

add sbom to release assests

---

charts/karmada/templates/post-install-job.yaml
charts/karmada/values.yaml

/kind cleanup
/kind bug
cleanup helm chart:
* set `karmada-metrics-adapter` image pull policy to `karmadaImagePullPolicy`, in order to keep the same as other components
* fix a occasional bug in `post-install-job`, detail refers to code comments
Fixes #
```release-note
```

cleanup helm chart

---

.github/workflows/ci-image-scanning.yaml

/kind cleanup
refer to https://github.com/karmada-io/karmada/issues/5048#issuecomment-2201857283, set the permissions required for the job in ci-image-scanning.yaml
Parts of #5048
```release-note
```

set the permissions required for job in ci-image-scanning.yaml

---

.github/workflows/dockerhub-latest-chart.yml
.github/workflows/lint-chart.yaml

/kind feature
Part of #5048 
```release-note
NONE
```

Define top level Permission for dockerhub-latest-chart.yml (latest chart to Dockerhub) work flow

---

.github/workflows/dockerhub-latest-image.yml
.github/workflows/dockerhub-released-chart.yml
.github/workflows/dockerhub-released-image.yml
.github/workflows/release.yml
.github/workflows/swr-latest-image.yml
.github/workflows/swr-released-image.yml

/kind cleanup
set Minimum GITHUB_TOKEN permissions to github workflow
Parts of #5048 
```release-note
```

set Minimum GITHUB_TOKEN permissions to github workflow

---

.github/workflows/fossa.yml

/kind feature
Part of #5048 
```release-note
NONE
```

Define top level Permission for fossa.yml (FOSSA) workflow

---

hack/tools/tools.go
hack/update-codegen.sh
vendor/k8s.io/kube-openapi/cmd/openapi-gen/openapi-gen.go
vendor/modules.txt

/kind cleanup
The `openapi-gen` has been removed from [k8s.io/code-generator](https://github.com/kubernetes/code-generator/tree/master/cmd) by https://github.com/kubernetes/kubernetes/pull/123529 because it is redundant with [the one in k8s.io/kube-openapi](https://github.com/kubernetes/kube-openapi/tree/master/cmd/openapi-gen).
Fixes #
We are going to bump Kubernetes dependencies to v1.30, this PR solves one of the blockers.
```release-note
NONE
```

Switch openapi-gen from k8s.io/code-generator to k8s.io/kube-openapi

---

artifacts/deploy/karmada-apiserver.yaml
artifacts/deploy/kube-controller-manager.yaml
hack/deploy-karmada.sh

Cherry pick of #4899 on release-1.8.
#4899: chore: let kube version of artifaces/deploy/karmada-apiserver
```release-note
```

Automated cherry pick of #4899: chore: let kube version of artifaces/deploy/karmada-apiserver

---

.github/workflows/lint-chart.yaml

/kind feature
Part of #5048
```release-note
NONE
```

Define top level Permission for lint-chart.yaml (Chart Lint) workflow

---

hack/update-estimator-protobuf.sh

/kind cleanup
Skip generates proto files in vendor.
Fixes #
As per the help of `--apimachinery-packages`, directories prefixed with `-` are not generated:
```
--apimachinery-packages string     comma-separated list of directories to get apimachinery input types from which are needed by any API. Directories prefixed with '-' are not generated, directories prefixed with '+' only create types with explicit IDL instructions. (default "+k8s.io/apimachinery/pkg/util/intstr,+k8s.io/apimachinery/pkg/api/resource,+k8s.io/apimachinery/pkg/runtime/schema,+k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/apis/meta/v1beta …
```

Skip generating proto for kubernetes apis in vendor

---

pkg/controllers/mcs/endpointslice_controller.go

/kind cleanup
For cleanup part logic, it is used to protect the upgrade scenario, now we do not need it anymore.
Fixes #
```release-note
NONE
```

Remove unused cleanup code in endpointslice-controller

---

pkg/controllers/mcs/endpointslice_controller.go
pkg/controllers/mcs/service_import_controller.go

/kind cleanup
As comment in https://github.com/karmada-io/karmada/pull/4620#issuecomment-2196643082, we do not need to add the `karmada.io/managed` label to the collected endpointslice and derived service, so I removed it.
Fixes #
```release-note
NONE
```

Remove managed label in collected endpointslice and derived service

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/desired-gitrepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/observed-gitrepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1/GitRepository/testdata/status-file.yaml

/kind feature
Part of #4870 
Fixes #
NONE
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of GitRepository with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated GitRepository's observedGeneration semantics with its native

---

.github/workflows/ci-schedule-compatibility.yaml

* Add master branch to run workflow of karmada-apiserver compatibility.
/kind cleanup
changes:
- delete the step for upgrade/downupgrade karmada-apiserver. (resolve the compatibility problem of karmada-apiserver downupgrade https://github.com/karmada-io/karmada/actions/runs/9734577204/job/26862782887 )
- Add master branch to run karmada-apiserver compatibility
cc @zhzhuang-zju 
Tested on my fork repo: https://github.com/liangyuanpeng/karmada/actions/runs/9802951091
And reason of workflow is failing is have a test need to update for karmada-apiserver 1.30, it's working at https://github.com/karmada-io/karmada/pull/5141
Fixes #
**Does this PR introduce …

ci: delete the step for upgrade/downupgrade karmada-apiserver.

---

pkg/detector/detector.go
pkg/webhook/clusterpropagationpolicy/mutating.go
pkg/webhook/propagationpolicy/mutating.go

/kind cleanup
we need to transplant this finalizer to karmada-webhook in v1.11 release.
Fixes #
```release-note
NONE
```

Transplant propagation policy finalizer to karmada-webhook

---

.github/workflows/ci-schedule.yml

/kind feature
Part of #5048 
```release-note
NONE
```

Define top level Permission for ci-schedule workflow

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/desired-cloneset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/observed-cloneset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/CloneSet/testdata/status-file.yaml

/kind feature
Part of https://github.com/karmada-io/karmada/issues/4870, https://github.com/karmada-io/karmada/issues/5021
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of CloneSet with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated CloneSet's observedGeneration semantics with its native

---

hack/update-import-aliases.sh
hack/update-mocks.sh
pkg/scheduler/framework/interface.go
pkg/scheduler/framework/testing/mock_interface.go

/kind cleanup
Fixes the generated file doesn't group imports(`gomock "go.uber.org/mock/gomock"`) issue.
https://github.com/karmada-io/karmada/blob/8a101ebcb7c798a440153a3243f4992d87bad5db/pkg/scheduler/framework/testing/mock_interface.go#L12-L19
```release-note
NONE
```

Fix mockgen generated files not group imports issue

---

pkg/scheduler/core/spreadconstraint/group_clusters.go
pkg/scheduler/core/spreadconstraint/util_test.go

/kind feature
With the PR, Karmada will sort clusterInfo by score, and fallback to sorting by availableReplicas. This will help cases in which some clusters have the same score, but we should prefer scheduling on clusters with higher availableReplicas.
Fixes #5129
```release-note
`karmada-scheduler`: GroupClusters will sort clusters by score and availableReplica count.
```

GroupClusters should sort by score and availableReplica count

---

pkg/printers/internalversion/printers.go
pkg/printers/internalversion/printers_test.go

/kind feature
In daily operation and maintenance, the command `kubectl get cluster xxx -owide` displays too little information, and usually the administrator need to view it through `kubectl get cluster xxx -oyaml`.
Therefore, in order to improve operation and maintenance efficiency, this PR prints more valuable fields.
Fixes #
Test result:
```shell
[root@whitewindmills ~]# kubectl --kubeconfig karmada.config get cluster -owide
NAME          VERSION                           MODE   READY   AGE   ZONES    REGION    PROVIDER   API-ENDPOINT                          PROXY-URL
member1       v1.25.8-79+a42148b1deb54e-dirty   Pull   True    18h   foo,bar …
```

Add more columns for cluster

---

charts/karmada/templates/karmada-agent.yaml
charts/karmada/templates/karmada-controller-manager.yaml
charts/karmada/templates/karmada-scheduler.yaml

…posed, but other componment is not.
This is improve for installation, the port of karmada-apiserver is exposed, but other componment is not.
Fixes #
```release-note
Expose the default port  for the karmada-controller-manager, scheduler and agent when creating a PodMonitor.
```

Expose containing port of serving metrics

---

pkg/scheduler/core/spreadconstraint/group_clusters.go
pkg/scheduler/core/spreadconstraint/util_test.go

Cherry pick of #5144 into release-1.10. 
With this small change, we now sort clusters by taking their availableReplicas into account, rather than defaulting to the cluster's name. This helps spread resource usage across all clusters and would be helpful to use as part of the current v1.10 release.

Automated cherry pick of #5144: GroupClusters should sort by score and availableReplica count

---

pkg/karmadactl/register/register.go
pkg/util/constants.go
pkg/util/credential.go

/kind feature
Follow-up to https://github.com/karmada-io/karmada/pull/3262
Adds the well-known "karmada.io/managed" label to resources created by karmada controllers
We need a way to bypass creation of some ClusterRole/Rolebindings by our OPA Gatekeeper and we don't have a consistent label to select on. When we join a cluster via push command, it creates ClusterRole/ClusterRoleBinding that are too open (`*` and `*`) which is by default blocked by our opa-gatekeeper policies. This allows us to bypass it by the karmada managed label.
Fixes #
```release-note
`karmadactl`: Add the reserved label …
```

`karmadactl`: Add the reserved label `karmada.io/system` to resources created by the `join` command

---

pkg/karmadactl/cmdinit/cert/cert.go
pkg/karmadactl/cmdinit/cert/cert_test.go
pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go

/kind feature
issue: https://github.com/karmada-io/karmada/issues/5103
Fixes https://github.com/karmada-io/karmada/issues/5103
```release-note
`karmadactl`: Introduced `--ca-cert-file` and `--ca-key-file` flags to `init` command to specify the root CA which will be used to issue the certificate for components.
```

feat: karmadactl add ca-cert-path and ca-key-path opts

---

pkg/apis/cluster/install/install.go
pkg/apis/search/install/install.go
pkg/resourceinterpreter/customized/webhook/customized.go
pkg/util/gclient/gclient.go

/kind cleanup
This PR adopts the deprecated `AddToScheme` and `SchemeGroupVersion`, which becomes the blocker of #5146.
```
Using golangci-lint version:
golangci-lint has version 1.59.0 built with go1.22.3 from 2059b18a on 2024-05-26T18:13:27Z
pkg/apis/search/install/install.go:30:19: SA1019: searchv1alpha1.AddToScheme is deprecated: use Install instead (staticcheck)
utilruntime.Must(searchv1alpha1.AddToScheme(scheme))
^
pkg/util/gclient/gclient.go:45:19: SA1019: clusterv1alpha1.AddToScheme is deprecated: use Install instead (staticcheck)
utilruntime.Must(clusterv1alpha1.AddToScheme(aggregatedScheme))     // add cluster schemes
^
pkg/util/gclient/gclient.go:46:19: SA1019: configv1alpha1.AddToScheme is deprecated: use …
```

Adopt deprecated AddToScheme functions

---

cmd/aggregated-apiserver/app/options/options.go
cmd/aggregated-apiserver/app/options/validation.go

/kind cleanup
When upgrading the Kubernetes dependency to version 1.30, the following errors are reported by the component `karmada-aggregate-apiserver`:
```log
I0712 09:39:04.225311       1 options.go:97] karmada-aggregated-apiserver version: version.Info{GitVersion:"v1.11.0-alpha.0-142-g32068dc9b", GitCommit:"32068dc9b81eaa30e36743f4b6c57539fa79bf5a", GitTreeState:"clean", BuildDate:"2024-07-12T09:34:00Z", GoVersion:"go1.22.4", Compiler:"gc", Platform:"linux/amd64"}
I0712 09:39:04.490806       1 shared_informer.go:313] Waiting for caches to sync for *generic.policySource[*k8s.io/api/admissionregistration/v1.ValidatingAdmissionPolicy,*k8s.io/api/admissionregistration/v1.ValidatingAdmissionPolicyBinding,k8s.io/apiserver/p …
```

replace RecommendedOptions with needed subset options in karmada-aggregate-apiserver component

---

pkg/resourceinterpreter/default/native/aggregatestatus.go
pkg/resourceinterpreter/default/native/reflectstatus.go
pkg/resourceinterpreter/default/native/status_type.go

/kind feature
part of #4870
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of DaemonSet with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated DaemonSet's observedGeneration semantics with its native

---

test/e2e/karmadactl_test.go

In this commit, we test `karmadactl logs` command on existing cluster, existing pod, non-existing pod, non-existing cluster, and invalid input.
Part of #4544
```release-note
NONE
```

test/e2e/karmadactl_test.go: test logs command

---

SECURITY-INSIGHTS.yml

provide an [OpenSSF Security Insights](https://github.com/ossf/security-insights-spec/blob/v1.0.0/specification.md) manifest file. 
Parts of #5048
```release-note
```

add security-insights.yml

---

pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/util/helper/work.go

/kind bug
The finalizer `MCSEndpointSliceDispatchControllerFinalizer` was added too late, and when the dispatched work is still in the process of creating, deleting the `MultiClusterService` object may result in residual dispatched work resources.
Fixes #
```release-note
karmada-controller-manager: fix the issue of residual work in the MultiClusterService feature.
```

Fix the issue of residual work in the MultiClusterService feature.

---

test/e2e/karmadactl_test.go

In this commit, we test `karmadactl version` command to make sure it return valid information and return error when invalid flag is provided.
Part of #4544
```release-note
NONE
```

test/e2e/karmadactl_test.go: test version command

---

pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/util/helper/work.go

Cherry pick of #5188 on release-1.10.
#5188: Fix the issue of residual work in the MultiClusterService
```release-note
karmada-controller-manager: fix the issue of residual work in the MultiClusterService feature.
```

Automated cherry pick of #5188: Fix the issue of residual work in the MultiClusterService

---

test/e2e/karmadactl_test.go

In this commit, we test `karmadactl get` command on existing resource, non-existing resource, and invalid resource type.
Part of #4544
```release-note
NONE
```

test/e2e/karmadactl_test.go: test get command

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/desired-daemonset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/observed-daemonset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/testdata/status-file.yaml

/kind feature
part of https://github.com/karmada-io/karmada/issues/4870
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of daemonsets.apps.kruise.io with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated daemonsets.apps.kruise.io observedGeneration semantics with its native

---

test/e2e/karmadactl_test.go

In this commit, we test `karmadactl describe` command on existing resource, non-existing resource, non-existing namespace, and invalid resource type.
Part of #4544
```release-note
NONE
```

test/e2e/karmadactl_test.go: test describe command

---

operator/cmd/operator/app/operator.go
operator/cmd/operator/app/options/options.go

/kind cleanup
Fixes #
```release-note
`karmada-operator`: Introduced `--metrics-bind-address` and `--health-probe-bind-address` flags, it's a compatible change as the default value does not change from previous versions. 
```

Add missing command line arguments for karmada-operator

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml

/kind feature
The default interpreter for FlinkDeployment does not currently account for namespace or priorityclass. This was done because in our use-case, the priorityclass is shared amongst tenants and can be set statically. But after thinking again, it makes more sense to have this interpretation be generic.
This is a quick PR that adds that capability. 
```release-note
Added generic handling of priorityclass and namespace for default flinkdeployment interpreter
```

Adding generic handling of priorityclass + namespace for flinkdeployment interpreter

---

test/e2e/aggregatedapi_test.go
test/e2e/clusteraffinities_test.go
test/e2e/dependenciesdistributor_test.go
test/e2e/fieldselector_test.go
test/e2e/karmadactl_test.go
test/e2e/lazy_activation_policy_test.go
test/e2e/mcs_test.go
test/e2e/preemption_test.go
test/e2e/rescheduling_test.go
test/e2e/search_test.go
test/e2e/tainttoleration_test.go

Unify access to cluster members utilizing `framework.ClusterMembers()[i]`.
/kind cleanup [not sure if this is the correct kind of PR!]
Motivated by @XiShanYongYe-Chang's comment:
https://github.com/karmada-io/karmada/pull/5195#discussion_r1680354650
```release-note
NONE
```

test/e2e: unify access to cluster members utilizing `framework.ClusterMembers()[i]`

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/desired-helmrepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/observed-helmrepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmRepository/testdata/status-file.yaml

Fixes #4870 
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of helmrepositories.source.toolkit.fluxcd.io with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated helmrepositories.source.toolkit.fluxcd.io observedGeneration semantics with its native

---

docs/proposals/dispatch-suspension/README.md

/kind design
Fixes #1567, #4421, #4688
Other related issues: #4937 
```release-note
NONE
```

[Proposal] Support for cluster-level resource propagation pause and resume capabilities

---

test/e2e/karmadactl_test.go

In this commit, we test `karmadactl options` on listing all available global options successfully and returning an error for the invalid flag in options.
Part of #4544
```release-note
NONE
```

test/e2e/karmadactl_test.go: test options command

---

test/e2e/clusterpropagationpolicy_test.go
test/e2e/coverage_docs/clusterpropagationpolicy_test.md
test/e2e/framework/clusterpropagationpolicy.go
test/e2e/karmadactl_test.go

complete the e2e test case scenarios for clusterpp.
Additional scenes include:
- Deployment propagation testing
create a ClusterPropagationPolicy for deployment and then update deployment replicas
- [ImplicitPriority] propagation testing
priority: MatchName>MatchLabel>MatchAll
- delete the old ClusterPropagationPolicy to unbind and create a new one(namespace scope and cluster scope)
parts of # 4544
```release-note
NONE
```

complete the e2e test case scenarios for clusterpp

---

test/e2e/federatedresourcequota_test.go
test/helper/policy.go

In this commit, we unify access to cluster members in `test/helper` by passing `clusterNames` as an input parameter to the function `NewFederatedResourceQuota`. This commit is also a follow-up of this PR #5226.
/kind cleanup
Motivated by @XiShanYongYe-Chang's comment:
https://github.com/karmada-io/karmada/pull/5226#issuecomment-2238613211
```release-note
NONE
```

test: unify access to cluster members utilizing `framework.ClusterMembers()` as input parameter

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/desired-bucket.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/observed-bucket.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/Bucket/testdata/status-file.yaml

/kind feature
part of #4870
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of buckets.source.toolkit.fluxcd.io with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated buckets.source.toolkit.fluxcd.io observedGeneration semantics with its native

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/desired-ocirepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/observed-ocirepository.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/OCIRepository/testdata/status-file.yaml

/kind feature
Part of #4870 
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of ocirepositories.source.toolkit.fluxcd.io with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated ocirepositories.source.toolkit.fluxcd.io observedGeneration semantics with its native

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/desired-helmchart.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/observed-helmchart.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/source.toolkit.fluxcd.io/v1beta2/HelmChart/testdata/status-file.yaml

/kind feature
part of #4870
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of helmcharts.source.toolkit.fluxcd.io with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated helmcharts.source.toolkit.fluxcd.io observedGeneration semantics with its native

---

artifacts/deploy/webhook-configuration.yaml
charts/karmada/templates/_karmada_webhook_configuration.tpl
operator/pkg/karmadaresource/webhookconfiguration/manifests.go
pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

/kind feature
spilling out a part of https://github.com/karmada-io/karmada/pull/5240
```release-note
- karmada-webhook: changed "app" label from mutating-config/validating-config to karmada-webhook to make them identifiyable
```

relabel webhooks to make it obvious they belong to karmada

---

charts/karmada/_crds/patches/webhook_in_clusterresourcebindings.yaml
charts/karmada/_crds/patches/webhook_in_resourcebindings.yaml

/kind cleanup
The current syntax does not work for kustomize
```
❯ kustomize build charts/karmada/_crds/
Error: wrong node kind: expected ScalarNode but got MappingNode: node contents:
{? {caBundle: ''} : ''}
```
Adding quotes around it makes it work for kustomize build while still working for helm charts. This is a no risk change for those that prefer using kustomize.
Fixes #
```release-note
NONE
```

fix: kustomize syntax for webhook caBundle

---

pkg/controllers/cluster/cluster_controller.go
pkg/karmadactl/util/idempotency.go

/kind feature
followup to https://github.com/karmada-io/karmada/pull/4620 where this was not added
```release-note
- add karmada.io/system=true label to newly created karmada-es-* namespaces
```

add karmada.io/system label to created execution namespaces

---

pkg/controllers/status/work_status_controller.go
pkg/metrics/resource.go

/kind feature
add metrics for recreate/update resource event when sync work status
detail backgroud:
When I create a sa and a sa type secret in control plane, yet, I only propagate the secret to member clusters, then the secret will be deleted immediately by sa-controller of the member cluster. In turn the work_status_controller will watch the deletion event and recreate the resource to cluster, this cycle goes on and never stops.
Normally, there shouldn't be a large number of recreate events, so, I want to record a metric of the recreate event which can monitor the abnormal situation.
Fixes #
Test report:
```shell …
```

add metrics for recreate/update resource event when sync work status

---

charts/karmada/templates/_karmada_webhook_configuration.tpl

/kind bug
We've been having a lot of issues with karmada deleting cluster-level resources such as ClusterRole and ClusterRoleBinding.
After debugging, we realized that the label `clusterresourcebinding.karmada.io/permanent-id` was missing from those ClusterResourceBinding and that the webhook is responsible for populating that. Given that this was empty, all resource propagated to the member cluster also had an empty value for the id (i.e. `clusterresourcebinding.karmada.io/permanent-id: ""`) which is then identified as orphaned work and is deleted in the cluster.
This must have broke after the "63 char limit issue" because all of our CRBs prior to that release are fine and do not cause orphan work issues:
(note 79 days …

fix: `ClusterResourceBinding` scope in `MutatingWebhookConfiguration`

---

test/e2e/clusterpropagationpolicy_test.go

The scope of some Policy's resourceSelector in E2E use case is too large to affect other use cases.
detail refer to #5256
Fixes #5256
```release-note
```

fix unexpected interference between different e2e use cases

---

test/e2e/clusterresourcebinding_test.go

/kind cleanup
As described in linked PR, if the label is not set, it could lead to cluster resources being identified as orphaned work and deleted in member clusters. This PR attempts to prevent regressions from happening.
Request in PR https://github.com/karmada-io/karmada/pull/5252#issuecomment-2252336961
```release-note
```

e2e: clusterresourcebinding permanent-id label

---

charts/karmada/_crds/kustomization.yaml

/kind cleanup
patchesStrategicMerge is deprecated, following the warning message to run command of `kustomize edit fix` for update it.
```shell
```
Fixes #
```release-note
```

cleanup: use patches instead to patchesStrategicMerge for kustomize.

---

docs/proposals/operator-custom-crd-download-strategy/README.md

/kind design
Details are in the design document.
Fixes #
```release-note
NONE
```

Proposal: Custom CRD Download Strategy Support for Karmada Operator

---

artifacts/agent/karmada-agent.yaml
charts/karmada/templates/karmada-agent.yaml
cmd/agent/app/agent.go
cmd/agent/app/options/options.go
cmd/agent/app/options/validation.go
cmd/agent/app/options/validation_test.go
pkg/karmadactl/cmdinit/utils/examples.go
pkg/karmadactl/register/register.go

/kind feature
/kind cleanup
part of https://github.com/karmada-io/karmada/issues/5219
```release-note
`karmada-agent`:  Add health probe argument `health-probe-bind-address`, deprecate `--bind-address` and `--secure-port` flag.
```

Standardize the health probe arguments

---

charts/karmada/templates/_karmada_webhook_configuration.tpl

Cherry pick of #5252 on release-1.10.
#5252: fix: `ClusterResourceBinding` scope in
```release-note
Helm: fix wrong `ClusterResourceBinding` scope in `MutatingWebhookConfiguration`.
```

Automated cherry pick of #5252: fix: `ClusterResourceBinding` scope in

---

test/e2e/suite_log_test.go
test/e2e/suite_test.go

/kind flake
When e2e failed, the test environment is already destroyed, but we maybe we need to locate problem by refering ResourceTemplate/ResourceBinding/Work. So,we want to record all binding and related objects to log file after each e2e failure case.
Fixes part of #5136
If here is any e2e case failed, you can find the corresponding exported logs in `ci runner -> Summary -> Artifacts -> karmada_kind_log_v1.x.x`, such as:
```release-note
```

print all binding and related objects to log file after each e2e failure case

---

pkg/scheduler/scheduler.go
pkg/util/helper/patch.go

/kind cleanup
only generate json patch for status filed when patchBindingStatus
Fixes #5203
Test report of **Benchmark**:
**1）** test code:
<details>
<summary>benchmark_test.go</summary>
```go
var now = metav1.Now()
var bindSpec = workv1alpha2.ResourceBindingSpec{
PropagateDeps:         true,
ReplicaRequirements: &workv1alpha2.ReplicaRequirements{
ResourceRequest: util.EmptyResource().ResourceList(),
},
Replicas:              10,
Placement: &policyv1alpha1.Placement{
ReplicaScheduling: &policyv1alpha1.ReplicaSchedulingStrategy{
ReplicaSchedulingType:     policyv1alpha1.ReplicaSchedulingTypeDivided,
ReplicaDivisionPreference: …
```

only generate json patch for status filed when patchBindingStatus

---

pkg/webhook/federatedresourcequota/validating_test.go

In this commit, we add unit tests for the `FederatedResourceQuota` validation logic and its related components. The tests ensure that the validation logic correctly handles various scenarios, including:
- Validating `FederatedResourceQuota` specifications with appropriate resource assignments.
- Detecting cases where overall resource limits are less than the assigned resources.
- Handling scenarios where resource names in assignments do not exist in the overall resources.
- Validating `FederatedResourceQuotaStatus` to ensure standard resource types and correct cluster names.
- Handling invalid resource lists in both `Overall` and `AggregatedStatus`.
**Test Coverage**
The test case coverage has been increased from 30.2% to 100% 🎉. This can be verified in the …

pkg: test `federatedresourcequota` webhook

---

operator/pkg/karmadaresource/rbac/rbac.go
pkg/controllers/unifiedauth/unified_auth_controller.go
pkg/karmadactl/cmdinit/utils/rbac.go
pkg/karmadactl/cmdinit/utils/rbac_test.go

/kind feature
similar to [namespaces](https://github.com/karmada-io/karmada/pull/5243/files) cluster-roles need to have an identifier so we can find them all (without having to guess based on names)
and allow-list them in our "are you allowed to create cluster-roles" auditing tooling
```release-note
- add karmada.io/system=true label to internally created karmada cluster-roles and cluster-role-bindings
```

add karmada.io/system label to created clusterrole+bindings

---

test/e2e/karmadactl_test.go

/kind cleanup
- After waiting for all member clusters' pods to reach the running state, there's no need to wait for member cluster member1's pod to reach the running state again.
- The `top pod` test does not require creating a new cluster, so remove the `ginkgo.Labels{NeedCreateCluster}` label.
Fixes #
```release-note
```

cleanup: Remove redundant e2e testing steps

---

.github/workflows/cli.yaml

/kind cleanup
Part of #5048 
```release-note
NONE
```

Define top level Permission for cli.yml workflow

---

.github/workflows/ci-schedule-compatibility.yaml

/kind feature
Part of #5048 
```release-note
NONE
```

Define top level Permission for ci-schedule-compatibility workflow

---

.github/workflows/ci.yml

/kind feature
Part of #5048
```release-note
NONE
```

Define top level Permission for ci.yml workflow 

---

pkg/util/validation/validation.go
pkg/util/validation/validation_test.go

/kind feature
Fixes #5118
```release-note
```

work suspension: webhook validation

---

pkg/util/annotation_test.go
pkg/util/label_test.go

The test case coverage for annotation.go has been increased from 73.9% to 100% and for label.go has been increased from 97.8% to 100% . 
Ref #5235 
To verify the changes in the pkg/util directory run the following commands:
```
```
```release-note
NONE
```

Add 100% unit test coverage for annotation and label in pkg/util

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/desired-helmrelease.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/observed-helmrelease.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/helm.toolkit.fluxcd.io/v2beta1/HelmRelease/testdata/status-file.yaml

/kind feature
Part of #4870 
NONE
```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of helmreleases.helm.toolkit.fluxcd.io with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

Align federated helmreleases.helm.toolkit.fluxcd.io observedGeneration semantics with its native

---

pkg/controllers/status/crb_status_controller_test.go
pkg/controllers/status/rb_status_controller_test.go

repair the test for rb status controller:
In the UT of `RBStatusController`, here is a fake client, as:
```go
c.Client = fake.NewClientBuilder().WithScheme(gclient.NewSchema()).Build(),
```
the ut function wants to preset some resource by the fake client, such as:
```go
if err := c.Client.Create(context.Background(), binding); err != nil {
t.Fatalf("Failed to create binding: %v", err)
}
```
then it wants to update the status of that resource, such as:
```go
if err := c.Client.Status().Update(context.Background(), binding); err != nil {
t.Fatalf("Failed to update status of binding: %v", err)
}
```
Actually, the update function will failed with `Error: resourcebindings.work.karmada.io "binding" not …

repair the test for rb status controller

---

pkg/controllers/context/context_test.go

**Description**:
This PR enhances the test coverage for the pkg/controllers/context package, increasing its test coverage from 42.3% to 100%. The new tests are designed to ensure the functionality and reliability of the package, improving its overall maintainability.
**Implemented Tests**:
1. TestInitializers_ControllerNames: Checks that ControllerNames() correctly returns all controller names.
2. TestInitializers_StartControllers: Tests the StartControllers() method under different conditions, including successful starts, error handling, and scenarios with disabled controllers.
**Test Coverage**:
Implementing this tests increased it's test coverage from 42.3% to 100%. This can be verified in the file directory i.e. pkg/controllers/context using command
`go test …

Improve test coverage of pkg/controllers/context

---

pkg/util/common_test.go

The test case coverage for common.go has been increased to 100%.
Ref #5235 
To verify the changes in the pkg/util directory run the following commands:
```
```
```release-note
NONE
```

Add unit tests for common.go in pkg/util

---

.github/workflows/release.yml

/kind feature
This PR includes the following two things in total:
- remove unused workflow step
https://github.com/karmada-io/karmada/blob/71de3dc02247e22da249c285fa0c0c032ae01445/.github/workflows/release.yml#L36-L39
- add slsa provenance to release assets
This PR will generate a non-forgeable attestation to the artifacts' digests using the identity of the GitHub workflow. This can be used to create a positive attestation to a software artifact coming from karmada repository.
That means that once karmada users verify the artifacts they have downloaded they can be sure that the artifacts were created by karmada repository's workflow and haven't been tampered with.
This time a total of four slsa provenance are introduced …

chore: add slsa provenance to release assets

---

test/e2e/federatedresourcequota_test.go
test/e2e/karmadactl_test.go
test/e2e/namespace_test.go
test/e2e/rescheduling_test.go

This commit standardizes the generation of random string lengths by utilizing the `RandomStrLength` global constant.
The motivation for this change arose from observing that `RandomStrLength` was already being used to create clusters in [`test/e2e/aggregatedapi_test.go`](https://github.com/karmada-io/karmada/blob/37488bd1093a2c5cf808b6cf87d601caab07a05f/test/e2e/aggregatedapi_test.go#L69). This presented a good opportunity to unify cluster name generation using the `RandomStrLength` constant across the codebase. Please let me know if this is a valid improvement! 🙏
/kind cleanup
```release-note
NONE
```

test/e2e: unfiy random string length generation

---

test/e2e/resource_test.go

since kubernetes 1.30 begin set IPMode of LoadBalancer service to VIP by default if IP is setting, So we need to set the IPMode to VIP for test.
check failing tests: https://github.com/karmada-io/karmada/actions/runs/9734577204/job/26862785337
check the kubernetes side: https://github.com/kubernetes/kubernetes/blob/d27e3462baa419532209a7515bd24de36b2a5020/pkg/apis/core/v1/defaults.go#L147-L151
also can check the reproduce workflow: https://github.com/karmada-io/karmada/actions/runs/9804835683/job/27073502218?pr=5141
just change the karmada-apiserver to v1.30.0 for reproduce it.
and i open a PR https://github.com/karmada-io/karmada/pull/5142 to adding the master branch to run karmada-apiserver …

 Fix test for corev1.LoadBalancerIngress,add IP model to VIP when ip is setting.

---

pkg/controllers/execution/execution_controller.go
pkg/controllers/execution/execution_controller_test.go
pkg/events/events.go
pkg/util/lifted/corev1printers.go
pkg/util/lifted/scheduler/cache/cache.go
pkg/util/lifted/validatingfhpa.go
test/e2e/framework/events.go
test/e2e/propagationpolicy_test.go
test/helper/resource.go

/kind feature
As requested by @chaunceyjiang [here](https://github.com/karmada-io/karmada/pull/5317#discussion_r1708454030)
Part of #5217 
```release-note
```
It's definitely a noisy one (from e2e):
```
❯ kubectl get events -n karmada-es-member1 -w | grep Dispatch
3s          Normal    WorkDispatching          work/deploy-5tss401-798f586f4f      Work dispatching is in a suspended state.
20m         Normal    WorkDispatching          work/deploy-6vf8r-5b589484f8        Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/deploy-bxwzd-595fbff7bf        Work is …
```

work suspension: emit event for work dispatch status 

---

pkg/controllers/binding/binding_controller_test.go
pkg/controllers/binding/cluster_resource_binding_controller_test.go

Improved test coverage for /pkg/controllers/binding from 36.4% to 64.9%
Part: https://github.com/karmada-io/karmada/issues/5235
```release-note
NONE
```

Improve test coverage for /pkg/controllers/binding

---

pkg/controllers/status/cluster_condition_cache_test.go

/kind feature
###Fixes #5337 
- Added test cases to cover scenarios where the `readyCondition` status changes in the `thresholdAdjustedReadyCondition` method.
- Focused on ensuring that the `thresholdStartTime` is updated correctly when the condition changes and that the old status is retained until the threshold is exceeded.

Added unit test cluster_condition coverage : 100%

---

pkg/util/interpreter/matcher_test.go
pkg/util/names/names_test.go
pkg/util/overridemanager/shadow_test.go

/kind feature
The test case coverage for interpreter/matcher.go, overridemanager/shadow.go and names/names.go has been increased to 100%.
Ref #5235 
To verify the changes in the pkg/util directory run the following commands:
```
```
```release-note
NONE
```

Add 100% test coverage for matcher, shadow, and names.go in pkg/util

---

pkg/resourceinterpreter/default/native/replica_test.go

/kind feature
The test case coverage for pkg/resourceinterpreter/default/native/replica.go has been increased from 0% to to more than 80%.
Fixes #
To verify the changes in the pkg/resourceinterpreter/default/native/ directory run the following commands:
```
```
```release-note
NONE
```

Improved test coverage for replica in pkg/resourceinterpreter

---

.github/workflows/ci-image-scanning.yaml
.github/workflows/dockerhub-latest-chart.yml
.github/workflows/dockerhub-released-chart.yml
.github/workflows/lint-chart.yaml

/kind cleanup
The setup-go action is the recommended way of [using Go with GitHub Actions](https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-go#specifying-a-go-version), because it helps ensure consistent behavior across different runners and different versions of Go. At present, we still have the following workflows for which the Go version has not been specified：
- .github/workflows/ci-image-scanning.yaml
- .github/workflows/dockerhub-latest-chart.yml
- .github/workflows/dockerhub-released-chart.yml
- .github/workflows/lint-chart.yaml
Fixes #
When the Go version is not specified, the Go version in …

use single source for go version

---

pkg/descheduler/core/filter_test.go
pkg/descheduler/core/helper_test.go
pkg/descheduler/descheduler_test.go

This PR enhances the test coverage for the pkg/descheduler package by adding a new test file pkg/descheduler/core/helper_test.go and improving test coverage of all test files in pkg/descheduler.
**Changes:**
1. Added new test file for pkg/descheduler/core/helper.go.
2. Added meaningful test cases for functions which were not covered before by the tests and improved test coverage of pkg/descheduler/core/ from 13.75% to 85.5%.
3. Added meaningful test cases for functions which were not covered before by the file descheduler_test.go, significantly improving its test coverage. 
/kind feature
Enhances the functionality of the pkg/descheduler package by improving the robustness of event …

Improve test coverage of pkg/descheduler

---

.github/workflows/ci-image-scanning.yaml
.github/workflows/dockerhub-latest-chart.yml
.github/workflows/dockerhub-released-chart.yml
.github/workflows/lint-chart.yaml

Cherry pick of #5360 on release-1.10.
#5360: use single source for go version
```release-note
```

Automated cherry pick of #5360: use single source for go version

---

.github/workflows/lint-chart.yaml
charts/karmada/templates/karmada-scheduler-estimator.yaml

/kind cleanup
The scheduler-estimator Pod already has an app label configured:
https://github.com/karmada-io/karmada/blob/e5b12986081bf878bf4b70f3db2f8500e0bceb02/charts/karmada/templates/karmada-scheduler-estimator.yaml#L33-L35
And we also have a default app label value in the `values.yaml`:
https://github.com/karmada-io/karmada/blob/e5b12986081bf878bf4b70f3db2f8500e0bceb02/charts/karmada/values.yaml#L801-L802
This results in duplicate app labels in the scheduler-estimator Pod:
```yaml
labels:
app: karmada-scheduler-estimator-xx
app: karmada-scheduler-estimator
```
This doesn't affect the helm installation, but it prevents kustomize from building it:
```
mapping key "app" already defined
```
This patch removes the …

charts/karmada: remove duplicate app label config in scheduler-estimator

---

test/e2e/clusterpropagationpolicy_test.go
test/e2e/propagationpolicy_test.go

/kind feature
Adding more e2e tests based on the proposal
Part of https://github.com/karmada-io/karmada/issues/5217
Note that 2 of the tests are NOT passing, which indicates that there's a bug in execution / work sync somewhere
```release-note
```

e2e for work suspension resume

---

test/e2e/resource_test.go
test/helper/resource.go

these days, the e2e case [pdb status collection testing] often failed, such as:
https://github.com/karmada-io/karmada/actions/runs/10401933004/job/28805568396?pr=5378
https://github.com/karmada-io/karmada/actions/runs/10401933004/job/28811015421?pr=5378
1. `work` status of `deploment/nginx` in member1:
```yaml
"manifestStatuses": [
{
"identifier": {
"ordinal": 0,
"group": "apps",
"version": "v1",
"kind": "Deployment",
"resource": "",
"namespace": "karmadatest-tlftr",
"name": "poddisruptionbudget-m472d"
},
"status": {
"availableReplicas": 3,
"generation": 1,
"observedGeneration": 1,
"readyReplicas": 3,
"replicas": 3,
"resourceTemplateGeneration": 2,
"updatedReplicas": 3
},
"health": "Healthy"
}
]
```
2. …

fix pdb collection testing occasional failure

---

test/e2e/propagationpolicy_test.go

In #5376 we no longer suspend deletion, as a result these tests do not make sense any longer.
/cc @chaosi-zju @XiShanYongYe-Chang 
Fixes #
```release-note
```

chore: remove e2e tests for delete when suspended

---

pkg/resourceinterpreter/default/native/aggregatestatus_test.go
pkg/resourceinterpreter/default/native/default_test.go
pkg/resourceinterpreter/default/native/dependencies_test.go
pkg/resourceinterpreter/default/native/healthy_test.go
pkg/resourceinterpreter/default/native/replica_test.go
pkg/resourceinterpreter/default/native/retain_test.go
pkg/resourceinterpreter/default/native/revisereplica_test.go

/kind feature
The test case coverage for pkg/resourceinterpreter/default/native/default.go has been increased from 0% to over 95%, and the coverage for other files has also been improved.
Fixes #
To verify the changes in the pkg/resourceinterpreter/default/native/ directory run the following commands:
```
```
```release-note
NONE
```

Improved test coverage for default.go and other related files in pkg/resourceinterpreter

---

pkg/karmadactl/get/get.go
pkg/karmadactl/options/global.go
test/e2e/karmadactl_test.go

/kind feature
- Fix the issue of incomplete output when the resource does not found
before:
```bash
$ karmadactl get secret 
No resources found in  namespace.
```
after:
```bash
$ karmadactl get secret 
No resources found in default namespace.
```
- Enhance karmadactl to provide a complete resource view of the Karmada control plane and member clusters.
Given that the Karmada control plane has a deployment named `nginx`, which is propagated to member1 and member2.
```bash
// display deployment in Karmada control plane
$ _output/bin/linux/amd64/karmadactl get deployment             
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE   ADOPTION
nginx   Karmada   0/2     4            0           17s   -
// display …
```

Enhance the capabilities of the karmadactl get command

---

charts/karmada/templates/post-install-job.yaml

/kind cleanup
I encountered the following situation: the `static-resource` Job failed during execution, so it retried once. The retry was successful, and although the Job eventually completed successfully, the initial failure resulted in a failed Pod. Because of this failed Pod, the post-install check script kept running, even though all Karmada components were already running. This patch makes the post-install script ignore Pods related to `static-resource`.
Fixes #
```release-note
none
```

charts/karmada: ignore the static-resource Pod in the post-install check

---

.github/workflows/cli.yaml
hack/cli-testing-environment.sh

/kind cleanup
this CI is using the kubernetes from created by `cli-testing-environment` and have not used `helm/kind-action`, so juse remove it..
https://github.com/karmada-io/karmada/blob/4898c0fc55a13033fcf21fcc46a41318548c5713/hack/cli-testing-environment.sh#L53-L55
the second change is collect logs for kind kubernetes.
Fixes #
```release-note
```

chore: remove unuse ghaction step and collect logs of karmadactl test.

---

pkg/karmadactl/describe/describe.go
test/e2e/karmadactl_test.go

/kind feature
Enhance the `karmadactl describe` command to add the ability to view Karmada control plane resources.
```bash
$ karmadactl describe pods --operation-scope members --cluster member1
Name:             nginx
Namespace:        default
Priority:         0
Service Account:  default
Node:             member1-control-plane/172.18.0.3
... ...
$ karmadactl describe pods 
Name:         nginx
Namespace:    default
Priority:     0
Node:         <none>
Labels:       propagationpolicy.karmada.io/permanent-id=d698e260-0eec-4dd7-b571-9c0cedb158f6
Annotations:  propagationpolicy.karmada.io/name: nginx-847459f8b6
propagationpolicy.karmada.io/namespace: default
Status:       Running
... ...
$ karmadactl describe pods …
```

enhance karmadactl describe command

---

pkg/controllers/status/cluster_status_controller.go
pkg/controllers/status/cluster_status_controller_test.go

/kind bug
During the cluster status update, due to the presence of an old Condition in the previous Cluster status, this Condition is incorrectly updated to the Cluster object during the status refresh. The expected Cluster status conditions should no longer include the old condition.
Fixes #
```release-note
karmada-controller-manager: fix the error of cluster status old condition update will overwrite the newest condition
```

fix the error of cluster status old condition update will overwrite the newest condition

---

pkg/karmadactl/exec/exec.go
test/e2e/karmadactl_test.go

/kind feature
enhance karmadactl exec command
Given that the Karmada control plane has a deployment named `nginx`, which is propagated to member1, member2 and member3.
```bash
$ karmadactl get pods --operation-scope all
NAME    CLUSTER   READY   STATUS    RESTARTS   AGE
nginx   Karmada   3/1     Running   0          26m
nginx   member1   1/1     Running   0          26m
nginx   member2   1/1     Running   0          26m
nginx   member3   1/1     Running   0          26m
$ karmadactl exec -it  nginx --operation-scope=members --cluster=member1 -- echo "hello"
hello
$ karmadactl exec -it  nginx --operation-scope=members --cluster=member2 -- echo "hello"
hello
$ karmadactl exec -it  nginx --operation-scope=members …
```

enhance karmadactl exec command

---

pkg/controllers/namespace/namespace_sync_controller_test.go

This PR introduces tests for namespace controller and adds a test file that significantly enchances its code coverage.
**Additions:**
1. Added a test file namespace_sync_controller_test.go in pkg/controllers/namespace directory.
**Test Coverage**:
Test coverage has been increased from 0% to 41.7%, reflecting the complexity of the controller. To check test coverage, run `go test -coverprofile=coverage.out` in the pkg/controllers/namespace directory.
**What type of PR is this**?
/kind feature
This PR enhances the testing coverage of the namespace controller, which is crucial for managing namespace operations and ensuring the controller’s stability and functionality. By adding these tests, we ensure that potential …

Added test for namespace controller

---

pkg/detector/handler_test.go

/kind feature
The test case coverage for pkg/detector/handler.go has been increased from 0% to 100%.
Fixes #
To verify the changes in the pkg/detector/ directory run the following commands:
```
```
```release-note
NONE
```

Improved test coverage for handler in pkg/detector

---

test/e2e/karmadactl_test.go

In this commit, we add e2e tests for the `karmadactl apply` command to ensure it handles various scenarios correctly. The tests include:
- Applying configurations without propagating them into member clusters.
- Applying configurations with propagation into specific member clusters.
- Applying configurations and propagating them to all member clusters.
- Verifying that no resources were created during `--dry-run` mode.
- Ensuring the command returns an error for an invalid flag.
- Ensuring the command returns an error when the specified file does not exist.
- Applying configurations with the `--namespace` flag to ensure resources are created in the specified namespace.
- Applying configurations with the `--force-conflicts` flag to ensure conflicts are forcefully resolved …

test/e2e/karmadactl_test.go: test apply command

---

pkg/scheduler/scheduler_test.go

/kind test
/kind flake
Part of #5235 
No
```release-note
None
```

Add some tests for `pkg/scheduler`

---

pkg/controllers/binding/common_test.go

/kind feature
This PR adds comprehensive unit tests for the following functions in the `binding` package:
- `needReviseReplicas`
- `divideReplicasByJobCompletions`
Fixes: #5235 
1. **Added Unit Tests for `needReviseReplicas`**:
- Covered various scenarios including:
- Replicas is zero.
- Placement is nil.
- Replica scheduling type is not divided.
- Replica scheduling type is divided.
2. **Added Unit Tests for `divideReplicasByJobCompletions`**:
- Covered various scenarios including:
- Completions found.
- Completions not found.
- Error in NestedInt64.
- 
- Ran all unit tests to ensure they pass.
- Verified that the new tests cover the intended scenarios and edge cases.

Added tests in pkg/binding for condition coverage

---

pkg/detector/policy_test.go

/kind feature
The test case coverage for pkg/detector/policy.go has been improved.
Fixes #
To verify the changes in the pkg/detector/ directory run the following commands:
```
```
```release-note
NONE
```

Improved test coverage for policy in pkg/detector

---

pkg/servicenameresolutiondetector/coredns/detector_test.go
pkg/servicenameresolutiondetector/store/condition_cache_test.go
pkg/servicenameresolutiondetector/store/node_store_test.go

This PR introduces tests for servicenameresolutiondetector package covering all the modules in each directory of it. 
*Additions:**
1. pkg/servicenameresolutiondetector/coredns/detector_test.go
2. pkg/servicenameresolutiondetector/store/condition_cache_test.go
3. pkg/servicenameresolutiondetector/store/node_store_test.go
The servicenameresolutiondetector package had a test coverage of 0.00%. The PR enhances its overall test coverage to more than 80%. The test coverage of pkg/servicenameresolutiondetector/coredns is enhanced to 74.3% and of pkg/servicenameresolutiondetector/store to 90.3%. This can be verified using `go test ./... -coverprofile=coverage.out` in the pkg/servicenameresolutiondetector directory.
/kind …

Added tests for pkg/servicenameresolutiondetector

---

pkg/controllers/status/work_status_controller.go
pkg/controllers/status/work_status_controller_test.go

/kind bug
As discussed in https://github.com/karmada-io/karmada/issues/5397 , we should not sync work status, because it attempts to update the resource in the member cluster
Fixes #5397
```release-note
```

fix: work status sync when work dispatching is suspended

---

operator/pkg/controller/context/context_test.go

**Description**:
This PR introduces tests for operator/pkg/controller/context/context.go.
**Additions**:
operator/pkg/controller/context/context_test.go:
1. TestIsControllerEnabled: This test checks various scenarios for the IsControllerEnabled function.
2. TestInitializersControllerNames: This test checks that the ControllerNames function of the Initializers type returns all known controller names correctly.
/kind feature
This PR adds comprehensive tests for testing core functionality of context controller.
Fixes a part of #5236 
```release-note
NONE
```

Added tests for operator/pkg/controller/context

---

pkg/karmadactl/top/metrics_printer.go
pkg/karmadactl/top/metrics_sorter.go
pkg/karmadactl/top/top.go
pkg/karmadactl/top/top_node.go

/kind feature
karmadactl supports top node
```shell
$ karmadactl top node
NAME                    CLUSTER   CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
member1-control-plane   member1   90m          2%     876Mi           5% 
member2-control-plane   member1   90m          2%     876Mi           5% 
member3-control-plane   member1   90m          2%     876Mi           5% 
$ karmadactl top node --clusters=member1
NAME                    CLUSTER   CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
member1-control-plane   member1   90m          2%     876Mi           5% 
```
Parts of #4217
none …

karmadactl supports top node

---

pkg/util/fedinformer/handlers_test.go
pkg/util/fedinformer/keys/keys_test.go
pkg/util/fedinformer/typedmanager/multi-cluster-manager_test.go
pkg/util/fedinformer/typedmanager/single-cluster-manager_test.go

**Description**:
This PR adds 3 new test files for pkg/util/fedinformer and enhances its code coverage and reliability of a critical component of the project. These new additions have increased its test coverage significantly.
**Additions:**
3 new test files are implemented in this PR.
1.  pkg/util/fedinformer/handlers_test.go
2.  pkg/util/fedinformer/typedmanager/multi-cluster-manager_test.go
3.  pkg/util/fedinformer/typedmanager/single-cluster-manager_test.go
/kind feature
This PR improves the test coverage and reliability of the fedinformer package, which is critical for the functionality of the project. Enhanced testing ensures better stability and performance. …

Added tests pkg/util/fedinformer

---

pkg/karmadactl/apiresources/apiresources.go
pkg/karmadactl/apiresources/apiversions.go
pkg/karmadactl/karmadactl.go

/kind feature
add new command karmadactl api-resources
Parts of #5249 
```release-note
`karmadactl`: add new command `api-resources` to print the supported API resources on the server in Karmada control plane or a member cluster.
`karmadactl`: add new command `api-versions` to print the supported API versions on the server in Karmada control plane or a member cluster.
```

add new command karmadactl api-resources

---

charts/karmada/templates/_karmada_apiservice.tpl

/kind bug
I did not enable the `metricsAdapter` component, so the metrics adapter-related deployment was not created:
https://github.com/karmada-io/karmada/blob/cd99897506a42b9398f5f958f1ffe6821414f419/charts/karmada/templates/karmada-metrics-adapter.yaml#L1
However, its `APIService` was still created, causing the controller-manager to continuously output the following error:
```
Discovery failed for some groups, 3 failing: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: stale GroupVersion discovery: custom.metrics.k8s.io/v1beta1, custom.metrics.k8s.io/v1beta2: stale GroupVersion discovery: custom.metrics.k8s.io/v1beta2, metrics.k8s.io/v1beta1: stale GroupVersion discovery: …
```

charts/karmada: fix the creation condition of metrics-adapter related APIService

---

pkg/karmadactl/explain/explain.go
pkg/karmadactl/karmadactl.go
vendor/k8s.io/kubectl/pkg/cmd/explain/explain.go
vendor/k8s.io/kubectl/pkg/explain/OWNERS
vendor/k8s.io/kubectl/pkg/explain/explain.go
vendor/k8s.io/kubectl/pkg/explain/field_lookup.go
vendor/k8s.io/kubectl/pkg/explain/fields_printer.go
vendor/k8s.io/kubectl/pkg/explain/fields_printer_builder.go
vendor/k8s.io/kubectl/pkg/explain/formatter.go
vendor/k8s.io/kubectl/pkg/explain/model_printer.go
vendor/k8s.io/kubectl/pkg/explain/recursive_fields_printer.go
vendor/k8s.io/kubectl/pkg/explain/test-recursive-swagger.json
vendor/k8s.io/kubectl/pkg/explain/test-swagger.json
vendor/k8s.io/kubectl/pkg/explain/typename.go
vendor/k8s.io/kubectl/pkg/explain/v2/explain.go
vendor/k8s.io/kubectl/pkg/explain/v2/funcs.go
vendor/k8s.io/kubectl/pkg/explain/v2/generator.go
vendor/k8s.io/kubectl/pkg/explain/v2/template.go
vendor/k8s.io/kubectl/pkg/explain/v2/templates/plaintext.tmpl
vendor/modules.txt

/kind feature
add new command karmadactl explain
```bash
$ karmadactl explain explain pods --operation-scope members --cluster member1
KIND:       Pod
VERSION:    v1
DESCRIPTION:
Pod is a collection of containers that can run on a host. This resource is
created by clients and scheduled onto hosts.
FIELDS:
apiVersion    <string>
APIVersion defines the versioned schema of this representation of an object.
Servers should convert recognized schemas to the latest internal value, and
may reject unrecognized values. More info:
https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
kind  <string>
Kind is a string value representing the REST resource this object
represents. Servers may infer …
```

add new command karmadactl explain

---

artifacts/deploy/karmada-scheduler-estimator.yaml
charts/karmada/templates/karmada-scheduler-estimator.yaml
cmd/scheduler-estimator/app/options/options.go
cmd/scheduler-estimator/app/options/validation.go
cmd/scheduler-estimator/app/options/validation_test.go
cmd/scheduler-estimator/app/scheduler-estimator.go
pkg/karmadactl/addons/estimator/manifests.go
pkg/karmadactl/cmdinit/utils/examples.go

/kind feature
/kind cleanup
part of https://github.com/karmada-io/karmada/issues/5219
```release-note
`karmada-scheduler-estimator`:  Add health probe argument `health-probe-bind-address` and metrics argument `metrics-bind-address`. Deprecate `--bind-address` and `--secure-port` flags.
```

Standardize the health probe and metrics arguments of scheduler-estimator

---

pkg/registry/search/storage/proxy_test.go

/kind feature
Fixes part of :  #5236
Added comprehensive unit tests for the `ProxyingREST` struct in the `proxy_test.go` file. The tests cover the following methods:
- `New`: Ensures that the `ProxyingREST` returns a new `Proxying` object.
- `NamespaceScoped`: Verifies that `NamespaceScoped` returns `false`.
- `ConnectMethods`: Confirms that the correct HTTP methods are returned.
- `NewConnectOptions`: Ensures it returns the expected default values.
- `Connect`: Tests proxying functionality with valid and invalid `RequestInfo`.
- `Destroy`: Validates the cleanup behavior (no-op for this implementation).
- `GetSingularName`: Checks that the correct singular name is returned.
**None**

Added UTs for proxy file 80% coverage

---

pkg/estimator/client/service_test.go

Added unit tests for service file in `pkg/estimator/client`  
This PR introduces unit tests for the `resolveCluster` and `findServicePort` functions in the `pkg/estimator/client` package. These tests aim to cover various scenarios including handling of `ExternalName` services, port mismatches, and errors related to service port types. This ensures better test coverage and reliability of the service handling logic.
**Which issue(s) this PR fixes**:  
Fixes issue with incomplete test coverage for service handling in the `pkg/estimator/client` package.
Fixes part of : #5235 
**Does this PR introduce a user-facing change?**:  
```release-note
NONE

Added tests for service file in pkg/estimator/client

---

artifacts/deploy/karmada-descheduler.yaml
charts/karmada/templates/karmada-descheduler.yaml
cmd/descheduler/app/descheduler.go
cmd/descheduler/app/options/options.go
cmd/descheduler/app/options/validation.go
cmd/descheduler/app/options/validation_test.go
operator/pkg/controlplane/manifests.go
pkg/karmadactl/addons/descheduler/manifests.go

/kind cleanup
/kind feature
part of https://github.com/karmada-io/karmada/issues/5219
```release-note
`karmada-descheduler`:  Add health probe argument `health-probe-bind-address` and metrics argument `metrics-bind-address`. Deprecate `--bind-address` and `--secure-port` flags.
```

Standardize the health probe and metrics arguments of descheduler

---

artifacts/deploy/karmada-controller-manager.yaml
charts/karmada/templates/karmada-controller-manager.yaml
cmd/controller-manager/app/controllermanager.go
cmd/controller-manager/app/options/options.go
cmd/controller-manager/app/options/validation.go
cmd/controller-manager/app/options/validation_test.go
operator/pkg/controlplane/manifests.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go

/kind feature
/kind cleanup
part of https://github.com/karmada-io/karmada/issues/5219
```release-note
`karmada-controller-manager`:  Add health probe argument `health-probe-bind-address`, and deprecate `--bind-address` and `--secure-port` flag.
```

Standardize the health probe argument of karmada-controller-manager

---

artifacts/deploy/karmada-scheduler.yaml
cmd/scheduler/app/options/options.go
cmd/scheduler/app/options/validation.go
cmd/scheduler/app/options/validation_test.go
cmd/scheduler/app/scheduler.go
operator/pkg/controlplane/manifests.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go

/kind cleanup
Part of https://github.com/karmada-io/karmada/issues/5219
/assign @whitewindmills @RainbowMango
Fixes #
```release-note
`karmada-scheduler`:  Add health probe argument `health-probe-bind-address` and metrics argument `metrics-bind-address`. Deprecate `--bind-address` and `--secure-port` flags.
```

Standardize the health probe and metrics arguments of scheduler.

---

examples/customresourceinterpreter/webhook/app/webhook_test.go
examples/customresourceinterpreter/webhook/app/workloadwebhook_test.go

This pr introduces tests for karmada/examples/customresourceinterpreter/webhook/app/workloadwebhook.go and webhook.go.
**Additions:**
1. workloadwebhook_test.go
2. webhook_test.go
/kind feature
This PR adds comprehensive tests for testing core functionality of customresourceinterpreter/webhook.
Fixes a part of #5236 
```release-note
NONE
```

Added tests for examples/customresourceinterpreter/webhook

---

pkg/controllers/certificate/cert_rotation_controller.go
pkg/controllers/certificate/cert_rotation_controller_test.go

/kind cleanup
Add the test for  /pkg/controllers/certificate, improve test coverage to 55%; 
found some places in `CertRotationController` did not use a unified context,  changed it together.
Part of #https://github.com/karmada-io/karmada/issues/5235
```release-note
NONE
```

Improve test coverage for /pkg/controllers/certificate, with a minor optimization

---

charts/karmada/templates/karmada-static-resource-job.yaml
charts/karmada/templates/post-install-job.yaml
charts/karmada/values.yaml

/kind cleanup
After #5305, we can now delete the static-resource job directly after its completion.
The new [`ttlSecondsAfterFinished` feature](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/) can handle this task elegantly. However, this feature only reached GA in version 1.23. Before this version, the feature requires manually enabling the feature gate, and we cannot assume that users' clusters have this feature gate enabled. Therefore, unlike the https://github.com/karmada-io/karmada/pull/5305#issuecomment-2313929232, considering that Karmada needs to run on various versions of Kubernetes, we cannot directly remove the post-install Job. The current strategy is:
1. For Kubernetes versions …

charts/karmada: automatically clean up the static-resource Job after it completes

---

pkg/karmadactl/top/top_pods.go
test/e2e/karmadactl_test.go

/kind cleanup
- Improve the example for the `top pod` command.
- Combine multiple `ginkgo.It` tests into one.
Parts  of #5249
```release-note
```

enhance top pod command

---

pkg/registry/cluster/storage/aggregate.go
pkg/registry/cluster/storage/aggregate_test.go

Fixes #5228 
```release-note
User can append a "/" at the end when configuring the cluster's apiEndpoint.
```

fix: remove extra slash when constructing member cluster URL if the apiEndpoint of the cluster object ends with a slash

---

cmd/descheduler/app/descheduler_test.go

This PR introduces tests for cmd/descheduler/app/descheduler.go .
/kind feature
This PR adds comprehensive tests for testing core functionality of cmd/descheduler .
Fixes a part of #5236 
```release-note
NONE
```

Added tests for cmd/descheduler

---

pkg/karmadactl/karmadactl.go
pkg/karmadactl/label/label.go
vendor/k8s.io/kubectl/pkg/cmd/label/label.go
vendor/modules.txt

/kind feature
add new command label
Parts of  #5249
```release-note
`karmadactl`: add a new command `label` to update the labels on a resource
```

add new command label

---

pkg/karmadactl/karmadactl.go
pkg/karmadactl/patch/patch.go
vendor/k8s.io/kubectl/pkg/cmd/patch/patch.go
vendor/modules.txt

/kind feature
add new command patch
Parts of #5249
```release-note
`karmadactl`: add new command `patch`  to update fields of a resource
```

add new command patch

---

artifacts/agent/karmada-agent.yaml
artifacts/deploy/karmada-controller-manager.yaml
artifacts/deploy/karmada-descheduler.yaml
artifacts/deploy/karmada-scheduler-estimator.yaml
artifacts/deploy/karmada-scheduler.yaml
artifacts/deploy/karmada-webhook.yaml

/kind cleanup
Fixes part of #5166
```release-note
Expose the metrics port for the karmada-controller-manager, scheduler、agent、karmada-webhook、descheduler and scheduler-estimator in local-up-karmada.
```

Expose metrics port for local-up installation

---

operator/pkg/controlplane/manifests.go
operator/pkg/controlplane/webhook/mainfests.go

/kind cleanup
Expose metrics port for operator installation
Fixes part of #5166
```release-note
Expose the metrics port for the karmada-controller-manager, scheduler、karmada-webhook and descheduler in operator installation.
```

Expose metrics port for operator installation

---

.github/workflows/release.yml

/kind cleanup
Only update krew index for latest stable version. Avoid sending noisy PRs and in the future,we don't need some PR anymore like:
- https://github.com/karmada-io/karmada/pull/4767
/cc @RainbowMango @zhzhuang-zju 
Ref https://github.com/karmada-io/karmada/issues/4703
Fixes #
Tested on my fork repo:
- https://github.com/liangyuanpeng/karmada/actions/runs/9987870100/job/27603262187  (release v1.10.2,running the step `Update krew index`)
- https://github.com/liangyuanpeng/karmada/actions/runs/9987694858  (release v1.99.3, skip the step`Update krew index` due to karmada latest stable version is v1.10.2 and not v1.99.3 )
**Does this PR introduce …

Only update krew index for latest stable version.

---

pkg/util/validation/validation.go
pkg/webhook/clusterpropagationpolicy/mutating.go
pkg/webhook/propagationpolicy/mutating.go
test/e2e/clusterpropagationpolicy_test.go
test/e2e/propagationpolicy_test.go

/kind feature
In the previous release, the names of PP and CPP are not allowed to exceed 63 characters. Now, we remove this limit.
Fix #4711
```release-note
karmada-webhook: Remove the limit of 63 name lengths with PropagationPolicy/ClusterPropagationPolicy resource.
```

Remove pp/cpp name length limit

---

cmd/scheduler/app/options/options_test.go
cmd/scheduler/app/scheduler_test.go

This PR introduces tests for cmd/scheduler/app/scheduler.go and cmd/scheduler/app/options/options.go .
/kind feature
This PR adds comprehensive tests for testing core functionality of cmd/scheduler .
Fixes a part of #5236 
The additions in this PR are similar to implemented in #5445 .
```release-note
NONE
```

Added tests for cmd/scheduler

---

pkg/controllers/status/cluster_status_controller.go
pkg/controllers/status/cluster_status_controller_test.go

Cherry pick of #5227 on release-1.9.
#5227: fix error of when cluster status condition update
```release-note
`karmada-controller-manager`: Fixed the error of cluster status old condition update will overwrite the newest condition.
```

Automated cherry pick of #5227: fix error of when cluster status condition update

---

.github/workflows/release.yml

/kind cleanup
https://github.com/karmada-io/karmada/actions/runs/10645084310/job/29510560441
```shell
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
github action has made some updates. If you use the gh command, you must pass the GH_TOKEN env
/hold 
Let me test the whole process in the fork repo
/assign @RainbowMango @zhzhuang-zju 
Fixes #
```release-note
```

ci: add github token for update-krew-index

---

.github/workflows/release.yml

Cherry pick of #5469 on release-1.11.
#5469: ci: add github token for update-krew-index
```release-note
NONE
```

Automated cherry pick of #5469: ci: add github token for update-krew-index

---

hack/tools/genkarmadactldocs/gen_karmadactl_docs.go
pkg/karmadactl/annotate/annotate.go
pkg/karmadactl/apiresources/apiresources.go
pkg/karmadactl/apiresources/apiversions.go
pkg/karmadactl/attach/attach.go
pkg/karmadactl/create/create.go
pkg/karmadactl/delete/delete.go
pkg/karmadactl/edit/edit.go
pkg/karmadactl/explain/explain.go
pkg/karmadactl/label/label.go
pkg/karmadactl/patch/patch.go
pkg/karmadactl/top/top.go
pkg/karmadactl/util/command_group.go

/kind cleanup
The `commandGroup` annotation for the ctl command is used for filtering commands when generating the [karmadactl index doc](https://karmada.io/docs/reference/karmadactl/karmadactl-commands/karmadactl_index). Therefore, the appropriate annotations need to be added to the ctl command to prevent the generated documentation from missing relevant sections.
Fixes #
```release-note
NONE
```

add commandGroup annotation to ctl command

---

pkg/karmadactl/apiresources/apiresources.go
pkg/karmadactl/apiresources/apiversions.go
pkg/karmadactl/attach/attach.go
pkg/karmadactl/describe/describe.go
pkg/karmadactl/exec/exec.go
pkg/karmadactl/explain/explain.go
pkg/karmadactl/get/get.go

/kind feature
The operation-scope flag gets used a lot when examining resources on member clusters. The 's' shorthand was added to improve user QoL.
```release-note
`karmadactl`: Added shorthand letter `s` to 'operation-scope' flags across commands.
```

feat: Added 's' shorthand to operation-scope flags

---

pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/statefulset.go
pkg/karmadactl/cmdinit/kubernetes/statefulset_test.go

/kind feature
Supports the function of --etcd-node-selector-labels for multiple labels of nodes in the cluster
```release-note
user@virtual-machine:karmada/_output/bin/linux/amd64# ./karmadactl init --etcd-node-selector-labels karmada.io/etcd=true,kubernetes.io/os=linux
I0830 09:58:51.083493    7186 deploy.go:111] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"0c4ff310f2d3bba4c54a513c62bc4110e5353b32", GitTreeState:"clean", BuildDate:"2024-08-30T01:35:17Z", GoVersion:"go1.22.6", Compiler:"gc", Platform:"linux/amd64"}
I0830 09:58:51.083581    7186 enable_option.go:85] No default release version found. build version: version.Info{GitVersion:"", …
```

Support multiple label selection ability in EtcdNodeSelectorLabels

---

pkg/webhook/resourcedeletionprotection/validating_test.go

In this commit, we add unit tests for the `ValidatingAdmission` validation webhook specifically for the resource deletion protection feature. These tests ensure that the webhook correctly handles various admission scenarios:
- Tests the behavior when decoding the request object fails, verifying that admission is denied with an appropriate error message.
- Ensures that resources labeled with `DeletionProtectionAlways` are denied deletion, validating that the error message is returned.
- Confirms that resources without the deletion protection label are allowed to be deleted without errors.
- Validates that resources with other labels are not impacted and are allowed to be deleted.
- Confirms that non-delete operations (e.g., create) are allowed by default.
**What type of PR …

pkg/webhook: unit test resource deletion protection

---

pkg/webhook/propagationpolicy/mutating_test.go
pkg/webhook/propagationpolicy/validating_test.go

In this commit, we introduce unit tests for both the `ValidatingAdmission` and `MutatingAdmission` webhooks for the `PropagationPolicy` resource.
- Tests how the webhook responds when decoding the request object fails.
- Ensures that updates to the `SchedulerName` field are denied, as it should remain immutable.
- Validates that changes to the `PropagationPolicyPermanentIDLabel` label and its absence in creation requests are correctly handled.
- Confirms that valid `PropagationPolicy` objects are allowed through without errors.
- Provides full coverage of policy mutation with default values and patch application.
**What type of PR is …

pkg/webhook: unit test propagation policy

---

cmd/descheduler/app/options/options.go
cmd/scheduler/app/options/options.go
cmd/scheduler/app/scheduler.go
pkg/descheduler/descheduler.go
pkg/estimator/client/cache.go
pkg/scheduler/scheduler.go
pkg/scheduler/scheduler_test.go

/kind feature
When the scheduler estimator feature is enabled for the Karmada scheduler component, we can then provision scheduler estimator instances for member clusters that will provide the scheduler with more accurate information regarding resources for those member clusters. 
To gain that information, given some member cluster, the scheduler needs to contact the service for that member cluster's scheduler estimator deployment. As of today, it uses a naming convention for discovering those services. By default, given some member cluster `m1`, it will look for a service named `karmada-scheduler-estimator-m1` in the `karmada-system` namespace.
The service name prefix is …

Add the Ability to Specify the Namespace Used for Discovering Scheduler Estimator Services

---

.github/workflows/ci-schedule-compatibility.yaml
.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/cli.yaml

/kind cleanup
- update CI for kubernetes 1.31
- schedule workflow for release-1.11
Fixes #
```release-note
```

chore: update ci for kubernetes 1.31 and schedule for release-1.11

---

pkg/controllers/namespace/namespace_sync_controller_test.go
pkg/util/overridemanager/commandargsoverride_test.go
pkg/util/overridemanager/imageoverride_test.go
pkg/util/overridemanager/overridemanager_test.go
pkg/util/validation/validation_test.go
test/e2e/clusteroverridepolicy_test.go
test/e2e/failover_test.go
test/e2e/overridepolicy_test.go

In this commit, we unify the usage of `policyv1alpha1` operators, specifically `OverriderOpAdd`, `OverriderOpRemove`, and `OverriderOpReplace`.
/kind cleanup
**Additional Context**
While testing the override policy (#5495), I identified an opportunity to improve consistency by unifying the operators, leading to this submission.
```release-note
NONE
```

pkg+test: unify the usage of policyv1alpha1 operators

---

cmd/scheduler-estimator/app/options/options.go
pkg/karmadactl/addons/estimator/manifests.go

/kind bug
/kind cleanup
fix launch arguments when install estimator by karmadactl which caused its installation failure
```shell
$ kubectl get pods -o wide -n karmada-system
...
karmada-system       karmada-scheduler-estimator-member4-774fd8d76c-skjj9            0/1     Error     1 (9s ago)   10s   10.91.0.17   karmada-karmadactl-host-control-plane   <none>           <none>
...
$ kubectl logs -f  karmada-scheduler-estimator-member4-774fd8d76c-skjj9 -n karmada-system                                                    
Usage:
karmada-scheduler-estimator [flags]
...
Error: unknown flag: --client-cert-auth
```
Fixes # …

Fix `karmadactl addon` failed to install karmada-scheduler-estimator due to unknown flag

---

charts/OWNERS

/kind cleanup
This PR nominates @a7i and @chaosi-zju as the owners of the helm chart.
Both @a7i and @chaosi-zju have been contributing significantly to the helm chart for a long time. 
Their expertise are evident in every PR they sent and reviewed. Given their deep knowledge of the codebase and his commitment to the quality, I believe they are the perfect fit for this role.
Fixes #
```release-note
NONE
```

Nominates Amir and Chaosi as the owners of helm chart

---

docs/proposals/karmada-operator/external-etcd-credentials-ref/README.md

/kind design
Details are provided in the proposal.
Fixes #
```release-note
NONE
```

Proposal: Enhance `EcternalEtcd` Configuration to Support Retrieving etcd Client Credentials from a Kubernetes Secret

---

pkg/webhook/clusterpropagationpolicy/mutating.go
pkg/webhook/multiclusterservice/mutating.go
pkg/webhook/overridepolicy/mutating.go

In this commit, we log the mutating handlers for `OverridePolicy`, `ClusterPropagationPolicy`, and `MultiClusterService`. Specifically, it logs information about the mutation of these resources, including the namespace, name, and the operation type from the admission request.
During testing of the multi-cluster service webhook (#5517), I observed that all mutating webhook handlers include logging functionality, except for the handlers related to `OverridePolicy`, `ClusterPropagationPolicy`, and `MultiClusterService`. Adding logging to these handlers will improve debugging and enhance visibility into the operations they handle, which is the purpose of this PR.
/kind feature …

pkg/webhook: log mutating handlers in `OverridePolicy`, `ClusterPropagationPolicy`, and `MultiClusterService`

---

pkg/controllers/federatedhpa/config/types_test.go
pkg/controllers/federatedhpa/federatedhpa_controller_test.go
pkg/controllers/federatedhpa/metrics/client_test.go
pkg/controllers/federatedhpa/replica_calculator_test.go

This PR introduces the first set of comprehensive unit tests for the Federated Horizontal Pod Autoscaler (FederatedHPA) controller and its associated components. Due to the extensive nature of the test additions, i'll try to split the test additions into 2 PR's.
**Additions:**
1. FederatedHPA Controller (pkg/controllers/federatedhpa/federatedhpa_controller_test.go)
2. Metrics Client (pkg/controllers/federatedhpa/metrics/client_test.go)
3. Replica Calculator (pkg/controllers/federatedhpa/replica_calculator_test.go)
4. Config Types (pkg/controllers/federatedhpa/config/types_test.go)
**Test Coverage Improvements:**
federatedhpa_controller_test.go: 0% to 41.2% (More tests will be added in the future PR)
client_test.go: 0% to 92.9%
replica_calculator_test.go: 0% to 85.7% …

Added tests for federatedhpa controller

---

pkg/webhook/work/mutating_test.go

In this commit, we introduce unit tests for the `MutatingAdmission` webhook specifically for the `Work` resource. The mutation webhook tests include the following:
- Provides full coverage of policy mutation, including setting default and validating no unnecessary patches.
Part of #5491.
```release-note
NONE
```

pkg/webhook: unit test Work

---

pkg/webhook/multiclusterservice/mutating_test.go
pkg/webhook/multiclusterservice/validating_test.go

In this commit, we introduce unit tests for both the `ValidationAdmission` and `MutatingAdmission` webooks specifically for the `MultiClusterService` resource.
- Tests the behavior when decoding the request object fails, verifying that admission is denied with an appropriate error message.
- Validates that the webhook denies admission when encountering invalid values in the `MultiClusterService` spec, ensuring error messaging.
- Confirms that valid `MultiClusterService` objects are admitted without errors.
- Provides full coverage of `MultiClusterService` object mutation, including setting default namespaces and validating no …

pkg/webhook: unit test Multi-Cluster Service

---

docs/proposals/karmada-operator/api-server-extra-volumes-volume-mounts/README.md

/kind design
- Details are contained in the proposal.
Fixes #
```release-note
NONE
```

Proposal: Support to Specify Extra Volumes and Volume Mounts for Karmada Control Plane Components

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/util/patcher/pather.go

/kind feature
Today, when creating a Karmada instance to be managed by the Karmada operator, it's possible to specify extra args for the control plane components. However, it's not possible to specify extra volumes and volume mounts. This feature request is for providing the ability to specify extra volumes and volume mounts for the Karmada components.
**Why is this needed**:
At Bloomberg, we're currently building a managed Karmada platform and want to use the Karmada operator to manage the entire lifecycle of managed Karmada instances. We have tenants who have requirements such as the following:
- Ability to configure custom AuthN webhook
- Ability to configure encryption at rest
Given that it's already possible to …

Support to Specify Extra Volumes and Volume Mounts for Karmada API Server Component

---

pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller_test.go
pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller_test.go

This PR introduces comprehensive unit tests for the Federated Resource Quota controller and for parts which are not much complex to test.
**Additions:**
1. Federated Resource Quota Sync Controller (pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller_test.go)
2. Federated Resource Quota Status Controller (pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller_test.go)
**Test Coverage Improvements:**
1. federated_resource_quota_sync_controller_test.go : 0% to 55.2%
2. federated_resource_quota_status_controller_test.go: 0% to 48.4%
Federated Resource Quota Controller Coverage: 0% to 51.3%
/kind feature
**Does this PR …

Added tests for federatedresourcequota controller

---

pkg/webhook/propagationpolicy/mutating_test.go

In this commit, we refactor propagation policy names and check on number of patches after the mutation happens.
Motivated by @XiShanYongYe-Chang's comment https://github.com/karmada-io/karmada/pull/5494#discussion_r1758148145.
/kind cleanup
Follow-up on #5492.
```release-note
NONE
```

pkg/webhook: refactor Propagation Policy test

---

pkg/webhook/clusterpropagationpolicy/mutating_test.go
pkg/webhook/clusterpropagationpolicy/validating_test.go

In this commit, we introduce unit tests for both the `ValidatingAdmission` and `MutatingAdmission` webhooks for the `ClusterPropagationPolicy` resource.
- Tests how the webhook responds when decoding the request object fails.
- Ensures updates to the `SchedulerName` field are denied, as it should remain immutable.
- Validates that changes to the `ClusterPropagationPolicyPermanentIDLabel` label and its absence in creation requests are correctly handled.
- Confirms that valid `ClusterPropagationPolicy` objects are allowed through without errors.
- Provides full coverage of cluster policy mutation with default values and patch application. …

pkg/webhook: unit test cluster propagation policy

---

pkg/apis/cluster/types.go
pkg/apis/cluster/v1alpha1/types.go
pkg/controllers/status/cluster_status_controller.go

/kind feature
since https://github.com/karmada-io/karmada/pull/5325 is closed, I open this PR to do it.
Fixes #1804
```release-note
API change: Introduced a new condition `CompleteAPIEnablements` to represent api collection status of clusters.
```

add new cluster condition: CompleteAPIEnablements

---

operator/pkg/controlplane/controlplane.go

/kind bug
A recent change introduced new flags for configuring mTLS for the [Karmada Scheduler](https://github.com/karmada-io/karmada/blob/release-1.11/operator/pkg/controlplane/manifests.go#L195) & [Descheduler](https://github.com/karmada-io/karmada/blob/release-1.11/operator/pkg/controlplane/manifests.go#L262) components. As such, the manifest templates for those components were changed accordingly to reflect the new change. Configuration of the new flags now require that a volume be [mounted](https://github.com/karmada-io/karmada/blob/release-1.11/operator/pkg/controlplane/manifests.go#L222) to use as the source of the TLS data. However, it looks like there's one more change required that was missed.
**Which issue(s) …

Fix mTLS Configuration for Karmada Scheduler & Descheduler Components

---

operator/pkg/controlplane/controlplane.go

Cherry pick of #5546 on release-1.11.
#5546: Set Karmada Cert Secret Used For Configurating mTLS for
```release-note
`karmada-operator`: Fixed the issue where the manifests for the `karmada-scheduler` and `karmada-descheduler` components were not parsed correctly.
```

Automated cherry pick of #5546: Set Karmada Cert Secret Used For Configurating mTLS for

---

docs/CHANGELOG/CHANGELOG-1.10.md
docs/CHANGELOG/CHANGELOG-1.11.md
docs/CHANGELOG/CHANGELOG-1.9.md

publish release note for v1.11.1, v1.10.5, v1,9.7
Fixes #
/hold
waiting for #5319 #5519
```release-note
```

publish release note for v1.11.1, v1.10.5, v1.9.7

---

cmd/agent/app/agent.go
cmd/agent/app/options/options.go

/kind cleanup
part of https://github.com/karmada-io/karmada/issues/5547
```release-note
`karmada-agent`: Removed `--bind-address` and `--secure-port` flags which were deprecated in release-1.11 and replaced by `--health-probe-bind-address` and `--metrics-bind-address`.
```

Remove deprecated `--bind-address` and `--secure-port` from `karmada-agent`

---

pkg/scheduler/framework/plugins/apienablement/api_enablement.go

/kind bug
Because when obtaining APIEnablements, it may be empty or partial.
This will cause the scheduler to delete the scheduling results, resulting in incorrect deletion
So if the cluster is already in the list of scheduling results, even if the API is not hit, skip the filter
https://github.com/karmada-io/karmada/blob/a87ec2a61abadf9f102440b1f64cf338b2ee5518/pkg/controllers/status/cluster_status_controller.go#L233-L239
Fixes #
```release-note
```

skip the filter if the cluster is already in the list of scheduling result even if the API is missed

---

artifacts/deploy/karmada-controller-manager.yaml
charts/karmada/templates/karmada-controller-manager.yaml
cmd/controller-manager/app/controllermanager.go
cmd/controller-manager/app/options/options.go

/kind cleanup
part of https://github.com/karmada-io/karmada/issues/5547
```release-note
`karmada-controller-manager`: Removed `--bind-address` and `--secure-port` flags which were deprecated in release-1.11 and replaced by `--health-probe-bind-address` and `--metrics-bind-address`.
```

Removed deprecated `--bind-address` and `--bind-address` from `karmada-controller-manager`

---

artifacts/deploy/karmada-scheduler-estimator.yaml
charts/karmada/templates/karmada-scheduler-estimator.yaml
cmd/scheduler-estimator/app/options/options.go
cmd/scheduler-estimator/app/scheduler-estimator.go
pkg/karmadactl/addons/estimator/manifests.go
pkg/karmadactl/cmdinit/utils/examples.go

/kind cleanup
part of https://github.com/karmada-io/karmada/issues/5547
Based on this [comment](https://github.com/karmada-io/karmada/pull/5273#discussion_r1732080241), I assign different default values to `--metrics-bind-address` and `--health-probe-bind-address`. I've chosen to align with other components by using `8080` as the default for `--metrics-bind-address`.
```
`karmada-scheduler-estimator`: Removed `--bind-address` and `--secure-port` flags which were deprecated in release-1.11 and replaced by `--health-probe-bind-address` and `--metrics-bind-address`.
```

Remove deprecated `--bind-address` and `--bind-address` from `karmada-scheduler-estimator`

---

pkg/webhook/resourceinterpretercustomization/validation_test.go

In this commit, we introduce unit tests for `ValidationAdmission` webhook for the `ResourceInterpreterCustomization` resource. The tests include:
- Tests how the webhook responds when decoding the request object fails.
- Tests how the webhook responds when it fails to retrieve list of objects from a namespace.
- Ensures that invalid `ResourceInterpreterCustomization` spec denies the admission.
- Confirms that valid `ResourceInterpreterCustomization` spec are allowed through without errors.
Part of #5491.
```release-note
NONE
```

pkg/webhook: unit test ResourceInterpreterCustomization

---

pkg/karmadactl/annotate/annotate.go
pkg/karmadactl/apiresources/apiresources.go
pkg/karmadactl/apiresources/apiversions.go
pkg/karmadactl/apply/apply.go
pkg/karmadactl/attach/attach.go
pkg/karmadactl/completion/completion.go
pkg/karmadactl/cordon/cordon.go
pkg/karmadactl/create/create.go
pkg/karmadactl/delete/delete.go
pkg/karmadactl/describe/describe.go
pkg/karmadactl/edit/edit.go
pkg/karmadactl/exec/exec.go
pkg/karmadactl/explain/explain.go
pkg/karmadactl/get/get.go
pkg/karmadactl/interpret/interpret.go
pkg/karmadactl/join/join.go
pkg/karmadactl/karmadactl.go
pkg/karmadactl/label/label.go
pkg/karmadactl/logs/logs.go
pkg/karmadactl/patch/patch.go
pkg/karmadactl/promote/promote.go
pkg/karmadactl/taint/taint.go
pkg/karmadactl/token/token.go
pkg/karmadactl/top/top_node.go
pkg/karmadactl/top/top_pods.go
pkg/karmadactl/unjoin/unjoin.go
pkg/karmadactl/util/completion/completion.go

/kind feature
Implementing autocompletion for karmadactl, which can save you a lot of typing.
Parts of #5477
```release-note
`karmadactl`: Implementing autocompletion for karmadactl to save a lot of typing
```

Implementing autocompletion for karmadactl

---

pkg/webhook/federatedresourcequota/validating_test.go

In this commit, we refactor `FederatedResourceQuota` webhook mainly matching on substrings instead of whole strings for reliability and resilience and reformat the test case names to follow format `Function_Scenario_ExpectedResult` for better readability.
/kind cleanup
Follow-up of #5287.
```release-note
NONE
```

pkg/webhook: refactor Federated Resource Quota test

---

pkg/webhook/multiclusteringress/validating_test.go

In this commit we introduce unit tests for the `Validation Admission`. These tests ensure correct behavior for various validation scenarios and improve coverage:
- Tests the behavior when decoding the request object fails, verifying that admission is denied with an appropriate error message.
- Validates that the webhook denies admission when encountering invalid values in the `MultiClusterIngress` spec, ensuring error messaging.
- Confirms that valid `MultiClusterIngress` objects are admitted without errors.
Part of #5491.
**Dependency**:
~~This PR depends on #5520.~~
```release-note
NONE
```

pkg/webhook: unit test Multi-Cluster Ingress

---

pkg/webhook/overridepolicy/mutating_test.go
pkg/webhook/overridepolicy/validating_test.go

In this commit, we introduce unit tests for both the `ValidationAdmission` and `MutatingAdmission` webhooks specifically for the `OverridePolicy` resource.
- Tests the behavior when decoding the request object fails, verifying that admission is denied with an appropriate error message.
- Validates that the webhook denies admission when encountering invalid label values in the `OverridePolicy` spec, ensuring proper error messaging.
- Confirms that valid `OverridePolicy` objects are admitted without errors.
- Provides full coverage of policy mutation, including setting default namespaces and validating no unnecessary patches.
**What type …

pkg/webhook: unit test override policy

---

pkg/webhook/clusteroverridepolicy/validating_test.go

In this commit, we add unit tests for the `ValidationAdmission` webhook specifically for the `ClusterOverridePolicy` resource. These tests ensure that the webhook correctly handles various admission scenarios:
- Tests the behavior when decoding the request object fails, verifying that the admission is denied with an approriate error message.
- Validates that the webhook denies admission when encountering invalid label values in the `ClusterOverridePolicy` spec, ensuring proper error messaging.
- Confirms that valid `ClusterOverridePolicy` objects are admissionly allowed without errors.
/kind feature
Part of #5491
```release-note
NONE
```

pkg/webhook: unit test cluster override policy

---

pkg/webhook/resourcebinding/mutating_test.go

In this commit, we introduce unit tests for the `MutatingAdmission` webhook that mutates the `ResourceBinding` resource. These tests ensure correct behavior for various mutation scenarios and improve coverage:
- Testing the handling of decode errors and ensuring that admission is denied when decoding fails.
- Full coverage testing of policy mutation, including setting default UUID labels for the `ResourceBinding`.
- Verifying that only the expected patch for the UUID label is applied, ensuring no other unnecessary mutations.
/kind feature
Part of #5491
```release-note
NONE
```

pkg/webhook: unit test resource binding

---

pkg/webhook/clusterresourcebinding/mutating_test.go

In this commit, we introduce unit tests for the `MutatingAdmission` webhook that mutates the `ClusterResourceBinding` resource. These tests ensure correct behavior for various mutation scenarios and improve coverage:
- Testing the handling of decode errors and ensuring that admission is denied when decoding fails.
- Full coverage testing of policy mutation, including setting default UUID labels for the `ClusterResourceBinding`.
- Verifying that only the expected patch for the UUID label is applied, ensuring no other unnecessary mutations.
/kind feature
Part of #5491
```release-note
NONE
```

pkg/webhook: unit test cluster resource binding

---

artifacts/deploy/karmada-scheduler.yaml
charts/karmada/templates/karmada-scheduler.yaml
cmd/scheduler/app/options/options.go
cmd/scheduler/app/options/options_test.go
cmd/scheduler/app/options/validation.go
cmd/scheduler/app/options/validation_test.go
cmd/scheduler/app/scheduler.go
operator/pkg/controlplane/manifests.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go

/kind cleanup
Remove deprecated --bind-address and --secure-port from karmada-scheduler
Fixes part of #5547
```release-note
`karmada-scheduler`: Removed `--bind-address` and `--secure-port` flags which were deprecated in release-1.11 and replaced by `--health-probe-bind-address` and `--metrics-bind-address`.
```

Remove deprecated --bind-address and --secure-port from karmada-scheduler

---

pkg/webhook/federatedresourcequota/validating_test.go
pkg/webhook/multiclusteringress/validating_test.go

An intermittent error was found on the master branch, 
```log
=== FAIL: pkg/webhook/federatedresourcequota TestValidatingAdmission_Handle/Handle_ExceedResourceLimits_ResourceLimitsExceeded (0.00s)
E0921 06:46:06.951602   28812 validating.go:55] [spec.overall[memory]: Invalid value: "5Gi": overall is less than assignments spec.overall[cpu]: Invalid value: "5": overall is less than assignments]
validating_test.go:432: Handle() = {Type: Denied, Message: [spec.overall[memory]: Invalid value: "5Gi": overall is less than assignments, spec.overall[cpu]: Invalid value: "5": overall is less than assignments]}, want {Type: Denied, Message: spec.overall[cpu]: Invalid value: "5": overall is less than assignments, …
```

fix ut failed in federatedresourcequota

---

artifacts/deploy/karmada-descheduler.yaml
charts/karmada/templates/karmada-descheduler.yaml
cmd/descheduler/app/descheduler.go
cmd/descheduler/app/options/options.go
cmd/descheduler/app/options/validation_test.go
operator/pkg/controlplane/manifests.go
pkg/karmadactl/addons/descheduler/manifests.go

/kind cleanup
Remove deprecated --bind-address and --secure-port from karmada-descheduler
Fixes part of #5547
```release-note
`karmada-descheduler`: Removed `--bind-address` and `--secure-port` flags which were deprecated in release-1.11 and replaced by `--health-probe-bind-address` and `--metrics-bind-address`.
```

Remove deprecated --bind-address and --secure-port from karmada-descheduler

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
pkg/apis/work/v1alpha1/work_types.go
pkg/apis/work/v1alpha1/zz_generated.deepcopy.go
pkg/apis/work/v1alpha2/binding_types.go
pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
pkg/generated/openapi/zz_generated.openapi.go

This PR proposes the API change to address the requirement of #5101.
Fixes #
```release-note
API Change: Introduced `PreserveResourcesOnDeletion` field to both PropagationPolicy and ClusterPropagationPolicy API, which provides the ability to roll back migration safely. 
```

Proposing API to support migration rollback

---

pkg/webhook/federatedhpa/mutating_test.go
pkg/webhook/federatedhpa/validating_test.go

In this commit, we introduce unit tests for both the `MutatingAdmission` and `ValidatingAdmission` webhooks specifically for the `FederatedHPA` resource.
- Verifies that admission is denied with an appropriate error message when decoding the request object fails.
- Ensures admission is denied when the `FederatedHPA` spec contains invalid values, such as a `minReplicas` set to zero, and the correct error message is returned.
- Confirms that a valid `FederatedHPA` object is allowed through without errors.
- Verifies that admission is denied when decoding the request object fails, returning the appropriate error message.
- Ensures that the `FederatedHPA` object is correctly mutated when provided with …

pkg/webhook: unit test Federated HPA

---

operator/pkg/karmadaresource/rbac/manifest.go
operator/pkg/karmadaresource/rbac/rbac.go
operator/pkg/util/apiclient/idempotency.go

/kind bug
auto authorize system:admin to proxy member clusters in operation install method
Fixes #5571
test report:
```shell
$ karmadactl --karmada-context karmada-apiserver get deploy --operation-scope members
NAME    CLUSTER   READY   UP-TO-DATE   AVAILABLE   AGE   ADOPTION
nginx   member1   1/1     1            1           9s    Y
```
```release-note
`karmada-operator`: Fixed `system:admin` can not proxy to member cluster issue.
```

`karmada-operator`: Grand proxy permission to system:admin

---

docs/proposals/structured-configuration/README.md

/kind design
Overriding values inside JSON and YAML to simplify modifications.
Fixes #5330
Related PR: #5329 
```release-note
Introduced `FieldOverrider ` for overriding values in YAML or JSON.
```

Overriding values inside JSON and YAML

---

operator/README.md

In this commit, we redirect users to the latest `karmada-operator` tag.
Fixes #5578
```release-note
NONE
```

operator/README.md: redirect users to the latest `karmada-operator` released tag

---

pkg/controllers/unifiedauth/unified_auth_controller_test.go

This PR enhances the unit tests for the Unified Auth Controller in the unifiedauth package. The improvements aim to increase code reliability, maintainability, and test coverage for the Unified Auth Controller.
**Additions and Modifications:**
1. pkg/controllers/unifiedauth/unified_auth_controller_test.go
1. unified_auth_controller_test.go: 25.30% to 71.3%
Overall coverage of unifiedauth controller: 25.30% to 71.3%
/kind feature
```release-note
NONE
```

Added tests for unifiedauth controller

---

operator/pkg/scheme/scheme_test.go

In this commit, we unit test the init scheme functionality of the operator by checking that both k8s core scheme and operator v1alpha1 scheme are added.
Part of #5491.
```release-note
NONE
```

operator/pkg/scheme: unit test scheme

---

pkg/controllers/remediation/remedy_controller_test.go

This PR enhances the unit tests for the Remedy Controller in the remediation package. The improvements aim to increase code reliability, maintainability, and test coverage for the Remedy Controller.
**Additions and Modifications:**
1. pkg/controllers/remediation/remedy_controller_test.go
1. remedy_controller_test.go: 0% to 74.4%
Overall coverage of remediation controller: 68.82% to 86.5%
/kind feature
```release-note
NONE
```

Added tests for remediation controller

---

operator/pkg/karmadaresource/webhookconfiguration/webhookconfiguration_test.go

In this commit, we introduce unit tests for mutating and validating webhook configurations to make sure they are working as expected.
Part of #5491.
```release-note
NONE
```

operator/pkg/karmadaresource: unit test `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration`

---

pkg/karmadactl/promote/promote.go

/kind feature
Let `karmadactl promote` command leverage [migration rollback](https://github.com/karmada-io/karmada/issues/5577) feature to guarantee the promotion can be rolled back safely. 
To address the issue #3004 sent by @chaunceyjiang .
Fixes part of #5577
Fixes #3004
```release-note
karmadactl: set `PreserveResourcesOnDeletion` by default in auto-created propagation policy during promotion process 
```

guarantee the promotion can be rolled back safely

---

pkg/modeling/modeling.go

/kind bug
when the "getIndex" fails, display more data details in logs.
Fixes # add more details in the log.
```release-note
```

Show more debug logs when failed to build resource model due to `getIndex` fails

---

pkg/controllers/workloadrebalancer/workloadrebalancer_controller_test.go

This PR adds a new test case for cluster-wide resources and refactors the existing test structure for the WorkloadRebalancer controller. These changes aim to improve code coverage and reduce cyclomatic complexity.
**Changes:**
1. Added a new test case for cluster-wide resource rebalancing:
- This test case ensures that the controller correctly handles cluster-wide resources, improving our coverage of different resource types.
2. Refactored the TestRebalancerController_Reconcile function:
- Extracted the test execution logic into a separate function (runRebalancerTest).
- Moved binding check logic into separate functions (checkBindings, checkClusterBinding, checkResourceBinding).
- These changes reduce the cyclomatic complexity of the main test function, making it easier …

Improved test coverage for workloadrebalancer controller

---

operator/pkg/util/kubeconfig.go
pkg/controllers/status/cluster_status_controller.go
pkg/karmadactl/cmdinit/karmada/deploy.go
pkg/karmadactl/util/apiclient/apiclient.go

In this commit, we apply the Dependency Inversion Principle by depending on an interface instead of a concrete type. This improves flexibility and testability.
While testing the Karmada Init and DeInit in the operator package (#5613), I found it difficult to mock `*clientset.Clientset`, complicating unit tests. By refactoring to depend on an interface, we improve flexibility and testability, allowing for the integration of a fake clientset since it implements that interface.
/kind cleanup
```release-note
NONE
```

operator+pkg:  depend on `clientset.Interface` instead of `*clientset.Clientset`

---

.github/workflows/ci-image-scanning-on-schedule.yml

Add the workflow to scan release version images(release-1.5/1.6/1.7) on schedule.
Fixes #none
Refer to https://github.com/zhzhuang-zju/karmada/actions/runs/6662001229
```release-note
NONE
```

ci: add schedule image-scanning

---

hack/local-up-karmada.sh

/kind feature
supports specifying whether need making local images in local up installation
Fixes #
```release-note
NONE
```

Allow `hack/local-up-karmada.sh` to use latest pre-built images

---

charts/index.yaml
charts/karmada-operator/Chart.yaml
charts/karmada/Chart.yaml

/kind cleanup
Add helm index for v1.10.0 and v1.11.0
these two new version can't be searched by helm, as you see:
```shell
$ helm search repo karmada-charts -l
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                      
karmada-charts/karmada          v1.9.0          latest          A Helm chart for karmada         
karmada-charts/karmada          v1.8.0          v1.1.0          A Helm chart for karmada         
karmada-charts/karmada          v1.7.1          v1.1.0          A Helm chart for karmada         
karmada-charts/karmada          v1.7.0          v1.1.0          A Helm chart for karmada         
karmada-charts/karmada          v1.6.2          v1.1.0          A Helm chart for …
```

Add helm index for v1.10.0 and v1.11.0

---

pkg/resourceinterpreter/default/native/dependencies.go
pkg/resourceinterpreter/default/native/dependencies_test.go

/kind bug
It was incorrectly handling PVCs when it belongs to the StatefulSet VolumeClaimTemplates.
If you set the claim name in the to match the StatefulSet VolumeClaimTemplate the StatefulSet controller would replace it for the pod, so the name isn't a backed by a real pvc.
create the following statefulset, and note the pod created has a claim with name `www-web-0`
```yaml
kind: StatefulSet
metadata:
name: web
spec:
selector:
matchLabels:
app: nginx # has to match .spec.template.metadata.labels
serviceName: "nginx"
replicas: 3 # by default is 1
minReadySeconds: 10 # by default is 0
template:
metadata:
labels:
app: nginx # has to match .spec.selector.matchLabels
spec:
volumes:
- name: www …
```

Avoid treating PVC managed by VolumeClaimTemplate as dependencies

---

docs/proposals/karmadactl/init-configuration-file.md

/kind feature
karmadactl supports configuration file installation and deployment
Parts of [#3464](https://github.com/karmada-io/karmada/issues/3464) 
```release-note
```

docs: add proposal of karmadactl init support config file

---

pkg/controllers/status/work_status_controller.go
pkg/controllers/status/work_status_controller_test.go

/kind feature
In one of our small staging clusters, we get a lot of InterpretHealthFailed events (over 100k per week). After investigations, it seems to be resources such as ClusterRole and ClusterRoleBinding that never have a status, so there is nothing to inspect.
This is also repeated over and over again in karmada-controller-manager logs:
```
"Interpret health of object(ClusterRole//oncall) failed, err: default InterpretHealth interpreter for \"rbac.authorization.k8s.io/v1, Kind=ClusterRole\" not found." logger="events" type="Warning" object={"kind":"Work","namespace":"karmada-es-REDACTED","name":"oncall-76bd899f7f","uid":"7a93a59e-3196-4192-975c-ccdc3dd5e6f7","apiVersion":"work.karmada.io/v1alpha1","resourceVersion": …
```

skip interpret health of resources without a hook

---

go.mod
pkg/util/overridemanager/overridemanager.go
pkg/util/overridemanager/overridemanager_test.go
pkg/util/validation/validation.go
pkg/webhook/overridepolicy/validating_test.go
test/e2e/coverage_docs/overridepolicy_test.md
test/e2e/overridepolicy_test.go

/kind feature
The proposal introduces a new feature that allows users to partially override values inside  JSON and YAML fields. This is achieved using JSON patch operation. This design enables users to to override the values within JSON/YAML fields partially, rather than replacing a whole JSON/YAML fields with `PlaintextOverrider`. Currently, `PlaintextOverrider`  applies JSON patch operations to whole fields, rather than specific values within fields, making it unsuitable for cases where users need to override individual values within those fields.
Fixes #5330
Proposal: #5449 
Related PR: #5329, #5581 …

feat: add fieldoverrider

---

pkg/descheduler/descheduler_test.go

This pull request enhances the Descheduler component with comprehensive unit tests and improved error handling. The new tests aim to improve code reliability, maintainability, and overall test coverage for descheduling operations.
Added error handling tests in the worker function, including:
1. Handling invalid key types
2. Dealing with invalid resource key formats
3. Proper handling of ResourceBindings that are not found or being deleted
1. pkg/descheduler/descheduler.go
1. pkg/descheduler/descheduler.go : 59.14% to 80.80%
/kind feature
```release-note
NONE
```

Added tests for pkg/descheduler/descheduler.go

---

pkg/scheduler/framework/plugins/apienablement/api_enablement_test.go
pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity_test.go
pkg/scheduler/framework/plugins/clustereviction/cluster_eviction_test.go
pkg/scheduler/framework/plugins/clusterlocality/cluster_locality_test.go
pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint_test.go
pkg/scheduler/framework/plugins/tainttoleration/taint_toleration_test.go

This PR enhances the test coverage for various scheduler plugins by adding comprehensive unit tests. These additions aim to increase code reliability, maintainability, and ensure proper functionality of the scheduler plugins.
**Additions:**
1. pkg/scheduler/framework/plugins/apienablement/api_enablement_test.go
2. pkg/scheduler/framework/plugins/clusteraffinity/cluster_affinity_test.go
3. pkg/scheduler/framework/plugins/clustereviction/cluster_eviction_test.go
4. pkg/scheduler/framework/plugins/clusterlocality/cluster_locality_test.go
5. pkg/scheduler/framework/plugins/spreadconstraint/spread_constraint_test.go
6. pkg/scheduler/framework/plugins/tainttoleration/taint_toleration_test.go
1. pkg/scheduler/framework/plugins/apienablement/api_enablement_test. …

Added tests for scheduler plugins

---

pkg/webhook/interpreter/decode.go
pkg/webhook/interpreter/decode_test.go
pkg/webhook/interpreter/http_test.go
pkg/webhook/interpreter/inject_test.go
pkg/webhook/interpreter/response_test.go
pkg/webhook/interpreter/webhook_test.go

In this commit, we introduce unit tests for the `Interpreter` webhook across `Decoder`, `HTTP`, `Injection`, `Response`, and `Webhook` components.
Part of #5491.
```release-note
NONE
```

pkg/webhook: unit test Interpreter

---

operator/pkg/tasks/deinit/test_helpers.go
operator/pkg/tasks/init/test_helpers.go
operator/pkg/util/util.go

Add test helpers that would be reused across tasks in the operator package.
/kind cleanup
```release-note
NONE
```

operator/pkg: add test helpers

---

pkg/detector/claim.go
pkg/detector/claim_test.go
pkg/detector/detector.go
pkg/detector/policy.go
pkg/detector/policy_test.go

/kind cleanup
refer to #3845, pp will preempt cpp regardless of priority. And it will also clean up the labels used to mark cpp during the preemption process. However, currently only the labels are being cleaned up, and the annotations are being left behind. This results in the same resource having both the annotation marking pp and the annotation marking cpp, like
```yaml
apiVersion: work.karmada.io/v1alpha2
kind: ResourceBinding
metadata:
annotations:
clusterpropagationpolicy.karmada.io/name: test-cpp
policy.karmada.io/applied-placement: '{"clusterTolerations":[{"key":"cluster.karmada.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"cluster.karmada.io/unreachable","operator":"Exist …
```

Clean up the residual annotations when resources are preempted by pp from cpp

---

pkg/detector/claim.go
pkg/detector/claim_test.go
pkg/detector/detector.go

/kind bug
Refer to #5307, there is a chance that poliy marks be lost when deleting the old pp/cpp and binding a new one. When performing a clean up of marks on rb/crb, we can compare the value of the label `policyv1alpha1.ClusterPropagationPolicyPermanentIDLabel/policyv1alpha1.PolicyPermanentIDLabel` on the cb/crb with the policyId value of the deleted CPP/PP. If they are not the same, it indicates that the rb/crb has already claimed to a new CPP/PP, and there is no need to clean up the label/annotation.
Fixes #5307
```release-note
`karmada-controller-manager`: Fixed an issue that policy claim metadata …
```

skip cleanup when the poliy claim metadata changed

---

pkg/scheduler/cache/cache_test.go

This PR enhances the unit tests for the Scheduler Cache in the cache package. The improvements aim to increase code reliability, maintainability, and test coverage for the Scheduler Cache.
**Additions:**
1. pkg/scheduler/cache/cache_test.go
pkg/cache : 7.50% to 100%
/kind feature
```release-note
NONE
```

Added tests for scheduler/cache

---

pkg/descheduler/core/filter_test.go
pkg/descheduler/core/helper_test.go

This PR introduces new test cases and refractors the old tests for the core components of descheduler. It adds new test cases in `pkg/descheduler/core/filter_test.go` and refactors old tests in `pkg/descheduler/core/helper_test.go` to a table-driven approach, thus testing more scenarios. The new tests aim to improve code reliability, maintainability, and overall test coverage for core descheduling operations.
1. pkg/descheduler/core/filter_test.go:
- Added new test cases for testing filter bindings.
- Added new test cases for validating GVK (Group Version Kind) and placement annotations.
- Introduced tests for handling invalid JSON in placement annotations and various edge cases.
2. pkg/descheduler/core/helper_test.go:
- Refactored …

Added new tests and refractored old in pkg/descheduler/core

---

pkg/util/lifted/validatingfhpa_test.go

This PR introduces unit tests for the FederatedHPA validation functions in the lifted package. The additions aim to increase code reliability, maintainability, and test coverage for the FederatedHPA validation logic.
**Additions:**
1. pkg/util/lifted/validatingfhpa_test.go
1. pkg/util/lifted/validatingfhpa.go : 0.00% to 100%
/kind feature
```release-note
NONE
```

Added unit tests for FederatedHPA validation

---

operator/pkg/util/template_test.go

In this commit, we unit test template on parsing template functionality on parsing and executing html templates with passed args.
Part of #5491.
```release-note
NONE
```

operator/pkg/util: unit test template

---

operator/pkg/util/naming_test.go

In this commit, we unit test naming `generateResourceName` utility on given karmada component name and suffix.
Part of #5491.
```release-note
NONE
```

operator/pkg/util: unit test naming

---

operator/pkg/util/kubeconfig.go
operator/pkg/util/kubeconfig_test.go

In this commit, we unit test kubeconfig utility in the karmada operator package on building client from secret reference and checking whether the given cluster is local or remote.
Part of #5491.
```release-note
NONE
```

operator/pkg/util: unit test kubeconfig

---

pkg/scheduler/core/common_test.go

This PR introduces comprehensive unit tests for the common scheduling functions in the scheduler package. The new tests aim to improve code reliability, maintainability, and overall test coverage for core scheduling operations.
**Additions:**
1. pkg/scheduler/core/common_test.go
1. pkg/scheduler/core/common_test.go : 0% to 95.20%
This is can be verified in  _pkg/scheduler/core_ directory using 
```
```
/kind feature
```release-note
NONE
```

Added tests pkg/scheduler/core/common.go

---

pkg/util/validation/validation.go
pkg/webhook/overridepolicy/validating_test.go

/kind feature
feat: validate fieldOverrider operation
Part of #5608
```release-note
`karmada-webhook`: validate fieldOverrider operation.
```

feat: validate fieldOverrider operation

---

pkg/scheduler/framework/interface_test.go
pkg/scheduler/framework/types_test.go
pkg/scheduler/metrics/metrics_test.go

This PR introduces unit tests for the metrics, interface and types in the scheduler package. The improvements aim to increase code reliability, maintainability, and test coverage of the scheduler.
**Additions:**
1. pkg/scheduler/framework/interface_test.go
2. pkg/scheduler/framework/types_test.go
3. pkg/scheduler/metrics/metrics_test.go
1. pkg/scheduler/framework/interface_test.go : 100%
2. pkg/scheduler/framework/types_test.go : 100%
3. pkg/scheduler/metrics/metrics_test.go : 100%
/kind feature
```release-note
NONE
```

Added tests for metrics and framework package of pkg/scheduler

---

operator/pkg/controlplane/webhook/webhook_test.go

In this commit, we include unit tests for karmada webhook in the operator controlplane package making sure that installing karmada webhook and its associated service are working as expected.
Part of #5491.
```release-note
NONE
```

operator/pkg/controlplane: unit test karmada webhook

---

operator/pkg/controlplane/controlplane_test.go

In this commit, we add unit tests for Kube Controller Manager, Karmada Controller Manager, Karmada Scheduler, and Karmada Descheduler components.
Part of #5491.
```release-note
NONE
```

operator/pkg/controlplane: unit test controlplane

---

operator/pkg/tasks/init/apiserver_test.go
operator/pkg/util/apiclient/test_helpers.go

In this commit, we introduce unit tests for the apiserver init task in the operator pkg by testing the running and waiting operations on Karmada API Server and Karmada Aggregated API Server.
Part of #5491.
Depends on #5630.
```release-note
NONE
```

operator/pkg/tasks: unit test apiserver

---

operator/pkg/tasks/deinit/cert_test.go

In this commit, we unit test the cert deinit task on the clean up operations.
Part of #5491.
Depends on #5630.
```release-note
NONE
```

operator/pkg/tasks/deinit: unit test cert

---

pkg/resourceinterpreter/default/native/dependencies.go
pkg/resourceinterpreter/default/native/dependencies_test.go

Cherry pick of #5568 on release-1.11.
#5568: fix sts pvc logic
Part of #5656 
```release-note
`karmada-controller-manager`: Ignored StatefulSet Dependencies with PVCs created via the VolumeClaimTemplates.
```

Automated cherry pick of #5568: Avoid treating PVC managed by VolumeClaimTemplate as dependencies

---

operator/pkg/tasks/init/wait.go
operator/pkg/tasks/init/wait_test.go

In this commit, we unit test wait init task on waiting for Karmada APIServer and Karmada Control Plane components.
Part of #5491.
Depends on #5624.
```release-note
NONE
```

operator/pkg/tasks/init: unit test wait

---

pkg/util/lifted/validateclustertaints_test.go
pkg/util/lifted/validatingmcs_test.go

This PR introduces unit tests for the cluster taints validation and MCS (Multi-Cluster Services) validation functions in the pkg/util/lifted package. These additions aim to increase code reliability, maintainability, and test coverage for the cluster taints and MCS validation logic.
**Additions:**
1. pkg/util/lifted/validateclustertaints_test.go
2. pkg/util/lifted/validatingmcs_test.go
1. pkg/util/lifted/validateclustertaints.go: 0.00% to 100%
2. pkg/util/lifted/validatingmcs.go: 0.00% to 100%
/kind feature
Fixes a part of #5470
```release-note
NONE
```

Added tests for validateclustertaints.go and validatingmcs.go

---

pkg/util/lifted/podtemplate_test.go

This PR introduces unit tests for the podtemplate.go file in the pkg/util/lifted package. The additions aim to increase code reliability, maintainability, and test coverage for the pod template handling logic.
**Additions:**
1. pkg/util/lifted/podtemplate_test.go
pkg/util/lifted/podtemplate.go: 0.00% to 100%
/kind feature
```release-note
NONE
```

Added unit tests for pkg/util/lifted/podtemplate.go

---

operator/pkg/tasks/deinit/component.go
operator/pkg/tasks/deinit/component_test.go

In this commit, we unit test component deinit task in the karmada operator package on removing component subtasks and etcd component.
Part of #5491.
```release-note
NONE
```

operator/pkg/tasks/deinit: unit test component

---

operator/pkg/tasks/deinit/kubeconfig_test.go

In this commit, we unit test kubeconfig deinit task in the operator package on cleaning up the secret if it has the given labels.
Part of #5491.
```release-note
NONE
```

operator/pkg/tasks/deinit: unit test kubeconfig

---

pkg/scheduler/scheduler_test.go

This PR significantly enhances the unit tests for the scheduler package and is the first part of unit tests for it. The improvements aim to increase code reliability, maintainability, and test coverage for various scheduler functions.
**Note:**
The CI tests will fail because the mocks needed for tests are included in second part of unit tests for scheduler module.
pkg/scheduler/scheduler_test.go
**Key Improvements:**
Added tests for doSchedule, doScheduleBinding, and doScheduleClusterBinding functions.
Added tests for scheduleResourceBindingWithClusterAffinity and scheduleResourceBindingWithClusterAffinities.
Added tests for patchScheduleResultForResourceBinding.
pkg/scheduler/scheduler_test.go: 29.71% to 66.90%
**What type of PR is …

Added first part of unit tests for pkg/scheduler

---

pkg/util/membercluster_client_test.go

**Description:** 
This PR enhances the unit tests for member cluster client functions in pkg/util/membercluster_client.go. It introduces new tests for previously uncovered functions and refactors existing tests to use the `assert` package from `testify`. These changes significantly improve test readability, and maintainability while ensuring comprehensive coverage of the member cluster client functionality.
**Improvements:**
1. pkg/util/membercluster_client_test.go:
- Added new tests for `NewClusterScaleClientSet`, `NewClusterClientSetForAgent`, and `NewClusterDynamicClientSetForAgent`
- Refactored existing tests to use `assert` for improved readability and better error messages
1. pkg/util/membercluster_client.go: 57% to 92.1%
/kind feature …

Added tests for pkg/util/membercluster_client_test.go

---

pkg/util/lifted/corev1printers_test.go

This PR introduces comprehensive unit tests for node-related functions in pkg/util/lifted/corev1printers.go. These additions significantly improve the test coverage and ensure the reliability of node handling and printing logic in the Karmada project.
**Improvements:**
1. pkg/util/lifted/corev1printers_test.go
1. pkg/util/lifted/corev1printers.go : 8.76 to 52.70%
/kind feature
```release-note
NONE
```

Added first part of unit tests for pkg/util/lifted/corev1printers.go

---

pkg/scheduler/scheduler_test.go

This PR significantly enhances the unit tests for the scheduler package and is the second part of unit tests for it. The improvements aim to increase code reliability, maintainability, and test coverage for various scheduler functions.
**Note:**
The CI tests might fail because the imports needed for tests are included in the first part of unit tests for scheduler module.
pkg/scheduler/scheduler_test.go
**Key Improvements:**
1. Added tests for scheduleClusterResourceBindingWithClusterAffinity and scheduleClusterResourceBindingWithClusterAffinities.
2. Added tests for the worker functionality and scheduleNext method.
3. Added tests for the placementChanged function.
4. Added new test cases for the TestCreateScheduler …

Added second part of unit tests for pkg/scheduler

---

operator/pkg/util/patcher/pather_test.go

In this commit, we unit test the patcher in the karmada operator pkg on patching the Deployment and StatefulSet k8s manifests.
Part of #5491.
```release-note
NONE
```

operator/pkg/util: unit test patcher

---

operator/pkg/certs/certs.go

In this commit, we fix the null pointer dereference issue that happens in altnames mutators for both Karmada APIServer and EtcdServer when accessing the `Components` field on `AltNamesMutatorConfig` struct.
In testing the Certificate Manager and Karmada Store (#5559), empty `Components` in [AltNamesMutatorConfig struct](https://github.com/karmada-io/karmada/blob/4c8bcd4af157ce68bc000da4974ec4d07a4b27fc/operator/pkg/certs/certs.go#L56) triggered a null pointer dereference in both APIServer and EtcdServer AltNames mutators. This PR resolves that issue.
/kind bug
```release-note
NONE
```

operator/pkg/certs: mitigate potential null pointer dereference in AltNames Mutators for both the `APIServer` and `EtcdServer`

---

operator/pkg/workflow/job_test.go

In this commit, we unit test the job workflow in the operator package on initializing the running data runtime interface and running tasks and subtasks recursively.
Part of #5491.
```release-note
NONE
```

operator/pkg/workflow: unit test job

---

operator/pkg/karmadaresource/apiservice/apiservice.go
operator/pkg/util/apiclient/idempotency.go
pkg/karmadactl/addons/init/global.go
pkg/karmadactl/cmdinit/karmada/check.go
pkg/karmadactl/util/apiclient/apiclient.go
pkg/karmadactl/util/idempotency.go
pkg/karmadactl/util/validate.go

In this commit, we apply the Dependency Inversion Principle by depending on an interface instead of a concrete type. This improves flexibility and testability.
While testing the KarmadaResource API service operator package (#5596), I found it difficult to mock *aggregator.Clientset, complicating unit tests. By refactoring to depend on an interface, we improve flexibility and testability, allowing for the integration of a fake aggregator clientset since it implements that interface.
/kind cleanup
```release-note
NONE
```

operator/pkg: depend on `aggregator.Interface` instead of `*aggregator.Clientset`

---

operator/pkg/controlplane/search/search_test.go

In this commit, we include unit tests for karmada search in the operator control plane package to make sure installing karmada search and its associated service are working as expected.
Part of #5491
```release-note
NONE
```

operator/pkg/controlplane: unit test karmada search

---

operator/pkg/controlplane/metricsadapter/metricsadapter_test.go

In this commit, we add unit tests for the metrics adapter controlplane pkg of the operator making sure that installing Karmada Metrics Adapter Deployment works as expect and its associated service.
Part of #5491
```release-note
NONE
```

operator/pkg/controlplane: unit test Metrics Adapter

---

operator/pkg/karmadaresource/rbac/rbac_test.go

In this commit, we add unit tests for the RBAC in the karamada resource operator pkg making sure Karmada Resource View Clusterrole and Karmada Resource Edit Clusterrole are working as expected.
Part of #5491.
```release-note
NONE
```

operator/pkg/karmadaresource: unit test RBAC

---

operator/pkg/controlplane/apiserver/apiserver_test.go

In this commit, we introduce unit tests for both control plane apiserver and aggregated apiserver for the operator.
Part of #5491
```release-note
NONE
```

operator/pkg/controlplane: unit test apiserver

---

operator/pkg/controlplane/etcd/etcd_test.go

In this commit, we include unit test cases for the etcd controlplane pkg of the operator making sure that installing Karmada Etcd Statefulset works as expected and its associated Etcd client/peer services.
Part of #5491
```release-note
NONE
```

operator/pkg/controlplane: unit test etcd

---

.github/workflows/release.yml

failed ci link:
https://github.com/karmada-io/karmada/actions/runs/11399514762/job/31718886970
refer to https://github.com/aquasecurity/trivy-action/issues/404#issuecomment-2406987466, replacing `scan-ref: /github/workspace/` with `scan-ref: ${{ github.workspace }}/` to fix the problem.
Fixes #
local verification：
https://github.com/zhzhuang-zju/karmada/actions/runs/11400139818/job/31720357994
```release-note
```

fix the error lstat /github/workspace: no such file or directory

---

operator/config/samples/karmada.yaml

/kind cleanup
This PR updates the image tags for Karmada components, etcd, and kube-apiserver in the sample file from `v1.8.0` to `v1.11.1`. Manual updates are necessary to reflect the latest version until dynamic configuration is implemented.
Part of #5484 update [sample file of karmada operator](https://github.com/karmada-io/karmada/blob/master/operator/config/samples/karmada.yaml)
This is a temporary manual update, as future plans involve implementing dynamic configuration.
```release-note
NONE
```

chore: update image tags for Karmada components to v1.11.1

---

operator/pkg/certs/certs.go
pkg/karmadactl/cmdinit/cert/cert.go

In this commit, we enhance the `GeneratePrivateKey` and `ParsePrivateKeyPEM` functions:
- Added validation for unsupported key types and provided a more descriptive error message. This function supports ECDSA (using P-256) and RSA (with a key size of 3072 bits) algorithms. It returns an error for unsupported key types.
- Improved error handling to include the type of the unsupported key format in the error message. This function now provides more informative feedback when the private key format is neither RSA nor ECDSA.
During the testing of the Certificate Manager and Karmada Store (#5559), it was observed that when unsupported key types such as `UnknownPublicKeyAlgorithm`, `DSA`, or `Ed25519` (as documented in the [Go standard library crypto …

operator/pkg/certs: validate X509 Cert key types and improve error handling

---

pkg/estimator/client/cache.go
pkg/estimator/client/service.go
pkg/estimator/client/service_test.go
pkg/util/grpcconnection/config.go

/kind feature
when dial scheduler-estimator, use ServiceName/serviceNamspace instead of the full domain name. Because the DNS suffix `.svc.cluster.local` is configurable
Fixes #
```release-note
```

karmada-scheduler-estimator add the support for custom DNS suffix

---

artifacts/deploy/karmada-aggregated-apiserver.yaml
artifacts/deploy/karmada-apiserver.yaml
artifacts/deploy/karmada-ca-cert-secret.yaml
artifacts/deploy/karmada-cert-secret.yaml
artifacts/deploy/karmada-descheduler.yaml
artifacts/deploy/karmada-etcd.yaml
artifacts/deploy/karmada-key-pair-secret.yaml
artifacts/deploy/karmada-metrics-adapter.yaml
artifacts/deploy/karmada-scheduler-estimator.yaml
artifacts/deploy/karmada-scheduler.yaml
artifacts/deploy/karmada-search.yaml
artifacts/deploy/karmada-webhook.yaml
artifacts/deploy/kube-controller-manager.yaml
examples/customresourceinterpreter/karmada-interpreter-webhook-example.yaml
hack/deploy-karmada.sh
hack/util.sh

/kind cleanup
In karmada, here are two important secrets, which is mount by most karmada components. One is karmada-cert, which contains a series of cert files like ca.crt, apiserver.crt and so on; another is karmada-kubeconfig, which contains a kubeconfig of karmada-apiserver.
However, in different installation methods, we used inconsistent secret naming or file path naming, which can potentially cause some unnecessary problems, detail refer to #5363.
This PR aims to standardize the naming of karmada secrets in local up installation method.
Fixes part of #5363
```release-note
standardize the naming of …
```

standardize the naming of karmada secrets in local up method

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
operator/pkg/constants/constants.go
operator/pkg/controller/karmada/controller.go

/kind feature
This is an implementation of this [proposal](https://github.com/karmada-io/karmada/pull/5260) for adding support to the Karmada operator for external etcd cluster connections.
Fixes #5242
```release-note
The new `SecretRef` field added as part of the configuration for connecting to an external etcd cluster can be 
used to reference a secret that contains credentials for connecting to an external etcd cluster.
```

External `etcd` Support for Karmada Operator - Part 1

---

hack/scan-image-vuln.sh

/kind cleanup
- Updated Trivy Version: Changed the version from v0.48.1 to v0.53.0 to ensure consistency across local usage and GitHub CI.
Part of https://github.com/karmada-io/karmada/issues/5484 update [hack/scan-image-vuln.sh](https://github.com/karmada-io/karmada/blob/master/hack/scan-image-vuln.sh)
- This change aligns the Trivy version used in the script with the version used in the CI workflow.
**Does this PR introduce a user-facing change?**
```release-note
NONE

chore(hack): upgrade Trivy to v0.56.1 for consistency with CI

---

operator/pkg/certs/certs_test.go
operator/pkg/certs/store_test.go
operator/pkg/util/util.go

In this commit, we introduce unit tests for operator `certs` package. The test cases include but not limited to:
- Test private key generation.
- Test self-signed certificate authority (CA) generation.
- Verify creation of self-signed certificate and key files within the CA.
- Include tests for utility functions, such as appending to Subject Alternative Names in SSL/TLS certificates.
- Add tests for Karmada Store operations related to certificates stored in Kubernetes Secrets:
- Create
- Read
- Update
- Load
Part of #5491.
**Dependency**
This PR depends on #5560 and #5561.
```release-note
NONE
```

operator/pkg/certs: unit test Certificate Manager and Karmada Store

---

pkg/controllers/cronfederatedhpa/cronfederatedhpa_handler_test.go
pkg/controllers/cronfederatedhpa/cronfederatedhpa_job_test.go

This PR introduces tests for cronfederatedhpa controller. This PR tests the cronfederatedhpa_handler and some functions of cronfederatedhpa_job module. The cronfederatedhpa_controller module is harder and complex to test and we could approach it after completion of tests which are necessary, maintainable and easy.
The test coverage of the directory _pkg/controllers/cronfederatedhpa_ has been increased from 0.00% to 27.8%. 
/kind feature
This PR adds comprehensive tests for testing functionality of cronfederatedhpa controller.
```release-note …
```

Added tests for cronfederatedhpa controller

---

operator/pkg/tasks/init/cert.go
operator/pkg/tasks/init/cert_test.go

In this commit, we introduce unit tests for the cert operator package, covering tasks such as creating new certificates, running existing certificates, and skipping certificates.
Part of #5491.
Depends on #5561 and #5630.
```release-note
NONE
```

operator/pkg/tasks/init: unit test cert 

---

operator/pkg/tasks/init/rbac_test.go

In this commit, we unit test rbac in the karmada init task operator package by checking that cluster roles and their associated cluster role bindings are created as expected.
Part of #5491.
**Dependency**
This PR depends on #5630.
```release-note
NONE
```

operator/pkg/tasks/init: unit test rbac

---

operator/pkg/certs/store_test.go

In this commit, we fix flaky test in `store_test.go` by using `GetCert` to retrieve secrets instead of unreliable `CertList` indexing due to non-guarnteed map order.
Motivated by @RainbowMango's comment https://github.com/karmada-io/karmada/pull/5559#issuecomment-2426597145.
Follow-up on #5559
```release-note
NONE
```

operator/pkg/certs/store_test: fix flaky test `TestCertList`

---

pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go
pkg/search/proxy/store/multi_cluster_cache.go
pkg/search/proxy/store/multi_cluster_cache_test.go
pkg/search/proxy/testing/mock_store.go

/kind bug
For detailed information of in tree plugins' execution order, please see:
// https://github.com/karmada-io/karmada/tree/master/docs/proposals/resource-aggregation-proxy#request-routing
But in fact, I found that if the requested resource is defined in ResourceRegistry but there is no cluster, the query is the resource of the karmada apiserver
```
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
name: test
spec:
- apiVersion: v1
kind: Node
- apiVersion: v1
kind: Pod
- apiVersion: v1
kind: Namespace
```
This will cause two problems
case1.When there is no cluster registered, the query resource comes from karmada-apiserver
case2.When using watch, after deleting all clusters, …

hasResource should return whether resource is matched not cached

---

operator/README.md
operator/config/deploy/karmada-operator-clusterrole.yaml
operator/config/deploy/karmada-operator-clusterrolebinding.yaml
operator/config/deploy/karmada-operator-deployment.yaml
operator/config/deploy/karmada-operator-serviceaccount.yaml

/kind feature
Part of #5182
```release-note
NONE
```

minimize the rbac permissions for karmada-operator

---

pkg/controllers/gracefuleviction/crb_graceful_eviction_controller_test.go
pkg/controllers/gracefuleviction/evictiontask_test.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller_test.go

This PR adds comprehensive unit tests for the ResourceBinding (RB) and ClusterResourceBinding (CRB) graceful eviction controllers.
**Additions:**
1. pkg/controllers/gracefuleviction/crb_graceful_eviction_controller_test.go
2. pkg/controllers/gracefuleviction/rb_graceful_eviction_controller_test.go
Additionally, a new test case has been added to the `Test_nextRetry` function in `evictiontask_test.go` to increase coverage.
1. crb_graceful_eviction_controller_test.go : 0% to 62.5%
2. rb_graceful_eviction_controller_test.go : 0% to 62.5%
3. evictiontask_test.go : 98% to 100%
Overall graceful eviction controller : 35.90% to 76.7%
/kind feature
**Does this …

Added tests for graceful eviction controller

---

pkg/estimator/client/general.go
pkg/estimator/client/general_test.go

/kind bug
Fixes #
Found this issue during the review of documents at https://github.com/karmada-io/website/pull/713#issuecomment-2414368554 by @LavredisG. 
Given the resource model:
```yaml
resourceModels:
- grade: 0
ranges:
- max: "1"
min: "0"
name: cpu
- grade: 1
ranges:
- max: "2"
min: "1"
name: cpu
- grade: 2
ranges:
- max: "4"
min: "2"
name: cpu
```
If a Pod request 1 CPU, `grade 1` will be selected.
If a Pod request 1.5 CPU, `grade 1` will be ignored as we are not sure it can provide sufficient resources.
```release-note
`karmada-scheduler`: Fixes an issue where resource model grades were …
```

Fixes incorrect resource model selection

---

pkg/estimator/client/general.go

Cherry pick of #5685 on release-1.11.
#5685: add ResourceSummary deep copy in general-estimator
```release-note
`karmada-scheduler`: Fixed unexpected modification of original `ResourceSummary` due to lack of deep copy.
```

Automated cherry pick of #5685: add ResourceSummary deep copy in general-estimator

---

pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go
pkg/search/proxy/store/multi_cluster_cache.go
pkg/search/proxy/store/multi_cluster_cache_test.go
pkg/search/proxy/testing/mock_store.go

Cherry pick of #5662 on release-1.9.
#5662: HasResource should return whether resource is registered not
Part of https://github.com/karmada-io/karmada/issues/5718
```release-note
`karmada-search`: Modify the logic of checking whether the resource is registered when selecting the plugin .
```

Automated cherry pick of #5662: HasResource should return whether resource is registered not

---

pkg/dependenciesdistributor/dependencies_distributor.go

/kind feature
When users enable dependency distribution for a resource template, it will inherit the `PreserveResourcesOnDeletion` policy from the resource they are following. As a result, we can rollback the migration of dependency distributed resources.
Part of #5577 
```release-note
`karmada-controller-manager`: keep preserveResourcesOnDeletion of the dependent resource consistent with that of the primary resource
```

Keep preserveResourcesOnDeletion of the dependent resource consistent with that of the primary resource

---

hack/deploy-karmada.sh
hack/util.sh

/kind feature
Execute `karmadactl token create` command failed, because the cluster is set `insecure-skip-tls-verify=true` in karmada config, that is a insecure config.
So, this PR add CA data to local up generated karmada config for enhanced security.
Fixes #5738
test report:
```shell
$ karmadactl token create --print-register-command --kubeconfig ~/.kube/karmada.config --karmada-context karmada-apiserver                                                                                
karmadactl register 172.18.0.4:5443 --token yqnbkt.muyyaah5omv1s24d --discovery-token-ca-cert-hash sha256:4f12a0f772cdaecfb7e150992f627485485d75922ddae5080bcb50a79bf22971 …
```

add CA data to local up generated karmada config for enhanced security

---

pkg/estimator/client/general.go
pkg/estimator/client/general_test.go

Cherry pick of #5706 on release-1.11.
#5706: Fixes an issue where resource model grades were incorrectly
```release-note
`karmada-scheduler`: Fixes an issue where resource model grades were incorrectly matched based on resource requests. Now only grades that can provide sufficient resources will be selected.
```

Automated cherry pick of #5706: Fixes an issue where resource model grades were incorrectly

---

.github/workflows/operator.yaml
hack/deploy-karmada-by-operator.sh
hack/deploy-karmada-operator.sh
hack/deploy-karmada.sh
hack/local-up-karmada-by-operator.sh
hack/util.sh
operator/config/samples/karmada-sample.yaml

/kind feature
The current `karmada-operator` lacks code merge access control; this PR will introduce:
- A one-click script to install a Karmada instance through the `karmada-operator`.
- karmada-operator ci
Fixes #
```release-note
```

add ci for karmada operator

---

pkg/util/context_test.go
pkg/util/policy_test.go
pkg/util/round_trippers_test.go

This PR introduces comprehensive unit tests for utility functions in the pkg/util package. These additions aim to increase code reliability, maintainability, and test coverage for the context handling, proxy header round tripper, and policy activation logic.
**Additions:**
1. pkg/util/context_test.go
2. pkg/util/round_trippers_test.go
3. pkg/util/policy_test.go
1. pkg/util/context.go : 0% to 100%
2. pkg/util/round_trippers.go : 0% to 100%
3. pkg/util/policy.go : 0% to 100%
/kind feature
```release-note
NONE
```

Added tests for utility functions in the pkg/util

---

pkg/detector/detector_test.go

This PR significantly enhances the unit tests for the detector package, focusing on the ResourceDetector component. The improvements aim to increase code reliability, maintainability, and test coverage for various detector functions.
1. pkg/detector/detector_test.go
**Key Improvements:**
- Implemented tests for GVRDisabled function
- Added tests for NeedLeaderElection and EventFilter function
- Implemented comprehensive tests for OnAdd, OnUpdate, and OnDelete functions
- Added tests for LookForMatchedPolicy and LookForMatchedClusterPolicy functions
- Added tests for ApplyPolicy and ApplyClusterPolicy functions
- Created mock implementations for various interfaces to facilitate testing
Test Coverage:
pkg/detector/detector.go: 1.60% to 32.60%
**What type …

Added first part of unit tests for pkg/detector

---

operator/pkg/tasks/init/crd_test.go

In this commit, we unit test crds on preparing, skipping, downloading, and unpacking operations.
Part of #5491.
```release-note
NONE
```

operator/pkg/tasks/init: unit test crds

---

.github/workflows/cli.yaml
hack/verify-license.sh
pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/config/config.go
pkg/karmadactl/cmdinit/config/config_test.go
pkg/karmadactl/cmdinit/config/types.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy_test.go
vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/meta.go
vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml.go
vendor/modules.txt

/kind feature
Increased karmadactl's ability to init by reading configuration files
From
```shell
user@virtual-machine:karmada/_output/bin/linux/amd64# karmadactl init --karmada-apiserver-image registry.k8s.io/kube-apiserver:v1.30.0 --karmada-kube-controller-manager-image registry.k8s.io/kube-controller-manager:v1.30.0 --etcd-image registry.k8s.io/etcd:3.5.13-0 --etcd-init-image docker.io/library/alpine:3.19.1 --karmada-aggregated-apiserver-image docker.io/karmada/karmada-aggregated-apiserver:v1.10.3 --karmada-controller-manager-image docker.io/karmada/karmada-controller-manager:v1.10.3 --karmada-scheduler-image docker.io/karmada/karmada-scheduler:v1.10.3 --karmada-webhook-image docker.io/karmada/karmada-webhook:v1.10.3 …
```

Feature: karmadactl init supports deployment through configuration files

---

test/e2e/framework/work.go
test/e2e/migration_and_rollback_test.go

add e2e for migration rollback feature
Fixes part of #5577
```release-note
```

add e2e for migration rollback feature

---

pkg/scheduler/core/spreadconstraint/group_clusters.go

/kind feature
Optimize the score calculation method to better measure the pros and cons of the group. This PR implements calc group score for divided to assign replicas evenly.
Fixes #4805
@whitewindmills 
```release-note
`karmada-scheduler`: implement group score calculation instead of take the highest score of clusters
```

Implement calc group score for divided to assign replicas evenly

---

pkg/controllers/execution/execution_controller.go
pkg/util/constants.go
test/e2e/migration_and_rollback_test.go

/kind cleanup
So we don't manage them in two different places and end up missing updating one
None
```release-note
```

chore: unify karmada labels/annotations usage in execution controller and test

---

artifacts/deploy/bootstrap-token-configuration.yaml
charts/karmada/templates/_karmada_bootstrap_token_configuration.tpl
pkg/karmadactl/cmdinit/karmada/rbac.go
pkg/karmadactl/karmadactl.go
pkg/karmadactl/unjoin/unjoin.go
pkg/karmadactl/unregister/unregister.go
pkg/karmadactl/util/cluster.go
pkg/util/secret.go

/kind feature
support unregister cluster in karmada
Part of #5380
```release-note
karmadactl: support unregister a pull mode cluster
```

support unregister cluster in karmada

---

operator/pkg/util/util.go
operator/pkg/util/util_test.go

In this commit, we unit test utilities on downloader operations and unpacking tar files.
Part of #5491.
```release-note
NONE
```

operator/pkg: unit test utilities

---

pkg/scheduler/core/spreadconstraint/group_clusters.go

/kind feature
Optimize the score calculation method to better measure the pros and cons of the group. This PR implements calc group score for duplicate to assign replicas evenly.
Part of #5159
@whitewindmills 
```release-note
`karmada-scheduler`: implement group score calculation instead of take the highest score of clusters
```

Implement calc group score for duplicate to assign replicas evenly

---

.github/workflows/cli.yaml
hack/cli-testing-init-with-config.sh
pkg/karmadactl/cmdinit/config/config_test.go
pkg/karmadactl/cmdinit/config/types.go

This PR is an additional test, based on the suggestion provided in [url](https://github.com/karmada-io/karmada/pull/5357#discussion_r1807568543).
Part of #5387
It adds test cases for deploying Karmada services using the `karmadactl init --config` command with a configuration file, similar to the existing tests for `karmadactl init`.
@liangyuanpeng 
@RainbowMango 
~~This PR currently contains two commits because the test files depend on the new feature for deploying with a configuration file, introduced in [#5357](https://github.com/karmada-io/karmada/pull/5357). Once that PR is merged, this PR will be rebased, retaining only the commit for adding test …

Add GitHub tests for karmadactl init --config command

---

pkg/scheduler/core/spreadconstraint/group_clusters_test.go

/kind feature
Optimize the score calculation method to better measure the pros and cons of the group. This PR added unit test for group score calc to assign replicas evenly.
Part of #5159 
@whitewindmills 
```release-note
None.
```

Add unit test for group score calc to assign replicas evenly

---

pkg/karmadactl/unregister/unregister.go
pkg/karmadactl/util/cluster.go

/kind cleanup
cleanup: change `*kubeclient.Clientset` to `kubeclient.Interface` in unregister module
* Improved Abstraction: By using the interface, we enhance the code's flexibility, making it easier to swap out implementations or mock dependencies for testing.
* Easier Testing: Interfaces facilitate unit testing by allowing the use of mock clients, thereby improving test coverage and reliability.
* Code Maintainability: This change promotes better software design principles, making the codebase easier to understand and maintain.
Part of #5380
```release-note
```

cleanup: change *kubeclient.Clientset to kubeclient.Interface in unregister module

---

pkg/karmadactl/unregister/unregister.go
pkg/karmadactl/unregister/unregister_test.go

add realted ut for unregister feature
Part of #5380
```release-note
```

add realted ut for unregister

---

artifacts/deploy/bootstrap-token-configuration.yaml

/kind feature
Part of #5182
```release-note
NONE
```

minimize the rbac permissions for karmada-agent

---

pkg/util/lifted/scheduler/framework/types_test.go

**Description:** 
This PR introduces comprehensive unit tests for scheduler framework types in pkg/util/lifted/scheduler/framework/types.go. These additions significantly improve the test coverage and ensure the reliability of scheduler framework functionality.
**Additions::**
1. pkg/util/lifted/scheduler/framework/types_test.go
1. pkg/util/lifted/scheduler/framework/types.go: 26.78% to 89.20%
/kind feature
```release-note
NONE
```

Added unit tests for scheduler framework types

---

pkg/karmadactl/addons/init/global.go
pkg/karmadactl/addons/metricsadapter/metricsadapter_test.go

In this commit, we unit test metrics adapter on status operations making sure metrics adapter deployed correctly on both the host cluster and karmada control plane by checking on deployment and aaAPIServices respectively.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl/addons: unit test metrics adapter

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go

/kind cleanup
This PR restrics the service types supported by karmada-operator.
Part of #5767 
This PR introduces validation rules which narrow down the range of acceptable configuration, but this has no impact on users who are currently using `ClusterIP` and `NodePort`.  And for `Loadbalancer` and `ExternalName`, currently not supported. (We are considering introduce the support of `Loadbalancer` to address the use case reported at #4634).
```release-note
API change: The ServiceType of Karmada API server now has been restrict to `ClusterIP`, `NodePort` and `LoadBalancer`.
```

Restrict supported service types of Karamda APIServer supported by karmada-operator

---

.github/workflows/release.yml

/kind cleanup
Stop krew update on branch release-1.10, see #4703 for more details.
Fixes #
Thanks to @liangyuanpeng for his excellent effort on #5224. We don't need to do the same thing on release 1.11 and the following release, either.
```release-note
NONE
```

Stop bump krew for release-1.10

---

docs/proposals/karmada-operator/api-server-service-status/README.md

/kind design
- Details are contained in the proposal.
Fixes #
```release-note
NONE
```

Proposal: Add API Server Service Information to `KarmadaStatus`

---

operator/pkg/tasks/init/upload.go

/kind feature
enable LoadBalancer type karmada-apiserver service in operator
Fixes part of #5767
```release-note
`karmada-operator`:  enable LoadBalancer type karmada-apiserver service
```

 enable LoadBalancer type karmada-apiserver service in operator

---

pkg/karmadactl/unjoin/unjoin.go
pkg/karmadactl/unregister/unregister.go
pkg/karmadactl/util/cluster.go

/kind feature
When karmadactl unjoin a member cluster, the unjoin may fail all the time because the resource deletion of the member cluster fails. By enhancing the forced deletion on karmadactl unjoin, if the resource deletion of the member cluster fails also force unjoin
Fixes #4431
1. delete clusterRole of member1
```shell
➜  karmada git:(master) km1 delete clusterrole karmada-controller-manager:karmada-member1 
clusterrole.rbac.authorization.k8s.io "karmada-controller-manager:karmada-member1" deleted
```
2. karmadactl unjoin member1
```shell
➜  karmada git:(master) karmadactl unjoin member1 --cluster-kubeconfig=/root/.kube/members.config
I1219 …
```

Enhanced forced deletion on karmadactl unjoin

---

pkg/controllers/status/crb_status_controller_test.go

/kind cleanup
It is clearly that crb should only handle root scope resources, so it is inappropriate for the tests in the crb status controller to reference pod.
Fixes #
```release-note
NONE
```

fix crb_status_controller ut is referencing namespaced objects

---

pkg/aggregatedapiserver/apiserver.go
pkg/aggregatedapiserver/apiserver_test.go

In this commit, we unit test aggregatedAPIServer on creating new aggregatedAPIServer with clusterAPI.
Part of #5491.
```release-note
NONE
```

pkg: unit test aggregatedAPIServer

---

pkg/karmadactl/addons/descheduler/descheduler.go
pkg/karmadactl/addons/descheduler/descheduler_test.go
pkg/karmadactl/addons/estimator/estimator.go
pkg/karmadactl/addons/metricsadapter/metricsadapter.go
pkg/karmadactl/addons/metricsadapter/metricsadapter_test.go
pkg/karmadactl/addons/search/search.go
pkg/karmadactl/addons/utils/helpers.go
pkg/karmadactl/register/register.go

In this commit, we unit test descheduler addon on enabling, disabling, and status operations. In addition to this we refactor some code to utilize some utilities across karmadactl addons.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl/addons: unit test descheduler

---

pkg/util/proxy/proxy.go

/kind bug
We can solve the problem of too many connections by setting DisableKeepAlives: true
test.sh:
```#!/bin/bash
KUBECONFIG="proxy.config"
SLEEP_INTERVAL=0.1
MAX_JOBS=100  
function run_karmadactl() {
while true; do
kubectl  --kubeconfig "$KUBECONFIG" get node
sleep "$SLEEP_INTERVAL"
done
}
for ((i = 1; i <= MAX_JOBS; i++)); do
run_karmadactl &
done
wait
```
Monitor the number of TCP connections in the pod
```
#!/bin/bash
while true; do
tcp_count=$(ss -tn | wc -l)
echo "$(date '+%Y-%m-%d %H:%M:%S') - Current total TCP connections: $((tcp_count - 1))"  # Subtract 1 for the header line
sleep 10
done
```
before fix
after fix 
Fixes #5574
**Does this …

cluster proxy transport disable keepalive

---

pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap.go
pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap_test.go

In this commit, we unit test bootstraptoken agent on tlsbootstrap functionality by testing `AllowBootstrapTokensToPostCSRs`, `AutoApproveKarmadaAgentBootstrapTokens`, and `AutoApproveAgentCertificateRotation` making sure they are working as expected.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl/cmdinit: unit test bootstraptoken

---

pkg/util/lifted/scheduler/cache/cache_test.go

**Description:** 
This PR adds comprehensive unit tests for the scheduler's cache package, focusing on testing the core functionality of cache operations. These tests improve code coverage and ensure reliable behavior of a critical component that manages node/pod state and snapshot management for scheduling decisions.
**Additions:**
1. pkg/util/lifted/scheduler/cache/cache_test.go
**Test coverage:**
1. pkg/util/lifted/scheduler/cache/cache_test.go : 0% to 77.4%
/kind feature
```release-note
NONE
```

Added unit tests for scheduler's cache package

---

pkg/search/apiserver.go
pkg/search/apiserver_test.go

In this commit, we unit test karmada search APIServer on creating REST storage and installing the API group.
Part of #5491
```release-note
NONE
```

pkg/search: unit test karmada search APIServer

---

pkg/util/lifted/scheduler/cache/snapshot_test.go

This PR adds comprehensive unit tests for the scheduler cache snapshot functionality. This improves code coverage and ensures reliable behavior of this critical scheduling component.
**Additions:**
1. pkg/util/lifted/scheduler/cache/snapshot_test.go
1. pkg/util/lifted/scheduler/cache/snapshot_test.go : 0% to 100%
/kind feature
```release-note
NONE
```

Added unit tests for the scheduler cache snapshot functionality

---

pkg/karmadactl/cmdinit/karmada/check_test.go

In this commit, we unit test `WaitAPIServiceReady` check function that is utilized across addons and during init operations on waiting for a non-existent aaAPIService, not-ready aaAPIService, and finally where aaAPIService becomes ready before the timeout.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl/cmdinit/karmada: unit test check

---

pkg/controllers/namespace/namespace_sync_controller_test.go
pkg/controllers/remediation/remedy_controller_test.go

/kind cleanup
Cancel the concurrent execution of SetupWithManager tests, because when the SetupWithManager method is executed more than once, an error will be reported if the same controller name is used. In addition, the concurrent execution of the SetupWithManager test case is of little significance. The concurrency we usually refer to is the concurrency of its internal queue execution, not the controller itself. Therefore, the test case was deleted.
Fixes #
@anujagrawal699 
```release-note
NONE
```

[UT] cancel concurrent test for SetupWithManager

---

pkg/util/helper/workstatus_test.go

This PR adds comprehensive unit tests for untested functions of the workstatus helper from the helper utility package. It introduces new tests for previously uncovered functions and refactors existing tests to use the `assert` package from `testify`. These additions aim to increase code reliability, maintainability, and test coverage for the workstatus helper.
1. pkg/util/helper/workstatus_test.go
1. pkg/util/helper/workstatus.go : 27.78% to 86.80%
/kind feature
Fixes a part of #5470
```release-note
NONE
```

Added unit tests for pkg/util/helper/workstatus.go

---

pkg/search/proxy/framework/plugins/cache/apis/core/v1/conversion.go
pkg/search/proxy/framework/plugins/cache/apis/core/v1/register.go
pkg/search/proxy/framework/plugins/cache/cache.go
pkg/search/proxy/framework/plugins/cache/scheme.go

/kind feature
karmada-search: support field selector for corev1 resources.
This supports most scenarios that use fieldSelector, such as finding a list of pods by node name.
Fixes #
without this patch:
```sh
Error from server (BadRequest): Unable to find "/v1, Resource=pods" that match label selector "", field selector "spec.nodeName=member1-worker": "spec.nodeName" is not a known field selector: only "metadata.name", "metadata.namespace"
```
with this patch:
```sh
example-app-6c847589df-xmjm5                2024-10-29T03:15:25Z
...
```
```release-note
karmada-search: support field selector for corev1 …
```

karmada-search: support field selector for corev1 resources

---

.github/workflows/ci-image-scanning-on-schedule.yml
.github/workflows/ci-image-scanning.yaml

/kind cleanup
Recently, the image-scanning CI encountered a rate-limiting error when downloading the vulnerability database from ghcr.io. See:
- https://github.com/karmada-io/karmada/actions/runs/11270619338
There is an issue  https://github.com/aquasecurity/trivy-action/issues/389 tracking this problem in the trivy-action repository. Released v0.26.0 which adds support for caching should alleviate some of the pain as caching should ensure DBs are reused if cache is available. 
In addition, the following have also been strengthened:
- specify multiple DB registries, which will try the default GitHub Registry, and if too many requests is reached, will use the aws mirror
- avoid repeatedly updating the Vulnerability DB …

image-scanning: fix ratelimiting error when downloading vulnerability db from ghcr.io

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
pkg/apis/work/v1alpha2/binding_types.go
pkg/generated/openapi/zz_generated.openapi.go

Part of #5788. This small PR adds PurgeMode to the GracefulEvictionTask as a prerequisite for ensuring scheduler skips clusters which triggered the failover.
```release-note
Introduce PurgeMode to GracefulEvictionTask in ResourceBinding
```

feat(stateful failover support) Introduce PurgeMode to GracefulEvictionTask in ResourceBinding

---

pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller_test.go

This PR introduces tests for deploymentreplicassyncer controller. The new addition tests significant logic of deploymentreplicassyncer controller.
**Additions**:
1. TestPredicateFunc:
- Added tests for various scenarios including label changes, replica changes, and different event types (Create, Update, Delete, Generic).
- Ensures the predicate function correctly filters relevant events.
2. TestSetupWithManager:
- Verifies that the controller can be properly set up with a manager.
3. TestReconcile:
- Added test cases for different reconciliation scenarios:
- Successful replicas sync
- Binding not found
- Non-divided scheduling type
- Replicas already synced
- Checks for correct result, error handling, and replica updates.
4. TestIsDeploymentStatusCollected:
- Covers …

Added tests for controllers/deploymentreplicassyncer

---

pkg/search/controller.go
pkg/search/controllers_test.go

In this commit, we unit test karmada search controller on creating new controller and handling the following events watched by the shared informer: `addCluster`, `updateCluster`, `deleteCluster`, `addResourceRegistry`, `updateResourceRegistry`, and `deleteResourceRegistry` making sure those handled and cached correctly to the indexer.
Part of #5491
```release-note
NONE
```

pkg/search: unit test controller

---

pkg/apis/work/v1alpha2/binding_types_helper.go
pkg/apis/work/v1alpha2/binding_types_helper_test.go
pkg/generated/openapi/zz_generated.openapi.go

/kind feature
update GracefulEvictCluster() to set PurgeMode during eviction process
Part of #5788
```release-note
update GracefulEvictCluster() to set PurgeMode during eviction process
```

Support PurgeMode setting in evection tasks

---

pkg/estimator/client/general_test.go

This PR adds comprehensive unit tests for the general estimator package. It introduces new tests for previously uncovered functions and refactors existing tests to use the `assert` package from `testify`. These changes improve code reliability, maintainability and test coverage. 
1. pkg/estimator/client/general_test.go
1. pkg/estimator/client/general.go : 38.82% to 87.90%
/kind feature
```release-note
NONE
```

Added unit tests for general estimator package

---

pkg/resourceinterpreter/default/native/reflectstatus_test.go

This PR standardizes and enhances tests for pkg/resourceinterpreter/default/native/reflectstatus.go, focusing on consistent test patterns and better coverage. It add tests for untested functions, refactors all status reflection tests to use a unified structure, adds missing edge cases and improves assertion handling with the `assert` package. These changes improve test maintainability, readability, and overall coverage while ensuring consistent validation across different resource types.
1. addedTests-pkg/resourceinterpreter/default/native/reflectstatus_test.go
1. addedTests-pkg/resourceinterpreter/default/native/reflectstatus.go : 22.66 to 90.60%
/kind feature
Fixes a …

Added unit tests for reflect status interpreter

---

hack/deploy-karmada-operator.sh
hack/local-up-karmada-by-operator.sh

/kind cleanup
Due to the merge of PR #5614, the URL for the crdtarball used by `local-up-karmada-by-operator.sh` has become invalid, causing CI failures.
Fix as follows:
- change url `local` to `http:local`
- correct the image name
Fixes #
```release-note
```

fix operatore ci fail for invalid crdtarball

---

artifacts/deploy/admin-clusterrole-aggregation.yaml
artifacts/deploy/bootstrap-token-configuration.yaml
charts/karmada/templates/_karmada_bootstrap_token_configuration.tpl
pkg/karmadactl/cmdinit/bootstraptoken/agent/tlsbootstrap.go
pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go

/kind cleanup 
refer to https://github.com/karmada-io/karmada/pull/5793#issuecomment-2484577844
- standardize the naming of Karmada system roles by prefixing them with `system:karmada`
- rename  label `kubernetes.io/bootstrapping: rbac-defaults` to `karmada.io/bootstrapping: rbac-defaults`
- remove annotation `rbac.authorization.kubernetes.io/autoupdate: "true"`
-  standardize the group for karmada bootstrapping bearer tokens  by prefixing them with `system:bootstrappers:karmada`
Fixes #
```release-note
```

Standardize the naming conventions for karmada system roles

---

cmd/controller-manager/app/controllermanager.go
cmd/controller-manager/app/options/options.go
pkg/dependenciesdistributor/dependencies_distributor.go

Add parameters to customize the number of workers for dependencies-distributor controller
/kind feature
part of  https://github.com/karmada-io/karmada/issues/5790
```release-note
`karmada-controller-manager`: Introduced `--concurrent-dependent-resource-syncs` flags to specify the number of dependent resource that are allowed to sync concurrently
```

feat(dependenciesdistributor):  introduce --concurrent-dependent-resource-syncs flag

---

pkg/resourceinterpreter/customized/webhook/customized_test.go

This PR adds comprehensive unit tests for the customized webhook interpreter. These tests verify the core functionality of webhook interpretation operations including replica retrieval, dependencies handling, patch operations and webhook enabling.
**Additions:**
1. pkg/resourceinterpreter/customized/webhook/customized_test.go
1. pkg/resourceinterpreter/customized/webhook/customized.go : 0% to 65%
/kind feature
```release-note
NONE
```

Added unit tests for the CustomizedInterpreter

---

pkg/karmadactl/unjoin/unjoin.go
pkg/karmadactl/util/cluster.go
test/e2e/rescheduling_test.go

Cherry pick of #4451 on release-1.9.
#4451: enhanced forced deletion on karmadactl unjoin
```release-note
`karmadactl`: The `--force` option of `unjoin` command now try to clean up resources propagated in member clusters.
```

Automated cherry pick of #4451: enhanced forced deletion on karmadactl unjoin

---

pkg/search/controller.go
pkg/search/controllers_test.go

In the test, `fake.NewFakeClient()` and `fakekarmadaclient.NewSimpleClientset()` are two different fake clients. In other test cases without errors, `controlPlaneClient` is not really used because it is replaced by `fakedynamic.NewSimpleDynamicClient`. In failed test case, however, it is used to create the cluster object, which should be the cause of the occasional error. 
**Root cause: we added eventHandlers twice, which caused the test sequence to go wrong and kept on waiting for events.**
The reason why we add the second commit: https://github.com/karmada-io/karmada/pull/5856#issuecomment-2492889764
Fixes #5855
**Does this PR …

fix flake test of TestUpdateClusterEventHandler

---

pkg/karmadactl/addons/metricsadapter/manifests.go

Cherry pick of #5840 on release-1.11.
#5840: Fix: karmada-metrics-adapter use the correct certificate when
```release-note
`karmadactl`: Fixed `karmada-metrics-adapter` use the incorrect certificate issue when deployed via karmadactl `init`.
```

Automated cherry pick of #5840: Fix: karmada-metrics-adapter use the correct certificate when

---

cmd/controller-manager/app/controllermanager.go
pkg/controllers/certificate/approver/agent_csr_approving.go
pkg/util/certificate/csr.go
pkg/util/certificate/csr_test.go

/kind feature
In #5793, we decided to change the user group that the `karmada-agent` accesses the Karmada API server from `system:nodes` to `system:karmada:agents`, and change the user `system:node:` to `system:karmada:agent:`, thereby isolating the permissions of the `karmada-agent` and `kubelet` to avoid being affected by node authentication.
To provide the capability for the agent's CSR to be automatically approved, this PR introduces the `agentcsrapproving` controller. It is disabled by default and maintains the same behavior as the `csrapproving` in `kube-controller-manager`, which used to automatically approve the csr of `kubelet`.
Fixes # …

add agentcsrapproving controller to auto approve agent csr

---

pkg/dependenciesdistributor/dependencies_distributor.go

/kind feature
set concurrentreconciles for dependencies-distributor controller, which previously was a fixed value of 2;
value same as --concurrent-resourcebinding-syncs flag.
part of  https://github.com/karmada-io/karmada/issues/5790
```release-note
```

feat(dependenciesdistributor):  remove dependenciesdistributor concurrentreconciles

---

artifacts/deploy/kube-controller-manager.yaml
charts/karmada/values.yaml
cmd/controller-manager/app/controllermanager.go
operator/pkg/controlplane/manifests.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go
pkg/karmadactl/register/register.go

/kind feature
agentcsrapproving controller is introduced in #5825, from now on, registering member clusters with PULL mode using `karmadactl register` no longer depends on the `csrapproving` controller. 
Fixes #
```release-note
```

cleanup csrapproving controller from kube-controller-manager

---

pkg/controllers/cluster/taint_manager.go
pkg/controllers/cluster/taint_manager_test.go

/kind feature
Update taint-manager to config eviction task with `PurgeMode`.
Part of #5788 
```release-note
karmada-controller-manager: update taint-manager to config eviction task with purgeMode
```

Update taint-manager to config eviction task with purgeMode

---

pkg/karmadactl/exec/exec.go
pkg/karmadactl/exec/exec_test.go

In this commit, we unit test exec on validating the execute options on control plane and member clusters.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl: unit test exec

---

pkg/controllers/status/common.go

/kind bug
Currently, the rb/crb status controller watchs rb/crb and work, but the predicates for creating events are all false, which means that if the work status is up to date, but the queue of the rb/crb status controller is not cleared, and it crashes, these unprocessed items will not be requeued after the next restart, and the status of rb/crb and workload will not be updated, until the relevant member cluster objects update the status again, triggering the work status controller and rb/crb status controller to process again.
Fixes #
```release-note
`karmada-controller-manager`: Fixed the corner …
```

let rb status controller onCreate predicate return true

---

.golangci.yml
cmd/aggregated-apiserver/app/options/options.go
cmd/karmada-search/app/karmada-search.go
cmd/metrics-adapter/app/options/options.go
pkg/util/grpcconnection/config.go

Re-enable the deprecation check which was disabled for the version upgrade.
Part of #5796 
```release-note
Replace `PostStartHookContext.StopCh` with `PostStartHookContext.Done` since `StopCh` is deprecated.
Replace `Run(ctx.Done())` with `RunWithContext`.
```

Enable the deprecation check which was disabled for version upgrade

---

pkg/karmadactl/cmdinit/karmada/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/utils/examples.go
pkg/karmadactl/cmdinit/utils/examples_test.go

/kind feature
The `karmadactl init` command, at the end of the initializtaion, writes some sensitive information in the stdout, like token, in its `karmadactl register` example. This will bring up two issues：
- data leak, for instance in CI/CD logs
- The token's validity period is one day. Users may not join the pull mode member clusters immediately after installing Karmada, causing the secret to expire.
I hope the command output to be how to do rather than what to do. Users can follow the steps in the command output as needed.
Fixes #
Modified command output:
```bash
Register cluster with 'Pull' mode
Step 1: Create bootstrap tokens and get the full …
```

Redact sensitive information from the karmadactl init command output

---

operator/pkg/tasks/init/crd.go
pkg/util/validation/validation.go
pkg/util/validation/validation_test.go

/kind feature
`karmada-operator` provides a custom download path for CRDs files. Before processing the files, it's necessary to validate the CRDs archive to enhance system robustness.
- Check if its file name includes relative paths.
- check if the CRDs archive has the expected directory structure.
Fixes #
`karamdactl init` has the same issue, and its enhancement is ongoing
```release-note
```

karmada-operator: add CRDs archive verification to enhance file system robustness

---

pkg/controllers/status/common.go

Cherry pick of #5865 on release-1.10.
#5865: let rb status controller onCreate predicate return true
```release-note
`karmada-controller-manager`: Fixed the corner case where the reconciliation of aggregating status might be missed in case of component restart.
```

Automated cherry pick of #5865: let rb status controller onCreate predicate return true

---

pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/utils/util.go
pkg/util/validation/validation_test.go

/kind feature
`karmadactl init` provides a custom download path for CRDs files. Before processing the files, it's necessary to validate the CRDs archive to enhance system robustness.
- check if its file name includes unclean paths.
- check if the CRDs archive has the expected directory structure.
Fixes #
```release-note
```

karmadactl init: add CRDs archive verification to enhance file system robustness

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
pkg/apis/work/v1alpha2/binding_types.go
pkg/apis/work/v1alpha2/binding_types_helper.go
pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
pkg/controllers/applicationfailover/common.go
pkg/controllers/applicationfailover/common_test.go
pkg/controllers/applicationfailover/crb_application_failover_controller.go
pkg/controllers/applicationfailover/rb_application_failover_controller.go
pkg/generated/openapi/zz_generated.openapi.go

/kind feature
Build PreservedLabelState when triggering evition in RB/CRB application controller
Part of #5788
```release-note
karmada-controller-manager: build PreservedLabelState when triggering evition in RB/CRB application controller
```

Build PreservedLabelState when triggering evition in RB/CRB application controller

---

pkg/util/helper/binding.go
pkg/util/helper/binding_test.go

/kind feature
Within the [binding controller](https://github.com/karmada-io/karmada/blob/38ee277de7aaaf4f93fec42d49bfc71cc4b0be76/pkg/controllers/binding/binding_controller.go#L145-L164) and [cluster binding controller](https://github.com/karmada-io/karmada/blob/38ee277de7aaaf4f93fec42d49bfc71cc4b0be76/pkg/controllers/binding/cluster_resource_binding_controller.go#L144-L160) we find and remove orphan works by checking the works against the existing clusters.
Existing clusters are populated by joining the resource binding's `spec.Clusters` field with any clusters that are found in the GracefulEvictionTasks. With the addition of PurgeMode, we should now check that the PurgeMode is not Immediately when populating the …

Cleanup works from cluster if purgemode is immediately

---

pkg/search/controllers_test.go

This PR introduces two key changes, which may address flaky test cases:
- Sets the default resync period for the shared informer to one second, instead of zero, ensuring that the informer checks for changes at regular intervals, reducing the chance of missing updates.
- Ensures that the shared informer is shut down after completion, guaranteeing that all goroutines have terminated, which helps avoid any lingering processes that could interfere with test execution.
/kind flake
There are flake tests regards some test cases in search controller as found in this PR #5864.
```release-note …
```

pkg/search/controllers_test: address flaky test

---

pkg/controllers/binding/common.go

/kind feature
Inject preservedLabelState to the failover to clusters.
Part of #5788
```release-note
karmada-controller-manager: Inject preservedLabelState to the failover to clusters
```

Inject preservedLabelState to the failover to clusters

---

api/openapi-spec/swagger.json
artifacts/deploy/karmada-controller-manager.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/controllers/applicationfailover/common.go
pkg/controllers/applicationfailover/common_test.go
pkg/controllers/binding/common.go
pkg/features/features.go
pkg/generated/openapi/zz_generated.openapi.go

/kind feature
This PR adds a feature gate `StatefulFailoverInjection` which controls whether Karmada collects state information from the source cluster during a failover event for stateful applications and injects this information into the application configuration when it is moved to the target cluster.
Part of #5788
```release-note
Introduced feature gate `StatefulFailoverInjection` to control whether Karmada collects and injects state information during a failover event for stateful application.
```

Add stateful application failover status injection feature gate

---

artifacts/deploy/karmada-controller-manager.yaml
cmd/controller-manager/app/controllermanager.go
pkg/controllers/applicationfailover/common.go
pkg/controllers/applicationfailover/crb_application_failover_controller.go
pkg/controllers/applicationfailover/rb_application_failover_controller.go
pkg/controllers/cluster/cluster_controller_test.go
pkg/controllers/cluster/taint_manager.go
pkg/features/features.go

/kind feature
This PR updates the `Failover` feature gate to be disabled by default. 
The changes are based on user feedback,
In the future, the cluster failover feature will focus on making it more user-friendly and visible, for example, providing the support of explicitly specifying applications that are eligible for cluster failover when configuring application distribution policies.
Fixes #
```release-note
The feature `Failover` now has been disabled by default, which should be explicitly enabled to avoid unexpected incidents. 
```

Disable cluster failover by default which should be explicitly enabled by administrators

---

pkg/resourceinterpreter/customized/webhook/request/resourceinterpretercontext_test.go

This PR adds comprehensive unit tests for the interpretation context handling. These tests ensure robust functionality of webhook response processing and validation for various interpreter operations.
**Additions:**
1. pkg/resourceinterpreter/customized/webhook/request/resourceinterpretercontext_test.go
1. pkg/resourceinterpreter/customized/webhook/request/resourceinterpretercontext.go: 0% to 90.80%
/kind feature
```release-note
NONE
```

Added unit tests for interpretation context handling

---

pkg/karmadactl/describe/describe.go
pkg/karmadactl/describe/describe_test.go

In this commit, we unit test describe command on karmadactl by creating a fake rest client builder and make sure the described k8s object returned successfully when the command submitted.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl: unit test describe

---

pkg/karmadactl/join/join.go
pkg/karmadactl/join/join_test.go

In this commit, we unit test the process of joining a cluster to the Karmada control plane. The tests validate the arguments passed to the join cluster operation and ensure the creation of the new cluster runtime object. Additionally, we verify that the necessary access secrets for the new cluster in push mode are correctly generated in the Karmada control plane.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl: unit test join

---

pkg/util/helper/cronfederatedhpa_test.go
pkg/util/helper/status_test.go

This PR introduces comprehensive unit tests for status and cronfederatedhpa helper utility functions in the pkg/util/helper. These additions aim to increase code reliability, maintainability, and test coverage of the helper utility package.
**Additions:**
1. pkg/util/helper/cronfederatedhpa_test.go
2. pkg/util/helper/status_test.go
1. pkg/util/helper/cronfederatedhpa_test.go : 0% to 100%
2. pkg/util/helper/status_test.go : 0% to 100%
/kind feature
```release-note
NONE
```

Added unit tests for status and cronfederatedhpa helper utilities

---

pkg/util/helper/cronfederatedhpa.go
pkg/util/helper/cronfederatedhpa_test.go

This PR introduces a DefaultHistoryLimit constant to replace the magic number '3' in CronFederatedHPA history limits.
**Changes:**
- Added DefaultHistoryLimit constant (value: 3) to define default history entries
- Updated GetCronFederatedHPASuccessHistoryLimits to use the constant
- Updated GetCronFederatedHPAFailedHistoryLimits to use the constant
- Improved test case names for better clarity and maintainability
/kind cleanup
Fixes #
As suggested by @XiShanYongYe-Chang in #5768 
```release-note
NONE
```

refactor: introduce DefaultHistoryLimit constant for CronFederatedHPA

---

go.mod
go.sum
hack/cli-testing-environment.sh
hack/cli-testing-init-with-config.sh
hack/local-up-karmada-by-operator.sh
hack/local-up-karmada.sh
hack/util.sh
vendor/modules.txt
vendor/sigs.k8s.io/kind/pkg/apis/config/defaults/image.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/docker/network.go
vendor/sigs.k8s.io/kind/pkg/cluster/internal/providers/podman/provider.go
vendor/sigs.k8s.io/kind/pkg/cmd/kind/version/version.go

/kind cleanup
This PR updates sigs.k8s.io/kind to v0.25.0 whose default node image is Kubernetes v1.31.2.
Our E2E test uses kind to simulate clusters, and now we use the latest Kubernetes v1.31.
Fixes #
```release-note
NONE
```

Bump kind dependencis from v0.24.0 to v0.25.0

---

pkg/karmadactl/promote/promote.go
pkg/karmadactl/promote/promote_test.go

In this commit, we unti test promoting a namespace-scoped or cluster-scoped resource in a legacy clsuter and validating the promote options on karmadactl command.
Part of https://github.com/karmada-io/karmada/issues/5491.
```release-note
NONE
```

pkg/karmadactl: unit test promote

---

pkg/util/lifted/lua/loadlib_safe_test.go
pkg/util/lifted/lua/oslib_safe_test.go

This PR introduces comprehensive unit tests for the safe Lua library utility functions in the pkg/util/lifted/lua package. These additions aim to increase code reliability, maintainability, and test coverage for the Lua libraries lifted from argo-cd and gopher-lua.
**Additions & Modifications:**
1. pkg/util/lifted/lua/loadlib_safe_test.go
2. pkg/util/lifted/lua/oslib_safe_test.go
1. pkg/util/lifted/lua/loadlib_safe_test.go : 0% to 95.80%
2. pkg/util/lifted/lua/oslib_safe_test.go : 52.14% to 94.50%
/kind feature
```release-note
NONE
```

Added unit tests for safe lua lifted libraries

---

pkg/karmadactl/cordon/cordon_test.go

In this commit, we unit test cordon on karmadactl client making sure the cordon/uncordon working as expected on a given cluster.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl: unit test cordon

---

pkg/karmadactl/unjoin/unjoin.go
pkg/karmadactl/unjoin/unjoin_test.go

In this commit, we unit test unjoining cluster by validating the unjoin cluster operation on arguments passed and by verifying the deletion of all resources on the unjoining cluster in case of cluster kubeconfig passed.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl: unit test unjoin

---

pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo.go
pkg/karmadactl/cmdinit/bootstraptoken/clusterinfo/clusterinfo_test.go
pkg/karmadactl/util/idempotency.go

In this commit, we unit test clusterinfo on creating bootstrap configmap and creating cluster info RBAC rules.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl/cmdinit/bootstraptoken: unit test clusterinfo

---

pkg/resourceinterpreter/customized/declarative/configmanager/accessor_test.go

This PR adds comprehensive unit tests for the custom resource interpreter's configuration manager. The tests verify the core functionality of configuration management operations including script handling, merging behaviors, and dependency management.
**Additions:**
1. pkg/resourceinterpreter/customized/declarative/configmanager/accessor_test.go
1. pkg/resourceinterpreter/customized/declarative/configmanager/accessor.go: 30.70% → 100%
/kind feature
```release-note
NONE
```

Added unit tests for custom resource interpreter's configuration manager

---

pkg/estimator/server/replica/replica_test.go

This PR adds comprehensive unit tests for the replica package in the estimator server. The tests cover all functions including GetUnschedulablePodsOfWorkload and podUnschedulable.
**Additions:**
1. pkg/estimator/server/replica/replica_test.go
1. pkg/estimator/server/replica/replica.go : 0% to 85.70%
/kind feature
```release-note
NONE
```

Added unit tests for the replica package in the estimator server

---

pkg/util/lifted/scheduler/cache/node_tree_test.go

This PR adds comprehensive unit tests for the scheduler's node tree functionality. These tests improve code coverage and ensure reliable behavior of a critical component that manages node organization by zones for efficient scheduling decisions.
**Additions:**
1. pkg/util/lifted/scheduler/cache/node_tree_test.go
1. pkg/util/lifted/scheduler/cache/node_tree_test.go : 0% to 98.2%
/kind feature
```release-note
NONE
```

Added unit tests for the scheduler's node tree functionality

---

pkg/karmadactl/completion/completion.go

/kind feature
Add support for code completion capabilities for Fish and PowerShell terminals.
Part of [#5477](https://github.com/karmada-io/karmada/issues/5477)
@zhzhuang-zju 
```release-note
`karmadactl`: Add Fish shell autocompletion support for improved command-line efficiency.
```

add shell completion code for fish

---

pkg/resourceinterpreter/customized/webhook/configmanager/accessor_test.go
pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go

This PR adds comprehensive unit tests for the resourceinterpreter webhook configmanager. These tests verify the core functionality of webhook configuration handling and access, including configuration syncing, merging, and accessor behaviors.
**Additions:**
1. pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go
2. pkg/resourceinterpreter/customized/webhook/configmanager/accessor_test.go
1. pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go : 0% to 81%
2. pkg/resourceinterpreter/customized/webhook/configmanager/accessor_test.go : 0% to 86.4%
/kind feature
```release-note
NONE …
```

Added unit tests for resourceinterpreter webhook configmanager

---

test/e2e/karmadactl_test.go

/kind flake
The e2e test `Karmadactl top testing Karmadactl top pod which does not exist [It] Karmadactl top pod which does not exist` has been intermittently failing. 
See,  https://github.com/karmada-io/karmada/actions/runs/12197101877/job/34026335469?pr=5772#step:6:1770
the e2e fails because the member cluster's server is not available at this time.
> error: cluster(member1): the server is currently unable to handle the request (get pods.metrics.k8s.io pod-z682t)
We are unable to determine why the metrics-server in member1 cannot handle requests due to the absence of logs from the member cluster and uncertainty regarding whether this is a transient service outage. However, we can enhance the …

fix flake test of KarmadactlTopPod

---

pkg/apis/cluster/types.go
pkg/apis/cluster/v1alpha1/types.go
pkg/controllers/status/cluster_status_controller.go
pkg/scheduler/framework/plugins/apienablement/api_enablement.go

Cherry pick of #5400, #5216 on release-1.10.
#5400: add new cluster condition: IncompleteAPIEnablements
#5216: skip the filter if the cluster is already in the list of scheduling result even if the API is missed
```release-note
karmada-scheduler: cluster in the scheduling list won't be filtered out even if it's APIEnablements don't include the resource's API
```

Automated cherry pick of #5400, #5216

---

pkg/apis/cluster/types.go
pkg/apis/cluster/v1alpha1/types.go
pkg/controllers/status/cluster_status_controller.go
pkg/scheduler/framework/plugins/apienablement/api_enablement.go

Cherry pick of #5400, #5216 on release-1.10.
#5400: add new cluster condition: IncompleteAPIEnablements
#5216: skip the filter if the cluster is already in the list of scheduling result even if the API is missed
```release-note
`karmada-scheduler`: Avoid filtering out clusters if the API enablement is incomplete during re-scheduling.
```

Automated cherry pick of #5400, #5216 

---

charts/index.yaml

/kind cleanup
Bump upgrade helm chart index to v1.12.0
Fixes
```release-note
upgrade helm chart index to v1.12.0.
```

Bump upgrade helm chart index to v1.12.0

---

operator/pkg/util/kubeconfig_test.go
pkg/controllers/binding/binding_controller_test.go
pkg/controllers/binding/cluster_resource_binding_controller_test.go
pkg/karmadactl/util/apiclient/apiclient.go
pkg/karmadactl/util/apiclient/apiclient_test.go
pkg/util/testing/helpers.go

In this commit, we unit test the apiclient to verify the creation of a restconfig in both scenarios: when it exists and when it doesn't.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl/util: unit test apiclient

---

pkg/dependenciesdistributor/dependencies_distributor.go

Cherry pick of #5943 on release-1.12.
#5943: Fix the problem of ResourceBinding remaining when the
```release-note
`karmada-controller-manager: Fixed the problem of ResourceBinding remaining after the resource template is deleted in the dependencies distribution scenario.
```

Automated cherry pick of #5943: Fix the problem of ResourceBinding remaining when the

---

artifacts/deploy/karmada-controller-manager.yaml
cmd/controller-manager/app/controllermanager.go
pkg/controllers/cluster/cluster_controller_test.go
pkg/features/features.go

Cherry pick of #5899 on release-1.10.
```release-note
The feature `Failover` now has been disabled by default, which should be explicitly enabled to avoid unexpected incidents. 
```

Disable cluster failover by default which should be explicitly enabled by administrators after a fully evaluation

---

pkg/webhook/configuration/validating.go
pkg/webhook/configuration/validating_test.go

/kind bug
When I apply a ResourceInterpreterWebhookConfiguration's `.webhooks[*].clientConfig.service.port` is nil, it report panic in the `karmada-webhook` component.
```yaml
apiVersion: config.karmada.io/v1alpha1
kind: ResourceInterpreterWebhookConfiguration
metadata:
name: examples
webhooks:
- clientConfig:
caBundle: {{caBundle}}
service:
namespace: karmada-system
name: karmada-interpreter-webhook-example
path: /interpreter-workload
interpreterContextVersions:
- v1alpha1
name: workloads.example.com
rules:
- apiGroups:
- workload.example.io
apiVersions:
- v1alpha1
kinds:
- Workload
operations:
- InterpretReplica
- ReviseReplica
- Retain
- AggregateStatus
- InterpretHealth
- InterpretStatus
- InterpretDependency …
```

`karmada-webhook`: Fix panic when validating ResourceInterpreterWebhookConfiguration with unspecified service port

---

pkg/karmadactl/register/register.go

/kind feature
When executing the `karmadactl register` command, there are many localized file operations involved, which lead to the following issues:
- The current file storage path is /etc/karmada, and non-admin users will not have permission to create this directory. see #https://github.com/karmada-io/karmada/pull/5334#issuecomment-2278636701
- Sensitive information such as CA should not be stored in files
- When `karmadactl register` fails, the residual files can cause the next execution of `karmadactl register` to fail.
In fact, the file localization steps in `karmadactl register` are unnecessary and can be removed.
Fixes #
If we want to use …

remove the unnecessary file localization steps when karmadactl register

---

pkg/webhook/configuration/validating.go
pkg/webhook/configuration/validating_test.go

Cherry pick of #5960 on release-1.10.
#5960: fix validate panic when
Part of #5964 
```release-note
`karmada-webhook`: Fixed panic when validating ResourceInterpreterWebhookConfiguration with unspecified service port.
```

Automated cherry pick of #5960: Fix panic when validating ResourceInterpreterWebhookConfiguration with unspecified service port

---

pkg/search/controllers_test.go

/kind flake
This PR reduce the probability of flaky test cases by waiting for cache to sync. It seems fake client has some flaky issues with watch implementation that is different from real implementation as seen in https://github.com/kubernetes/kubernetes/issues/87472#issuecomment-577472496?
Fixes #5926
```release-note
NONE
```

pkg/search/controllers_test: reduce the probability of flaky test cases by waiting for cache to sync

---

hack/verify-license.sh
operator/pkg/controller/karmada/validating_test.go
pkg/resourceinterpreter/customized/webhook/serviceresolvers.go
pkg/resourceinterpreter/customized/webhook/serviceresolvers_test.go
pkg/util/helper/index.go
pkg/util/helper/index_test.go

/kind cleanup
I found that some files I did not add licenses, but lint CI did not report errors, so I checked the `hack/verify-license.sh` script.
When I run it, it report:
```log
Usage: addlicense [flags] pattern [pattern ...]
The program ensures source code files have copyright license headers
by scanning directory patterns recursively.
It modifies all source files in place and avoids adding a license header
to any file that already has one.
The pattern argument can be provided multiple times, and may also refer
to single files.
Flags:
-c string
copyright holder (default "Google LLC")
-check
check only mode: verify presence of license headers and exit with non-zero code if missing
-f string
license file
-ignore value …
```

Fix verify license lint error

---

operator/pkg/certs/certs.go
operator/pkg/init.go
operator/pkg/tasks/init/cert.go
operator/pkg/tasks/init/cert_test.go
operator/pkg/tasks/init/upload.go

/kind bug
When provisioning a Karmada instance to be managed by the Karmada operator, there's support for both in-cluster and external ETCD modes. When external ETCD mode is used, the operator should skip setting up an in-cluster ETCD instance, which entails setting up PKI for the instance and deploying it as a stateful set. However, currently, in external ETCD mode, the operator will skip deploying the stateful set, but will still generate PKI, which is an issue. In external ETCD mode, all tasks relevant to setting up an in-cluster instance should be skipped.
Fixes #5975
```release-note …
```

Fix ETCD PKI Provisioning Issue in Karmada Operator

---

pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
test/e2e/workloadrebalancer_test.go

/kind bug
fix rebalancer auto deleted failed
Fixes #5985
```release-note
`karmada-controller-manager`: Fixed the bug of WorkloadRebalancer doesn't get deleted after TTL.
```

fix rebalancer auto deleted failed

---

pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
test/e2e/workloadrebalancer_test.go

Cherry pick of #5989 on release-1.10.
#5989: fix rebalancer auto deleted failed
```release-note
`karmada-controller-manager`: Fixed the bug of WorkloadRebalancer doesn't get deleted after TTL.
```

Automated cherry pick of #5989: fix rebalancer auto deleted failed

---

pkg/util/helper/work_test.go

This PR adds comprehensive unit tests for untested functions of the module work from the helper utility package. It introduces new tests for previously uncovered functions and refactors existing tests to use the `assert` package from `testify`. These additions aim to increase code reliability, maintainability, and test coverage for the work helper.
1. pkg/util/helper/work.go
1. pkg/util/helper/work.go : 27.78% to 92.2%
/kind feature
```release-note
NONE
```

Added tests for pkg/util/helper/work.go

---

operator/pkg/certs/certs.go
operator/pkg/init.go
operator/pkg/tasks/init/cert.go
operator/pkg/tasks/init/cert_test.go
operator/pkg/tasks/init/upload.go

Cherry pick of #5976 on release-1.12.
#5976: Only genrate ETCD PKI for local ETCD setup
```release-note
`karmada-operator`: Fixed the issue that external ETCD certificate be overwritten by generated in-cluster ETCD certificate.
```

Automated cherry pick of #5976: Only genrate ETCD PKI for local ETCD setup

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
pkg/apis/work/v1alpha2/binding_types.go
pkg/apis/work/v1alpha2/zz_generated.deepcopy.go
pkg/generated/openapi/zz_generated.openapi.go
pkg/scheduler/event_handler.go
pkg/scheduler/event_handler_test.go
pkg/util/binding.go
pkg/util/binding_test.go

/kind feature
Add rb suspension capability, background: https://github.com/karmada-io/karmada/pull/5690
Fixes https://github.com/karmada-io/karmada/pull/5690
It extends the Suspension fileds and support rb susupend and resume, mostly like the previous issue https://github.com/karmada-io/karmada/issues/5217 and PRs implemented in it. 
This pr just implemented  binding suspension in `scheduler `, setting status condition in `controller` will be implemented in another pr after https://github.com/karmada-io/karmada/pull/6002 merged because it may lead to status update conflict between scheduler and controller. …

feat: cluster-level resource scheduling suspend and resume capabilities

---

docs/proposals/scheduling-suspension/README.md

/kind design
Fixes https://github.com/karmada-io/karmada/issues/4937
```release-note
NONE
```

[Proposal] Support for resource scheduling suspend and resume capabilities

---

cmd/agent/main.go
cmd/controller-manager/controller-manager.go
cmd/descheduler/main.go
cmd/scheduler-estimator/main.go
cmd/scheduler/main.go
operator/cmd/operator/operator.go

/kind cleanup
remove workaround code for resolving workqueue metrics loss by modifying import order
Fixes part of #5954
Lastst test report:
<details>
<summary>click here to see test report</summary>
* karmada-controller-manager:
```shell
/ # curl http://127.0.0.1:8080/metrics | grep workqueue_queue_duration_seconds_sum
...
workqueue_queue_duration_seconds_sum{controller="taint-manager",name="taint-manager"} 0.302839183
workqueue_queue_duration_seconds_sum{controller="unified-auth-controller",name="unified-auth-controller"} 0.080192647
workqueue_queue_duration_seconds_sum{controller="work-status",name="work-status"} 0.003801357 …
```

remove workaround code for resolving workqueue metrics loss by modifying import order

---

docs/CHANGELOG/CHANGELOG-1.10.md
docs/CHANGELOG/CHANGELOG-1.11.md
docs/CHANGELOG/CHANGELOG-1.12.md
docs/CHANGELOG/CHANGELOG-1.13.md

According to [Karmada's release cycle](https://karmada.io/docs/next/releases#the-release-cycle), the release team is preparing to release an alpha version of v1.13.0 today, along with patch version for the maintenance releases. This pr is used to publish its release notes
Fixes #
```release-note
NONE
```

publish release v1.13.0-alpha.1, v1.12.2, v1.11.5, v1.10.9

---

artifacts/deploy/karmada-metrics-adapter.yaml
charts/karmada/templates/karmada-metrics-adapter.yaml
cmd/metrics-adapter/app/options/options.go
operator/pkg/controlplane/metricsadapter/manifests.go
pkg/karmadactl/addons/metricsadapter/manifests.go

/kind feature
expose metrics of karmada-metrics-adapter
Fixes part of #5954
```release-note
`karmada-metrics-adapter`: Introduced `--metrics-bind-address` flag which will be used to expose Prometheus metrics.
```

expose metrics of karmada-metrics-adapter

---

pkg/apis/work/v1alpha2/binding_types_helper.go
pkg/apis/work/v1alpha2/binding_types_helper_test.go
pkg/scheduler/event_handler.go
pkg/util/binding.go
pkg/util/binding_test.go

/kind cleanup
Add ResourceBinding scheduling suspension helper function to simplify code.
Part of #5977
```release-note
NONE
```

Add ResourceBinding scheduling suspension helper function

---

hack/util.sh
operator/config/samples/karmada.yaml
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deploy_test.go

/kind feature
Fixes #6024
NONE

Version Updates in files

---

README.md

- Update the meeting(English) time, referred to in this [conversation](https://groups.google.com/g/karmada/c/6DNoZekh-4A)
Part of #6030
```release-note
NONE
```

Update community meeting time

---

pkg/util/grpcconnection/config.go

- `grpc.DialContext` and `grpc.WithBlock` are deprecated
- Updates client connection creation to use modern gRPC patterns
- Leverages DNS resolver for better service discovery
- Maintains backward compatibility while enabling future features
Part of #5796 
Replace `grpc.DialContext` and `grpc.WithBlock` with `grpc.NewClient` to follow the recommended pattern in https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md.
Since we only allow users to configure the authentication setting of the grpc client without any custom [dial options](https://pkg.go.dev/google.golang.org/grpc#DialOption), I think we should be safe …

Replace grpc.DialContext and grpc.WithBlock with grpc.NewClient

---

pkg/controllers/ctrlutil/work.go

/kind bug
see #5938
Fixes #5938
```release-note
NONE
```

fix deep equal check failure in CreateOrUpdateWork(), by replace the marshaler

---

hack/deploy-karmada.sh

/kind bug
Fix local up installation failed on macOS duo to missing envsubst by default.
Fixes #5934
```release-note
```

Fix local up installation failed on macOS duo to missing envsubst

---

artifacts/deploy/karmada-aggregated-apiserver.yaml
artifacts/deploy/karmada-apiserver.yaml
artifacts/deploy/karmada-controller-manager.yaml
artifacts/deploy/karmada-descheduler.yaml
artifacts/deploy/karmada-etcd.yaml
artifacts/deploy/karmada-metrics-adapter.yaml
artifacts/deploy/karmada-scheduler-estimator.yaml
artifacts/deploy/karmada-scheduler.yaml
artifacts/deploy/karmada-search.yaml
artifacts/deploy/karmada-webhook.yaml
artifacts/deploy/kube-controller-manager.yaml

/kind cleanup
A [security context](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/) defines privilege and access control settings for a Pod or Container. More details can refer to https://www.dynatrace.com/engineering/blog/kubernetes-security-part-3-security-context/
This PR restricted the component's security context, including,
- set `allowPrivilegeEscalation` to false
- set `privileged` to false,
- configured the `seccompProfile` to `RuntimeDefault`
Regarding `runAsUser` and `runAsNonRoot`, unfortunately, imposing these restrictions resulted in abnormal functionality of the component, so they could not be applied. As for `readOnlyRootFilesystem`, implementing this would reduce convenience …

config security context

---

pkg/controllers/multiclusterservice/mcs_controller.go
pkg/detector/detector.go

/kind bug
The https://github.com/karmada-io/karmada/pull/5974 has decoupled `work` suspension inherited from pp and `resourcebinding` suspension, but there is something missed, when update rb conflicted, the whole suspension filed will be override by suspension from pp, which will casue rb scheduling suspension to nil, this pr fix it, and also print the suspension state using kubectl.
Fixes #
```release-note
`karmada-controller-manager`: Fixed an issue that the scheduling suspension on ResourceBinding might be mistakenly overwritten.
```

fix pp suspension mistakenly override scheduling suspension

---

pkg/dependenciesdistributor/dependencies_distributor.go

fix controller print too many "No need to sync binding" log when restarts
Fixes https://github.com/karmada-io/karmada/issues/6071
```release-note
```

feat(dependenciesdistributor):  remove log

---

pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go
pkg/search/proxy/store/util.go
pkg/search/proxy/store/util_test.go
pkg/search/proxy/testing/constant.go

karmada-search resourceregistry can merge the same cluster gvk's namespaces
get ResourceRegistry:
get secret:
Fixes #6064
```release-note
`karmada-search`: Fixed the issue that namespaces in different ResourceRegistry might be overwritten.
```

fix(search/proxy/controller): resourceregistry merge ns

---

pkg/controllers/binding/common.go

/kind feature
When `ensureWork`, one cluster fails would prevent other clusters from syncing, this PR aims to enhance `ensureWork` to continue processing clusters after individual failures.
real user case:
1. `member1` cluster is discontected, while `member2`/`member3` is normal
2. delete deployment from control-plane, it will be successfully deleted on all clusters except member1, besides, the `work` of `member1` cluster will remain due to the finalizer
4. then, assuming `member1` cluster recovered
3. recreate the deployment with the same name, deployments to all clusters may be blocked for up to 1000s.
cause:
when `ensureWork` failed on member1 cluster due to the old `work` is exist and being deleted, we fast failed …

enhance ensureWork to continue processing clusters after individual failures

---

pkg/karmadactl/addons/descheduler/manifests.go
pkg/karmadactl/addons/init/enable_option.go
pkg/karmadactl/addons/metricsadapter/manifests.go
pkg/karmadactl/addons/search/manifests.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go
pkg/karmadactl/util/global.go
pkg/util/names/names.go

/kind feature
/kind cleanup
In karmada, here are two important secrets, which is mount by most karmada components. One is karmada-cert, which contains a series of cert files like ca.crt, apiserver.crt and so on; another is karmada-kubeconfig, which contains a kubeconfig of karmada-apiserver.
However, in different installation methods, we used inconsistent secret naming or file path naming, which can potentially cause some unnecessary problems, detail refer to https://github.com/karmada-io/karmada/issues/5363.
This PR aims to standardize the naming of karmada config in `karmadactl` installation method.
Fixes part of #6051
karmada-agent is a bit …

standardize the naming of karmada config in karmadactl method

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/apiserver/apiserver_test.go
operator/pkg/controlplane/apiserver/manifests.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/controlplane_test.go
operator/pkg/controlplane/etcd/etcd.go
operator/pkg/controlplane/etcd/etcd_test.go
operator/pkg/controlplane/manifests.go
operator/pkg/controlplane/metricsadapter/metricsadapter.go
operator/pkg/controlplane/metricsadapter/metricsadapter_test.go
operator/pkg/controlplane/search/search.go
operator/pkg/controlplane/search/search_test.go
operator/pkg/controlplane/webhook/webhook.go
operator/pkg/controlplane/webhook/webhook_test.go
operator/pkg/util/patcher/pather.go

/kind feature
This is an implementation of this [proposal](https://github.com/karmada-io/karmada/pull/6010) to add support for configuring the priority class name of Karmada control plane components.
Fixes #6009
Partof #6042
```release-note
`karmada-operator`: The new `PriorityClassName` field added as part of the Karmada control plane component configurations can be used to specify the priority class name of that component.
```

Add Support for Component Priority Class Configuration in Karmada Operator

---

go.mod
hack/util.sh

/kind cleanup
In `hack/util.sh`, we can directly read `MIN_GO_VERSION` from `go.mod` via Go CLI. No need to remember to modify it manually when updating Go version.
Discussed here: https://github.com/karmada-io/karmada/pull/6066#discussion_r1921418431
```release-note
NONE
```

Read MIN_GO_VERSION directly with Go CLI

---

pkg/resourceinterpreter/customized/declarative/luavm/lua.go
pkg/util/lifted/lua/string_safe.go

/kind feature
Users can accomplish the desired resource interpretation through custom Lua scripts, which will utilize built-in functions from Lua's function libraries, including those from the `string` and `os` libraries. To enhance the robustness of the system, the following enhancements have been made to the functions in the `string` lib:
- Limit the length of strings to no more than 1,000,000 characters.
- Do not provide the string.gsub() and string.rep functions.
- Add timeout checks to the internal for loops within the functions.
Fixes #
```release-note
`karmada-controller-manager`: karmada lua …
```

karmada lua uses more secure string functions

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml

/kind feature
After doing some load testing of the FlinkDeployment failover (which overall has been looking quite good, but may need to address a couple edge cases), I found that the interpreter is missing one of the ephemeral states that FlinkDeployments can transition through. 
Occasionally on failover, the FlinkDeployment will transition from RECONCILING -> INITIALIZING -> CREATED, before finally ending on RUNNING. Additionally, we can make use of the status.error field to further improve the health interpretation. 
In this PR I've added:
1. INITIALIZING state as an ephemeral state which we should check during health interpretation.
2. Checking if status.error != nil. If the deployment has a published error, then we …

Updating FlinkDeployment interpreter to display error status, improving health interpreter

---

.github/workflows/installation-cli.yaml
go.mod
test/e2e/framework/cluster.go
test/e2e/framework/metrics.go
test/e2e/metrics_test.go
test/e2e/suite_test.go

introduce tests to check whether workqueue metrics exist
Fixes part of #5954
```release-note
```

introduce tests to check whether workqueue metrics exist

---

hack/deploy-karmada-by-operator.sh
operator/pkg/controller/karmada/planner.go
operator/pkg/controller/karmada/planner_test.go
operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/apiserver/apiserver_test.go
operator/pkg/controlplane/apiserver/manifests.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/controlplane_test.go
operator/pkg/controlplane/manifests.go
operator/pkg/controlplane/metricsadapter/manifests.go
operator/pkg/controlplane/metricsadapter/metricsadapter.go
operator/pkg/controlplane/metricsadapter/metricsadapter_test.go
operator/pkg/controlplane/search/manifests.go
operator/pkg/controlplane/search/search.go
operator/pkg/controlplane/search/search_test.go
operator/pkg/controlplane/webhook/manifests.go
operator/pkg/controlplane/webhook/webhook.go
operator/pkg/controlplane/webhook/webhook_test.go
operator/pkg/tasks/deinit/kubeconfig.go
operator/pkg/tasks/deinit/kubeconfig_test.go
operator/pkg/tasks/init/upload.go
operator/pkg/util/naming.go

/kind feature
/kind cleanup
In karmada, here are two important secrets, which is mount by most karmada components. One is karmada-cert, which contains a series of cert files like ca.crt, apiserver.crt and so on; another is karmada-kubeconfig, which contains a kubeconfig of karmada-apiserver.
However, in different installation methods, we used inconsistent secret naming or file path naming, which can potentially cause some unnecessary problems, detail refer to https://github.com/karmada-io/karmada/issues/5363.
This PR aims to standardize the naming of karmada config in Karmada Operator installation method.
Part of #6051  …

Standardize the naming of karmada config in Karmada Operator

---

pkg/search/proxy/controller.go
pkg/search/proxy/controller_test.go
pkg/search/proxy/store/util.go
pkg/search/proxy/store/util_test.go
pkg/search/proxy/testing/constant.go

Cherry pick of #6065 on release-1.12.
#6065: fix: resourceregistry merge the same cluster gvk's namespace
```release-note
`karmada-search`: Fixed the issue that namespaces in different ResourceRegistry might be overwritten.
```

Automated cherry pick of #6065: fix: resourceregistry merge the same cluster gvk's namespace

---

charts/karmada/_crds/patches/webhook_in_clusterresourcebindings.yaml
charts/karmada/_crds/patches/webhook_in_resourcebindings.yaml
hack/deploy-karmada.sh
operator/pkg/tasks/init/karmadaresource.go
operator/pkg/util/util.go
operator/pkg/util/util_test.go
pkg/karmadactl/cmdinit/karmada/deploy.go
pkg/karmadactl/cmdinit/karmada/deploy_test.go

/kind bug
when deploying karmada instance by operator or `karmadactl init`，karmada-apiserver will report `dial tcp: lookup karmada-webhook.karmada-system.svc on x.x.x.x: no such host` error if the namespace of karmada instance is not `karmada-system`.
```bash
E0208 07:01:36.926856       1 watcher.go:567] failed to prepare current and previous objects: conversion webhook for work.karmada.io/v1alpha2, Kind=ResourceBinding failed: Post "https://karmada-webhook.karmada-system.svc:443/convert?timeout=30s": dial tcp: lookup karmada-webhook.karmada-system.svc on 100.136.0.10:53: no such host
I0208 07:01:36.927733       1 reflector.go:481] storage/cacher.go:/work.karmada.io/resourcebindings: retrying watch of …
```

karmada-webhook: fix the no such host error

---

pkg/detector/detector_test.go

/kind cleanup
mockResourceDetector isn't working and we don't need it to complete the tests.
Fixes #
```release-note
NONE
```

remove mockResourceDetector

---

pkg/karmadactl/cmdinit/cmdinit.go
pkg/karmadactl/cmdinit/kubernetes/deploy.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go
pkg/karmadactl/cmdinit/kubernetes/statefulset.go

Currently, the priority class name for Karmada components is hardcoded to system-node-critical for some components, while others do not specify a priority class at all. This limitation can compromise the reliability and stability of the system in environments where scheduling of critical components is essential.
This pr is going to add support for Component Priority Class Configuration in `karmadactl init`.
Parts of #6042
```release-note
`karmadactl`: command `init` now can specify the priority class name of the karmada components, default to `system-node-critical`.
```

Add Support for Component Priority Class Configuration in karmadactl init

---

artifacts/agent/karmada-agent.yaml
artifacts/deploy/karmada-aggregated-apiserver.yaml
artifacts/deploy/karmada-controller-manager.yaml
artifacts/deploy/karmada-descheduler.yaml
artifacts/deploy/karmada-etcd.yaml
artifacts/deploy/karmada-metrics-adapter.yaml
artifacts/deploy/karmada-scheduler-estimator.yaml
artifacts/deploy/karmada-scheduler.yaml
artifacts/deploy/karmada-search.yaml
artifacts/deploy/karmada-webhook.yaml

/kind cleanup
Refer to #6042. installation tools of Karmada now support setting the Priority Class of components, with the default value being `system-node-critical`. This PR is used to unify the configuration of Component Priority Class in `local-up`. 
Parts of #6042
```release-note
```

Unify Component Priority Class in local-up

---

examples/customresourceinterpreter/README.md

/kind cleanup
Adjust the description regarding the use of `resourceinterpreterwebhook`. When configuring the `clientConfig` in the Service manner, an additional ExternalName type Service can be deployed in the `karmada-apiserver`. 
Fixes #
```release-note
NONE
```

[Cleanup] update some describetion with the resourceinterpreterwebhook readme file

---

.github/workflows/installation-chart.yaml

/kind cleanup
Bumps [helm/chart-testing-action](https://github.com/helm/chart-testing-action) from 2.6.1 to 2.7.0.
Fixes #
The dependabot bot sent another PR(#6089) but was blocked due to the default behavior of `CT` changing, which needs manual adoption.
```release-note
NONE
```

Bump helm/chart-testing-action from 2.6.1 to 2.7.0

---

pkg/controllers/status/cluster_status_controller.go
pkg/metrics/cluster.go

/kind bug
Fixes https://github.com/karmada-io/karmada/issues/5843
```release-note
`Instrumentation`: The cluster status-related metrics, emitting from `karmada-controller-manager`, will be cleaned up after the cluster is removed.
```

fix(cluster):  remove related metrics label when cluster is deleted

---

pkg/karmadactl/unjoin/unjoin.go
pkg/karmadactl/unjoin/unjoin_test.go
pkg/karmadactl/unregister/unregister.go
pkg/karmadactl/unregister/unregister_test.go

/kind feature
Restrict the cluster sync mode for the unjoin and unregister command.
```bash
$ karmadactl get cluster
NAME      CLUSTER   VERSION   MODE   READY   AGE     ADOPTION
member1   Karmada   v1.31.2   Push   True    17h     -
member3   Karmada   v1.31.2   Pull   True    3d23h   -
$ karmadactl unregister member1  --cluster-kubeconfig ~/.kube/members.config --karmada-config ~/.kube/karmada.config --cluster-context member1 -v=4 
I0124 11:10:55.943833 2452252 unregister.go:188] Unregistering cluster. cluster name: member1
I0124 11:10:55.943887 2452252 unregister.go:189] Unregistering cluster. karmada-agent deployed in namespace: karmada-system
I0124 11:10:55.943901 2452252 unregister.go:190] Unregistering cluster. …
```

Restrict the cluster sync mode for the unjoin and unregister command

---

pkg/karmadactl/cmdinit/utils/examples.go

/kind bug
Fixes #
```release-note
```

fix: when contenxt fails to run when it contains quotes

---

pkg/controllers/multiclusterservice/mcs_controller_test.go
pkg/controllers/namespace/namespace_sync_controller_test.go
pkg/detector/detector_test.go
pkg/resourceinterpreter/customized/declarative/luavm/lua_test.go
pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go
pkg/resourceinterpreter/default/native/aggregatestatus_test.go
pkg/resourceinterpreter/default/native/reflectstatus_test.go
pkg/resourceinterpreter/default/native/retain_test.go
pkg/scheduler/scheduler_metrics_test.go
pkg/util/eventfilter/eventfilter_test.go
pkg/util/helper/unstructured_test.go

/kind cleanup
Part of the content of https://github.com/karmada-io/karmada/pull/6028
Some tests would call `helper.Unstructured()` but no typeMeta was provided, causing some tests to incorrectly report passing.
this problem blocks #6076
Fixes #
```release-note
NONE
```

fixed some UTs did not pass apiversion and kind when generating unstuctured.Unstructured

---

.github/workflows/installation-cli.yaml
hack/cli-testing-environment.sh
hack/cli-testing-init-with-config.sh

Signed-off-by: Akash <akashsingh2210670@gmail.com>
Parts of  #5916
```release-note
NONE
```

feat : add cluster registration step in pull mode to installation-cli.yaml

---

pkg/controllers/ctrlutil/work.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller_test.go
pkg/util/helper/work.go
pkg/webhook/work/mutating.go

/kind feature
It could remove unnecessary update operations in `ctrlutil.CreateOrUpdateWork()`, by mutating the `Work` in advance, and let `DeepEqual()` return true. when karmada-controller-manager restart, this may help reduce the time it takes to clear the work queue.
Should be part of #6031, if it's not true please correct me.
Fixes #
Tests will remain failing until #6028 is merged and this PR is rebased on it.
```release-note
NONE
```

add work mutating in ctrlutil.CreateOrUpdateWork()

---

operator/pkg/controller/karmada/controller.go

/kind bug
When the operator reconciles the Karmada CR, it will first validate the Karmada CR and then set the default values. This causes the validation to fail when users omit the configuration of certain fields.
It is necessary to set the default values first and then perform the validation. 
Fixes #
How to reproduce it:
1. deploy karmada-operator
```bash
$ hack/deploy-karmada-operator.sh {path/to/kubeconfig} {context}
```
2. deploy a karmada CR
```bash
$ kubectl apply -v=4 -f - <<EOF
kind: Karmada
metadata:
spec:
components:
karmadaDescheduler: {}
etcd: {}
EOF
```
3. view …

operator: fix the issue that the default values of Karmada are not correctly applied

---

pkg/detector/detector.go
pkg/util/label.go
pkg/util/label_test.go

/kind feature
Fixes https://github.com/karmada-io/karmada/issues/6154
```release-note
```

fix(detector): Fix the invalid behavior in the detector to determine whether the binding object needs to be updated.

---

pkg/detector/detector.go

/kind bug
This is the remediation for PR #6154 where forgot to clean the legacy merge operation.
Fixes #
```release-note
```

fix(detector):  forgot to clean the legacy merge operation

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
pkg/apis/policy/v1alpha1/propagation_types.go
pkg/generated/openapi/zz_generated.openapi.go

/kind feature
Making it a required field allows for more flexibility in future changes. For example, if we need to modify the default value later, we can make it optional and explicitly define a default value.
Part of #5961
```release-note
Make priorityClassSource in the SchedulePriority of PropagationPolicy a required field.
```

Make priorityClassSource in the SchedulePriority of PropagationPolicy a required field

---

pkg/detector/detector.go
pkg/util/label.go
pkg/util/label_test.go

Cherry pick of #6157 #6161 on release-1.12.
#6157: fix(detector): fix new binding object
#6161: fix(detector): fix new binding object
```release-note
```

Automated cherry pick of #6157, #6161: fix(detector): Fixed the issue where the `detector` unnecessary updates for RB issue.

---

pkg/detector/detector.go
pkg/util/label.go
pkg/util/label_test.go

Cherry pick of https://github.com/karmada-io/karmada/pull/6157 https://github.com/karmada-io/karmada/pull/6161 on release-1.11.
https://github.com/karmada-io/karmada/pull/6157: fix(detector): fix new binding object
https://github.com/karmada-io/karmada/pull/6161: fix(detector): fix new binding object
```release-note
```

Automated cherry pick of #6157 #6161 upstream release 1.11

---

pkg/detector/detector.go
pkg/util/label.go
pkg/util/label_test.go

Cherry pick of https://github.com/karmada-io/karmada/pull/6157 https://github.com/karmada-io/karmada/pull/6161 on release-1.10.
https://github.com/karmada-io/karmada/pull/6157: fix(detector): fix new binding object
https://github.com/karmada-io/karmada/pull/6161: fix(detector): fix new binding object
```release-note
```

Automated cherry pick of #6157 #6161 upstream release 1.10

---

charts/karmada/templates/karmada-apiserver.yaml
charts/karmada/values.yaml

/kind feature
Initial implementation of karmada-io/karmada#6144, for Helm only.
Other installation methods can be handled in separate PRs, if that's OK.
```release-note
`HELM Chart`: OpenID Connect based auth can be configured for the Karmada API server when installing via Helm
```

Allow configuring karmada-apiserver OIDC via Helm

---

pkg/karmadactl/register/register.go

Remove deprecated --ca-cert-path from karmadactl
Fixes #6177  
```release-note
```

chore: remove deprecated --ca-cert-path from karmadactl

---

hack/deploy-karmada-operator.sh
hack/local-up-karmada-by-operator.sh
hack/operator-e2e-environment.sh
operator/config/deploy/karmada-operator-clusterrole.yaml
operator/config/deploy/karmada-operator-clusterrolebinding.yaml
operator/config/deploy/karmada-operator-deployment.yaml
operator/config/deploy/karmada-operator-serviceaccount.yaml
operator/pkg/constants/constants.go
operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/apiserver/manifests.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/etcd/etcd.go
operator/pkg/controlplane/etcd/manifests.go
operator/pkg/controlplane/manifests.go
operator/pkg/controlplane/metricsadapter/manifests.go
operator/pkg/controlplane/metricsadapter/metricsadapter.go
operator/pkg/controlplane/search/manifests.go
operator/pkg/controlplane/search/search.go
operator/pkg/controlplane/webhook/manifests.go
operator/pkg/controlplane/webhook/webhook.go
operator/pkg/tasks/init/wait.go
operator/pkg/util/apiclient/wait_test.go

/kind bug
When attempting to provision multiple Karmada instances in the same namespace, issues relating to client certificate verification will surface either when the operator tries to contact the new provisioned API server as it's provisioning the instance (e.g., to install CRDs), or after the instance has reached ready state.
These issues occur because more label selectors are needed to uniquely identify the resources linked to a Karmada instance when more than one instance is deployed to the namespace.
- Introduction of `app.kubernetes.io/name` and `app.kubernetes.io/instance` [recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) to uniquely identify resources linked …

Fix issues with running multiple Karmada instances in the same namespace

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
operator/pkg/tasks/init/cert.go

/kind feature
This is an implementation of this [proposal](https://github.com/karmada-io/karmada/pull/6176) to add support to the Karmada operator for configuring the validity period of control plane leaf certificates.
```shell
mc -n karmada-system get karmadas.operator.karmada.io t1 -oyaml | yq '.spec.customCertificate'
```
```yaml
null
```
```shell
mc -n karmada-system get secrets t1-karmada-cert -o jsonpath='{.data.apiserver\.crt}' | base64 --decode | openssl x509 -text -noout | grep -i "not after"
```
```text
Not After : Mar  9 16:10:09 2026 GMT
```
```shell
mc -n karmada-system get karmadas.operator.karmada.io t2 -oyaml | yq '.spec.customCertificate'
```
```yaml
leafCertValidityDays: 90
```
```shell
mc -n …
```

Add Support to Configure Leaf Certificate Validity Period in Karmada Operator

---

hack/deploy-karmada-operator.sh
hack/local-up-karmada-by-operator.sh
hack/operator-e2e-environment.sh
operator/config/deploy/karmada-operator-clusterrole.yaml
operator/config/deploy/karmada-operator-clusterrolebinding.yaml
operator/config/deploy/karmada-operator-deployment.yaml
operator/config/deploy/karmada-operator-serviceaccount.yaml
operator/pkg/constants/constants.go
operator/pkg/controlplane/apiserver/apiserver.go
operator/pkg/controlplane/apiserver/manifests.go
operator/pkg/controlplane/controlplane.go
operator/pkg/controlplane/etcd/etcd.go
operator/pkg/controlplane/etcd/manifests.go
operator/pkg/controlplane/manifests.go
operator/pkg/controlplane/metricsadapter/manifests.go
operator/pkg/controlplane/metricsadapter/metricsadapter.go
operator/pkg/controlplane/search/manifests.go
operator/pkg/controlplane/search/search.go
operator/pkg/controlplane/webhook/manifests.go
operator/pkg/controlplane/webhook/webhook.go
operator/pkg/tasks/init/wait.go
operator/pkg/util/apiclient/wait_test.go

Cherry pick of #6180 on release-1.13.
#6180: Fix issues with running multiple Karmada instances in the
```release-note
`karmada-operator`: The `karmada-app` label key previously used for control plane components and for the components of the operator itself has been changed to the more idiomatic `app.kubernetes.io/name` label key.
```

Automated cherry pick of #6180: Fix issues with running multiple Karmada instances in the

---

hack/tools/gencomponentdocs/gen_component_docs.go

/kind cleanup
When releasing documents, it is necessary to generate reference documents for different components through gencomponentdocs. Currently, only the generation of individual components one by one is supported, which is inefficient and prone to omissions. In actual usage scenarios, a more common situation is to generate reference documents for all components at once. Therefore, I hope to introduce the "module all" to support the full-scale generation of component reference documents. 
Fixes #
Before:
```bash
./gencomponentdocs ../website/docs/reference/components/ karmada-webhook
./gencomponentdocs …
```

gencomponentdocs support module all to generate all karmada components docs

---

artifacts/deploy/karmada-scheduler-estimator.yaml
hack/deploy-karmada.sh

/kind cleanup
Change the name of the server certificate used by the karmada-scheduler-estimator from `karmada-metrics-adapter-cert` to `karmada-scheduler-estimator-cert` to meet the convention.
Part of https://github.com/karmada-io/karmada/issues/6051
The secrets generated from local-up-karmada.sh
```release-note
None
```

Fix the naming of the server certificate of karmada-scheduler-estimator

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/controllers/certificate/approver/agent_csr_approving.go
pkg/controllers/cluster/cluster_controller.go
pkg/controllers/cluster/taint_manager.go
pkg/controllers/deploymentreplicassyncer/deployment_replicas_syncer_controller.go
pkg/controllers/execution/execution_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
pkg/controllers/hpascaletargetmarker/hpa_scale_target_marker_controller.go
pkg/controllers/mcs/endpointslice_controller.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/mcs/service_import_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/controllers/namespace/namespace_sync_controller.go
pkg/controllers/unifiedauth/unified_auth_controller.go
pkg/controllers/workloadrebalancer/workloadrebalancer_controller.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/detector/detector.go

/kind feature
part of  https://github.com/karmada-io/karmada/issues/5790
```release-note
`karmada-controller-manager`: All controller reconcile frequency will honor a unified rate limiter configuration(--rate-limiter-*).
`karmada-agent`: All controller reconcile frequency will honor a unified rate limiter configuration(--rate-limiter-*).
```

add the ratelimiter options parameter for controllers that are missing it

---

pkg/controllers/binding/binding_controller_test.go
pkg/controllers/binding/cluster_resource_binding_controller_test.go
pkg/controllers/status/crb_status_controller_test.go
pkg/controllers/status/rb_status_controller_test.go
pkg/util/helper/binding_test.go
pkg/util/helper/index.go
pkg/util/helper/work.go
pkg/util/helper/work_test.go
pkg/util/helper/workstatus_test.go
pkg/util/indexregistry/fieldindex.go

/kind cleanup
This PR introduced two index names for Works, to replace the original label name.
Each index should have a unique name, better not to share it with the label name.
Fixes #
This PR focuses on renaming the index name and introduces a dedicated package(`pkg/util/indexregistry`) that could be used to store all indexes.
```release-note
NONE
```

Update Works index with a unique name

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/controllers/ctrlutil/work.go
pkg/controllers/ctrlutil/work_test.go
pkg/controllers/mcs/common.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller_test.go
pkg/controllers/multiclusterservice/mcs_controller.go
pkg/controllers/status/work_status_controller.go
pkg/util/constants.go
pkg/util/helper/predicate.go
pkg/util/helper/predicate_test.go
pkg/util/helper/work.go
pkg/webhook/work/mutating.go

Replace `propagation.karmada.io/instruction` with `suspendDispatching` field. Annotation was just a temporary solution. With the native support of the work API, we should deprecate the use of annotations and utilize the work field instead.
Fixes #5386 
```release-note
`Deprecation`: The label `propagation.karmada.io/instruction` now has been deprecated in favor of the field(`.spec.suspendDispatching`) in Work API, the label will be removed in future releases.
```

feat: replace instruction annotation with work suspendDispatching field

---

cmd/agent/app/agent.go

/kind bug
When the [report-secrets](https://github.com/karmada-io/karmada/blob/release-1.13/cmd/agent/app/options/options.go#L202) flag is set to `None` in the `agent` component, cluster and cluster impersonator secrets will not be generated.  However, those secret pointers will still be dereferenced in the code, resulting in a segmentation violation.
Fixes #6213
```release-note
`karmada-agent`: Fixed a panic issue where the agent does not need to report secure when registering cluster.
```

Fix segmentation violation error in `agent` component

---

cmd/agent/app/agent.go

Cherry pick of #6214 on release-1.13.
#6214: Fix segmentation violation error in karmada-agent component
```release-note
`karmada-agent`: Fixed a panic issue where the agent does not need to report secret when registering cluster.
```

Automated cherry pick of #6214: Fix segmentation violation error in karmada-agent component

---

pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/crb_graceful_eviction_controller_test.go
pkg/controllers/gracefuleviction/evictiontask.go
pkg/controllers/gracefuleviction/evictiontask_test.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller_test.go

/kind bug
When the binding object is scheduled but there is no result, the SchedulerObservedGeneration in the binding object status will not be set to the generation value, which results in graceful-eviction-controller will not be able to handle gracefulEvictionTask and will always remain.
Fixes #3747
```release-note
`karmada-controller-manager`: fix the issue where the binding gracefulEvictionTask can never be clear.
```

fix the issue where the binding gracefulEvictionTask can never be clear

---

pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/crb_graceful_eviction_controller_test.go
pkg/controllers/gracefuleviction/evictiontask.go
pkg/controllers/gracefuleviction/evictiontask_test.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller_test.go

Cherry pick of #6227 on release-1.13.
#6227: to prevent the generation judgment from always being false
```release-note
`karmada-controller-manager`: Fixed the issue that the gracefulEvictionTask of ResourceBinding can not be cleared in case of schedule fails.
```

Automated cherry pick of #6227: to prevent the generation judgment from always being false

---

cmd/agent/app/agent.go
cmd/aggregated-apiserver/app/options/options.go
cmd/controller-manager/app/controllermanager.go
cmd/descheduler/app/descheduler.go
cmd/karmada-search/app/karmada-search.go
cmd/metrics-adapter/app/options/options.go
cmd/scheduler-estimator/app/scheduler-estimator.go
cmd/scheduler/app/scheduler.go
cmd/webhook/app/webhook.go

/kind bug
#6094
```release-note
For all components with rate limit parameters of 'kube-api-qps' and 'kube-api-burst', and scheduler-estimator with 'cluster-api-qps' and 'cluster-api-burst', these parameters will be stricter and administrators may need to adjust them to get the same effect as before the update.
```

unify http ratelimiter for control plane client

---

test/e2e/suites/operator/api_sidecar_test.go
test/e2e/suites/operator/suite_test.go

/kind cleanup
Add sidecar configuration e2e test, protect the following two scenarios:
- check if the sidecar configuration works
- check if the configuration of the main container will not be applied to the sidecar container
Parts of #6138
```release-note
NONE
```

e2e: add sidecar configuration e2e test

---

charts/karmada/templates/pre-install-job.yaml

/kind bug
When installing Karmada using the Helm chart with `certs.mode` set to `custom`, the required `ClusterRole`, `ClusterRoleBinding`, and `ServiceAccount` are not created: https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/pre-install-job.yaml#L449-L498. 
These resources are essential for the [static-resource-job](https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-static-resource-job.yaml#L32), [post-delete-job](https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/post-delete-job.yaml#L36), and [post-install-job](https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/post-install-job.yaml#L42) to function correctly.
To …

Fix missing ClusterRole, ClusterRoleBinding, and ServiceAccount for Custom Cert Mode in Helm Chart

---

charts/karmada/templates/pre-install-job.yaml

Cherry pick of #6188 on release-1.13.
#6188: Fix Missing Role, RoleBinding, and ServiceAccount for Custom
```release-note
helm: Fixed the issue where the required ServiceAccount was missing when the certificate mode was set to custom. 
```

Automated cherry pick of #6188: Fix Missing Role, RoleBinding, and ServiceAccount for Custom

---

.github/workflows/lint-chart.yaml
charts/OWNERS
charts/karmada/Chart.yaml
hack/setup-dev-base.sh

/kind cleanup
Refer to https://github.com/karmada-io/karmada/actions/runs/14121042195/job/39570423517?pr=6240#step:11:50. The CI failed due to the maintainer NotFound error in file [charts/karmada/Chart.yaml](https://github.com/karmada-io/karmada/blob/release-1.11/charts/karmada/Chart.yaml). As `@pidb` has no longer maintained helm since release-1.12, this PR will clean up `@pidb` in the maintainer list.
Fixes #
```release-note
None.
```

release-1.11: remove charts maintainer

---

pkg/resourceinterpreter/default/native/aggregatestatus.go
pkg/resourceinterpreter/default/native/aggregatestatus_test.go
test/e2e/suites/base/resource_test.go

/kind bug
see #6248
Fixes #6248
```release-note
karmada-controller-manager: The default resource interpreter will no longer populate the `.status.LoadBalancer.Ingress[].Hostname` field with the member cluster name for Service and Ingress resources.
```

don't add cluster name to hostname field when aggregate service status

---

pkg/dependenciesdistributor/dependencies_distributor.go
pkg/dependenciesdistributor/dependencies_distributor_test.go

/kind feature
Each time a dependency resource is updated, dependenciesdistributor reconcile will be triggered and executed twice, if  `labels` field not updated, the second time is unnecessary.
When dependent resources are updated, reconcile is triggered twice. If labels are not updated, the second reconcile is meaningless.
The queue provided by go-client will automatically deduplicate if the same resource object key exists, provided that the resource object key is comparable, that is, implements the Comparable interface. The following types can be compared:
For the type `LabelsKey`, because there is an element labels, which is a map type, and  `LabelsKey` is pointer type, it becomes an …

fix(dependenciesdistributor): reduce update trigger

---

cmd/agent/app/agent.go
pkg/karmadactl/join/join.go
pkg/karmadactl/join/join_test.go
pkg/util/cluster.go
pkg/util/cluster_test.go

/kind bug
Since there is no uniqueness check for the names of the registering clusters, a new pull-mode cluster may overwrite an existing member cluster. Therefore, I added a uniqueness check for the cluster names. 
Fixes #6229
```release-note
`karmada-agent`: Fixed the issue where a new pull-mode cluster may overwrite the existing member clusters.
```

fix: A new pull-mode cluster may overwrite the existing member clusters

---

pkg/karmadactl/deinit/deinit.go
pkg/karmadactl/deinit/deinit_test.go

In this commit, we unit test deinit in karmadactl on deleting all components related to karmada after it was initialized using init.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl: unit test deinit

---

cmd/agent/app/agent.go
pkg/karmadactl/join/join.go
pkg/util/cluster.go
pkg/util/cluster_test.go

Cherry pick of #6253 on release-1.11.
#6253: fix: A new pull-mode cluster may overwrite the existing
```release-note
`karmada-agent`: Fixed the issue where a new pull-mode cluster may overwrite the existing member clusters.
```

Automated cherry pick of #6253: fix: A new pull-mode cluster may overwrite the existing

---

pkg/karmadactl/addons/utils/helpers.go
pkg/karmadactl/cmdinit/utils/deploy.go
pkg/karmadactl/register/register.go
pkg/karmadactl/util/check.go

/kind bug
When the command "register" processes the "discovery-timeout", it directly uses the value of "int(o.Timeout)" as the number of seconds for the "timeout", which causes the "timeout" to become ineffective.  
For example:
- set flag `discovery-timeout` to 5m, the `int(o.Timeout)` will be 300000000000, leading to the timeout duration being greatly magnified. 
- set flag `discovery-timeout` to 10m, the command `register` will fail immediately
Fixes #
```release-note
`karmadactl`: Fixed the issue where option `discovery-timeout` fails to work properly
```

fix the issue where discovery-timeout fails to work properly

---

pkg/karmadactl/addons/utils/helpers.go
pkg/karmadactl/cmdinit/utils/deploy.go
pkg/karmadactl/register/register.go
pkg/karmadactl/util/check.go

Cherry pick of #6270 on release-1.13.
#6270: fix the issue where discovery-timeout fails to work properly
Part of #6275 
```release-note
`karmadactl`: Fixed the issue where option `discovery-timeout` fails to work properly
```

Automated cherry pick of #6270: fix the issue where discovery-timeout fails to work properly

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
cmd/descheduler/app/descheduler.go
cmd/metrics-adapter/app/options/options.go
cmd/scheduler-estimator/app/scheduler-estimator.go
cmd/scheduler/app/scheduler.go
cmd/webhook/app/webhook.go
operator/cmd/operator/app/operator.go

/kind feature
This PR is the next PR of #6044 
Fixes #
```release-note
`Instrumentation`: Introduced `karmada_build_info` metric, which exposes build metadata, to components `karmada-agent`, `karmada-controller-manager`, `karmada-descheduler`, `karmada-metrics-adapter`, `karmada-scheduler-estimator`, `karmada-scheduler`, and `karmada-webhook`.
```

feat: add build_info metrics and go runtime metrics for karmada

---

pkg/resourceinterpreter/default/native/aggregatestatus.go
pkg/util/helper/ingress.go
pkg/util/helper/ingress_test.go
pkg/util/helper/service.go
pkg/util/helper/service_test.go

/kind feature
Like described in https://github.com/karmada-io/karmada/issues/6248, If we no longer add the cluster name when aggregating the status of Services and Ingress, there will be redundant items with the same content in multiple ingresses in the status. like:
```
status:
loadBalancer:
ingress:
- hostname: xxx.xxx.com
- hostname: xxx.xxx.com
```
This pr adds the cluster name as an identifier when the member cluster status is not nil, and deduplicates and sorts the identical items in the list.
Fixes #
This PR includes a commit included in #6249. It is better to rebase and review this PR after merging #6249. …

Deduplicate and sort status for Service and Ingress when aggregating status

---

.golangci.yml
hack/verify-staticcheck.sh

/kind cleanup
This PR upgrades `golangci-lint` from `v1.64.8` to the latest stable version, `v2.0.2`. The configuration file (`.golangci.yml`) has been updated to align with the significant structural changes introduced in `v2.0`, primarily guided by the output of the `golangci-lint migrate` command and the official migration documentation.
Key changes include:
**Separation of Linters and Formatters**: `gofmt`, `goimports`, and `gci` have been moved from the `linters.enable` list to the new top-level `formatters.enable` section, reflecting their primary role. Their settings are now under `formatters.settings`.
**Implicit Standard Linters**: Linters enabled by **default** or integral to golangci-lint's core operation in …

Upgrade golangci-lint from v1.64.8 to v2.0.2

---

artifacts/agent/karmada-agent.yaml
artifacts/deploy/karmada-aggregated-apiserver.yaml
artifacts/deploy/karmada-controller-manager.yaml
artifacts/deploy/karmada-descheduler.yaml
artifacts/deploy/karmada-metrics-adapter.yaml
artifacts/deploy/karmada-scheduler-estimator.yaml
artifacts/deploy/karmada-scheduler.yaml
artifacts/deploy/karmada-search.yaml
artifacts/deploy/karmada-webhook.yaml

/kind cleanup
This PR updates the listening addresses for multiple components (agent, metrics adapter, webhook, etc.) to use the Pod's IP address via the `POD_IP` environment variable. By binding to the specific Pod IP rather than a generic address like `0.0.0.0`, the components are restricted to listening only on their assigned network interface. This improves security by reducing exposure, and ensures that metrics and health probes are correctly bound to the right interface, aiding in more predictable network behavior.
Part of #6266 
- The changes affect all relevant deployments.
- Ensure that after these changes, all inter-component communications …

Update bind addresses to use POD_IP for local-up script

---

.golangci.yml

/kind cleanup
Add a comment explaining the reason for disabling QF1008.
For more details, please refer to https://github.com/karmada-io/karmada/pull/6288.
Part of https://github.com/karmada-io/karmada/issues/6273
```release-note
NONE
```

Add comment for disabling QF1008

---

.golangci.yml
pkg/karmadactl/get/get.go

/kind cleanup
Fix lint issue - `QF1001: could apply De Morgan's law (staticcheck)`.
For more details: https://staticcheck.dev/docs/checks#QF1001
Part of #6273
```release-note
NONE
```

Fix lint issue QF1001

---

.golangci.yml
cmd/service-name-resolution-detector-example/app/options/coredns.go
cmd/service-name-resolution-detector-example/app/service-name-resolution-detector.go
pkg/servicenameresolutiondetector/coredns/detector.go
pkg/servicenameresolutiondetector/coredns/detector_test.go

/kind cleanup
Fix lint issue - `ST1011: var periodSeconds is of type time.Duration; don't use unit-specific suffix "Seconds" (staticcheck)`.
For more details: https://staticcheck.dev/docs/checks#ST1011
Part of #6273
```release-note
NONE
```

Fix lint issue ST1011

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml

The user may have deployed a FlinkDeployment YAML with missing spec requirements, which prevents the deployment from being created. This will publish an error in status and we should treat this as a healthy user error.
The previous health check will consider this type as unhealthy and therefore reschedule the application. This fixes the behavior by checking the additional `error` field and let Karmada not reschedule the job if user error exists.
Fixes #
```release-note
NONE
```

update Flink interpreter to check error when job state is not published

---

.golangci.yml

/kind cleanup
Add comment for disabling [`ST1000`](https://staticcheck.dev/docs/checks/#ST1000) and `package-comments`.
Part of #6273
```release-note
NONE
```

Add comment for disabling ST1000 and package-comments

---

docs/proposals/karmada-operator/pod-disruption-budget/README.md

Add design doc
/kind design
All details are included in the design document.
Fixes #
```release-note
The newly introduced `CommonSettings.podDisruptionBudgetConfig `field can be optionally set by users to specify the settings to create a pod disruption budget that will be used to ensure the availability of control plane components during planned disruption events.
```

Proposal: Add PodDisruptionBudget (PDB) Support in the Karmada Operator

---

pkg/controllers/cronfederatedhpa/cronfederatedhpa_controller.go
pkg/controllers/federatedhpa/federatedhpa_controller.go
pkg/controllers/federatedhpa/metrics/client.go

Modify the calling methods of the following metric functions in FHPA：
metrics.ObserveProcessCronFederatedHPALatency
metrics.ObserveProcessFederatedHPALatency
metrics.ObserveFederatedHPAPullMetricsLatency
Get the final execution error status of FHPA logic
Fixes #6300
```release-note
`karmada-metrics-adapter`: Fixed the issue that the result label of `federatedhpa_pull_metrics_duration_seconds` is always `success`.
```

fix fhpa metrics issue introduced by #6300

---

pkg/controllers/binding/binding_controller.go
pkg/controllers/binding/cluster_resource_binding_controller.go
pkg/dependenciesdistributor/dependencies_distributor.go
pkg/detector/detector.go
pkg/detector/policy.go
pkg/detector/preemption.go
pkg/util/overridemanager/overridemanager.go

/kind feature
When the node CPU usage rate is almost over 90%, it seems that deepcopy cost the most time:
```
I1113 14:36:11.161745      18 overridemanager.go:181] applyNamespacedOverrides, list configmap-beta-moa-demo-prod-681,  cluster member-cluster1, cost: 0.980144234
I1113 14:36:12.445315      18 overridemanager.go:181] applyNamespacedOverrides, list configmap-beta-moa-demo-prod-681,  cluster member-cluster2, cost: 0.811084427
```
After turning off list deepcopy, the list time is reduced to 0.1s or even lower.
```
I1113 15:43:39.212238      17 overridemanager.go:182] applyNamespacedOverrides, list beta-moa-demo-prod-283,  cluster member-cluster1, cost: 0.040210384
I1113 15:43:39.251189      17 …
```

disable deepcopy for list action

---

operator/pkg/controlplane/etcd/etcd.go

In this commit, we remove the redundant field `EtcdPeerServiceName` in the function `installKarmadaEtcd` in `operator/pkg/controlplane/etcd` package. 
/kind cleanup
Fixes #5584
```release-note
NONE
```

operator/pkg/controlplane/etcd: remove redundant `EtcdPeerServiceName`

---

pkg/karmadactl/apply/apply.go
pkg/karmadactl/apply/apply_test.go

In this commit, we unit test apply command on validation, and generating propagation objects.
Part of #5491.
```release-note
NONE
```

pkg/karmadactl: unit test apply command

---

pkg/webhook/multiclusterservice/mutating_test.go

In this commit, we refactor the multi-cluster service object names and check on number of patches after the mutation happens.
Motivated by @XiShanYongYe-Chang's comment https://github.com/karmada-io/karmada/pull/5494#discussion_r1758148145.
/kind cleanup
Follow-up on #5517.
```release-note
NONE
```

pkg/webhook: refactor Multi-Cluster Service test

---

operator/pkg/tasks/init/upload_test.go

In this commit, we unit test the upload init task in the operator package on create new upload task and making sure the upload `kubeconfig` secret working as expected.
Part of #5491.
**Dependency**
This PR depends on #5630.
```release-note
NONE
```

operator/pkg/tasks/init: unit test upload

---

pkg/controllers/status/work_status_controller.go
pkg/util/objectwatcher/objectwatcher.go

/kind feature
Add deepequal check for objectWatcher.Update() in karmada-controller-manager to reduce redundant HTTP update operations on member clusters, which helps reduce the time consumption of karmada-controller-manager startup.
Fixes #
If #6148 can be merged and this PR can be rebased on it, the changes brought by this PR can be more clearly shown through these metrics.
```release-note
`Performance`/`karmada-controller-manager`: Now when karmada-controller-manager tries to update a resource to a member cluster, it will attempt to compare the contents to skip redundant update operations. The …
```

Add deepequal check for objectWatcher.Update()

---

charts/karmada/templates/_helpers.tpl
charts/karmada/templates/karmada-agent.yaml
charts/karmada/templates/karmada-aggregated-apiserver.yaml
charts/karmada/templates/karmada-controller-manager.yaml
charts/karmada/templates/karmada-descheduler.yaml
charts/karmada/templates/karmada-metrics-adapter.yaml
charts/karmada/templates/karmada-scheduler-estimator.yaml
charts/karmada/templates/karmada-scheduler.yaml
charts/karmada/templates/karmada-search.yaml
charts/karmada/templates/karmada-webhook.yaml

/kind cleanup
This PR updates the listening addresses for multiple components (metrics adapter, webhook, etc.) to use the Pod's IP address via the `POD_IP` environment variable. By binding to the specific Pod IP rather than a generic address like `0.0.0.0`, the components are restricted to listening only on their assigned network interface. This improves security by reducing exposure and ensures that metrics and health probes are correctly bound to the right interface, aiding in more predictable network behavior.
Part of #6266 
- The changes affect all relevant deployments.
- Ensure that after these changes, all inter-component communications (e.g., …

Update bind addresses to use POD_IP for helm

---

pkg/karmadactl/addons/descheduler/manifests.go
pkg/karmadactl/addons/estimator/manifests.go
pkg/karmadactl/addons/metricsadapter/manifests.go
pkg/karmadactl/addons/search/manifests.go
pkg/karmadactl/cmdinit/kubernetes/deployments.go

/kind cleanup
This PR updates the listening addresses for multiple components (metrics adapter, webhook, etc.) to use the Pod's IP address via the `POD_IP` environment variable. By binding to the specific Pod IP rather than a generic address like `0.0.0.0`, the components are restricted to listening only on their assigned network interface. This improves security by reducing exposure and ensures that metrics and health probes are correctly bound to the right interface, aiding in more predictable network behavior.
Part of #6266 
- The changes affect all relevant deployments.
- Ensure that after these changes, all inter-component communications (e.g., …

Update bind addresses to use POD_IP for karmadactl

---

operator/pkg/controlplane/apiserver/manifests.go
operator/pkg/controlplane/manifests.go
operator/pkg/controlplane/metricsadapter/manifests.go
operator/pkg/controlplane/search/manifests.go
operator/pkg/controlplane/webhook/manifests.go

/kind cleanup
This PR updates the listening addresses for multiple components (metrics adapter, webhook, etc.) to use the Pod's IP address via the `POD_IP` environment variable. By binding to the specific Pod IP rather than a generic address like `0.0.0.0`, the components are restricted to listening only on their assigned network interface. This improves security by reducing exposure and ensures that metrics and health probes are correctly bound to the right interface, aiding in more predictable network behavior.
Part of #6266 
- The changes affect all relevant deployments.
- Ensure that after these changes, all inter-component communications (e.g., …

Update bind addresses to use POD_IP for karmada-operator

---

pkg/karmadactl/register/register.go

/kind bug
`karmada register` command generates `/etc/karmada/bootstrap-karmada-agent.conf` with the endpoint in `default/cluster-info` configmap which can often be un-reachable from member clusters (`karmada-apiserver.karmada-system.svc.cluster.local` in most cases as reported in #4262 ??). 
Moreover, `karmada register` command does not provide any way to change the url. Thus, `karmada register` can NOT generate proper kubeconfig for karmada-agent. and it keeps failing to deploy karmada-agent on member clusters.
This PR make `karmada register` use the bootstrap endpoint which user passed instead of cluster-info.
Fixes #4262 
Discussion: should we …

'karmadactl register' should use bootstrap endpoint for karmada-agents' kubeconfig instead of discovered cluster-info

---

pkg/controllers/status/cluster_status_controller.go

Fixes Issue：[6281 ](https://github.com/karmada-io/karmada/issues/6281)
Fixes #6281
```release-note
`karmada-controller-manager`/`karmada-agent`: Fixed the issue that cluster status update interval shorter than configured `--cluster-status-update-frequency`.
```

Fix cluster status update interval not hornor `--cluster-status-update-frequency` issue

---

docs/CHANGELOG/CHANGELOG-1.11.md
docs/CHANGELOG/CHANGELOG-1.12.md
docs/CHANGELOG/CHANGELOG-1.13.md
docs/CHANGELOG/CHANGELOG-1.14.md

According to Karmada's release cycle, the release team is preparing to release v1.14.0-beta.0 the end of the month, along with patch version for the maintenance releases. This pr is used to publish its release notes
Fixes #
```release-note
NONE
```

publish release note for v1.14.0-beta.0, v1.13.2, v1.12.6, v1.11.9

---

go.mod
go.sum
vendor/modules.txt

/kind cleanup
Bump custom-metrics-apiserver with an official release [with Kubernetes dependencies v0.32.0](https://github.com/kubernetes-sigs/custom-metrics-apiserver/releases) to include [k8s dependencies 0.32](https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/194).
Part of #6310 
```release-note
NONE
```

Bump custom-metrics-apiserver version to v1.32.0

---

pkg/scheduler/event_handler.go

/kind bug
Ref to #6354, karmada-scheduler should not enqueue rbs/crbs when the cluster is updated if `binding.spec.suspension.scheduling` is set to true.
Fixes #6354
```release-note
`karmada-scheduler`: Fixed the issue where resource scheduling suspension may become ineffective during a cluster update.
```

fixed the issue where resource scheduling suspension may become ineffective

---

operator/pkg/util/naming.go

In this commit, we update go doc comments and parameter names for more clarity and readability. This is completely subjective and I am very open to the feedback.
This opportunity for improvement was identified while working on PR #5638.
The decision to separate this change into its own PR was motivated by feedback from @zhzhuang-zju and @XiShanYongYe-Chang, as discussed in https://github.com/karmada-io/karmada/pull/5638#discussion_r2055122547 and https://github.com/karmada-io/karmada/pull/5638#discussion_r2055128537, respectively.
```release-note
NONE
```

operator/pkg/util/naming: update go doc comments for more clarity and readability

---

pkg/scheduler/event_handler.go

Cherry pick of #6356 on release-1.13.
#6356: fixed the issue where resource scheduling suspension may
```release-note
`karmada-scheduler`: Fixed the issue where resource scheduling suspension may become ineffective during a cluster update.
```

Automated cherry pick of #6356: fixed the issue where resource scheduling suspension may

---

charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
pkg/apis/policy/v1alpha1/federatedresourcequota_types.go

/kind feature
I would like to improve the output of `kubectl/karmadactl get federatedResourceQuota`. The current output looks like this:
```bash
✗ kubectl get federatedresourcequotas.policy.karmada.io                                       
NAME   AGE
test   3m59s
```
There is no useful information currently. We can also add the overall and overallUsed fields to the output, like:
```bash
kubectl get federatedresourcequotas.policy.karmada.io
NAME   OVERALL          OVERALL_USED
test   {"cpu":"100m"}   
```
Parts of #6350 
```release-note
`FederatedResourceQuota`: Added two additional printer columns, …
```

additional print columns for CRDs FederatedResourceQuota

---

test/e2e/suites/base/search_test.go
test/e2e/suites/base/suite_test.go

/kind cleanup
In the `ginkgo.SynchronizedBeforeSuite`, we create two namespaces: testNamespace and secondaryTestNamespace. However, during the cleanup phase, only testNamespace will be cleaned up, resulting in a leftover namespace.
Fixes #
```release-note
```

e2e: cleanup all namespaces created both in control plane and member clusters

---

pkg/webhook/federatedresourcequota/validating.go
pkg/webhook/federatedresourcequota/validating_test.go

Signed-off-by: likakuli <1154584512@qq.com>
/kind feature
FedResourceQuota is a user-facing resource and its name is used in work's label. So the length should be no more than 63 characters like other resource. e.g. `PropagationPolicy`
Fixes #
```release-note
`karmada-webhook`: The length of FederatedResourceQuota now has been restricted to no more than 63 chars.
```

feature: add name length check for fedresourcequota

---

pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_sync_controller_test.go
test/e2e/suites/base/federatedresourcequota_test.go
test/helper/policy.go

/kind feature
Adjust the behavior of the legacy staticAssignments to skip creating redundant ResourceQuotas to member clusters
Parts of #6350
```release-note
```

FederatedResourceQuota: skip creating redundant ResourceQuotas to member clusters

---

hack/deploy-karmada.sh

/kind design
This pr is about [#6091](https://github.com/karmada-io/karmada/issues/6091)
Fixes [#6091](https://github.com/karmada-io/karmada/issues/6091) 
@XiShanYongYe-Chang 
@zhzhuang-zju 
```release-note
```

design:Add component certificate identification for karmada components

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
operator/pkg/controlplane/apiserver/apiserver.go

This commit introduces support for the `loadBalancerClass` field in the Karmada operator CRD for the `karmadaAPIServer` component.
When the `serviceType` for `karmadaAPIServer` is set to `LoadBalancer`, users can now specify a `loadBalancerClass` to select a specific load balancer implementation, aligning with Kubernetes Service behavior.
Changes include:
- Added `loadBalancerClass` field to the `karmadas.operator.karmada.io` CRD.
- Added `LoadBalancerClass` field to the `KarmadaAPIServer` struct in Go types.
- Updated the `createKarmadaAPIServerService` function to set the `spec.loadBalancerClass` on the Service object when applicable.
/kind feature
Fixes #
**Special notes for your …

feat(operator): support loadBalancerClass for karmadaAPIServer

---

pkg/scheduler/scheduler.go

Cherry pick of #6369 on release-1.13.
#6369: fix the issue where bindings that fails
```release-note
`karmada-scheduler`: Fixed the issue where bindings that fail occasionally will be treated as unschedulableBindings when feature gate PriorityBasedScheduling is enabled.
```

Automated cherry pick of #6369: fix the issue where bindings that fails

---

pkg/controllers/federatedresourcequota/federated_resource_quota_status_controller.go

/kind feature
Update `federated-resource-quota-status-controller` so that staticAssignment only updates `AggregatedStatus`
Parts of #6350 
```release-note
`karmada-controller-manager`: The `federated-resource-quota-status-controller` will skip reflecting overall and overall used in case the Federated Resource Quota Enforcement feature is on.
```

staticAssignment only updates AggregatedStatus

---

artifacts/deploy/karmada-webhook.yaml
artifacts/deploy/webhook-configuration.yaml
charts/karmada/templates/_karmada_webhook_configuration.tpl
cmd/webhook/app/options/options.go
cmd/webhook/app/webhook.go
operator/pkg/karmadaresource/webhookconfiguration/manifests.go
pkg/karmadactl/cmdinit/karmada/webhook_configuration.go
pkg/webhook/resourcebinding/validating.go
pkg/webhook/resourcebinding/validating_test.go

/kind feature
The webhook intercepts `CREATE` and `UPDATE` events for `ResourceBinding` objects.
-   For `CREATE` events (when a `ResourceBinding` is scheduled, i.e., `spec.clusters` is populated): It calculates the resources requested by the `ResourceBinding` (based on `spec.clusters[].replicas` and `spec.replicaRequirements.resourceRequest`). It then checks if adding this usage to the current `FederatedResourceQuota.status.overallUsed` would exceed the `FederatedResourceQuota.spec.overall` limit. If it exceeds, the request is denied. Otherwise, `FederatedResourceQuota.status.overallUsed` is updated, and the request is allowed.
-   For `UPDATE` events on `ResourceBinding`: It calculates the delta in resource usage based …

Create RB ValidatingWebhook for FederatedResourceQuota check

---

cmd/controller-manager/app/controllermanager.go
pkg/controllers/cluster/cluster_controller.go
pkg/controllers/taint/clustertaintpolicy_controller.go
pkg/controllers/taint/clustertaintpolicy_controller_test.go
pkg/util/helper/taint.go

/kind feature
Add the ClusterTaintPolicy controller to handle taints on the clusters
Part of #6317
```release-note
`karmada-controller-manager`: Added the `clustertaintpolicy` controller to manage cluster taint based on ClusterTaintPolicy.
```

Add the ClusterTaintPolicy controller to handle taints on the clusters

---

charts/karmada/templates/_helpers.tpl
charts/karmada/templates/karmada-webhook.yaml
charts/karmada/values.yaml

/kind feature
This PR adds feature gates support to the `karmada-webhook` Helm Chart configuration. Users can now configure feature gates for the webhook component via the `webhook.featureGates` field in `values.yaml`, similar to other components like [controllerManager](https://github.com/karmada-io/karmada/blob/master/charts/karmada/values.yaml#L353) and [schedulerEstimator](https://github.com/karmada-io/karmada/blob/master/charts/karmada/values.yaml#L890). This provides a consistent and flexible way to enable or disable webhook features across all installation modes.
Part of #6350 
```release-note …
```

Add feature gates support to karmada-webhook config (Helm Chart)

---

docs/proposals/karmada-operator/reconciliation-suspension/README.md

/kind design
Details are in the design doc.
Fixes #
```release-note
The new optional `spec.suspend` field can be used to temporarily pause/suspend the reconciliation of a `Karmada` object.
```

Proposal: Support Suspension of Reconciliation for Karmada Control Planes

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
hack/local-up-karmada-by-operator.sh
operator/config/crds/operator.karmada.io_karmadas.yaml
operator/pkg/apis/operator/v1alpha1/type.go
operator/pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
operator/pkg/controller/karmada/controller.go

/kind feature
Implementation of this [proposal](https://github.com/karmada-io/karmada/pull/6358).
Fixes #
```release-note
`karmada-operator`: The new optional `spec.suspend` field can be used to temporarily pause/suspend the reconciliation of a `Karmada` object.
```

Support Suspension of Reconciliation for Karmada Control Planes

---

operator/pkg/controlplane/webhook/webhook.go
operator/pkg/controlplane/webhook/webhook_test.go

/kind feature
This PR adds feature gates support to the `karmada-webhook` Karmada Operator configuration. Users can now configure feature gates for the webhook component via the [Karmada CRD](https://github.com/karmada-io/karmada/blob/master/operator/README.md).
Part of #6350 
```release-note
`karmada-operator`: Users can now configure feature gates for karmada-webhook.
```

Add feature gates support to karmada-webhook config (Operator)

---

pkg/util/helper/taint.go
pkg/util/helper/taint_test.go

/kind cleanup
Using a `strings.Builder` for concatenating the taint messages in GenerateTaintsMessage to improve performance and readability when processing a larger number of taints.
As comment in https://github.com/karmada-io/karmada/pull/6368#discussion_r2092411890
Fixes #
```release-note
NONE
```

cleanup: refactor GenerateTaintsMessage method

---

charts/karmada/_crds/bases/policy/policy.karmada.io_clustertaintpolicies.yaml
pkg/apis/policy/v1alpha1/clustertaint_types.go
pkg/apis/policy/v1alpha1/zz_generated.deepcopy.go
pkg/controllers/taint/clustertaintpolicy_controller.go
pkg/generated/openapi/zz_generated.openapi.go

In the previous commit, the ClusterTaintPolicy does not specify the expected definition for resource deletion and field change.
Part of #6317
```release-note
API Change: add comments for field update and ClusterTaintPolicy deletion to the API and use AddOnConditions and RemoveOnConditions to replace MatchConditions.
```

Add comments for field updation and policy deletion for ClusterTaintPolicy API

---

cmd/webhook/app/options/options.go

Disabled NoExecute toleration auto-injection for PP/CPP.
Part of #6317 
cmd output effect based on this patch:
```cmd
Flag --default-not-ready-toleration-seconds has been deprecated, default-not-ready-toleration-seconds is deprecated and will be removed in a future version.
Flag --default-unreachable-toleration-seconds has been deprecated, default-unreachable-toleration-seconds is deprecated and will be removed in a future version.
I0514 16:05:39.410685  457446 webhook.go:114] karmada-webhook version: version.Info{GitVersion:"v1.14.0-beta.0-34-ga0df1eda1", GitCommit:"a0df1eda161e6f73af381242ab9e6d168e13fd56", …
```

Deprecated default-not-ready-toleration-seconds and default-unreachable-toleration-seconds flags for karmada-webhook

---

pkg/controllers/cluster/cluster_controller.go
pkg/controllers/cluster/cluster_controller_test.go
test/e2e/framework/cluster.go
test/e2e/framework/constant.go
test/e2e/suites/base/clusteraffinities_test.go
test/e2e/suites/base/failover_test.go
test/e2e/suites/base/karmadactl_test.go
test/e2e/suites/base/resource_test.go

/kind feature
Remove the behavior of automatically adding not-ready and unreachable NoExecute taints
Part of [#6317](https://github.com/karmada-io/karmada/issues/6317)
@XiShanYongYe-Chang 
```release-note
`karmada-controller-manager`: The clusters-controller no longer automatically adds NoExecute taints to clusters.
```

cluster-controller no longer taints clusters based on conditions

---

cmd/controller-manager/app/controllermanager.go
pkg/apis/cluster/v1alpha1/well_known_constants.go
pkg/controllers/cluster/cluster_controller.go
pkg/controllers/cluster/cluster_controller_test.go
pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/event_handler.go
pkg/scheduler/scheduler.go

/kind feature
No longer add the NoExecute taint for the Deleting Cluster.
Part of #6317 
```release-note
`karmada-controller`: The `cluster-controller` no longer relies on taints to clean up resources on clusters scheduled for deletion, but instead depends on the scheduler to reschedule workloads to other available clusters.
```

No longer add terminting NoExecute taint for the Deleting Cluster

---

artifacts/deploy/karmada-webhook.yaml
artifacts/deploy/webhook-configuration.yaml
cmd/webhook/app/options/options.go
cmd/webhook/app/webhook.go
pkg/webhook/clustertaintpolicy/validating.go
pkg/webhook/clustertaintpolicy/validating_test.go

/kind feature
Add the ClusterTaintPolicy validation
Part of #6317 
```release-note
`karmada-webhook`: Added the ClusterTaintPolicy validation webhook, and added `--allow-no-execute-taint-policy` flag.
```

Add the ClusterTaintPolicy validation

---

artifacts/deploy/karmada-controller-manager.yaml
cmd/controller-manager/app/controllermanager.go
cmd/controller-manager/controller-manager.go
pkg/features/features.go

/kind feature
JSON logging support.  More details are highlighted in #6230.
Fixes #
Partof #6230 
**Tests with feature off**:
```text
I0526 21:00:08.993241   36799 controllermanager.go:151] karmada-controller-manager version: version.Info{GitVersion:"v0.0.0-master", GitCommit:"unknown", GitShortCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.24.1", Compiler:"gc", Platform:"darwin/arm64"}
I0526 21:00:08.994271   36799 envvar.go:172] "Feature gate default state" feature="InformerResourceVersion" enabled=false
I0526 21:00:08.994291   36799 envvar.go:172] "Feature gate default state" feature="WatchListClient" enabled=false
I0526 21:00:08.994293   36799 …
```

JSON logging support for Karmada controller manager component

---

test/e2e/framework/deployment.go
test/e2e/suites/base/federatedresourcequota_test.go

/kind flake
```md
Operation cannot be fulfilled on deployments.apps "deploy-c6rvt": the object has been modified; please apply your changes to the latest version and try again
{
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "Operation cannot be fulfilled on deployments.apps \"deploy-c6rvt\": the object has been modified; please apply your changes to the latest version and try again",
Reason: "Conflict",
Details: {Name: "deploy-c6rvt", Group: "apps", Kind: "deployments", UID: "", Causes: nil, RetryAfterSeconds: 0},
Code: 409,
},
}
```
Ref to https://github.com/karmada-io/karmada/actions/runs/15630222414 …

flakey test: Retry on failed deployment update

---

artifacts/deploy/karmada-webhook.yaml
cmd/webhook/app/options/options.go
cmd/webhook/app/webhook.go
operator/pkg/controlplane/webhook/manifests.go
pkg/util/helper/taint.go
pkg/util/helper/taint_test.go
pkg/webhook/clusterpropagationpolicy/mutating.go
pkg/webhook/clusterpropagationpolicy/mutating_test.go
pkg/webhook/propagationpolicy/mutating.go
pkg/webhook/propagationpolicy/mutating_test.go
test/e2e/suites/base/clusteraffinities_test.go
test/e2e/suites/base/failover_test.go

We have deprecated `default-not-ready-toleration-seconds` and `default-unreachable-toleration-seconds` flags for `karmada-webhook` in v1.14: #6373, now, we can remove them.
Part of #6428
```release-note
`karmada-webhook`: The `--default-not-ready-toleration-seconds` and `--default-unreachable-toleration-seconds` flags which were deprecated in release-1.14, now has been removed.
```

Remove default-not-ready-toleration-seconds and default-unreachable-toleration-seconds flags

---

.github/dependabot.yml
.github/workflows/ci-image-scanning-on-schedule.yml
.github/workflows/ci-schedule-compatibility.yaml
operator/config/samples/karmada.yaml

/kind cleanup
Part of #6451 
**Special notes for your reviewer**: NA
```release-note
NONE
```

chore: update maintained versions to `1.14` and bump imageTag to `v1.14.0`

---

artifacts/deploy/karmada-controller-manager.yaml
cmd/controller-manager/app/options/options.go
operator/pkg/controlplane/manifests.go

In v1.14, we have deprecated the `failover-eviction-timeout` flag, now, we can remove it in v1.15.
Part of #6428
```release-note
`karmaa-controller-manager`: The flag `--failover-eviction-timeout` has been deprecated in release-1.14, now has been removed. 
```

Remove failover-eviction-timeout flag in the karmada-controller-manager

---

artifacts/agent/karmada-agent.yaml
cmd/agent/app/agent.go
cmd/agent/main.go

/kind feature
Part of https://github.com/karmada-io/karmada/issues/6230
Example output log with `--logging-format json` set:
```
{"ts":1749695644313.8142,"caller":"app/agent.go:148","msg":"karmada-agent version: version.Info{GitVersion:\"\", GitCommit:\"a1b734cfac92bf2ad728a7029d2549ab755c1886\", GitShortCommit:\"a1b734cfa\", GitTreeState:\"dirty\", BuildDate:\"2025-06-11T23:24:24Z\", GoVersion:\"go1.24.2\", Compiler:\"gc\", Platform:\"linux/amd64\"}","v":0}
{"ts":1749695644324.9548,"caller":"cli/run.go:72","msg":"command failed","err":"Get …
```

added json logging support in karmada-agent

---

artifacts/deploy/karmada-scheduler-estimator.yaml
cmd/scheduler-estimator/app/scheduler-estimator.go
cmd/scheduler-estimator/main.go

/kind feature
**Which issue(s) this PR fixes:**
Part of https://github.com/karmada-io/karmada/issues/6230
* New Flags after change:
```text
--log-flush-frequency duration
Maximum number of seconds between log flushes (default 5s)
--log-json-info-buffer-size quantity
[Alpha] In JSON format with split output streams, the info messages can be buffered for a while to increase performance. The default value of zero bytes disables
buffering. The size can be specified as number of bytes (512), multiples of 1000 (1K), multiples of 1024 (2Ki), or powers of those (3M, 4G, 5Mi, 6Gi). Enable …
```

JSON logging support for Karmada scheduler-estimator

---

artifacts/deploy/karmada-scheduler.yaml
cmd/scheduler/app/scheduler.go
cmd/scheduler/main.go

/kind feature
Part of https://github.com/karmada-io/karmada/issues/6230
```release-note
`karmada-scheduler`: Introduced `--logging-format` flag, which can be set to `json` to enable JSON logging.
```

Add json logging support for karmada scheduler

---

artifacts/deploy/karmada-search.yaml
cmd/karmada-search/app/karmada-search.go
cmd/karmada-search/main.go

/kind feature
JSON logging support. More details are highlighted #6230.
Part of #6230 
```
`karmada-search`: Introduced `--logging-format` flag which can be set to `json` to enable JSON logging.
```

JSON logging support for Karmada Search component

---

pkg/controllers/binding/common.go
pkg/controllers/binding/common_test.go
test/e2e/suites/base/federatedresourcequota_test.go
test/e2e/suites/base/scheduling_test.go

/kind bug
We introduced federatedresourcequota enforcement in v1.14 to achieve unified quota management across clusters. This is realized by intercepting modifications to workload requirements and the `spec.clusters` field of resource bindings. However, the federated resource quota mechanism fails when workloads scale up.
The root cause is that the binding controller synchronizes workload modifications to member clusters. When the replicas scheduling policy is set to "duplicated", the binding controller does not revise the workload's replicas according to the scheduling results in `bindingSpec.clusters`. As a result, the scale-up operations of workloads are directly synchronized to member clusters, rendering the …

Fix workload scale up bypass FederatedResourceQuota check issue

---

pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller_test.go

/kind cleanup
As stated in #6467, the workload replicas of member clusters are consistent with `rb.Clusters` rather than `rb.replicas`. Therefore, when the `federated-resource-quota-enforcement-controller` periodically refreshes `overallUsage` based on `rb`, it should only use `rbSpec.clusters` and `rbSpec.ReplicaRequirements` for calculation.
For example, when a Deployment is scaled up and intercepted by the federated resource quota, its `rb` might be:
```yaml
spec:
clusters:
- name: member1
replicas: 2
- name: member2
replicas: 2
replicas: 3
```
- If calculated based on `rbSpec.replicas`, the total replicas = 3 * len(clusters) = 6  
- If calculated based on `rbSpec.clusters`, the total replicas = 2 + 2 = 4  
The two …

Use rbSpec.clusters and rbSpec.ReplicaRequirements to calculate rb' resource usage

---

pkg/controllers/binding/common.go
pkg/controllers/binding/common_test.go
test/e2e/framework/deployment.go
test/e2e/suites/base/federatedresourcequota_test.go
test/e2e/suites/base/scheduling_test.go

Cherry pick of #6474 on release-1.14.
#6474: fix the issue where federatedresourcequota becomes invalid
```release-note
`karmada-controller-manager`: Fixed the issue that a workload propagated with `duplicated mode` can bypass quota checks during scale up.
```

Automated cherry pick of #6474: fix the issue where federatedresourcequota becomes invalid

---

pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller.go
pkg/controllers/federatedresourcequota/federated_resource_quota_enforcement_controller_test.go

Cherry pick of #6477 on release-1.14.
#6477: use rbSpec.clusters and rbSpec.ReplicaRequirements to
```release-note
`karmada-controller-manager`: Fixed the issue where the federated-resource-quota-enforcement-controller miscalculates quota usage.
```

Automated cherry pick of #6477: use rbSpec.clusters and rbSpec.ReplicaRequirements to

---

pkg/scheduler/framework/plugins/apienablement/api_enablement.go
pkg/scheduler/framework/plugins/apienablement/api_enablement_test.go

/kind bug
Modifies the `APIEnablement` plugin to never delete scheduled resources, even if their API (CRD) is temporarily unavailable. This prevents resource deletion when users accidentally delete and reinstall CRDs in member clusters.
Fixes #6461 
**Special notes for your reviewer**: NA
```release-note
NONE
```

fix: ensure APIEnablement plugin never deletes scheduled resources

---

charts/karmada/templates/karmada-search.yaml

/kind bug
Update Karmada search helm chart template to use `search.resources` for deployment resources. It originally uses the `apiServer.resource`.
Fixes #
```release-note
`karmada-search`: karmada-search helm chart template now references the resources from `search.resources`.
```

fix: Update Karmada search template to use search.resources for resources

---

.gemini/config.yaml

/kind feature
https://github.com/marketplace/gemini-code-assist
Fixes #
```release-note
```

CI: add Gemini assist for code reviews

---

pkg/controllers/status/work_status_controller.go
pkg/controllers/status/work_status_controller_test.go

/kind bug
ref #6510
Fixes #6510
```release-note
`karmada-controller-manager`: Fixed the issue that resources will be recreated after deleted on the cluster when resource is suspended for dispatching
```

Fixed the issue that resources will be recreated after deleted on the cluster when resource is suspended for dispatching

---

pkg/controllers/status/work_status_controller.go
pkg/controllers/status/work_status_controller_test.go

Cherry pick of #6525 on release-1.14.
#6525: don't recreate resource in the member cluster when it is
```release-note
`karmada-controller-manager`: Fixed the issue that resources will be recreated after being deleted on the cluster when resource is suspended for dispatching
```

Automated cherry pick of #6525: don't recreate resource in the member cluster when it is

---

.github/workflows/installation-chart.yaml

/kind flake
Fix #6547 
Fixes #
```release-note
none
```

Fix the rate-limit issue of kustomize action

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/controllers/ctrlutil/work.go
pkg/controllers/ctrlutil/work_test.go
pkg/controllers/execution/execution_controller.go
pkg/controllers/status/work_status_controller.go
pkg/controllers/status/work_status_controller_test.go
pkg/util/constants.go
pkg/util/helper/predicate.go
pkg/util/helper/predicate_test.go

ref #6437 
Fixes #6437
```release-note
`Deprecation`: The deprecated label `propagation.karmada.io/instruction`, which was designed to suspend Work propagation, has now been removed.
```

Delete the propagation.karmada.io/instruction label

---

.github/workflows/ci-schedule-compatibility.yaml
.github/workflows/ci-schedule.yml
.github/workflows/ci.yml
.github/workflows/installation-chart.yaml
.github/workflows/installation-cli.yaml
.github/workflows/installation-operator.yaml

/kind cleanup
Update Kubernetes versions in CI workflows to include test against k8s v1.33.0.
Part of #6489
```release-note
CI Dependencies: Include Kubernetes v1.33 and remove version v1.24.
```

Update Kubernetes versions in CI workflows to include v1.33.0

---

charts/karmada-operator/crds/operator.karmada.io_karmadas.yaml
charts/karmada/_crds/bases/apps/apps.karmada.io_workloadrebalancers.yaml
charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_cronfederatedhpas.yaml
charts/karmada/_crds/bases/autoscaling/autoscaling.karmada.io_federatedhpas.yaml
charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpretercustomizations.yaml
charts/karmada/_crds/bases/config/config.karmada.io_resourceinterpreterwebhookconfigurations.yaml
charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusteringresses.yaml
charts/karmada/_crds/bases/networking/networking.karmada.io_multiclusterservices.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_clusteroverridepolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_clusterpropagationpolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_clustertaintpolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_federatedresourcequotas.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_overridepolicies.yaml
charts/karmada/_crds/bases/policy/policy.karmada.io_propagationpolicies.yaml
charts/karmada/_crds/bases/remedy/remedy.karmada.io_remedies.yaml
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_works.yaml
examples/customresourceinterpreter/apis/workload.example.io_workloads.yaml
hack/update-crdgen.sh
operator/config/crds/operator.karmada.io_karmadas.yaml

/kind cleanup
Bump controller-gen version to v0.18.0 to include k8s 1.33.
Part of #6489
```release-note
Dependencies: Upgraded controller-gen to v0.18.0.
```

Bump controller-gen version to v0.18.0

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/customizations_tests.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/testdata/desired-sidecarset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/testdata/observed-sidecarset-nginx.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/SidecarSet/testdata/status-file.yaml

/kind feature
Adds resource interpreter customization for OpenKruise SidecarSet, enabling Karmada to properly manage SidecarSet resources in multi-cluster environments. This includes:
- Status aggregation across member clusters
- Health checks for SidecarSet resources
- Dependency interpretation for ConfigMaps and Secrets
- Comprehensive test coverage
- Includes test cases for multi-cluster scenarios
- Verified with `karmadactl interpret` command
- Follows the same pattern as other resource interpreter customizations
```release-note
feat: Add resource interpreter support for OpenKruise SidecarSet
Adds …
```

feat: add resource interpreter customization for SidecarSet

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/customizations.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/customizations_tests.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/testdata/desired-uniteddeployment.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/testdata/observed-uniteddeployment.yaml
pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/UnitedDeployment/testdata/status-file.yaml

/kind feature
Adds resource interpreter customization for OpenKruise UnitedDeployment, enabling Karmada to properly manage UnitedDeployment resources in multi-cluster environments. This PR introduces:
- Status aggregation logic for UnitedDeployment across member clusters
- Health interpretation for UnitedDeployment resources
- Dependency extraction for ConfigMaps and Secrets referenced in the pod template
- Lua scripts for all required interpreter hooks (replica, status, health, dependency, etc.)
- Test data and validation using `karmadactl interpret` to ensure correct behavior
- The customization follows the established pattern for resource interpreter customizations in Karmada
- All interpreter …

feat: add resource interpreter customization for UnitedDeployment

---

pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_dispatch_controller.go
pkg/controllers/multiclusterservice/mcs_controller.go

Fixes #
Partof https://github.com/karmada-io/karmada/issues/6230
NONE

JSON logging for multiclusterservice controllers

---

pkg/controllers/mcs/service_export_controller.go

/kind bug
When the `karmada-controller-manager` is restarted, the `servcie-export-controller` will requeue the ServiceExport associated with the collected EndpointSlice resources for processing:
https://github.com/karmada-io/karmada/blob/bd5692f08a259c1a959dc3fd1944071be9fda729/pkg/controllers/mcs/service_export_controller.go#L149-L159
Then, during the processing, the EndpointSlice resource is obtained from the cluster cache:
https://github.com/karmada-io/karmada/blob/bd5692f08a259c1a959dc3fd1944071be9fda729/pkg/controllers/mcs/service_export_controller.go#L399-L421
The cache may not have been synchronized at this time, and an empty EndpointSlice list will be obtained, which will be deleted in the `removeOrphanWork` …

Ensure EndpointSlice informer cache is synced before reporting EndpointSlice

---

pkg/controllers/mcs/service_export_controller.go

Cherry pick of #6434 on release-1.13.
#6434: wait for EndpointSlice informer synced when report
```release-note
`karmada-controller-manager`: Fixed the issue that EndpointSlice are deleted unexpectedly due to the EndpointSlice informer cache not being synced
```

Automated cherry pick of #6434: wait for EndpointSlice informer synced when report

---

pkg/controllers/gracefuleviction/crb_graceful_eviction_controller.go
pkg/controllers/gracefuleviction/rb_graceful_eviction_controller.go

Add one of the following kinds:
/kind cleanup
Structured logging support
Partially Fix #6230
```release-note
NONE
```

refactor(app): improve logging in graceful eviction controllers

---

pkg/controllers/applicationfailover/common.go
pkg/controllers/applicationfailover/crb_application_failover_controller.go
pkg/controllers/applicationfailover/rb_application_failover_controller.go

structured logging support. More details are highlighted in
https://github.com/karmada-io/karmada/pull/6440 and
https://github.com/karmada-io/karmada/issues/6230
Fixes #
```release-note
NONE
```

application failover klog structured logging 

---

charts/karmada-operator/templates/karmada-operator-deployment.yaml
charts/karmada-operator/values.yaml

/kind feature
This PR adds support for injecting arbitrary environment variables (e.g., http proxy env vars)  into the Karmada Operator deployment.
It also adds supports for specifying extra arguments (e.g., `--log-format=json`) for the operator binary.
Fixes #
```release-note
`Helm chart`: Karmada Operator chart now possible to set environment variables and extra arguments for the Karmada operator deployment.
```

Add support for specifying env vars and extra args for the Karmada operator

---

pkg/controllers/mcs/endpointslice_controller.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/mcs/service_import_controller.go

Fixes #
Partof https://github.com/karmada-io/karmada/issues/6230
NONE

refactor: enable JSON logging in mcs controller

---

pkg/apis/work/v1alpha2/binding_types.go
pkg/scheduler/helper.go
pkg/util/constants.go
pkg/webhook/resourcebinding/validating.go
pkg/webhook/resourcebinding/validating_test.go

/kind feature
In case quota is exceeded, it would be helpful to notify Karmada users as to what is happening. This short PR improves the deny message verbosity of our validation webhook and adds this message as a condition to the ResourceBinding spec. 
Example:
```
status:
conditions:
- lastTransitionTime: "2025-06-22T14:43:55Z"
message: 'admission webhook "resourcebinding.karmada.io" denied the request: FederatedResourceQuota(test-namespace/federated-quota)
exceeded for resource cpu: requested sum 6, limit 4.'
reason: QuotaExceeded
status: "False"
type: Scheduled
```
Part of #6350 
```release-note
`karmada-scheduler`: Added …
```

Add quota exceeded conditions in case scheduler fails to update resourcebinding

---

pkg/controllers/ctrlutil/work.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller_test.go
pkg/util/finalizer.go
pkg/util/finalizer_test.go

/kind bug
ref https://github.com/karmada-io/karmada/issues/6616#issuecomment-3173153743
Fixes #6616
```release-note
`karmada-controller-manager`: Fixed the issue that endpointslice and work resources residuce when using MCS and MCI simultaneously and then deleting them.
```

When using MCS and MCI simultaneously, prevent resource residuce caused by deleting MCS and MCI

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/resourceinterpreter/customized/declarative/configmanager/manager.go
pkg/resourceinterpreter/customized/webhook/configmanager/manager.go
pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go
pkg/resourceinterpreter/customized/webhook/customized.go
pkg/resourceinterpreter/customized/webhook/customized_test.go
pkg/resourceinterpreter/interpreter.go
pkg/util/constants.go

/kind bug
ref #6600 
Part of #6600
```release-note
`karmada-controller-manager`: Fixed the issue that ensures resource interpreter cache sync before starting controllers
```

ensure resource interpreter cache sync before starting controllers

---

pkg/controllers/ctrlutil/work.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller_test.go
pkg/util/finalizer.go
pkg/util/finalizer_test.go

Cherry pick of #6622 on release-1.14.
#6622: merge EndpointSlice Work finalizers instead of overwriting it
```release-note
`karmada-controller-manager`: Fixed the issue that endpointslice and work resources residuce when using MCS and MCI simultaneously and then deleting them.
```

Automated cherry pick of #6622: When using MCS and MCI simultaneously, prevent resource residuce caused by deleting MCS and MCI

---

pkg/detector/detector.go
pkg/detector/policy.go
pkg/util/helper/binding.go

Cherry pick of #6544 on release-1.12.
#6544: detector: eliminate the mutation of the informer cache
```release-note
`karmada-controller-manager`: Fixed the issue that the informer cache gets unexpectedly modified during usage,
```

Automated cherry pick of #6544: detector: eliminate the mutation of the informer cache

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/resourceinterpreter/customized/declarative/configmanager/manager.go
pkg/resourceinterpreter/customized/declarative/configmanager/manager_test.go
pkg/resourceinterpreter/customized/webhook/configmanager/manager.go
pkg/resourceinterpreter/customized/webhook/configmanager/manager_test.go
pkg/resourceinterpreter/customized/webhook/customized.go
pkg/resourceinterpreter/customized/webhook/customized_test.go
pkg/resourceinterpreter/interpreter.go
pkg/util/constants.go

Cherry pick of #6602 #6612 #6626 on release-1.14.
#6602: Fixed an issue where the ConfigurableInterpreter could report as synced before its underlying informer cache was fully synchronized, preventing potential out-of-sync errors during startup.
#6612:  Fixed an issue where the HookInterpreter could report as synced before its underlying informer cache was fully synchronized, preventing potential out-of-sync errors during startup.
#6626: Fixed the issue that ensures resource interpreter cache sync before starting controllers.
```release-note
`karmada-controller-manager`: Fixed an issue where the ResourceInterpreter could report as synced before its underlying …
```

Automated cherry pick of  #6602 #6612 #6626 on release-1.14

---

pkg/karmadactl/create/create.go
pkg/karmadactl/explain/explain.go

/kind cleanup
Non-formatted strings are passed into `fmt.Sprintf()`, causing fmt errors in generated karmadactl docs (see https://github.com/karmada-io/website/pull/876/files). 
Fixes #
```release-note
```

fix formatted strings

---

cmd/agent/app/agent.go
cmd/controller-manager/app/controllermanager.go
pkg/features/features.go

/kind feature
This PR introduces a new feature gate `ControllerPriorityQueue` for controller-runtime based controllers in karmada-controller-manager and karmada-agent.
With this feature enabled, controllers give higher priority to recent cluster changes and postpone processing less urgent items in the queue. This significantly improves responsiveness during startup, as controllers can quickly catch up with the latest 
state and reduce the visible backlog from the user’s perspective.
However, enabling this feature may lead to an increase in reconciliation frequency, as newer events spend less time in the queue and therefore have fewer opportunities to be deduplicated. Additionally, within controller-runtime, this feature …

feat: introduce ControllerPriorityQueue feature gate

---

pkg/karmadactl/promote/promote.go

/kind bug
After creating the ResourceInterpreterWebhookConfiguration and ResourceInterpreterCustomization resources informer, then call `start` and `WaitForCacheSync` for the informer, thus, ensuring that the cache is synchronized before invoking the resource interpreter.
Part of #6600
```release-note
`karmadactl`: Fixed the issue of `promote` command that the interpreter cache is out of sync before first use.
```

Fix the issue that the cache is out of sync within the resource interpreter when using karmadactl promote

---

pkg/controllers/mcs/endpointslice_controller.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/util/constants.go
pkg/util/helper/mcs.go
pkg/util/helper/mcs_test.go

/kind bug
ref #6522
Fixes #6522
```release-note
`karmada-controller-manager`: Fixed the issue that reporting repeat EndpointSlice resources leads to duplicate backend IPs
```

Fixed the issue that reporting repeat EndpointSlice resources leads to duplicate backend IPs

---

pkg/detector/detector.go
pkg/detector/policy.go
pkg/util/selector.go
pkg/util/selector_test.go

/kind bug
Fixed the issue where pp-related claimMetadata was not properly cleaned up
Fixes #6513
```release-note
`karmada-controller-manager`: Fixed the issue where pp-related claimMetadata was not properly cleaned up when deleting propagationpolicy with Lazy activationPreference.
```

fixed the issue where pp-related claimMetadata was not properly cleaned up

---

pkg/scheduler/core/assignment.go
pkg/scheduler/core/assignment_test.go
pkg/scheduler/core/common.go
pkg/scheduler/core/common_test.go
pkg/scheduler/core/division_algorithm.go
pkg/scheduler/core/generic_scheduler.go
pkg/scheduler/core/generic_scheduler_test.go
pkg/scheduler/core/spreadconstraint/group_clusters.go
pkg/scheduler/core/spreadconstraint/select_clusters.go
pkg/scheduler/core/spreadconstraint/select_clusters_by_cluster.go
pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go
pkg/scheduler/core/spreadconstraint/select_clusters_by_region_test.go
pkg/scheduler/core/spreadconstraint/select_clusters_test.go
pkg/scheduler/core/util.go
pkg/scheduler/core/util_test.go

/kind feature
-->
The PR 
related to issue #5202 
```release-note
`karmada-scheduler`: Optimized the scheduler step,  invoking calculate `availableRelicas` is reduced to once, improving the performance.
```

Improve the performance of karmada-scheduler

---

pkg/controllers/mcs/endpointslice_controller.go
pkg/controllers/mcs/service_export_controller.go
pkg/controllers/multiclusterservice/endpointslice_collect_controller.go
pkg/util/constants.go
pkg/util/helper/mcs.go
pkg/util/helper/mcs_test.go

Cherry pick of #6523 on release-1.12.
#6523: Exclude EndpointSlice resources managed by Karmada system to
```release-note
`karmada-controller-manager`: Fixed the issue that reporting repeat EndpointSlice resources leads to duplicate backend IPs
```

Automated cherry pick of #6523: Exclude EndpointSlice resources managed by Karmada system to avoid duplicate reporting

---

pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/flink.apache.org/v1beta1/FlinkDeployment/customizations.yaml

/kind feature
Adds GetComponents to the FlinkDeployment custom interpreter. 
Will keep the original GetReplicas method for now until we can test out the GetComponents feature a bit more.
Part of #6641
```release-note
Implements getComponents for FlinkDeployment custom interpreter
```

Adding componentResource calculation for FlinkDeployment

---

docs/proposals/failover/stateful-workload-cluster-failover.md

/kind feature
Support cluster failover for stateful workloads.
Fixes #
```release-note
NONE
```

[Proposal] Support cluster failover for stateful workloads

---

pkg/detector/detector.go
pkg/detector/detector_test.go
pkg/detector/policy.go

/kind bug
In lazy mode, the processor needs to differentiate if the enqueue is caused by Karmada to take different handling paths. For non-lazy policies, this distinction is unnecessary.
Note: toggling ResourceChangeByKarmada changes the effective queue key. Mixing both true/false for the same resource may lead to two different QueueKeys enqueued and processed concurrently, causing race conditions. Therefore, set ResourceChangeByKarmada only in lazy mode.
Fixes #5996
Fixes #6379 
Fixes #6322
```release-note
`karmada-controller-manager`: Fixed the issue that the relevant fields in rb and pp are …
```

fix the issue that the relevant fields in rb and pp are inconsistent

---

pkg/detector/detector.go
pkg/detector/policy.go
pkg/util/selector.go
pkg/util/selector_test.go

Cherry pick of #6656 on release-1.13.
#6656: fixed the issue where pp-related claimMetadata was not
```release-note
`karmada-controller-manager`: Fixed the issue where pp-related claimMetadata was not properly cleaned up when deleting propagationpolicy with Lazy activationPreference.
```

Automated cherry pick of #6656: fixed the issue where pp-related claimMetadata was not

---

pkg/controllers/binding/binding_controller.go
pkg/controllers/binding/cluster_resource_binding_controller.go
pkg/controllers/binding/common.go
pkg/util/helper/binding.go
pkg/util/helper/binding_test.go

/kind feature
Support cluster failover for stateful workloads, ref https://github.com/karmada-io/karmada/pull/6495.
Part of https://github.com/karmada-io/karmada/issues/6593
```release-note
NONE
```

Ensure in directly purgeMode: resources removed from old cluster before being created in new cluster

---

api/openapi-spec/swagger.json
charts/karmada/_crds/bases/work/work.karmada.io_clusterresourcebindings.yaml
charts/karmada/_crds/bases/work/work.karmada.io_resourcebindings.yaml
pkg/apis/work/v1alpha2/binding_types.go
pkg/generated/openapi/zz_generated.openapi.go
pkg/webhook/resourcebinding/validating.go
pkg/webhook/resourcebinding/validating_test.go

/kind feature
This PR adds that enforces the name's presence and ensures the uniqueness of the component name when there are multiple components.
Part of #6641 
```release-note
NONE
```

added validation check for the components section of resourcebinding

---

pkg/detector/detector.go
pkg/util/binding.go
pkg/util/binding_test.go
test/e2e/suites/base/propagationpolicy_test.go

/kind bug
ref to https://github.com/karmada-io/karmada/issues/6660#issuecomment-3232352171
Fixes #6660
```release-note
`karmada-controller-manager`: Fixed the issue that the binding's suspension persists when the policy deletes the suspension configuration.
```

fix the issue that the binding's suspension persists when the policy deletes the suspension configuration

---

pkg/detector/detector.go
pkg/util/binding.go
pkg/util/binding_test.go
test/e2e/suites/base/propagationpolicy_test.go

Cherry pick of #6707 on release-1.13.
#6707: fix the issue that the binding's suspension persists when the
```release-note
`karmada-controller-manager`: Fixed the issue that the binding's suspension persists when the policy deletes the suspension configuration.
```

Automated cherry pick of #6707: fix the issue that the binding's suspension persists when the

---

pkg/detector/detector.go
pkg/detector/detector_test.go
pkg/detector/policy.go

Cherry pick of #6674 on release-1.14.
#6674: fix the issue that the relevant fields in rb and pp are
```release-note
`karmada-controller-manager`: Fixed the issue that the relevant fields in rb and pp are inconsistent.
```

Automated cherry pick of #6674: fix the issue that the relevant fields in rb and pp are

---

pkg/controllers/mcs/service_export_controller.go
pkg/controllers/mcs/service_export_controller_test.go
pkg/util/fedinformer/genericmanager/testing/fake.go

/kind flake
Part of #6582
```release-note
NONE
```

Add UT for service-export-controller

---

pkg/detector/detector.go

/kind bug
When the feature gate `MultiplePodTemplatesScheduling` is enabled, and a FlinkDeployment along with a matching policy is deployed, the generated binding can correctly record the resource information of each template.
```yaml
spec:
jobManager:
replicas: 1
resource:
cpu: 1
memory: 2048m
serviceAccount: flink
taskManager:
resource:
cpu: 1
memory: 2048m
---
spec:
components:
- name: jobmanager
replicaRequirements:
resourceRequest:
cpu: "1"
memory: "2.048"
replicas: 1
- name: taskmanager
replicaRequirements:
resourceRequest:
cpu: "1"
memory: "2.048"
replicas: 1
```
However, when modifying the resource requests of the FlinkDeployment, the `spec.components` in the binding will not change accordingly.
```yaml
spec: …
```

fix the issue that rbSpec.Components is not updated when the template is updated

---

README.md

/kind cleanup
Update Kuberentes compatibility table: adding v1.15 and removing EOL v1.12.
Part of #6724
```release-note
NONE
```

Update Kubernetes compatibility: add v1.15 and remove v1.12

---

hack/util.sh

/kind cleanup
Consistent with the node image default used by kind v0.29.0
https://github.com/kubernetes-sigs/kind/releases
```md
The default node image is now 
kindest/node:v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f
```
Fixes #
```release-note
```

update default node image to v1.33.1

---

pkg/apis/config/v1alpha1/interpretercontext_types.go
pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
pkg/generated/openapi/zz_generated.openapi.go

/kind feature
This PR introduces multiple components to support the webhook interpreter.
Part of #6734
```release-note
`API Change`: Introduced `Components` field to `ResourceInterpreterContext` in the `ResourceInterpreterResponse` to support interpreting components for webhook interpreter. 
```

Introduce components field to webhook interpreter response

---

pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go
pkg/resourceinterpreter/customized/declarative/luavm/lua_convert_test.go

/kind bug
Ref to https://github.com/karmada-io/karmada/issues/6747#issuecomment-3283308945, we should escape the dot and colon characters when convert the lua result.
Fixes #6747
We should backport this to release1.13, release1.14 and release1.15.
```release-note
`ResourceInterpreter`: Fixed the issue that when an object API field name contains dots or colons, it would cause the resource interpreter to fail.
```

escape the dot and colon characters when convert the lua result

---

api/openapi-spec/swagger.json
operator/pkg/apis/operator/v1alpha1/type.go
pkg/apis/networking/v1alpha1/service_types.go
pkg/apis/policy/v1alpha1/override_types.go
pkg/apis/search/searchregistry_types.go
pkg/apis/search/v1alpha1/searchregistry_types.go
pkg/generated/openapi/zz_generated.openapi.go

As refered in issue #6750, fix the issue that omitempty tag is not consistent with required mark in operator api definitions
Fixes #6750

fix the issue that omitempty json tag is not consistent with required mark

---

pkg/resourceinterpreter/customized/declarative/luavm/lua_convert.go
pkg/resourceinterpreter/customized/declarative/luavm/lua_convert_test.go

Cherry pick of #6749 on release-1.15.
#6749: escape the dot and colon characters when convert the lua
```release-note
ResourceInterpreter: Fixed the issue that when an object API field name contains dots or colons, it would cause the resource interpreter to fail.
```
Related issue:
https://github.com/karmada-io/karmada/issues/6762#event-19821720136

Automated cherry pick of #6749: escape the dot and colon characters when convert the lua

---

operator/pkg/tasks/init/karmadaresource.go
operator/pkg/util/apiclient/idempotency.go

/kind bug
When I upgrade a Karmada instance managed by the operator, if a CRD has changed, then I expect that CRD to be updated in the Karmada API server accordingly. Currently, the operator will try to create a CRD and if that fails because the CRD already exist, then it will just skip applying it.
Fixes #6776
```release-note
NONE
```

Make sure CRDs are updated on upgrades

---

pkg/controllers/cluster/taint_manager.go
pkg/controllers/cluster/taint_manager_test.go
pkg/util/helper/taint.go
pkg/util/helper/taint_test.go

/kind cleanup
https://github.com/karmada-io/karmada/actions/runs/17933081090/job/50994164390
The test TestNoExecuteTaintManager_needEviction/taint_tolerated_with_positive_toleration_seconds_-_wait_for_toleration_time was experiencing intermittent failures due to timing issues. The test expected a specific toleration time (e.g., 59s) but got slightly different values (e.g., 57.995129913s) because of the time elapsed between different time.Now() calls during test execution.
**Root Cause**
The GetMinTolerationTime function used time.Now() and time.Until() internally, which introduced non-deterministic timing behavior in tests. When taints had TimeAdded values and tolerations had TolerationSeconds, the calculated remaining …

Fix flaky test failures in taint manager due to time differences

---

pkg/karmadactl/explain/explain.go

/kind cleanup
Recently, the Karmada website has been preparing to upgrade Docusaurus from v2 to v3, which includes upgrading the MDX dependency to v3. As a result, some Markdown documents that previously compiled successfully under Docusaurus v2 may now fail to build under Docusaurus v3.
One such example is:\
https://github.com/karmada-io/website/blob/e222688eb46703f179db40fabe3a2040a59210a1/docs/reference/karmadactl/karmadactl-commands/karmadactl\_explain.md?plain=1#L13
The build error is:
<pre style="background: none"><code class="language-bash" data-language="bash" identifier="26cc901d931846e5a4fee12de5155f33-0" index="0" total="1">Error while compiling file docs/reference/karmadactl/karmadactl-commands/karmadactl_expl …

update explain cmd long message

---

pkg/estimator/client/accurate.go
pkg/estimator/client/general.go
pkg/estimator/client/interface.go

/kind feature
Introduces a new method `MaxAvailableComponentSets` which will return a list of TargetClusters, where the replica # will correspond to the total number of component sets for multiple-component CRDs. 
I decided to add the new method as a part of a separate interface called `ComponentSetEstimator`. This was done because if you add the `MaxAvailableComponentSets`, all downstream implementers of `ReplicaEstimator` will expect an implementation of `MaxAvailableComponentSets`. 
By adding a separate extended interface, other estimators (such as GeneralEstimator) can keep their implementations of ReplicaEstimator, and only estimators that support multi-component workloads will implement ComponentSetEstimator. …

Adding maxAvailableComponentSets to estimator interface
